{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mptransitagency-swift.class\/phone"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mptransitagency-swift.class\/phone"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTransitAgency-swift.class\/phone","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Phone contains the phone number of the transit agency."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"phone","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPTransitAgency(py)phone","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"phone"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTransitAgency-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPTransitAgency-swift.class":{"role":"symbol","title":"MPTransitAgency","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPTransitAgency"}],"abstract":[{"type":"text","text":"Transit agency information."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTransitAgency-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPTransitAgency"}],"url":"\/documentation\/mapsindoors\/mptransitagency-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPTransitAgency-swift.class/phone":{"role":"symbol","title":"phone","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Phone contains the phone number of the transit agency."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTransitAgency-swift.class\/phone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"phone"}],"url":"\/documentation\/mapsindoors\/mptransitagency-swift.class\/phone"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"phone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"phone"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString<Optional>","preciseIdentifier":"c:Q$objc(cs)NSStringobjc(pl)Optional"},{"kind":"text","text":" *"},{"kind":"identifier","text":"phone"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTransitAgency-swift.class\/title","value":"MPTransitAgency"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTransitAgency-swift.class\/fragments","value":[{"kind":"identifier","text":"MPTransitAgency"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTransitAgency-swift.class~1phone\/title","value":"phone"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTransitAgency-swift.class~1phone\/fragments","value":[{"kind":"identifier","text":"phone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}