{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"containsCoordinate","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"coordinate"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"ignorePolygonHoles","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]},{"kind":"parameters","parameters":[{"name":"coordinate","content":[{"inlineContent":[{"text":"Coordinate to check for containment.","type":"text"}],"type":"paragraph"}]},{"name":"ignorePolygonHoles","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Should holes in a polygon be ignored"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"text":"True if the coordinate is inside the polygon boundary AND outside any holes in the polygon. False if the coordinate is outside the polygon, or inside any holes in the polygon.","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"MapsIndoors"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"containsCoordinate:ignorePolygonHoles:","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPPolygonGeometry(im)containsCoordinate:ignorePolygonHoles:","title":"containsCoordinate(_:ignorePolygonHoles:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"containsCoordinate","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"},{"kind":"text","text":", "},{"text":"ignorePolygonHoles","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol"},"kind":"symbol","abstract":[{"type":"text","text":"Check if the given coordinate is contained within the polygon."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/containsCoordinate(_:ignorePolygonHoles:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mppolygongeometry\/containscoordinate(_:ignorepolygonholes:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mppolygongeometry\/containscoordinate(_:ignorepolygonholes:)"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPolygonGeometry/containsCoordinate(_:ignorePolygonHoles:)":{"kind":"symbol","title":"containsCoordinate(_:ignorePolygonHoles:)","abstract":[{"text":"Check if the given coordinate is contained within the polygon.","type":"text"}],"url":"\/documentation\/mapsindoors\/mppolygongeometry\/containscoordinate(_:ignorepolygonholes:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"containsCoordinate"},{"kind":"text","text":"("},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ignorePolygonHoles","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"containsCoordinate:ignorePolygonHoles:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/containsCoordinate(_:ignorePolygonHoles:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPolygonGeometry":{"kind":"symbol","title":"MPPolygonGeometry","abstract":[],"url":"\/documentation\/mapsindoors\/mppolygongeometry","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPPolygonGeometry","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPPolygonGeometry"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry"},"MapsPeopleWhite.png":{"alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","type":"image"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"containsCoordinate:ignorePolygonHoles:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"containsCoordinate:ignorePolygonHoles:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"containsCoordinate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"coordinate"},{"text":" ","kind":"text"},{"text":"ignorePolygonHoles:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"ignorePolygonHoles"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1containsCoordinate(_:ignorePolygonHoles:)\/title","value":"containsCoordinate:ignorePolygonHoles:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1containsCoordinate(_:ignorePolygonHoles:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"containsCoordinate:ignorePolygonHoles:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPolygonGeometry\/title","value":"MPPolygonGeometry","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPolygonGeometry\/fragments","op":"replace","value":[{"text":"MPPolygonGeometry","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}