{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"containsPoint"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"point"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint","text":"MPPoint","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"point","content":[{"type":"paragraph","inlineContent":[{"text":"Point to check for containment.","type":"text"}]}]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"True if the point is inside the polygon boundary AND outside any holes in the polygon. False if the point is outside the polygon, or inside any holes in the polygon."}],"type":"paragraph"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Method","title":"containsPoint(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"containsPoint"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","kind":"typeIdentifier","text":"MPPoint"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPPolygonGeometry(im)containsPoint:","symbolKind":"method","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"containsPoint:"}]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/containsPoint(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Check if the given point is contained within the polygon."}],"variants":[{"paths":["\/documentation\/mapsindoors\/mppolygongeometry\/containspoint(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mppolygongeometry\/containspoint(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry"]]},"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPoint":{"type":"topic","navigatorTitle":[{"text":"MPPoint","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mppoint","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPPoint","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"MPPoint"},"MapsPeopleWhite.png":{"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPolygonGeometry/containsPoint(_:)":{"type":"topic","role":"symbol","url":"\/documentation\/mapsindoors\/mppolygongeometry\/containspoint(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"containsPoint","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","text":"MPPoint"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/containsPoint(_:)","abstract":[{"type":"text","text":"Check if the given point is contained within the polygon."}],"navigatorTitle":[{"kind":"identifier","text":"containsPoint:"}],"title":"containsPoint(_:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPolygonGeometry":{"navigatorTitle":[{"text":"MPPolygonGeometry","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry","url":"\/documentation\/mapsindoors\/mppolygongeometry","type":"topic","role":"symbol","kind":"symbol","title":"MPPolygonGeometry","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPPolygonGeometry","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"containsPoint:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"containsPoint:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"containsPoint:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","kind":"typeIdentifier","text":"MPPoint"},{"kind":"text","text":" *) "},{"text":"point","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"MPPoint","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPoint\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPoint\/fragments","value":[{"kind":"identifier","text":"MPPoint"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1containsPoint(_:)\/title","value":"containsPoint:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1containsPoint(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"containsPoint:","kind":"identifier"}],"op":"replace"},{"value":"MPPolygonGeometry","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPolygonGeometry\/title"},{"op":"replace","value":[{"text":"MPPolygonGeometry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPolygonGeometry\/fragments"}]}]}