{"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"containsCoordinate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"ignorePolygonHoles","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"containmentMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometryContainmentMetadata","text":"MPGeometryContainmentMetadata"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"modules":[{"name":"MapsIndoors"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPPolygonGeometry(im)containsCoordinate:ignorePolygonHoles:containmentMetadata:","title":"containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)","navigatorTitle":[{"text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:","kind":"identifier"}]},"abstract":[{"type":"text","text":"Check if the given coordinate is contained within the polygon, and optionally return the coordinate closest to the polygon."},{"text":" ","type":"text"},{"type":"text","text":"If the polygon contains the coordinate, ‘coordinate’ is returned as nearestPoint."},{"text":" ","type":"text"},{"type":"text","text":"If coordinate is not contained, the nearest point is calculated."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mppolygongeometry\/containscoordinate(_:ignorepolygonholes:containmentmetadata:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mppolygongeometry\/containscoordinate(_:ignorepolygonholes:containmentmetadata:)"]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"containsCoordinate","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"coordinate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ignorePolygonHoles"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"containmentMetadata"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata","text":"MPGeometryContainmentMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometryContainmentMetadata"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Coordinate to check for containment."}],"type":"paragraph"}],"name":"coordinate"},{"name":"ignorePolygonHoles","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Should holes in a polygon be ignored"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If not nil, the nearest point and distance on the polygon boundary is returned. Note this may be the nearest point on a polygon-hole."}]}],"name":"containmentMetadata"}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"False if the coordinate is outside the polygon, or inside any holes in the polygon."}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)"},"references":{"MapsPeopleWhite.png":{"type":"image","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPolygonGeometry":{"navigatorTitle":[{"text":"MPPolygonGeometry","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry","url":"\/documentation\/mapsindoors\/mppolygongeometry","type":"topic","role":"symbol","kind":"symbol","title":"MPPolygonGeometry","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPPolygonGeometry","kind":"identifier"}],"abstract":[]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryContainmentMetadata":{"type":"topic","role":"symbol","url":"\/documentation\/mapsindoors\/mpgeometrycontainmentmetadata","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPGeometryContainmentMetadata","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata","abstract":[],"navigatorTitle":[{"text":"MPGeometryContainmentMetadata","kind":"identifier"}],"title":"MPGeometryContainmentMetadata"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPolygonGeometry/containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"containsCoordinate"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ignorePolygonHoles"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"containmentMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometryContainmentMetadata","kind":"typeIdentifier","text":"MPGeometryContainmentMetadata"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","title":"containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)","abstract":[{"text":"Check if the given coordinate is contained within the polygon, and optionally return the coordinate closest to the polygon.","type":"text"},{"type":"text","text":" "},{"text":"If the polygon contains the coordinate, ‘coordinate’ is returned as nearestPoint.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If coordinate is not contained, the nearest point is calculated."}],"url":"\/documentation\/mapsindoors\/mppolygongeometry\/containscoordinate(_:ignorepolygonholes:containmentmetadata:)","navigatorTitle":[{"text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"containsCoordinate:ignorePolygonHoles:containmentMetadata:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"containsCoordinate:"},{"kind":"text","text":"("},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":") ","kind":"text"},{"text":"coordinate","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignorePolygonHoles:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"ignorePolygonHoles","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"containmentMetadata:"},{"kind":"text","text":"("},{"text":"MPGeometryContainmentMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometryContainmentMetadata","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata"},{"text":" *) ","kind":"text"},{"text":"containmentMetadata","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MPPolygonGeometry","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPolygonGeometry\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPolygonGeometry\/fragments","op":"replace","value":[{"text":"MPPolygonGeometry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryContainmentMetadata\/title","value":"MPGeometryContainmentMetadata","op":"replace"},{"value":[{"text":"MPGeometryContainmentMetadata","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryContainmentMetadata\/fragments"},{"value":"containsCoordinate:ignorePolygonHoles:containmentMetadata:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:","kind":"identifier"}],"op":"replace"}]}]}