{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gmsPathForPath"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GMSPath","preciseIdentifier":"c:objc(cs)GMSPath"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"GMSPath"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppolygongeometry\/gmspathforpath()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppolygongeometry\/gmspathforpath()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/gmsPathForPath()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get a GMSPath representing the path of the polygon."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gmsPathForPath"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GMSPath","preciseIdentifier":"c:objc(cs)GMSPath"},{"kind":"text","text":"?"}],"title":"gmsPathForPath()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPPolygonGeometry(im)gmsPathForPath","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"gmsPathForPath"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPPolygonGeometry":{"role":"symbol","title":"MPPolygonGeometry","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPolygonGeometry"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPolygonGeometry"}],"url":"\/documentation\/mapsindoors\/mppolygongeometry"},"doc://MapsIndoors/documentation/MapsIndoors/MPPolygonGeometry/gmsPathForPath()":{"role":"symbol","title":"gmsPathForPath()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gmsPathForPath"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GMSPath","preciseIdentifier":"c:objc(cs)GMSPath"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get a GMSPath representing the path of the polygon."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/gmsPathForPath()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gmsPathForPath"}],"url":"\/documentation\/mapsindoors\/mppolygongeometry\/gmspathforpath()"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"gmsPathForPath"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gmsPathForPath"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"GMSPath","preciseIdentifier":"c:objc(cs)GMSPath"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"gmsPathForPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry\/title","value":"MPPolygonGeometry"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry\/fragments","value":[{"kind":"identifier","text":"MPPolygonGeometry"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1gmsPathForPath()\/title","value":"gmsPathForPath"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1gmsPathForPath()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gmsPathForPath"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}