{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"holes"},{"kind":"text","text":": [[["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]]]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppolygongeometry\/holes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppolygongeometry\/holes"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/holes","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Optional array of polygon holes."},{"type":"text","text":" "},{"type":"text","text":"A polygon hole is an array of [longitude, latitude] pairs."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"holes"},{"kind":"text","text":": [[["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]]]?"}],"title":"holes","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPPolygonGeometry(py)holes","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"holes"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPPolygonGeometry":{"role":"symbol","title":"MPPolygonGeometry","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPolygonGeometry"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPolygonGeometry"}],"url":"\/documentation\/mapsindoors\/mppolygongeometry"},"doc://MapsIndoors/documentation/MapsIndoors/MPPolygonGeometry/holes":{"role":"symbol","title":"holes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"holes"},{"kind":"text","text":": [[["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]]]?"}],"abstract":[{"type":"text","text":"Optional array of polygon holes."},{"type":"text","text":" "},{"type":"text","text":"A polygon hole is an array of [longitude, latitude] pairs."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/holes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"holes"}],"url":"\/documentation\/mapsindoors\/mppolygongeometry\/holes"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"holes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"holes"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<NSArray<NSArray<NSNumber *> *> *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"holes"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry\/title","value":"MPPolygonGeometry"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry\/fragments","value":[{"kind":"identifier","text":"MPPolygonGeometry"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1holes\/title","value":"holes"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1holes\/fragments","value":[{"kind":"identifier","text":"holes"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}