{"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`init`"},{"text":"(","kind":"text"},{"text":"dictionary","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]!) ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"MPPolygonGeometry","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPolygonGeometry"}],"title":"init(dictionary:)","externalID":"c:@M@MapsIndoors@objc(cs)MPPolygonGeometry(im)initWithDictionary:error:","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"initWithDictionary:error:","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"`init`","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dictionary"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dict"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!) ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"MPPolygonGeometry","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPolygonGeometry"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"name":"Warning","style":"warning","content":[{"inlineContent":[{"text":"[INTERNAL - DO NOT USE]","type":"text"}],"type":"paragraph"}],"type":"aside"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mppolygongeometry\/init(dictionary:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mppolygongeometry\/init(dictionary:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/init(dictionary:)"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPolygonGeometry/init(dictionary:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/init(dictionary:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"`init`","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dictionary"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!) "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"MPPolygonGeometry","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPolygonGeometry"}],"title":"init(dictionary:)","abstract":[],"url":"\/documentation\/mapsindoors\/mppolygongeometry\/init(dictionary:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:error:"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPolygonGeometry":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPPolygonGeometry","kind":"identifier"}],"navigatorTitle":[{"text":"MPPolygonGeometry","kind":"identifier"}],"type":"topic","title":"MPPolygonGeometry","kind":"symbol","role":"symbol","url":"\/documentation\/mapsindoors\/mppolygongeometry"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithDictionary:error:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithDictionary:error:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPolygonGeometry","text":"MPPolygonGeometry"},{"text":" *) ","kind":"text"},{"text":"initWithDictionary:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dict"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1init(dictionary:)\/title","value":"initWithDictionary:error:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1init(dictionary:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDictionary:error:"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPolygonGeometry\/title","value":"MPPolygonGeometry","op":"replace"},{"value":[{"text":"MPPolygonGeometry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPolygonGeometry\/fragments"}]}]}