{"abstract":[{"type":"text","text":"Will allow markers to overlap, nothing will be removed."}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowOverLap","kind":"identifier"}],"navigatorTitle":[{"text":"MPCollisionHandlingAllowOverLap","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"case","externalID":"c:@M@MapsIndoors@E@MPCollisionHandling@MPCollisionHandlingAllowOverLap","roleHeading":"Case","role":"symbol","title":"MPCollisionHandling.allowOverLap"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/mapsindoors\/mpcollisionhandling\/allowoverlap"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpcollisionhandling\/allowoverlap"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowOverLap","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/allowOverLap"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCollisionHandling/allowOverLap":{"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"allowOverLap","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/allowOverLap","navigatorTitle":[{"text":"MPCollisionHandlingAllowOverLap","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpcollisionhandling\/allowoverlap","kind":"symbol","title":"MPCollisionHandling.allowOverLap","abstract":[{"type":"text","text":"Will allow markers to overlap, nothing will be removed."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCollisionHandling":{"abstract":[{"type":"text","text":"The different ways to handle collisions of icons and labels on the map."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling","url":"\/documentation\/mapsindoors\/mpcollisionhandling","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPCollisionHandling"}],"title":"MPCollisionHandling","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPCollisionHandling"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MPCollisionHandlingAllowOverLap"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"MPCollisionHandlingAllowOverLap","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MPCollisionHandlingAllowOverLap","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling~1allowOverLap\/title","value":"MPCollisionHandlingAllowOverLap"},{"value":[{"text":"MPCollisionHandlingAllowOverLap","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling~1allowOverLap\/fragments","op":"replace"},{"value":"MPCollisionHandling","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling\/title","op":"replace"},{"value":[{"text":"MPCollisionHandling","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}