{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/removeIconAndLabel","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpcollisionhandling\/removeiconandlabel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpcollisionhandling\/removeiconandlabel"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeIconAndLabel"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Will hide markers if they are overlapping with another marker."}],"metadata":{"title":"MPCollisionHandling.removeIconAndLabel","modules":[{"name":"MapsIndoors"}],"symbolKind":"case","externalID":"c:@M@MapsIndoors@E@MPCollisionHandling@MPCollisionHandlingRemoveIconAndLabel","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"removeIconAndLabel","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"MPCollisionHandlingRemoveIconAndLabel","kind":"identifier"}],"role":"symbol"},"references":{"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"identifier":"MapsPeopleWhite.png","type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCollisionHandling/removeIconAndLabel":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeIconAndLabel","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpcollisionhandling\/removeiconandlabel","abstract":[{"type":"text","text":"Will hide markers if they are overlapping with another marker."}],"title":"MPCollisionHandling.removeIconAndLabel","navigatorTitle":[{"kind":"identifier","text":"MPCollisionHandlingRemoveIconAndLabel"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/removeIconAndLabel","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCollisionHandling":{"role":"symbol","navigatorTitle":[{"text":"MPCollisionHandling","kind":"identifier"}],"title":"MPCollisionHandling","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling","url":"\/documentation\/mapsindoors\/mpcollisionhandling","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPCollisionHandling","kind":"identifier"}],"abstract":[{"text":"The different ways to handle collisions of icons and labels on the map.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MPCollisionHandlingRemoveIconAndLabel"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MPCollisionHandlingRemoveIconAndLabel","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MPCollisionHandlingRemoveIconAndLabel"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MPCollisionHandlingRemoveIconAndLabel","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling~1removeIconAndLabel\/title"},{"value":[{"text":"MPCollisionHandlingRemoveIconAndLabel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling~1removeIconAndLabel\/fragments"},{"value":"MPCollisionHandling","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling\/fragments","value":[{"text":"MPCollisionHandling","kind":"identifier"}]}]}]}