{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/removeIconFirst","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpcollisionhandling\/removeiconfirst"]},{"paths":["\/documentation\/mapsindoors\/mpcollisionhandling\/removeiconfirst"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Will hide icons if they are overlapping with another feature such as an icon or another label."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeIconFirst","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"MPCollisionHandlingRemoveIconFirst","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"title":"MPCollisionHandling.removeIconFirst","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"removeIconFirst","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@E@MPCollisionHandling@MPCollisionHandlingRemoveIconFirst","roleHeading":"Case"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCollisionHandling":{"role":"symbol","navigatorTitle":[{"text":"MPCollisionHandling","kind":"identifier"}],"title":"MPCollisionHandling","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling","url":"\/documentation\/mapsindoors\/mpcollisionhandling","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPCollisionHandling","kind":"identifier"}],"abstract":[{"text":"The different ways to handle collisions of icons and labels on the map.","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCollisionHandling/removeIconFirst":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"removeIconFirst","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpcollisionhandling\/removeiconfirst","abstract":[{"type":"text","text":"Will hide icons if they are overlapping with another feature such as an icon or another label."}],"title":"MPCollisionHandling.removeIconFirst","navigatorTitle":[{"text":"MPCollisionHandlingRemoveIconFirst","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/removeIconFirst","type":"topic"},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"identifier":"MapsPeopleWhite.png","type":"image"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MPCollisionHandlingRemoveIconFirst"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MPCollisionHandlingRemoveIconFirst","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MPCollisionHandlingRemoveIconFirst"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling\/title","value":"MPCollisionHandling"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling\/fragments","op":"replace","value":[{"text":"MPCollisionHandling","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling~1removeIconFirst\/title","value":"MPCollisionHandlingRemoveIconFirst"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling~1removeIconFirst\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPCollisionHandlingRemoveIconFirst"}]}]}]}