{"sections":[],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/removeLabelFirst","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeLabelFirst","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpcollisionhandling\/removelabelfirst"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpcollisionhandling\/removelabelfirst"]}],"metadata":{"title":"MPCollisionHandling.removeLabelFirst","externalID":"c:@M@MapsIndoors@E@MPCollisionHandling@MPCollisionHandlingRemoveLabelFirst","role":"symbol","modules":[{"name":"MapsIndoors"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeLabelFirst"}],"navigatorTitle":[{"kind":"identifier","text":"MPCollisionHandlingRemoveLabelFirst"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling"]]},"abstract":[{"type":"text","text":"Will hide labels if they are overlapping with another feature such as an icon or another label."}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCollisionHandling/removeLabelFirst":{"title":"MPCollisionHandling.removeLabelFirst","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"removeLabelFirst","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Will hide labels if they are overlapping with another feature such as an icon or another label."}],"url":"\/documentation\/mapsindoors\/mpcollisionhandling\/removelabelfirst","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/removeLabelFirst","navigatorTitle":[{"kind":"identifier","text":"MPCollisionHandlingRemoveLabelFirst"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCollisionHandling":{"abstract":[{"type":"text","text":"The different ways to handle collisions of icons and labels on the map."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling","url":"\/documentation\/mapsindoors\/mpcollisionhandling","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPCollisionHandling"}],"title":"MPCollisionHandling","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPCollisionHandling"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MPCollisionHandlingRemoveLabelFirst"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPCollisionHandlingRemoveLabelFirst"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"MPCollisionHandlingRemoveLabelFirst","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"MPCollisionHandlingRemoveLabelFirst","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling~1removeLabelFirst\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling~1removeLabelFirst\/fragments","value":[{"kind":"identifier","text":"MPCollisionHandlingRemoveLabelFirst"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling\/title","op":"replace","value":"MPCollisionHandling"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling\/fragments","value":[{"text":"MPCollisionHandling","kind":"identifier"}],"op":"replace"}]}]}