{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hide"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbuilding-swift.class\/hide()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbuilding-swift.class\/hide()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/hide()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Hide the building from the map."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"hideBuilding"}],"role":"symbol","title":"hide()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hide"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:objc(cs)MPBuilding(im)hideBuilding","modules":[{"name":"MapsIndoors"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/hide()":{"deprecated":true,"role":"symbol","title":"hide()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hide"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Hide the building from the map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/hide()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hideBuilding"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/hide()"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class":{"role":"symbol","title":"MPBuilding","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuilding"}],"abstract":[{"type":"text","text":"Holds relevant data for a single building, and the buildings floor levels."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBuilding"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"hideBuilding"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hideBuilding"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"hideBuilding"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1hide()\/title","value":"hideBuilding"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1hide()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hideBuilding"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class\/title","value":"MPBuilding"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class\/fragments","value":[{"kind":"identifier","text":"MPBuilding"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}