{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"newFloor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"onMap"},{"kind":"text","text":" "},{"kind":"internalParam","text":"map"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSMapView","preciseIdentifier":"c:objc(cs)GMSMapView"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbuilding-swift.class\/show(_:onmap:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbuilding-swift.class\/show(_:onmap:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/show(_:onMap:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Use this method to actually shift floor and show the building level."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"showBuilding:onMap:"}],"role":"symbol","title":"show(_:onMap:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"onMap"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSMapView","preciseIdentifier":"c:objc(cs)GMSMapView"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:objc(cs)MPBuilding(im)showBuilding:onMap:","modules":[{"name":"MapsIndoors"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/show(_:onMap:)":{"deprecated":true,"role":"symbol","title":"show(_:onMap:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"onMap"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSMapView","preciseIdentifier":"c:objc(cs)GMSMapView"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Use this method to actually shift floor and show the building level."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/show(_:onMap:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showBuilding:onMap:"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/show(_:onmap:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class":{"role":"symbol","title":"MPBuilding","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuilding"}],"abstract":[{"type":"text","text":"Holds relevant data for a single building, and the buildings floor levels."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBuilding"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showBuilding:onMap:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showBuilding:onMap:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showBuilding:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"newFloor"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMap:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSMapView","preciseIdentifier":"c:objc(cs)GMSMapView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"map"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1show(_:onMap:)\/title","value":"showBuilding:onMap:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1show(_:onMap:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showBuilding:onMap:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class\/title","value":"MPBuilding"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class\/fragments","value":[{"kind":"identifier","text":"MPBuilding"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}