{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSetCacheManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","preciseIdentifier":"c:objc(cs)MPDataSetCacheManager","text":"MPDataSetCacheManager"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mapsindoors\/datasetcachemanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mapsindoors\/datasetcachemanager"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/dataSetCacheManager","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get the shared dataset cache manager."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSetCacheManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheManager","preciseIdentifier":"c:objc(cs)MPDataSetCacheManager"}],"title":"dataSetCacheManager","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MapsIndoors(cpy)dataSetCacheManager","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"dataSetCacheManager"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors":{"role":"symbol","title":"MapsIndoors","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsIndoors"}],"abstract":[{"type":"text","text":"Main class for initialisation, configuration and content synchronisation."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapsIndoors"}],"url":"\/documentation\/mapsindoors\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheManager":{"role":"symbol","title":"MPDataSetCacheManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheManager"}],"abstract":[{"type":"text","text":"Data set manager class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManager"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/dataSetCacheManager":{"role":"symbol","title":"dataSetCacheManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSetCacheManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheManager","preciseIdentifier":"c:objc(cs)MPDataSetCacheManager"}],"abstract":[{"type":"text","text":"Get the shared dataset cache manager."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/dataSetCacheManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dataSetCacheManager"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/datasetcachemanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"dataSetCacheManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dataSetCacheManager"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonnull"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","preciseIdentifier":"c:objc(cs)MPDataSetCacheManager","text":"MPDataSetCacheManager"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dataSetCacheManager"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors\/title","value":"MapsIndoors"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors\/fragments","value":[{"kind":"identifier","text":"MapsIndoors"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title","value":"MPDataSetCacheManager"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheManager"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1dataSetCacheManager\/title","value":"dataSetCacheManager"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1dataSetCacheManager\/fragments","value":[{"kind":"identifier","text":"dataSetCacheManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}