{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchAuthenticationDetails"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpAuthDetailsHandlerBlockType","preciseIdentifier":"c:MPMapsIndoors.h@T@mpAuthDetailsHandlerBlockType","text":"mpAuthDetailsHandlerBlockType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Completion callback"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mapsindoors\/fetchauthenticationdetails(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mapsindoors\/fetchauthenticationdetails(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/fetchAuthenticationDetails(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Fetch authentication details needed to perform an Auth2 supported single signon flow in your application."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchAuthenticationDetails"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpAuthDetailsHandlerBlockType","preciseIdentifier":"c:MPMapsIndoors.h@T@mpAuthDetailsHandlerBlockType"},{"kind":"text","text":")"}],"title":"fetchAuthenticationDetails(_:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MapsIndoors(cm)fetchAuthenticationDetails:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"fetchAuthenticationDetails:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/fetchAuthenticationDetails(_:)":{"role":"symbol","title":"fetchAuthenticationDetails(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchAuthenticationDetails"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpAuthDetailsHandlerBlockType","preciseIdentifier":"c:MPMapsIndoors.h@T@mpAuthDetailsHandlerBlockType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Fetch authentication details needed to perform an Auth2 supported single signon flow in your application."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/fetchAuthenticationDetails(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchAuthenticationDetails:"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/fetchauthenticationdetails(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors":{"role":"symbol","title":"MapsIndoors","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsIndoors"}],"abstract":[{"type":"text","text":"Main class for initialisation, configuration and content synchronisation."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapsIndoors"}],"url":"\/documentation\/mapsindoors\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/mpAuthDetailsHandlerBlockType":{"role":"symbol","title":"mpAuthDetailsHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpAuthDetailsHandlerBlockType"}],"abstract":[{"type":"text","text":"Authentication details callback handler block"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpAuthDetailsHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpAuthDetailsHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpauthdetailshandlerblocktype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"fetchAuthenticationDetails:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fetchAuthenticationDetails:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"fetchAuthenticationDetails:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(id<MPAuthDetails>, NSError *)","preciseIdentifier":"c:BFv(#*Qoobjc(pl)MPAuthDetails#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1fetchAuthenticationDetails(_:)\/title","value":"fetchAuthenticationDetails:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1fetchAuthenticationDetails(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fetchAuthenticationDetails:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors\/title","value":"MapsIndoors"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors\/fragments","value":[{"kind":"identifier","text":"MapsIndoors"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpAuthDetailsHandlerBlockType\/title","value":"mpAuthDetailsHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpAuthDetailsHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpAuthDetailsHandlerBlockType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}