{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLanguage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"languageCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"languageCode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The language for which the content should be fetched. Uses the two-letter language code ISO 639-1."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mapsindoors\/setlanguage(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mapsindoors\/setlanguage(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/setLanguage(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the language for the content provided by MapsIndoors."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLanguage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"setLanguage(_:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MapsIndoors(cm)setLanguage:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"setLanguage:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/setLanguage(_:)":{"role":"symbol","title":"setLanguage(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLanguage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the language for the content provided by MapsIndoors."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/setLanguage(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setLanguage:"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/setlanguage(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors":{"role":"symbol","title":"MapsIndoors","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsIndoors"}],"abstract":[{"type":"text","text":"Main class for initialisation, configuration and content synchronisation."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapsIndoors"}],"url":"\/documentation\/mapsindoors\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"setLanguage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setLanguage:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setLanguage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"languageCode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1setLanguage(_:)\/title","value":"setLanguage:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1setLanguage(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setLanguage:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors\/title","value":"MapsIndoors"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors\/fragments","value":[{"kind":"identifier","text":"MapsIndoors"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}