{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"synchronizeContent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpSyncContentHandlerBlockType","preciseIdentifier":"c:MPMapsIndoors.h@T@mpSyncContentHandlerBlockType","text":"mpSyncContentHandlerBlockType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback function that fires when content has been fetched or if this process resolves in an error. Note: Does not automtically retry fetch."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mapsindoors\/synchronizecontent(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mapsindoors\/synchronizecontent(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/synchronizeContent(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Fetch all neccesary content to be able to run MapsIndoors in offline environments."},{"type":"text","text":" "},{"type":"text","text":"If you have registered custom location sources, they are not synchronized by this method - it is the responsibility of the provider of the custom location source to synchronize as appropriate."},{"type":"text","text":" "},{"type":"text","text":"This method only synchronizes the current dataset - If you need to synchronize data for non-current datasets, please see "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/dataSetCacheManager"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/synchronizeContent()"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"synchronizeContent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpSyncContentHandlerBlockType","preciseIdentifier":"c:MPMapsIndoors.h@T@mpSyncContentHandlerBlockType"},{"kind":"text","text":")"}],"title":"synchronizeContent(_:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MapsIndoors(cm)synchronizeContent:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"synchronizeContent:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheManager/synchronizeContent()":{"role":"symbol","title":"synchronizeContent()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"synchronizeContent"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Fetch and update content for all managed data sets. The delegate object receives the completion event."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/synchronizeContent()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"synchronizeContent"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/synchronizecontent()"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/dataSetCacheManager":{"role":"symbol","title":"dataSetCacheManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSetCacheManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheManager","preciseIdentifier":"c:objc(cs)MPDataSetCacheManager"}],"abstract":[{"type":"text","text":"Get the shared dataset cache manager."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/dataSetCacheManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dataSetCacheManager"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/datasetcachemanager"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors":{"role":"symbol","title":"MapsIndoors","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsIndoors"}],"abstract":[{"type":"text","text":"Main class for initialisation, configuration and content synchronisation."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapsIndoors"}],"url":"\/documentation\/mapsindoors\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/synchronizeContent(_:)":{"role":"symbol","title":"synchronizeContent(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"synchronizeContent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpSyncContentHandlerBlockType","preciseIdentifier":"c:MPMapsIndoors.h@T@mpSyncContentHandlerBlockType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Fetch all neccesary content to be able to run MapsIndoors in offline environments."},{"type":"text","text":" "},{"type":"text","text":"If you have registered custom location sources, they are not synchronized by this method - it is the responsibility of the provider of the custom location source to synchronize as appropriate."},{"type":"text","text":" "},{"type":"text","text":"This method only synchronizes the current dataset - If you need to synchronize data for non-current datasets, please see "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/dataSetCacheManager"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/synchronizeContent()"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/synchronizeContent(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"synchronizeContent:"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/synchronizecontent(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/mpSyncContentHandlerBlockType":{"role":"symbol","title":"mpSyncContentHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpSyncContentHandlerBlockType"}],"abstract":[{"type":"text","text":"Content synchronisation callback handler block"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpSyncContentHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpSyncContentHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpsynccontenthandlerblocktype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"synchronizeContent:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"synchronizeContent:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"synchronizeContent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1synchronizeContent()\/title","value":"synchronizeContent"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1synchronizeContent()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"synchronizeContent"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1dataSetCacheManager\/title","value":"dataSetCacheManager"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1dataSetCacheManager\/fragments","value":[{"kind":"identifier","text":"dataSetCacheManager"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors\/title","value":"MapsIndoors"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors\/fragments","value":[{"kind":"identifier","text":"MapsIndoors"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1synchronizeContent(_:)\/title","value":"synchronizeContent:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1synchronizeContent(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"synchronizeContent:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpSyncContentHandlerBlockType\/title","value":"mpSyncContentHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpSyncContentHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpSyncContentHandlerBlockType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}