{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toMap"},{"kind":"text","text":" "},{"kind":"internalParam","text":"map"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSMapView","preciseIdentifier":"c:objc(cs)GMSMapView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"map","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The map that should hold the floor selector."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpfloorselectorcontrol\/add(tomap:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpfloorselectorcontrol\/add(tomap:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/add(toMap:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Add the floor selector to a map."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"addToMap:"}],"role":"symbol","title":"add(toMap:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toMap"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSMapView","preciseIdentifier":"c:objc(cs)GMSMapView"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(cs)MPFloorSelectorControl(im)addToMap:","modules":[{"name":"MapsIndoors"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please use addSubview on containing view instead"}]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl":{"role":"symbol","title":"MPFloorSelectorControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloorSelectorControl"}],"abstract":[{"type":"text","text":"Floor selection UI element. Can be added to the map, but should be linked to an MPBuilding to make sense."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPFloorSelectorControl"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/add(toMap:)":{"deprecated":true,"role":"symbol","title":"add(toMap:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toMap"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSMapView","preciseIdentifier":"c:objc(cs)GMSMapView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Add the floor selector to a map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/add(toMap:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addToMap:"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/add(tomap:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addToMap:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addToMap:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addToMap:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSMapView","preciseIdentifier":"c:objc(cs)GMSMapView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"map"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl\/title","value":"MPFloorSelectorControl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl\/fragments","value":[{"kind":"identifier","text":"MPFloorSelectorControl"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1add(toMap:)\/title","value":"addToMap:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1add(toMap:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addToMap:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}