{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedFloorButtonBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpfloorselectorcontrol\/selectedfloorbuttonbackgroundcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpfloorselectorcontrol\/selectedfloorbuttonbackgroundcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/selectedFloorButtonBackgroundColor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The backgroundColor of floor selector buttons in selected state."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedFloorButtonBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"title":"selectedFloorButtonBackgroundColor","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPFloorSelectorControl(cpy)selectedFloorButtonBackgroundColor","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"selectedFloorButtonBackgroundColor"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/selectedFloorButtonBackgroundColor":{"role":"symbol","title":"selectedFloorButtonBackgroundColor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedFloorButtonBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The backgroundColor of floor selector buttons in selected state."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/selectedFloorButtonBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedFloorButtonBackgroundColor"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/selectedfloorbuttonbackgroundcolor"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl":{"role":"symbol","title":"MPFloorSelectorControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloorSelectorControl"}],"abstract":[{"type":"text","text":"Floor selection UI element. Can be added to the map, but should be linked to an MPBuilding to make sense."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPFloorSelectorControl"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"selectedFloorButtonBackgroundColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"selectedFloorButtonBackgroundColor"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *"},{"kind":"identifier","text":"selectedFloorButtonBackgroundColor"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1selectedFloorButtonBackgroundColor\/title","value":"selectedFloorButtonBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1selectedFloorButtonBackgroundColor\/fragments","value":[{"kind":"identifier","text":"selectedFloorButtonBackgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl\/title","value":"MPFloorSelectorControl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl\/fragments","value":[{"kind":"identifier","text":"MPFloorSelectorControl"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}