{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserFloor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"floorIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpfloorselectorcontrol\/setuserfloor(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpfloorselectorcontrol\/setuserfloor(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/setUserFloor(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the floor index that the user\/device is located. This value is used to provide an indicator on the floor selector, regardless of the floor actually displayed"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserFloor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":")"}],"title":"setUserFloor(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPFloorSelectorControl(im)setUserFloor:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"setUserFloor:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/setUserFloor(_:)":{"role":"symbol","title":"setUserFloor(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserFloor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the floor index that the user\/device is located. This value is used to provide an indicator on the floor selector, regardless of the floor actually displayed"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/setUserFloor(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setUserFloor:"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/setuserfloor(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl":{"role":"symbol","title":"MPFloorSelectorControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloorSelectorControl"}],"abstract":[{"type":"text","text":"Floor selection UI element. Can be added to the map, but should be linked to an MPBuilding to make sense."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPFloorSelectorControl"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setUserFloor:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserFloor:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setUserFloor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"floorIndex"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1setUserFloor(_:)\/title","value":"setUserFloor:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1setUserFloor(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserFloor:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl\/title","value":"MPFloorSelectorControl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl\/fragments","value":[{"kind":"identifier","text":"MPFloorSelectorControl"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}