{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rows"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixRows-swift.class","preciseIdentifier":"c:objc(cs)MPDistanceMatrixRows","text":"MPDistanceMatrixRows"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdistancematrixresult\/rows"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdistancematrixresult\/rows"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/rows","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rows"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPDistanceMatrixRows","preciseIdentifier":"c:objc(cs)MPDistanceMatrixRows"},{"kind":"text","text":"]?"}],"title":"rows","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPDistanceMatrixResult(py)rows","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"rows"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixRows-swift.class":{"role":"symbol","title":"MPDistanceMatrixRows","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDistanceMatrixRows"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixRows-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDistanceMatrixRows"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixrows-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixResult/rows":{"role":"symbol","title":"rows","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rows"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPDistanceMatrixRows","preciseIdentifier":"c:objc(cs)MPDistanceMatrixRows"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/rows","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rows"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixresult\/rows"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixResult":{"role":"symbol","title":"MPDistanceMatrixResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDistanceMatrixResult"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDistanceMatrixResult"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixresult"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"rows"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rows"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<MPDistanceMatrixRows *><MPDistanceMatrixRows>","preciseIdentifier":"c:Q$objc(cs)NSArrayobjc(pl)MPDistanceMatrixRows"},{"kind":"text","text":" *"},{"kind":"identifier","text":"rows"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixRows-swift.class\/title","value":"MPDistanceMatrixRows"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixRows-swift.class\/fragments","value":[{"kind":"identifier","text":"MPDistanceMatrixRows"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult~1rows\/title","value":"rows"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult~1rows\/fragments","value":[{"kind":"identifier","text":"rows"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult\/title","value":"MPDistanceMatrixResult"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult\/fragments","value":[{"kind":"identifier","text":"MPDistanceMatrixResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}