{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplivedatamanagerstate\/connected"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplivedatamanagerstate\/connected"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/connected","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The Connected state relfects the state of being connected to the Live Update remote services."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}],"title":"MPLiveDataManagerState.connected","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MPLiveDataManagerState@MPLiveDataManagerStateConnected","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerStateConnected"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerState/connected":{"role":"symbol","title":"MPLiveDataManagerState.connected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}],"abstract":[{"type":"text","text":"The Connected state relfects the state of being connected to the Live Update remote services."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/connected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerStateConnected"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerstate\/connected"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerState":{"role":"symbol","title":"MPLiveDataManagerState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManagerState"}],"abstract":[{"type":"text","text":"Enumeration of MPLiveDataManager states."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerState"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerstate"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MPLiveDataManagerStateConnected"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerStateConnected"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MPLiveDataManagerStateConnected"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState~1connected\/title","value":"MPLiveDataManagerStateConnected"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState~1connected\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerStateConnected"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState\/title","value":"MPLiveDataManagerState"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}