{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteProperty"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteProperty\/value"},"variants":[{"paths":["\/documentation\/mapsindoors\/mprouteproperty\/value"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mprouteproperty\/value"]}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"abstract":[{"text":"Route property value.","type":"text"}],"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPRouteProperty(py)value","navigatorTitle":[{"kind":"identifier","text":"value"}],"modules":[{"name":"MapsIndoors"}],"required":true,"role":"symbol","title":"value","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"symbolKind":"property","roleHeading":"Instance Property"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteProperty":{"navigatorTitle":[{"kind":"identifier","text":"MPRouteProperty"}],"url":"\/documentation\/mapsindoors\/mprouteproperty","role":"symbol","title":"MPRouteProperty","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRouteProperty"}],"type":"topic","abstract":[{"type":"text","text":"Route property model"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteProperty"},"MapsPeopleWhite.png":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteProperty/value":{"navigatorTitle":[{"text":"value","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mprouteproperty\/value","required":true,"role":"symbol","title":"value","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"type":"topic","abstract":[{"text":"Route property value.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteProperty\/value"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"value"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"value","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"value"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteProperty\/title","value":"MPRouteProperty"},{"op":"replace","value":[{"text":"MPRouteProperty","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteProperty\/fragments"},{"op":"replace","value":"value","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteProperty~1value\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteProperty~1value\/fragments","value":[{"text":"value","kind":"identifier"}]}]}]}