{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationsUsingQueryAsync"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"locationQuery"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery","preciseIdentifier":"c:objc(cs)MPLocationQuery","text":"MPLocationQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":" "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpLocationListHandlerBlockType","preciseIdentifier":"c:MPLocationsProvider.h@T@mpLocationListHandlerBlockType","text":"mpLocationListHandlerBlockType"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"locationQuery","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Locations query object. Must at least define your MapsIndoors solution ID (MPLocationQuery.solutionId)"}]}]},{"name":"language","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The language code. Must be one of the MapsIndoors solutions supported content languages."}]}]},{"name":"handler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler callback block. Contains the MPLocationDataset object (can be nil) and an NSError object (can be nil)."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocationsusingqueryasync(_:language:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocationsusingqueryasync(_:language:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsUsingQueryAsync(_:language:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Method to query a subset of locations from the provider."}],"kind":"symbol","metadata":{"modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getLocationsUsingQueryAsync:language:completionHandler:"}],"role":"symbol","title":"getLocationsUsingQueryAsync(_:language:completionHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationsUsingQueryAsync"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocationQuery","preciseIdentifier":"c:objc(cs)MPLocationQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpLocationListHandlerBlockType","preciseIdentifier":"c:MPLocationsProvider.h@T@mpLocationListHandlerBlockType"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:objc(pl)MPLocationsProvider(im)getLocationsUsingQueryAsync:language:completionHandler:","required":true,"platforms":[]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use getLocationsUsingQuery:completionHandler: instead"}]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol":{"role":"symbol","title":"MPLocationsProviderProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationsProviderProtocol"}],"abstract":[{"type":"text","text":"Locations provider protocol."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationsProviderProtocol"}],"url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/getLocationsUsingQueryAsync(_:language:completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"getLocationsUsingQueryAsync:language:completionHandler:"}],"deprecated":true,"role":"symbol","title":"getLocationsUsingQueryAsync(_:language:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationsUsingQueryAsync"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocationQuery","preciseIdentifier":"c:objc(cs)MPLocationQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpLocationListHandlerBlockType","preciseIdentifier":"c:MPLocationsProvider.h@T@mpLocationListHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Method to query a subset of locations from the provider."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsUsingQueryAsync(_:language:completionHandler:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocationsusingqueryasync(_:language:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery":{"role":"symbol","title":"MPLocationQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationQuery"}],"abstract":[{"type":"text","text":"Locations query object used in conjunction with the MPLocationsProvider"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationQuery"}],"url":"\/documentation\/mapsindoors\/mplocationquery"},"doc://MapsIndoors/documentation/MapsIndoors/mpLocationListHandlerBlockType":{"role":"symbol","title":"mpLocationListHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpLocationListHandlerBlockType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpLocationListHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpLocationListHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mplocationlisthandlerblocktype"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getLocationsUsingQueryAsync:language:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationsUsingQueryAsync:language:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getLocationsUsingQueryAsync:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery","preciseIdentifier":"c:objc(cs)MPLocationQuery","text":"MPLocationQuery"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"locationQuery"},{"kind":"text","text":" "},{"kind":"identifier","text":"language:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"language"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(MPLocationDataset *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)MPLocationDataset#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"handler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol\/title","value":"MPLocationsProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol\/fragments","value":[{"kind":"identifier","text":"MPLocationsProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationsUsingQueryAsync(_:language:completionHandler:)\/title","value":"getLocationsUsingQueryAsync:language:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationsUsingQueryAsync(_:language:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationsUsingQueryAsync:language:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery\/title","value":"MPLocationQuery"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery\/fragments","value":[{"kind":"identifier","text":"MPLocationQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpLocationListHandlerBlockType\/title","value":"mpLocationListHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpLocationListHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpLocationListHandlerBlockType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}