{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBuildingWithinBounds"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mapExtend"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapExtend","preciseIdentifier":"c:objc(cs)MPMapExtend","text":"MPMapExtend"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":" "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpBuildingDetailsHandlerBlockType","preciseIdentifier":"c:MPVenueProvider.h@T@mpBuildingDetailsHandlerBlockType","text":"mpBuildingDetailsHandlerBlockType"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"mapExtend","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The geographic bounds, defined by north, south, west and east"}]}]},{"name":"handler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Building fetch callback block"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpvenueprovider\/getbuildingwithinbounds(_:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpvenueprovider\/getbuildingwithinbounds(_:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingWithinBounds(_:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get a single building within given bounds"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBuildingWithinBounds"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPMapExtend","preciseIdentifier":"c:objc(cs)MPMapExtend"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpBuildingDetailsHandlerBlockType","preciseIdentifier":"c:MPVenueProvider.h@T@mpBuildingDetailsHandlerBlockType"},{"kind":"text","text":"?)"}],"title":"getBuildingWithinBounds(_:completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPVenueProvider(im)getBuildingWithinBounds:completionHandler:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getBuildingWithinBounds:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/getBuildingWithinBounds(_:completionHandler:)":{"role":"symbol","title":"getBuildingWithinBounds(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBuildingWithinBounds"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPMapExtend","preciseIdentifier":"c:objc(cs)MPMapExtend"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpBuildingDetailsHandlerBlockType","preciseIdentifier":"c:MPVenueProvider.h@T@mpBuildingDetailsHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get a single building within given bounds"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingWithinBounds(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getBuildingWithinBounds:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/getbuildingwithinbounds(_:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider":{"role":"symbol","title":"MPVenueProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenueProvider"}],"abstract":[{"type":"text","text":"Venue provider interface, that defines a delegate and a method for venue queries."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenueProvider"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapExtend":{"role":"symbol","title":"MPMapExtend","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapExtend"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapExtend","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMapExtend"}],"url":"\/documentation\/mapsindoors\/mpmapextend"},"doc://MapsIndoors/documentation/MapsIndoors/mpBuildingDetailsHandlerBlockType":{"role":"symbol","title":"mpBuildingDetailsHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpBuildingDetailsHandlerBlockType"}],"abstract":[{"type":"text","text":"Handler block for fetching buildings"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpBuildingDetailsHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpBuildingDetailsHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpbuildingdetailshandlerblocktype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getBuildingWithinBounds:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBuildingWithinBounds:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getBuildingWithinBounds:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapExtend","preciseIdentifier":"c:objc(cs)MPMapExtend","text":"MPMapExtend"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"mapExtend"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(MPBuilding *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)MPBuilding#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"handler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getBuildingWithinBounds(_:completionHandler:)\/title","value":"getBuildingWithinBounds:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getBuildingWithinBounds(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBuildingWithinBounds:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider\/title","value":"MPVenueProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider\/fragments","value":[{"kind":"identifier","text":"MPVenueProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapExtend\/title","value":"MPMapExtend"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapExtend\/fragments","value":[{"kind":"identifier","text":"MPMapExtend"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpBuildingDetailsHandlerBlockType\/title","value":"mpBuildingDetailsHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpBuildingDetailsHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpBuildingDetailsHandlerBlockType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}