{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBuildingsWithCompletion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpBuildingListHandlerBlockType","preciseIdentifier":"c:MPVenueProvider.h@T@mpBuildingListHandlerBlockType","text":"mpBuildingListHandlerBlockType"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpvenueprovider\/getbuildingswithcompletion(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpvenueprovider\/getbuildingswithcompletion(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingsWithCompletion(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get buildings from this provider"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBuildingsWithCompletion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpBuildingListHandlerBlockType","preciseIdentifier":"c:MPVenueProvider.h@T@mpBuildingListHandlerBlockType"},{"kind":"text","text":"?)"}],"title":"getBuildingsWithCompletion(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPVenueProvider(im)getBuildingsWithCompletion:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getBuildingsWithCompletion:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/mpBuildingListHandlerBlockType":{"role":"symbol","title":"mpBuildingListHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpBuildingListHandlerBlockType"}],"abstract":[{"type":"text","text":"Handler block for fetching buildings"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpBuildingListHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpBuildingListHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpbuildinglisthandlerblocktype"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider":{"role":"symbol","title":"MPVenueProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenueProvider"}],"abstract":[{"type":"text","text":"Venue provider interface, that defines a delegate and a method for venue queries."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenueProvider"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/getBuildingsWithCompletion(_:)":{"role":"symbol","title":"getBuildingsWithCompletion(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBuildingsWithCompletion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpBuildingListHandlerBlockType","preciseIdentifier":"c:MPVenueProvider.h@T@mpBuildingListHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get buildings from this provider"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingsWithCompletion(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getBuildingsWithCompletion:"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/getbuildingswithcompletion(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getBuildingsWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBuildingsWithCompletion:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getBuildingsWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<MPBuilding *> *, NSError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"handler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpBuildingListHandlerBlockType\/title","value":"mpBuildingListHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpBuildingListHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpBuildingListHandlerBlockType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider\/title","value":"MPVenueProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider\/fragments","value":[{"kind":"identifier","text":"MPVenueProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getBuildingsWithCompletion(_:)\/title","value":"getBuildingsWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getBuildingsWithCompletion(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBuildingsWithCompletion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}