{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDataFrom"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"point"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class","preciseIdentifier":"c:objc(cs)MPPoint","text":"MPPoint"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A dictionary of venue, building and floor objects. Can be empty."}]}]},{"kind":"parameters","parameters":[{"name":"point","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Geographic point"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpvenueprovider\/getdatafrom(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpvenueprovider\/getdatafrom(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getDataFrom(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Synchronously get all possible data related to the provided geographical point."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDataFrom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"title":"getDataFrom(_:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPVenueProvider(cm)getDataFromPoint:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getDataFromPoint:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPPoint-swift.class":{"role":"symbol","title":"MPPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPoint"}],"abstract":[{"type":"text","text":"Basic point geometry class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPoint"}],"url":"\/documentation\/mapsindoors\/mppoint-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/getDataFrom(_:)":{"role":"symbol","title":"getDataFrom(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDataFrom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Synchronously get all possible data related to the provided geographical point."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getDataFrom(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDataFromPoint:"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/getdatafrom(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider":{"role":"symbol","title":"MPVenueProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenueProvider"}],"abstract":[{"type":"text","text":"Venue provider interface, that defines a delegate and a method for venue queries."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenueProvider"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getDataFromPoint:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getDataFromPoint:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getDataFromPoint:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class","preciseIdentifier":"c:objc(cs)MPPoint","text":"MPPoint"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"point"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class\/title","value":"MPPoint"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class\/fragments","value":[{"kind":"identifier","text":"MPPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getDataFrom(_:)\/title","value":"getDataFromPoint:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getDataFrom(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getDataFromPoint:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider\/title","value":"MPVenueProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider\/fragments","value":[{"kind":"identifier","text":"MPVenueProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}