{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdateFactory\/updateWithId(locationId:fromSource:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mplocationupdatefactory\/updatewithid(locationid:fromsource:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mplocationupdatefactory\/updatewithid(locationid:fromsource:)"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateWithId","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"locationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"fromSource","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationSource","kind":"typeIdentifier","text":"MPLocationSource"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"MPLocationUpdate","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationUpdate"}],"title":"updateWithId(locationId:fromSource:)","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","required":true,"modules":[{"name":"MapsIndoors"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPLocationUpdateFactory(im)updateWithId:fromSource:","navigatorTitle":[{"text":"updateWithId:fromSource:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdateFactory"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(updateWithId:fromSource:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateWithId"},{"kind":"text","text":"("},{"text":"locationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromSource"},{"text":" ","kind":"text"},{"text":"locationSource","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationSource","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource","text":"MPLocationSource","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"MPLocationUpdate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationUpdate"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSource":{"title":"MPLocationSource","navigatorTitle":[{"kind":"identifier","text":"MPLocationSource"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPLocationSource","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mplocationsource","abstract":[{"type":"text","text":"Location source protocol."}],"kind":"symbol"},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image","alt":null,"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationUpdateFactory/updateWithId(locationId:fromSource:)":{"navigatorTitle":[{"text":"updateWithId:fromSource:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mplocationupdatefactory\/updatewithid(locationid:fromsource:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateWithId","kind":"identifier"},{"kind":"text","text":"("},{"text":"locationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"fromSource","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationSource","text":"MPLocationSource","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLocationUpdate","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationUpdate"}],"title":"updateWithId(locationId:fromSource:)","role":"symbol","type":"topic","required":true,"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdateFactory\/updateWithId(locationId:fromSource:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationUpdateFactory":{"navigatorTitle":[{"kind":"identifier","text":"MPLocationUpdateFactory"}],"abstract":[{"type":"text","text":"Protocol  to create instance of "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate","isActive":true}],"url":"\/documentation\/mapsindoors\/mplocationupdatefactory","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPLocationUpdateFactory","kind":"identifier"}],"title":"MPLocationUpdateFactory","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdateFactory"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationUpdate":{"navigatorTitle":[{"kind":"identifier","text":"MPLocationUpdate"}],"url":"\/documentation\/mapsindoors\/mplocationupdate","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPLocationUpdate","kind":"identifier"}],"title":"MPLocationUpdate","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"updateWithId:fromSource:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateWithId:fromSource:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPLocationUpdate","text":"id<MPLocationUpdate>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"updateWithId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"locationId"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromSource:"},{"kind":"text","text":"("},{"text":"id<MPLocationSource>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPLocationSource"},{"text":" *) ","kind":"text"},{"text":"locationSource","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"MPLocationSource","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MPLocationSource"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdateFactory~1updateWithId(locationId:fromSource:)\/title","value":"updateWithId:fromSource:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateWithId:fromSource:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdateFactory~1updateWithId(locationId:fromSource:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdateFactory\/title","value":"MPLocationUpdateFactory"},{"value":[{"kind":"identifier","text":"MPLocationUpdateFactory"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdateFactory\/fragments","op":"replace"},{"op":"replace","value":"MPLocationUpdate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdate\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdate\/fragments","value":[{"text":"MPLocationUpdate","kind":"identifier"}],"op":"replace"}]}]}