{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init(rule:parent:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdisplayrule\/init(rule:parent:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdisplayrule\/init(rule:parent:)"]}],"metadata":{"externalID":"c:@M@MapsIndoors@objc(cs)MPDisplayRule(im)initWithRule:parent:","modules":[{"name":"MapsIndoors"}],"roleHeading":"Initializer","title":"init(rule:parent:)","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rule"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule","text":"MPDisplayRule","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"parent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDisplayRule","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithRule:parent:"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rule"},{"text":": ","kind":"text"},{"text":"MPDisplayRule","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"parent"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule","kind":"typeIdentifier","text":"MPDisplayRule","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/init(rule:parent:)":{"url":"\/documentation\/mapsindoors\/mpdisplayrule\/init(rule:parent:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rule","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPDisplayRule","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"parent","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDisplayRule","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init(rule:parent:)","kind":"symbol","title":"init(rule:parent:)","abstract":[],"navigatorTitle":[{"text":"initWithRule:parent:","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule":{"url":"\/documentation\/mapsindoors\/mpdisplayrule","title":"MPDisplayRule","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDisplayRule"}],"type":"topic","navigatorTitle":[{"text":"MPDisplayRule","kind":"identifier"}],"abstract":[{"type":"text","text":"This class represents a Display Rule, a MapsIndoors concept which describes a number of styling values for MapsIndoors objects."},{"type":"text","text":" "},{"text":"The values contained within dictates how the MapsIndoors SDK renders a given object on the map (POI, area, selection, model, etc.).","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithRule:parent:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithRule:parent:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithRule:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule","kind":"typeIdentifier","text":"MPDisplayRule","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rule"},{"text":" ","kind":"text"},{"text":"parent:","kind":"identifier"},{"kind":"text","text":"("},{"text":"MPDisplayRule","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"parent"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1init(rule:parent:)\/title","value":"initWithRule:parent:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithRule:parent:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1init(rule:parent:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/title","value":"MPDisplayRule","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/fragments","value":[{"text":"MPDisplayRule","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}