{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule"]]},"abstract":[{"type":"text","text":"Whether or not to show a text label. See "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/label"},{"type":"text","text":" property."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/labelVisible"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdisplayrule\/labelvisible"]},{"paths":["\/documentation\/mapsindoors\/mpdisplayrule\/labelvisible"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"labelVisible"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"labelVisible","roleHeading":"Instance Property","navigatorTitle":[{"text":"labelVisible","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MapsIndoors@objc(cs)MPDisplayRule(py)labelVisible","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"labelVisible","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"property"},"references":{"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/labelVisible":{"kind":"symbol","navigatorTitle":[{"text":"labelVisible","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/labelVisible","url":"\/documentation\/mapsindoors\/mpdisplayrule\/labelvisible","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"labelVisible","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","title":"labelVisible","role":"symbol","abstract":[{"text":"Whether or not to show a text label. See ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/label","isActive":true},{"text":" property.","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule":{"navigatorTitle":[{"kind":"identifier","text":"MPDisplayRule"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpdisplayrule","title":"MPDisplayRule","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"This class represents a Display Rule, a MapsIndoors concept which describes a number of styling values for MapsIndoors objects."},{"text":" ","type":"text"},{"type":"text","text":"The values contained within dictates how the MapsIndoors SDK renders a given object on the map (POI, area, selection, model, etc.)."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPDisplayRule","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/label":{"kind":"symbol","navigatorTitle":[{"text":"label","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/label","url":"\/documentation\/mapsindoors\/mpdisplayrule\/label","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"label","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"label","role":"symbol","abstract":[{"text":"The label to show for the marker. It can be a fixed string or a label template, e.g. ","type":"text"},{"type":"codeVoice","code":"\"{{name}}\""},{"text":", ","type":"text"},{"type":"codeVoice","code":"\"{{roomId}}\""},{"text":", ","type":"text"},{"type":"codeVoice","code":"\"Room #{{roomId}}\""},{"type":"text","text":" etc.."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"labelVisible","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"labelVisible","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"labelVisible","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"labelVisible","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1labelVisible\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1labelVisible\/fragments","op":"replace","value":[{"kind":"identifier","text":"labelVisible"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/title","value":"MPDisplayRule"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/fragments","value":[{"text":"MPDisplayRule","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1label\/title","value":"label","op":"replace"},{"value":[{"kind":"identifier","text":"label"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1label\/fragments"}]}]}