{"variants":[{"paths":["\/documentation\/mapsindoors\/mpdisplayrule\/model3dvisible"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdisplayrule\/model3dvisible"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DVisible"},"metadata":{"modules":[{"name":"MapsIndoors"}],"title":"model3DVisible","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"model3DVisible"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@MapsIndoors@objc(cs)MPDisplayRule(py)model3DVisible","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"model3DVisible"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"abstract":[{"type":"text","text":"Whether or not to show the 3D model on the map."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"model3DVisible","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule"]]},"sections":[],"kind":"symbol","references":{"MapsPeopleWhite.png":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/model3DVisible":{"kind":"symbol","navigatorTitle":[{"text":"model3DVisible","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DVisible","url":"\/documentation\/mapsindoors\/mpdisplayrule\/model3dvisible","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"model3DVisible","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","title":"model3DVisible","role":"symbol","abstract":[{"type":"text","text":"Whether or not to show the 3D model on the map."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule":{"navigatorTitle":[{"kind":"identifier","text":"MPDisplayRule"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpdisplayrule","title":"MPDisplayRule","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"This class represents a Display Rule, a MapsIndoors concept which describes a number of styling values for MapsIndoors objects."},{"text":" ","type":"text"},{"type":"text","text":"The values contained within dictates how the MapsIndoors SDK renders a given object on the map (POI, area, selection, model, etc.)."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPDisplayRule","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"model3DVisible","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"model3DVisible","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"model3DVisible"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"model3DVisible","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DVisible\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DVisible\/fragments","op":"replace","value":[{"text":"model3DVisible","kind":"identifier"}]},{"op":"replace","value":"MPDisplayRule","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/fragments","op":"replace","value":[{"text":"MPDisplayRule","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}