{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule"]]},"metadata":{"modules":[{"name":"MapsIndoors"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPDisplayRule(py)model2DWidthMeters","title":"model2DWidthMeters","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"model2DWidthMeters","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"model2DWidthMeters"}],"role":"symbol"},"abstract":[{"type":"text","text":"The width of the 2D model. The value is in meters to make it easy to associate with the real world."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdisplayrule\/model2dwidthmeters"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdisplayrule\/model2dwidthmeters"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"model2DWidthMeters","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DWidthMeters","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule":{"abstract":[{"text":"This class represents a Display Rule, a MapsIndoors concept which describes a number of styling values for MapsIndoors objects.","type":"text"},{"type":"text","text":" "},{"text":"The values contained within dictates how the MapsIndoors SDK renders a given object on the map (POI, area, selection, model, etc.).","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDisplayRule"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule","navigatorTitle":[{"kind":"identifier","text":"MPDisplayRule"}],"title":"MPDisplayRule","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule","role":"symbol","kind":"symbol"},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","alt":null,"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/model2DWidthMeters":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DWidthMeters","abstract":[{"type":"text","text":"The width of the 2D model. The value is in meters to make it easy to associate with the real world."}],"kind":"symbol","navigatorTitle":[{"text":"model2DWidthMeters","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"model2DWidthMeters"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/model2dwidthmeters","title":"model2DWidthMeters"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"model2DWidthMeters","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"model2DWidthMeters"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"model2DWidthMeters","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/title","op":"replace","value":"MPDisplayRule"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/fragments","value":[{"kind":"identifier","text":"MPDisplayRule"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model2DWidthMeters\/title","value":"model2DWidthMeters"},{"op":"replace","value":[{"kind":"identifier","text":"model2DWidthMeters"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model2DWidthMeters\/fragments"}]}]}