{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdisplayrule\/model3dzoomto"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdisplayrule\/model3dzoomto"]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DZoomTo","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"model3DZoomTo","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule"]]},"abstract":[{"type":"text","text":"The zoom level from where the 3D model should stop showing on the map."}],"metadata":{"title":"model3DZoomTo","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"model3DZoomTo","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"model3DZoomTo","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPDisplayRule(py)model3DZoomTo","modules":[{"name":"MapsIndoors"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/model3DZoomTo":{"title":"model3DZoomTo","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"model3DZoomTo","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"abstract":[{"text":"The zoom level from where the 3D model should stop showing on the map.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DZoomTo","url":"\/documentation\/mapsindoors\/mpdisplayrule\/model3dzoomto","navigatorTitle":[{"text":"model3DZoomTo","kind":"identifier"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDisplayRule","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdisplayrule","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MPDisplayRule","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule","title":"MPDisplayRule","abstract":[{"text":"This class represents a Display Rule, a MapsIndoors concept which describes a number of styling values for MapsIndoors objects.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The values contained within dictates how the MapsIndoors SDK renders a given object on the map (POI, area, selection, model, etc.)."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"model3DZoomTo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"model3DZoomTo","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"kind":"identifier","text":"model3DZoomTo"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"model3DZoomTo","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DZoomTo\/title"},{"op":"replace","value":[{"text":"model3DZoomTo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DZoomTo\/fragments"},{"op":"replace","value":"MPDisplayRule","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/fragments","value":[{"text":"MPDisplayRule","kind":"identifier"}]}]}]}