{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule"]]},"metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"polygonZoomTo","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPDisplayRule(py)polygonZoomTo","modules":[{"name":"MapsIndoors"}],"title":"polygonZoomTo","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonZoomTo"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]},"abstract":[{"text":"The map zoom level beneath which the location Polygon should be visible.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdisplayrule\/polygonzoomto"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdisplayrule\/polygonzoomto"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"polygonZoomTo"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonZoomTo"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/polygonZoomTo":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonZoomTo","abstract":[{"text":"The map zoom level beneath which the location Polygon should be visible.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"polygonZoomTo"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonZoomTo"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/polygonzoomto","title":"polygonZoomTo"},"MapsPeopleWhite.png":{"alt":null,"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule":{"abstract":[{"text":"This class represents a Display Rule, a MapsIndoors concept which describes a number of styling values for MapsIndoors objects.","type":"text"},{"type":"text","text":" "},{"text":"The values contained within dictates how the MapsIndoors SDK renders a given object on the map (POI, area, selection, model, etc.).","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDisplayRule"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule","navigatorTitle":[{"kind":"identifier","text":"MPDisplayRule"}],"title":"MPDisplayRule","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule","role":"symbol","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"polygonZoomTo","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"polygonZoomTo"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":" ","kind":"text"},{"text":"polygonZoomTo","kind":"identifier"}]}]}},{"value":"polygonZoomTo","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1polygonZoomTo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1polygonZoomTo\/fragments","value":[{"kind":"identifier","text":"polygonZoomTo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/title","value":"MPDisplayRule"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/fragments","value":[{"text":"MPDisplayRule","kind":"identifier"}],"op":"replace"}]}]}