{"variants":[{"paths":["\/documentation\/mapsindoors\/mpdisplayrule\/visible"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdisplayrule\/visible"]}],"metadata":{"externalID":"c:@M@MapsIndoors@objc(cs)MPDisplayRule(py)visible","roleHeading":"Instance Property","title":"visible","symbolKind":"property","modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visible"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"visible","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Whether or not to show the location.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visible","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/visible"},"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule":{"url":"\/documentation\/mapsindoors\/mpdisplayrule","title":"MPDisplayRule","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDisplayRule"}],"type":"topic","navigatorTitle":[{"text":"MPDisplayRule","kind":"identifier"}],"abstract":[{"type":"text","text":"This class represents a Display Rule, a MapsIndoors concept which describes a number of styling values for MapsIndoors objects."},{"type":"text","text":" "},{"text":"The values contained within dictates how the MapsIndoors SDK renders a given object on the map (POI, area, selection, model, etc.).","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/visible":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"visible"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/mapsindoors\/mpdisplayrule\/visible","role":"symbol","abstract":[{"text":"Whether or not to show the location.","type":"text"}],"title":"visible","navigatorTitle":[{"text":"visible","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/visible"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"visible","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"visible"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"visible","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/title","value":"MPDisplayRule"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/fragments","value":[{"kind":"identifier","text":"MPDisplayRule"}],"op":"replace"},{"op":"replace","value":"visible","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1visible\/title"},{"value":[{"text":"visible","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1visible\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}