{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/wallsHeight","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"wallsHeight"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"wallsHeight","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"property","externalID":"c:@M@MapsIndoors@objc(cs)MPDisplayRule(py)wallsHeight","roleHeading":"Instance Property","role":"symbol","title":"wallsHeight"},"abstract":[{"type":"text","text":"The height of the walls on the map."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"wallsHeight"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdisplayrule\/wallsheight"]},{"paths":["\/documentation\/mapsindoors\/mpdisplayrule\/wallsheight"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/wallsHeight":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"wallsHeight"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"wallsHeight"}],"url":"\/documentation\/mapsindoors\/mpdisplayrule\/wallsheight","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/wallsHeight","title":"wallsHeight","abstract":[{"text":"The height of the walls on the map.","type":"text"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDisplayRule","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdisplayrule","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MPDisplayRule","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule","title":"MPDisplayRule","abstract":[{"text":"This class represents a Display Rule, a MapsIndoors concept which describes a number of styling values for MapsIndoors objects.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The values contained within dictates how the MapsIndoors SDK renders a given object on the map (POI, area, selection, model, etc.)."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"wallsHeight","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"wallsHeight","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"text":" ","kind":"text"},{"text":"wallsHeight","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"wallsHeight","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1wallsHeight\/title"},{"value":[{"kind":"identifier","text":"wallsHeight"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1wallsHeight\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/title","value":"MPDisplayRule"},{"value":[{"text":"MPDisplayRule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/fragments","op":"replace"}]}]}