{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCategories"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpcategoriesprovider\/getcategories()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpcategoriesprovider\/getcategories()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider\/getCategories()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get categories from the specified solution."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCategories"},{"kind":"text","text":"()"}],"title":"getCategories()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPCategoriesProvider(im)getCategories","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getCategories"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPCategoriesProvider":{"role":"symbol","title":"MPCategoriesProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPCategoriesProvider"}],"abstract":[{"type":"text","text":"A categories provider acts as a service for the location categories belonging to a specific MapsIndoors solution\/dataset."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPCategoriesProvider"}],"url":"\/documentation\/mapsindoors\/mpcategoriesprovider"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPCategoriesProvider/getCategories()":{"role":"symbol","title":"getCategories()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCategories"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Get categories from the specified solution."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider\/getCategories()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getCategories"}],"url":"\/documentation\/mapsindoors\/mpcategoriesprovider\/getcategories()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getCategories"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCategories"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getCategories"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategoriesProvider\/title","value":"MPCategoriesProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategoriesProvider\/fragments","value":[{"kind":"identifier","text":"MPCategoriesProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategoriesProvider~1getCategories()\/title","value":"getCategories"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategoriesProvider~1getCategories()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCategories"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}