{"sections":[],"abstract":[{"type":"text","text":"Check if the given coordinate is contained within the polygon, and optionally return the coordinate closest to the polygon."},{"type":"text","text":" "},{"text":"If the polygon contains the coordinate, ‘coordinate’ is returned as nearestPoint.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If coordinate is not contained, the nearest point is calculated."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol"]]},"variants":[{"paths":["\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/containscoordinate(_:ignorepolygonholes:containmentmetadata:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/containscoordinate(_:ignorepolygonholes:containmentmetadata:)"]}],"metadata":{"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPGeometryQueryProtocol(im)containsCoordinate:ignorePolygonHoles:containmentMetadata:","symbolKind":"method","title":"containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"containsCoordinate","kind":"identifier"},{"kind":"text","text":"("},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"ignorePolygonHoles","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"containmentMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPGeometryContainmentMetadata","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometryContainmentMetadata"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"modules":[{"name":"MapsIndoors"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"containsCoordinate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"coordinate","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ignorePolygonHoles","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"containmentMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata","text":"MPGeometryContainmentMetadata","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometryContainmentMetadata"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Coordinate to check for containment."}],"type":"paragraph"}],"name":"coordinate"},{"name":"ignorePolygonHoles","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Should holes in a polygon be ignored"}]}]},{"content":[{"inlineContent":[{"text":"If not nil, the nearest point and distance on the polygon boundary is returned. Note this may be the nearest point on a polygon-hole.","type":"text"}],"type":"paragraph"}],"name":"containmentMetadata"}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"False if the coordinate is outside the polygon, or inside any holes in the polygon."}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryQueryProtocol":{"url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol","navigatorTitle":[{"text":"MPGeometryQueryProtocol","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPGeometryQueryProtocol","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol","title":"MPGeometryQueryProtocol","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryContainmentMetadata":{"role":"symbol","title":"MPGeometryContainmentMetadata","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPGeometryContainmentMetadata","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpgeometrycontainmentmetadata","navigatorTitle":[{"kind":"identifier","text":"MPGeometryContainmentMetadata"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata"},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null,"identifier":"MapsPeopleWhite.png","type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryQueryProtocol/containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"containsCoordinate"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"ignorePolygonHoles","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"containmentMetadata"},{"text":": ","kind":"text"},{"text":"MPGeometryContainmentMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometryContainmentMetadata"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/containscoordinate(_:ignorepolygonholes:containmentmetadata:)","navigatorTitle":[{"text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Check if the given coordinate is contained within the polygon, and optionally return the coordinate closest to the polygon."},{"text":" ","type":"text"},{"text":"If the polygon contains the coordinate, ‘coordinate’ is returned as nearestPoint.","type":"text"},{"type":"text","text":" "},{"text":"If coordinate is not contained, the nearest point is calculated.","type":"text"}],"role":"symbol","title":"containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"containsCoordinate:ignorePolygonHoles:containmentMetadata:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"containsCoordinate:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"},{"kind":"text","text":") "},{"text":"coordinate","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ignorePolygonHoles:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"ignorePolygonHoles"},{"kind":"text","text":" "},{"kind":"identifier","text":"containmentMetadata:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"MPGeometryContainmentMetadata","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometryContainmentMetadata"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"containmentMetadata"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol\/title","value":"MPGeometryQueryProtocol"},{"op":"replace","value":[{"text":"MPGeometryQueryProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryContainmentMetadata\/title","value":"MPGeometryContainmentMetadata","op":"replace"},{"value":[{"text":"MPGeometryContainmentMetadata","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryContainmentMetadata\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)\/title","value":"containsCoordinate:ignorePolygonHoles:containmentMetadata:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}