{"abstract":[{"text":"Check if the given line segment is fully contained within the polygon.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"containsLineSegmentFromCoordinate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"u"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"toCoordinate","kind":"externalParam"},{"kind":"text","text":" "},{"text":"v","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"u","content":[{"inlineContent":[{"type":"text","text":"Start coordinate of line segment to check for containment."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"End coordinate of line segment to check for containment.","type":"text"}],"type":"paragraph"}],"name":"v"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"True if the coordinate is inside the polygon boundary AND outside any holes in the polygon. False if the coordinate is outside the polygon, or inside any holes in the polygon.","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsLineSegmentFromCoordinate(_:toCoordinate:)"},"kind":"symbol","metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"containsLineSegmentFromCoordinate:toCoordinate:"}],"required":true,"externalID":"c:@M@MapsIndoors@objc(pl)MPGeometryQueryProtocol(im)containsLineSegmentFromCoordinate:toCoordinate:","modules":[{"name":"MapsIndoors"}],"title":"containsLineSegmentFromCoordinate(_:toCoordinate:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"containsLineSegmentFromCoordinate"},{"text":"(","kind":"text"},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"toCoordinate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"variants":[{"paths":["\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/containslinesegmentfromcoordinate(_:tocoordinate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/containslinesegmentfromcoordinate(_:tocoordinate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryQueryProtocol":{"role":"symbol","url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol","navigatorTitle":[{"text":"MPGeometryQueryProtocol","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPGeometryQueryProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol","title":"MPGeometryQueryProtocol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryQueryProtocol/containsLineSegmentFromCoordinate(_:toCoordinate:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsLineSegmentFromCoordinate(_:toCoordinate:)","abstract":[{"text":"Check if the given line segment is fully contained within the polygon.","type":"text"}],"navigatorTitle":[{"text":"containsLineSegmentFromCoordinate:toCoordinate:","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"containsLineSegmentFromCoordinate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toCoordinate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/containslinesegmentfromcoordinate(_:tocoordinate:)","required":true,"title":"containsLineSegmentFromCoordinate(_:toCoordinate:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null,"type":"image"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"containsLineSegmentFromCoordinate:toCoordinate:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsLineSegmentFromCoordinate:toCoordinate:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"text":"containsLineSegmentFromCoordinate:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":") "},{"text":"u","kind":"internalParam"},{"kind":"text","text":" "},{"text":"toCoordinate:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") "},{"text":"v","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol\/title","value":"MPGeometryQueryProtocol"},{"value":[{"kind":"identifier","text":"MPGeometryQueryProtocol"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1containsLineSegmentFromCoordinate(_:toCoordinate:)\/title","value":"containsLineSegmentFromCoordinate:toCoordinate:"},{"value":[{"kind":"text","text":"- "},{"text":"containsLineSegmentFromCoordinate:toCoordinate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1containsLineSegmentFromCoordinate(_:toCoordinate:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}