{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"containsLineSegment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"u"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"v"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"YES of the linesegment is fully inside the polygon boundary AND outside any holes in the polygon."}]}]},{"kind":"parameters","parameters":[{"name":"u","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"start coordinate of linesegment to check for containment."}]}]},{"name":"v","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"end coordinate of linesegment to check for containment."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/containslinesegment(from:to:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/containslinesegment(from:to:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsLineSegment(from:to:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Check if the given linesegment is fully contained within the polygon."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"containsLineSegmentFromCoordinate:toCoordinate:"}],"role":"symbol","title":"containsLineSegment(from:to:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"containsLineSegment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:objc(pl)MPGeometryQueryProtocol(im)containsLineSegmentFromCoordinate:toCoordinate:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPGeometryQueryProtocol/containsLineSegment(from:to:)":{"navigatorTitle":[{"kind":"identifier","text":"containsLineSegmentFromCoordinate:toCoordinate:"}],"role":"symbol","title":"containsLineSegment(from:to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"containsLineSegment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Check if the given linesegment is fully contained within the polygon."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsLineSegment(from:to:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/containslinesegment(from:to:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPGeometryQueryProtocol":{"role":"symbol","title":"MPGeometryQueryProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeometryQueryProtocol"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPGeometryQueryProtocol"}],"url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"containsLineSegmentFromCoordinate:toCoordinate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsLineSegmentFromCoordinate:toCoordinate:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"containsLineSegmentFromCoordinate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":")"},{"kind":"internalParam","text":"u"},{"kind":"text","text":" "},{"kind":"identifier","text":"toCoordinate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":")"},{"kind":"internalParam","text":"v"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1containsLineSegment(from:to:)\/title","value":"containsLineSegmentFromCoordinate:toCoordinate:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1containsLineSegment(from:to:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsLineSegmentFromCoordinate:toCoordinate:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol\/title","value":"MPGeometryQueryProtocol"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol\/fragments","value":[{"kind":"identifier","text":"MPGeometryQueryProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}