{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contains"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"point"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class","preciseIdentifier":"c:objc(cs)MPPoint","text":"MPPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"YES of the point is inside the polygon boundary AND outside any holes in the polygon."}]}]},{"kind":"parameters","parameters":[{"name":"point","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"point to check for containment."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/contains(_:)-cxpg"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/contains(_:)-cxpg"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/contains(_:)-cxpg","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Check if the given point is contained within the polygon."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"containsPoint:"}],"role":"symbol","title":"contains(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contains"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:objc(pl)MPGeometryQueryProtocol(im)containsPoint:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPGeometryQueryProtocol/contains(_:)-cxpg":{"navigatorTitle":[{"kind":"identifier","text":"containsPoint:"}],"role":"symbol","title":"contains(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contains"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Check if the given point is contained within the polygon."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/contains(_:)-cxpg","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/contains(_:)-cxpg"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPPoint-swift.class":{"role":"symbol","title":"MPPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPoint"}],"abstract":[{"type":"text","text":"Basic point geometry class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPoint"}],"url":"\/documentation\/mapsindoors\/mppoint-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPGeometryQueryProtocol":{"role":"symbol","title":"MPGeometryQueryProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeometryQueryProtocol"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPGeometryQueryProtocol"}],"url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"containsPoint:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsPoint:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"containsPoint:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class","preciseIdentifier":"c:objc(cs)MPPoint","text":"MPPoint"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"point"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1contains(_:)-cxpg\/title","value":"containsPoint:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1contains(_:)-cxpg\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsPoint:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class\/title","value":"MPPoint"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class\/fragments","value":[{"kind":"identifier","text":"MPPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol\/title","value":"MPGeometryQueryProtocol"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol\/fragments","value":[{"kind":"identifier","text":"MPGeometryQueryProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}