{"kind":"symbol","variants":[{"paths":["\/documentation\/mapsindoors\/mpcustomfloorselector\/floorindex"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpcustomfloorselector\/floorindex"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floorIndex"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"sections":[],"abstract":[{"text":"The current floor index of the floor selector. Setting this will switch to another Floor.","type":"text"}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/floorIndex","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPCustomFloorSelector(py)floorIndex","required":true,"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"floorIndex"}],"modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"floorIndex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"symbolKind":"property","title":"floorIndex"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomFloorSelector":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPCustomFloorSelector"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPCustomFloorSelector"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector","abstract":[{"text":"The protocol to conform to when building a floor selector for MapsIndoors.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpcustomfloorselector","title":"MPCustomFloorSelector"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomFloorSelector/floorIndex":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"floorIndex","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"floorIndex","kind":"identifier"}],"required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/floorIndex","abstract":[{"text":"The current floor index of the floor selector. Setting this will switch to another Floor.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpcustomfloorselector\/floorindex","title":"floorIndex"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"type":"image","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"floorIndex"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"floorIndex"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"floorIndex"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MPCustomFloorSelector","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector\/fragments","value":[{"text":"MPCustomFloorSelector","kind":"identifier"}],"op":"replace"},{"value":"floorIndex","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1floorIndex\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1floorIndex\/fragments","value":[{"text":"floorIndex","kind":"identifier"}],"op":"replace"}]}]}