{"abstract":[{"type":"text","text":"Invoked when the SDK indicates to hide the floor selector (e.g. no buildings are present in the viewport)."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onHide"},{"kind":"text","text":"()"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpcustomfloorselector\/onhide()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpcustomfloorselector\/onhide()"]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/onHide()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector"]]},"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPCustomFloorSelector(im)onHide","symbolKind":"method","navigatorTitle":[{"text":"onHide","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onHide"},{"kind":"text","text":"()"}],"role":"symbol","required":true,"modules":[{"name":"MapsIndoors"}],"roleHeading":"Instance Method","title":"onHide()"},"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomFloorSelector/onHide()":{"title":"onHide()","abstract":[{"type":"text","text":"Invoked when the SDK indicates to hide the floor selector (e.g. no buildings are present in the viewport)."}],"url":"\/documentation\/mapsindoors\/mpcustomfloorselector\/onhide()","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/onHide()","navigatorTitle":[{"kind":"identifier","text":"onHide"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onHide"},{"text":"()","kind":"text"}],"role":"symbol","required":true,"type":"topic","kind":"symbol"},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","type":"image","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomFloorSelector":{"title":"MPCustomFloorSelector","abstract":[{"text":"The protocol to conform to when building a floor selector for MapsIndoors.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpcustomfloorselector","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector","navigatorTitle":[{"kind":"identifier","text":"MPCustomFloorSelector"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPCustomFloorSelector"}],"role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"onHide","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onHide"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onHide"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1onHide()\/title","value":"onHide","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onHide"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1onHide()\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector\/title","op":"replace","value":"MPCustomFloorSelector"},{"op":"replace","value":[{"text":"MPCustomFloorSelector","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector\/fragments"}]}]}