{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/onShow()"},"sections":[],"abstract":[{"type":"text","text":"Invoked when the SDK indicates to show the floor selector (e.g. a building is present in the viewport)."}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpcustomfloorselector\/onshow()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpcustomfloorselector\/onshow()"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onShow"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Method","title":"onShow()","navigatorTitle":[{"text":"onShow","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPCustomFloorSelector(im)onShow","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onShow"},{"text":"()","kind":"text"}],"required":true,"modules":[{"name":"MapsIndoors"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomFloorSelector/onShow()":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/onShow()","title":"onShow()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onShow","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"onShow","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpcustomfloorselector\/onshow()","abstract":[{"type":"text","text":"Invoked when the SDK indicates to show the floor selector (e.g. a building is present in the viewport)."}],"required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomFloorSelector":{"title":"MPCustomFloorSelector","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPCustomFloorSelector","kind":"identifier"}],"abstract":[{"type":"text","text":"The protocol to conform to when building a floor selector for MapsIndoors."}],"url":"\/documentation\/mapsindoors\/mpcustomfloorselector","navigatorTitle":[{"text":"MPCustomFloorSelector","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"onShow","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onShow"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"onShow"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1onShow()\/title","op":"replace","value":"onShow"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1onShow()\/fragments","value":[{"kind":"text","text":"- "},{"text":"onShow","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector\/title","value":"MPCustomFloorSelector","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector\/fragments","value":[{"text":"MPCustomFloorSelector","kind":"identifier"}]}]}]}