{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/remove()"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector"]]},"metadata":{"modules":[{"name":"MapsIndoors"}],"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPCustomFloorSelector(im)remove","symbolKind":"method","navigatorTitle":[{"text":"remove","kind":"identifier"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"text":"()","kind":"text"}],"roleHeading":"Instance Method","title":"remove()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"text":"Removes the floor selector view from its super view (usually the map view).","type":"text"}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpcustomfloorselector\/remove()"]},{"paths":["\/documentation\/mapsindoors\/mpcustomfloorselector\/remove()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomFloorSelector":{"title":"MPCustomFloorSelector","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPCustomFloorSelector","kind":"identifier"}],"abstract":[{"type":"text","text":"The protocol to conform to when building a floor selector for MapsIndoors."}],"url":"\/documentation\/mapsindoors\/mpcustomfloorselector","navigatorTitle":[{"text":"MPCustomFloorSelector","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomFloorSelector/remove()":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/remove()","title":"remove()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"remove"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpcustomfloorselector\/remove()","abstract":[{"type":"text","text":"Removes the floor selector view from its super view (usually the map view)."}],"required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"remove"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"remove","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"remove","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"MPCustomFloorSelector","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector\/fragments","value":[{"kind":"identifier","text":"MPCustomFloorSelector"}],"op":"replace"},{"value":"remove","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1remove()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"remove","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1remove()\/fragments"}]}]}