{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"manager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEnter"},{"kind":"text","text":" "},{"kind":"internalParam","text":"region"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLRegion","preciseIdentifier":"c:objc(cs)CLRegion"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpnotificationshelper\/locationmanager(_:didenter:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpnotificationshelper\/locationmanager(_:didenter:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper\/locationManager(_:didEnter:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEnter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLRegion","preciseIdentifier":"c:objc(cs)CLRegion"},{"kind":"text","text":")"}],"title":"locationManager(_:didEnter:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPNotificationsHelper(cm)locationManager:didEnterRegion:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"locationManager:didEnterRegion:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPNotificationsHelper/locationManager(_:didEnter:)":{"role":"symbol","title":"locationManager(_:didEnter:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEnter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLRegion","preciseIdentifier":"c:objc(cs)CLRegion"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper\/locationManager(_:didEnter:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"locationManager:didEnterRegion:"}],"url":"\/documentation\/mapsindoors\/mpnotificationshelper\/locationmanager(_:didenter:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPNotificationsHelper":{"role":"symbol","title":"MPNotificationsHelper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPNotificationsHelper"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPNotificationsHelper"}],"url":"\/documentation\/mapsindoors\/mpnotificationshelper"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"locationManager:didEnterRegion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"locationManager:didEnterRegion:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"locationManager:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"manager"},{"kind":"text","text":" "},{"kind":"identifier","text":"didEnterRegion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLRegion","preciseIdentifier":"c:objc(cs)CLRegion"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"region"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPNotificationsHelper~1locationManager(_:didEnter:)\/title","value":"locationManager:didEnterRegion:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPNotificationsHelper~1locationManager(_:didEnter:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"locationManager:didEnterRegion:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPNotificationsHelper\/title","value":"MPNotificationsHelper"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPNotificationsHelper\/fragments","value":[{"kind":"identifier","text":"MPNotificationsHelper"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}