{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"monitorRegion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class","preciseIdentifier":"c:objc(cs)MPMessage","text":"MPMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"locationManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpnotificationshelper\/monitorregion(for:with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpnotificationshelper\/monitorregion(for:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper\/monitorRegion(for:with:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"monitorRegion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPMessage","preciseIdentifier":"c:objc(cs)MPMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":")"}],"title":"monitorRegion(for:with:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPNotificationsHelper(cm)monitorRegionForMessage:withLocationManager:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"monitorRegionForMessage:withLocationManager:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPNotificationsHelper/monitorRegion(for:with:)":{"role":"symbol","title":"monitorRegion(for:with:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"monitorRegion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPMessage","preciseIdentifier":"c:objc(cs)MPMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper\/monitorRegion(for:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"monitorRegionForMessage:withLocationManager:"}],"url":"\/documentation\/mapsindoors\/mpnotificationshelper\/monitorregion(for:with:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessage-swift.class":{"role":"symbol","title":"MPMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMessage"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMessage"}],"url":"\/documentation\/mapsindoors\/mpmessage-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPNotificationsHelper":{"role":"symbol","title":"MPNotificationsHelper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPNotificationsHelper"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPNotificationsHelper"}],"url":"\/documentation\/mapsindoors\/mpnotificationshelper"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"monitorRegionForMessage:withLocationManager:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"monitorRegionForMessage:withLocationManager:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"monitorRegionForMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class","preciseIdentifier":"c:objc(cs)MPMessage","text":"MPMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"message"},{"kind":"text","text":" "},{"kind":"identifier","text":"withLocationManager:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"locationManager"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPNotificationsHelper~1monitorRegion(for:with:)\/title","value":"monitorRegionForMessage:withLocationManager:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPNotificationsHelper~1monitorRegion(for:with:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"monitorRegionForMessage:withLocationManager:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class\/title","value":"MPMessage"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class\/fragments","value":[{"kind":"identifier","text":"MPMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPNotificationsHelper\/title","value":"MPNotificationsHelper"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPNotificationsHelper\/fragments","value":[{"kind":"identifier","text":"MPNotificationsHelper"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}