{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"External","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/mapsindoors\/mproutelegtype\/external"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mproutelegtype\/external"]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType\/External","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"metadata":{"title":"MPRouteLegType.External","role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"External","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@E@MPRouteLegType@MPRouteLegTypeExternal","navigatorTitle":[{"text":"MPRouteLegTypeExternal","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLegType/External":{"url":"\/documentation\/mapsindoors\/mproutelegtype\/external","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType\/External","title":"MPRouteLegType.External","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"External","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPRouteLegTypeExternal"}],"kind":"symbol","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLegType":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType","abstract":[],"url":"\/documentation\/mapsindoors\/mproutelegtype","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRouteLegType"}],"role":"symbol","title":"MPRouteLegType","navigatorTitle":[{"text":"MPRouteLegType","kind":"identifier"}]},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"type":"image","identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"MPRouteLegTypeExternal","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MPRouteLegTypeExternal"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"MPRouteLegTypeExternal","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"MPRouteLegTypeExternal","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLegType~1External\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLegType~1External\/fragments","op":"replace","value":[{"text":"MPRouteLegTypeExternal","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLegType\/title","value":"MPRouteLegType"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLegType\/fragments","value":[{"text":"MPRouteLegType","kind":"identifier"}],"op":"replace"}]}]}