{"kind":"symbol","variants":[{"paths":["\/documentation\/mapsindoors\/mproutelegtype\/mapsindoors"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mproutelegtype\/mapsindoors"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapsIndoors","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType\/MapsIndoors"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPRouteLegTypeMapsIndoors"}],"role":"symbol","modules":[{"name":"MapsIndoors"}],"title":"MPRouteLegType.MapsIndoors","externalID":"c:@M@MapsIndoors@E@MPRouteLegType@MPRouteLegTypeMapsIndoors","roleHeading":"Case","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLegType":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MPRouteLegType","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mproutelegtype","title":"MPRouteLegType","role":"symbol","navigatorTitle":[{"text":"MPRouteLegType","kind":"identifier"}],"type":"topic"},"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLegType/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType\/MapsIndoors","url":"\/documentation\/mapsindoors\/mproutelegtype\/mapsindoors","role":"symbol","abstract":[],"kind":"symbol","type":"topic","title":"MPRouteLegType.MapsIndoors","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsIndoors"}],"navigatorTitle":[{"text":"MPRouteLegTypeMapsIndoors","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MPRouteLegTypeMapsIndoors","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MPRouteLegTypeMapsIndoors","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"MPRouteLegTypeMapsIndoors","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"MPRouteLegType","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLegType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLegType\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPRouteLegType"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLegType~1MapsIndoors\/title","value":"MPRouteLegTypeMapsIndoors","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MPRouteLegTypeMapsIndoors"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLegType~1MapsIndoors\/fragments"}]}]}