{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"topicString"},{"kind":"text","text":" "},{"kind":"internalParam","text":"topic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpliveupdatetopic\/init(topicstring:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpliveupdatetopic\/init(topicstring:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic\/init(topicString:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initialises a Topic with a 7-component path formatted string, for example “datasetId\/venueId\/buildingId\/floorId\/roomId\/locationId\/domainType”"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"topicString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"init(topicString:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)MPLiveUpdateTopic(im)initWithTopicString:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTopicString:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveUpdateTopic/init(topicString:)":{"role":"symbol","title":"init(topicString:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"topicString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialises a Topic with a 7-component path formatted string, for example “datasetId\/venueId\/buildingId\/floorId\/roomId\/locationId\/domainType”"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic\/init(topicString:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithTopicString:"}],"url":"\/documentation\/mapsindoors\/mpliveupdatetopic\/init(topicstring:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveUpdateTopic":{"role":"symbol","title":"MPLiveUpdateTopic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveUpdateTopic"}],"abstract":[{"type":"text","text":"Topic model for a Live Update. A Live Update Topic is hierarchical in the way it is defined, and its relation to MapsIndoors data is derivable by its 7 components: Dataset, Venue, Building, Floor, Room, Location and Domain Type"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveUpdateTopic"}],"url":"\/documentation\/mapsindoors\/mpliveupdatetopic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithTopicString:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTopicString:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTopicString:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"topic"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic~1init(topicString:)\/title","value":"initWithTopicString:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic~1init(topicString:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTopicString:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic\/title","value":"MPLiveUpdateTopic"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic\/fragments","value":[{"kind":"identifier","text":"MPLiveUpdateTopic"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}