{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowAutomaticSwitch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toFloor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapcontroldelegate\/allowautomaticswitch(tofloor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmapcontroldelegate\/allowautomaticswitch(tofloor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/allowAutomaticSwitch(toFloor:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"allowAutomaticSwitchToFloor:"}],"role":"symbol","title":"allowAutomaticSwitch(toFloor:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowAutomaticSwitch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toFloor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:objc(pl)MPMapControlDelegate(im)allowAutomaticSwitchToFloor:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControlDelegate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPMapControlDelegate/allowAutomaticSwitch(toFloor:)":{"navigatorTitle":[{"kind":"identifier","text":"allowAutomaticSwitchToFloor:"}],"role":"symbol","title":"allowAutomaticSwitch(toFloor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowAutomaticSwitch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toFloor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/allowAutomaticSwitch(toFloor:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/allowautomaticswitch(tofloor:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControlDelegate":{"role":"symbol","title":"MPMapControlDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControlDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol specification to hold the floor change event."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControlDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMapControlDelegate"}],"url":"\/documentation\/mapsindoors\/mpmapcontroldelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"allowAutomaticSwitchToFloor:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"allowAutomaticSwitchToFloor:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"allowAutomaticSwitchToFloor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"toFloor"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1allowAutomaticSwitch(toFloor:)\/title","value":"allowAutomaticSwitchToFloor:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1allowAutomaticSwitch(toFloor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"allowAutomaticSwitchToFloor:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/title","value":"MPMapControlDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/fragments","value":[{"kind":"identifier","text":"MPMapControlDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}