{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTap"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"marker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSMarker","preciseIdentifier":"c:objc(cs)GMSMarker"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forLocationCluster"},{"kind":"text","text":" "},{"kind":"internalParam","text":"locations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","preciseIdentifier":"c:objc(cs)MPLocation","text":"MPLocation"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"moreZoomPossible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapcontroldelegate\/didtap(_:forlocationcluster:morezoompossible:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmapcontroldelegate\/didtap(_:forlocationcluster:morezoompossible:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didTap(_:forLocationCluster:moreZoomPossible:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didTapMarker:forLocationCluster:moreZoomPossible:"}],"role":"symbol","title":"didTap(_:forLocationCluster:moreZoomPossible:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTap"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSMarker","preciseIdentifier":"c:objc(cs)GMSMarker"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forLocationCluster"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"moreZoomPossible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:objc(pl)MPMapControlDelegate(im)didTapMarker:forLocationCluster:moreZoomPossible:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControlDelegate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class":{"role":"symbol","title":"MPLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"abstract":[{"type":"text","text":"This class holds the data for a single location and a marker to display the data on a map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControlDelegate/didTap(_:forLocationCluster:moreZoomPossible:)":{"navigatorTitle":[{"kind":"identifier","text":"didTapMarker:forLocationCluster:moreZoomPossible:"}],"role":"symbol","title":"didTap(_:forLocationCluster:moreZoomPossible:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTap"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSMarker","preciseIdentifier":"c:objc(cs)GMSMarker"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forLocationCluster"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"moreZoomPossible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didTap(_:forLocationCluster:moreZoomPossible:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/didtap(_:forlocationcluster:morezoompossible:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControlDelegate":{"role":"symbol","title":"MPMapControlDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControlDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol specification to hold the floor change event."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControlDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMapControlDelegate"}],"url":"\/documentation\/mapsindoors\/mpmapcontroldelegate"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didTapMarker:forLocationCluster:moreZoomPossible:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTapMarker:forLocationCluster:moreZoomPossible:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"didTapMarker:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSMarker","preciseIdentifier":"c:objc(cs)GMSMarker"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"marker"},{"kind":"text","text":" "},{"kind":"identifier","text":"forLocationCluster:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<MPLocation *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"locations"},{"kind":"text","text":" "},{"kind":"identifier","text":"moreZoomPossible:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"moreZoomPossible"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/title","value":"MPLocation"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/fragments","value":[{"kind":"identifier","text":"MPLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didTap(_:forLocationCluster:moreZoomPossible:)\/title","value":"didTapMarker:forLocationCluster:moreZoomPossible:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didTap(_:forLocationCluster:moreZoomPossible:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTapMarker:forLocationCluster:moreZoomPossible:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/title","value":"MPMapControlDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/fragments","value":[{"kind":"identifier","text":"MPMapControlDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}