{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxElementsPerGoogleDistanceMatrixRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdirectionsservice\/maxelementspergoogledistancematrixrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdirectionsservice\/maxelementspergoogledistancematrixrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsService\/maxElementsPerGoogleDistanceMatrixRequest","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The maximum number of elements to “spend” in each call to the Distance Matrix API."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxElementsPerGoogleDistanceMatrixRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"title":"maxElementsPerGoogleDistanceMatrixRequest","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPDirectionsService(cpy)maxElementsPerGoogleDistanceMatrixRequest","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"maxElementsPerGoogleDistanceMatrixRequest"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsService"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsService/maxElementsPerGoogleDistanceMatrixRequest":{"role":"symbol","title":"maxElementsPerGoogleDistanceMatrixRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxElementsPerGoogleDistanceMatrixRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The maximum number of elements to “spend” in each call to the Distance Matrix API."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsService\/maxElementsPerGoogleDistanceMatrixRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxElementsPerGoogleDistanceMatrixRequest"}],"url":"\/documentation\/mapsindoors\/mpdirectionsservice\/maxelementspergoogledistancematrixrequest"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsService":{"role":"symbol","title":"MPDirectionsService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsService"}],"abstract":[{"type":"text","text":"Directions service"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsService"}],"url":"\/documentation\/mapsindoors\/mpdirectionsservice"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"maxElementsPerGoogleDistanceMatrixRequest"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"maxElementsPerGoogleDistanceMatrixRequest"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxElementsPerGoogleDistanceMatrixRequest"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsService~1maxElementsPerGoogleDistanceMatrixRequest\/title","value":"maxElementsPerGoogleDistanceMatrixRequest"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsService~1maxElementsPerGoogleDistanceMatrixRequest\/fragments","value":[{"kind":"identifier","text":"maxElementsPerGoogleDistanceMatrixRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsService\/title","value":"MPDirectionsService"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsService\/fragments","value":[{"kind":"identifier","text":"MPDirectionsService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}