{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"routing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"directionsQuery"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsQuery","preciseIdentifier":"c:objc(cs)MPDirectionsQuery","text":"MPDirectionsQuery"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"directionsQuery","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Directions query"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdirectionsservice\/routing(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdirectionsservice\/routing(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsService\/routing(with:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get directions."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"routing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDirectionsQuery","preciseIdentifier":"c:objc(cs)MPDirectionsQuery"},{"kind":"text","text":")"}],"title":"routing(with:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPDirectionsService(im)routingWithQuery:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"routingWithQuery:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsService"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsService/routing(with:)":{"role":"symbol","title":"routing(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"routing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDirectionsQuery","preciseIdentifier":"c:objc(cs)MPDirectionsQuery"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get directions."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsService\/routing(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"routingWithQuery:"}],"url":"\/documentation\/mapsindoors\/mpdirectionsservice\/routing(with:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsService":{"role":"symbol","title":"MPDirectionsService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsService"}],"abstract":[{"type":"text","text":"Directions service"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsService"}],"url":"\/documentation\/mapsindoors\/mpdirectionsservice"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsQuery":{"role":"symbol","title":"MPDirectionsQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsQuery"}],"abstract":[{"type":"text","text":"Directions query model."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsQuery"}],"url":"\/documentation\/mapsindoors\/mpdirectionsquery"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"routingWithQuery:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"routingWithQuery:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"routingWithQuery:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsQuery","preciseIdentifier":"c:objc(cs)MPDirectionsQuery","text":"MPDirectionsQuery"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"directionsQuery"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsService~1routing(with:)\/title","value":"routingWithQuery:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsService~1routing(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"routingWithQuery:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsService\/title","value":"MPDirectionsService"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsService\/fragments","value":[{"kind":"identifier","text":"MPDirectionsService"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/title","value":"MPDirectionsQuery"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/fragments","value":[{"kind":"identifier","text":"MPDirectionsQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}