{"variants":[{"paths":["\/documentation\/mapsindoors\/mpdirectionsservice\/routingwith(query:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsservice\/routingwith(query:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService\/routingWith(query:)"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"routingWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDirectionsQuery","text":"MPDirectionsQuery","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRoute","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","text":"MPRoute","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Directions query.","type":"text"}]}],"name":"query"}]},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A calculated route or an error."}]}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"title":"routingWith(query:)","navigatorTitle":[{"kind":"identifier","text":"routingWithQuery:completionHandler:"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"MapsIndoors"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPDirectionsService(im)routingWithQuery:completionHandler:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"routingWith","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"query"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDirectionsQuery","text":"MPDirectionsQuery","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"MPRoute","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRoute","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"required":true},"kind":"symbol","abstract":[{"type":"text","text":"Get directions as specified in the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery"},{"text":".","type":"text"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPRoute"}],"type":"topic","url":"\/documentation\/mapsindoors\/mproute","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","abstract":[{"text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","isActive":true,"type":"reference"},{"type":"text","text":"."}],"title":"MPRoute","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPRoute","kind":"identifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsService/routingWith(query:)":{"required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService\/routingWith(query:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"routingWith","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDirectionsQuery","kind":"typeIdentifier","text":"MPDirectionsQuery"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"MPRoute","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRoute","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"routingWithQuery:completionHandler:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdirectionsservice\/routingwith(query:)","abstract":[{"type":"text","text":"Get directions as specified in the "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery","isActive":true,"type":"reference"},{"type":"text","text":"."}],"title":"routingWith(query:)","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsService":{"kind":"symbol","navigatorTitle":[{"text":"MPDirectionsService","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdirectionsservice","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","abstract":[],"title":"MPDirectionsService","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDirectionsService","kind":"identifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery":{"kind":"symbol","navigatorTitle":[{"text":"MPDirectionsQuery","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdirectionsquery","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery","title":"MPDirectionsQuery","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDirectionsQuery","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"routingWithQuery:completionHandler:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"routingWithQuery:completionHandler:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"routingWithQuery:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDirectionsQuery","text":"MPDirectionsQuery"},{"text":" *) ","kind":"text"},{"text":"query","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(id<MPRoute>, NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*Qo@M@MapsIndoors@objc(pl)MPRoute#*$objc(cs)NSError)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"MPRoute","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/title"},{"value":[{"kind":"identifier","text":"MPRoute"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService~1routingWith(query:)\/title","op":"replace","value":"routingWithQuery:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService~1routingWith(query:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"routingWithQuery:completionHandler:"}]},{"value":"MPDirectionsService","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/fragments","value":[{"text":"MPDirectionsService","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/title","value":"MPDirectionsQuery","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/fragments","value":[{"kind":"identifier","text":"MPDirectionsQuery"}]}]}]}