{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/fields"},{"type":"text","text":" to get properties like image, description etc."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocation-swift.class\/image"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocation-swift.class\/image"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/image","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Location image."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"image"}],"role":"symbol","title":"image","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"c:objc(cs)MPLocation(py)image","modules":[{"name":"MapsIndoors"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":" "}]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/image":{"deprecated":true,"role":"symbol","title":"image","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Location image."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/image","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"image"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/image"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class":{"role":"symbol","title":"MPLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"abstract":[{"type":"text","text":"This class holds the data for a single location and a marker to display the data on a map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/fields":{"role":"symbol","title":"fields","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"MPLocationField","preciseIdentifier":"c:objc(cs)MPLocationField"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Custom properties associated with the location object."},{"type":"text","text":" "},{"type":"text","text":"Keys are case sensitive.  For case-insensitive access to custom properties use "},{"type":"codeVoice","code":"getFieldForKey:"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/fields","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fields"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/fields"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"image"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"image"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" * "},{"kind":"identifier","text":"image"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1image\/title","value":"image"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1image\/fragments","value":[{"kind":"identifier","text":"image"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/title","value":"MPLocation"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/fragments","value":[{"kind":"identifier","text":"MPLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1fields\/title","value":"fields"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1fields\/fragments","value":[{"kind":"identifier","text":"fields"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}