{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"properties"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMutableDictionary","preciseIdentifier":"c:objc(cs)NSMutableDictionary"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocation-swift.class\/properties"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocation-swift.class\/properties"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/properties","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Dictionary of location properties. The keys ‘image’ and ‘description’ will always be present, and possibly others, such as ‘address’, ‘contact’, ‘openinghours’ and ‘_tags’ or your own data structure."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"properties"}],"role":"symbol","title":"properties","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"properties"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMutableDictionary","preciseIdentifier":"c:objc(cs)NSMutableDictionary"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"c:objc(cs)MPLocation(py)properties","modules":[{"name":"MapsIndoors"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use fields dictionary instead"}]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class":{"role":"symbol","title":"MPLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"abstract":[{"type":"text","text":"This class holds the data for a single location and a marker to display the data on a map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/properties":{"deprecated":true,"role":"symbol","title":"properties","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"properties"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMutableDictionary","preciseIdentifier":"c:objc(cs)NSMutableDictionary"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Dictionary of location properties. The keys ‘image’ and ‘description’ will always be present, and possibly others, such as ‘address’, ‘contact’, ‘openinghours’ and ‘_tags’ or your own data structure."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/properties","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"properties"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/properties"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"properties"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"properties"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSMutableDictionary","preciseIdentifier":"c:objc(cs)NSMutableDictionary"},{"kind":"text","text":" *"},{"kind":"identifier","text":"properties"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/title","value":"MPLocation"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/fragments","value":[{"kind":"identifier","text":"MPLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1properties\/title","value":"properties"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1properties\/fragments","value":[{"kind":"identifier","text":"properties"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}