{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLocationsReady"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"locationData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDataset","preciseIdentifier":"c:objc(cs)MPLocationDataset","text":"MPLocationDataset"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationsproviderdelegate\/onlocationsready(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationsproviderdelegate\/onlocationsready(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderDelegate\/onLocationsReady(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onLocationsReady:"}],"role":"symbol","title":"onLocationsReady(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLocationsReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocationDataset","preciseIdentifier":"c:objc(cs)MPLocationDataset"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MPLocationsProviderDelegate(im)onLocationsReady:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderDelegate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDataset":{"role":"symbol","title":"MPLocationDataset","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationDataset"}],"abstract":[{"type":"text","text":"Dataset that holds locations, searched results and a filter."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDataset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationDataset"}],"url":"\/documentation\/mapsindoors\/mplocationdataset"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderDelegate":{"role":"symbol","title":"MPLocationsProviderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationsProviderDelegate"}],"abstract":[{"type":"text","text":"Locations provider delegate."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationsProviderDelegate"}],"url":"\/documentation\/mapsindoors\/mplocationsproviderdelegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderDelegate/onLocationsReady(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onLocationsReady:"}],"role":"symbol","title":"onLocationsReady(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLocationsReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocationDataset","preciseIdentifier":"c:objc(cs)MPLocationDataset"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderDelegate\/onLocationsReady(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderdelegate\/onlocationsready(_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onLocationsReady:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onLocationsReady:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onLocationsReady:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDataset","preciseIdentifier":"c:objc(cs)MPLocationDataset","text":"MPLocationDataset"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"locationData"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDataset\/title","value":"MPLocationDataset"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDataset\/fragments","value":[{"kind":"identifier","text":"MPLocationDataset"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderDelegate\/title","value":"MPLocationsProviderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderDelegate\/fragments","value":[{"kind":"identifier","text":"MPLocationsProviderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderDelegate~1onLocationsReady(_:)\/title","value":"onLocationsReady:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderDelegate~1onLocationsReady(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onLocationsReady:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}