{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDistanceMatrixResultReady"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"distanceMatrixResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult","preciseIdentifier":"c:objc(cs)MPDistanceMatrixResult","text":"MPDistanceMatrixResult"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdistancematrixproviderdelegate\/ondistancematrixresultready(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdistancematrixproviderdelegate\/ondistancematrixresultready(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProviderDelegate\/onDistanceMatrixResultReady(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onDistanceMatrixResultReady:"}],"role":"symbol","title":"onDistanceMatrixResultReady(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDistanceMatrixResultReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPDistanceMatrixResult","preciseIdentifier":"c:objc(cs)MPDistanceMatrixResult"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MPDistanceMatrixProviderDelegate(im)onDistanceMatrixResultReady:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProviderDelegate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixProviderDelegate":{"role":"symbol","title":"MPDistanceMatrixProviderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDistanceMatrixProviderDelegate"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProviderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDistanceMatrixProviderDelegate"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixproviderdelegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixProviderDelegate/onDistanceMatrixResultReady(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onDistanceMatrixResultReady:"}],"role":"symbol","title":"onDistanceMatrixResultReady(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDistanceMatrixResultReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPDistanceMatrixResult","preciseIdentifier":"c:objc(cs)MPDistanceMatrixResult"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProviderDelegate\/onDistanceMatrixResultReady(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpdistancematrixproviderdelegate\/ondistancematrixresultready(_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixResult":{"role":"symbol","title":"MPDistanceMatrixResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDistanceMatrixResult"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDistanceMatrixResult"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixresult"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onDistanceMatrixResultReady:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDistanceMatrixResultReady:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onDistanceMatrixResultReady:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult","preciseIdentifier":"c:objc(cs)MPDistanceMatrixResult","text":"MPDistanceMatrixResult"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"distanceMatrixResult"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProviderDelegate\/title","value":"MPDistanceMatrixProviderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProviderDelegate\/fragments","value":[{"kind":"identifier","text":"MPDistanceMatrixProviderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProviderDelegate~1onDistanceMatrixResultReady(_:)\/title","value":"onDistanceMatrixResultReady:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProviderDelegate~1onDistanceMatrixResultReady(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDistanceMatrixResultReady:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult\/title","value":"MPDistanceMatrixResult"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult\/fragments","value":[{"kind":"identifier","text":"MPDistanceMatrixResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}