{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessagesReady"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"messages"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmessageproviderdelegate\/onmessagesready(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmessageproviderdelegate\/onmessagesready(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessageProviderDelegate\/onMessagesReady(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onMessagesReady:"}],"role":"symbol","title":"onMessagesReady(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessagesReady"},{"kind":"text","text":"(["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:objc(pl)MPMessageProviderDelegate(im)onMessagesReady:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessageProviderDelegate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPMessageProviderDelegate":{"role":"symbol","title":"MPMessageProviderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMessageProviderDelegate"}],"abstract":[{"type":"text","text":"Messages provider delegate."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessageProviderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMessageProviderDelegate"}],"url":"\/documentation\/mapsindoors\/mpmessageproviderdelegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessageProviderDelegate/onMessagesReady(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessagesReady:"}],"role":"symbol","title":"onMessagesReady(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessagesReady"},{"kind":"text","text":"(["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessageProviderDelegate\/onMessagesReady(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpmessageproviderdelegate\/onmessagesready(_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onMessagesReady:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessagesReady:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onMessagesReady:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<MPMessage>","preciseIdentifier":"c:Q$objc(cs)NSArrayobjc(pl)MPMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"messages"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessageProviderDelegate\/title","value":"MPMessageProviderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessageProviderDelegate\/fragments","value":[{"kind":"identifier","text":"MPMessageProviderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessageProviderDelegate~1onMessagesReady(_:)\/title","value":"onMessagesReady:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessageProviderDelegate~1onMessagesReady(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessagesReady:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}