{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSolutionWithCompletion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpSolutionHandlerBlockType","preciseIdentifier":"c:MPSolutionProvider.h@T@mpSolutionHandlerBlockType","text":"mpSolutionHandlerBlockType"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpsolutionprovider\/getsolutionwithcompletion(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpsolutionprovider\/getsolutionwithcompletion(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/getSolutionWithCompletion(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get solution from this provider and supply a callback handler function."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSolutionWithCompletion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpSolutionHandlerBlockType","preciseIdentifier":"c:MPSolutionProvider.h@T@mpSolutionHandlerBlockType"},{"kind":"text","text":"?)"}],"title":"getSolutionWithCompletion(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPSolutionProvider(im)getSolutionWithCompletion:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getSolutionWithCompletion:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPSolutionProvider/getSolutionWithCompletion(_:)":{"role":"symbol","title":"getSolutionWithCompletion(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSolutionWithCompletion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpSolutionHandlerBlockType","preciseIdentifier":"c:MPSolutionProvider.h@T@mpSolutionHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get solution from this provider and supply a callback handler function."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/getSolutionWithCompletion(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getSolutionWithCompletion:"}],"url":"\/documentation\/mapsindoors\/mpsolutionprovider\/getsolutionwithcompletion(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/mpSolutionHandlerBlockType":{"role":"symbol","title":"mpSolutionHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpSolutionHandlerBlockType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpSolutionHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpSolutionHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpsolutionhandlerblocktype"},"doc://MapsIndoors/documentation/MapsIndoors/MPSolutionProvider":{"role":"symbol","title":"MPSolutionProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSolutionProvider"}],"abstract":[{"type":"text","text":"Solution provider interface, that defines a delegate and a method for solution queries."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPSolutionProvider"}],"url":"\/documentation\/mapsindoors\/mpsolutionprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getSolutionWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getSolutionWithCompletion:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getSolutionWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(MPSolution *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)MPSolution#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider~1getSolutionWithCompletion(_:)\/title","value":"getSolutionWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider~1getSolutionWithCompletion(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getSolutionWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpSolutionHandlerBlockType\/title","value":"mpSolutionHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpSolutionHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpSolutionHandlerBlockType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider\/title","value":"MPSolutionProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider\/fragments","value":[{"kind":"identifier","text":"MPSolutionProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}