{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserRoles"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpUserRoleCompletion","preciseIdentifier":"c:MPSolutionProvider.h@T@mpUserRoleCompletion","text":"mpUserRoleCompletion"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"called when user roles or error has been found"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpsolutionprovider\/getuserroles(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpsolutionprovider\/getuserroles(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/getUserRoles(completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get user roles associated with the solution"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserRoles"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpUserRoleCompletion","preciseIdentifier":"c:MPSolutionProvider.h@T@mpUserRoleCompletion"},{"kind":"text","text":")"}],"title":"getUserRoles(completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPSolutionProvider(im)getUserRolesWithCompletion:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getUserRolesWithCompletion:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPSolutionProvider":{"role":"symbol","title":"MPSolutionProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSolutionProvider"}],"abstract":[{"type":"text","text":"Solution provider interface, that defines a delegate and a method for solution queries."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPSolutionProvider"}],"url":"\/documentation\/mapsindoors\/mpsolutionprovider"},"doc://MapsIndoors/documentation/MapsIndoors/MPSolutionProvider/getUserRoles(completion:)":{"role":"symbol","title":"getUserRoles(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserRoles"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpUserRoleCompletion","preciseIdentifier":"c:MPSolutionProvider.h@T@mpUserRoleCompletion"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get user roles associated with the solution"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/getUserRoles(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getUserRolesWithCompletion:"}],"url":"\/documentation\/mapsindoors\/mpsolutionprovider\/getuserroles(completion:)"},"doc://MapsIndoors/documentation/MapsIndoors/mpUserRoleCompletion":{"role":"symbol","title":"mpUserRoleCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpUserRoleCompletion"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpUserRoleCompletion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpUserRoleCompletion"}],"url":"\/documentation\/mapsindoors\/mpuserrolecompletion"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getUserRolesWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUserRolesWithCompletion:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getUserRolesWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<MPUserRole *> *, NSError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider\/title","value":"MPSolutionProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider\/fragments","value":[{"kind":"identifier","text":"MPSolutionProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider~1getUserRoles(completion:)\/title","value":"getUserRolesWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider~1getUserRoles(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUserRolesWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpUserRoleCompletion\/title","value":"mpUserRoleCompletion"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpUserRoleCompletion\/fragments","value":[{"kind":"identifier","text":"mpUserRoleCompletion"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}