{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOfflineDataAvailable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSolutionId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"solutionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"YES if offline or preloaded data is available, else NO,"}]}]},{"kind":"parameters","parameters":[{"name":"solutionId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"solutionId to check for offline data availability."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpsolutionprovider\/isofflinedataavailable(forsolutionid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpsolutionprovider\/isofflinedataavailable(forsolutionid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/isOfflineDataAvailable(forSolutionId:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Determine if cached or preloaded data is available for the given solutionId."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOfflineDataAvailable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSolutionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isOfflineDataAvailable(forSolutionId:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPSolutionProvider(cm)isOfflineDataAvailableForSolutionId:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"isOfflineDataAvailableForSolutionId:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPSolutionProvider":{"role":"symbol","title":"MPSolutionProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSolutionProvider"}],"abstract":[{"type":"text","text":"Solution provider interface, that defines a delegate and a method for solution queries."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPSolutionProvider"}],"url":"\/documentation\/mapsindoors\/mpsolutionprovider"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPSolutionProvider/isOfflineDataAvailable(forSolutionId:)":{"role":"symbol","title":"isOfflineDataAvailable(forSolutionId:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOfflineDataAvailable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSolutionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determine if cached or preloaded data is available for the given solutionId."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/isOfflineDataAvailable(forSolutionId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isOfflineDataAvailableForSolutionId:"}],"url":"\/documentation\/mapsindoors\/mpsolutionprovider\/isofflinedataavailable(forsolutionid:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"isOfflineDataAvailableForSolutionId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isOfflineDataAvailableForSolutionId:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isOfflineDataAvailableForSolutionId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"solutionId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider\/title","value":"MPSolutionProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider\/fragments","value":[{"kind":"identifier","text":"MPSolutionProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider~1isOfflineDataAvailable(forSolutionId:)\/title","value":"isOfflineDataAvailableForSolutionId:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider~1isOfflineDataAvailable(forSolutionId:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isOfflineDataAvailableForSolutionId:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}