{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dontCache"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"codeListing","syntax":null,"code":["Don't cache. Data will be removed at any point after usage."]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcachingstrategy\/dontcache"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachingstrategy\/dontcache"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/dontCache","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dontCache"}],"title":"MPDataSetCachingStrategy.dontCache","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MPDataSetCachingStrategy@MPDataSetCachingStrategyDontCache","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPDataSetCachingStrategyDontCache"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCachingStrategy":{"role":"symbol","title":"MPDataSetCachingStrategy","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCachingStrategy"}],"abstract":[{"type":"text","text":"Data set caching strategy."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCachingStrategy"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachingstrategy"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCachingStrategy/dontCache":{"role":"symbol","title":"MPDataSetCachingStrategy.dontCache","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dontCache"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/dontCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCachingStrategyDontCache"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachingstrategy\/dontcache"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MPDataSetCachingStrategyDontCache"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPDataSetCachingStrategyDontCache"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MPDataSetCachingStrategyDontCache"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy\/title","value":"MPDataSetCachingStrategy"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy\/fragments","value":[{"kind":"identifier","text":"MPDataSetCachingStrategy"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy~1dontCache\/title","value":"MPDataSetCachingStrategyDontCache"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy~1dontCache\/fragments","value":[{"kind":"identifier","text":"MPDataSetCachingStrategyDontCache"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}