{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderDelegate","preciseIdentifier":"c:objc(pl)MPBeaconProviderDelegate","text":"MPBeaconProviderDelegate"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbeaconproviderprotocol\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbeaconproviderprotocol\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderProtocol\/delegate","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"role":"symbol","title":"delegate","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPBeaconProviderDelegate","preciseIdentifier":"c:objc(pl)MPBeaconProviderDelegate"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"c:objc(pl)MPBeaconProvider(py)delegate","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderProtocol"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPBeaconProviderDelegate":{"role":"symbol","title":"MPBeaconProviderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeaconProviderDelegate"}],"abstract":[{"type":"text","text":"Beacons provider delegate."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBeaconProviderDelegate"}],"url":"\/documentation\/mapsindoors\/mpbeaconproviderdelegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeaconProviderProtocol/delegate":{"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPBeaconProviderDelegate","preciseIdentifier":"c:objc(pl)MPBeaconProviderDelegate"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderProtocol\/delegate","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpbeaconproviderprotocol\/delegate"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeaconProviderProtocol":{"role":"symbol","title":"MPBeaconProviderProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeaconProviderProtocol"}],"abstract":[{"type":"text","text":"Beacons provider protocol."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBeaconProviderProtocol"}],"url":"\/documentation\/mapsindoors\/mpbeaconproviderprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<MPBeaconProviderDelegate>","preciseIdentifier":"c:Qoobjc(pl)MPBeaconProviderDelegate"},{"kind":"text","text":" *"},{"kind":"identifier","text":"delegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProviderDelegate\/title","value":"MPBeaconProviderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProviderDelegate\/fragments","value":[{"kind":"identifier","text":"MPBeaconProviderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProviderProtocol~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProviderProtocol~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProviderProtocol\/title","value":"MPBeaconProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProviderProtocol\/fragments","value":[{"kind":"identifier","text":"MPBeaconProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}