{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onVenuesReady"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"venueCollection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueCollection","preciseIdentifier":"c:objc(cs)MPVenueCollection","text":"MPVenueCollection"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpvenueproviderdelegate\/onvenuesready(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpvenueproviderdelegate\/onvenuesready(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate\/onVenuesReady(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onVenuesReady:"}],"role":"symbol","title":"onVenuesReady(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onVenuesReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPVenueCollection","preciseIdentifier":"c:objc(cs)MPVenueCollection"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MPVenueProviderDelegate(im)onVenuesReady:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPVenueCollection":{"role":"symbol","title":"MPVenueCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenueCollection"}],"abstract":[{"type":"text","text":"Venue collection model, just holds an array."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenueCollection"}],"url":"\/documentation\/mapsindoors\/mpvenuecollection"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProviderDelegate/onVenuesReady(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onVenuesReady:"}],"role":"symbol","title":"onVenuesReady(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onVenuesReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPVenueCollection","preciseIdentifier":"c:objc(cs)MPVenueCollection"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate\/onVenuesReady(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpvenueproviderdelegate\/onvenuesready(_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProviderDelegate":{"role":"symbol","title":"MPVenueProviderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenueProviderDelegate"}],"abstract":[{"type":"text","text":"Venue provider delegate."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenueProviderDelegate"}],"url":"\/documentation\/mapsindoors\/mpvenueproviderdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onVenuesReady:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onVenuesReady:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onVenuesReady:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueCollection","preciseIdentifier":"c:objc(cs)MPVenueCollection","text":"MPVenueCollection"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"venueCollection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueCollection\/title","value":"MPVenueCollection"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueCollection\/fragments","value":[{"kind":"identifier","text":"MPVenueCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProviderDelegate~1onVenuesReady(_:)\/title","value":"onVenuesReady:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProviderDelegate~1onVenuesReady(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onVenuesReady:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProviderDelegate\/title","value":"MPVenueProviderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProviderDelegate\/fragments","value":[{"kind":"identifier","text":"MPVenueProviderDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}