{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRouteResultReady"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"route"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class","preciseIdentifier":"c:objc(cs)MPRoute","text":"MPRoute"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mproutingproviderdelegate\/onrouteresultready(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mproutingproviderdelegate\/onrouteresultready(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProviderDelegate\/onRouteResultReady(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onRouteResultReady:"}],"role":"symbol","title":"onRouteResultReady(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRouteResultReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPRoute","preciseIdentifier":"c:objc(cs)MPRoute"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MPRoutingProviderDelegate(im)onRouteResultReady:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProviderDelegate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProviderDelegate/onRouteResultReady(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onRouteResultReady:"}],"role":"symbol","title":"onRouteResultReady(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRouteResultReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPRoute","preciseIdentifier":"c:objc(cs)MPRoute"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProviderDelegate\/onRouteResultReady(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mproutingproviderdelegate\/onrouteresultready(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoute-swift.class":{"role":"symbol","title":"MPRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoute"}],"abstract":[{"type":"text","text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the "},{"type":"codeVoice","code":"MPDirectionsService"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRoute"}],"url":"\/documentation\/mapsindoors\/mproute-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProviderDelegate":{"role":"symbol","title":"MPRoutingProviderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoutingProviderDelegate"}],"abstract":[{"type":"text","text":"Directions service delegate"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProviderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRoutingProviderDelegate"}],"url":"\/documentation\/mapsindoors\/mproutingproviderdelegate"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onRouteResultReady:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRouteResultReady:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onRouteResultReady:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class","preciseIdentifier":"c:objc(cs)MPRoute","text":"MPRoute"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"route"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProviderDelegate~1onRouteResultReady(_:)\/title","value":"onRouteResultReady:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProviderDelegate~1onRouteResultReady(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRouteResultReady:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class\/title","value":"MPRoute"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class\/fragments","value":[{"kind":"identifier","text":"MPRoute"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProviderDelegate\/title","value":"MPRoutingProviderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProviderDelegate\/fragments","value":[{"kind":"identifier","text":"MPRoutingProviderDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}