{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderDelegate","preciseIdentifier":"c:objc(pl)MPLocationsProviderDelegate","text":"MPLocationsProviderDelegate"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationsproviderprotocol\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationsproviderprotocol\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/delegate","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"role":"symbol","title":"delegate","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationsProviderDelegate","preciseIdentifier":"c:objc(pl)MPLocationsProviderDelegate"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"c:objc(pl)MPLocationsProvider(py)delegate","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderDelegate":{"role":"symbol","title":"MPLocationsProviderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationsProviderDelegate"}],"abstract":[{"type":"text","text":"Locations provider delegate."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationsProviderDelegate"}],"url":"\/documentation\/mapsindoors\/mplocationsproviderdelegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/delegate":{"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationsProviderDelegate","preciseIdentifier":"c:objc(pl)MPLocationsProviderDelegate"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/delegate","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/delegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol":{"role":"symbol","title":"MPLocationsProviderProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationsProviderProtocol"}],"abstract":[{"type":"text","text":"Locations provider protocol."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationsProviderProtocol"}],"url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<MPLocationsProviderDelegate>","preciseIdentifier":"c:Qoobjc(pl)MPLocationsProviderDelegate"},{"kind":"text","text":" *"},{"kind":"identifier","text":"delegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderDelegate\/title","value":"MPLocationsProviderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderDelegate\/fragments","value":[{"kind":"identifier","text":"MPLocationsProviderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol\/title","value":"MPLocationsProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol\/fragments","value":[{"kind":"identifier","text":"MPLocationsProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}