{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationWithId"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"locationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocationwithid(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocationwithid(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationWithId(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Method to query a unique location from the provider based on an id."},{"type":"text","text":" "},{"type":"text","text":"Data is returned in the current translation ([MapsIndoors getLanguage])."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getLocationWithId:"}],"role":"symbol","title":"getLocationWithId(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationWithId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MPLocationsProvider(im)getLocationWithId:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/getLocationWithId(_:)":{"navigatorTitle":[{"kind":"identifier","text":"getLocationWithId:"}],"role":"symbol","title":"getLocationWithId(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationWithId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method to query a unique location from the provider based on an id."},{"type":"text","text":" "},{"type":"text","text":"Data is returned in the current translation ([MapsIndoors getLanguage])."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationWithId(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocationwithid(_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol":{"role":"symbol","title":"MPLocationsProviderProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationsProviderProtocol"}],"abstract":[{"type":"text","text":"Locations provider protocol."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationsProviderProtocol"}],"url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getLocationWithId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationWithId:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getLocationWithId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"locationId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationWithId(_:)\/title","value":"getLocationWithId:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationWithId(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationWithId:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol\/title","value":"MPLocationsProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol\/fragments","value":[{"kind":"identifier","text":"MPLocationsProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}