{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocations"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocations()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocations()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocations()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Method to initiate fetching of all locations from the provider in the current translation ([MapsIndoors getLanguage])."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getLocations"}],"role":"symbol","title":"getLocations()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocations"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:objc(pl)MPLocationsProvider(im)getLocations","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/getLocations()":{"navigatorTitle":[{"kind":"identifier","text":"getLocations"}],"role":"symbol","title":"getLocations()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocations"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Method to initiate fetching of all locations from the provider in the current translation ([MapsIndoors getLanguage])."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocations()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocations()"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol":{"role":"symbol","title":"MPLocationsProviderProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationsProviderProtocol"}],"abstract":[{"type":"text","text":"Locations provider protocol."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationsProviderProtocol"}],"url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getLocations"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocations"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getLocations"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocations()\/title","value":"getLocations"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocations()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocations"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol\/title","value":"MPLocationsProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol\/fragments","value":[{"kind":"identifier","text":"MPLocationsProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}