{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class","preciseIdentifier":"c:objc(cs)MPBuilding","text":"MPBuilding"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbuildingcollection\/buildings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbuildingcollection\/buildings"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingCollection\/buildings","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPBuilding","preciseIdentifier":"c:objc(cs)MPBuilding"},{"kind":"text","text":"]?"}],"title":"buildings","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPBuildingCollection(py)buildings","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"buildings"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingCollection"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class":{"role":"symbol","title":"MPBuilding","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuilding"}],"abstract":[{"type":"text","text":"Holds relevant data for a single building, and the buildings floor levels."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBuilding"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuildingCollection/buildings":{"role":"symbol","title":"buildings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPBuilding","preciseIdentifier":"c:objc(cs)MPBuilding"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingCollection\/buildings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildings"}],"url":"\/documentation\/mapsindoors\/mpbuildingcollection\/buildings"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuildingCollection":{"role":"symbol","title":"MPBuildingCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuildingCollection"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBuildingCollection"}],"url":"\/documentation\/mapsindoors\/mpbuildingcollection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"buildings"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"buildings"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<MPBuilding *><MPBuilding>","preciseIdentifier":"c:Q$objc(cs)NSArrayobjc(pl)MPBuilding"},{"kind":"text","text":" *"},{"kind":"identifier","text":"buildings"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class\/title","value":"MPBuilding"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class\/fragments","value":[{"kind":"identifier","text":"MPBuilding"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingCollection~1buildings\/title","value":"buildings"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingCollection~1buildings\/fragments","value":[{"kind":"identifier","text":"buildings"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingCollection\/title","value":"MPBuildingCollection"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingCollection\/fragments","value":[{"kind":"identifier","text":"MPBuildingCollection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}