{"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"geometry","kind":"identifier"},{"kind":"text","text":": "},{"text":"MPGeometry","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometry","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometry","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"text":"The geometry representing the location.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mplocation\/geometry"]},{"paths":["\/documentation\/mapsindoors\/mplocation\/geometry"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"geometry"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometry","text":"MPGeometry"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"geometry"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPLocation(py)geometry","modules":[{"name":"MapsIndoors"}],"roleHeading":"Instance Property","title":"geometry","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/geometry","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"title":"MPLocation","kind":"symbol","url":"\/documentation\/mapsindoors\/mplocation","abstract":[{"type":"text","text":"This holds the data for a single location and a marker to display the data on a map."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"MapsPeopleWhite.png":{"alt":null,"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/geometry":{"title":"geometry","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"geometry"}],"type":"topic","abstract":[{"text":"The geometry representing the location.","type":"text"}],"url":"\/documentation\/mapsindoors\/mplocation\/geometry","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPGeometry","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometry"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/geometry","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometry":{"kind":"symbol","title":"MPGeometry","url":"\/documentation\/mapsindoors\/mpgeometry","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPGeometry","kind":"identifier"}],"navigatorTitle":[{"text":"MPGeometry","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometry"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"geometry","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"geometry"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"MPGeometry","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometry","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometry"},{"kind":"text","text":" * "},{"kind":"identifier","text":"geometry"}],"languages":["occ"]}]}},{"value":"MPLocation","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MPLocation"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1geometry\/title","value":"geometry","op":"replace"},{"op":"replace","value":[{"text":"geometry","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1geometry\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometry\/title","op":"replace","value":"MPGeometry"},{"value":[{"kind":"identifier","text":"MPGeometry"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometry\/fragments"}]}]}