{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager"]]},"kind":"symbol","abstract":[{"text":"Add data set to the list of managed data sets.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/addDataSet(_:cachingScope:)"},"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/adddataset(_:cachingscope:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/adddataset(_:cachingscope:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addDataSet"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"dataSetId","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cachingScope"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPDataSetCachingScope","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope","preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingScope"},{"kind":"text","text":") -> "},{"text":"MPDataSetCache","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Data set id of the data set that should be added."}]}],"name":"dataSetId"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Caching scope for this dataset."}]}],"name":"cachingScope"}]},{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"The cache object if data set was successfully added as a result of this call, if the dataset already existed this method returns nil."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager(im)addDataSet:cachingScope:","modules":[{"name":"MapsIndoors"}],"required":true,"symbolKind":"method","role":"symbol","title":"addDataSet(_:cachingScope:)","navigatorTitle":[{"kind":"identifier","text":"addDataSet:cachingScope:"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addDataSet","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"cachingScope","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCachingScope","preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingScope"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache"},{"text":"?","kind":"text"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/addDataSet(_:cachingScope:)":{"title":"addDataSet(_:cachingScope:)","kind":"symbol","abstract":[{"text":"Add data set to the list of managed data sets.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/addDataSet(_:cachingScope:)","navigatorTitle":[{"kind":"identifier","text":"addDataSet:cachingScope:"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/adddataset(_:cachingscope:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addDataSet"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cachingScope"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingScope","text":"MPDataSetCachingScope"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","text":"MPDataSetCache"},{"kind":"text","text":"?"}],"type":"topic","required":true},"MapsPeopleWhite.png":{"alt":null,"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager":{"kind":"symbol","navigatorTitle":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDataSetCacheManager","kind":"identifier"}],"title":"MPDataSetCacheManager","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Data set manager class."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingScope":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MPDataSetCachingScope","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachingscope","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCachingScope"}],"title":"MPDataSetCachingScope","kind":"symbol","abstract":[{"type":"text","text":"Data set caching scope. Currently only a full cache (non-partial) scope is supported (basic and detailed scope will sync full dataset)."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCache":{"kind":"symbol","navigatorTitle":[{"text":"MPDataSetCache","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache","url":"\/documentation\/mapsindoors\/mpdatasetcache","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDataSetCache","kind":"identifier"}],"title":"MPDataSetCache","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Data set cache class."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"addDataSet:cachingScope:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"addDataSet:cachingScope:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCache","kind":"typeIdentifier","text":"id<MPDataSetCache>"},{"text":" *) ","kind":"text"},{"text":"addDataSet:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"dataSetId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cachingScope:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDataSetCachingScope","preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingScope","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cachingScope","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1addDataSet(_:cachingScope:)\/title","value":"addDataSet:cachingScope:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1addDataSet(_:cachingScope:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addDataSet:cachingScope:"}]},{"value":"MPDataSetCacheManager","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title","op":"replace"},{"value":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments"},{"value":"MPDataSetCachingScope","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope\/title"},{"op":"replace","value":[{"text":"MPDataSetCachingScope","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache\/title","op":"replace","value":"MPDataSetCache"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache\/fragments","value":[{"kind":"identifier","text":"MPDataSetCache"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}