{"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelSynchronizationOfCacheItems"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"items","kind":"internalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem","text":"MPDataSetCacheItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"items","content":[{"inlineContent":[{"type":"text","text":"Cache Items to cancel sync of."}],"type":"paragraph"}]}]}],"abstract":[{"text":"Cancel synchronization of data for the given cache items.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/cancelsynchronizationofcacheitems(_:)"]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/cancelsynchronizationofcacheitems(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancelSynchronizationOfCacheItems"},{"text":"([","kind":"text"},{"text":"MPDataSetCacheItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"cancelSynchronizationOfCacheItems:"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager(im)cancelSynchronizationOfCacheItems:","modules":[{"name":"MapsIndoors"}],"roleHeading":"Instance Method","title":"cancelSynchronizationOfCacheItems(_:)","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/cancelSynchronizationOfCacheItems(_:)","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/cancelSynchronizationOfCacheItems(_:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/cancelSynchronizationOfCacheItems(_:)","kind":"symbol","required":true,"navigatorTitle":[{"text":"cancelSynchronizationOfCacheItems:","kind":"identifier"}],"abstract":[{"text":"Cancel synchronization of data for the given cache items.","type":"text"}],"role":"symbol","title":"cancelSynchronizationOfCacheItems(_:)","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/cancelsynchronizationofcacheitems(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"cancelSynchronizationOfCacheItems","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"MPDataSetCacheItem","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem"},{"text":"])","kind":"text"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Data set cache item class."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDataSetCacheItem","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem","role":"symbol","url":"\/documentation\/mapsindoors\/mpdatasetcacheitem","title":"MPDataSetCacheItem","navigatorTitle":[{"text":"MPDataSetCacheItem","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","alt":null,"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager":{"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheManager"}],"kind":"symbol","title":"MPDataSetCacheManager","role":"symbol","navigatorTitle":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Data set manager class."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"cancelSynchronizationOfCacheItems:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"cancelSynchronizationOfCacheItems:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"cancelSynchronizationOfCacheItems:"},{"kind":"text","text":"("},{"text":"NSArray<id<MPDataSetCacheItem>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"items","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1cancelSynchronizationOfCacheItems(_:)\/title","value":"cancelSynchronizationOfCacheItems:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1cancelSynchronizationOfCacheItems(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"cancelSynchronizationOfCacheItems:","kind":"identifier"}],"op":"replace"},{"value":"MPDataSetCacheItem","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem\/title"},{"value":[{"kind":"identifier","text":"MPDataSetCacheItem"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title","value":"MPDataSetCacheManager"},{"value":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments"}]}]}