{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelSynchronization"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":" "},{"kind":"internalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheItem","preciseIdentifier":"c:objc(cs)MPDataSetCacheItem","text":"MPDataSetCacheItem"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"items","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CacheItems to cancel sync of."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/cancelsynchronization(of:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/cancelsynchronization(of:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/cancelSynchronization(of:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Cancel synchronization of data for the given cache items."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelSynchronization"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPDataSetCacheItem","preciseIdentifier":"c:objc(cs)MPDataSetCacheItem"},{"kind":"text","text":"])"}],"title":"cancelSynchronization(of:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPDataSetCacheManager(im)cancelSynchronizationOfCacheItems:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"cancelSynchronizationOfCacheItems:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheItem":{"role":"symbol","title":"MPDataSetCacheItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheItem"}],"abstract":[{"type":"text","text":"Data set cache item class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheItem"}],"url":"\/documentation\/mapsindoors\/mpdatasetcacheitem"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheManager":{"role":"symbol","title":"MPDataSetCacheManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheManager"}],"abstract":[{"type":"text","text":"Data set manager class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManager"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheManager/cancelSynchronization(of:)":{"role":"symbol","title":"cancelSynchronization(of:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelSynchronization"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPDataSetCacheItem","preciseIdentifier":"c:objc(cs)MPDataSetCacheItem"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Cancel synchronization of data for the given cache items."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/cancelSynchronization(of:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cancelSynchronizationOfCacheItems:"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/cancelsynchronization(of:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"cancelSynchronizationOfCacheItems:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelSynchronizationOfCacheItems:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"cancelSynchronizationOfCacheItems:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<MPDataSetCacheItem *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"items"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheItem\/title","value":"MPDataSetCacheItem"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheItem\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheItem"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title","value":"MPDataSetCacheManager"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheManager"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1cancelSynchronization(of:)\/title","value":"cancelSynchronizationOfCacheItems:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1cancelSynchronization(of:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelSynchronizationOfCacheItems:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}