{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSet"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dataSetId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCache","preciseIdentifier":"c:objc(cs)MPDataSetCache","text":"MPDataSetCache"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"DataSetCache or nil"}]}]},{"kind":"parameters","parameters":[{"name":"dataSetId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"DataSetId to find corresponding MPDataSetCache object for."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/dataset(withid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/dataset(withid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/dataSet(withId:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get the dataset-object for the given dataSetId."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSet"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPDataSetCache","preciseIdentifier":"c:objc(cs)MPDataSetCache"},{"kind":"text","text":"?"}],"title":"dataSet(withId:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPDataSetCacheManager(im)dataSetWithId:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"dataSetWithId:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCache":{"role":"symbol","title":"MPDataSetCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCache"}],"abstract":[{"type":"text","text":"Data set cache class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCache"}],"url":"\/documentation\/mapsindoors\/mpdatasetcache"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheManager/dataSet(withId:)":{"role":"symbol","title":"dataSet(withId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSet"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPDataSetCache","preciseIdentifier":"c:objc(cs)MPDataSetCache"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the dataset-object for the given dataSetId."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/dataSet(withId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dataSetWithId:"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/dataset(withid:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheManager":{"role":"symbol","title":"MPDataSetCacheManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheManager"}],"abstract":[{"type":"text","text":"Data set manager class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManager"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"dataSetWithId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dataSetWithId:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCache","preciseIdentifier":"c:objc(cs)MPDataSetCache","text":"MPDataSetCache"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"dataSetWithId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"dataSetId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCache\/title","value":"MPDataSetCache"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCache\/fragments","value":[{"kind":"identifier","text":"MPDataSetCache"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1dataSet(withId:)\/title","value":"dataSetWithId:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1dataSet(withId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dataSetWithId:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title","value":"MPDataSetCacheManager"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}