{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager"]]},"abstract":[{"text":"The dataset-object for the current MapsIndoors API key \/ solution","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSetForCurrentMapsIndoorsAPIKey"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache","text":"MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache"},{"kind":"text","text":"?"}]}]},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The dataset-object for the current MapsIndoors API key \/ solution"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/datasetforcurrentmapsindoorsapikey()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/datasetforcurrentmapsindoorsapikey()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/dataSetForCurrentMapsIndoorsAPIKey()"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager(im)dataSetForCurrentMapsIndoorsAPIKey","modules":[{"name":"MapsIndoors"}],"required":true,"navigatorTitle":[{"text":"dataSetForCurrentMapsIndoorsAPIKey","kind":"identifier"}],"title":"dataSetForCurrentMapsIndoorsAPIKey()","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSetForCurrentMapsIndoorsAPIKey","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"MPDataSetCache","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache"},{"kind":"text","text":"?"}],"symbolKind":"method"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/dataSetForCurrentMapsIndoorsAPIKey()":{"required":true,"navigatorTitle":[{"text":"dataSetForCurrentMapsIndoorsAPIKey","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/dataSetForCurrentMapsIndoorsAPIKey()","title":"dataSetForCurrentMapsIndoorsAPIKey()","kind":"symbol","abstract":[{"text":"The dataset-object for the current MapsIndoors API key \/ solution","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSetForCurrentMapsIndoorsAPIKey","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"MPDataSetCache","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache"},{"text":"?","kind":"text"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/datasetforcurrentmapsindoorsapikey()"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCache":{"kind":"symbol","navigatorTitle":[{"text":"MPDataSetCache","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache","url":"\/documentation\/mapsindoors\/mpdatasetcache","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDataSetCache","kind":"identifier"}],"title":"MPDataSetCache","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Data set cache class."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager":{"kind":"symbol","navigatorTitle":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDataSetCacheManager","kind":"identifier"}],"title":"MPDataSetCacheManager","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Data set manager class."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"identifier":"MapsPeopleWhite.png","type":"image"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"dataSetForCurrentMapsIndoorsAPIKey","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dataSetForCurrentMapsIndoorsAPIKey"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id<MPDataSetCache>","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCache"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"dataSetForCurrentMapsIndoorsAPIKey"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1dataSetForCurrentMapsIndoorsAPIKey()\/title","value":"dataSetForCurrentMapsIndoorsAPIKey"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1dataSetForCurrentMapsIndoorsAPIKey()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dataSetForCurrentMapsIndoorsAPIKey"}]},{"value":"MPDataSetCache","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache\/fragments","value":[{"text":"MPDataSetCache","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title","value":"MPDataSetCacheManager"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments","op":"replace","value":[{"text":"MPDataSetCacheManager","kind":"identifier"}]}]}]}