{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchSyncSizes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dataSetCaches"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCache","preciseIdentifier":"c:objc(cs)MPDataSetCache","text":"MPDataSetCache"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate","preciseIdentifier":"c:objc(pl)MPDataSetCacheManagerSizeDelegate","text":"MPDataSetCacheManagerSizeDelegate"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"dataSetCaches","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"DataSetCaches to determine sync sizes for."}]}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback\/progress receiver"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/fetchsyncsizes(for:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/fetchsyncsizes(for:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/fetchSyncSizes(for:delegate:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Determine synchronization sizes for the given set of DataSetCaches."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchSyncSizes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPDataSetCache","preciseIdentifier":"c:objc(cs)MPDataSetCache"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheManagerSizeDelegate","preciseIdentifier":"c:objc(pl)MPDataSetCacheManagerSizeDelegate"},{"kind":"text","text":")"}],"title":"fetchSyncSizes(for:delegate:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPDataSetCacheManager(im)fetchSyncSizesForDataSetCaches:delegate:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"fetchSyncSizesForDataSetCaches:delegate:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCache":{"role":"symbol","title":"MPDataSetCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCache"}],"abstract":[{"type":"text","text":"Data set cache class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCache"}],"url":"\/documentation\/mapsindoors\/mpdatasetcache"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheManager":{"role":"symbol","title":"MPDataSetCacheManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheManager"}],"abstract":[{"type":"text","text":"Data set manager class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManager"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheManager/fetchSyncSizes(for:delegate:)":{"role":"symbol","title":"fetchSyncSizes(for:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchSyncSizes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPDataSetCache","preciseIdentifier":"c:objc(cs)MPDataSetCache"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheManagerSizeDelegate","preciseIdentifier":"c:objc(pl)MPDataSetCacheManagerSizeDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Determine synchronization sizes for the given set of DataSetCaches."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/fetchSyncSizes(for:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchSyncSizesForDataSetCaches:delegate:"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/fetchsyncsizes(for:delegate:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheManagerSizeDelegate":{"role":"symbol","title":"MPDataSetCacheManagerSizeDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol for getting callbacks when determining the size af dataset syncs."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"fetchSyncSizesForDataSetCaches:delegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchSyncSizesForDataSetCaches:delegate:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"fetchSyncSizesForDataSetCaches:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<MPDataSetCache *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"dataSetCaches"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MPDataSetCacheManagerSizeDelegate>","preciseIdentifier":"c:Qoobjc(pl)MPDataSetCacheManagerSizeDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCache\/title","value":"MPDataSetCache"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCache\/fragments","value":[{"kind":"identifier","text":"MPDataSetCache"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title","value":"MPDataSetCacheManager"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheManager"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1fetchSyncSizes(for:delegate:)\/title","value":"fetchSyncSizesForDataSetCaches:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1fetchSyncSizes(for:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchSyncSizesForDataSetCaches:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate\/title","value":"MPDataSetCacheManagerSizeDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}