{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/fetchSyncSizesFor(dataSetCaches:delegate:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager"]]},"sections":[],"abstract":[{"type":"text","text":"Determine synchronization sizes for the given set of MPDataSetCaches."}],"kind":"symbol","metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchSyncSizesFor","kind":"identifier"},{"kind":"text","text":"("},{"text":"dataSetCaches","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManagerSizeDelegate","text":"MPDataSetCacheManagerSizeDelegate","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"fetchSyncSizesForDataSetCaches:delegate:"}],"role":"symbol","modules":[{"name":"MapsIndoors"}],"title":"fetchSyncSizesFor(dataSetCaches:delegate:)","externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager(im)fetchSyncSizesForDataSetCaches:delegate:","roleHeading":"Instance Method","required":true},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/fetchsyncsizesfor(datasetcaches:delegate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/fetchsyncsizesfor(datasetcaches:delegate:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchSyncSizesFor"},{"kind":"text","text":"("},{"text":"dataSetCaches","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MPDataSetCache","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache"},{"text":"], ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheManagerSizeDelegate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManagerSizeDelegate"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"dataSetCaches","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MPDataSetCaches to determine sync sizes for."}]}]},{"name":"delegate","content":[{"inlineContent":[{"type":"text","text":"callback\/progress receiver"}],"type":"paragraph"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerSizeDelegate":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate","title":"MPDataSetCacheManagerSizeDelegate","url":"\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"}],"type":"topic","abstract":[{"text":"Delegate protocol for getting callbacks when determining the size af dataset syncs.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"}]},"MapsPeopleWhite.png":{"type":"image","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager":{"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheManager"}],"kind":"symbol","title":"MPDataSetCacheManager","role":"symbol","navigatorTitle":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Data set manager class."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/fetchSyncSizesFor(dataSetCaches:delegate:)":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/fetchSyncSizesFor(dataSetCaches:delegate:)","required":true,"navigatorTitle":[{"text":"fetchSyncSizesForDataSetCaches:delegate:","kind":"identifier"}],"abstract":[{"type":"text","text":"Determine synchronization sizes for the given set of MPDataSetCaches."}],"role":"symbol","title":"fetchSyncSizesFor(dataSetCaches:delegate:)","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/fetchsyncsizesfor(datasetcaches:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fetchSyncSizesFor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dataSetCaches","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","text":"MPDataSetCache","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManagerSizeDelegate","kind":"typeIdentifier","text":"MPDataSetCacheManagerSizeDelegate"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCache":{"url":"\/documentation\/mapsindoors\/mpdatasetcache","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDataSetCache","kind":"identifier"}],"kind":"symbol","title":"MPDataSetCache","role":"symbol","navigatorTitle":[{"text":"MPDataSetCache","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Data set cache class."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"fetchSyncSizesForDataSetCaches:delegate:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fetchSyncSizesForDataSetCaches:delegate:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"fetchSyncSizesForDataSetCaches:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<id<MPDataSetCache>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"dataSetCaches","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"delegate:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCacheManagerSizeDelegate","kind":"typeIdentifier","text":"id<MPDataSetCacheManagerSizeDelegate>"},{"text":" *) ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"MPDataSetCacheManagerSizeDelegate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate\/title"},{"value":[{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate\/fragments","op":"replace"},{"value":"MPDataSetCacheManager","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheManager"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1fetchSyncSizesFor(dataSetCaches:delegate:)\/title","value":"fetchSyncSizesForDataSetCaches:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1fetchSyncSizesFor(dataSetCaches:delegate:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"fetchSyncSizesForDataSetCaches:delegate:"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache\/title","value":"MPDataSetCache","op":"replace"},{"value":[{"kind":"identifier","text":"MPDataSetCache"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}