{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCachingStrategy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"strategy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy","preciseIdentifier":"c:@E@MPDataSetCachingStrategy","text":"MPDataSetCachingStrategy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cacheItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheItem","preciseIdentifier":"c:objc(cs)MPDataSetCacheItem","text":"MPDataSetCacheItem"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"YES if strategy is set for this item, else NO."}]}]},{"kind":"parameters","parameters":[{"name":"strategy","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Caching strategy."}]}]},{"name":"cacheItem","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Cache item."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/setcachingstrategy(_:cacheitem:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/setcachingstrategy(_:cacheitem:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/setCachingStrategy(_:cacheItem:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set a caching strategy for given cache item."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCachingStrategy"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPDataSetCachingStrategy","preciseIdentifier":"c:@E@MPDataSetCachingStrategy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cacheItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheItem","preciseIdentifier":"c:objc(cs)MPDataSetCacheItem"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"setCachingStrategy(_:cacheItem:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPDataSetCacheManager(im)setCachingStrategy:cacheItem:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"setCachingStrategy:cacheItem:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheManager/setCachingStrategy(_:cacheItem:)":{"role":"symbol","title":"setCachingStrategy(_:cacheItem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCachingStrategy"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPDataSetCachingStrategy","preciseIdentifier":"c:@E@MPDataSetCachingStrategy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cacheItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheItem","preciseIdentifier":"c:objc(cs)MPDataSetCacheItem"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set a caching strategy for given cache item."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/setCachingStrategy(_:cacheItem:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setCachingStrategy:cacheItem:"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/setcachingstrategy(_:cacheitem:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheManager":{"role":"symbol","title":"MPDataSetCacheManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheManager"}],"abstract":[{"type":"text","text":"Data set manager class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManager"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCachingStrategy":{"role":"symbol","title":"MPDataSetCachingStrategy","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCachingStrategy"}],"abstract":[{"type":"text","text":"Data set caching strategy."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCachingStrategy"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachingstrategy"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheItem":{"role":"symbol","title":"MPDataSetCacheItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheItem"}],"abstract":[{"type":"text","text":"Data set cache item class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheItem"}],"url":"\/documentation\/mapsindoors\/mpdatasetcacheitem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setCachingStrategy:cacheItem:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCachingStrategy:cacheItem:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"setCachingStrategy:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy","preciseIdentifier":"c:@E@MPDataSetCachingStrategy","text":"MPDataSetCachingStrategy"},{"kind":"text","text":")"},{"kind":"internalParam","text":"strategy"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheItem:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheItem","preciseIdentifier":"c:objc(cs)MPDataSetCacheItem","text":"MPDataSetCacheItem"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"cacheItem"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1setCachingStrategy(_:cacheItem:)\/title","value":"setCachingStrategy:cacheItem:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1setCachingStrategy(_:cacheItem:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCachingStrategy:cacheItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title","value":"MPDataSetCacheManager"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheManager"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy\/title","value":"MPDataSetCachingStrategy"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy\/fragments","value":[{"kind":"identifier","text":"MPDataSetCachingStrategy"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheItem\/title","value":"MPDataSetCacheItem"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheItem\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}