{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setCachingScope"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scope"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCachingScope","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope","preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingScope"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cacheItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheItem","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"scope","content":[{"type":"paragraph","inlineContent":[{"text":"Caching scope.","type":"text"}]}]},{"name":"cacheItem","content":[{"type":"paragraph","inlineContent":[{"text":"Cache item.","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"text":" if scope is changed for this item, else ","type":"text"},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}]}]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/setCachingScope(_:cacheItem:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager"]]},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/setcachingscope(_:cacheitem:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/setcachingscope(_:cacheitem:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager(im)setCachingScope:cacheItem:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setCachingScope"},{"text":"(","kind":"text"},{"text":"MPDataSetCachingScope","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingScope"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cacheItem"},{"text":": ","kind":"text"},{"text":"MPDataSetCacheItem","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","required":true,"navigatorTitle":[{"text":"setCachingScope:cacheItem:","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"title":"setCachingScope(_:cacheItem:)","roleHeading":"Instance Method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Set a caching scope for given cache item.","type":"text"}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingScope":{"role":"symbol","kind":"symbol","abstract":[{"text":"Data set caching scope. Currently only a full cache (non-partial) scope is supported (basic and detailed scope will sync full dataset).","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope","navigatorTitle":[{"text":"MPDataSetCachingScope","kind":"identifier"}],"title":"MPDataSetCachingScope","url":"\/documentation\/mapsindoors\/mpdatasetcachingscope","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCachingScope"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Data set cache item class."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDataSetCacheItem","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem","role":"symbol","url":"\/documentation\/mapsindoors\/mpdatasetcacheitem","title":"MPDataSetCacheItem","navigatorTitle":[{"text":"MPDataSetCacheItem","kind":"identifier"}]},"MapsPeopleWhite.png":{"alt":null,"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/setCachingScope(_:cacheItem:)":{"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/setCachingScope(_:cacheItem:)","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/setcachingscope(_:cacheitem:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setCachingScope","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MPDataSetCachingScope","preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingScope","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cacheItem"},{"text":": ","kind":"text"},{"text":"MPDataSetCacheItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","navigatorTitle":[{"text":"setCachingScope:cacheItem:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Set a caching scope for given cache item.","type":"text"}],"required":true,"title":"setCachingScope(_:cacheItem:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager":{"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheManager"}],"kind":"symbol","title":"MPDataSetCacheManager","role":"symbol","navigatorTitle":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Data set manager class."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"setCachingScope:cacheItem:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setCachingScope:cacheItem:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"setCachingScope:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MPDataSetCachingScope","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope","preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingScope","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"scope"},{"kind":"text","text":" "},{"text":"cacheItem:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCacheItem","text":"id<MPDataSetCacheItem>"},{"text":" *) ","kind":"text"},{"text":"cacheItem","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MPDataSetCachingScope","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope\/fragments","value":[{"text":"MPDataSetCachingScope","kind":"identifier"}]},{"value":"MPDataSetCacheItem","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem\/title"},{"value":[{"kind":"identifier","text":"MPDataSetCacheItem"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1setCachingScope(_:cacheItem:)\/title","value":"setCachingScope:cacheItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1setCachingScope(_:cacheItem:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCachingScope:cacheItem:"}]},{"value":"MPDataSetCacheManager","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments","value":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}