{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"indoorPathFirstLineUpwards"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderfit\/indoorpathfirstlineupwards"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderfit\/indoorpathfirstlineupwards"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/indoorPathFirstLineUpwards","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Ensures that the first part of any indoor route leg\/step that is longer than 1 meter is facing upwards. Outdoor route leg\/step renders with north facing upwards."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"indoorPathFirstLineUpwards"}],"title":"MPDirectionsRenderFit.indoorPathFirstLineUpwards","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MPDirectionsRenderFit@MPDirectionsRenderFitIndoorPathFirstLineUpwards","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRenderFitIndoorPathFirstLineUpwards"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderFit":{"role":"symbol","title":"MPDirectionsRenderFit","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRenderFit"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRenderFit"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderfit"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderFit/indoorPathFirstLineUpwards":{"role":"symbol","title":"MPDirectionsRenderFit.indoorPathFirstLineUpwards","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"indoorPathFirstLineUpwards"}],"abstract":[{"type":"text","text":"Ensures that the first part of any indoor route leg\/step that is longer than 1 meter is facing upwards. Outdoor route leg\/step renders with north facing upwards."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/indoorPathFirstLineUpwards","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRenderFitIndoorPathFirstLineUpwards"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderfit\/indoorpathfirstlineupwards"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MPDirectionsRenderFitIndoorPathFirstLineUpwards"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRenderFitIndoorPathFirstLineUpwards"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MPDirectionsRenderFitIndoorPathFirstLineUpwards"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderFit\/title","value":"MPDirectionsRenderFit"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderFit\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRenderFit"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderFit~1indoorPathFirstLineUpwards\/title","value":"MPDirectionsRenderFitIndoorPathFirstLineUpwards"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderFit~1indoorPathFirstLineUpwards\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRenderFitIndoorPathFirstLineUpwards"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}