{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"indoorPathUpwards"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderfit\/indoorpathupwards"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderfit\/indoorpathupwards"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/indoorPathUpwards","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Ensures that the direct line between start and end location of any indoor route leg\/step is facing upwards. Outdoor route leg\/step renders with north facing upwards."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"indoorPathUpwards"}],"title":"MPDirectionsRenderFit.indoorPathUpwards","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MPDirectionsRenderFit@MPDirectionsRenderFitIndoorPathUpwards","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRenderFitIndoorPathUpwards"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderFit":{"role":"symbol","title":"MPDirectionsRenderFit","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRenderFit"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRenderFit"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderfit"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderFit/indoorPathUpwards":{"role":"symbol","title":"MPDirectionsRenderFit.indoorPathUpwards","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"indoorPathUpwards"}],"abstract":[{"type":"text","text":"Ensures that the direct line between start and end location of any indoor route leg\/step is facing upwards. Outdoor route leg\/step renders with north facing upwards."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/indoorPathUpwards","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRenderFitIndoorPathUpwards"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderfit\/indoorpathupwards"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MPDirectionsRenderFitIndoorPathUpwards"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRenderFitIndoorPathUpwards"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MPDirectionsRenderFitIndoorPathUpwards"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderFit\/title","value":"MPDirectionsRenderFit"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderFit\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRenderFit"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderFit~1indoorPathUpwards\/title","value":"MPDirectionsRenderFitIndoorPathUpwards"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderFit~1indoorPathUpwards\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRenderFitIndoorPathUpwards"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}