{"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithLiveUpdate:","kind":"identifier"}],"title":"initWithLiveUpdate:","symbolKind":"method","externalID":"c:@M@MapsIndoors@objc(cs)MPCountLiveUpdate(im)initWithLiveUpdate:","modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithLiveUpdate:","kind":"identifier"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/mapsindoors\/mpcountliveupdate\/initwithliveupdate:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLiveUpdate:"},{"kind":"text","text":"("},{"text":"MPLiveUpdate","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate"},{"text":" *) ","kind":"text"},{"text":"withLiveUpdate","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCountLiveUpdate\/initWithLiveUpdate:"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCountLiveUpdate"]]},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCountLiveUpdate/initWithLiveUpdate:":{"title":"initWithLiveUpdate:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithLiveUpdate:","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCountLiveUpdate\/initWithLiveUpdate:","navigatorTitle":[{"kind":"identifier","text":"initWithLiveUpdate:"}],"abstract":[],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpcountliveupdate\/initwithliveupdate:","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/getLiveUpdate(forDomainType:)":{"url":"\/documentation\/mapsindoors\/mplocation\/getliveupdate(fordomaintype:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","type":"topic","title":"getLiveUpdate(forDomainType:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getLiveUpdate","kind":"identifier"},{"kind":"text","text":"("},{"text":"forDomainType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"text":"MPLiveUpdate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"getLiveUpdateForDomainType:"}],"abstract":[{"type":"text","text":"Get a live update based on a known domain type."}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCountLiveUpdate":{"navigatorTitle":[{"kind":"identifier","text":"MPCountLiveUpdate"}],"role":"symbol","abstract":[{"text":"Model for live event information for a given Location.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCountLiveUpdate","type":"topic","url":"\/documentation\/mapsindoors\/mpcountliveupdate","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPCountLiveUpdate"}],"title":"MPCountLiveUpdate"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate":{"url":"\/documentation\/mapsindoors\/mpliveupdate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","type":"topic","title":"MPLiveUpdate","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPLiveUpdate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPLiveUpdate"}],"abstract":[{"text":"Model for a Live Update. Used in ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","type":"reference","isActive":true}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/title","value":"getLiveUpdateForDomainType:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getLiveUpdateForDomainType:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCountLiveUpdate\/title","op":"replace","value":"MPCountLiveUpdate"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCountLiveUpdate\/fragments","value":[{"kind":"identifier","text":"MPCountLiveUpdate"}]},{"value":"MPLiveUpdate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/title"},{"value":[{"text":"MPLiveUpdate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}