{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeSynchronizeContentDataLoadingErrorKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/kmperrorcodesynchronizecontentdataloadingerrorkey"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/kmperrorcodesynchronizecontentdataloadingerrorkey"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/kMPErrorCodeSynchronizeContentDataLoadingErrorKey","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeSynchronizeContentDataLoadingErrorKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"kMPErrorCodeSynchronizeContentDataLoadingErrorKey","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:MPErrorCodes.h@2332@macro@kMPErrorCodeSynchronizeContentDataLoadingErrorKey","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"kMPErrorCodeSynchronizeContentDataLoadingErrorKey"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/kMPErrorCodeSynchronizeContentDataLoadingErrorKey":{"role":"symbol","title":"kMPErrorCodeSynchronizeContentDataLoadingErrorKey","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeSynchronizeContentDataLoadingErrorKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/kMPErrorCodeSynchronizeContentDataLoadingErrorKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kMPErrorCodeSynchronizeContentDataLoadingErrorKey"}],"url":"\/documentation\/mapsindoors\/kmperrorcodesynchronizecontentdataloadingerrorkey"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Macro"},{"op":"replace","path":"\/metadata\/title","value":"kMPErrorCodeSynchronizeContentDataLoadingErrorKey"},{"op":"replace","path":"\/metadata\/symbolKind","value":"macro"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeSynchronizeContentDataLoadingErrorKey"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1kMPErrorCodeSynchronizeContentDataLoadingErrorKey\/title","value":"kMPErrorCodeSynchronizeContentDataLoadingErrorKey"}],"traits":[{"interfaceLanguage":"occ"}]}]}