{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeCategoriesNotFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/kmperrorcodecategoriesnotfound"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/kmperrorcodecategoriesnotfound"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/kMPErrorCodeCategoriesNotFound","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeCategoriesNotFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"kMPErrorCodeCategoriesNotFound","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:MPErrorCodes.h@1274@macro@kMPErrorCodeCategoriesNotFound","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"kMPErrorCodeCategoriesNotFound"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/kMPErrorCodeCategoriesNotFound":{"role":"symbol","title":"kMPErrorCodeCategoriesNotFound","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeCategoriesNotFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/kMPErrorCodeCategoriesNotFound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kMPErrorCodeCategoriesNotFound"}],"url":"\/documentation\/mapsindoors\/kmperrorcodecategoriesnotfound"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Macro"},{"op":"replace","path":"\/metadata\/title","value":"kMPErrorCodeCategoriesNotFound"},{"op":"replace","path":"\/metadata\/symbolKind","value":"macro"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeCategoriesNotFound"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1kMPErrorCodeCategoriesNotFound\/title","value":"kMPErrorCodeCategoriesNotFound"}],"traits":[{"interfaceLanguage":"occ"}]}]}