{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeDirectionsRouteNotFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/kmperrorcodedirectionsroutenotfound"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/kmperrorcodedirectionsroutenotfound"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/kMPErrorCodeDirectionsRouteNotFound","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeDirectionsRouteNotFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"kMPErrorCodeDirectionsRouteNotFound","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:MPErrorCodes.h@1048@macro@kMPErrorCodeDirectionsRouteNotFound","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"kMPErrorCodeDirectionsRouteNotFound"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/kMPErrorCodeDirectionsRouteNotFound":{"role":"symbol","title":"kMPErrorCodeDirectionsRouteNotFound","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeDirectionsRouteNotFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/kMPErrorCodeDirectionsRouteNotFound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kMPErrorCodeDirectionsRouteNotFound"}],"url":"\/documentation\/mapsindoors\/kmperrorcodedirectionsroutenotfound"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Macro"},{"op":"replace","path":"\/metadata\/title","value":"kMPErrorCodeDirectionsRouteNotFound"},{"op":"replace","path":"\/metadata\/symbolKind","value":"macro"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeDirectionsRouteNotFound"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1kMPErrorCodeDirectionsRouteNotFound\/title","value":"kMPErrorCodeDirectionsRouteNotFound"}],"traits":[{"interfaceLanguage":"occ"}]}]}