{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsIndoors"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mapsindoors"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mapsindoors"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Main class for initialisation, configuration and content synchronisation."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsIndoors"}],"title":"MapsIndoors","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MapsIndoors","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/accessToken","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/dataSetCacheManager","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/delegate","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/eventLoggingDisabled","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/imageProvider","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/locationsProvider","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/positionProvider","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/sources","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/userRoles"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/checkOfflineDataAvailabilityAsync(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/fetchAuthenticationDetails(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/getAPIKey()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/getGoogleAPIKey()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/getLanguage()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/getOfflineMode()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/isAPIKeyValid()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/isOfflineDataAvailable()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/provideAPIKey(_:googleAPIKey:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/register(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/setLanguage(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/setOfflineMode(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/synchronizeContent(_:)"]}],"references":{"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/getAPIKey()":{"role":"symbol","title":"getAPIKey()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAPIKey"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Gets the current MapsIndoors API key."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/getAPIKey()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getMapsIndoorsAPIKey"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/getapikey()"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/dataSetCacheManager":{"role":"symbol","title":"dataSetCacheManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSetCacheManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheManager","preciseIdentifier":"c:objc(cs)MPDataSetCacheManager"}],"abstract":[{"type":"text","text":"Get the shared dataset cache manager."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/dataSetCacheManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dataSetCacheManager"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/datasetcachemanager"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/isOfflineDataAvailable()":{"role":"symbol","title":"isOfflineDataAvailable()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOfflineDataAvailable"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determine if enough data is available for a good user experience in offline mode."},{"type":"text","text":" "},{"type":"text","text":"For results that are not dependent on timing of async calls, this is best used in the completion handler of +[MapsIndoors checkOfflineDataAvailabilityAsync:]."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/isOfflineDataAvailable()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isOfflineDataAvailable"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/isofflinedataavailable()"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/imageProvider":{"role":"symbol","title":"imageProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPImageProviderProtocol","preciseIdentifier":"c:objc(pl)MPImageProvider"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The image provider that MapsIndoors should use when image ressources are needed. MapsIndoors will provide a default if this property is nil."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/imageProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageProvider"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/imageprovider"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/accessToken":{"role":"symbol","title":"accessToken","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get or set the access token. Only relevant for datasets that requires authorised access."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/accessToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accessToken"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/accesstoken"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/sources":{"role":"symbol","title":"sources","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sources"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPLocationSource","preciseIdentifier":"c:objc(pl)MPLocationSource"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The currently registered location sources."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/sources","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sources"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/sources"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/setOfflineMode(_:)":{"role":"symbol","title":"setOfflineMode(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setOfflineMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the offline mode for the content provided by MapsIndoors. True means that the SDK is not allowed to use network traffic. NB: This forces the implementation to be offline, even if there is no data available offline."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/setOfflineMode(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setOfflineMode:"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/setofflinemode(_:)"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/eventLoggingDisabled":{"role":"symbol","title":"eventLoggingDisabled","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventLoggingDisabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Gets or sets the event logging state. If enabled, the SDK will collect anonymous SDK usage data from the application. By default, the collection of usage event data is enabled, but in order for logs to be collected, the logging must also be enabled in the MapsIndoors CMS."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/eventLoggingDisabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"eventLoggingDisabled"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/eventloggingdisabled"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/userRoles":{"role":"symbol","title":"userRoles","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userRoles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPUserRole","preciseIdentifier":"c:objc(cs)MPUserRole"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Get or set the user roles that should apply generally for querying routes and locations. The roles are applied in an OR fashion. This means that if for example a locations internal restrictions matches one or more of the given roles, the location will be included in response object. Setting the user roles will only work when online."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/userRoles","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userRoles"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/userroles"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/positionProvider":{"role":"symbol","title":"positionProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"positionProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPositionProvider","preciseIdentifier":"c:objc(pl)MPPositionProvider"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The position provider that MapsIndoors should use when user location services are needed."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/positionProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"positionProvider"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/positionprovider"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/provideAPIKey(_:googleAPIKey:)":{"role":"symbol","title":"provideAPIKey(_:googleAPIKey:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provideAPIKey"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"googleAPIKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Provides your API key and content key to the MapsIndoors SDK. These keys are unique for your MapsIndoors solution and are used to identify and authorise use of the data provided by MapsIndoors."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/provideAPIKey(_:googleAPIKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"provideAPIKey:googleAPIKey:"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/provideapikey(_:googleapikey:)"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors":{"role":"symbol","title":"MapsIndoors","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsIndoors"}],"abstract":[{"type":"text","text":"Main class for initialisation, configuration and content synchronisation."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapsIndoors"}],"url":"\/documentation\/mapsindoors\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/getLanguage()":{"role":"symbol","title":"getLanguage()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLanguage"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Gets the current language for the content provided by MapsIndoors."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/getLanguage()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getLanguage"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/getlanguage()"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/getGoogleAPIKey()":{"role":"symbol","title":"getGoogleAPIKey()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getGoogleAPIKey"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Gets the current Google API key."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/getGoogleAPIKey()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getGoogleAPIKey"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/getgoogleapikey()"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/checkOfflineDataAvailabilityAsync(_:)":{"role":"symbol","title":"checkOfflineDataAvailabilityAsync(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkOfflineDataAvailabilityAsync"},{"kind":"text","text":"(() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Check availability of offline data."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/checkOfflineDataAvailabilityAsync(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"checkOfflineDataAvailabilityAsync:"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/checkofflinedataavailabilityasync(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/setLanguage(_:)":{"role":"symbol","title":"setLanguage(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLanguage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the language for the content provided by MapsIndoors."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/setLanguage(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setLanguage:"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/setlanguage(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/getOfflineMode()":{"role":"symbol","title":"getOfflineMode()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getOfflineMode"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Gets the current offline mode. True means that the SDK is not allowed to use network traffic."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/getOfflineMode()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getOfflineMode"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/getofflinemode()"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPMapsIndoorsDelegate","preciseIdentifier":"c:objc(pl)MPMapsIndoorsDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get or set the delegate object."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/delegate"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/isAPIKeyValid()":{"role":"symbol","title":"isAPIKeyValid()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAPIKeyValid"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns whether the current API key is valid or not."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/isAPIKeyValid()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAPIKeyValid"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/isapikeyvalid()"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/synchronizeContent(_:)":{"role":"symbol","title":"synchronizeContent(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"synchronizeContent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpSyncContentHandlerBlockType","preciseIdentifier":"c:MPMapsIndoors.h@T@mpSyncContentHandlerBlockType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Fetch all neccesary content to be able to run MapsIndoors in offline environments."},{"type":"text","text":" "},{"type":"text","text":"If you have registered custom location sources, they are not synchronized by this method - it is the responsibility of the provider of the custom location source to synchronize as appropriate."},{"type":"text","text":" "},{"type":"text","text":"This method only synchronizes the current dataset - If you need to synchronize data for non-current datasets, please see @see dataSetCacheManager and MPDataSetCacheManager.synchronizeContent()"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/synchronizeContent(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"synchronizeContent:"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/synchronizecontent(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/register(_:)":{"role":"symbol","title":"register(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"MPLocationSource","preciseIdentifier":"c:objc(pl)MPLocationSource"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Register Location data sources."},{"type":"text","text":" "},{"type":"text","text":"All registered location sources must have a unique sourceId."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/register(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerLocationSources:"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/register(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/fetchAuthenticationDetails(_:)":{"role":"symbol","title":"fetchAuthenticationDetails(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchAuthenticationDetails"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpAuthDetailsHandlerBlockType","preciseIdentifier":"c:MPMapsIndoors.h@T@mpAuthDetailsHandlerBlockType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Fetch authentication details needed to perform an Auth2 supported single signon flow in your application."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/fetchAuthenticationDetails(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchAuthenticationDetails:"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/fetchauthenticationdetails(_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/locationsProvider":{"deprecated":true,"role":"symbol","title":"locationsProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationsProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationsProviderProtocol","preciseIdentifier":"c:objc(pl)MPLocationsProvider"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The location provider that MapsIndoors should use."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/locationsProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"locationsProvider"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/locationsprovider"},"doc://MapsIndoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MapsIndoors"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MapsIndoors"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MapsIndoors"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/accessToken","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/dataSetCacheManager","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/delegate","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/eventLoggingDisabled","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/imageProvider","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/locationsProvider","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/positionProvider","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/sources","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/userRoles"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/checkOfflineDataAvailabilityAsync(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/fetchAuthenticationDetails(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/getAPIKey()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/getGoogleAPIKey()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/getLanguage()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/getOfflineMode()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/isAPIKeyValid()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/isOfflineDataAvailable()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/provideAPIKey(_:googleAPIKey:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/register(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/setLanguage(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/setOfflineMode(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/synchronizeContent(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsIndoors"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1getAPIKey()\/title","value":"getMapsIndoorsAPIKey"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1getAPIKey()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getMapsIndoorsAPIKey"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1dataSetCacheManager\/title","value":"dataSetCacheManager"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1dataSetCacheManager\/fragments","value":[{"kind":"identifier","text":"dataSetCacheManager"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1isOfflineDataAvailable()\/title","value":"isOfflineDataAvailable"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1isOfflineDataAvailable()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isOfflineDataAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1imageProvider\/title","value":"imageProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1imageProvider\/fragments","value":[{"kind":"identifier","text":"imageProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1accessToken\/title","value":"accessToken"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1accessToken\/fragments","value":[{"kind":"identifier","text":"accessToken"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1sources\/title","value":"sources"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1sources\/fragments","value":[{"kind":"identifier","text":"sources"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1setOfflineMode(_:)\/title","value":"setOfflineMode:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1setOfflineMode(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setOfflineMode:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1eventLoggingDisabled\/title","value":"eventLoggingDisabled"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1eventLoggingDisabled\/fragments","value":[{"kind":"identifier","text":"eventLoggingDisabled"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1userRoles\/title","value":"userRoles"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1userRoles\/fragments","value":[{"kind":"identifier","text":"userRoles"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1positionProvider\/title","value":"positionProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1positionProvider\/fragments","value":[{"kind":"identifier","text":"positionProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1provideAPIKey(_:googleAPIKey:)\/title","value":"provideAPIKey:googleAPIKey:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1provideAPIKey(_:googleAPIKey:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"provideAPIKey:googleAPIKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors\/title","value":"MapsIndoors"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors\/fragments","value":[{"kind":"identifier","text":"MapsIndoors"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1getLanguage()\/title","value":"getLanguage"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1getLanguage()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getLanguage"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1getGoogleAPIKey()\/title","value":"getGoogleAPIKey"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1getGoogleAPIKey()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getGoogleAPIKey"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1checkOfflineDataAvailabilityAsync(_:)\/title","value":"checkOfflineDataAvailabilityAsync:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1checkOfflineDataAvailabilityAsync(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"checkOfflineDataAvailabilityAsync:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1setLanguage(_:)\/title","value":"setLanguage:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1setLanguage(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setLanguage:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1getOfflineMode()\/title","value":"getOfflineMode"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1getOfflineMode()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getOfflineMode"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1isAPIKeyValid()\/title","value":"isAPIKeyValid"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1isAPIKeyValid()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isAPIKeyValid"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1synchronizeContent(_:)\/title","value":"synchronizeContent:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1synchronizeContent(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"synchronizeContent:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1register(_:)\/title","value":"registerLocationSources:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1register(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"registerLocationSources:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1fetchAuthenticationDetails(_:)\/title","value":"fetchAuthenticationDetails:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1fetchAuthenticationDetails(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fetchAuthenticationDetails:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1locationsProvider\/title","value":"locationsProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1locationsProvider\/fragments","value":[{"kind":"identifier","text":"locationsProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}