{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPAppDataProvider"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpappdataprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpappdataprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The app data provider acts as a service for the metadata (MPAppData) of a MapsIndoors app solution."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPAppDataProvider"}],"title":"MPAppDataProvider","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPAppDataProvider","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPAppDataProvider"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider\/getAppData()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider\/getAppData(completion:)"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider\/isOfflineDataAvailable(forSolutionId:language:)"]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPAppDataProvider/getAppData(completion:)":{"role":"symbol","title":"getAppData(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAppData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpAppDataHandlerBlockType","preciseIdentifier":"c:MPAppDataProvider.h@T@mpAppDataHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get app metadata and handle the data with a callback block"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider\/getAppData(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAppDataWithCompletion:"}],"url":"\/documentation\/mapsindoors\/mpappdataprovider\/getappdata(completion:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPAppDataProvider/getAppData()":{"role":"symbol","title":"getAppData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAppData"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Get app metadata. Assign a delegate object to this instance in order to handle the data fetch."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider\/getAppData()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAppData"}],"url":"\/documentation\/mapsindoors\/mpappdataprovider\/getappdata()"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MPAppDataProvider/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPAppDataProviderDelegate","preciseIdentifier":"c:objc(pl)MPAppDataProviderDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Delegate object. This is another way of handling data fetching. Using completionHandler block instead is recommended."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/mapsindoors\/mpappdataprovider\/delegate"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/documentation/MapsIndoors/MPAppDataProvider":{"role":"symbol","title":"MPAppDataProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPAppDataProvider"}],"abstract":[{"type":"text","text":"The app data provider acts as a service for the metadata (MPAppData) of a MapsIndoors app solution."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPAppDataProvider"}],"url":"\/documentation\/mapsindoors\/mpappdataprovider"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(cs)NSObject"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPAppDataProvider/isOfflineDataAvailable(forSolutionId:language:)":{"role":"symbol","title":"isOfflineDataAvailable(forSolutionId:language:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOfflineDataAvailable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSolutionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determine if cached or preloaded data is available for the given solutionId."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider\/isOfflineDataAvailable(forSolutionId:language:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isOfflineDataAvailableForSolutionId:language:"}],"url":"\/documentation\/mapsindoors\/mpappdataprovider\/isofflinedataavailable(forsolutionid:language:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPAppDataProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPAppDataProvider"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPAppDataProvider"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider\/getAppData()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider\/getAppData(completion:)"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider\/isOfflineDataAvailable(forSolutionId:language:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPAppDataProvider"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider~1getAppData(completion:)\/title","value":"getAppDataWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider~1getAppData(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAppDataWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider~1getAppData()\/title","value":"getAppData"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider~1getAppData()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAppData"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider\/title","value":"MPAppDataProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider\/fragments","value":[{"kind":"identifier","text":"MPAppDataProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider~1isOfflineDataAvailable(forSolutionId:language:)\/title","value":"isOfflineDataAvailableForSolutionId:language:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider~1isOfflineDataAvailable(forSolutionId:language:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isOfflineDataAvailableForSolutionId:language:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}