{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpAppDataHandlerBlockType"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppData","preciseIdentifier":"c:objc(cs)MPAppData","text":"MPAppData"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpappdatahandlerblocktype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpappdatahandlerblocktype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpAppDataHandlerBlockType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Callback block for getting app data or handling error in doing so."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpAppDataHandlerBlockType"}],"title":"mpAppDataHandlerBlockType","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias","externalID":"c:MPAppDataProvider.h@T@mpAppDataHandlerBlockType","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"mpAppDataHandlerBlockType"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPAppData":{"role":"symbol","title":"MPAppData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPAppData"}],"abstract":[{"type":"text","text":"Provides the contextual information needed for setting up a map with specific MapsPeople site data"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPAppData"}],"url":"\/documentation\/mapsindoors\/mpappdata"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/mpAppDataHandlerBlockType":{"role":"symbol","title":"mpAppDataHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpAppDataHandlerBlockType"}],"abstract":[{"type":"text","text":"Callback block for getting app data or handling error in doing so."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpAppDataHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpAppDataHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpappdatahandlerblocktype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"mpAppDataHandlerBlockType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mpAppDataHandlerBlockType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"mpAppDataHandlerBlockType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(MPAppData *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)MPAppData#*$objc(cs)NSError)"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpAppDataHandlerBlockType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppData\/title","value":"MPAppData"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppData\/fragments","value":[{"kind":"identifier","text":"MPAppData"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpAppDataHandlerBlockType\/title","value":"mpAppDataHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpAppDataHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpAppDataHandlerBlockType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}