{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeaconProviderProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbeaconproviderprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbeaconproviderprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProvider-swift.class"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderProtocol","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Beacons provider protocol."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeaconProviderProtocol"}],"title":"MPBeaconProviderProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)MPBeaconProvider","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPBeaconProviderProtocol"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderProtocol\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderProtocol\/getBeacons(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderProtocol\/getBeacons(_:clientId:)"]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPBeaconProviderProtocol/getBeacons(_:clientId:)":{"navigatorTitle":[{"kind":"identifier","text":"getBeacons:clientId:"}],"role":"symbol","title":"getBeacons(_:clientId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBeacons"},{"kind":"text","text":"(["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderProtocol\/getBeacons(_:clientId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpbeaconproviderprotocol\/getbeacons(_:clientid:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeaconProviderProtocol/getBeacons(_:)":{"navigatorTitle":[{"kind":"identifier","text":"getBeacons:"}],"role":"symbol","title":"getBeacons(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBeacons"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderProtocol\/getBeacons(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpbeaconproviderprotocol\/getbeacons(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeaconProviderProtocol":{"role":"symbol","title":"MPBeaconProviderProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeaconProviderProtocol"}],"abstract":[{"type":"text","text":"Beacons provider protocol."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBeaconProviderProtocol"}],"url":"\/documentation\/mapsindoors\/mpbeaconproviderprotocol"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeaconProviderProtocol/delegate":{"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPBeaconProviderDelegate","preciseIdentifier":"c:objc(pl)MPBeaconProviderDelegate"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderProtocol\/delegate","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpbeaconproviderprotocol\/delegate"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeaconProvider-swift.class":{"role":"symbol","title":"MPBeaconProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeaconProvider"}],"abstract":[{"type":"text","text":"Beacons provider that defines a delegate and a method to initiate fetching of Beacons from the provider."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProvider-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBeaconProvider"}],"url":"\/documentation\/mapsindoors\/mpbeaconprovider-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPBeaconProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPBeaconProvider"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPBeaconProvider"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderProtocol\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderProtocol\/getBeacons(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderProtocol\/getBeacons(_:clientId:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeaconProvider"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProviderProtocol~1getBeacons(_:clientId:)\/title","value":"getBeacons:clientId:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProviderProtocol~1getBeacons(_:clientId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBeacons:clientId:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProviderProtocol~1getBeacons(_:)\/title","value":"getBeacons:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProviderProtocol~1getBeacons(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBeacons:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProviderProtocol\/title","value":"MPBeaconProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProviderProtocol\/fragments","value":[{"kind":"identifier","text":"MPBeaconProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProviderProtocol~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProviderProtocol~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProvider-swift.class\/title","value":"MPBeaconProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProvider-swift.class\/fragments","value":[{"kind":"identifier","text":"MPBeaconProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}