{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeaconProviderDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbeaconproviderdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbeaconproviderdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Beacons provider delegate."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeaconProviderDelegate"}],"title":"MPBeaconProviderDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)MPBeaconProviderDelegate","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPBeaconProviderDelegate"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderDelegate\/onBeaconsReady(_:)"]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPBeaconProviderDelegate":{"role":"symbol","title":"MPBeaconProviderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeaconProviderDelegate"}],"abstract":[{"type":"text","text":"Beacons provider delegate."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBeaconProviderDelegate"}],"url":"\/documentation\/mapsindoors\/mpbeaconproviderdelegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeaconProviderDelegate/onBeaconsReady(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onBeaconsReady:"}],"role":"symbol","title":"onBeaconsReady(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBeaconsReady"},{"kind":"text","text":"(["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderDelegate\/onBeaconsReady(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpbeaconproviderdelegate\/onbeaconsready(_:)"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPBeaconProviderDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPBeaconProviderDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPBeaconProviderDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProviderDelegate\/onBeaconsReady(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeaconProviderDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProviderDelegate\/title","value":"MPBeaconProviderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProviderDelegate\/fragments","value":[{"kind":"identifier","text":"MPBeaconProviderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProviderDelegate~1onBeaconsReady(_:)\/title","value":"onBeaconsReady:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProviderDelegate~1onBeaconsReady(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBeaconsReady:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}