{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpBuildingDetailsHandlerBlockType"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class","preciseIdentifier":"c:objc(cs)MPBuilding","text":"MPBuilding"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"building","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Building object. Can be nil."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error object. Can be nil."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbuildingdetailshandlerblocktype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbuildingdetailshandlerblocktype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpBuildingDetailsHandlerBlockType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Handler block for fetching buildings"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpBuildingDetailsHandlerBlockType"}],"title":"mpBuildingDetailsHandlerBlockType","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias","externalID":"c:MPVenueProvider.h@T@mpBuildingDetailsHandlerBlockType","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"mpBuildingDetailsHandlerBlockType"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/mpBuildingDetailsHandlerBlockType":{"role":"symbol","title":"mpBuildingDetailsHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpBuildingDetailsHandlerBlockType"}],"abstract":[{"type":"text","text":"Handler block for fetching buildings"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpBuildingDetailsHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpBuildingDetailsHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpbuildingdetailshandlerblocktype"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class":{"role":"symbol","title":"MPBuilding","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuilding"}],"abstract":[{"type":"text","text":"Holds relevant data for a single building, and the buildings floor levels."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBuilding"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"mpBuildingDetailsHandlerBlockType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mpBuildingDetailsHandlerBlockType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"mpBuildingDetailsHandlerBlockType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(MPBuilding *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)MPBuilding#*$objc(cs)NSError)"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpBuildingDetailsHandlerBlockType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpBuildingDetailsHandlerBlockType\/title","value":"mpBuildingDetailsHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpBuildingDetailsHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpBuildingDetailsHandlerBlockType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class\/title","value":"MPBuilding"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class\/fragments","value":[{"kind":"identifier","text":"MPBuilding"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}