{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuilding"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbuilding-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbuilding-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)JSONModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)NSCopying","doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding","doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Holds relevant data for a single building, and the buildings floor levels."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuilding"}],"title":"MPBuilding","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPBuilding","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPBuilding"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/address","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/administrativeId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/anchor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/bounds","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/buildingId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/currentFloor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/defaultFloor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/delegate","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/externalId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/fields","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/floors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/floorsReady","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/map","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/name","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/venueId"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/getBounds()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/getFloor()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/getFloorArray()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/getFloors()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/getInitFloor()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/hide()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/setFloor(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/show(_:onMap:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/updateTiles()"]}],"references":{"doc://MapsIndoors/objc(cs)JSONModel":{"type":"unresolvable","title":"JSONModel","identifier":"doc:\/\/MapsIndoors\/objc(cs)JSONModel"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/hide()":{"deprecated":true,"role":"symbol","title":"hide()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hide"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Hide the building from the map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/hide()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hideBuilding"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/hide()"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/getFloor()":{"role":"symbol","title":"getFloor()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFloor"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MPFloor","preciseIdentifier":"c:objc(cs)MPFloor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the current floor."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/getFloor()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getFloor"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/getfloor()"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/getFloorArray()":{"role":"symbol","title":"getFloorArray()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFloorArray"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"MPFloor","preciseIdentifier":"c:objc(cs)MPFloor"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Get the floors as an array of MPFloor."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/getFloorArray()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getFloorArray"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/getfloorarray()"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/bounds":{"role":"symbol","title":"bounds","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bounds"},{"kind":"text","text":": [["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]]?"}],"abstract":[{"type":"text","text":"Get building bounds"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/bounds","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bounds"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/bounds"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPBuildingDelegate","preciseIdentifier":"c:objc(pl)MPBuildingDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Delegate that holds the building ready event method. Relevant when using offline mode, as it will take a while to load the database upon first app start."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/delegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/floors":{"role":"symbol","title":"floors","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floors"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSMutableDictionary","preciseIdentifier":"c:objc(cs)NSMutableDictionary"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"MPFloorProtocol","preciseIdentifier":"c:objc(pl)MPFloor"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Get building floors"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/floors","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floors"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/floors"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get building name"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/name"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/defaultFloor":{"role":"symbol","title":"defaultFloor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultFloor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the buildings default floor. Is used by MPMapControl to determine which floor to show if a user have not already selected a floor."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/defaultFloor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultFloor"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/defaultfloor"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/map":{"role":"symbol","title":"map","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"map"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSMapView","preciseIdentifier":"c:objc(cs)GMSMapView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Reference to the map. The reference is used to activate\/deactivate tile layers."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/map","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"map"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/map"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/show(_:onMap:)":{"deprecated":true,"role":"symbol","title":"show(_:onMap:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"onMap"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSMapView","preciseIdentifier":"c:objc(cs)GMSMapView"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Use this method to actually shift floor and show the building level."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/show(_:onMap:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showBuilding:onMap:"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/show(_:onmap:)"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCopying"},"doc://MapsIndoors/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/setFloor(_:)":{"role":"symbol","title":"setFloor(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFloor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Set the current floor property (without affecting the building display)."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/setFloor(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setFloor:"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/setfloor(_:)"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/updateTiles()":{"deprecated":true,"role":"symbol","title":"updateTiles()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateTiles"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Updates the current floor tile layer by clearing the tile cache."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/updateTiles()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateBuildingTiles"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/updatetiles()"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/currentFloor":{"role":"symbol","title":"currentFloor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentFloor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Holds the current floor."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/currentFloor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"currentFloor"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/currentfloor"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/floorsReady":{"role":"symbol","title":"floorsReady","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floorsReady"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Simple counter that keeps track of how many floors and related tile layers are ready."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/floorsReady","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floorsReady"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/floorsready"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/externalId":{"role":"symbol","title":"externalId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"externalId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"External id."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/externalId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"externalId"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/externalid"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class":{"role":"symbol","title":"MPBuilding","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuilding"}],"abstract":[{"type":"text","text":"Holds relevant data for a single building, and the buildings floor levels."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBuilding"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/getFloors()":{"role":"symbol","title":"getFloors()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFloors"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the number of floors."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/getFloors()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getFloors"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/getfloors()"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/getBounds()":{"role":"symbol","title":"getBounds()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBounds"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the geographic bounds for the building"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/getBounds()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getBuildingBounds"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/getbounds()"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/address":{"role":"symbol","title":"address","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get building address"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/address","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"address"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/address"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/anchor":{"role":"symbol","title":"anchor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get building anchor coordinate"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/anchor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"anchor"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/anchor"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/administrativeId":{"role":"symbol","title":"administrativeId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"administrativeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get building administrative id"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/administrativeId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"administrativeId"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/administrativeid"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/buildingId":{"role":"symbol","title":"buildingId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get building id"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/buildingId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildingId"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/buildingid"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/getInitFloor()":{"role":"symbol","title":"getInitFloor()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getInitFloor"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the initial\/default floor upon creation."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/getInitFloor()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getInitFloor"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/getinitfloor()"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/venueId":{"role":"symbol","title":"venueId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"venueId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Venue id"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/venueId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"venueId"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/venueid"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class/fields":{"role":"symbol","title":"fields","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"MPLocationField","preciseIdentifier":"c:objc(cs)MPLocationField"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Dictionary of custom fields"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/fields","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fields"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class\/fields"},"doc://MapsIndoors/objc(pl)AbstractJSONModelProtocol":{"type":"unresolvable","title":"JSONModel.AbstractJSONModelProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPBuilding"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPBuilding"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPBuilding"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/address","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/administrativeId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/anchor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/bounds","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/buildingId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/currentFloor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/defaultFloor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/delegate","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/externalId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/fields","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/floors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/floorsReady","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/map","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/name","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/venueId"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/getBounds()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/getFloor()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/getFloorArray()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/getFloors()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/getInitFloor()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/hide()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/setFloor(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/show(_:onMap:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class\/updateTiles()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuilding"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSONModel","preciseIdentifier":"c:objc(cs)JSONModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1hide()\/title","value":"hideBuilding"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1hide()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hideBuilding"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1getFloor()\/title","value":"getFloor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1getFloor()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getFloor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1getFloorArray()\/title","value":"getFloorArray"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1getFloorArray()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getFloorArray"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1bounds\/title","value":"bounds"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1bounds\/fragments","value":[{"kind":"identifier","text":"bounds"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1floors\/title","value":"floors"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1floors\/fragments","value":[{"kind":"identifier","text":"floors"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1name\/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1defaultFloor\/title","value":"defaultFloor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1defaultFloor\/fragments","value":[{"kind":"identifier","text":"defaultFloor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1map\/title","value":"map"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1map\/fragments","value":[{"kind":"identifier","text":"map"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1show(_:onMap:)\/title","value":"showBuilding:onMap:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1show(_:onMap:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showBuilding:onMap:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1setFloor(_:)\/title","value":"setFloor:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1setFloor(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFloor:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1updateTiles()\/title","value":"updateBuildingTiles"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1updateTiles()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateBuildingTiles"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1currentFloor\/title","value":"currentFloor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1currentFloor\/fragments","value":[{"kind":"identifier","text":"currentFloor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1floorsReady\/title","value":"floorsReady"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1floorsReady\/fragments","value":[{"kind":"identifier","text":"floorsReady"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1externalId\/title","value":"externalId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1externalId\/fragments","value":[{"kind":"identifier","text":"externalId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class\/title","value":"MPBuilding"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class\/fragments","value":[{"kind":"identifier","text":"MPBuilding"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1getFloors()\/title","value":"getFloors"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1getFloors()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getFloors"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1getBounds()\/title","value":"getBuildingBounds"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1getBounds()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBuildingBounds"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1address\/title","value":"address"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1address\/fragments","value":[{"kind":"identifier","text":"address"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1anchor\/title","value":"anchor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1anchor\/fragments","value":[{"kind":"identifier","text":"anchor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1administrativeId\/title","value":"administrativeId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1administrativeId\/fragments","value":[{"kind":"identifier","text":"administrativeId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1buildingId\/title","value":"buildingId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1buildingId\/fragments","value":[{"kind":"identifier","text":"buildingId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1getInitFloor()\/title","value":"getInitFloor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1getInitFloor()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getInitFloor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1venueId\/title","value":"venueId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1venueId\/fragments","value":[{"kind":"identifier","text":"venueId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1fields\/title","value":"fields"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class~1fields\/fragments","value":[{"kind":"identifier","text":"fields"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}