{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuildingDataset"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbuildingdataset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbuildingdataset"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)JSONModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)NSCopying","doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding","doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Collection of buildings with some retrieval and calculation functionality."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuildingDataset"}],"title":"MPBuildingDataset","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPBuildingDataset","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPBuildingDataset"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/features","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/getBuilding(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/intersectionAreaBetweenBounds(_:andBounds:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/setBuildingDelegate(_:)"]}],"references":{"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/objc(cs)JSONModel":{"type":"unresolvable","title":"JSONModel","identifier":"doc:\/\/MapsIndoors\/objc(cs)JSONModel"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuildingDataset/intersectionAreaBetweenBounds(_:andBounds:)":{"role":"symbol","title":"intersectionAreaBetweenBounds(_:andBounds:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"intersectionAreaBetweenBounds"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andBounds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Get the intersection area on two GMSCoordinateBounds."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/intersectionAreaBetweenBounds(_:andBounds:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"intersectionAreaBetweenBounds:andBounds:"}],"url":"\/documentation\/mapsindoors\/mpbuildingdataset\/intersectionareabetweenbounds(_:andbounds:)"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/objc(pl)AbstractJSONModelProtocol":{"type":"unresolvable","title":"JSONModel.AbstractJSONModelProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuildingDataset/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The type of data (equals “FeatureCollection”)."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/mapsindoors\/mpbuildingdataset\/type"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuildingDataset":{"role":"symbol","title":"MPBuildingDataset","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuildingDataset"}],"abstract":[{"type":"text","text":"Collection of buildings with some retrieval and calculation functionality."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBuildingDataset"}],"url":"\/documentation\/mapsindoors\/mpbuildingdataset"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuildingDataset/features":{"role":"symbol","title":"features","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"features"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Array of buildings contained in the collection."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/features","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"features"}],"url":"\/documentation\/mapsindoors\/mpbuildingdataset\/features"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuildingDataset/getBuilding(_:)":{"role":"symbol","title":"getBuilding(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBuilding"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPBuilding","preciseIdentifier":"c:objc(cs)MPBuilding"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Retrieve a building by its unique shortname."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/getBuilding(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getBuilding:"}],"url":"\/documentation\/mapsindoors\/mpbuildingdataset\/getbuilding(_:)"},"doc://MapsIndoors/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCopying"},"doc://MapsIndoors/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuildingDataset/setBuildingDelegate(_:)":{"role":"symbol","title":"setBuildingDelegate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBuildingDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPBuildingDelegate","preciseIdentifier":"c:objc(pl)MPBuildingDelegate"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Assign a delegate object to all buildings in the collection, this object will hold the onBuildingReady:shortName event method."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/setBuildingDelegate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setBuildingDelegate:"}],"url":"\/documentation\/mapsindoors\/mpbuildingdataset\/setbuildingdelegate(_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPBuildingDataset"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPBuildingDataset"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPBuildingDataset"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/features","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/getBuilding(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/intersectionAreaBetweenBounds(_:andBounds:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/setBuildingDelegate(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuildingDataset"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSONModel","preciseIdentifier":"c:objc(cs)JSONModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset~1intersectionAreaBetweenBounds(_:andBounds:)\/title","value":"intersectionAreaBetweenBounds:andBounds:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset~1intersectionAreaBetweenBounds(_:andBounds:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"intersectionAreaBetweenBounds:andBounds:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset\/title","value":"MPBuildingDataset"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset\/fragments","value":[{"kind":"identifier","text":"MPBuildingDataset"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset~1features\/title","value":"features"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset~1features\/fragments","value":[{"kind":"identifier","text":"features"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset~1getBuilding(_:)\/title","value":"getBuilding:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset~1getBuilding(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBuilding:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset~1setBuildingDelegate(_:)\/title","value":"setBuildingDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset~1setBuildingDelegate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBuildingDelegate:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}