{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPCategoriesProvider"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpcategoriesprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpcategoriesprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A categories provider acts as a service for the location categories belonging to a specific MapsIndoors solution\/dataset."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPCategoriesProvider"}],"title":"MPCategoriesProvider","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPCategoriesProvider","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPCategoriesProvider"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider\/getCategories()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider\/getCategoriesWithCompletion(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider\/isOfflineDataAvailable(forSolutionId:language:)"]}],"references":{"doc://MapsIndoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(cs)NSObject"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPCategoriesProvider/getCategoriesWithCompletion(_:)":{"role":"symbol","title":"getCategoriesWithCompletion(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCategoriesWithCompletion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpCategoriesHandlerBlockType","preciseIdentifier":"c:MPCategoriesProvider.h@T@mpCategoriesHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get Categories from this provider and provide a callback handler."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider\/getCategoriesWithCompletion(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getCategoriesWithCompletion:"}],"url":"\/documentation\/mapsindoors\/mpcategoriesprovider\/getcategorieswithcompletion(_:)"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/documentation/MapsIndoors/MPCategoriesProvider/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPCategoriesProviderDelegate","preciseIdentifier":"c:objc(pl)MPCategoriesProviderDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Categories provider delegate."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/mapsindoors\/mpcategoriesprovider\/delegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPCategoriesProvider/isOfflineDataAvailable(forSolutionId:language:)":{"role":"symbol","title":"isOfflineDataAvailable(forSolutionId:language:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOfflineDataAvailable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSolutionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determine if cached or preloaded data is available for the given solutionId."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider\/isOfflineDataAvailable(forSolutionId:language:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isOfflineDataAvailableForSolutionId:language:"}],"url":"\/documentation\/mapsindoors\/mpcategoriesprovider\/isofflinedataavailable(forsolutionid:language:)"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/documentation/MapsIndoors/MPCategoriesProvider/getCategories()":{"role":"symbol","title":"getCategories()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCategories"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Get categories from the specified solution."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider\/getCategories()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getCategories"}],"url":"\/documentation\/mapsindoors\/mpcategoriesprovider\/getcategories()"},"doc://MapsIndoors/documentation/MapsIndoors/MPCategoriesProvider":{"role":"symbol","title":"MPCategoriesProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPCategoriesProvider"}],"abstract":[{"type":"text","text":"A categories provider acts as a service for the location categories belonging to a specific MapsIndoors solution\/dataset."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPCategoriesProvider"}],"url":"\/documentation\/mapsindoors\/mpcategoriesprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPCategoriesProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPCategoriesProvider"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPCategoriesProvider"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider\/getCategories()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider\/getCategoriesWithCompletion(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider\/isOfflineDataAvailable(forSolutionId:language:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPCategoriesProvider"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategoriesProvider~1getCategoriesWithCompletion(_:)\/title","value":"getCategoriesWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategoriesProvider~1getCategoriesWithCompletion(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCategoriesWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategoriesProvider~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategoriesProvider~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategoriesProvider~1isOfflineDataAvailable(forSolutionId:language:)\/title","value":"isOfflineDataAvailableForSolutionId:language:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategoriesProvider~1isOfflineDataAvailable(forSolutionId:language:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isOfflineDataAvailableForSolutionId:language:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategoriesProvider~1getCategories()\/title","value":"getCategories"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategoriesProvider~1getCategories()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCategories"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategoriesProvider\/title","value":"MPCategoriesProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategoriesProvider\/fragments","value":[{"kind":"identifier","text":"MPCategoriesProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}