{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataField"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatafield-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdatafield-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)JSONModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)NSCopying","doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding","doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataField-swift.class","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataField-swift.class\/fields","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataField-swift.class\/key","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataField-swift.class\/value"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataField"}],"title":"MPDataField","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPDataField","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPDataField"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDataField-swift.class":{"role":"symbol","title":"MPDataField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataField"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataField-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataField"}],"url":"\/documentation\/mapsindoors\/mpdatafield-swift.class"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/objc(pl)AbstractJSONModelProtocol":{"type":"unresolvable","title":"JSONModel.AbstractJSONModelProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataField-swift.class/fields":{"role":"symbol","title":"fields","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"MPLocationField","preciseIdentifier":"c:objc(cs)MPLocationField"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Dictionary of custom fields"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataField-swift.class\/fields","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fields"}],"url":"\/documentation\/mapsindoors\/mpdatafield-swift.class\/fields"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataField-swift.class/key":{"role":"symbol","title":"key","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataField-swift.class\/key","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"key"}],"url":"\/documentation\/mapsindoors\/mpdatafield-swift.class\/key"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataField-swift.class/value":{"role":"symbol","title":"value","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataField-swift.class\/value","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"value"}],"url":"\/documentation\/mapsindoors\/mpdatafield-swift.class\/value"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/objc(cs)JSONModel":{"type":"unresolvable","title":"JSONModel","identifier":"doc:\/\/MapsIndoors\/objc(cs)JSONModel"},"doc://MapsIndoors/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCopying"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPDataField"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPDataField"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPDataField"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataField-swift.class\/fields","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataField-swift.class\/key","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataField-swift.class\/value"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataField"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSONModel","preciseIdentifier":"c:objc(cs)JSONModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataField-swift.class\/title","value":"MPDataField"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataField-swift.class\/fragments","value":[{"kind":"identifier","text":"MPDataField"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataField-swift.class~1fields\/title","value":"fields"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataField-swift.class~1fields\/fragments","value":[{"kind":"identifier","text":"fields"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataField-swift.class~1key\/title","value":"key"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataField-swift.class~1key\/fragments","value":[{"kind":"identifier","text":"key"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataField-swift.class~1value\/title","value":"value"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataField-swift.class~1value\/fragments","value":[{"kind":"identifier","text":"value"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}