{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheScope"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcachescope"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachescope"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH","doc:\/\/MapsIndoors\/SY","doc:\/\/MapsIndoors\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Data set caching scope. Currently only a full cache (non-partial) scope is supported (basic and detailed scope will sync full dataset)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheScope"}],"title":"MPDataSetCacheScope","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@MPDataSetCacheScope","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheScope"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/cachingScope_Basic","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/cachingScope_Detailed","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/cachingScope_Full"]},{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/init(rawValue:)"]},{"title":"Type Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/basic","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/cachingScope_Default","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/default","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/detailed","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/full"]},{"title":"Default Implementations","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/Equatable-Implementations","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheScope/cachingScope_Full":{"role":"symbol","title":"MPDataSetCacheScope.cachingScope_Full","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cachingScope_Full"}],"abstract":[{"type":"text","text":"Basic + location-specific images."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/cachingScope_Full","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCachingScope_Full"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachescope\/cachingscope_full"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheScope/basic":{"role":"symbol","title":"basic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"basic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheScope","preciseIdentifier":"c:@E@MPDataSetCacheScope"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/basic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetBasic"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachescope\/basic"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheScope/cachingScope_Basic":{"role":"symbol","title":"MPDataSetCacheScope.cachingScope_Basic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cachingScope_Basic"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/cachingScope_Basic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCachingScope_Basic"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachescope\/cachingscope_basic"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheScope/cachingScope_Detailed":{"role":"symbol","title":"MPDataSetCacheScope.cachingScope_Detailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cachingScope_Detailed"}],"abstract":[{"type":"text","text":"Basic cache scope. Information about locations, buildings and venue and type images."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/cachingScope_Detailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCachingScope_Detailed"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachescope\/cachingscope_detailed"},"doc://MapsIndoors/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/MapsIndoors\/s8SendableP"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheScope/cachingScope_Default":{"role":"symbol","title":"cachingScope_Default","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cachingScope_Default"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheScope","preciseIdentifier":"c:@E@MPDataSetCacheScope"}],"abstract":[{"type":"text","text":"Full cache scope. All necessary content is downloaded for a data set to work offline."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/cachingScope_Default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCachingScope_Default"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachescope\/cachingscope_default"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheScope/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachescope\/rawrepresentable-implementations"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheScope/default":{"role":"symbol","title":"default","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheScope","preciseIdentifier":"c:@E@MPDataSetCacheScope"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetDefault"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachescope\/default"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheScope/detailed":{"role":"symbol","title":"detailed","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detailed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheScope","preciseIdentifier":"c:@E@MPDataSetCacheScope"}],"abstract":[{"type":"text","text":"Basic cache scope. Information about locations, buildings and venue and type images."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/detailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetDetailed"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachescope\/detailed"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheScope/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachescope\/init(rawvalue:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheScope/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachescope\/equatable-implementations"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheScope":{"role":"symbol","title":"MPDataSetCacheScope","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheScope"}],"abstract":[{"type":"text","text":"Data set caching scope. Currently only a full cache (non-partial) scope is supported (basic and detailed scope will sync full dataset)"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheScope"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachescope"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheScope/full":{"role":"symbol","title":"full","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"full"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheScope","preciseIdentifier":"c:@E@MPDataSetCacheScope"}],"abstract":[{"type":"text","text":"Basic + location-specific images."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/full","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetFull"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachescope\/full"},"doc://MapsIndoors/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/MapsIndoors\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"MPDataSetCacheScope"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheScope"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPDataSetCacheScope"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/basic","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/cachingScope_Basic","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/cachingScope_Default","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/cachingScope_Detailed","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/cachingScope_Full","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/default","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/detailed","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/full"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheScope"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope~1cachingScope_Full\/title","value":"MPDataSetCachingScope_Full"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope~1cachingScope_Full\/fragments","value":[{"kind":"identifier","text":"MPDataSetCachingScope_Full"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope~1basic\/title","value":"MPDataSetBasic"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope~1basic\/fragments","value":[{"kind":"identifier","text":"MPDataSetBasic"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope~1cachingScope_Basic\/title","value":"MPDataSetCachingScope_Basic"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope~1cachingScope_Basic\/fragments","value":[{"kind":"identifier","text":"MPDataSetCachingScope_Basic"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope~1cachingScope_Detailed\/title","value":"MPDataSetCachingScope_Detailed"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope~1cachingScope_Detailed\/fragments","value":[{"kind":"identifier","text":"MPDataSetCachingScope_Detailed"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope~1cachingScope_Default\/title","value":"MPDataSetCachingScope_Default"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope~1cachingScope_Default\/fragments","value":[{"kind":"identifier","text":"MPDataSetCachingScope_Default"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope~1default\/title","value":"MPDataSetDefault"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope~1default\/fragments","value":[{"kind":"identifier","text":"MPDataSetDefault"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope~1detailed\/title","value":"MPDataSetDetailed"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope~1detailed\/fragments","value":[{"kind":"identifier","text":"MPDataSetDetailed"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope\/title","value":"MPDataSetCacheScope"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheScope"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope~1full\/title","value":"MPDataSetFull"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope~1full\/fragments","value":[{"kind":"identifier","text":"MPDataSetFull"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}