{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDistanceMatrixResult"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdistancematrixresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdistancematrixresult"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)JSONModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)NSCopying","doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding","doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/bestDestination","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/bestOrigin","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/destination_addresses","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/origin_addresses","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/provider","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/rows","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/status","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/venue"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDistanceMatrixResult"}],"title":"MPDistanceMatrixResult","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPDistanceMatrixResult","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPDistanceMatrixResult"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixResult/status":{"role":"symbol","title":"status","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/status","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"status"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixresult\/status"},"doc://MapsIndoors/objc(cs)JSONModel":{"type":"unresolvable","title":"JSONModel","identifier":"doc:\/\/MapsIndoors\/objc(cs)JSONModel"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCopying"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixResult/bestOrigin":{"role":"symbol","title":"bestOrigin","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bestOrigin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/bestOrigin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bestOrigin"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixresult\/bestorigin"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/objc(pl)AbstractJSONModelProtocol":{"type":"unresolvable","title":"JSONModel.AbstractJSONModelProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixResult/origin_addresses":{"role":"symbol","title":"origin_addresses","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin_addresses"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/origin_addresses","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"origin_addresses"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixresult\/origin_addresses"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixResult/destination_addresses":{"role":"symbol","title":"destination_addresses","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"destination_addresses"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/destination_addresses","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"destination_addresses"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixresult\/destination_addresses"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixResult/venue":{"role":"symbol","title":"venue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"venue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/venue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"venue"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixresult\/venue"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixResult/rows":{"role":"symbol","title":"rows","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rows"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPDistanceMatrixRows","preciseIdentifier":"c:objc(cs)MPDistanceMatrixRows"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/rows","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rows"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixresult\/rows"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixResult/bestDestination":{"role":"symbol","title":"bestDestination","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bestDestination"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/bestDestination","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bestDestination"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixresult\/bestdestination"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixResult":{"role":"symbol","title":"MPDistanceMatrixResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDistanceMatrixResult"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDistanceMatrixResult"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixresult"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixResult/provider":{"role":"symbol","title":"provider","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/provider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"provider"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixresult\/provider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPDistanceMatrixResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPDistanceMatrixResult"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPDistanceMatrixResult"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/bestDestination","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/bestOrigin","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/destination_addresses","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/origin_addresses","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/provider","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/rows","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/status","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult\/venue"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDistanceMatrixResult"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSONModel","preciseIdentifier":"c:objc(cs)JSONModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult~1status\/title","value":"status"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult~1status\/fragments","value":[{"kind":"identifier","text":"status"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult~1bestOrigin\/title","value":"bestOrigin"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult~1bestOrigin\/fragments","value":[{"kind":"identifier","text":"bestOrigin"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult~1origin_addresses\/title","value":"origin_addresses"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult~1origin_addresses\/fragments","value":[{"kind":"identifier","text":"origin_addresses"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult~1destination_addresses\/title","value":"destination_addresses"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult~1destination_addresses\/fragments","value":[{"kind":"identifier","text":"destination_addresses"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult~1venue\/title","value":"venue"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult~1venue\/fragments","value":[{"kind":"identifier","text":"venue"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult~1rows\/title","value":"rows"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult~1rows\/fragments","value":[{"kind":"identifier","text":"rows"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult~1bestDestination\/title","value":"bestDestination"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult~1bestDestination\/fragments","value":[{"kind":"identifier","text":"bestDestination"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult\/title","value":"MPDistanceMatrixResult"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult\/fragments","value":[{"kind":"identifier","text":"MPDistanceMatrixResult"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult~1provider\/title","value":"provider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult~1provider\/fragments","value":[{"kind":"identifier","text":"provider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}