{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDistanceMatrixProvider"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdistancematrixprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdistancematrixprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/delegate","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/googleApiKey","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/graphId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/solutionId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/vehicle"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getDistanceMatrix(withOrigins:destinations:travelMode:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:userRoles:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getGoogleDistanceMatrix(withOrigins:destinations:travelMode:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getGoogleDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDistanceMatrixProvider"}],"title":"MPDistanceMatrixProvider","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPDistanceMatrixProvider","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPDistanceMatrixProvider"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixProvider/graphId":{"role":"symbol","title":"graphId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"graphId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/graphId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"graphId"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixprovider\/graphid"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixProvider/vehicle":{"role":"symbol","title":"vehicle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vehicle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/vehicle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"vehicle"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixprovider\/vehicle"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixProvider/getDistanceMatrix(withOrigins:destinations:travelMode:)":{"role":"symbol","title":"getDistanceMatrix(withOrigins:destinations:travelMode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDistanceMatrix"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOrigins"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"destinations"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"travelMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getDistanceMatrix(withOrigins:destinations:travelMode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDistanceMatrixWithOrigins:destinations:travelMode:"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixprovider\/getdistancematrix(withorigins:destinations:travelmode:)"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(cs)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixProvider/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDistanceMatrixProviderDelegate","preciseIdentifier":"c:objc(pl)MPDistanceMatrixProviderDelegate"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixprovider\/delegate"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixProvider/getGoogleDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)":{"role":"symbol","title":"getGoogleDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getGoogleDistanceMatrix"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOrigins"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"destinations"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"travelMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"depart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"arrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpMatrixHandlerBlockType","preciseIdentifier":"c:MPDistanceMatrixProvider.h@T@mpMatrixHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getGoogleDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getGoogleDistanceMatrixWithOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixprovider\/getgoogledistancematrix(withorigins:destinations:travelmode:avoid:depart:arrive:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixProvider/getGoogleDistanceMatrix(withOrigins:destinations:travelMode:)":{"role":"symbol","title":"getGoogleDistanceMatrix(withOrigins:destinations:travelMode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getGoogleDistanceMatrix"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOrigins"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"destinations"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"travelMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getGoogleDistanceMatrix(withOrigins:destinations:travelMode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getGoogleDistanceMatrixWithOrigins:destinations:travelMode:"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixprovider\/getgoogledistancematrix(withorigins:destinations:travelmode:)"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixProvider":{"role":"symbol","title":"MPDistanceMatrixProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDistanceMatrixProvider"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDistanceMatrixProvider"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixprovider"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixProvider/solutionId":{"role":"symbol","title":"solutionId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"solutionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/solutionId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"solutionId"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixprovider\/solutionid"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixProvider/getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)":{"role":"symbol","title":"getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDistanceMatrix"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOrigins"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"destinations"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"travelMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"depart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"arrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpMatrixHandlerBlockType","preciseIdentifier":"c:MPDistanceMatrixProvider.h@T@mpMatrixHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDistanceMatrixWithOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixprovider\/getdistancematrix(withorigins:destinations:travelmode:avoid:depart:arrive:completionhandler:)"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixProvider/googleApiKey":{"role":"symbol","title":"googleApiKey","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"googleApiKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/googleApiKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"googleApiKey"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixprovider\/googleapikey"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixProvider/getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:userRoles:completionHandler:)":{"role":"symbol","title":"getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:userRoles:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDistanceMatrix"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOrigins"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"destinations"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"travelMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"depart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"arrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userRoles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPUserRole","preciseIdentifier":"c:objc(cs)MPUserRole"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpMatrixHandlerBlockType","preciseIdentifier":"c:MPDistanceMatrixProvider.h@T@mpMatrixHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:userRoles:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDistanceMatrixWithOrigins:destinations:travelMode:avoid:depart:arrive:userRoles:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixprovider\/getdistancematrix(withorigins:destinations:travelmode:avoid:depart:arrive:userroles:completionhandler:)"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPDistanceMatrixProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPDistanceMatrixProvider"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPDistanceMatrixProvider"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/delegate","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/googleApiKey","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/graphId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/solutionId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/vehicle"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getDistanceMatrix(withOrigins:destinations:travelMode:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:userRoles:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getGoogleDistanceMatrix(withOrigins:destinations:travelMode:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getGoogleDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDistanceMatrixProvider"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1graphId\/title","value":"graphId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1graphId\/fragments","value":[{"kind":"identifier","text":"graphId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1vehicle\/title","value":"vehicle"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1vehicle\/fragments","value":[{"kind":"identifier","text":"vehicle"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1getDistanceMatrix(withOrigins:destinations:travelMode:)\/title","value":"getDistanceMatrixWithOrigins:destinations:travelMode:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1getDistanceMatrix(withOrigins:destinations:travelMode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDistanceMatrixWithOrigins:destinations:travelMode:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1getGoogleDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)\/title","value":"getGoogleDistanceMatrixWithOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1getGoogleDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getGoogleDistanceMatrixWithOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1getGoogleDistanceMatrix(withOrigins:destinations:travelMode:)\/title","value":"getGoogleDistanceMatrixWithOrigins:destinations:travelMode:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1getGoogleDistanceMatrix(withOrigins:destinations:travelMode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getGoogleDistanceMatrixWithOrigins:destinations:travelMode:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider\/title","value":"MPDistanceMatrixProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider\/fragments","value":[{"kind":"identifier","text":"MPDistanceMatrixProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1solutionId\/title","value":"solutionId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1solutionId\/fragments","value":[{"kind":"identifier","text":"solutionId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)\/title","value":"getDistanceMatrixWithOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDistanceMatrixWithOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1googleApiKey\/title","value":"googleApiKey"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1googleApiKey\/fragments","value":[{"kind":"identifier","text":"googleApiKey"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:userRoles:completionHandler:)\/title","value":"getDistanceMatrixWithOrigins:destinations:travelMode:avoid:depart:arrive:userRoles:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:userRoles:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDistanceMatrixWithOrigins:destinations:travelMode:avoid:depart:arrive:userRoles:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}