{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRenderFit"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderfit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderfit"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH","doc:\/\/MapsIndoors\/SY","doc:\/\/MapsIndoors\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/indoorPathFirstLineUpwards","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/indoorPathUpwards","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/northBound"]},{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/Equatable-Implementations","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRenderFit"}],"title":"MPDirectionsRenderFit","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@MPDirectionsRenderFit","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRenderFit"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderFit/northBound":{"role":"symbol","title":"MPDirectionsRenderFit.northBound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"northBound"}],"abstract":[{"type":"text","text":"Renders the route leg\/step with north facing upwards."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/northBound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRenderFitNorthBound"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderfit\/northbound"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderFit":{"role":"symbol","title":"MPDirectionsRenderFit","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRenderFit"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRenderFit"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderfit"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/MapsIndoors\/SY"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderFit/indoorPathUpwards":{"role":"symbol","title":"MPDirectionsRenderFit.indoorPathUpwards","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"indoorPathUpwards"}],"abstract":[{"type":"text","text":"Ensures that the direct line between start and end location of any indoor route leg\/step is facing upwards. Outdoor route leg\/step renders with north facing upwards."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/indoorPathUpwards","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRenderFitIndoorPathUpwards"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderfit\/indoorpathupwards"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderFit/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpdirectionsrenderfit\/init(rawvalue:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderFit/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mpdirectionsrenderfit\/rawrepresentable-implementations"},"doc://MapsIndoors/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/MapsIndoors\/s8SendableP"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderFit/indoorPathFirstLineUpwards":{"role":"symbol","title":"MPDirectionsRenderFit.indoorPathFirstLineUpwards","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"indoorPathFirstLineUpwards"}],"abstract":[{"type":"text","text":"Ensures that the first part of any indoor route leg\/step that is longer than 1 meter is facing upwards. Outdoor route leg\/step renders with north facing upwards."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/indoorPathFirstLineUpwards","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRenderFitIndoorPathFirstLineUpwards"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderfit\/indoorpathfirstlineupwards"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderFit/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mpdirectionsrenderfit\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"MPDirectionsRenderFit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRenderFit"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPDirectionsRenderFit"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/indoorPathFirstLineUpwards","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/indoorPathUpwards","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderFit\/northBound"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRenderFit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderFit~1northBound\/title","value":"MPDirectionsRenderFitNorthBound"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderFit~1northBound\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRenderFitNorthBound"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderFit\/title","value":"MPDirectionsRenderFit"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderFit\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRenderFit"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderFit~1indoorPathUpwards\/title","value":"MPDirectionsRenderFitIndoorPathUpwards"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderFit~1indoorPathUpwards\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRenderFitIndoorPathUpwards"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderFit~1indoorPathFirstLineUpwards\/title","value":"MPDirectionsRenderFitIndoorPathFirstLineUpwards"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderFit~1indoorPathFirstLineUpwards\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRenderFitIndoorPathFirstLineUpwards"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}