{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRenderer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Directions Renderer"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRenderer"}],"title":"MPDirectionsRenderer","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPDirectionsRenderer","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRenderer"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/actionPointImages","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/backgroundColor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/contextualInfoSettings","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/delegate","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/edgeInsets","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/fitBounds","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/fitMode","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/isRenderingRoute","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/map","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/nextRouteLegButton","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/previousRouteLegButton","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/route","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/routeLegIndex","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/routeStepIndex","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/solidColor"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/animate(_:)"]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer/route":{"role":"symbol","title":"route","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"route"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPRoute","preciseIdentifier":"c:objc(cs)MPRoute"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Assigns (or unassigns) a route object"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/route","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"route"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/route"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer/edgeInsets":{"role":"symbol","title":"edgeInsets","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"edgeInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"abstract":[{"type":"text","text":"Intentional egde insets for bounds fitting. The rendering is not guaranteed to respect the specified insets."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/edgeInsets","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"edgeInsets"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/edgeinsets"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer/routeStepIndex":{"role":"symbol","title":"routeStepIndex","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routeStepIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Optional index of the route step in the current route leg. If set, only the step will be rendered and not the current route leg. If set to something negative, route step rendering will be disabled."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/routeStepIndex","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"routeStepIndex"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/routestepindex"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer/nextRouteLegButton":{"role":"symbol","title":"nextRouteLegButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextRouteLegButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Template button used to render a marker at the end of the rendered route leg"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/nextRouteLegButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nextRouteLegButton"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/nextroutelegbutton"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer/map":{"role":"symbol","title":"map","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"map"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSMapView","preciseIdentifier":"c:objc(cs)GMSMapView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Assigns (or unassigns) a Google map object"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/map","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"map"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/map"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer/isRenderingRoute":{"role":"symbol","title":"isRenderingRoute","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRenderingRoute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Indicates whether the renderer is currently showing a route or not."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/isRenderingRoute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isRenderingRoute"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/isrenderingroute"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer/routeLegIndex":{"role":"symbol","title":"routeLegIndex","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routeLegIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Index of the route leg that will be rendered. If set to something negative, rendering will be disabled."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/routeLegIndex","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"routeLegIndex"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/routelegindex"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer/previousRouteLegButton":{"role":"symbol","title":"previousRouteLegButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previousRouteLegButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Template button used to render a marker at the start of the rendered route leg"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/previousRouteLegButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"previousRouteLegButton"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/previousroutelegbutton"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer/contextualInfoSettings":{"role":"symbol","title":"contextualInfoSettings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contextualInfoSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDirectionsRendererContextualInfoSettings","preciseIdentifier":"c:objc(cs)MPDirectionsRendererContextualInfoSettings"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Set this property to show labels and icons from nearby Locations as additional contextual information about the start and end positions of the rendered route segment."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/contextualInfoSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contextualInfoSettings"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/contextualinfosettings"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer/fitBounds":{"role":"symbol","title":"fitBounds","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fitBounds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"If set to YES, the map viewport will be adjusted to fit the rendered route leg\/step."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/fitBounds","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fitBounds"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/fitbounds"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer/backgroundColor":{"role":"symbol","title":"backgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Background color of the rendered route leg\/step. The background color will ne visible during animation."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/backgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backgroundColor"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/backgroundcolor"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer/solidColor":{"role":"symbol","title":"solidColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"solidColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Foreground color of the rendered route leg\/step."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/solidColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"solidColor"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/solidcolor"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDirectionsRendererDelegate","preciseIdentifier":"c:objc(pl)MPDirectionsRendererDelegate"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/delegate"},"doc://MapsIndoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(cs)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer":{"role":"symbol","title":"MPDirectionsRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRenderer"}],"abstract":[{"type":"text","text":"Directions Renderer"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRenderer"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer/fitMode":{"role":"symbol","title":"fitMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fitMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDirectionsRenderFit","preciseIdentifier":"c:@E@MPDirectionsRenderFit"}],"abstract":[{"type":"text","text":"Bounds fitting mode."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/fitMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fitMode"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/fitmode"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer/animate(_:)":{"role":"symbol","title":"animate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Start animation of the route leg\/step with given duration. Starting with a "},{"type":"codeVoice","code":"backgroundColor"},{"type":"text","text":" route leg\/step the polyline will be gradually stroked from start to end with the "},{"type":"codeVoice","code":"solidColor"},{"type":"text","text":" at the speed of "},{"type":"codeVoice","code":"leg\/step length \/ duration"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/animate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animate:"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/animate(_:)"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer/actionPointImages":{"role":"symbol","title":"actionPointImages","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionPointImages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Custom images to use for representing the action points. The first image will be used as the start image. The image at position N in the array will be used at the end of the leg with index N-1, as well as the end of the last step of the leg with index N-1."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/actionPointImages","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"actionPointImages"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/actionpointimages"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPDirectionsRenderer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRenderer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPDirectionsRenderer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/actionPointImages","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/backgroundColor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/contextualInfoSettings","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/delegate","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/edgeInsets","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/fitBounds","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/fitMode","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/isRenderingRoute","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/map","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/nextRouteLegButton","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/previousRouteLegButton","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/route","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/routeLegIndex","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/routeStepIndex","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/solidColor"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/animate(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRenderer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1route\/title","value":"route"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1route\/fragments","value":[{"kind":"identifier","text":"route"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1edgeInsets\/title","value":"edgeInsets"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1edgeInsets\/fragments","value":[{"kind":"identifier","text":"edgeInsets"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1routeStepIndex\/title","value":"routeStepIndex"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1routeStepIndex\/fragments","value":[{"kind":"identifier","text":"routeStepIndex"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1nextRouteLegButton\/title","value":"nextRouteLegButton"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1nextRouteLegButton\/fragments","value":[{"kind":"identifier","text":"nextRouteLegButton"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1map\/title","value":"map"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1map\/fragments","value":[{"kind":"identifier","text":"map"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1isRenderingRoute\/title","value":"isRenderingRoute"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1isRenderingRoute\/fragments","value":[{"kind":"identifier","text":"isRenderingRoute"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1routeLegIndex\/title","value":"routeLegIndex"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1routeLegIndex\/fragments","value":[{"kind":"identifier","text":"routeLegIndex"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1previousRouteLegButton\/title","value":"previousRouteLegButton"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1previousRouteLegButton\/fragments","value":[{"kind":"identifier","text":"previousRouteLegButton"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1contextualInfoSettings\/title","value":"contextualInfoSettings"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1contextualInfoSettings\/fragments","value":[{"kind":"identifier","text":"contextualInfoSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1fitBounds\/title","value":"fitBounds"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1fitBounds\/fragments","value":[{"kind":"identifier","text":"fitBounds"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1backgroundColor\/title","value":"backgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1backgroundColor\/fragments","value":[{"kind":"identifier","text":"backgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1solidColor\/title","value":"solidColor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1solidColor\/fragments","value":[{"kind":"identifier","text":"solidColor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/title","value":"MPDirectionsRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1fitMode\/title","value":"fitMode"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1fitMode\/fragments","value":[{"kind":"identifier","text":"fitMode"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1animate(_:)\/title","value":"animate:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1animate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animate:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1actionPointImages\/title","value":"actionPointImages"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1actionPointImages\/fragments","value":[{"kind":"identifier","text":"actionPointImages"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}