{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloorTileLayer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpfloortilelayer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpfloortilelayer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPOnlineTileLayer"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/init(venue:andFloor:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/floor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/subdomains","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/urlTemplate","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/venueId"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/parseUrl()"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/setTileSize(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/tileSize()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloorTileLayer"}],"title":"MPFloorTileLayer","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPFloorTileLayer","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPFloorTileLayer"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPFloorTileLayer/urlTemplate":{"role":"symbol","title":"urlTemplate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlTemplate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The url template string to use when fetching tiles. Must have format “prefix{param_1}infix{param_N}suffix”, e.g.: “http:\/\/tiles.url.com\/{floor}\/{x}\/{y}\/{zoom}.png”"},{"type":"text","text":" "},{"type":"text","text":"By default the implementation of this tilelayer will look for {venueId}\/{style}\/{buildingId}\/{floor}\/{z}\/{x}\/{y}, where x, y and z is mandatory."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/urlTemplate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"urlTemplate"}],"url":"\/documentation\/mapsindoors\/mpfloortilelayer\/urltemplate"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorTileLayer/floor":{"role":"symbol","title":"floor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPFloor","preciseIdentifier":"c:objc(cs)MPFloor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Floor property"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/floor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floor"}],"url":"\/documentation\/mapsindoors\/mpfloortilelayer\/floor"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorTileLayer/tileSize()":{"role":"symbol","title":"tileSize()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileSize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Get the indoor floor tile-size for rendering."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/tileSize()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tileSize"}],"url":"\/documentation\/mapsindoors\/mpfloortilelayer\/tilesize()"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorTileLayer/subdomains":{"role":"symbol","title":"subdomains","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subdomains"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Array of strings identifying subdomains. If this property is set, and the url template contains the parameter {subdomain}, the tilelayer will do round-robin over the subdomains specified."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/subdomains","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subdomains"}],"url":"\/documentation\/mapsindoors\/mpfloortilelayer\/subdomains"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorTileLayer/setTileSize(_:)":{"role":"symbol","title":"setTileSize(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTileSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Set the indoor floor tile-size for rendering."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/setTileSize(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setTileSize:"}],"url":"\/documentation\/mapsindoors\/mpfloortilelayer\/settilesize(_:)"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorTileLayer/init(venue:andFloor:)":{"role":"symbol","title":"init(venue:andFloor:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"venue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPVenue","preciseIdentifier":"c:objc(cs)MPVenue"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andFloor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPFloor","preciseIdentifier":"c:objc(cs)MPFloor"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Instantiate using a venue and a floor object."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/init(venue:andFloor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithVenue:andFloor:"}],"url":"\/documentation\/mapsindoors\/mpfloortilelayer\/init(venue:andfloor:)"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorTileLayer/venueId":{"role":"symbol","title":"venueId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"venueId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Venue id"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/venueId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"venueId"}],"url":"\/documentation\/mapsindoors\/mpfloortilelayer\/venueid"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorTileLayer":{"role":"symbol","title":"MPFloorTileLayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloorTileLayer"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPFloorTileLayer"}],"url":"\/documentation\/mapsindoors\/mpfloortilelayer"},"doc://MapsIndoors/documentation/MapsIndoors/MPOnlineTileLayer":{"role":"symbol","title":"MPOnlineTileLayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPOnlineTileLayer"}],"abstract":[{"type":"text","text":"Online tile layer. Used to serve a google map with a MapsPeople online tileservice."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPOnlineTileLayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPOnlineTileLayer"}],"url":"\/documentation\/mapsindoors\/mponlinetilelayer"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorTileLayer/parseUrl()":{"role":"symbol","title":"parseUrl()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseUrl"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Parse the url template. Normally, this is done automatically"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/parseUrl()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parseUrl"}],"url":"\/documentation\/mapsindoors\/mpfloortilelayer\/parseurl()"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPFloorTileLayer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPFloorTileLayer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPFloorTileLayer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/floor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/subdomains","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/urlTemplate","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/venueId"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/init(venue:andFloor:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/parseUrl()"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/setTileSize(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/tileSize()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloorTileLayer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPOnlineTileLayer","preciseIdentifier":"c:objc(cs)MPOnlineTileLayer","text":"MPOnlineTileLayer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer~1urlTemplate\/title","value":"urlTemplate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer~1urlTemplate\/fragments","value":[{"kind":"identifier","text":"urlTemplate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer~1floor\/title","value":"floor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer~1floor\/fragments","value":[{"kind":"identifier","text":"floor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer~1tileSize()\/title","value":"tileSize"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer~1tileSize()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"tileSize"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer~1subdomains\/title","value":"subdomains"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer~1subdomains\/fragments","value":[{"kind":"identifier","text":"subdomains"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer~1setTileSize(_:)\/title","value":"setTileSize:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer~1setTileSize(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setTileSize:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer~1init(venue:andFloor:)\/title","value":"initWithVenue:andFloor:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer~1init(venue:andFloor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVenue:andFloor:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer~1venueId\/title","value":"venueId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer~1venueId\/fragments","value":[{"kind":"identifier","text":"venueId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer\/title","value":"MPFloorTileLayer"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer\/fragments","value":[{"kind":"identifier","text":"MPFloorTileLayer"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPOnlineTileLayer\/title","value":"MPOnlineTileLayer"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPOnlineTileLayer\/fragments","value":[{"kind":"identifier","text":"MPOnlineTileLayer"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer~1parseUrl()\/title","value":"parseUrl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer~1parseUrl()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parseUrl"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}