{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloorSelectorControl"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpfloorselectorcontrol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpfloorselectorcontrol"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorProtocol","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/objc(pl)CALayerDelegate","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH","doc:\/\/MapsIndoors\/objc(pl)UIAccessibilityIdentification","doc:\/\/MapsIndoors\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/MapsIndoors\/objc(pl)UIAppearance","doc:\/\/MapsIndoors\/objc(pl)UIAppearanceContainer","doc:\/\/MapsIndoors\/objc(pl)UICoordinateSpace","doc:\/\/MapsIndoors\/objc(pl)UIDynamicItem","doc:\/\/MapsIndoors\/objc(pl)UIFocusEnvironment","doc:\/\/MapsIndoors\/objc(pl)UIFocusItem","doc:\/\/MapsIndoors\/objc(pl)UIFocusItemContainer","doc:\/\/MapsIndoors\/objc(pl)UILargeContentViewerItem","doc:\/\/MapsIndoors\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/MapsIndoors\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/MapsIndoors\/objc(pl)UIResponderStandardEditActions","doc:\/\/MapsIndoors\/objc(pl)UITraitEnvironment","doc:\/\/MapsIndoors\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Floor selection UI element. Can be added to the map, but should be linked to an MPBuilding to make sense."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloorSelectorControl"}],"title":"MPFloorSelectorControl","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPFloorSelectorControl","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPFloorSelectorControl"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/buttonSize","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/buttons","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/currentFloor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/disableAutomaticLayoutManagement","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/fromFloorIndex","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/maxHeight","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/nFloors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/topIcon","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/topImageView"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/add(to:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/add(toMap:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/notifyFloorSelect(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/setUserFloor(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/updateFrame()"]},{"title":"Type Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/floorButtonBackgroundColor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/floorButtonBorderPadding","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/floorButtonTitleColor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/selectedFloorButtonBackgroundColor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/selectedFloorButtonTitleColor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/userFloorColor"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/selectedColor()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/setSelectedColor(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/setTintColor(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/tintColor()"]}],"references":{"doc://MapsIndoors/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIFocusItem"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/setUserFloor(_:)":{"role":"symbol","title":"setUserFloor(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserFloor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the floor index that the user\/device is located. This value is used to provide an indicator on the floor selector, regardless of the floor actually displayed"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/setUserFloor(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setUserFloor:"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/setuserfloor(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/updateFrame()":{"role":"symbol","title":"updateFrame()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateFrame"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Update the floor selector view frame. Needed upon switch to landscape\/portrait"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/updateFrame()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateFrame"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/updateframe()"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/setTintColor(_:)":{"role":"symbol","title":"setTintColor(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTintColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Set the tint color for the floor buttons."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/setTintColor(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setTintColor:"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/settintcolor(_:)"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIResponderStandardEditActions"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/selectedColor()":{"role":"symbol","title":"selectedColor()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedColor"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the background color for the selected floor button."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/selectedColor()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedColor"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/selectedcolor()"},"doc://MapsIndoors/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIAppearance"},"doc://MapsIndoors/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIUserActivityRestoring"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/disableAutomaticLayoutManagement":{"role":"symbol","title":"disableAutomaticLayoutManagement","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableAutomaticLayoutManagement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/disableAutomaticLayoutManagement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"disableAutomaticLayoutManagement"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/disableautomaticlayoutmanagement"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl":{"role":"symbol","title":"MPFloorSelectorControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloorSelectorControl"}],"abstract":[{"type":"text","text":"Floor selection UI element. Can be added to the map, but should be linked to an MPBuilding to make sense."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPFloorSelectorControl"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol"},"doc://MapsIndoors/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/MapsIndoors\/objc(pl)UITraitEnvironment"},"doc://MapsIndoors/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/MapsIndoors\/objc(pl)CALayerDelegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/add(to:)":{"deprecated":true,"role":"symbol","title":"add(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Add the floor selector to a view."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/add(to:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addToView:"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/add(to:)"},"doc://MapsIndoors/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://MapsIndoors/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIFocusItemContainer"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/buttons":{"role":"symbol","title":"buttons","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttons"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Array of the floor selector buttons."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/buttons","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buttons"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/buttons"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/selectedFloorButtonBackgroundColor":{"role":"symbol","title":"selectedFloorButtonBackgroundColor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedFloorButtonBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The backgroundColor of floor selector buttons in selected state."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/selectedFloorButtonBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedFloorButtonBackgroundColor"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/selectedfloorbuttonbackgroundcolor"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/fromFloorIndex":{"role":"symbol","title":"fromFloorIndex","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromFloorIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Floor index to start from (typically 0)."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/fromFloorIndex","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fromFloorIndex"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/fromfloorindex"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/selectedFloorButtonTitleColor":{"role":"symbol","title":"selectedFloorButtonTitleColor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedFloorButtonTitleColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The textColor of floor selector buttons in selected state."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/selectedFloorButtonTitleColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedFloorButtonTitleColor"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/selectedfloorbuttontitlecolor"},"doc://MapsIndoors/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/MapsIndoors\/objc(cs)UIView"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/nFloors":{"role":"symbol","title":"nFloors","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nFloors"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The number of floors."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/nFloors","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nFloors"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/nfloors"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorProtocol":{"role":"symbol","title":"MPFloorSelectorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloorSelectorProtocol"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPFloorSelectorProtocol"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorprotocol"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/floorButtonTitleColor":{"role":"symbol","title":"floorButtonTitleColor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floorButtonTitleColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The textColor of floor selector buttons in normal state."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/floorButtonTitleColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floorButtonTitleColor"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/floorbuttontitlecolor"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/floorButtonBorderPadding":{"role":"symbol","title":"floorButtonBorderPadding","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floorButtonBorderPadding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The padding around floor selector buttons.  Defaults to 1."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/floorButtonBorderPadding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floorButtonBorderPadding"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/floorbuttonborderpadding"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/topIcon":{"role":"symbol","title":"topIcon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The top icon image."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/topIcon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"topIcon"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/topicon"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/floorButtonBackgroundColor":{"role":"symbol","title":"floorButtonBackgroundColor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floorButtonBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The backgroundColor of floor selector buttons in normal state."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/floorButtonBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floorButtonBackgroundColor"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/floorbuttonbackgroundcolor"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/add(toMap:)":{"deprecated":true,"role":"symbol","title":"add(toMap:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toMap"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSMapView","preciseIdentifier":"c:objc(cs)GMSMapView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Add the floor selector to a map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/add(toMap:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addToMap:"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/add(tomap:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/userFloorColor":{"role":"symbol","title":"userFloorColor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userFloorColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The color of the indicator current user location floor."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/userFloorColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userFloorColor"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/userfloorcolor"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/maxHeight":{"role":"symbol","title":"maxHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The maximum height that the floor selector may occupy"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/maxHeight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxHeight"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/maxheight"},"doc://MapsIndoors/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIPasteConfigurationSupporting"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/topImageView":{"role":"symbol","title":"topImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"UIImageView containing the top image."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/topImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"topImageView"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/topimageview"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIAppearanceContainer"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/currentFloor":{"role":"symbol","title":"currentFloor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentFloor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The current floor."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/currentFloor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"currentFloor"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/currentfloor"},"doc://MapsIndoors/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIDynamicItem"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/notifyFloorSelect(_:)":{"role":"symbol","title":"notifyFloorSelect(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyFloorSelect"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method that fires when a floor button is pressed."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/notifyFloorSelect(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"notifyFloorSelect:"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/notifyfloorselect(_:)"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIFocusEnvironment"},"doc://MapsIndoors/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/MapsIndoors\/objc(pl)UILargeContentViewerItem"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/setSelectedColor(_:)":{"role":"symbol","title":"setSelectedColor(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSelectedColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Set the background color for the selected floor button."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/setSelectedColor(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSelectedColor:"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/setselectedcolor(_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIAccessibilityIdentification"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://MapsIndoors/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/MapsIndoors\/objc(pl)UICoordinateSpace"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/tintColor()":{"role":"symbol","title":"tintColor()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tintColor"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the tint color for the floor buttons."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/tintColor()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tintColor"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/tintcolor()"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/buttonSize":{"role":"symbol","title":"buttonSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The size of a single floor button (buttonSize x buttonSize)."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/buttonSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buttonSize"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/buttonsize"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPFloorSelectorControl"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPFloorSelectorControl"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPFloorSelectorControl"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/buttonSize","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/buttons","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/currentFloor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/disableAutomaticLayoutManagement","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/floorButtonBackgroundColor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/floorButtonBorderPadding","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/floorButtonTitleColor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/fromFloorIndex","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/maxHeight","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/nFloors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/selectedFloorButtonBackgroundColor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/selectedFloorButtonTitleColor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/topIcon","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/topImageView","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/userFloorColor"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/add(to:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/add(toMap:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/notifyFloorSelect(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/setUserFloor(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/updateFrame()"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/selectedColor()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/setSelectedColor(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/setTintColor(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/tintColor()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloorSelectorControl"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1setUserFloor(_:)\/title","value":"setUserFloor:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1setUserFloor(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setUserFloor:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1updateFrame()\/title","value":"updateFrame"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1updateFrame()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateFrame"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1setTintColor(_:)\/title","value":"setTintColor:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1setTintColor(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setTintColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1selectedColor()\/title","value":"selectedColor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1selectedColor()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"selectedColor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1disableAutomaticLayoutManagement\/title","value":"disableAutomaticLayoutManagement"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1disableAutomaticLayoutManagement\/fragments","value":[{"kind":"identifier","text":"disableAutomaticLayoutManagement"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl\/title","value":"MPFloorSelectorControl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl\/fragments","value":[{"kind":"identifier","text":"MPFloorSelectorControl"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1add(to:)\/title","value":"addToView:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1add(to:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addToView:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1buttons\/title","value":"buttons"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1buttons\/fragments","value":[{"kind":"identifier","text":"buttons"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1selectedFloorButtonBackgroundColor\/title","value":"selectedFloorButtonBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1selectedFloorButtonBackgroundColor\/fragments","value":[{"kind":"identifier","text":"selectedFloorButtonBackgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1fromFloorIndex\/title","value":"fromFloorIndex"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1fromFloorIndex\/fragments","value":[{"kind":"identifier","text":"fromFloorIndex"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1selectedFloorButtonTitleColor\/title","value":"selectedFloorButtonTitleColor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1selectedFloorButtonTitleColor\/fragments","value":[{"kind":"identifier","text":"selectedFloorButtonTitleColor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1nFloors\/title","value":"nFloors"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1nFloors\/fragments","value":[{"kind":"identifier","text":"nFloors"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorProtocol\/title","value":"MPFloorSelectorProtocol"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorProtocol\/fragments","value":[{"kind":"identifier","text":"MPFloorSelectorProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1floorButtonTitleColor\/title","value":"floorButtonTitleColor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1floorButtonTitleColor\/fragments","value":[{"kind":"identifier","text":"floorButtonTitleColor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1floorButtonBorderPadding\/title","value":"floorButtonBorderPadding"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1floorButtonBorderPadding\/fragments","value":[{"kind":"identifier","text":"floorButtonBorderPadding"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1topIcon\/title","value":"topIcon"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1topIcon\/fragments","value":[{"kind":"identifier","text":"topIcon"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1floorButtonBackgroundColor\/title","value":"floorButtonBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1floorButtonBackgroundColor\/fragments","value":[{"kind":"identifier","text":"floorButtonBackgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1add(toMap:)\/title","value":"addToMap:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1add(toMap:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addToMap:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1userFloorColor\/title","value":"userFloorColor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1userFloorColor\/fragments","value":[{"kind":"identifier","text":"userFloorColor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1maxHeight\/title","value":"maxHeight"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1maxHeight\/fragments","value":[{"kind":"identifier","text":"maxHeight"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1topImageView\/title","value":"topImageView"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1topImageView\/fragments","value":[{"kind":"identifier","text":"topImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1currentFloor\/title","value":"currentFloor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1currentFloor\/fragments","value":[{"kind":"identifier","text":"currentFloor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1notifyFloorSelect(_:)\/title","value":"notifyFloorSelect:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1notifyFloorSelect(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"notifyFloorSelect:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1setSelectedColor(_:)\/title","value":"setSelectedColor:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1setSelectedColor(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setSelectedColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1tintColor()\/title","value":"tintColor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1tintColor()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"tintColor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1buttonSize\/title","value":"buttonSize"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1buttonSize\/fragments","value":[{"kind":"identifier","text":"buttonSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}