{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpGeocodeHandlerBlockType"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class","preciseIdentifier":"c:objc(cs)MPVenue","text":"MPVenue"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class","preciseIdentifier":"c:objc(cs)MPBuilding","text":"MPBuilding"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class","preciseIdentifier":"c:objc(cs)MPFloor","text":"MPFloor"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"venue","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Building containing the geographic point. Can be nil."}]}]},{"name":"building","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Building containing the geographic point. Can be nil."}]}]},{"name":"floor","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Building containing the geographic point. Can be nil."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error object. Can be nil."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpgeocodehandlerblocktype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpgeocodehandlerblocktype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpGeocodeHandlerBlockType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Handler block for fetching data related to a geographic point"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpGeocodeHandlerBlockType"}],"title":"mpGeocodeHandlerBlockType","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias","externalID":"c:MPVenueProvider.h@T@mpGeocodeHandlerBlockType","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"mpGeocodeHandlerBlockType"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/mpGeocodeHandlerBlockType":{"role":"symbol","title":"mpGeocodeHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpGeocodeHandlerBlockType"}],"abstract":[{"type":"text","text":"Handler block for fetching data related to a geographic point"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpGeocodeHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpGeocodeHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpgeocodehandlerblocktype"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class":{"role":"symbol","title":"MPBuilding","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuilding"}],"abstract":[{"type":"text","text":"Holds relevant data for a single building, and the buildings floor levels."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBuilding"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloor-swift.class":{"role":"symbol","title":"MPFloor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloor"}],"abstract":[{"type":"text","text":"Floor data model. Holds the floor geometry, display name, z-index and id of the building it belongs to."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPFloor"}],"url":"\/documentation\/mapsindoors\/mpfloor-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class":{"role":"symbol","title":"MPVenue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenue"}],"abstract":[{"type":"text","text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenue"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"mpGeocodeHandlerBlockType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mpGeocodeHandlerBlockType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"mpGeocodeHandlerBlockType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(MPVenue *, MPBuilding *, MPFloor *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)MPVenue#*$objc(cs)MPBuilding#*$objc(cs)MPFloor#*$objc(cs)NSError)"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpGeocodeHandlerBlockType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpGeocodeHandlerBlockType\/title","value":"mpGeocodeHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpGeocodeHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpGeocodeHandlerBlockType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class\/title","value":"MPBuilding"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class\/fragments","value":[{"kind":"identifier","text":"MPBuilding"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class\/title","value":"MPFloor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class\/fragments","value":[{"kind":"identifier","text":"MPFloor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class\/title","value":"MPVenue"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class\/fragments","value":[{"kind":"identifier","text":"MPVenue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}