{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplivedatamanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplivedatamanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The Live Data Manager class is the central class for managing Live Update subscriptions."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManager"}],"title":"MPLiveDataManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPLiveDataManager","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManager"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/delegate","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/state","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/subscriptions"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/subscribe(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/unsubscribe(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/unsubscribeAll()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/updateLiveDataInfo()"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/sharedInstance()"]}],"references":{"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(cs)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManager/unsubscribe(_:)":{"role":"symbol","title":"unsubscribe(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsubscribe"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Unsubscribe to Live Updates with a given Topic Criteria. When the last Topic Criteria is successfully unsubscribed the Live Data Manager will disconnect from the Live Update remote services."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/unsubscribe(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unsubscribe:"}],"url":"\/documentation\/mapsindoors\/mplivedatamanager\/unsubscribe(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManager/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLiveDataManagerDelegate","preciseIdentifier":"c:objc(pl)MPLiveDataManagerDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Set or get the Live Data Manager Delegate. The delegate recieves all Live Updates, state changes, errors and other calls from the Live Data Manager."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/mapsindoors\/mplivedatamanager\/delegate"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManager/state":{"role":"symbol","title":"state","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLiveDataManagerState","preciseIdentifier":"c:@E@MPLiveDataManagerState"}],"abstract":[{"type":"text","text":"Get the state of the Live Data Manager."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/state","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"state"}],"url":"\/documentation\/mapsindoors\/mplivedatamanager\/state"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManager/updateLiveDataInfo()":{"role":"symbol","title":"updateLiveDataInfo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateLiveDataInfo"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Update Live Data information, including list of active Domain Types for the current dataset."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/updateLiveDataInfo()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateLiveDataInfo"}],"url":"\/documentation\/mapsindoors\/mplivedatamanager\/updatelivedatainfo()"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManager/sharedInstance()":{"role":"symbol","title":"sharedInstance()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MPLiveDataManager","preciseIdentifier":"c:objc(cs)MPLiveDataManager"}],"abstract":[{"type":"text","text":"Get (or create and get) the shared instance of the Live Data Manager."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/sharedInstance()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedInstance"}],"url":"\/documentation\/mapsindoors\/mplivedatamanager\/sharedinstance()"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManager":{"role":"symbol","title":"MPLiveDataManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManager"}],"abstract":[{"type":"text","text":"The Live Data Manager class is the central class for managing Live Update subscriptions."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManager"}],"url":"\/documentation\/mapsindoors\/mplivedatamanager"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManager/unsubscribeAll()":{"role":"symbol","title":"unsubscribeAll()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsubscribeAll"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Unsubscribe all Live Updates. When the last Topic Criteria is successfully unsubscribed the Live Data Manager will disconnect from the Live Update remote services."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/unsubscribeAll()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unsubscribeAll"}],"url":"\/documentation\/mapsindoors\/mplivedatamanager\/unsubscribeall()"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManager/subscribe(_:)":{"role":"symbol","title":"subscribe(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribe"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Subscribe to Live Updates with a given Topic Criteria. If no previous subscriptions have been made, the Live Data Manager will first connect to the Live Update remote services."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/subscribe(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subscribe:"}],"url":"\/documentation\/mapsindoors\/mplivedatamanager\/subscribe(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManager/subscriptions":{"role":"symbol","title":"subscriptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscriptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Get the currently active and successful subscriptions."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/subscriptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subscriptions"}],"url":"\/documentation\/mapsindoors\/mplivedatamanager\/subscriptions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPLiveDataManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPLiveDataManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/delegate","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/state","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/subscriptions"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/subscribe(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/unsubscribe(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/unsubscribeAll()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/updateLiveDataInfo()"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/sharedInstance()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1unsubscribe(_:)\/title","value":"unsubscribe:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1unsubscribe(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unsubscribe:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1state\/title","value":"state"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1state\/fragments","value":[{"kind":"identifier","text":"state"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1updateLiveDataInfo()\/title","value":"updateLiveDataInfo"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1updateLiveDataInfo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateLiveDataInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1sharedInstance()\/title","value":"sharedInstance"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1sharedInstance()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedInstance"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager\/title","value":"MPLiveDataManager"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManager"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1unsubscribeAll()\/title","value":"unsubscribeAll"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1unsubscribeAll()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unsubscribeAll"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1subscribe(_:)\/title","value":"subscribe:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1subscribe(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"subscribe:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1subscriptions\/title","value":"subscriptions"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1subscriptions\/fragments","value":[{"kind":"identifier","text":"subscriptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}