{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveTopicCriteria"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplivetopiccriteria"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplivetopiccriteria"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionTopic","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Live Topic Criteria model used for subscriptions to Live Updates using MPLiveDataManager."},{"type":"text","text":" "},{"type":"text","text":"A Live Topic Criteria is hierarchical in the way it is defined, and its relation to MapsIndoors data is derivable by its 7 components: Dataset, Venue, Building, Floor, Room, Location and Domain Type."},{"type":"text","text":" "},{"type":"text","text":"All properties can be left out but datasetId will then default to the currently active dataset."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveTopicCriteria"}],"title":"MPLiveTopicCriteria","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPLiveTopicCriteria","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLiveTopicCriteria"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/building(_:)-swift.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/dataset(_:)-swift.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/domainType(_:)-swift.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/floor(_:)-swift.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/location(_:)-swift.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/room(_:)-swift.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/venue(_:)-swift.method"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/building(_:)-swift.type.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/dataset(_:)-swift.type.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/domainType(_:)-swift.type.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/floor(_:)-swift.type.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/location(_:)-swift.type.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/room(_:)-swift.type.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/venue(_:)-swift.type.method"]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria/floor(_:)-swift.type.method":{"role":"symbol","title":"floor(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"floor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Initialise a Topic Criteria with given Floor id."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/floor(_:)-swift.type.method","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floor:"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria\/floor(_:)-swift.type.method"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria/room(_:)-swift.type.method":{"role":"symbol","title":"room(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"room"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Initialise a Topic Criteria with given Room id."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/room(_:)-swift.type.method","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"room:"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria\/room(_:)-swift.type.method"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria/dataset(_:)-swift.type.method":{"role":"symbol","title":"dataset(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataset"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Initialise a Topic Criteria with given Dataset id."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/dataset(_:)-swift.type.method","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dataset:"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria\/dataset(_:)-swift.type.method"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria/location(_:)-swift.type.method":{"role":"symbol","title":"location(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"location"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Initialise a Topic Criteria with given Location id."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/location(_:)-swift.type.method","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"location:"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria\/location(_:)-swift.type.method"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria/location(_:)-swift.method":{"role":"symbol","title":"location(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"location"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Get Topic Criteria with given Location id changed."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/location(_:)-swift.method","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"location:"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria\/location(_:)-swift.method"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria/room(_:)-swift.method":{"role":"symbol","title":"room(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"room"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Get Topic Criteria with given Room id changed."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/room(_:)-swift.method","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"room:"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria\/room(_:)-swift.method"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria/building(_:)-swift.method":{"role":"symbol","title":"building(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"building"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Get Topic Criteria with given Building id changed."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/building(_:)-swift.method","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"building:"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria\/building(_:)-swift.method"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria":{"role":"symbol","title":"MPLiveTopicCriteria","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Live Topic Criteria model used for subscriptions to Live Updates using MPLiveDataManager."},{"type":"text","text":" "},{"type":"text","text":"A Live Topic Criteria is hierarchical in the way it is defined, and its relation to MapsIndoors data is derivable by its 7 components: Dataset, Venue, Building, Floor, Room, Location and Domain Type."},{"type":"text","text":" "},{"type":"text","text":"All properties can be left out but datasetId will then default to the currently active dataset."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveTopicCriteria"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria/domainType(_:)-swift.method":{"role":"symbol","title":"domainType(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"domainType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Get Topic Criteria with given Domain Type changed."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/domainType(_:)-swift.method","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"domainType:"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria\/domaintype(_:)-swift.method"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria/dataset(_:)-swift.method":{"role":"symbol","title":"dataset(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataset"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Get Topic Criteria with given Dataset id changed."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/dataset(_:)-swift.method","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dataset:"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria\/dataset(_:)-swift.method"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria/venue(_:)-swift.method":{"role":"symbol","title":"venue(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"venue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Get Topic Criteria with given Venue id changed."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/venue(_:)-swift.method","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"venue:"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria\/venue(_:)-swift.method"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveUpdateTopic":{"role":"symbol","title":"MPLiveUpdateTopic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveUpdateTopic"}],"abstract":[{"type":"text","text":"Topic model for a Live Update. A Live Update Topic is hierarchical in the way it is defined, and its relation to MapsIndoors data is derivable by its 7 components: Dataset, Venue, Building, Floor, Room, Location and Domain Type"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveUpdateTopic"}],"url":"\/documentation\/mapsindoors\/mpliveupdatetopic"},"doc://MapsIndoors/documentation/MapsIndoors/MPSubscriptionTopic":{"role":"symbol","title":"MPSubscriptionTopic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSubscriptionTopic"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionTopic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionTopic"}],"url":"\/documentation\/mapsindoors\/mpsubscriptiontopic"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria/building(_:)-swift.type.method":{"role":"symbol","title":"building(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"building"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Initialise a Topic Criteria with given Building id."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/building(_:)-swift.type.method","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"building:"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria\/building(_:)-swift.type.method"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria/venue(_:)-swift.type.method":{"role":"symbol","title":"venue(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"venue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Initialise a Topic Criteria with given Venue id."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/venue(_:)-swift.type.method","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"venue:"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria\/venue(_:)-swift.type.method"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria/domainType(_:)-swift.type.method":{"role":"symbol","title":"domainType(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"domainType"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Initialise a Topic Criteria with given Domain Type."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/domainType(_:)-swift.type.method","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"domainType:"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria\/domaintype(_:)-swift.type.method"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria/floor(_:)-swift.method":{"role":"symbol","title":"floor(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"floor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Get Topic Criteria with given Floor id changed."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/floor(_:)-swift.method","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floor:"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria\/floor(_:)-swift.method"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPLiveTopicCriteria"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLiveTopicCriteria"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPLiveTopicCriteria"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/building(_:)-swift.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/dataset(_:)-swift.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/domainType(_:)-swift.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/floor(_:)-swift.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/location(_:)-swift.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/room(_:)-swift.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/venue(_:)-swift.method"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/building(_:)-swift.type.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/dataset(_:)-swift.type.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/domainType(_:)-swift.type.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/floor(_:)-swift.type.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/location(_:)-swift.type.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/room(_:)-swift.type.method","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/venue(_:)-swift.type.method"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveTopicCriteria"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic","preciseIdentifier":"c:objc(cs)MPLiveUpdateTopic","text":"MPLiveUpdateTopic"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1floor(_:)-swift.type.method\/title","value":"floor:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1floor(_:)-swift.type.method\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"floor:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1room(_:)-swift.type.method\/title","value":"room:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1room(_:)-swift.type.method\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"room:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1dataset(_:)-swift.type.method\/title","value":"dataset:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1dataset(_:)-swift.type.method\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"dataset:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1location(_:)-swift.type.method\/title","value":"location:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1location(_:)-swift.type.method\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"location:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1location(_:)-swift.method\/title","value":"location:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1location(_:)-swift.method\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"location:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1room(_:)-swift.method\/title","value":"room:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1room(_:)-swift.method\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"room:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1building(_:)-swift.method\/title","value":"building:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1building(_:)-swift.method\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"building:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria\/title","value":"MPLiveTopicCriteria"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria\/fragments","value":[{"kind":"identifier","text":"MPLiveTopicCriteria"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1domainType(_:)-swift.method\/title","value":"domainType:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1domainType(_:)-swift.method\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"domainType:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1dataset(_:)-swift.method\/title","value":"dataset:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1dataset(_:)-swift.method\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dataset:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1venue(_:)-swift.method\/title","value":"venue:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1venue(_:)-swift.method\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"venue:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic\/title","value":"MPLiveUpdateTopic"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic\/fragments","value":[{"kind":"identifier","text":"MPLiveUpdateTopic"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionTopic\/title","value":"MPSubscriptionTopic"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionTopic\/fragments","value":[{"kind":"identifier","text":"MPSubscriptionTopic"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1building(_:)-swift.type.method\/title","value":"building:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1building(_:)-swift.type.method\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"building:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1venue(_:)-swift.type.method\/title","value":"venue:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1venue(_:)-swift.type.method\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"venue:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1domainType(_:)-swift.type.method\/title","value":"domainType:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1domainType(_:)-swift.type.method\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"domainType:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1floor(_:)-swift.method\/title","value":"floor:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1floor(_:)-swift.method\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"floor:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}