{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationQueryMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationquerymode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationquerymode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH","doc:\/\/MapsIndoors\/SY","doc:\/\/MapsIndoors\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQueryMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Locations query mode"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationQueryMode"}],"title":"MPLocationQueryMode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@MPLocationQueryMode","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLocationQueryMode"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQueryMode\/autocomplete","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQueryMode\/normal"]},{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQueryMode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQueryMode\/Equatable-Implementations","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQueryMode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/MapsIndoors\/s8SendableP"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQueryMode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQueryMode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mplocationquerymode\/equatable-implementations"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQueryMode":{"role":"symbol","title":"MPLocationQueryMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationQueryMode"}],"abstract":[{"type":"text","text":"Locations query mode"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQueryMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationQueryMode"}],"url":"\/documentation\/mapsindoors\/mplocationquerymode"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/MapsIndoors\/SY"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQueryMode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQueryMode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mplocationquerymode\/init(rawvalue:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQueryMode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQueryMode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mplocationquerymode\/rawrepresentable-implementations"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQueryMode/autocomplete":{"role":"symbol","title":"MPLocationQueryMode.autocomplete","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"autocomplete"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQueryMode\/autocomplete","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationQueryModeAutocomplete"}],"url":"\/documentation\/mapsindoors\/mplocationquerymode\/autocomplete"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQueryMode/normal":{"role":"symbol","title":"MPLocationQueryMode.normal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"normal"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQueryMode\/normal","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationQueryModeNormal"}],"url":"\/documentation\/mapsindoors\/mplocationquerymode\/normal"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"MPLocationQueryMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLocationQueryMode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPLocationQueryMode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQueryMode\/autocomplete","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQueryMode\/normal"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationQueryMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQueryMode\/title","value":"MPLocationQueryMode"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQueryMode\/fragments","value":[{"kind":"identifier","text":"MPLocationQueryMode"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQueryMode~1autocomplete\/title","value":"MPLocationQueryModeAutocomplete"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQueryMode~1autocomplete\/fragments","value":[{"kind":"identifier","text":"MPLocationQueryModeAutocomplete"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQueryMode~1normal\/title","value":"MPLocationQueryModeNormal"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQueryMode~1normal\/fragments","value":[{"kind":"identifier","text":"MPLocationQueryModeNormal"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}