{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationQuery"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationquery"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationquery"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Locations query object used in conjunction with the MPLocationsProvider"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationQuery"}],"title":"MPLocationQuery","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPLocationQuery","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLocationQuery"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/init(url:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/building","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/categories","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/floor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/mapExtend","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/max","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/near","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/orderBy","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/query","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/queryGeneration","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/queryMode","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/radius","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/sortOrder","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/types","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/venue","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/zoomLevel"]}],"references":{"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(cs)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery/radius":{"role":"symbol","title":"radius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"radius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Sets a radius limit in meters. Only to be used in conjunction with near property. This will cap the search results to the locations which distance to the near-position is less than specified as radius"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/radius","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"radius"}],"url":"\/documentation\/mapsindoors\/mplocationquery\/radius"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery/orderBy":{"role":"symbol","title":"orderBy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orderBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Order by “relevance”, “name”, “roomId”, “venue”, “building”, “floor”. Default is “relevance”."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/orderBy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orderBy"}],"url":"\/documentation\/mapsindoors\/mplocationquery\/orderby"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery/venue":{"role":"symbol","title":"venue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"venue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Venue filter. Supports the venue key provided in MPVenue.venueKey and MPLocation.venue"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/venue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"venue"}],"url":"\/documentation\/mapsindoors\/mplocationquery\/venue"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery/near":{"role":"symbol","title":"near","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"near"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Set a reference position coordinate. Distances to this position will affect the relevance of the search results. Only applies when ordering by relevance (default sort order)."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/near","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"near"}],"url":"\/documentation\/mapsindoors\/mplocationquery\/near"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery/categories":{"role":"symbol","title":"categories","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"categories"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Category filter. Supports the category keys provided from the MPCategoriesProvider. Does not support the localized names of the categories."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/categories","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"categories"}],"url":"\/documentation\/mapsindoors\/mplocationquery\/categories"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery/max":{"role":"symbol","title":"max","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"max"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Limit the amount of results from the MPLocationsProvider"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/max","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"max"}],"url":"\/documentation\/mapsindoors\/mplocationquery\/max"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery/floor":{"role":"symbol","title":"floor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Floor filter. Supports the floor index provided in MPMapControl.currentFloor and MPLocation.floor"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/floor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floor"}],"url":"\/documentation\/mapsindoors\/mplocationquery\/floor"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery":{"role":"symbol","title":"MPLocationQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationQuery"}],"abstract":[{"type":"text","text":"Locations query object used in conjunction with the MPLocationsProvider"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationQuery"}],"url":"\/documentation\/mapsindoors\/mplocationquery"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery/queryMode":{"role":"symbol","title":"queryMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationQueryMode","preciseIdentifier":"c:@E@MPLocationQueryMode"}],"abstract":[{"type":"text","text":"Location query mode.  Defaults to MPLocationQueryModeNormal."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/queryMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"queryMode"}],"url":"\/documentation\/mapsindoors\/mplocationquery\/querymode"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery/building":{"role":"symbol","title":"building","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"building"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Building filter. Supports the building key provided in MPLocation.building"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/building","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"building"}],"url":"\/documentation\/mapsindoors\/mplocationquery\/building"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery/zoomLevel":{"role":"symbol","title":"zoomLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Sets the zoom level. Currently has no effect on the search results."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/zoomLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"zoomLevel"}],"url":"\/documentation\/mapsindoors\/mplocationquery\/zoomlevel"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery/sortOrder":{"role":"symbol","title":"sortOrder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sortOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Apply a sort order. Can either be “asc” or “desc”. Default is “asc”"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/sortOrder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sortOrder"}],"url":"\/documentation\/mapsindoors\/mplocationquery\/sortorder"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery/init(url:)":{"role":"symbol","title":"init(url:)","fragments":[{"kind":"text","text":"\/*not inherited*\/ "},{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Parses an url, identifies query elements and returns a query object"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/init(url:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"queryWithUrl:"}],"url":"\/documentation\/mapsindoors\/mplocationquery\/init(url:)"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery/queryGeneration":{"role":"symbol","title":"queryGeneration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryGeneration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Query Generation - if the query is reused for multiple searches this will hold the most recent query generation"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/queryGeneration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"queryGeneration"}],"url":"\/documentation\/mapsindoors\/mplocationquery\/querygeneration"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery/mapExtend":{"role":"symbol","title":"mapExtend","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapExtend"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPMapExtend","preciseIdentifier":"c:objc(cs)MPMapExtend"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Adds a geographic filter as a bounding box, specified by north, east, south and west"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/mapExtend","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mapExtend"}],"url":"\/documentation\/mapsindoors\/mplocationquery\/mapextend"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery/query":{"role":"symbol","title":"query","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Free text search string"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/query","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"query"}],"url":"\/documentation\/mapsindoors\/mplocationquery\/query"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery/types":{"role":"symbol","title":"types","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"types"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Types filter. Supports the type strings provided from the MPSolutionsProvider."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/types","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"types"}],"url":"\/documentation\/mapsindoors\/mplocationquery\/types"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPLocationQuery"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLocationQuery"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPLocationQuery"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/building","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/categories","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/floor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/mapExtend","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/max","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/near","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/orderBy","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/query","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/queryGeneration","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/queryMode","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/radius","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/sortOrder","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/types","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/venue","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/zoomLevel"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/init(url:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationQuery"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1radius\/title","value":"radius"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1radius\/fragments","value":[{"kind":"identifier","text":"radius"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1orderBy\/title","value":"orderBy"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1orderBy\/fragments","value":[{"kind":"identifier","text":"orderBy"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1venue\/title","value":"venue"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1venue\/fragments","value":[{"kind":"identifier","text":"venue"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1near\/title","value":"near"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1near\/fragments","value":[{"kind":"identifier","text":"near"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1categories\/title","value":"categories"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1categories\/fragments","value":[{"kind":"identifier","text":"categories"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1max\/title","value":"max"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1max\/fragments","value":[{"kind":"identifier","text":"max"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1floor\/title","value":"floor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1floor\/fragments","value":[{"kind":"identifier","text":"floor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery\/title","value":"MPLocationQuery"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery\/fragments","value":[{"kind":"identifier","text":"MPLocationQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1queryMode\/title","value":"queryMode"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1queryMode\/fragments","value":[{"kind":"identifier","text":"queryMode"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1building\/title","value":"building"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1building\/fragments","value":[{"kind":"identifier","text":"building"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1zoomLevel\/title","value":"zoomLevel"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1zoomLevel\/fragments","value":[{"kind":"identifier","text":"zoomLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1sortOrder\/title","value":"sortOrder"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1sortOrder\/fragments","value":[{"kind":"identifier","text":"sortOrder"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1init(url:)\/title","value":"queryWithUrl:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1init(url:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"queryWithUrl:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1queryGeneration\/title","value":"queryGeneration"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1queryGeneration\/fragments","value":[{"kind":"identifier","text":"queryGeneration"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1mapExtend\/title","value":"mapExtend"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1mapExtend\/fragments","value":[{"kind":"identifier","text":"mapExtend"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1query\/title","value":"query"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1query\/fragments","value":[{"kind":"identifier","text":"query"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1types\/title","value":"types"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1types\/fragments","value":[{"kind":"identifier","text":"types"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}