{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocation-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocation-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)JSONModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionIndicator"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)NSCopying","doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding","doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This class holds the data for a single location and a marker to display the data on a map."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"title":"MPLocation","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPLocation","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLocation"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/init(location:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/init(point:andName:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/activeFrom","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/activeTo","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/aliases","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/baseType","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/building","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/categories","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/descr","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/externalId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/fields","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/floor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/floorName","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/geometry","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/icon","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/iconUrl","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/image","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/imageURL","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/isBookable","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/isIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/locationId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/marker","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/name","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/properties","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/restrictions","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/roomId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/sourceId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/type","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/venue"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getCoordinateBounds()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getField(forKey:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getLiveUpdate(forDomainType:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getLiveValue(forKey:domainType:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getPoint()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getProperty(_:)"]}],"references":{"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/restrictions":{"role":"symbol","title":"restrictions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"restrictions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"If set, location is restricted to given set of app user roles."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/restrictions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"restrictions"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/restrictions"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/iconUrl":{"role":"symbol","title":"iconUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Location icon as a URL. If icon is originally set as a UIImage, this property will be ignored."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/iconUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iconUrl"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/iconurl"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/getLiveUpdate(forDomainType:)":{"role":"symbol","title":"getLiveUpdate(forDomainType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLiveUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forDomainType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLiveUpdate","preciseIdentifier":"c:objc(cs)MPLiveUpdate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get a live update based on a known domain type"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getLiveUpdate(forDomainType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getLiveUpdateForDomainType:"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/getliveupdate(fordomaintype:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/externalId":{"role":"symbol","title":"externalId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"externalId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Location external id property."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/externalId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"externalId"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/externalid"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/isBookable":{"role":"symbol","title":"isBookable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isBookable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines if the MPLocation is bookable using the MPBookingService."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/isBookable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isBookable"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/isbookable"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/activeFrom":{"deprecated":true,"role":"symbol","title":"activeFrom","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeFrom"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Active from timestamp"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/activeFrom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"activeFrom"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/activefrom"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class":{"role":"symbol","title":"MPLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"abstract":[{"type":"text","text":"This class holds the data for a single location and a marker to display the data on a map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/icon":{"role":"symbol","title":"icon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Location icon. If nil, the location will either get an icon from the settings configured for the type of location or a default appearance that is configurable through "},{"type":"codeVoice","code":"MPMapControl"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/icon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"icon"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/icon"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/sourceId":{"role":"symbol","title":"sourceId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Location Source ID. Some implementations have different location sources, and this id is a reference to the location source that created the location. The source ID will remain the same throughout the running application session, but the source ID is not expected to remain the same across sessions."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/sourceId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sourceId"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/sourceid"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/roomId":{"deprecated":true,"role":"symbol","title":"roomId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Location room id property."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/roomId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"roomId"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/roomid"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/marker":{"deprecated":true,"role":"symbol","title":"marker","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"marker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSMarker","preciseIdentifier":"c:objc(cs)GMSMarker"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Marker property used to display on map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/marker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"marker"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/marker"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/getCoordinateBounds()":{"role":"symbol","title":"getCoordinateBounds()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCoordinateBounds"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get coordinate bounds for the location object"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getCoordinateBounds()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getCoordinateBounds"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/getcoordinatebounds()"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/aliases":{"role":"symbol","title":"aliases","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"aliases"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Get aliases for location."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/aliases","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"aliases"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/aliases"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/fields":{"role":"symbol","title":"fields","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"MPLocationField","preciseIdentifier":"c:objc(cs)MPLocationField"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Custom properties associated with the location object."},{"type":"text","text":" "},{"type":"text","text":"Keys are case sensitive.  For case-insensitive access to custom properties use @sa -[getFieldForKey:]"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/fields","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fields"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/fields"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/image":{"deprecated":true,"role":"symbol","title":"image","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Location image."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/image","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"image"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/image"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/floor":{"role":"symbol","title":"floor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"If the location resides on a specific floor level, this property is set. This value correlates with "},{"type":"codeVoice","code":"MPFloor.zIndex"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/floor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floor"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/floor"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/activeTo":{"deprecated":true,"role":"symbol","title":"activeTo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeTo"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Active to timestamp"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/activeTo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"activeTo"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/activeto"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/geometry":{"role":"symbol","title":"geometry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Ignore","preciseIdentifier":"c:objc(pl)Ignore"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Geometry as a Lat\/Long point."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/geometry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"geometry"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/geometry"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/categories":{"role":"symbol","title":"categories","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"categories"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMutableDictionary","preciseIdentifier":"c:objc(cs)NSMutableDictionary"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The categories for this location, as a dictionary."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/categories","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"categories"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/categories"},"doc://MapsIndoors/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCopying"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/building":{"role":"symbol","title":"building","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"building"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Location building property. This string correlates with "},{"type":"codeVoice","code":"MPBuilding.administrativeId"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/building","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"building"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/building"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/getField(forKey:)":{"role":"symbol","title":"getField(forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getField"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLocationField","preciseIdentifier":"c:objc(cs)MPLocationField"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get data for custom property with key, disregarding casing of key."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getField(forKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getFieldForKey:"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/getfield(forkey:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Location type property. This string correlates with "},{"type":"codeVoice","code":"MPType.name"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/type"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/init(location:)":{"deprecated":true,"role":"symbol","title":"init(location:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Location constructor."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/init(location:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLocation:"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/init(location:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/getProperty(_:)":{"deprecated":true,"role":"symbol","title":"getProperty(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getProperty"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"MPLocationProperty","preciseIdentifier":"c:objc(cs)MPLocationProperty"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get location property of the given type identifier"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getProperty(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getProperty:"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/getproperty(_:)"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/getPoint()":{"deprecated":true,"role":"symbol","title":"getPoint()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPoint"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the point holding coordinates for the location object"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getPoint()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getPoint"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/getpoint()"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/descr":{"role":"symbol","title":"descr","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"descr"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Location description property."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/descr","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"descr"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/descr"},"doc://MapsIndoors/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/init(point:andName:)":{"deprecated":true,"role":"symbol","title":"init(point:andName:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"point"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Location constructor."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/init(point:andName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithPoint:andName:"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/init(point:andname:)"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/locationId":{"role":"symbol","title":"locationId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Location id property."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/locationId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"locationId"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/locationid"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/properties":{"deprecated":true,"role":"symbol","title":"properties","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"properties"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMutableDictionary","preciseIdentifier":"c:objc(cs)NSMutableDictionary"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Dictionary of location properties. The keys ‘image’ and ‘description’ will always be present, and possibly others, such as ‘address’, ‘contact’, ‘openinghours’ and ‘_tags’ or your own data structure."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/properties","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"properties"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/properties"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/floorName":{"role":"symbol","title":"floorName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floorName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"If the location resides on a specific floor level, the name of that floor level can be retrieved here."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/floorName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floorName"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/floorname"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/venue":{"role":"symbol","title":"venue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"venue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Location venue property. This string correlates with "},{"type":"codeVoice","code":"MPVenue.venueKey"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/venue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"venue"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/venue"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionIndicator":{"deprecated":true,"role":"symbol","title":"MPPositionIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionIndicator"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPositionIndicator"}],"url":"\/documentation\/mapsindoors\/mppositionindicator"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/imageURL":{"role":"symbol","title":"imageURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"URL for image associated with this MPLocation."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/imageURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageURL"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/imageurl"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/baseType":{"role":"symbol","title":"baseType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationBaseType","preciseIdentifier":"c:@E@MPLocationBaseType"}],"abstract":[{"type":"text","text":"Location base type."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/baseType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"baseType"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/basetype"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/isIndoors":{"role":"symbol","title":"isIndoors","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isIndoors"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Will return YES if location is indoors and belongs to a building, otherwise NO."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/isIndoors","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isIndoors"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/isindoors"},"doc://MapsIndoors/objc(cs)JSONModel":{"type":"unresolvable","title":"JSONModel","identifier":"doc:\/\/MapsIndoors\/objc(cs)JSONModel"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Location name."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/name"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/getLiveValue(forKey:domainType:)":{"role":"symbol","title":"getLiveValue(forKey:domainType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLiveValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"domainType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get a live property value based on a known key and domain type"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getLiveValue(forKey:domainType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getLiveValueForKey:domainType:"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/getlivevalue(forkey:domaintype:)"},"doc://MapsIndoors/objc(pl)AbstractJSONModelProtocol":{"type":"unresolvable","title":"JSONModel.AbstractJSONModelProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPLocation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLocation"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPLocation"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/activeFrom","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/activeTo","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/aliases","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/baseType","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/building","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/categories","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/descr","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/externalId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/fields","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/floor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/floorName","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/geometry","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/icon","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/iconUrl","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/image","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/imageURL","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/isBookable","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/isIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/locationId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/marker","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/name","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/properties","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/restrictions","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/roomId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/sourceId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/type","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/venue"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getCoordinateBounds()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getField(forKey:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getLiveUpdate(forDomainType:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getLiveValue(forKey:domainType:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getPoint()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getProperty(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/init(location:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/init(point:andName:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSONModel","preciseIdentifier":"c:objc(cs)JSONModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1restrictions\/title","value":"restrictions"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1restrictions\/fragments","value":[{"kind":"identifier","text":"restrictions"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1iconUrl\/title","value":"iconUrl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1iconUrl\/fragments","value":[{"kind":"identifier","text":"iconUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1getLiveUpdate(forDomainType:)\/title","value":"getLiveUpdateForDomainType:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1getLiveUpdate(forDomainType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLiveUpdateForDomainType:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1externalId\/title","value":"externalId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1externalId\/fragments","value":[{"kind":"identifier","text":"externalId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1isBookable\/title","value":"isBookable"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1isBookable\/fragments","value":[{"kind":"identifier","text":"isBookable"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1activeFrom\/title","value":"activeFrom"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1activeFrom\/fragments","value":[{"kind":"identifier","text":"activeFrom"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/title","value":"MPLocation"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/fragments","value":[{"kind":"identifier","text":"MPLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1icon\/title","value":"icon"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1icon\/fragments","value":[{"kind":"identifier","text":"icon"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1sourceId\/title","value":"sourceId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1sourceId\/fragments","value":[{"kind":"identifier","text":"sourceId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1roomId\/title","value":"roomId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1roomId\/fragments","value":[{"kind":"identifier","text":"roomId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1marker\/title","value":"marker"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1marker\/fragments","value":[{"kind":"identifier","text":"marker"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1getCoordinateBounds()\/title","value":"getCoordinateBounds"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1getCoordinateBounds()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCoordinateBounds"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1aliases\/title","value":"aliases"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1aliases\/fragments","value":[{"kind":"identifier","text":"aliases"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1fields\/title","value":"fields"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1fields\/fragments","value":[{"kind":"identifier","text":"fields"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1image\/title","value":"image"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1image\/fragments","value":[{"kind":"identifier","text":"image"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1floor\/title","value":"floor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1floor\/fragments","value":[{"kind":"identifier","text":"floor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1activeTo\/title","value":"activeTo"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1activeTo\/fragments","value":[{"kind":"identifier","text":"activeTo"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1geometry\/title","value":"geometry"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1geometry\/fragments","value":[{"kind":"identifier","text":"geometry"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1categories\/title","value":"categories"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1categories\/fragments","value":[{"kind":"identifier","text":"categories"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1building\/title","value":"building"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1building\/fragments","value":[{"kind":"identifier","text":"building"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1getField(forKey:)\/title","value":"getFieldForKey:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1getField(forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getFieldForKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1init(location:)\/title","value":"initWithLocation:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1init(location:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLocation:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1getProperty(_:)\/title","value":"getProperty:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1getProperty(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getProperty:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1getPoint()\/title","value":"getPoint"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1getPoint()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1descr\/title","value":"descr"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1descr\/fragments","value":[{"kind":"identifier","text":"descr"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1init(point:andName:)\/title","value":"initWithPoint:andName:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1init(point:andName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPoint:andName:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1locationId\/title","value":"locationId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1locationId\/fragments","value":[{"kind":"identifier","text":"locationId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1properties\/title","value":"properties"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1properties\/fragments","value":[{"kind":"identifier","text":"properties"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1floorName\/title","value":"floorName"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1floorName\/fragments","value":[{"kind":"identifier","text":"floorName"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1venue\/title","value":"venue"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1venue\/fragments","value":[{"kind":"identifier","text":"venue"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionIndicator\/title","value":"MPPositionIndicator"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionIndicator\/fragments","value":[{"kind":"identifier","text":"MPPositionIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1imageURL\/title","value":"imageURL"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1imageURL\/fragments","value":[{"kind":"identifier","text":"imageURL"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1baseType\/title","value":"baseType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1baseType\/fragments","value":[{"kind":"identifier","text":"baseType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1isIndoors\/title","value":"isIndoors"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1isIndoors\/fragments","value":[{"kind":"identifier","text":"isIndoors"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1name\/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1getLiveValue(forKey:domainType:)\/title","value":"getLiveValueForKey:domainType:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1getLiveValue(forKey:domainType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLiveValueForKey:domainType:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}