{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationCoordinate3DMake"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"lat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"lng"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"floorId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D","preciseIdentifier":"c:@S@MPLocationCoordinate3D","text":"MPLocationCoordinate3D"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationcoordinate3dmake(_:_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationcoordinate3dmake(_:_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3DMake(_:_:_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationCoordinate3DMake"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLocationCoordinate3D","preciseIdentifier":"c:@S@MPLocationCoordinate3D"}],"title":"MPLocationCoordinate3DMake(_:_:_:)","roleHeading":"Function","role":"symbol","symbolKind":"func","externalID":"c:MPLocationCoordinate3D.h@F@MPLocationCoordinate3DMake","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLocationCoordinate3DMake"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationCoordinate3D":{"role":"symbol","title":"MPLocationCoordinate3D","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationCoordinate3D"}],"abstract":[{"type":"text","text":"A structure that contains a coordinate in 3D space: latitude\/longitude and floor."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationCoordinate3D"}],"url":"\/documentation\/mapsindoors\/mplocationcoordinate3d"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationCoordinate3DMake(_:_:_:)":{"role":"symbol","title":"MPLocationCoordinate3DMake(_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationCoordinate3DMake"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLocationCoordinate3D","preciseIdentifier":"c:@S@MPLocationCoordinate3D"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3DMake(_:_:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationCoordinate3DMake"}],"url":"\/documentation\/mapsindoors\/mplocationcoordinate3dmake(_:_:_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"op":"replace","path":"\/metadata\/title","value":"MPLocationCoordinate3DMake"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLocationCoordinate3DMake"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D","preciseIdentifier":"c:@S@MPLocationCoordinate3D","text":"MPLocationCoordinate3D"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationCoordinate3DMake"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"internalParam","text":"lat"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"internalParam","text":"lng"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"internalParam","text":"floorId"},{"kind":"text","text":")"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationCoordinate3D\/title","value":"MPLocationCoordinate3D"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationCoordinate3D\/fragments","value":[{"kind":"identifier","text":"MPLocationCoordinate3D"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationCoordinate3DMake(_:_:_:)\/title","value":"MPLocationCoordinate3DMake"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationCoordinate3DMake(_:_:_:)\/fragments","value":[{"kind":"identifier","text":"MPLocationCoordinate3DMake"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}