{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapsIndoorsDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapsindoorsdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmapsindoorsdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapsIndoorsDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"MapsIndoors delegate protocol"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapsIndoorsDelegate"}],"title":"MPMapsIndoorsDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)MPMapsIndoorsDelegate","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPMapsIndoorsDelegate"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapsIndoorsDelegate\/onError(_:)"]}],"references":{"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapsIndoorsDelegate/onError(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onError:"}],"role":"symbol","title":"onError(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when error occurs while initialising or synchronising."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapsIndoorsDelegate\/onError(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpmapsindoorsdelegate\/onerror(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapsIndoorsDelegate":{"role":"symbol","title":"MPMapsIndoorsDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapsIndoorsDelegate"}],"abstract":[{"type":"text","text":"MapsIndoors delegate protocol"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapsIndoorsDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMapsIndoorsDelegate"}],"url":"\/documentation\/mapsindoors\/mpmapsindoorsdelegate"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPMapsIndoorsDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPMapsIndoorsDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPMapsIndoorsDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapsIndoorsDelegate\/onError(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapsIndoorsDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapsIndoorsDelegate~1onError(_:)\/title","value":"onError:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapsIndoorsDelegate~1onError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onError:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapsIndoorsDelegate\/title","value":"MPMapsIndoorsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapsIndoorsDelegate\/fragments","value":[{"kind":"identifier","text":"MPMapsIndoorsDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}