{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMappedLocationUpdateHandler"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmappedlocationupdatehandler"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmappedlocationupdatehandler"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMappedLocationUpdateHandler","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMappedLocationUpdateHandler\/willUpdateLocationsOnMap(locations:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMappedLocationUpdateHandler"}],"title":"MPMappedLocationUpdateHandler","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)MPMappedLocationUpdateHandler","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPMappedLocationUpdateHandler"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPMappedLocationUpdateHandler":{"role":"symbol","title":"MPMappedLocationUpdateHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMappedLocationUpdateHandler"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMappedLocationUpdateHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMappedLocationUpdateHandler"}],"url":"\/documentation\/mapsindoors\/mpmappedlocationupdatehandler"},"doc://MapsIndoors/documentation/MapsIndoors/MPMappedLocationUpdateHandler/willUpdateLocationsOnMap(locations:)":{"navigatorTitle":[{"kind":"identifier","text":"willUpdateLocationsOnMap:"}],"role":"symbol","title":"willUpdateLocationsOnMap(locations:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willUpdateLocationsOnMap"},{"kind":"text","text":"("},{"kind":"externalParam","text":"locations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMappedLocationUpdateHandler\/willUpdateLocationsOnMap(locations:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpmappedlocationupdatehandler\/willupdatelocationsonmap(locations:)"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPMappedLocationUpdateHandler"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPMappedLocationUpdateHandler"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPMappedLocationUpdateHandler"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMappedLocationUpdateHandler\/willUpdateLocationsOnMap(locations:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMappedLocationUpdateHandler"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMappedLocationUpdateHandler\/title","value":"MPMappedLocationUpdateHandler"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMappedLocationUpdateHandler\/fragments","value":[{"kind":"identifier","text":"MPMappedLocationUpdateHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMappedLocationUpdateHandler~1willUpdateLocationsOnMap(locations:)\/title","value":"willUpdateLocationsOnMap:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMappedLocationUpdateHandler~1willUpdateLocationsOnMap(locations:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willUpdateLocationsOnMap:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}