{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMessageProviderDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmessageproviderdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmessageproviderdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessageProviderDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Messages provider delegate."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMessageProviderDelegate"}],"title":"MPMessageProviderDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)MPMessageProviderDelegate","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPMessageProviderDelegate"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessageProviderDelegate\/onMessageDetailsReady(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessageProviderDelegate\/onMessagesReady(_:)"]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPMessageProviderDelegate/onMessagesReady(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessagesReady:"}],"role":"symbol","title":"onMessagesReady(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessagesReady"},{"kind":"text","text":"(["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessageProviderDelegate\/onMessagesReady(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpmessageproviderdelegate\/onmessagesready(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessageProviderDelegate/onMessageDetailsReady(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageDetailsReady:"}],"role":"symbol","title":"onMessageDetailsReady(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageDetailsReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPMessage","preciseIdentifier":"c:objc(cs)MPMessage"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessageProviderDelegate\/onMessageDetailsReady(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpmessageproviderdelegate\/onmessagedetailsready(_:)"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessageProviderDelegate":{"role":"symbol","title":"MPMessageProviderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMessageProviderDelegate"}],"abstract":[{"type":"text","text":"Messages provider delegate."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessageProviderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMessageProviderDelegate"}],"url":"\/documentation\/mapsindoors\/mpmessageproviderdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPMessageProviderDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPMessageProviderDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPMessageProviderDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessageProviderDelegate\/onMessageDetailsReady(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessageProviderDelegate\/onMessagesReady(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMessageProviderDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessageProviderDelegate~1onMessagesReady(_:)\/title","value":"onMessagesReady:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessageProviderDelegate~1onMessagesReady(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessagesReady:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessageProviderDelegate~1onMessageDetailsReady(_:)\/title","value":"onMessageDetailsReady:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessageProviderDelegate~1onMessageDetailsReady(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageDetailsReady:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessageProviderDelegate\/title","value":"MPMessageProviderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessageProviderDelegate\/fragments","value":[{"kind":"identifier","text":"MPMessageProviderDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}