{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMyLocationButton"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmylocationbutton"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmylocationbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)UIButton"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/objc(pl)CALayerDelegate","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH","doc:\/\/MapsIndoors\/s8SendableP","doc:\/\/MapsIndoors\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting","doc:\/\/MapsIndoors\/objc(pl)UIAccessibilityIdentification","doc:\/\/MapsIndoors\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/MapsIndoors\/objc(pl)UIAppearance","doc:\/\/MapsIndoors\/objc(pl)UIAppearanceContainer","doc:\/\/MapsIndoors\/objc(pl)UIContextMenuInteractionDelegate","doc:\/\/MapsIndoors\/objc(pl)UICoordinateSpace","doc:\/\/MapsIndoors\/objc(pl)UIDynamicItem","doc:\/\/MapsIndoors\/objc(pl)UIFocusEnvironment","doc:\/\/MapsIndoors\/objc(pl)UIFocusItem","doc:\/\/MapsIndoors\/objc(pl)UIFocusItemContainer","doc:\/\/MapsIndoors\/objc(pl)UILargeContentViewerItem","doc:\/\/MapsIndoors\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/MapsIndoors\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/MapsIndoors\/objc(pl)UIResponderStandardEditActions","doc:\/\/MapsIndoors\/objc(pl)UISpringLoadedInteractionSupporting","doc:\/\/MapsIndoors\/objc(pl)UITraitEnvironment","doc:\/\/MapsIndoors\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMyLocationButton","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMyLocationButton"}],"title":"MPMyLocationButton","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPMyLocationButton","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPMyLocationButton"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting":{"type":"unresolvable","title":"UIKit.UIAccessibilityContentSizeCategoryImageAdjusting","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting"},"doc://MapsIndoors/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIAccessibilityIdentification"},"doc://MapsIndoors/objc(pl)UISpringLoadedInteractionSupporting":{"type":"unresolvable","title":"UIKit.UISpringLoadedInteractionSupporting","identifier":"doc:\/\/MapsIndoors\/objc(pl)UISpringLoadedInteractionSupporting"},"doc://MapsIndoors/documentation/MapsIndoors/MPMyLocationButton":{"role":"symbol","title":"MPMyLocationButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMyLocationButton"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMyLocationButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMyLocationButton"}],"url":"\/documentation\/mapsindoors\/mpmylocationbutton"},"doc://MapsIndoors/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://MapsIndoors/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIResponderStandardEditActions"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIFocusItemContainer"},"doc://MapsIndoors/objc(cs)UIButton":{"type":"unresolvable","title":"UIButton","identifier":"doc:\/\/MapsIndoors\/objc(cs)UIButton"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIFocusItem"},"doc://MapsIndoors/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/MapsIndoors\/objc(pl)UILargeContentViewerItem"},"doc://MapsIndoors/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIAppearance"},"doc://MapsIndoors/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/MapsIndoors\/s8SendableP"},"doc://MapsIndoors/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/MapsIndoors\/objc(pl)UICoordinateSpace"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/MapsIndoors\/objc(pl)CALayerDelegate"},"doc://MapsIndoors/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://MapsIndoors/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIFocusEnvironment"},"doc://MapsIndoors/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIPasteConfigurationSupporting"},"doc://MapsIndoors/objc(pl)UIContextMenuInteractionDelegate":{"type":"unresolvable","title":"UIKit.UIContextMenuInteractionDelegate","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIContextMenuInteractionDelegate"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/MapsIndoors\/objc(pl)UITraitEnvironment"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIUserActivityRestoring"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIDynamicItem"},"doc://MapsIndoors/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/MapsIndoors\/objc(pl)UIAppearanceContainer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPMyLocationButton"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPMyLocationButton"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPMyLocationButton"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMyLocationButton"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMyLocationButton\/title","value":"MPMyLocationButton"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMyLocationButton\/fragments","value":[{"kind":"identifier","text":"MPMyLocationButton"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}