{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPNotificationsHelper"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpnotificationshelper"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpnotificationshelper"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper\/fetchMessages(forSolution:completionHandler:messageHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper\/locationManager(_:didEnter:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper\/monitorRegion(for:with:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper\/setupNotifications(forApp:with:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPNotificationsHelper"}],"title":"MPNotificationsHelper","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPNotificationsHelper","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPNotificationsHelper"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPNotificationsHelper/monitorRegion(for:with:)":{"role":"symbol","title":"monitorRegion(for:with:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"monitorRegion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPMessage","preciseIdentifier":"c:objc(cs)MPMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper\/monitorRegion(for:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"monitorRegionForMessage:withLocationManager:"}],"url":"\/documentation\/mapsindoors\/mpnotificationshelper\/monitorregion(for:with:)"},"doc://MapsIndoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(cs)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPNotificationsHelper/setupNotifications(forApp:with:)":{"role":"symbol","title":"setupNotifications(forApp:with:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupNotifications"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forApp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper\/setupNotifications(forApp:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupNotificationsForApp:withLocationManager:"}],"url":"\/documentation\/mapsindoors\/mpnotificationshelper\/setupnotifications(forapp:with:)"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPNotificationsHelper/fetchMessages(forSolution:completionHandler:messageHandler:)":{"role":"symbol","title":"fetchMessages(forSolution:completionHandler:messageHandler:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"UIBackgroundFetchResult","preciseIdentifier":"c:@E@UIBackgroundFetchResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"messageHandler"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"MPMessage","preciseIdentifier":"c:objc(cs)MPMessage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper\/fetchMessages(forSolution:completionHandler:messageHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchMessagesForSolution:completionHandler:messageHandler:"}],"url":"\/documentation\/mapsindoors\/mpnotificationshelper\/fetchmessages(forsolution:completionhandler:messagehandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPNotificationsHelper":{"role":"symbol","title":"MPNotificationsHelper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPNotificationsHelper"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPNotificationsHelper"}],"url":"\/documentation\/mapsindoors\/mpnotificationshelper"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/documentation/MapsIndoors/MPNotificationsHelper/locationManager(_:didEnter:)":{"role":"symbol","title":"locationManager(_:didEnter:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEnter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLRegion","preciseIdentifier":"c:objc(cs)CLRegion"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper\/locationManager(_:didEnter:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"locationManager:didEnterRegion:"}],"url":"\/documentation\/mapsindoors\/mpnotificationshelper\/locationmanager(_:didenter:)"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPNotificationsHelper"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPNotificationsHelper"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPNotificationsHelper"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper\/fetchMessages(forSolution:completionHandler:messageHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper\/locationManager(_:didEnter:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper\/monitorRegion(for:with:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPNotificationsHelper\/setupNotifications(forApp:with:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPNotificationsHelper"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPNotificationsHelper~1monitorRegion(for:with:)\/title","value":"monitorRegionForMessage:withLocationManager:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPNotificationsHelper~1monitorRegion(for:with:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"monitorRegionForMessage:withLocationManager:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPNotificationsHelper~1setupNotifications(forApp:with:)\/title","value":"setupNotificationsForApp:withLocationManager:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPNotificationsHelper~1setupNotifications(forApp:with:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setupNotificationsForApp:withLocationManager:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPNotificationsHelper~1fetchMessages(forSolution:completionHandler:messageHandler:)\/title","value":"fetchMessagesForSolution:completionHandler:messageHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPNotificationsHelper~1fetchMessages(forSolution:completionHandler:messageHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fetchMessagesForSolution:completionHandler:messageHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPNotificationsHelper\/title","value":"MPNotificationsHelper"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPNotificationsHelper\/fragments","value":[{"kind":"identifier","text":"MPNotificationsHelper"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPNotificationsHelper~1locationManager(_:didEnter:)\/title","value":"locationManager:didEnterRegion:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPNotificationsHelper~1locationManager(_:didEnter:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"locationManager:didEnterRegion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}