{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpOfflineDataHandlerBlockType"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error object."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpofflinedatahandlerblocktype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpofflinedatahandlerblocktype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpOfflineDataHandlerBlockType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Offline content availability callback handler block"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpOfflineDataHandlerBlockType"}],"title":"mpOfflineDataHandlerBlockType","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias","externalID":"c:MPMapsIndoors.h@T@mpOfflineDataHandlerBlockType","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"mpOfflineDataHandlerBlockType"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/mpOfflineDataHandlerBlockType":{"role":"symbol","title":"mpOfflineDataHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpOfflineDataHandlerBlockType"}],"abstract":[{"type":"text","text":"Offline content availability callback handler block"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpOfflineDataHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpOfflineDataHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpofflinedatahandlerblocktype"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"mpOfflineDataHandlerBlockType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mpOfflineDataHandlerBlockType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"mpOfflineDataHandlerBlockType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpOfflineDataHandlerBlockType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpOfflineDataHandlerBlockType\/title","value":"mpOfflineDataHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpOfflineDataHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpOfflineDataHandlerBlockType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}