{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPoint"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppoint-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppoint-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometry"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)NSCopying","doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding","doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Basic point geometry class."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPoint"}],"title":"MPPoint","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPPoint","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPPoint"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/init(lat:lon:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/init(lat:lon:zValue:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/distance(to:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/getCoordinate()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/lat()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/latLngString()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/lng()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/setZValue(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/z()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/zIndex()"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/parse(_:)"]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPGeometry":{"role":"symbol","title":"MPGeometry","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeometry"}],"abstract":[{"type":"text","text":"Basic geometry class holding one or more coordinate sets"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPGeometry"}],"url":"\/documentation\/mapsindoors\/mpgeometry"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPPoint-swift.class/latLngString()":{"role":"symbol","title":"latLngString()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"latLngString"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Get latitude\/logitude value as a string"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/latLngString()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"latLngString"}],"url":"\/documentation\/mapsindoors\/mppoint-swift.class\/latlngstring()"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPPoint-swift.class/init(lat:lon:)":{"role":"symbol","title":"init(lat:lon:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"lat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Regular geographic point geometry initialization."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/init(lat:lon:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLat:lon:"}],"url":"\/documentation\/mapsindoors\/mppoint-swift.class\/init(lat:lon:)"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/documentation/MapsIndoors/MPPoint-swift.class/z()":{"role":"symbol","title":"z()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"z"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Get the z \/ floorIndex component."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/z()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"z"}],"url":"\/documentation\/mapsindoors\/mppoint-swift.class\/z()"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPPoint-swift.class/init(lat:lon:zValue:)":{"role":"symbol","title":"init(lat:lon:zValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"lat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Indoor geographic point geometry initialization."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/init(lat:lon:zValue:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLat:lon:zValue:"}],"url":"\/documentation\/mapsindoors\/mppoint-swift.class\/init(lat:lon:zvalue:)"},"doc://MapsIndoors/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPPoint-swift.class/getCoordinate()":{"role":"symbol","title":"getCoordinate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCoordinate"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"abstract":[{"type":"text","text":"Get a CoreLocation coordinate struct representation of the MPPoint"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/getCoordinate()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getCoordinate"}],"url":"\/documentation\/mapsindoors\/mppoint-swift.class\/getcoordinate()"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/documentation/MapsIndoors/MPPoint-swift.class/lng()":{"role":"symbol","title":"lng()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lng"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Get the longitude component."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/lng()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lng"}],"url":"\/documentation\/mapsindoors\/mppoint-swift.class\/lng()"},"doc://MapsIndoors/objc(pl)AbstractJSONModelProtocol":{"type":"unresolvable","title":"JSONModel.AbstractJSONModelProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol"},"doc://MapsIndoors/documentation/MapsIndoors/MPPoint-swift.class/setZValue(_:)":{"role":"symbol","title":"setZValue(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setZValue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Set the z \/ floorIndex component."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/setZValue(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setZValue:"}],"url":"\/documentation\/mapsindoors\/mppoint-swift.class\/setzvalue(_:)"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCopying"},"doc://MapsIndoors/documentation/MapsIndoors/MPPoint-swift.class/lat()":{"role":"symbol","title":"lat()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lat"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Get the latitude component."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/lat()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lat"}],"url":"\/documentation\/mapsindoors\/mppoint-swift.class\/lat()"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPPoint-swift.class/distance(to:)":{"role":"symbol","title":"distance(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"distance"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Calculate the 2d geographic distance to another point."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/distance(to:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"distanceTo:"}],"url":"\/documentation\/mapsindoors\/mppoint-swift.class\/distance(to:)"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPPoint-swift.class/parse(_:)":{"role":"symbol","title":"parse(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parse"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Static MPPoint builder. Parses a comma separated string an returns an MPPoint instance."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/parse(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parse:"}],"url":"\/documentation\/mapsindoors\/mppoint-swift.class\/parse(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPPoint-swift.class/zIndex()":{"role":"symbol","title":"zIndex()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"zIndex"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Get the z \/ floorIndex component as a rounded index."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/zIndex()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"zIndex"}],"url":"\/documentation\/mapsindoors\/mppoint-swift.class\/zindex()"},"doc://MapsIndoors/documentation/MapsIndoors/MPPoint-swift.class":{"role":"symbol","title":"MPPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPoint"}],"abstract":[{"type":"text","text":"Basic point geometry class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPoint"}],"url":"\/documentation\/mapsindoors\/mppoint-swift.class"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPPoint"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPPoint"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPPoint"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/distance(to:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/getCoordinate()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/init(lat:lon:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/init(lat:lon:zValue:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/lat()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/latLngString()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/lng()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/setZValue(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/z()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/zIndex()"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/parse(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPoint"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometry","preciseIdentifier":"c:objc(cs)MPGeometry","text":"MPGeometry"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometry\/title","value":"MPGeometry"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometry\/fragments","value":[{"kind":"identifier","text":"MPGeometry"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1latLngString()\/title","value":"latLngString"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1latLngString()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"latLngString"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1init(lat:lon:)\/title","value":"initWithLat:lon:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1init(lat:lon:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLat:lon:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1z()\/title","value":"z"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1z()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"z"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1init(lat:lon:zValue:)\/title","value":"initWithLat:lon:zValue:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1init(lat:lon:zValue:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLat:lon:zValue:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1getCoordinate()\/title","value":"getCoordinate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1getCoordinate()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCoordinate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1lng()\/title","value":"lng"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1lng()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lng"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1setZValue(_:)\/title","value":"setZValue:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1setZValue(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setZValue:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1lat()\/title","value":"lat"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1lat()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lat"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1distance(to:)\/title","value":"distanceTo:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1distance(to:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"distanceTo:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1parse(_:)\/title","value":"parse:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1parse(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"parse:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1zIndex()\/title","value":"zIndex"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1zIndex()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"zIndex"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class\/title","value":"MPPoint"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class\/fragments","value":[{"kind":"identifier","text":"MPPoint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}