{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProviderType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppositionprovidertype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppositionprovidertype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH","doc:\/\/MapsIndoors\/SY","doc:\/\/MapsIndoors\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/COMBINED_POSITION_PROVIDER","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/GPS_POSITION_PROVIDER","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/MOBILE_NETWORK_POSITION_PROVIDER","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/SENSOR_BASED_POSITION_PROVIDER","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/WIFI_POSITION_PROVIDER"]},{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/Equatable-Implementations","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProviderType"}],"title":"MPPositionProviderType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@MPPositionProviderType","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPPositionProviderType"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProviderType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mppositionprovidertype\/rawrepresentable-implementations"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProviderType/SENSOR_BASED_POSITION_PROVIDER":{"role":"symbol","title":"MPPositionProviderType.SENSOR_BASED_POSITION_PROVIDER","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SENSOR_BASED_POSITION_PROVIDER"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/SENSOR_BASED_POSITION_PROVIDER","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SENSOR_BASED_POSITION_PROVIDER"}],"url":"\/documentation\/mapsindoors\/mppositionprovidertype\/sensor_based_position_provider"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProviderType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mppositionprovidertype\/equatable-implementations"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProviderType/WIFI_POSITION_PROVIDER":{"role":"symbol","title":"MPPositionProviderType.WIFI_POSITION_PROVIDER","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"WIFI_POSITION_PROVIDER"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/WIFI_POSITION_PROVIDER","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WIFI_POSITION_PROVIDER"}],"url":"\/documentation\/mapsindoors\/mppositionprovidertype\/wifi_position_provider"},"doc://MapsIndoors/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/MapsIndoors\/s8SendableP"},"doc://MapsIndoors/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/MapsIndoors\/SY"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProviderType":{"role":"symbol","title":"MPPositionProviderType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProviderType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPositionProviderType"}],"url":"\/documentation\/mapsindoors\/mppositionprovidertype"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProviderType/GPS_POSITION_PROVIDER":{"role":"symbol","title":"MPPositionProviderType.GPS_POSITION_PROVIDER","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPS_POSITION_PROVIDER"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/GPS_POSITION_PROVIDER","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPS_POSITION_PROVIDER"}],"url":"\/documentation\/mapsindoors\/mppositionprovidertype\/gps_position_provider"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProviderType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mppositionprovidertype\/init(rawvalue:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProviderType/MOBILE_NETWORK_POSITION_PROVIDER":{"role":"symbol","title":"MPPositionProviderType.MOBILE_NETWORK_POSITION_PROVIDER","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MOBILE_NETWORK_POSITION_PROVIDER"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/MOBILE_NETWORK_POSITION_PROVIDER","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MOBILE_NETWORK_POSITION_PROVIDER"}],"url":"\/documentation\/mapsindoors\/mppositionprovidertype\/mobile_network_position_provider"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProviderType/COMBINED_POSITION_PROVIDER":{"role":"symbol","title":"MPPositionProviderType.COMBINED_POSITION_PROVIDER","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"COMBINED_POSITION_PROVIDER"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/COMBINED_POSITION_PROVIDER","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"COMBINED_POSITION_PROVIDER"}],"url":"\/documentation\/mapsindoors\/mppositionprovidertype\/combined_position_provider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"MPPositionProviderType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPPositionProviderType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPPositionProviderType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/COMBINED_POSITION_PROVIDER","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/GPS_POSITION_PROVIDER","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/MOBILE_NETWORK_POSITION_PROVIDER","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/SENSOR_BASED_POSITION_PROVIDER","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/WIFI_POSITION_PROVIDER"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProviderType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderType~1SENSOR_BASED_POSITION_PROVIDER\/title","value":"SENSOR_BASED_POSITION_PROVIDER"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderType~1SENSOR_BASED_POSITION_PROVIDER\/fragments","value":[{"kind":"identifier","text":"SENSOR_BASED_POSITION_PROVIDER"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderType~1WIFI_POSITION_PROVIDER\/title","value":"WIFI_POSITION_PROVIDER"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderType~1WIFI_POSITION_PROVIDER\/fragments","value":[{"kind":"identifier","text":"WIFI_POSITION_PROVIDER"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderType\/title","value":"MPPositionProviderType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderType\/fragments","value":[{"kind":"identifier","text":"MPPositionProviderType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderType~1GPS_POSITION_PROVIDER\/title","value":"GPS_POSITION_PROVIDER"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderType~1GPS_POSITION_PROVIDER\/fragments","value":[{"kind":"identifier","text":"GPS_POSITION_PROVIDER"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderType~1MOBILE_NETWORK_POSITION_PROVIDER\/title","value":"MOBILE_NETWORK_POSITION_PROVIDER"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderType~1MOBILE_NETWORK_POSITION_PROVIDER\/fragments","value":[{"kind":"identifier","text":"MOBILE_NETWORK_POSITION_PROVIDER"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderType~1COMBINED_POSITION_PROVIDER\/title","value":"COMBINED_POSITION_PROVIDER"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderType~1COMBINED_POSITION_PROVIDER\/fragments","value":[{"kind":"identifier","text":"COMBINED_POSITION_PROVIDER"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}