{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteCoordinate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mproutecoordinate-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mproutecoordinate-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)JSONModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)NSCopying","doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding","doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Route coordinate model"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteCoordinate"}],"title":"MPRouteCoordinate","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPRouteCoordinate","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPRouteCoordinate"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class\/floor_name","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class\/label","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class\/lat","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class\/lng","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class\/zLevel"]}],"references":{"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteCoordinate-swift.class/lat":{"role":"symbol","title":"lat","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Latitude angle"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class\/lat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lat"}],"url":"\/documentation\/mapsindoors\/mproutecoordinate-swift.class\/lat"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteCoordinate-swift.class/zLevel":{"role":"symbol","title":"zLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zLevel"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Floor level index"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class\/zLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"zLevel"}],"url":"\/documentation\/mapsindoors\/mproutecoordinate-swift.class\/zlevel"},"doc://MapsIndoors/objc(pl)AbstractJSONModelProtocol":{"type":"unresolvable","title":"JSONModel.AbstractJSONModelProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol"},"doc://MapsIndoors/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCopying"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteCoordinate-swift.class":{"role":"symbol","title":"MPRouteCoordinate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteCoordinate"}],"abstract":[{"type":"text","text":"Route coordinate model"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteCoordinate"}],"url":"\/documentation\/mapsindoors\/mproutecoordinate-swift.class"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteCoordinate-swift.class/label":{"role":"symbol","title":"label","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Label for displaying contextual information about this coordinate"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class\/label","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"label"}],"url":"\/documentation\/mapsindoors\/mproutecoordinate-swift.class\/label"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteCoordinate-swift.class/floor_name":{"role":"symbol","title":"floor_name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floor_name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Floor name for this coordinate"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class\/floor_name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floor_name"}],"url":"\/documentation\/mapsindoors\/mproutecoordinate-swift.class\/floor_name"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteCoordinate-swift.class/lng":{"role":"symbol","title":"lng","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lng"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Longitude angle"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class\/lng","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lng"}],"url":"\/documentation\/mapsindoors\/mproutecoordinate-swift.class\/lng"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding"},"doc://MapsIndoors/objc(cs)JSONModel":{"type":"unresolvable","title":"JSONModel","identifier":"doc:\/\/MapsIndoors\/objc(cs)JSONModel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPRouteCoordinate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPRouteCoordinate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPRouteCoordinate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class\/floor_name","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class\/label","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class\/lat","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class\/lng","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class\/zLevel"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteCoordinate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSONModel","preciseIdentifier":"c:objc(cs)JSONModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteCoordinate-swift.class~1lat\/title","value":"lat"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteCoordinate-swift.class~1lat\/fragments","value":[{"kind":"identifier","text":"lat"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteCoordinate-swift.class~1zLevel\/title","value":"zLevel"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteCoordinate-swift.class~1zLevel\/fragments","value":[{"kind":"identifier","text":"zLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteCoordinate-swift.class\/title","value":"MPRouteCoordinate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteCoordinate-swift.class\/fragments","value":[{"kind":"identifier","text":"MPRouteCoordinate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteCoordinate-swift.class~1label\/title","value":"label"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteCoordinate-swift.class~1label\/fragments","value":[{"kind":"identifier","text":"label"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteCoordinate-swift.class~1floor_name\/title","value":"floor_name"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteCoordinate-swift.class~1floor_name\/fragments","value":[{"kind":"identifier","text":"floor_name"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteCoordinate-swift.class~1lng\/title","value":"lng"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteCoordinate-swift.class~1lng\/fragments","value":[{"kind":"identifier","text":"lng"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}