{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteLeg"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mprouteleg-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mprouteleg-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)JSONModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)NSCopying","doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding","doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Route leg model. A route model will consist of one ore more route legs. Typically a route from 1st floor to 2nd floor will consist of two route legs. Thus, a route leg defines a continueus route part within the same floor and\/or building and\/or vehicle."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteLeg"}],"title":"MPRouteLeg","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPRouteLeg","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPRouteLeg"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/distance","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/duration","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/end_address","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/end_location","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/routeLegType","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/start_address","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/start_location","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/steps"]}],"references":{"doc://MapsIndoors/objc(cs)JSONModel":{"type":"unresolvable","title":"JSONModel","identifier":"doc:\/\/MapsIndoors\/objc(cs)JSONModel"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLeg-swift.class/distance":{"role":"symbol","title":"distance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distance"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The route leg distance in meters"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/distance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"distance"}],"url":"\/documentation\/mapsindoors\/mprouteleg-swift.class\/distance"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLeg-swift.class/end_location":{"role":"symbol","title":"end_location","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"end_location"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MPRouteCoordinate","preciseIdentifier":"c:objc(cs)MPRouteCoordinate"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The route leg end position"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/end_location","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"end_location"}],"url":"\/documentation\/mapsindoors\/mprouteleg-swift.class\/end_location"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCopying"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLeg-swift.class":{"role":"symbol","title":"MPRouteLeg","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteLeg"}],"abstract":[{"type":"text","text":"Route leg model. A route model will consist of one ore more route legs. Typically a route from 1st floor to 2nd floor will consist of two route legs. Thus, a route leg defines a continueus route part within the same floor and\/or building and\/or vehicle."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteLeg"}],"url":"\/documentation\/mapsindoors\/mprouteleg-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLeg-swift.class/routeLegType":{"role":"symbol","title":"routeLegType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routeLegType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPRouteLegType","preciseIdentifier":"c:@E@MPRouteLegType"}],"abstract":[{"type":"text","text":"The type of leg, determined by the source service, Google or MapsIndoors."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/routeLegType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"routeLegType"}],"url":"\/documentation\/mapsindoors\/mprouteleg-swift.class\/routelegtype"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/objc(pl)AbstractJSONModelProtocol":{"type":"unresolvable","title":"JSONModel.AbstractJSONModelProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLeg-swift.class/steps":{"role":"symbol","title":"steps","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"steps"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"MPRouteStepProtocol","preciseIdentifier":"c:objc(pl)MPRouteStep"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Collection of steps for the route leg."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/steps","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"steps"}],"url":"\/documentation\/mapsindoors\/mprouteleg-swift.class\/steps"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLeg-swift.class/end_address":{"role":"symbol","title":"end_address","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"end_address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The route leg end address. If the position is outdoors, the address may be a postal address. If the position is indoors, the address may be a textual description of the indoor location, like “Lower Ground Floor, Building X”."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/end_address","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"end_address"}],"url":"\/documentation\/mapsindoors\/mprouteleg-swift.class\/end_address"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLeg-swift.class/duration":{"role":"symbol","title":"duration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The route leg duration in seconds"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/duration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"duration"}],"url":"\/documentation\/mapsindoors\/mprouteleg-swift.class\/duration"},"doc://MapsIndoors/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLeg-swift.class/start_address":{"role":"symbol","title":"start_address","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"start_address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The route leg start address. If the position is outdoors, the address may be a postal address. If the position is indoors, the address may be a textual description of the indoor location, like “Lower Ground Floor, Building X”."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/start_address","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"start_address"}],"url":"\/documentation\/mapsindoors\/mprouteleg-swift.class\/start_address"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLeg-swift.class/start_location":{"role":"symbol","title":"start_location","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"start_location"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MPRouteCoordinate","preciseIdentifier":"c:objc(cs)MPRouteCoordinate"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The route leg start position"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/start_location","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"start_location"}],"url":"\/documentation\/mapsindoors\/mprouteleg-swift.class\/start_location"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPRouteLeg"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPRouteLeg"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPRouteLeg"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/distance","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/duration","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/end_address","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/end_location","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/routeLegType","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/start_address","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/start_location","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/steps"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteLeg"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSONModel","preciseIdentifier":"c:objc(cs)JSONModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1distance\/title","value":"distance"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1distance\/fragments","value":[{"kind":"identifier","text":"distance"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1end_location\/title","value":"end_location"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1end_location\/fragments","value":[{"kind":"identifier","text":"end_location"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class\/title","value":"MPRouteLeg"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class\/fragments","value":[{"kind":"identifier","text":"MPRouteLeg"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1routeLegType\/title","value":"routeLegType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1routeLegType\/fragments","value":[{"kind":"identifier","text":"routeLegType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1steps\/title","value":"steps"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1steps\/fragments","value":[{"kind":"identifier","text":"steps"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1end_address\/title","value":"end_address"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1end_address\/fragments","value":[{"kind":"identifier","text":"end_address"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1duration\/title","value":"duration"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1duration\/fragments","value":[{"kind":"identifier","text":"duration"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1start_address\/title","value":"start_address"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1start_address\/fragments","value":[{"kind":"identifier","text":"start_address"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1start_location\/title","value":"start_location"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1start_location\/fragments","value":[{"kind":"identifier","text":"start_location"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}