{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSolutionProvider"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpsolutionprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpsolutionprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Solution provider interface, that defines a delegate and a method for solution queries."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSolutionProvider"}],"title":"MPSolutionProvider","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPSolutionProvider","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPSolutionProvider"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/getSolution()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/getSolutionWithCompletion(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/getUserRoles(completion:)"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/isOfflineDataAvailable(forSolutionId:)"]}],"references":{"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPSolutionProvider/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPSolutionProviderDelegate","preciseIdentifier":"c:objc(pl)MPSolutionProviderDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Solution provider delegate."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/mapsindoors\/mpsolutionprovider\/delegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPSolutionProvider/getSolutionWithCompletion(_:)":{"role":"symbol","title":"getSolutionWithCompletion(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSolutionWithCompletion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpSolutionHandlerBlockType","preciseIdentifier":"c:MPSolutionProvider.h@T@mpSolutionHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get solution from this provider and supply a callback handler function."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/getSolutionWithCompletion(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getSolutionWithCompletion:"}],"url":"\/documentation\/mapsindoors\/mpsolutionprovider\/getsolutionwithcompletion(_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/documentation/MapsIndoors/MPSolutionProvider/getSolution()":{"role":"symbol","title":"getSolution()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSolution"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Get solution from this provider."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/getSolution()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getSolution"}],"url":"\/documentation\/mapsindoors\/mpsolutionprovider\/getsolution()"},"doc://MapsIndoors/documentation/MapsIndoors/MPSolutionProvider":{"role":"symbol","title":"MPSolutionProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSolutionProvider"}],"abstract":[{"type":"text","text":"Solution provider interface, that defines a delegate and a method for solution queries."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPSolutionProvider"}],"url":"\/documentation\/mapsindoors\/mpsolutionprovider"},"doc://MapsIndoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(cs)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPSolutionProvider/getUserRoles(completion:)":{"role":"symbol","title":"getUserRoles(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserRoles"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpUserRoleCompletion","preciseIdentifier":"c:MPSolutionProvider.h@T@mpUserRoleCompletion"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get user roles associated with the solution"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/getUserRoles(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getUserRolesWithCompletion:"}],"url":"\/documentation\/mapsindoors\/mpsolutionprovider\/getuserroles(completion:)"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MPSolutionProvider/isOfflineDataAvailable(forSolutionId:)":{"role":"symbol","title":"isOfflineDataAvailable(forSolutionId:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOfflineDataAvailable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSolutionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determine if cached or preloaded data is available for the given solutionId."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/isOfflineDataAvailable(forSolutionId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isOfflineDataAvailableForSolutionId:"}],"url":"\/documentation\/mapsindoors\/mpsolutionprovider\/isofflinedataavailable(forsolutionid:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPSolutionProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPSolutionProvider"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPSolutionProvider"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/getSolution()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/getSolutionWithCompletion(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/getUserRoles(completion:)"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProvider\/isOfflineDataAvailable(forSolutionId:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSolutionProvider"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider~1getSolutionWithCompletion(_:)\/title","value":"getSolutionWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider~1getSolutionWithCompletion(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getSolutionWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider~1getSolution()\/title","value":"getSolution"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider~1getSolution()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getSolution"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider\/title","value":"MPSolutionProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider\/fragments","value":[{"kind":"identifier","text":"MPSolutionProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider~1getUserRoles(completion:)\/title","value":"getUserRolesWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider~1getUserRoles(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUserRolesWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider~1isOfflineDataAvailable(forSolutionId:)\/title","value":"isOfflineDataAvailableForSolutionId:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProvider~1isOfflineDataAvailable(forSolutionId:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isOfflineDataAvailableForSolutionId:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}