{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSubscriptionTopic"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpsubscriptiontopic"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpsubscriptiontopic"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPWirelessPositionTopic"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionTopic","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionTopic\/init(topicString:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionTopic\/topicString"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSubscriptionTopic"}],"title":"MPSubscriptionTopic","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)MPSubscriptionTopic","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionTopic"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPSubscriptionTopic":{"role":"symbol","title":"MPSubscriptionTopic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSubscriptionTopic"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionTopic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionTopic"}],"url":"\/documentation\/mapsindoors\/mpsubscriptiontopic"},"doc://MapsIndoors/documentation/MapsIndoors/MPSubscriptionTopic/topicString":{"navigatorTitle":[{"kind":"identifier","text":"topicString"}],"role":"symbol","title":"topicString","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topicString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionTopic\/topicString","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpsubscriptiontopic\/topicstring"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPWirelessPositionTopic":{"role":"symbol","title":"MPWirelessPositionTopic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPWirelessPositionTopic"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPWirelessPositionTopic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPWirelessPositionTopic"}],"url":"\/documentation\/mapsindoors\/mpwirelesspositiontopic"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria":{"role":"symbol","title":"MPLiveTopicCriteria","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Live Topic Criteria model used for subscriptions to Live Updates using MPLiveDataManager."},{"type":"text","text":" "},{"type":"text","text":"A Live Topic Criteria is hierarchical in the way it is defined, and its relation to MapsIndoors data is derivable by its 7 components: Dataset, Venue, Building, Floor, Room, Location and Domain Type."},{"type":"text","text":" "},{"type":"text","text":"All properties can be left out but datasetId will then default to the currently active dataset."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveTopicCriteria"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria"},"doc://MapsIndoors/documentation/MapsIndoors/MPSubscriptionTopic/init(topicString:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithTopicString:"}],"role":"symbol","title":"init(topicString:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"topicString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionTopic\/init(topicString:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpsubscriptiontopic\/init(topicstring:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveUpdateTopic":{"role":"symbol","title":"MPLiveUpdateTopic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveUpdateTopic"}],"abstract":[{"type":"text","text":"Topic model for a Live Update. A Live Update Topic is hierarchical in the way it is defined, and its relation to MapsIndoors data is derivable by its 7 components: Dataset, Venue, Building, Floor, Room, Location and Domain Type"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveUpdateTopic"}],"url":"\/documentation\/mapsindoors\/mpliveupdatetopic"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPSubscriptionTopic"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPSubscriptionTopic"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPSubscriptionTopic"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionTopic\/topicString"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionTopic\/init(topicString:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSubscriptionTopic"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionTopic\/title","value":"MPSubscriptionTopic"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionTopic\/fragments","value":[{"kind":"identifier","text":"MPSubscriptionTopic"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionTopic~1topicString\/title","value":"topicString"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionTopic~1topicString\/fragments","value":[{"kind":"identifier","text":"topicString"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPWirelessPositionTopic\/title","value":"MPWirelessPositionTopic"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPWirelessPositionTopic\/fragments","value":[{"kind":"identifier","text":"MPWirelessPositionTopic"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria\/title","value":"MPLiveTopicCriteria"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria\/fragments","value":[{"kind":"identifier","text":"MPLiveTopicCriteria"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionTopic~1init(topicString:)\/title","value":"initWithTopicString:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionTopic~1init(topicString:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTopicString:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic\/title","value":"MPLiveUpdateTopic"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic\/fragments","value":[{"kind":"identifier","text":"MPLiveUpdateTopic"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}