{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPTravelMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mptravelmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mptravelmode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH","doc:\/\/MapsIndoors\/SY","doc:\/\/MapsIndoors\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/bicycling","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/driving","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/transit","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/unknown","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/walking"]},{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/Equatable-Implementations","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPTravelMode"}],"title":"MPTravelMode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@MPTravelMode","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPTravelMode"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPTravelMode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mptravelmode\/equatable-implementations"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPTravelMode/driving":{"role":"symbol","title":"MPTravelMode.driving","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"driving"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/driving","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPTravelModeDriving"}],"url":"\/documentation\/mapsindoors\/mptravelmode\/driving"},"doc://MapsIndoors/documentation/MapsIndoors/MPTravelMode/unknown":{"role":"symbol","title":"MPTravelMode.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPTravelModeUnknown"}],"url":"\/documentation\/mapsindoors\/mptravelmode\/unknown"},"doc://MapsIndoors/documentation/MapsIndoors/MPTravelMode/bicycling":{"role":"symbol","title":"MPTravelMode.bicycling","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bicycling"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/bicycling","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPTravelModeBicycling"}],"url":"\/documentation\/mapsindoors\/mptravelmode\/bicycling"},"doc://MapsIndoors/documentation/MapsIndoors/MPTravelMode/transit":{"role":"symbol","title":"MPTravelMode.transit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transit"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/transit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPTravelModeTransit"}],"url":"\/documentation\/mapsindoors\/mptravelmode\/transit"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPTravelMode/walking":{"role":"symbol","title":"MPTravelMode.walking","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"walking"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/walking","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPTravelModeWalking"}],"url":"\/documentation\/mapsindoors\/mptravelmode\/walking"},"doc://MapsIndoors/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/MapsIndoors\/SY"},"doc://MapsIndoors/documentation/MapsIndoors/MPTravelMode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mptravelmode\/rawrepresentable-implementations"},"doc://MapsIndoors/documentation/MapsIndoors/MPTravelMode":{"role":"symbol","title":"MPTravelMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPTravelMode"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPTravelMode"}],"url":"\/documentation\/mapsindoors\/mptravelmode"},"doc://MapsIndoors/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/MapsIndoors\/s8SendableP"},"doc://MapsIndoors/documentation/MapsIndoors/MPTravelMode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mptravelmode\/init(rawvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"MPTravelMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPTravelMode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPTravelMode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/bicycling","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/driving","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/transit","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/unknown","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/walking"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPTravelMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTravelMode~1driving\/title","value":"MPTravelModeDriving"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTravelMode~1driving\/fragments","value":[{"kind":"identifier","text":"MPTravelModeDriving"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTravelMode~1unknown\/title","value":"MPTravelModeUnknown"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTravelMode~1unknown\/fragments","value":[{"kind":"identifier","text":"MPTravelModeUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTravelMode~1bicycling\/title","value":"MPTravelModeBicycling"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTravelMode~1bicycling\/fragments","value":[{"kind":"identifier","text":"MPTravelModeBicycling"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTravelMode~1transit\/title","value":"MPTravelModeTransit"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTravelMode~1transit\/fragments","value":[{"kind":"identifier","text":"MPTravelModeTransit"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTravelMode~1walking\/title","value":"MPTravelModeWalking"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTravelMode~1walking\/fragments","value":[{"kind":"identifier","text":"MPTravelModeWalking"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTravelMode\/title","value":"MPTravelMode"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTravelMode\/fragments","value":[{"kind":"identifier","text":"MPTravelMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}