{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenue"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpvenue-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpvenue-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)JSONModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)NSCopying","doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding","doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenue"}],"title":"MPVenue","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPVenue","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPVenue"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/anchor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/bbox","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/bounds","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/buildings","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/defaultFloor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/entryPoints","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/externalId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/fields","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/graphId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/hasGraph","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/name","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/solutionId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/styles","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/tilesUrl","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/venueId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/venueKey"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/getBoundingBox()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/getBounds()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/getDefaultStyle()"]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/defaultFloor":{"role":"symbol","title":"defaultFloor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultFloor"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Venue default floor"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/defaultFloor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultFloor"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/defaultfloor"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/getDefaultStyle()":{"role":"symbol","title":"getDefaultStyle()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDefaultStyle"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MPMapStyle","preciseIdentifier":"c:objc(cs)MPMapStyle"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get a default style. If none is set, it will be the first string value in the list of map styles"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/getDefaultStyle()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDefaultStyle"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/getdefaultstyle()"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/getBoundingBox()":{"role":"symbol","title":"getBoundingBox()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBoundingBox"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the geographic bounding box for the venue"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/getBoundingBox()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getBoundingBox"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/getboundingbox()"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/tilesUrl":{"role":"symbol","title":"tilesUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tilesUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The general url template to be used when creating floor layers for this venue. If used by this framework, the url string must have format “prefix{param_1}infix{param_N}suffix”, e.g.: “http:\/\/tiles.url.com\/{floor}\/{x}\/{y}\/{zoom}.png”. See also MPURITemplate."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/tilesUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tilesUrl"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/tilesurl"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/styles":{"role":"symbol","title":"styles","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"styles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPMapStyle","preciseIdentifier":"c:objc(cs)MPMapStyle"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Array of possible map styles."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/styles","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"styles"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/styles"},"doc://MapsIndoors/objc(pl)AbstractJSONModelProtocol":{"type":"unresolvable","title":"JSONModel.AbstractJSONModelProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/getBounds()":{"deprecated":true,"role":"symbol","title":"getBounds()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBounds"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the geographic bounds for the venue"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/getBounds()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getVenueBounds"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/getbounds()"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/objc(cs)JSONModel":{"type":"unresolvable","title":"JSONModel","identifier":"doc:\/\/MapsIndoors\/objc(cs)JSONModel"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/graphId":{"role":"symbol","title":"graphId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"graphId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Route network\/graph identifier for the given venue."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/graphId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"graphId"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/graphid"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/hasGraph":{"role":"symbol","title":"hasGraph","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasGraph"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"YES\/NO property - determines of venue has _graphId"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/hasGraph","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasGraph"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/hasgraph"},"doc://MapsIndoors/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCopying"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Venue name."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/name"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/externalId":{"role":"symbol","title":"externalId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"externalId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"External id."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/externalId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"externalId"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/externalid"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/bbox":{"role":"symbol","title":"bbox","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bbox"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Geographic BBox array [w,s,e,n] for this venue."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/bbox","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bbox"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/bbox"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/bounds":{"role":"symbol","title":"bounds","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bounds"},{"kind":"text","text":": [["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]]?"}],"abstract":[{"type":"text","text":"Geographic bounds array [[lng,lat],[lng,lat],…] for this venue."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/bounds","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bounds"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/bounds"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/buildings":{"role":"symbol","title":"buildings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPBuilding","preciseIdentifier":"c:objc(cs)MPBuilding"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Container array for buildings in this venue. Note that this array are not populated initially. "},{"type":"codeVoice","code":"MPMapControl"},{"type":"text","text":" will populate this for the active venue."},{"type":"text","text":" "},{"type":"text","text":"To get the buildings for an arbitrary venue, please use "},{"type":"codeVoice","code":"MPVenueProvider.getBuildingsWithCompletion()"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/buildings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildings"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/buildings"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class":{"role":"symbol","title":"MPVenue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenue"}],"abstract":[{"type":"text","text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenue"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/venueId":{"role":"symbol","title":"venueId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"venueId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Venue id"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/venueId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"venueId"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/venueid"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/solutionId":{"role":"symbol","title":"solutionId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"solutionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Solution id"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/solutionId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"solutionId"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/solutionid"},"doc://MapsIndoors/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/fields":{"role":"symbol","title":"fields","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"MPLocationField","preciseIdentifier":"c:objc(cs)MPLocationField"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Dictionary of custom fields"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/fields","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fields"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/fields"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/entryPoints":{"role":"symbol","title":"entryPoints","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"entryPoints"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Array of entry points in this venue."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/entryPoints","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"entryPoints"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/entrypoints"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/anchor":{"role":"symbol","title":"anchor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchor"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Venue anchor point."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/anchor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"anchor"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/anchor"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/venueKey":{"role":"symbol","title":"venueKey","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"venueKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Venue key."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/venueKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"venueKey"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/venuekey"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPVenue"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPVenue"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPVenue"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/anchor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/bbox","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/bounds","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/buildings","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/defaultFloor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/entryPoints","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/externalId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/fields","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/graphId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/hasGraph","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/name","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/solutionId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/styles","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/tilesUrl","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/venueId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/venueKey"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/getBoundingBox()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/getBounds()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/getDefaultStyle()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenue"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSONModel","preciseIdentifier":"c:objc(cs)JSONModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1defaultFloor\/title","value":"defaultFloor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1defaultFloor\/fragments","value":[{"kind":"identifier","text":"defaultFloor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1getDefaultStyle()\/title","value":"getDefaultStyle"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1getDefaultStyle()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDefaultStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1getBoundingBox()\/title","value":"getBoundingBox"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1getBoundingBox()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBoundingBox"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1tilesUrl\/title","value":"tilesUrl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1tilesUrl\/fragments","value":[{"kind":"identifier","text":"tilesUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1styles\/title","value":"styles"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1styles\/fragments","value":[{"kind":"identifier","text":"styles"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1getBounds()\/title","value":"getVenueBounds"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1getBounds()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVenueBounds"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1graphId\/title","value":"graphId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1graphId\/fragments","value":[{"kind":"identifier","text":"graphId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1hasGraph\/title","value":"hasGraph"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1hasGraph\/fragments","value":[{"kind":"identifier","text":"hasGraph"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1name\/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1externalId\/title","value":"externalId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1externalId\/fragments","value":[{"kind":"identifier","text":"externalId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1bbox\/title","value":"bbox"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1bbox\/fragments","value":[{"kind":"identifier","text":"bbox"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1bounds\/title","value":"bounds"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1bounds\/fragments","value":[{"kind":"identifier","text":"bounds"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1buildings\/title","value":"buildings"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1buildings\/fragments","value":[{"kind":"identifier","text":"buildings"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class\/title","value":"MPVenue"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class\/fragments","value":[{"kind":"identifier","text":"MPVenue"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1venueId\/title","value":"venueId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1venueId\/fragments","value":[{"kind":"identifier","text":"venueId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1solutionId\/title","value":"solutionId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1solutionId\/fragments","value":[{"kind":"identifier","text":"solutionId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1fields\/title","value":"fields"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1fields\/fragments","value":[{"kind":"identifier","text":"fields"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1entryPoints\/title","value":"entryPoints"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1entryPoints\/fragments","value":[{"kind":"identifier","text":"entryPoints"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1anchor\/title","value":"anchor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1anchor\/fragments","value":[{"kind":"identifier","text":"anchor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1venueKey\/title","value":"venueKey"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1venueKey\/fragments","value":[{"kind":"identifier","text":"venueKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}