{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"RIGHT_DIRECTION"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteActionDirection","preciseIdentifier":"c:@E@MPRouteActionDirection","text":"MPRouteActionDirection"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/right_direction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/right_direction"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/RIGHT_DIRECTION","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"RIGHT_DIRECTION"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPRouteActionDirection","preciseIdentifier":"c:@E@MPRouteActionDirection"}],"title":"RIGHT_DIRECTION","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@E@MPRouteActionDirection@RIGHT_DIRECTION","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"RIGHT_DIRECTION"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPRouteActionDirection":{"role":"symbol","title":"MPRouteActionDirection","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteActionDirection"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteActionDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteActionDirection"}],"url":"\/documentation\/mapsindoors\/mprouteactiondirection"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/RIGHT_DIRECTION":{"role":"symbol","title":"RIGHT_DIRECTION","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"RIGHT_DIRECTION"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPRouteActionDirection","preciseIdentifier":"c:@E@MPRouteActionDirection"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/RIGHT_DIRECTION","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RIGHT_DIRECTION"}],"url":"\/documentation\/mapsindoors\/right_direction"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"RIGHT_DIRECTION"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RIGHT_DIRECTION"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"RIGHT_DIRECTION"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteActionDirection\/title","value":"MPRouteActionDirection"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteActionDirection\/fragments","value":[{"kind":"identifier","text":"MPRouteActionDirection"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1RIGHT_DIRECTION\/title","value":"RIGHT_DIRECTION"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1RIGHT_DIRECTION\/fragments","value":[{"kind":"identifier","text":"RIGHT_DIRECTION"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}