{"kind":"symbol","variants":[{"paths":["\/documentation\/mapsindoors\/mpdirectionsquery\/avoidwaytypes"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsquery\/avoidwaytypes"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"avoidWayTypes","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPHighway","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway"},{"text":"]?","kind":"text"}]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"Way types that should be avoided when calculating routes. Supports any ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighwayType","isActive":true},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/avoidWayTypes","interfaceLanguage":"swift"},"metadata":{"role":"symbol","externalID":"c:@M@MapsIndoors@objc(cs)MPDirectionsQuery(py)avoidWayTypes","roleHeading":"Instance Property","navigatorTitle":[{"text":"avoidWayTypes","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"avoidWayTypes"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","text":"MPHighway","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"symbolKind":"property","title":"avoidWayTypes"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway":{"title":"MPHighway","role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mphighway","abstract":[{"text":"Use instances of ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","isActive":true},{"type":"text","text":" to describe which type(s) of route elements to use."}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPHighway"}],"navigatorTitle":[{"kind":"identifier","text":"MPHighway"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"MPDirectionsQuery","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDirectionsQuery"}],"type":"topic","title":"MPDirectionsQuery","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery","url":"\/documentation\/mapsindoors\/mpdirectionsquery"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighwayType":{"abstract":[{"type":"text","text":"All accepted types of highways (or route elements)."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPHighwayType"}],"navigatorTitle":[{"kind":"identifier","text":"MPHighwayType"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mphighwaytype","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighwayType","kind":"symbol","type":"topic","title":"MPHighwayType"},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","type":"image","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery/avoidWayTypes":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Way types that should be avoided when calculating routes. Supports any "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighwayType","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/mapsindoors\/mpdirectionsquery\/avoidwaytypes","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/avoidWayTypes","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"avoidWayTypes"},{"text":": [","kind":"text"},{"text":"MPHighway","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"text":"avoidWayTypes","kind":"identifier"}],"title":"avoidWayTypes"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"avoidWayTypes","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"avoidWayTypes"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSArray<MPHighway *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"avoidWayTypes","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway\/title","op":"replace","value":"MPHighway"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway\/fragments","value":[{"kind":"identifier","text":"MPHighway"}],"op":"replace"},{"value":"MPDirectionsQuery","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/title"},{"value":[{"text":"MPDirectionsQuery","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/fragments"},{"op":"replace","value":"MPHighwayType","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighwayType\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighwayType\/fragments","value":[{"text":"MPHighwayType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1avoidWayTypes\/title","value":"avoidWayTypes"},{"value":[{"text":"avoidWayTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1avoidWayTypes\/fragments","op":"replace"}]}]}