{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/destinationPoint","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"destinationPoint"},{"kind":"text","text":": "},{"text":"MPPoint","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Destination point","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsquery\/destinationpoint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsquery\/destinationpoint"]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery"]]},"metadata":{"role":"symbol","externalID":"c:@M@MapsIndoors@objc(cs)MPDirectionsQuery(py)destinationPoint","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"destinationPoint","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint"},{"text":"?","kind":"text"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"destinationPoint"}],"title":"destinationPoint"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery/destinationPoint":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/destinationPoint","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"destinationPoint"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","text":"MPPoint"},{"text":"?","kind":"text"}],"kind":"symbol","title":"destinationPoint","abstract":[{"text":"Destination point","type":"text"}],"url":"\/documentation\/mapsindoors\/mpdirectionsquery\/destinationpoint","navigatorTitle":[{"text":"destinationPoint","kind":"identifier"}],"type":"topic"},"MapsPeopleWhite.png":{"alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"type":"image","identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery":{"type":"topic","title":"MPDirectionsQuery","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsQuery"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpdirectionsquery","abstract":[],"navigatorTitle":[{"text":"MPDirectionsQuery","kind":"identifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPoint":{"type":"topic","navigatorTitle":[{"text":"MPPoint","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mppoint","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPPoint","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"MPPoint"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"destinationPoint"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"destinationPoint"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","text":"MPPoint","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"destinationPoint"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1destinationPoint\/title","op":"replace","value":"destinationPoint"},{"op":"replace","value":[{"kind":"identifier","text":"destinationPoint"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1destinationPoint\/fragments"},{"value":"MPDirectionsQuery","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/fragments","value":[{"text":"MPDirectionsQuery","kind":"identifier"}]},{"op":"replace","value":"MPPoint","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPoint\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPoint\/fragments","value":[{"text":"MPPoint","kind":"identifier"}],"op":"replace"}]}]}