{"abstract":[{"text":"Way types that should be excluded (will never be used for a route) when calculating routes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Supports any "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If a way type also occurs in "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/avoidWayTypes"},{"text":" it will be excluded.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"excludeWayTypes","kind":"identifier"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","kind":"typeIdentifier","text":"MPHighway","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway"},{"kind":"text","text":"]?"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/excludeWayTypes"},"kind":"symbol","metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"excludeWayTypes","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPDirectionsQuery(py)excludeWayTypes","modules":[{"name":"MapsIndoors"}],"title":"excludeWayTypes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"excludeWayTypes","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","text":"MPHighway"},{"text":"]?","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsquery\/excludewaytypes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsquery\/excludewaytypes"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway":{"navigatorTitle":[{"text":"MPHighway","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","title":"MPHighway","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPHighway","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Use instances of "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","isActive":true},{"type":"text","text":" to describe which type(s) of route elements to use."}],"url":"\/documentation\/mapsindoors\/mphighway"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery","kind":"symbol","url":"\/documentation\/mapsindoors\/mpdirectionsquery","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsQuery"}],"navigatorTitle":[{"text":"MPDirectionsQuery","kind":"identifier"}],"type":"topic","title":"MPDirectionsQuery"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery/excludeWayTypes":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/excludeWayTypes","url":"\/documentation\/mapsindoors\/mpdirectionsquery\/excludewaytypes","abstract":[{"type":"text","text":"Way types that should be excluded (will never be used for a route) when calculating routes."},{"type":"text","text":" "},{"type":"text","text":"Supports any "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"If a way type also occurs in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/avoidWayTypes"},{"type":"text","text":" it will be excluded."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"excludeWayTypes","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MPHighway","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"excludeWayTypes"}],"type":"topic","title":"excludeWayTypes"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery/avoidWayTypes":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/avoidWayTypes","url":"\/documentation\/mapsindoors\/mpdirectionsquery\/avoidwaytypes","abstract":[{"text":"Way types that should be avoided (may be used if no other routes can be found)  when calculating routes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Supports any "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"If a way type also occurs in "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/excludeWayTypes","isActive":true},{"type":"text","text":" it will be excluded."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"avoidWayTypes"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MPHighway","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"avoidWayTypes","kind":"identifier"}],"type":"topic","title":"avoidWayTypes"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","alt":null,"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"excludeWayTypes"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"excludeWayTypes","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<MPHighway *>"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"excludeWayTypes"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway\/title","value":"MPHighway"},{"value":[{"text":"MPHighway","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway\/fragments"},{"value":"MPDirectionsQuery","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/title","op":"replace"},{"value":[{"text":"MPDirectionsQuery","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1excludeWayTypes\/title","op":"replace","value":"excludeWayTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1excludeWayTypes\/fragments","value":[{"text":"excludeWayTypes","kind":"identifier"}]},{"value":"avoidWayTypes","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1avoidWayTypes\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1avoidWayTypes\/fragments","value":[{"text":"avoidWayTypes","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}