{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery"]]},"metadata":{"role":"symbol","title":"origin","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"origin","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","kind":"typeIdentifier","text":"MPLocation"},{"text":"?","kind":"text"}],"symbolKind":"property","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"origin"}],"roleHeading":"Instance Property","externalID":"c:@M@MapsIndoors@objc(cs)MPDirectionsQuery(py)origin"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"origin","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation"},{"text":"?","kind":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Origin location.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsquery\/origin"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsquery\/origin"]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/origin","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery":{"kind":"symbol","navigatorTitle":[{"text":"MPDirectionsQuery","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdirectionsquery","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery","title":"MPDirectionsQuery","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDirectionsQuery","kind":"identifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery/origin":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"origin","kind":"identifier"},{"kind":"text","text":": "},{"text":"MPLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/origin","navigatorTitle":[{"kind":"identifier","text":"origin"}],"url":"\/documentation\/mapsindoors\/mpdirectionsquery\/origin","kind":"symbol","title":"origin","abstract":[{"text":"Origin location.","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation":{"navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLocation","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mplocation","title":"MPLocation","abstract":[{"type":"text","text":"This holds the data for a single location and a marker to display the data on a map."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"origin","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"origin"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"id<MPLocation>","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPLocation","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"origin","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","value":"MPDirectionsQuery","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/title"},{"value":[{"kind":"identifier","text":"MPDirectionsQuery"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/fragments"},{"value":"origin","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1origin\/title"},{"value":[{"kind":"identifier","text":"origin"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1origin\/fragments"},{"op":"replace","value":"MPLocation","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/fragments","value":[{"kind":"identifier","text":"MPLocation"}]}]}]}