{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"travelMode"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTravelMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPTravelMode","text":"MPTravelMode"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsquery\/travelmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsquery\/travelmode"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/travelMode"},"kind":"symbol","abstract":[{"text":"Set travel mode. Default is ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTravelMode\/walking","isActive":true,"type":"reference"},{"type":"text","text":"."}],"sections":[],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"travelMode"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPDirectionsQuery(py)travelMode","modules":[{"name":"MapsIndoors"}],"title":"travelMode","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"travelMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPTravelMode","preciseIdentifier":"c:@M@MapsIndoors@E@MPTravelMode"}]},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTravelMode/walking":{"navigatorTitle":[{"kind":"identifier","text":"MPTravelModeWalking"}],"role":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"walking"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTravelMode\/walking","title":"MPTravelMode.walking","url":"\/documentation\/mapsindoors\/mptravelmode\/walking","type":"topic","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery/travelMode":{"kind":"symbol","abstract":[{"text":"Set travel mode. Default is ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTravelMode\/walking","isActive":true,"type":"reference"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"travelMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPTravelMode","preciseIdentifier":"c:@M@MapsIndoors@E@MPTravelMode"}],"navigatorTitle":[{"text":"travelMode","kind":"identifier"}],"title":"travelMode","url":"\/documentation\/mapsindoors\/mpdirectionsquery\/travelmode","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/travelMode","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery":{"type":"topic","title":"MPDirectionsQuery","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsQuery"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpdirectionsquery","abstract":[],"navigatorTitle":[{"text":"MPDirectionsQuery","kind":"identifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTravelMode":{"navigatorTitle":[{"text":"MPTravelMode","kind":"identifier"}],"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPTravelMode"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTravelMode","title":"MPTravelMode","url":"\/documentation\/mapsindoors\/mptravelmode","type":"topic","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"travelMode","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"travelMode","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTravelMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPTravelMode","text":"MPTravelMode"},{"text":" ","kind":"text"},{"kind":"identifier","text":"travelMode"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"MPTravelModeWalking","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTravelMode~1walking\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTravelMode~1walking\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPTravelModeWalking"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1travelMode\/title","value":"travelMode"},{"value":[{"kind":"identifier","text":"travelMode"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1travelMode\/fragments"},{"value":"MPDirectionsQuery","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/fragments","value":[{"kind":"identifier","text":"MPDirectionsQuery"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTravelMode\/title","value":"MPTravelMode","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTravelMode\/fragments","value":[{"text":"MPTravelMode","kind":"identifier"}],"op":"replace"}]}]}