{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userRoles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPUserRole","preciseIdentifier":"c:objc(cs)MPUserRole","text":"MPUserRole"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdirectionsquery\/userroles"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdirectionsquery\/userroles"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/userRoles","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The user roles that the route should match."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userRoles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPUserRole","preciseIdentifier":"c:objc(cs)MPUserRole"},{"kind":"text","text":"]?"}],"title":"userRoles","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPDirectionsQuery(py)userRoles","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"userRoles"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsQuery"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsQuery/userRoles":{"role":"symbol","title":"userRoles","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userRoles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPUserRole","preciseIdentifier":"c:objc(cs)MPUserRole"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The user roles that the route should match."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/userRoles","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userRoles"}],"url":"\/documentation\/mapsindoors\/mpdirectionsquery\/userroles"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsQuery":{"role":"symbol","title":"MPDirectionsQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsQuery"}],"abstract":[{"type":"text","text":"Directions query model."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsQuery"}],"url":"\/documentation\/mapsindoors\/mpdirectionsquery"},"doc://MapsIndoors/documentation/MapsIndoors/MPUserRole":{"role":"symbol","title":"MPUserRole","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPUserRole"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPUserRole","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPUserRole"}],"url":"\/documentation\/mapsindoors\/mpuserrole"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"userRoles"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"userRoles"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<MPUserRole *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"userRoles"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1userRoles\/title","value":"userRoles"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1userRoles\/fragments","value":[{"kind":"identifier","text":"userRoles"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/title","value":"MPDirectionsQuery"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/fragments","value":[{"kind":"identifier","text":"MPDirectionsQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPUserRole\/title","value":"MPUserRole"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPUserRole\/fragments","value":[{"kind":"identifier","text":"MPUserRole"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}