{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"\/*not inherited*\/ "},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationquery\/init(url:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationquery\/init(url:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/init(url:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Parses an url, identifies query elements and returns a query object"}],"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"\/*not inherited*\/ "},{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"title":"init(url:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)MPLocationQuery(cm)queryWithUrl:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"queryWithUrl:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery":{"role":"symbol","title":"MPLocationQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationQuery"}],"abstract":[{"type":"text","text":"Locations query object used in conjunction with the MPLocationsProvider"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationQuery"}],"url":"\/documentation\/mapsindoors\/mplocationquery"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery/init(url:)":{"role":"symbol","title":"init(url:)","fragments":[{"kind":"text","text":"\/*not inherited*\/ "},{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Parses an url, identifies query elements and returns a query object"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/init(url:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"queryWithUrl:"}],"url":"\/documentation\/mapsindoors\/mplocationquery\/init(url:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"queryWithUrl:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"queryWithUrl:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery","preciseIdentifier":"c:objc(cs)MPLocationQuery","text":"MPLocationQuery"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"queryWithUrl:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"url"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery\/title","value":"MPLocationQuery"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery\/fragments","value":[{"kind":"identifier","text":"MPLocationQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1init(url:)\/title","value":"queryWithUrl:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1init(url:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"queryWithUrl:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}