{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPositionFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"provider"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"provider","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A provider that failed determining user position"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppositionproviderdelegate\/onpositionfailed(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppositionproviderdelegate\/onpositionfailed(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderDelegate\/onPositionFailed(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Positioning fail method. Will return the reference to the actual provider"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onPositionFailed:"}],"role":"symbol","title":"onPositionFailed(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPositionFailed"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MPPositionProviderDelegate(im)onPositionFailed:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderDelegate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProviderDelegate/onPositionFailed(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onPositionFailed:"}],"role":"symbol","title":"onPositionFailed(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPositionFailed"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Positioning fail method. Will return the reference to the actual provider"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderDelegate\/onPositionFailed(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mppositionproviderdelegate\/onpositionfailed(_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProviderDelegate":{"role":"symbol","title":"MPPositionProviderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProviderDelegate"}],"abstract":[{"type":"text","text":"Protocol specifying how an indoor positioning provider delegate should be implemented as the receiver of user positions."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPositionProviderDelegate"}],"url":"\/documentation\/mapsindoors\/mppositionproviderdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onPositionFailed:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPositionFailed:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onPositionFailed:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":")"},{"kind":"internalParam","text":"provider"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderDelegate~1onPositionFailed(_:)\/title","value":"onPositionFailed:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderDelegate~1onPositionFailed(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPositionFailed:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderDelegate\/title","value":"MPPositionProviderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderDelegate\/fragments","value":[{"kind":"identifier","text":"MPPositionProviderDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}