{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayRule"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule","text":"MPLocationDisplayRule"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mptype-swift.class\/displayrule"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mptype-swift.class\/displayrule"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/displayRule","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get the Display Rule assigned to this Location Type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayRule"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"title":"displayRule","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPType(py)displayRule","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"displayRule"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule":{"role":"symbol","title":"MPLocationDisplayRule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationDisplayRule"}],"abstract":[{"type":"text","text":"This class serves as a display rule for locations."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationDisplayRule"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPType-swift.class/displayRule":{"role":"symbol","title":"displayRule","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayRule"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Get the Display Rule assigned to this Location Type."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/displayRule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"displayRule"}],"url":"\/documentation\/mapsindoors\/mptype-swift.class\/displayrule"},"doc://MapsIndoors/documentation/MapsIndoors/MPType-swift.class":{"role":"symbol","title":"MPType","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPType"}],"abstract":[{"type":"text","text":"Location Type model."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPType"}],"url":"\/documentation\/mapsindoors\/mptype-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"displayRule"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"displayRule"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"MPLocationDisplayRule<Optional>","preciseIdentifier":"c:Q$objc(cs)MPLocationDisplayRuleobjc(pl)Optional"},{"kind":"text","text":" *"},{"kind":"identifier","text":"displayRule"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule\/title","value":"MPLocationDisplayRule"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule\/fragments","value":[{"kind":"identifier","text":"MPLocationDisplayRule"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPType-swift.class~1displayRule\/title","value":"displayRule"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPType-swift.class~1displayRule\/fragments","value":[{"kind":"identifier","text":"displayRule"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPType-swift.class\/title","value":"MPType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPType-swift.class\/fragments","value":[{"kind":"identifier","text":"MPType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}