{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"geometry","kind":"identifier"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRouteCoordinate","text":"MPRouteCoordinate","kind":"typeIdentifier"},{"text":"]? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/geometry","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"property","title":"geometry","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": ["},{"text":"MPRouteCoordinate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRouteCoordinate"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"geometry"}],"role":"symbol","modules":[{"name":"MapsIndoors"}],"required":true,"externalID":"c:@M@MapsIndoors@objc(pl)MPRouteStep(py)geometry"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mproutestep\/geometry"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mproutestep\/geometry"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep/geometry":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"geometry","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRouteCoordinate","text":"MPRouteCoordinate","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"type":"topic","required":true,"url":"\/documentation\/mapsindoors\/mproutestep\/geometry","navigatorTitle":[{"text":"geometry","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/geometry","title":"geometry","role":"symbol","kind":"symbol"},"MapsPeopleWhite.png":{"alt":null,"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute":{"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","title":"MPRoute","type":"topic","url":"\/documentation\/mapsindoors\/mproute","abstract":[{"type":"text","text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRoute"}],"navigatorTitle":[{"text":"MPRoute","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep":{"url":"\/documentation\/mapsindoors\/mproutestep","navigatorTitle":[{"text":"MPRouteStep","kind":"identifier"}],"type":"topic","abstract":[{"text":"Route step model. A step is segment on a ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg","type":"reference","isActive":true},{"type":"text","text":" ("},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg"},{"text":" is a segment on a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute"},{"type":"text","text":"). The step contains start and end locations, distance and duration information, as well as navigational instructions."}],"role":"symbol","title":"MPRouteStep","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPRouteStep","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLeg":{"url":"\/documentation\/mapsindoors\/mprouteleg","navigatorTitle":[{"kind":"identifier","text":"MPRouteLeg"}],"type":"topic","abstract":[{"text":"Route leg model. A route model will consist of one ore more route legs. Typically a route from 1st floor to 2nd floor will consist of two route legs. Thus, a route leg defines a continuous route part within the same floor and\/or building and\/or vehicle.","type":"text"}],"role":"symbol","title":"MPRouteLeg","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRouteLeg"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteCoordinate":{"type":"topic","title":"MPRouteCoordinate","navigatorTitle":[{"text":"MPRouteCoordinate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mproutecoordinate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPRouteCoordinate","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"geometry","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"geometry"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<MPRouteCoordinate>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"geometry","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1geometry\/title","value":"geometry"},{"value":[{"text":"geometry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1geometry\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/title","value":"MPRoute","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/fragments","value":[{"kind":"identifier","text":"MPRoute"}]},{"value":"MPRouteStep","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep\/title"},{"value":[{"text":"MPRouteStep","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg\/title","op":"replace","value":"MPRouteLeg"},{"value":[{"kind":"identifier","text":"MPRouteLeg"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg\/fragments"},{"value":"MPRouteCoordinate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteCoordinate\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteCoordinate\/fragments","value":[{"text":"MPRouteCoordinate","kind":"identifier"}],"op":"replace"}]}]}