{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"highway","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"highway","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPHighway","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPRouteStep(py)highway","navigatorTitle":[{"kind":"identifier","text":"highway"}],"roleHeading":"Instance Property","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mproutestep\/highway"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mproutestep\/highway"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"highway","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","text":"MPHighway"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/highway"},"abstract":[{"type":"text","text":"Way type for this step (part of the route). E.g. footway, steps, elevator, residential etc."}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep/highway":{"url":"\/documentation\/mapsindoors\/mproutestep\/highway","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/highway","title":"highway","abstract":[{"type":"text","text":"Way type for this step (part of the route). E.g. footway, steps, elevator, residential etc."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"highway"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","text":"MPHighway","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"highway"}],"kind":"symbol","required":true,"type":"topic"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoute"}],"url":"\/documentation\/mapsindoors\/mproute","navigatorTitle":[{"kind":"identifier","text":"MPRoute"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","title":"MPRoute","role":"symbol","abstract":[{"text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","isActive":true,"type":"reference"},{"text":".","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPHighway"}],"navigatorTitle":[{"text":"MPHighway","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Use instances of "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","type":"reference","isActive":true},{"type":"text","text":" to describe which type(s) of route elements to use."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","title":"MPHighway","url":"\/documentation\/mapsindoors\/mphighway"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep":{"navigatorTitle":[{"text":"MPRouteStep","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mproutestep","role":"symbol","type":"topic","title":"MPRouteStep","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep","kind":"symbol","abstract":[{"text":"Route step model. A step is segment on a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg","isActive":true},{"type":"text","text":" ("},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg","type":"reference","isActive":true},{"type":"text","text":" is a segment on a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute"},{"type":"text","text":"). The step contains start and end locations, distance and duration information, as well as navigational instructions."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPRouteStep","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLeg":{"navigatorTitle":[{"kind":"identifier","text":"MPRouteLeg"}],"url":"\/documentation\/mapsindoors\/mprouteleg","role":"symbol","type":"topic","title":"MPRouteLeg","abstract":[{"text":"Route leg model. A route model will consist of one ore more route legs. Typically a route from 1st floor to 2nd floor will consist of two route legs. Thus, a route leg defines a continuous route part within the same floor and\/or building and\/or vehicle.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPRouteLeg","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"highway","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"highway"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","text":"MPHighway"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"highway"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1highway\/title","value":"highway","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1highway\/fragments","value":[{"kind":"identifier","text":"highway"}],"op":"replace"},{"value":"MPRoute","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/title","op":"replace"},{"value":[{"text":"MPRoute","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/fragments","op":"replace"},{"value":"MPHighway","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway\/fragments","value":[{"kind":"identifier","text":"MPHighway"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep\/title","op":"replace","value":"MPRouteStep"},{"value":[{"kind":"identifier","text":"MPRouteStep"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg\/title","value":"MPRouteLeg"},{"value":[{"kind":"identifier","text":"MPRouteLeg"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg\/fragments","op":"replace"}]}]}