{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mproutestep\/transit_details"]},{"paths":["\/documentation\/mapsindoors\/mproutestep\/transit_details"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transit_details"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails","text":"MPTransitDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitDetails"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Transit details. May apply for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/travel_mode"},{"type":"text","text":" "},{"type":"codeVoice","code":"transit"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/transit_details"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transit_details"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitDetails","kind":"typeIdentifier","text":"MPTransitDetails"}],"navigatorTitle":[{"kind":"identifier","text":"transit_details"}],"role":"symbol","modules":[{"name":"MapsIndoors"}],"title":"transit_details","externalID":"c:@M@MapsIndoors@objc(pl)MPRouteStep(py)transit_details","roleHeading":"Instance Property","required":true},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitDetails":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPTransitDetails","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mptransitdetails","title":"MPTransitDetails","navigatorTitle":[{"kind":"identifier","text":"MPTransitDetails"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails","role":"symbol","kind":"symbol","abstract":[{"text":"Transit details information.","type":"text"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the "},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRoute"}],"url":"\/documentation\/mapsindoors\/mproute","title":"MPRoute","navigatorTitle":[{"kind":"identifier","text":"MPRoute"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep/travel_mode":{"navigatorTitle":[{"text":"travel_mode","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Travel mode key. Can be ","type":"text"},{"type":"codeVoice","code":"walking"},{"type":"text","text":", "},{"type":"codeVoice","code":"bicycling"},{"text":", ","type":"text"},{"type":"codeVoice","code":"driving"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"transit"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"travel_mode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/travel_mode","url":"\/documentation\/mapsindoors\/mproutestep\/travel_mode","title":"travel_mode","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLeg":{"title":"MPRouteLeg","navigatorTitle":[{"kind":"identifier","text":"MPRouteLeg"}],"abstract":[{"type":"text","text":"Route leg model. A route model will consist of one ore more route legs. Typically a route from 1st floor to 2nd floor will consist of two route legs. Thus, a route leg defines a continuous route part within the same floor and\/or building and\/or vehicle."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPRouteLeg","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mprouteleg","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Route step model. A step is segment on a "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg","type":"reference","isActive":true},{"type":"text","text":" ("},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg"},{"text":" is a segment on a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute"},{"type":"text","text":"). The step contains start and end locations, distance and duration information, as well as navigational instructions."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPRouteStep","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mproutestep","title":"MPRouteStep","navigatorTitle":[{"text":"MPRouteStep","kind":"identifier"}]},"MapsPeopleWhite.png":{"alt":null,"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep/transit_details":{"navigatorTitle":[{"text":"transit_details","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Transit details. May apply for "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/travel_mode","isActive":true},{"text":" ","type":"text"},{"type":"codeVoice","code":"transit"},{"text":".","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"transit_details"},{"text":": ","kind":"text"},{"text":"MPTransitDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitDetails"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/transit_details","url":"\/documentation\/mapsindoors\/mproutestep\/transit_details","title":"transit_details","required":true}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"transit_details","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"transit_details","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<MPTransitDetails>","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPTransitDetails"},{"kind":"text","text":" * "},{"text":"transit_details","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MPTransitDetails","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails\/fragments","value":[{"text":"MPTransitDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/title","value":"MPRoute","op":"replace"},{"value":[{"text":"MPRoute","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1travel_mode\/title","value":"travel_mode","op":"replace"},{"value":[{"text":"travel_mode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1travel_mode\/fragments"},{"value":"MPRouteLeg","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg\/fragments","value":[{"kind":"identifier","text":"MPRouteLeg"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep\/title","value":"MPRouteStep","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep\/fragments","op":"replace","value":[{"text":"MPRouteStep","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1transit_details\/title","value":"transit_details"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1transit_details\/fragments","op":"replace","value":[{"kind":"identifier","text":"transit_details"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}