{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"colorPrimaryDark","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"MapsIndoors"}],"required":true,"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"colorPrimaryDark"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"colorPrimaryDark","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPAppConfig(py)colorPrimaryDark","title":"colorPrimaryDark","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"The primary color to use for dark mode in the app."}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/colorPrimaryDark","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpappconfig\/colorprimarydark"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpappconfig\/colorprimarydark"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAppConfig/colorPrimaryDark":{"title":"colorPrimaryDark","url":"\/documentation\/mapsindoors\/mpappconfig\/colorprimarydark","abstract":[{"text":"The primary color to use for dark mode in the app.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"colorPrimaryDark","kind":"identifier"}],"required":true,"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/colorPrimaryDark","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"colorPrimaryDark","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAppConfig":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpappconfig","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig","abstract":[{"text":"Provides the contextual information needed for setting up a map with specific MapsPeople site data.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPAppConfig"}],"title":"MPAppConfig","navigatorTitle":[{"text":"MPAppConfig","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"colorPrimaryDark"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"colorPrimaryDark"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"colorPrimaryDark","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"colorPrimaryDark","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig~1colorPrimaryDark\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig~1colorPrimaryDark\/fragments","op":"replace","value":[{"kind":"identifier","text":"colorPrimaryDark"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig\/title","op":"replace","value":"MPAppConfig"},{"value":[{"kind":"identifier","text":"MPAppConfig"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}