{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPAppConfig(py)menuInfo","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"menuInfo","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : [","kind":"text"},{"kind":"typeIdentifier","text":"MPMenuInfo","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPMenuInfo"},{"text":"]]?","kind":"text"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"menuInfo"}],"required":true,"title":"menuInfo"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpappconfig\/menuinfo"]},{"paths":["\/documentation\/mapsindoors\/mpappconfig\/menuinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/menuInfo","interfaceLanguage":"swift"},"abstract":[{"text":"An ordered list of menu items for a specified menu.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"menuInfo","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : [","kind":"text"},{"text":"MPMenuInfo","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMenuInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPMenuInfo"},{"text":"]]? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMenuInfo":{"type":"topic","role":"symbol","url":"\/documentation\/mapsindoors\/mpmenuinfo","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPMenuInfo","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMenuInfo","abstract":[],"navigatorTitle":[{"text":"MPMenuInfo","kind":"identifier"}],"title":"MPMenuInfo"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAppConfig/menuInfo":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/menuInfo","title":"menuInfo","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An ordered list of menu items for a specified menu."}],"url":"\/documentation\/mapsindoors\/mpappconfig\/menuinfo","navigatorTitle":[{"kind":"identifier","text":"menuInfo"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"menuInfo","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPMenuInfo","text":"MPMenuInfo"},{"text":"]]?","kind":"text"}]},"MapsPeopleWhite.png":{"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAppConfig":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig","abstract":[{"text":"Provides the contextual information needed for setting up a map with specific MapsPeople site data.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpappconfig","kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPAppConfig"}],"role":"symbol","title":"MPAppConfig","navigatorTitle":[{"kind":"identifier","text":"MPAppConfig"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"menuInfo","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"menuInfo","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSArray<id<MPMenuInfo>> *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"menuInfo","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"MPMenuInfo","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMenuInfo\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMenuInfo\/fragments","value":[{"kind":"identifier","text":"MPMenuInfo"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig~1menuInfo\/title","value":"menuInfo","op":"replace"},{"value":[{"text":"menuInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig~1menuInfo\/fragments"},{"value":"MPAppConfig","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig\/title"},{"op":"replace","value":[{"text":"MPAppConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}