{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"routing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"directionsQuery"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsQuery","preciseIdentifier":"c:objc(cs)MPDirectionsQuery","text":"MPDirectionsQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":" "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpRouteHandlerBlockType","preciseIdentifier":"c:MPRoutingProvider.h@T@mpRouteHandlerBlockType","text":"mpRouteHandlerBlockType"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdirectionsservice\/routing(with:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdirectionsservice\/routing(with:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsService\/routing(with:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get directions."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"routing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDirectionsQuery","preciseIdentifier":"c:objc(cs)MPDirectionsQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpRouteHandlerBlockType","preciseIdentifier":"c:MPRoutingProvider.h@T@mpRouteHandlerBlockType"},{"kind":"text","text":"?)"}],"title":"routing(with:completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPDirectionsService(im)routingWithQuery:completionHandler:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"routingWithQuery:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsService"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsService/routing(with:completionHandler:)":{"role":"symbol","title":"routing(with:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"routing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDirectionsQuery","preciseIdentifier":"c:objc(cs)MPDirectionsQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpRouteHandlerBlockType","preciseIdentifier":"c:MPRoutingProvider.h@T@mpRouteHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get directions."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsService\/routing(with:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"routingWithQuery:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mpdirectionsservice\/routing(with:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsQuery":{"role":"symbol","title":"MPDirectionsQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsQuery"}],"abstract":[{"type":"text","text":"Directions query model."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsQuery"}],"url":"\/documentation\/mapsindoors\/mpdirectionsquery"},"doc://MapsIndoors/documentation/MapsIndoors/mpRouteHandlerBlockType":{"role":"symbol","title":"mpRouteHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpRouteHandlerBlockType"}],"abstract":[{"type":"text","text":"Callback handler for route result"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpRouteHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpRouteHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mproutehandlerblocktype"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsService":{"role":"symbol","title":"MPDirectionsService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsService"}],"abstract":[{"type":"text","text":"Directions service"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsService"}],"url":"\/documentation\/mapsindoors\/mpdirectionsservice"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"routingWithQuery:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"routingWithQuery:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"routingWithQuery:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsQuery","preciseIdentifier":"c:objc(cs)MPDirectionsQuery","text":"MPDirectionsQuery"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"directionsQuery"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(MPRoute *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)MPRoute#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"handler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsService~1routing(with:completionHandler:)\/title","value":"routingWithQuery:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsService~1routing(with:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"routingWithQuery:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/title","value":"MPDirectionsQuery"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/fragments","value":[{"kind":"identifier","text":"MPDirectionsQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpRouteHandlerBlockType\/title","value":"mpRouteHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpRouteHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpRouteHandlerBlockType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsService\/title","value":"MPDirectionsService"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsService\/fragments","value":[{"kind":"identifier","text":"MPDirectionsService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}