{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mproutecoordinate-swift.class\/label"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mproutecoordinate-swift.class\/label"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class\/label","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Label for displaying contextual information about this coordinate"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"label","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPRouteCoordinate(py)label","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"label"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteCoordinate-swift.class/label":{"role":"symbol","title":"label","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Label for displaying contextual information about this coordinate"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class\/label","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"label"}],"url":"\/documentation\/mapsindoors\/mproutecoordinate-swift.class\/label"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteCoordinate-swift.class":{"role":"symbol","title":"MPRouteCoordinate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteCoordinate"}],"abstract":[{"type":"text","text":"Route coordinate model"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteCoordinate"}],"url":"\/documentation\/mapsindoors\/mproutecoordinate-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"label"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"label"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString<Optional>","preciseIdentifier":"c:Q$objc(cs)NSStringobjc(pl)Optional"},{"kind":"text","text":" *"},{"kind":"identifier","text":"label"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteCoordinate-swift.class~1label\/title","value":"label"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteCoordinate-swift.class~1label\/fragments","value":[{"kind":"identifier","text":"label"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteCoordinate-swift.class\/title","value":"MPRouteCoordinate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteCoordinate-swift.class\/fragments","value":[{"kind":"identifier","text":"MPRouteCoordinate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}