{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class","preciseIdentifier":"c:objc(cs)MPPoint","text":"MPPoint"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppositionresult\/geometry"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppositionresult\/geometry"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/geometry","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The geographic point geometry of the position"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":"?"}],"title":"geometry","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPPositionResult(py)geometry","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"geometry"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult":{"role":"symbol","title":"MPPositionResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionResult"}],"abstract":[{"type":"text","text":"Position result model"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPositionResult"}],"url":"\/documentation\/mapsindoors\/mppositionresult"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult/geometry":{"role":"symbol","title":"geometry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The geographic point geometry of the position"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/geometry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"geometry"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/geometry"},"doc://MapsIndoors/documentation/MapsIndoors/MPPoint-swift.class":{"role":"symbol","title":"MPPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPoint"}],"abstract":[{"type":"text","text":"Basic point geometry class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPoint"}],"url":"\/documentation\/mapsindoors\/mppoint-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"geometry"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"geometry"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class","preciseIdentifier":"c:objc(cs)MPPoint","text":"MPPoint"},{"kind":"text","text":" *"},{"kind":"identifier","text":"geometry"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult\/title","value":"MPPositionResult"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult\/fragments","value":[{"kind":"identifier","text":"MPPositionResult"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1geometry\/title","value":"geometry"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1geometry\/fragments","value":[{"kind":"identifier","text":"geometry"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class\/title","value":"MPPoint"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class\/fragments","value":[{"kind":"identifier","text":"MPPoint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}