{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mppositionresult\/init(coordinate:floorindex:accuracy:bearing:)"]},{"paths":["\/documentation\/mapsindoors\/mppositionresult\/init(coordinate:floorindex:accuracy:bearing:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult\/init(coordinate:floorIndex:accuracy:bearing:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult"]]},"abstract":[{"text":"Initialise a MPPositoinResult with all properties.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"From Swift all values are optional which will set them to the default values."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithCoordinate:floorIndex:accuracy:bearing:"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPPositionResult(im)initWithCoordinate:floorIndex:accuracy:bearing:","role":"symbol","symbolKind":"init","title":"init(coordinate:floorIndex:accuracy:bearing:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"coordinate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"floorIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"accuracy","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"bearing","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"modules":[{"name":"MapsIndoors"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"required","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"coordinate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"floorIndex"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" = 0, ","kind":"text"},{"text":"accuracy","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":" = 0, ","kind":"text"},{"text":"bearing","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":" = 0)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"coordinate","content":[{"type":"paragraph","inlineContent":[{"text":"See ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult\/coordinate","isActive":true},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"See ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult\/floorIndex","isActive":true},{"type":"text","text":". Default is "},{"type":"codeVoice","code":"0"},{"text":".","type":"text"}]}],"name":"floorIndex"},{"content":[{"inlineContent":[{"text":"See ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult\/accuracy","type":"reference","isActive":true},{"type":"text","text":". Default is "},{"type":"codeVoice","code":"0"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"accuracy"},{"name":"bearing","content":[{"inlineContent":[{"type":"text","text":"See "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult\/bearing","isActive":true},{"type":"text","text":". Default is "},{"code":"0","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionResult/init(coordinate:floorIndex:accuracy:bearing:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithCoordinate:floorIndex:accuracy:bearing:"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/init(coordinate:floorindex:accuracy:bearing:)","kind":"symbol","abstract":[{"type":"text","text":"Initialise a MPPositoinResult with all properties."},{"type":"text","text":" "},{"type":"text","text":"From Swift all values are optional which will set them to the default values."}],"type":"topic","title":"init(coordinate:floorIndex:accuracy:bearing:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult\/init(coordinate:floorIndex:accuracy:bearing:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"coordinate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"},{"kind":"text","text":", "},{"text":"floorIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accuracy"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"bearing","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionResult/bearing":{"navigatorTitle":[{"text":"bearing","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/bearing","kind":"symbol","abstract":[{"type":"text","text":"The bearing in degrees from north"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult\/bearing","title":"bearing","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bearing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionResult/floorIndex":{"navigatorTitle":[{"kind":"identifier","text":"floorIndex"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/floorindex","kind":"symbol","abstract":[{"type":"text","text":"The index of the floor the "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult\/coordinate","type":"reference","isActive":true},{"type":"text","text":" is located on."}],"type":"topic","title":"floorIndex","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult\/floorIndex","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"floorIndex","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionResult":{"role":"symbol","abstract":[{"text":"Instances of this class holds a Position result returned by a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","isActive":true},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mppositionresult","navigatorTitle":[{"text":"MPPositionResult","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPPositionResult"}],"title":"MPPositionResult"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionProvider":{"url":"\/documentation\/mapsindoors\/mppositionprovider","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProvider"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPPositionProvider"}],"title":"MPPositionProvider","abstract":[{"type":"text","text":"Protocol specifying how an indoor positioning provider should be implemented if the users location is to be exposed to "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true},{"type":"text","text":"."}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionResult/coordinate":{"navigatorTitle":[{"kind":"identifier","text":"coordinate"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/coordinate","kind":"symbol","abstract":[{"text":"The geographic point of the position.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult\/coordinate","title":"coordinate","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"coordinate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionResult/accuracy":{"navigatorTitle":[{"kind":"identifier","text":"accuracy"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/accuracy","kind":"symbol","abstract":[{"type":"text","text":"The probability of the position in "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult\/coordinate","isActive":true},{"type":"text","text":". This is a radius in meters. Can be used to generate an approximation circle."}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult\/accuracy","title":"accuracy","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"accuracy","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","alt":null,"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithCoordinate:floorIndex:accuracy:bearing:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoordinate:floorIndex:accuracy:bearing:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCoordinate:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":") "},{"text":"coordinate","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"floorIndex:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"floorIndex","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accuracy:"},{"kind":"text","text":"("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"accuracy"},{"text":" ","kind":"text"},{"text":"bearing:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"text":") ","kind":"text"},{"text":"bearing","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult~1init(coordinate:floorIndex:accuracy:bearing:)\/title","op":"replace","value":"initWithCoordinate:floorIndex:accuracy:bearing:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult~1init(coordinate:floorIndex:accuracy:bearing:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoordinate:floorIndex:accuracy:bearing:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult~1bearing\/title","op":"replace","value":"bearing"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult~1bearing\/fragments","value":[{"kind":"identifier","text":"bearing"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult~1floorIndex\/title","value":"floorIndex","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult~1floorIndex\/fragments","value":[{"kind":"identifier","text":"floorIndex"}]},{"op":"replace","value":"MPPositionResult","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult\/fragments","op":"replace","value":[{"text":"MPPositionResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider\/title","value":"MPPositionProvider","op":"replace"},{"value":[{"kind":"identifier","text":"MPPositionProvider"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult~1coordinate\/title","value":"coordinate"},{"value":[{"text":"coordinate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult~1coordinate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult~1accuracy\/title","value":"accuracy"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult~1accuracy\/fragments","op":"replace","value":[{"text":"accuracy","kind":"identifier"}]}]}]}