{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topicString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpsubscriptiontopic\/topicstring"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpsubscriptiontopic\/topicstring"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionTopic\/topicString","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"topicString"}],"role":"symbol","title":"topicString","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topicString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"symbolKind":"property","externalID":"c:objc(pl)MPSubscriptionTopic(py)topicString","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionTopic"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPSubscriptionTopic":{"role":"symbol","title":"MPSubscriptionTopic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSubscriptionTopic"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionTopic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionTopic"}],"url":"\/documentation\/mapsindoors\/mpsubscriptiontopic"},"doc://MapsIndoors/documentation/MapsIndoors/MPSubscriptionTopic/topicString":{"navigatorTitle":[{"kind":"identifier","text":"topicString"}],"role":"symbol","title":"topicString","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topicString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionTopic\/topicString","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpsubscriptiontopic\/topicstring"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"topicString"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"topicString"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *"},{"kind":"identifier","text":"topicString"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionTopic\/title","value":"MPSubscriptionTopic"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionTopic\/fragments","value":[{"kind":"identifier","text":"MPSubscriptionTopic"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionTopic~1topicString\/title","value":"topicString"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionTopic~1topicString\/fragments","value":[{"kind":"identifier","text":"topicString"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}