{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"elevator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType","text":"MPHighwayType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mphighwaytype\/elevator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mphighwaytype\/elevator"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/elevator","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"elevator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"}],"title":"elevator","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@MPHighwayTypeElevator","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeElevator"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType/elevator":{"role":"symbol","title":"elevator","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"elevator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/elevator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeElevator"}],"url":"\/documentation\/mapsindoors\/mphighwaytype\/elevator"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType":{"role":"symbol","title":"MPHighwayType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPHighwayType"}],"abstract":[{"type":"text","text":"An enumeration of all accepted types of highways."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPHighwayType"}],"url":"\/documentation\/mapsindoors\/mphighwaytype"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"MPHighwayTypeElevator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPHighwayTypeElevator"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPHighwayTypeElevator"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1elevator\/title","value":"MPHighwayTypeElevator"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1elevator\/fragments","value":[{"kind":"identifier","text":"MPHighwayTypeElevator"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType\/title","value":"MPHighwayType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType\/fragments","value":[{"kind":"identifier","text":"MPHighwayType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}