{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighwayType\/footway"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mphighwaytype\/footway"]},{"paths":["\/documentation\/mapsindoors\/mphighwaytype\/footway"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"footway","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Case","title":"MPHighwayType.footway","externalID":"c:@M@MapsIndoors@E@MPHighwayType@MPHighwayTypeFootway","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"footway"}],"role":"symbol","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeFootway"}],"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighwayType"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighwayType/footway":{"kind":"symbol","title":"MPHighwayType.footway","type":"topic","navigatorTitle":[{"text":"MPHighwayTypeFootway","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighwayType\/footway","abstract":[],"role":"symbol","url":"\/documentation\/mapsindoors\/mphighwaytype\/footway","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"footway","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighwayType":{"navigatorTitle":[{"kind":"identifier","text":"MPHighwayType"}],"abstract":[{"text":"All accepted types of highways (or route elements).","type":"text"}],"kind":"symbol","title":"MPHighwayType","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighwayType","url":"\/documentation\/mapsindoors\/mphighwaytype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPHighwayType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"MPHighwayTypeFootway","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPHighwayTypeFootway"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MPHighwayTypeFootway","kind":"identifier"}],"languages":["occ"]}]}},{"value":"MPHighwayTypeFootway","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighwayType~1footway\/title","op":"replace"},{"op":"replace","value":[{"text":"MPHighwayTypeFootway","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighwayType~1footway\/fragments"},{"value":"MPHighwayType","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighwayType\/title"},{"value":[{"text":"MPHighwayType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighwayType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}