{"variants":[{"paths":["\/documentation\/mapsindoors\/mphighwaytype\/residential"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mphighwaytype\/residential"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighwayType\/residential"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"residential","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"roleHeading":"Case","externalID":"c:@M@MapsIndoors@E@MPHighwayType@MPHighwayTypeResidential","title":"MPHighwayType.residential","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeResidential"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residential","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighwayType"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","alt":null,"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"kind":"symbol","title":"MapsIndoors","role":"collection","type":"topic","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighwayType":{"abstract":[{"type":"text","text":"All accepted types of highways (or route elements)."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MPHighwayType","kind":"identifier"}],"navigatorTitle":[{"text":"MPHighwayType","kind":"identifier"}],"title":"MPHighwayType","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighwayType","type":"topic","url":"\/documentation\/mapsindoors\/mphighwaytype","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighwayType/residential":{"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"residential","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeResidential"}],"title":"MPHighwayType.residential","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighwayType\/residential","type":"topic","url":"\/documentation\/mapsindoors\/mphighwaytype\/residential","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MPHighwayTypeResidential"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MPHighwayTypeResidential","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"MPHighwayTypeResidential","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"MPHighwayType","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighwayType\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighwayType\/fragments","value":[{"text":"MPHighwayType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighwayType~1residential\/title","value":"MPHighwayTypeResidential","op":"replace"},{"value":[{"kind":"identifier","text":"MPHighwayTypeResidential"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighwayType~1residential\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}