{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"wheelChairRamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType","text":"MPHighwayType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mphighwaytype\/wheelchairramp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mphighwaytype\/wheelchairramp"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/wheelChairRamp","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeWheelChairRamp"}],"role":"symbol","title":"wheelChairRamp","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"wheelChairRamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"}],"symbolKind":"property","externalID":"c:@MPHighwayTypeWheelChairRamp","extendedModule":"MapsIndoors","modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType/wheelChairRamp":{"role":"symbol","title":"wheelChairRamp","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"wheelChairRamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/wheelChairRamp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeWheelChairRamp"}],"url":"\/documentation\/mapsindoors\/mphighwaytype\/wheelchairramp"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType":{"role":"symbol","title":"MPHighwayType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPHighwayType"}],"abstract":[{"type":"text","text":"An enumeration of all accepted types of highways."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPHighwayType"}],"url":"\/documentation\/mapsindoors\/mphighwaytype"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"MPHighwayTypeWheelChairRamp"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPHighwayTypeWheelChairRamp"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPHighwayTypeWheelChairRamp"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1wheelChairRamp\/title","value":"MPHighwayTypeWheelChairRamp"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1wheelChairRamp\/fragments","value":[{"kind":"identifier","text":"MPHighwayTypeWheelChairRamp"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType\/title","value":"MPHighwayType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType\/fragments","value":[{"kind":"identifier","text":"MPHighwayType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}