{"metadata":{"roleHeading":"Case","title":"MPDataSetCachingStrategy.automatic","navigatorTitle":[{"text":"MPDataSetCachingStrategyAutomatic","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@E@MPDataSetCachingStrategy@MPDataSetCachingStrategyAutomatic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automatic","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"MapsIndoors"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"automatic","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","abstract":[{"text":"Cache automatically. Data will be kept or removed according to internal behaviors.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachingstrategy\/automatic"]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachingstrategy\/automatic"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/automatic","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingStrategy":{"type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachingstrategy","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MPDataSetCachingStrategy","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCachingStrategy"}],"abstract":[{"text":"Data set caching strategy.","type":"text"}],"title":"MPDataSetCachingStrategy"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingStrategy/automatic":{"title":"MPDataSetCachingStrategy.automatic","kind":"symbol","abstract":[{"type":"text","text":"Cache automatically. Data will be kept or removed according to internal behaviors."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/automatic","navigatorTitle":[{"text":"MPDataSetCachingStrategyAutomatic","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachingstrategy\/automatic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automatic","kind":"identifier"}],"type":"topic"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"MPDataSetCachingStrategyAutomatic","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPDataSetCachingStrategyAutomatic"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MPDataSetCachingStrategyAutomatic","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MPDataSetCachingStrategy","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPDataSetCachingStrategy"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy~1automatic\/title","value":"MPDataSetCachingStrategyAutomatic","op":"replace"},{"value":[{"text":"MPDataSetCachingStrategyAutomatic","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy~1automatic\/fragments"}]}]}