{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"manual"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy"]]},"abstract":[{"text":"Cache manually. Data will be kept until data set is removed manually in the data set manager.","type":"text"}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/manual","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"manual","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPDataSetCachingStrategyManual"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"case","externalID":"c:@M@MapsIndoors@E@MPDataSetCachingStrategy@MPDataSetCachingStrategyManual","role":"symbol","title":"MPDataSetCachingStrategy.manual","roleHeading":"Case"},"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcachingstrategy\/manual"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachingstrategy\/manual"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingStrategy/manual":{"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/manual","title":"MPDataSetCachingStrategy.manual","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"manual","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachingstrategy\/manual","navigatorTitle":[{"text":"MPDataSetCachingStrategyManual","kind":"identifier"}],"abstract":[{"text":"Cache manually. Data will be kept until data set is removed manually in the data set manager.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingStrategy":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mpdatasetcachingstrategy","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDataSetCachingStrategy","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy","abstract":[{"type":"text","text":"Data set caching strategy."}],"navigatorTitle":[{"text":"MPDataSetCachingStrategy","kind":"identifier"}],"title":"MPDataSetCachingStrategy","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MPDataSetCachingStrategyManual"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MPDataSetCachingStrategyManual","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MPDataSetCachingStrategyManual"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy~1manual\/title","value":"MPDataSetCachingStrategyManual","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy~1manual\/fragments","value":[{"text":"MPDataSetCachingStrategyManual","kind":"identifier"}],"op":"replace"},{"value":"MPDataSetCachingStrategy","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy\/title"},{"value":[{"kind":"identifier","text":"MPDataSetCachingStrategy"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}