{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableLiveData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"domainType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMappedLocationUpdateHandler","preciseIdentifier":"c:objc(pl)MPMappedLocationUpdateHandler","text":"MPMappedLocationUpdateHandler"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/enablelivedata(_:handler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/enablelivedata(_:handler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/enableLiveData(_:handler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Start subscribing for Live Data for locations in the visible map region with given "},{"type":"codeVoice","code":"MPLiveDomainType"},{"type":"text","text":". Delegate will be called to handle display updates."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableLiveData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPMappedLocationUpdateHandler","preciseIdentifier":"c:objc(pl)MPMappedLocationUpdateHandler"},{"kind":"text","text":")"}],"title":"enableLiveData(_:handler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPMapControl(im)enableLiveData:handler:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"enableLiveData:handler:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl/enableLiveData(_:handler:)":{"role":"symbol","title":"enableLiveData(_:handler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableLiveData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPMappedLocationUpdateHandler","preciseIdentifier":"c:objc(pl)MPMappedLocationUpdateHandler"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Start subscribing for Live Data for locations in the visible map region with given "},{"type":"codeVoice","code":"MPLiveDomainType"},{"type":"text","text":". Delegate will be called to handle display updates."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/enableLiveData(_:handler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableLiveData:handler:"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/enablelivedata(_:handler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl":{"role":"symbol","title":"MPMapControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"abstract":[{"type":"text","text":"Convenience class for setting up a Google map with MapsIndoors venues, buildings, locations and other map content."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol"},"doc://MapsIndoors/documentation/MapsIndoors/MPMappedLocationUpdateHandler":{"role":"symbol","title":"MPMappedLocationUpdateHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMappedLocationUpdateHandler"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMappedLocationUpdateHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMappedLocationUpdateHandler"}],"url":"\/documentation\/mapsindoors\/mpmappedlocationupdatehandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enableLiveData:handler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableLiveData:handler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"enableLiveData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"domainType"},{"kind":"text","text":" "},{"kind":"identifier","text":"handler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MPMappedLocationUpdateHandler>","preciseIdentifier":"c:Qoobjc(pl)MPMappedLocationUpdateHandler"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"handler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1enableLiveData(_:handler:)\/title","value":"enableLiveData:handler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1enableLiveData(_:handler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableLiveData:handler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"kind":"identifier","text":"MPMapControl"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMappedLocationUpdateHandler\/title","value":"MPMappedLocationUpdateHandler"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMappedLocationUpdateHandler\/fragments","value":[{"kind":"identifier","text":"MPMappedLocationUpdateHandler"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}