{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSearchResult"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fitBounds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/showsearchresult(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/showsearchresult(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/showSearchResult(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Show a given array of locations. The display will override any zoom level condition made from display rules. Clear the locations by calling again with"},{"type":"text","text":" "},{"type":"text","text":"[showLocations:nil fitBounds:NO]"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSearchResult"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"showSearchResult(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPMapControl(im)showSearchResult:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"showSearchResult:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl/showSearchResult(_:)":{"role":"symbol","title":"showSearchResult(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSearchResult"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Show a given array of locations. The display will override any zoom level condition made from display rules. Clear the locations by calling again with"},{"type":"text","text":" "},{"type":"text","text":"[showLocations:nil fitBounds:NO]"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/showSearchResult(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showSearchResult:"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/showsearchresult(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl":{"role":"symbol","title":"MPMapControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"abstract":[{"type":"text","text":"Convenience class for setting up a Google map with MapsIndoors venues, buildings, locations and other map content."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showSearchResult:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showSearchResult:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showSearchResult:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"fitBounds"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1showSearchResult(_:)\/title","value":"showSearchResult:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1showSearchResult(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showSearchResult:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"kind":"identifier","text":"MPMapControl"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}