{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zIndexForUserLocationMarker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/zindexforuserlocationmarker"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/zindexforuserlocationmarker"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/zIndexForUserLocationMarker","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"zIndex of the user location marker (aka “the blue dot”)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zIndexForUserLocationMarker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"zIndexForUserLocationMarker","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPMapControl(py)zIndexForUserLocationMarker","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"zIndexForUserLocationMarker"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl":{"role":"symbol","title":"MPMapControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"abstract":[{"type":"text","text":"Convenience class for setting up a Google map with MapsIndoors venues, buildings, locations and other map content."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl/zIndexForUserLocationMarker":{"role":"symbol","title":"zIndexForUserLocationMarker","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zIndexForUserLocationMarker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"zIndex of the user location marker (aka “the blue dot”)."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/zIndexForUserLocationMarker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"zIndexForUserLocationMarker"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/zindexforuserlocationmarker"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"zIndexForUserLocationMarker"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"zIndexForUserLocationMarker"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"identifier","text":"zIndexForUserLocationMarker"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"kind":"identifier","text":"MPMapControl"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1zIndexForUserLocationMarker\/title","value":"zIndexForUserLocationMarker"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1zIndexForUserLocationMarker\/fragments","value":[{"kind":"identifier","text":"zIndexForUserLocationMarker"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}