{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/blueDot","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MapsIndoors"}],"role":"symbol","externalID":"c:@M@MapsIndoors@E@MPDisplayRuleType@MPDisplayRuleTypeBlueDot","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"MPDisplayRuleTypeBlueDot"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"blueDot","kind":"identifier"}],"roleHeading":"Case","title":"MPDisplayRuleType.blueDot"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"blueDot"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The display rule used for drawing the blue dot, only parts of this display rule is respected."}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdisplayruletype\/bluedot"]},{"paths":["\/documentation\/mapsindoors\/mpdisplayruletype\/bluedot"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"MapsPeopleWhite.png":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRuleType/blueDot":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/blueDot","title":"MPDisplayRuleType.blueDot","role":"symbol","abstract":[{"type":"text","text":"The display rule used for drawing the blue dot, only parts of this display rule is respected."}],"navigatorTitle":[{"kind":"identifier","text":"MPDisplayRuleTypeBlueDot"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpdisplayruletype\/bluedot","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"blueDot","kind":"identifier"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRuleType":{"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType","title":"MPDisplayRuleType","navigatorTitle":[{"kind":"identifier","text":"MPDisplayRuleType"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The MapsIndoors SDK contains a number of display rules used to style non-location content (blue dot, buildings or locations when they are selected)."}],"url":"\/documentation\/mapsindoors\/mpdisplayruletype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDisplayRuleType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MPDisplayRuleTypeBlueDot"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"MPDisplayRuleTypeBlueDot","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MPDisplayRuleTypeBlueDot","kind":"identifier"}]}],"kind":"declarations"}},{"value":"MPDisplayRuleTypeBlueDot","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType~1blueDot\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType~1blueDot\/fragments","value":[{"text":"MPDisplayRuleTypeBlueDot","kind":"identifier"}],"op":"replace"},{"value":"MPDisplayRuleType","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType\/fragments","op":"replace","value":[{"text":"MPDisplayRuleType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}