{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/buildingOutline","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"buildingOutline","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"role":"symbol","roleHeading":"Case","symbolKind":"case","title":"MPDisplayRuleType.buildingOutline","navigatorTitle":[{"text":"MPDisplayRuleTypeBuildingOutline","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@E@MPDisplayRuleType@MPDisplayRuleTypeBuildingOutline"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"buildingOutline","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType"]]},"abstract":[{"type":"text","text":"The display  rule used for drawing outline of the current building, only parts of this display rule is respected."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdisplayruletype\/buildingoutline"]},{"paths":["\/documentation\/mapsindoors\/mpdisplayruletype\/buildingoutline"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRuleType":{"role":"symbol","title":"MPDisplayRuleType","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MPDisplayRuleType","kind":"identifier"}],"navigatorTitle":[{"text":"MPDisplayRuleType","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpdisplayruletype","abstract":[{"type":"text","text":"The MapsIndoors SDK contains a number of display rules used to style non-location content (blue dot, buildings or locations when they are selected)."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRuleType/buildingOutline":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/buildingOutline","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buildingOutline"}],"title":"MPDisplayRuleType.buildingOutline","navigatorTitle":[{"text":"MPDisplayRuleTypeBuildingOutline","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdisplayruletype\/buildingoutline","type":"topic","abstract":[{"text":"The display  rule used for drawing outline of the current building, only parts of this display rule is respected.","type":"text"}],"kind":"symbol","role":"symbol"},"MapsPeopleWhite.png":{"type":"image","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MPDisplayRuleTypeBuildingOutline","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MPDisplayRuleTypeBuildingOutline","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MPDisplayRuleTypeBuildingOutline"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType\/title","op":"replace","value":"MPDisplayRuleType"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType\/fragments","value":[{"kind":"identifier","text":"MPDisplayRuleType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType~1buildingOutline\/title","value":"MPDisplayRuleTypeBuildingOutline","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType~1buildingOutline\/fragments","value":[{"text":"MPDisplayRuleTypeBuildingOutline","kind":"identifier"}]}]}]}