{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/main","interfaceLanguage":"swift"},"abstract":[{"text":"The display rule which may be edited via the CMS. The main rule inherits from the default rule.","type":"text"}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdisplayruletype\/main"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdisplayruletype\/main"]}],"metadata":{"roleHeading":"Case","modules":[{"name":"MapsIndoors"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"main","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@MapsIndoors@E@MPDisplayRuleType@MPDisplayRuleTypeMain","title":"MPDisplayRuleType.main","navigatorTitle":[{"text":"MPDisplayRuleTypeMain","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"main","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"MapsPeopleWhite.png":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRuleType":{"type":"topic","title":"MPDisplayRuleType","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType","navigatorTitle":[{"text":"MPDisplayRuleType","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MPDisplayRuleType","kind":"identifier"}],"abstract":[{"text":"The MapsIndoors SDK contains a number of display rules used to style non-location content (blue dot, buildings or locations when they are selected).","type":"text"}],"url":"\/documentation\/mapsindoors\/mpdisplayruletype"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRuleType/main":{"title":"MPDisplayRuleType.main","role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayruletype\/main","navigatorTitle":[{"text":"MPDisplayRuleTypeMain","kind":"identifier"}],"abstract":[{"type":"text","text":"The display rule which may be edited via the CMS. The main rule inherits from the default rule."}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/main","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"main"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"MPDisplayRuleTypeMain"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MPDisplayRuleTypeMain","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"MPDisplayRuleTypeMain","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType\/title","value":"MPDisplayRuleType"},{"value":[{"text":"MPDisplayRuleType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType\/fragments"},{"value":"MPDisplayRuleTypeMain","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType~1main\/title"},{"value":[{"text":"MPDisplayRuleTypeMain","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType~1main\/fragments","op":"replace"}]}]}