{"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"selectionHighlight","kind":"identifier"}]}]}],"abstract":[{"type":"text","text":"The display rule used for drawing a location, if it is selected. This display rule is entirely respected."}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdisplayruletype\/selectionhighlight"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdisplayruletype\/selectionhighlight"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPDisplayRuleTypeSelectionHighlight"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selectionHighlight"}],"externalID":"c:@M@MapsIndoors@E@MPDisplayRuleType@MPDisplayRuleTypeSelectionHighlight","modules":[{"name":"MapsIndoors"}],"roleHeading":"Case","symbolKind":"case","title":"MPDisplayRuleType.selectionHighlight"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/selectionHighlight"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRuleType":{"role":"symbol","abstract":[{"text":"The MapsIndoors SDK contains a number of display rules used to style non-location content (blue dot, buildings or locations when they are selected).","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDisplayRuleType","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdisplayruletype","type":"topic","title":"MPDisplayRuleType","navigatorTitle":[{"kind":"identifier","text":"MPDisplayRuleType"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRuleType/selectionHighlight":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPDisplayRuleTypeSelectionHighlight"}],"abstract":[{"type":"text","text":"The display rule used for drawing a location, if it is selected. This display rule is entirely respected."}],"role":"symbol","title":"MPDisplayRuleType.selectionHighlight","url":"\/documentation\/mapsindoors\/mpdisplayruletype\/selectionhighlight","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selectionHighlight"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/selectionHighlight"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"MapsPeopleWhite.png":{"alt":null,"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"MPDisplayRuleTypeSelectionHighlight","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MPDisplayRuleTypeSelectionHighlight","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"MPDisplayRuleTypeSelectionHighlight","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType\/title","value":"MPDisplayRuleType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType\/fragments","op":"replace","value":[{"text":"MPDisplayRuleType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType~1selectionHighlight\/title","op":"replace","value":"MPDisplayRuleTypeSelectionHighlight"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType~1selectionHighlight\/fragments","op":"replace","value":[{"text":"MPDisplayRuleTypeSelectionHighlight","kind":"identifier"}]}]}]}