{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"properties","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"] { get }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate"]]},"sections":[],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/properties","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/mapsindoors\/mpliveupdate\/properties"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpliveupdate\/properties"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"properties","modules":[{"name":"MapsIndoors"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"properties","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"properties","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate(py)properties"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate/properties":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/properties","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"properties"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"properties","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpliveupdate\/properties","title":"properties"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveUpdate"}],"url":"\/documentation\/mapsindoors\/mpliveupdate","abstract":[{"text":"Model for a Live Update. Used in ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","type":"reference"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPLiveUpdate"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","title":"MPLiveUpdate","kind":"symbol"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/getLiveUpdate(forDomainType:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getLiveUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forDomainType"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"MPLiveUpdate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate"},{"text":"?","kind":"text"}],"abstract":[{"text":"Get a live update based on a known domain type.","type":"text"}],"url":"\/documentation\/mapsindoors\/mplocation\/getliveupdate(fordomaintype:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getLiveUpdateForDomainType:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","type":"topic","required":true,"title":"getLiveUpdate(forDomainType:)","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"properties","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"properties","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" * ","kind":"text"},{"text":"properties","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate~1properties\/title","op":"replace","value":"properties"},{"op":"replace","value":[{"kind":"identifier","text":"properties"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate~1properties\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/title","value":"MPLiveUpdate","op":"replace"},{"value":[{"kind":"identifier","text":"MPLiveUpdate"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/fragments","op":"replace"},{"value":"getLiveUpdateForDomainType:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getLiveUpdateForDomainType:"}],"op":"replace"}]}]}