{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"topic","kind":"identifier"},{"kind":"text","text":": "},{"text":"MPLiveUpdateTopic","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdateTopic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic"},{"text":" { get }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/topic"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topic","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdateTopic","text":"MPLiveUpdateTopic","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"topic"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"property","externalID":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate(py)topic","roleHeading":"Instance Property","title":"topic","role":"symbol"},"kind":"symbol","abstract":[{"type":"text","text":"Get the Topic of the Live Update."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpliveupdate\/topic"]},{"paths":["\/documentation\/mapsindoors\/mpliveupdate\/topic"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate/topic":{"navigatorTitle":[{"text":"topic","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Get the Topic of the Live Update."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/topic","type":"topic","url":"\/documentation\/mapsindoors\/mpliveupdate\/topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topic","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdateTopic","text":"MPLiveUpdateTopic"}],"title":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate":{"url":"\/documentation\/mapsindoors\/mpliveupdate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","type":"topic","title":"MPLiveUpdate","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPLiveUpdate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPLiveUpdate"}],"abstract":[{"text":"Model for a Live Update. Used in ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","type":"reference","isActive":true}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdateTopic":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPLiveUpdateTopic"}],"abstract":[{"text":"Topic model for a Live Update. A Live Update Topic is hierarchical in the way it is defined, and its relation to MapsIndoors data is derivable by its 7 components: Dataset, Venue, Building, Floor, Room, Location and Domain Type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MPLiveUpdateTopic"}],"title":"MPLiveUpdateTopic","url":"\/documentation\/mapsindoors\/mpliveupdatetopic","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/getLiveUpdate(forDomainType:)":{"url":"\/documentation\/mapsindoors\/mplocation\/getliveupdate(fordomaintype:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","type":"topic","title":"getLiveUpdate(forDomainType:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getLiveUpdate","kind":"identifier"},{"kind":"text","text":"("},{"text":"forDomainType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"text":"MPLiveUpdate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"getLiveUpdateForDomainType:"}],"abstract":[{"type":"text","text":"Get a live update based on a known domain type."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"topic"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"topic","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"MPLiveUpdateTopic","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdateTopic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic"},{"text":" * ","kind":"text"},{"text":"topic","kind":"identifier"}],"languages":["occ"]}]}},{"value":"topic","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate~1topic\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate~1topic\/fragments","op":"replace","value":[{"kind":"identifier","text":"topic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/title","value":"MPLiveUpdate"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/fragments","value":[{"kind":"identifier","text":"MPLiveUpdate"}],"op":"replace"},{"value":"MPLiveUpdateTopic","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic\/title"},{"value":[{"text":"MPLiveUpdateTopic","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic\/fragments","op":"replace"},{"value":"getLiveUpdateForDomainType:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getLiveUpdateForDomainType:"}]}]}]}