{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willUpdateLocationsOnMap"},{"kind":"text","text":"("},{"kind":"externalParam","text":"locations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","preciseIdentifier":"c:objc(cs)MPLocation","text":"MPLocation"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmappedlocationupdatehandler\/willupdatelocationsonmap(locations:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmappedlocationupdatehandler\/willupdatelocationsonmap(locations:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMappedLocationUpdateHandler\/willUpdateLocationsOnMap(locations:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"willUpdateLocationsOnMap:"}],"role":"symbol","title":"willUpdateLocationsOnMap(locations:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willUpdateLocationsOnMap"},{"kind":"text","text":"("},{"kind":"externalParam","text":"locations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:objc(pl)MPMappedLocationUpdateHandler(im)willUpdateLocationsOnMap:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMappedLocationUpdateHandler"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPMappedLocationUpdateHandler":{"role":"symbol","title":"MPMappedLocationUpdateHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMappedLocationUpdateHandler"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMappedLocationUpdateHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMappedLocationUpdateHandler"}],"url":"\/documentation\/mapsindoors\/mpmappedlocationupdatehandler"},"doc://MapsIndoors/documentation/MapsIndoors/MPMappedLocationUpdateHandler/willUpdateLocationsOnMap(locations:)":{"navigatorTitle":[{"kind":"identifier","text":"willUpdateLocationsOnMap:"}],"role":"symbol","title":"willUpdateLocationsOnMap(locations:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willUpdateLocationsOnMap"},{"kind":"text","text":"("},{"kind":"externalParam","text":"locations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMappedLocationUpdateHandler\/willUpdateLocationsOnMap(locations:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpmappedlocationupdatehandler\/willupdatelocationsonmap(locations:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class":{"role":"symbol","title":"MPLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"abstract":[{"type":"text","text":"This class holds the data for a single location and a marker to display the data on a map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"willUpdateLocationsOnMap:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willUpdateLocationsOnMap:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"willUpdateLocationsOnMap:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<MPLocation *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"locations"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMappedLocationUpdateHandler\/title","value":"MPMappedLocationUpdateHandler"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMappedLocationUpdateHandler\/fragments","value":[{"kind":"identifier","text":"MPMappedLocationUpdateHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMappedLocationUpdateHandler~1willUpdateLocationsOnMap(locations:)\/title","value":"willUpdateLocationsOnMap:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMappedLocationUpdateHandler~1willUpdateLocationsOnMap(locations:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willUpdateLocationsOnMap:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/title","value":"MPLocation"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/fragments","value":[{"kind":"identifier","text":"MPLocation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}