{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"nearRight","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPGeoRegion(py)nearRight","modules":[{"name":"MapsIndoors"}],"title":"nearRight","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"nearRight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}]},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion"]]},"variants":[{"paths":["\/documentation\/mapsindoors\/mpgeoregion\/nearright"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpgeoregion\/nearright"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nearRight"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/nearRight","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoRegion":{"type":"topic","url":"\/documentation\/mapsindoors\/mpgeoregion","abstract":[],"title":"MPGeoRegion","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPGeoRegion","kind":"identifier"}],"navigatorTitle":[{"text":"MPGeoRegion","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoRegion/nearRight":{"title":"nearRight","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpgeoregion\/nearright","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nearRight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/nearRight","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"nearRight"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"nearRight"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"nearRight"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":" "},{"kind":"identifier","text":"nearRight"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MPGeoRegion","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion\/title"},{"op":"replace","value":[{"text":"MPGeoRegion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion\/fragments"},{"value":"nearRight","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1nearRight\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"nearRight"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1nearRight\/fragments"}]}]}