{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationServiceDelegate","preciseIdentifier":"c:objc(pl)MPLocationServiceDelegate","text":"MPLocationServiceDelegate"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationservice\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationservice\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationService\/delegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set a delegate to be informed about the status of loading the locations of"},{"type":"text","text":" "},{"type":"text","text":"the current solution."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationServiceDelegate","preciseIdentifier":"c:objc(pl)MPLocationServiceDelegate"},{"kind":"text","text":"?"}],"title":"delegate","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPLocationService(py)delegate","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationService"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationServiceDelegate":{"role":"symbol","title":"MPLocationServiceDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationServiceDelegate"}],"abstract":[{"type":"text","text":"This delegate informs about the status of loading the Locations of the current"},{"type":"text","text":" "},{"type":"text","text":"Solution."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationServiceDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationServiceDelegate"}],"url":"\/documentation\/mapsindoors\/mplocationservicedelegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationService/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationServiceDelegate","preciseIdentifier":"c:objc(pl)MPLocationServiceDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Set a delegate to be informed about the status of loading the locations of"},{"type":"text","text":" "},{"type":"text","text":"the current solution."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationService\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/mapsindoors\/mplocationservice\/delegate"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationService":{"role":"symbol","title":"MPLocationService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationService"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"LocationService"},{"type":"text","text":" acts as service for search and filtering in the full,"},{"type":"text","text":" "},{"type":"text","text":"aggregated collection of Locations. The service requests from all registered"},{"type":"text","text":" "},{"type":"text","text":"Location sources, both internal MapsIndoors and external. Get the shared"},{"type":"text","text":" "},{"type":"text","text":"instance through "},{"type":"codeVoice","code":"MPLocationService.sharedInstance"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationService"}],"url":"\/documentation\/mapsindoors\/mplocationservice"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<MPLocationServiceDelegate>","preciseIdentifier":"c:Qoobjc(pl)MPLocationServiceDelegate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"delegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationServiceDelegate\/title","value":"MPLocationServiceDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationServiceDelegate\/fragments","value":[{"kind":"identifier","text":"MPLocationServiceDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationService~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationService~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationService\/title","value":"MPLocationService"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationService\/fragments","value":[{"kind":"identifier","text":"MPLocationService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}