{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationSourceStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationSourceStatus","preciseIdentifier":"c:@E@MPLocationSourceStatus","text":"MPLocationSourceStatus"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationservice\/locationsourcestatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationservice\/locationsourcestatus"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationService\/locationSourceStatus","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The current status of the Location Source."},{"type":"text","text":" "},{"type":"text","text":"The Location Service can not be used reliably until the status is"},{"type":"text","text":" "},{"type":"text","text":"MPLocationSourceStatusComplete."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationSourceStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationSourceStatus","preciseIdentifier":"c:@E@MPLocationSourceStatus"}],"title":"locationSourceStatus","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPLocationService(py)locationSourceStatus","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"locationSourceStatus"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationService"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationService":{"role":"symbol","title":"MPLocationService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationService"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"LocationService"},{"type":"text","text":" acts as service for search and filtering in the full,"},{"type":"text","text":" "},{"type":"text","text":"aggregated collection of Locations. The service requests from all registered"},{"type":"text","text":" "},{"type":"text","text":"Location sources, both internal MapsIndoors and external. Get the shared"},{"type":"text","text":" "},{"type":"text","text":"instance through "},{"type":"codeVoice","code":"MPLocationService.sharedInstance"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationService"}],"url":"\/documentation\/mapsindoors\/mplocationservice"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationService/locationSourceStatus":{"role":"symbol","title":"locationSourceStatus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationSourceStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationSourceStatus","preciseIdentifier":"c:@E@MPLocationSourceStatus"}],"abstract":[{"type":"text","text":"The current status of the Location Source."},{"type":"text","text":" "},{"type":"text","text":"The Location Service can not be used reliably until the status is"},{"type":"text","text":" "},{"type":"text","text":"MPLocationSourceStatusComplete."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationService\/locationSourceStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"locationSourceStatus"}],"url":"\/documentation\/mapsindoors\/mplocationservice\/locationsourcestatus"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationSourceStatus":{"role":"symbol","title":"MPLocationSourceStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationSourceStatus"}],"abstract":[{"type":"text","text":"Available      Available status. The location source is expected to provide data but may not have data from all data sources yet;"},{"type":"text","text":" "},{"type":"text","text":"Unavailable    unavailable but expected to provide data under normal circumstances;"},{"type":"text","text":" "},{"type":"text","text":"Initialising   processing and expected to provide data when initialised;"},{"type":"text","text":" "},{"type":"text","text":"Inactive       intentionally inactive and not expected to provide data;"},{"type":"text","text":" "},{"type":"text","text":"Complete       The location service is ready to be used;"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationSourceStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationSourceStatus"}],"url":"\/documentation\/mapsindoors\/mplocationsourcestatus"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"locationSourceStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"locationSourceStatus"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationSourceStatus","preciseIdentifier":"c:@E@MPLocationSourceStatus","text":"MPLocationSourceStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationSourceStatus"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationService\/title","value":"MPLocationService"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationService\/fragments","value":[{"kind":"identifier","text":"MPLocationService"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationService~1locationSourceStatus\/title","value":"locationSourceStatus"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationService~1locationSourceStatus\/fragments","value":[{"kind":"identifier","text":"locationSourceStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationSourceStatus\/title","value":"MPLocationSourceStatus"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationSourceStatus\/fragments","value":[{"kind":"identifier","text":"MPLocationSourceStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}