{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"connecting","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpsubscriptionstate\/connecting"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpsubscriptionstate\/connecting"]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionState"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionState\/connecting"},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionStateConnecting"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"connecting","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@E@MPSubscriptionState@MPSubscriptionStateConnecting","modules":[{"name":"MapsIndoors"}],"roleHeading":"Case","title":"MPSubscriptionState.connecting","symbolKind":"case"},"references":{"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionState/connecting":{"url":"\/documentation\/mapsindoors\/mpsubscriptionstate\/connecting","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"connecting","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionStateConnecting"}],"type":"topic","title":"MPSubscriptionState.connecting","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionState\/connecting"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionState":{"title":"MPSubscriptionState","role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpsubscriptionstate","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPSubscriptionState","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionState"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MPSubscriptionStateConnecting"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPSubscriptionStateConnecting"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MPSubscriptionStateConnecting","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionState~1connecting\/title","value":"MPSubscriptionStateConnecting","op":"replace"},{"value":[{"kind":"identifier","text":"MPSubscriptionStateConnecting"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionState~1connecting\/fragments"},{"value":"MPSubscriptionState","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionState\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MPSubscriptionState"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionState\/fragments"}]}]}