{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnecting"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disconnecting"}],"title":"MPSubscriptionState.disconnecting","modules":[{"name":"MapsIndoors"}],"symbolKind":"case","externalID":"c:@M@MapsIndoors@E@MPSubscriptionState@MPSubscriptionStateDisconnecting","navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionStateDisconnecting"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionState\/disconnecting"},"variants":[{"paths":["\/documentation\/mapsindoors\/mpsubscriptionstate\/disconnecting"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpsubscriptionstate\/disconnecting"]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionState"]]},"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionState":{"type":"topic","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpsubscriptionstate","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPSubscriptionState","kind":"identifier"}],"title":"MPSubscriptionState","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionState","navigatorTitle":[{"text":"MPSubscriptionState","kind":"identifier"}]},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionState/disconnecting":{"role":"symbol","abstract":[],"title":"MPSubscriptionState.disconnecting","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disconnecting"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionState\/disconnecting","navigatorTitle":[{"text":"MPSubscriptionStateDisconnecting","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpsubscriptionstate\/disconnecting"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MPSubscriptionStateDisconnecting","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MPSubscriptionStateDisconnecting","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MPSubscriptionStateDisconnecting"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"MPSubscriptionState","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionState\/title"},{"op":"replace","value":[{"text":"MPSubscriptionState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionState\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionState~1disconnecting\/title","value":"MPSubscriptionStateDisconnecting","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionState~1disconnecting\/fragments","value":[{"text":"MPSubscriptionStateDisconnecting","kind":"identifier"}]}]}]}