{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameOnly"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfoscope\/nameonly"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfoscope\/nameonly"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/nameOnly","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Shows only name of POI of defined type along the rendered route"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameOnly"}],"title":"MPDirectionsRendererContextualInfoScope.nameOnly","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MPDirectionsRendererContextualInfoScope@MPDirectionsRendererContextualInfoScopeNameOnly","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScopeNameOnly"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRendererContextualInfoScope/nameOnly":{"role":"symbol","title":"MPDirectionsRendererContextualInfoScope.nameOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameOnly"}],"abstract":[{"type":"text","text":"Shows only name of POI of defined type along the rendered route"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/nameOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScopeNameOnly"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfoscope\/nameonly"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRendererContextualInfoScope":{"role":"symbol","title":"MPDirectionsRendererContextualInfoScope","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScope"}],"abstract":[{"type":"text","text":"Which information to show from the Location close to the end of a route leg."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScope"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfoscope"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MPDirectionsRendererContextualInfoScopeNameOnly"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScopeNameOnly"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScopeNameOnly"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoScope~1nameOnly\/title","value":"MPDirectionsRendererContextualInfoScopeNameOnly"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoScope~1nameOnly\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScopeNameOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoScope\/title","value":"MPDirectionsRendererContextualInfoScope"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoScope\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScope"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}