{"metadata":{"modules":[{"name":"MapsIndoors"}],"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPSolution(py)config","symbolKind":"property","navigatorTitle":[{"text":"config","kind":"identifier"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"config","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPSolutionConfig","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSolutionConfig"}],"roleHeading":"Instance Property","title":"config"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/config","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"config","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSolutionConfig","text":"MPSolutionConfig"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpsolution\/config"]},{"paths":["\/documentation\/mapsindoors\/mpsolution\/config"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolution":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPSolution","kind":"identifier"}],"navigatorTitle":[{"text":"MPSolution","kind":"identifier"}],"abstract":[{"type":"text","text":"The solution model holds data about the buildings and floors in a solution, plus additional meta-data."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution","role":"symbol","type":"topic","kind":"symbol","title":"MPSolution","url":"\/documentation\/mapsindoors\/mpsolution"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolutionConfig":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig","url":"\/documentation\/mapsindoors\/mpsolutionconfig","navigatorTitle":[{"kind":"identifier","text":"MPSolutionConfig"}],"abstract":[{"type":"text","text":"MPSolutionConfig is the way to access the Solution settings made in the MapsIndoors CMS."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPSolutionConfig","kind":"identifier"}],"title":"MPSolutionConfig"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolution/config":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/config","title":"config","required":true,"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"config"}],"url":"\/documentation\/mapsindoors\/mpsolution\/config","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"config","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSolutionConfig","text":"MPSolutionConfig","kind":"typeIdentifier"}],"type":"topic"},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","type":"image","alt":null}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"config","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"config","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSolutionConfig","text":"MPSolutionConfig"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"config"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution\/title","value":"MPSolution"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution\/fragments","op":"replace","value":[{"text":"MPSolution","kind":"identifier"}]},{"value":"MPSolutionConfig","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig\/fragments","op":"replace","value":[{"text":"MPSolutionConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1config\/title","value":"config"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1config\/fragments","value":[{"kind":"identifier","text":"config"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}