{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMapClientUrl"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forVenueId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"venueId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"locationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpsolution\/getmapclienturl(forvenueid:locationid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpsolution\/getmapclienturl(forvenueid:locationid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolution\/getMapClientUrl(forVenueId:locationId:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get a link for a location in a specific venue, for use with the web-client."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMapClientUrl"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forVenueId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"locationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"getMapClientUrl(forVenueId:locationId:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPSolution(im)getMapClientUrlForVenueId:locationId:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getMapClientUrlForVenueId:locationId:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolution"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPSolution/getMapClientUrl(forVenueId:locationId:)":{"role":"symbol","title":"getMapClientUrl(forVenueId:locationId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMapClientUrl"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forVenueId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"locationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get a link for a location in a specific venue, for use with the web-client."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolution\/getMapClientUrl(forVenueId:locationId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getMapClientUrlForVenueId:locationId:"}],"url":"\/documentation\/mapsindoors\/mpsolution\/getmapclienturl(forvenueid:locationid:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPSolution":{"role":"symbol","title":"MPSolution","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSolution"}],"abstract":[{"type":"text","text":"The solution model holds data about the buildings and floors in a solution, plus additional meta-data."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolution","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPSolution"}],"url":"\/documentation\/mapsindoors\/mpsolution"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getMapClientUrlForVenueId:locationId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMapClientUrlForVenueId:locationId:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getMapClientUrlForVenueId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"venueId"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"locationId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolution~1getMapClientUrl(forVenueId:locationId:)\/title","value":"getMapClientUrlForVenueId:locationId:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolution~1getMapClientUrl(forVenueId:locationId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMapClientUrlForVenueId:locationId:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolution\/title","value":"MPSolution"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolution\/fragments","value":[{"kind":"identifier","text":"MPSolution"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}