{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAppDataReady"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"appData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppData","preciseIdentifier":"c:objc(cs)MPAppData","text":"MPAppData"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpappdataproviderdelegate\/onappdataready(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpappdataproviderdelegate\/onappdataready(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProviderDelegate\/onAppDataReady(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onAppDataReady:"}],"role":"symbol","title":"onAppDataReady(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAppDataReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPAppData","preciseIdentifier":"c:objc(cs)MPAppData"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MPAppDataProviderDelegate(im)onAppDataReady:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProviderDelegate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPAppDataProviderDelegate/onAppDataReady(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onAppDataReady:"}],"role":"symbol","title":"onAppDataReady(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAppDataReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPAppData","preciseIdentifier":"c:objc(cs)MPAppData"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProviderDelegate\/onAppDataReady(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpappdataproviderdelegate\/onappdataready(_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPAppData":{"role":"symbol","title":"MPAppData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPAppData"}],"abstract":[{"type":"text","text":"Provides the contextual information needed for setting up a map with specific MapsPeople site data"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPAppData"}],"url":"\/documentation\/mapsindoors\/mpappdata"},"doc://MapsIndoors/documentation/MapsIndoors/MPAppDataProviderDelegate":{"role":"symbol","title":"MPAppDataProviderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPAppDataProviderDelegate"}],"abstract":[{"type":"text","text":"App data provider delegate."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProviderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPAppDataProviderDelegate"}],"url":"\/documentation\/mapsindoors\/mpappdataproviderdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onAppDataReady:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAppDataReady:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onAppDataReady:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppData","preciseIdentifier":"c:objc(cs)MPAppData","text":"MPAppData"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"appData"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProviderDelegate~1onAppDataReady(_:)\/title","value":"onAppDataReady:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProviderDelegate~1onAppDataReady(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAppDataReady:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppData\/title","value":"MPAppData"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppData\/fragments","value":[{"kind":"identifier","text":"MPAppData"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProviderDelegate\/title","value":"MPAppDataProviderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProviderDelegate\/fragments","value":[{"kind":"identifier","text":"MPAppDataProviderDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}