{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpfloorselectorcontrol\/buttonsize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpfloorselectorcontrol\/buttonsize"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/buttonSize","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The size of a single floor button (buttonSize x buttonSize)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"title":"buttonSize","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPFloorSelectorControl(py)buttonSize","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"buttonSize"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl":{"role":"symbol","title":"MPFloorSelectorControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloorSelectorControl"}],"abstract":[{"type":"text","text":"Floor selection UI element. Can be added to the map, but should be linked to an MPBuilding to make sense."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPFloorSelectorControl"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/buttonSize":{"role":"symbol","title":"buttonSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The size of a single floor button (buttonSize x buttonSize)."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/buttonSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buttonSize"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/buttonsize"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"buttonSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"buttonSize"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *"},{"kind":"identifier","text":"buttonSize"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl\/title","value":"MPFloorSelectorControl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl\/fragments","value":[{"kind":"identifier","text":"MPFloorSelectorControl"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1buttonSize\/title","value":"buttonSize"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1buttonSize\/fragments","value":[{"kind":"identifier","text":"buttonSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}