{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableAutomaticLayoutManagement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpfloorselectorcontrol\/disableautomaticlayoutmanagement"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpfloorselectorcontrol\/disableautomaticlayoutmanagement"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/disableAutomaticLayoutManagement","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableAutomaticLayoutManagement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"disableAutomaticLayoutManagement","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPFloorSelectorControl(py)disableAutomaticLayoutManagement","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"disableAutomaticLayoutManagement"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl":{"role":"symbol","title":"MPFloorSelectorControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloorSelectorControl"}],"abstract":[{"type":"text","text":"Floor selection UI element. Can be added to the map, but should be linked to an MPBuilding to make sense."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPFloorSelectorControl"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorControl/disableAutomaticLayoutManagement":{"role":"symbol","title":"disableAutomaticLayoutManagement","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableAutomaticLayoutManagement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorControl\/disableAutomaticLayoutManagement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"disableAutomaticLayoutManagement"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorcontrol\/disableautomaticlayoutmanagement"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"disableAutomaticLayoutManagement"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"disableAutomaticLayoutManagement"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"identifier","text":"disableAutomaticLayoutManagement"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl\/title","value":"MPFloorSelectorControl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl\/fragments","value":[{"kind":"identifier","text":"MPFloorSelectorControl"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1disableAutomaticLayoutManagement\/title","value":"disableAutomaticLayoutManagement"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorControl~1disableAutomaticLayoutManagement\/fragments","value":[{"kind":"identifier","text":"disableAutomaticLayoutManagement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}