{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getOfflineMode"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mapsindoors\/getofflinemode()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mapsindoors\/getofflinemode()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/getOfflineMode()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the current offline mode. True means that the SDK is not allowed to use network traffic."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getOfflineMode"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"getOfflineMode()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MapsIndoors(cm)getOfflineMode","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getOfflineMode"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/getOfflineMode()":{"role":"symbol","title":"getOfflineMode()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getOfflineMode"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Gets the current offline mode. True means that the SDK is not allowed to use network traffic."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/getOfflineMode()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getOfflineMode"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/getofflinemode()"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors":{"role":"symbol","title":"MapsIndoors","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsIndoors"}],"abstract":[{"type":"text","text":"Main class for initialisation, configuration and content synchronisation."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapsIndoors"}],"url":"\/documentation\/mapsindoors\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getOfflineMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getOfflineMode"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"getOfflineMode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1getOfflineMode()\/title","value":"getOfflineMode"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1getOfflineMode()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getOfflineMode"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors\/title","value":"MapsIndoors"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors\/fragments","value":[{"kind":"identifier","text":"MapsIndoors"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}