{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAPIKeyValid"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mapsindoors\/isapikeyvalid()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mapsindoors\/isapikeyvalid()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/isAPIKeyValid()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns whether the current API key is valid or not."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAPIKeyValid"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isAPIKeyValid()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MapsIndoors(cm)isAPIKeyValid","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"isAPIKeyValid"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors":{"role":"symbol","title":"MapsIndoors","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsIndoors"}],"abstract":[{"type":"text","text":"Main class for initialisation, configuration and content synchronisation."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapsIndoors"}],"url":"\/documentation\/mapsindoors\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/isAPIKeyValid()":{"role":"symbol","title":"isAPIKeyValid()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAPIKeyValid"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns whether the current API key is valid or not."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/isAPIKeyValid()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAPIKeyValid"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/isapikeyvalid()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"isAPIKeyValid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isAPIKeyValid"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isAPIKeyValid"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors\/title","value":"MapsIndoors"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors\/fragments","value":[{"kind":"identifier","text":"MapsIndoors"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1isAPIKeyValid()\/title","value":"isAPIKeyValid"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1isAPIKeyValid()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isAPIKeyValid"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}