{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sources"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationSource","preciseIdentifier":"c:objc(pl)MPLocationSource","text":"MPLocationSource"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mapsindoors\/register(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mapsindoors\/register(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/register(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Register Location data sources."},{"type":"text","text":" "},{"type":"text","text":"All registered location sources must have a unique sourceId."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"MPLocationSource","preciseIdentifier":"c:objc(pl)MPLocationSource"},{"kind":"text","text":"])"}],"title":"register(_:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MapsIndoors(cm)registerLocationSources:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"registerLocationSources:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors/register(_:)":{"role":"symbol","title":"register(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"MPLocationSource","preciseIdentifier":"c:objc(pl)MPLocationSource"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Register Location data sources."},{"type":"text","text":" "},{"type":"text","text":"All registered location sources must have a unique sourceId."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors\/register(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerLocationSources:"}],"url":"\/documentation\/mapsindoors\/mapsindoors\/register(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MapsIndoors":{"role":"symbol","title":"MapsIndoors","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsIndoors"}],"abstract":[{"type":"text","text":"Main class for initialisation, configuration and content synchronisation."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MapsIndoors","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MapsIndoors"}],"url":"\/documentation\/mapsindoors\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationSource":{"role":"symbol","title":"MPLocationSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationSource"}],"abstract":[{"type":"text","text":"Location source protocol."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationSource"}],"url":"\/documentation\/mapsindoors\/mplocationsource"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"registerLocationSources:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"registerLocationSources:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"registerLocationSources:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<id<MPLocationSource>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"sources"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1register(_:)\/title","value":"registerLocationSources:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors~1register(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"registerLocationSources:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors\/title","value":"MapsIndoors"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MapsIndoors\/fragments","value":[{"kind":"identifier","text":"MapsIndoors"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationSource\/title","value":"MPLocationSource"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationSource\/fragments","value":[{"kind":"identifier","text":"MPLocationSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}