{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppositionindicator\/position"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppositionindicator\/position"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionIndicator\/position","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"position"}],"role":"symbol","title":"position","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"symbolKind":"property","externalID":"c:objc(cs)MPPositionIndicator(py)position","modules":[{"name":"MapsIndoors"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionIndicator"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPPositionIndicator":{"deprecated":true,"role":"symbol","title":"MPPositionIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionIndicator"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPositionIndicator"}],"url":"\/documentation\/mapsindoors\/mppositionindicator"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionIndicator/position":{"deprecated":true,"role":"symbol","title":"position","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionIndicator\/position","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"position"}],"url":"\/documentation\/mapsindoors\/mppositionindicator\/position"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"position"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"position"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"identifier","text":"position"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionIndicator\/title","value":"MPPositionIndicator"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionIndicator\/fragments","value":[{"kind":"identifier","text":"MPPositionIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionIndicator~1position\/title","value":"position"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionIndicator~1position\/fragments","value":[{"kind":"identifier","text":"position"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}