{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildings"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","kind":"typeIdentifier","text":"MPBuilding","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPBuilding"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/buildings"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpvenue\/buildings"]},{"paths":["\/documentation\/mapsindoors\/mpvenue\/buildings"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"buildings","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPBuilding","text":"MPBuilding","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPVenue(py)buildings","roleHeading":"Instance Property","modules":[{"name":"MapsIndoors"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"buildings"}],"title":"buildings","required":true,"symbolKind":"property"},"sections":[],"abstract":[{"type":"text","text":"Container array for buildings in this venue. Note that this array are not populated initially. "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true,"type":"reference"},{"type":"text","text":" will populate this for the active venue."}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/buildings":{"role":"symbol","required":true,"type":"topic","title":"buildings","abstract":[{"type":"text","text":"Container array for buildings in this venue. Note that this array are not populated initially. "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true,"type":"reference"},{"text":" will populate this for the active venue.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/buildings","url":"\/documentation\/mapsindoors\/mpvenue\/buildings","kind":"symbol","navigatorTitle":[{"text":"buildings","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"buildings","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MPBuilding","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPBuilding","kind":"typeIdentifier"},{"kind":"text","text":"]?"}]},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","alt":null,"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"abstract":[{"type":"text","text":"This is the control object for the visual representation of the MapsIndoors SDK."}],"url":"\/documentation\/mapsindoors\/mpmapcontrol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPMapControl"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"type":"topic","kind":"symbol","title":"MPMapControl","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue":{"url":"\/documentation\/mapsindoors\/mpvenue","type":"topic","title":"MPVenue","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","kind":"symbol","role":"symbol","abstract":[{"text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data.","type":"text"}],"navigatorTitle":[{"text":"MPVenue","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPVenue"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding":{"abstract":[{"text":"Holds relevant data for a single building, and the buildings floor levels.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","role":"symbol","kind":"symbol","title":"MPBuilding","navigatorTitle":[{"kind":"identifier","text":"MPBuilding"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPBuilding","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpbuilding","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"buildings","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"buildings"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<id<MPBuilding>>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"buildings"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1buildings\/title","value":"buildings"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1buildings\/fragments","value":[{"text":"buildings","kind":"identifier"}]},{"value":"MPMapControl","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title"},{"value":[{"text":"MPMapControl","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","op":"replace"},{"op":"replace","value":"MPVenue","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/title"},{"value":[{"kind":"identifier","text":"MPVenue"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/title","value":"MPBuilding"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPBuilding"}]}]}]}