{"metadata":{"modules":[{"name":"MapsIndoors"}],"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultStyle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPMapStyle","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPMapStyle"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","title":"defaultStyle","navigatorTitle":[{"text":"defaultStyle","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@MapsIndoors@objc(pl)MPVenue(py)defaultStyle"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPMapStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPMapStyle","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapStyle"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Get a default style. If none is set, it will be the first string value in the list of map styles."}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpvenue\/defaultstyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpvenue\/defaultstyle"]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/defaultStyle","interfaceLanguage":"swift"},"references":{"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/defaultStyle":{"abstract":[{"type":"text","text":"Get a default style. If none is set, it will be the first string value in the list of map styles."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPMapStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPMapStyle"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"defaultStyle"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpvenue\/defaultstyle","kind":"symbol","required":true,"title":"defaultStyle","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/defaultStyle"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue":{"url":"\/documentation\/mapsindoors\/mpvenue","type":"topic","title":"MPVenue","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","kind":"symbol","role":"symbol","abstract":[{"text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data.","type":"text"}],"navigatorTitle":[{"text":"MPVenue","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPVenue"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapStyle":{"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpmapstyle","navigatorTitle":[{"text":"MPMapStyle","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapStyle","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPMapStyle","kind":"identifier"}],"title":"MPMapStyle"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"defaultStyle","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"defaultStyle","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPMapStyle","text":"id<MPMapStyle>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"defaultStyle","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1defaultStyle\/title","value":"defaultStyle"},{"op":"replace","value":[{"kind":"identifier","text":"defaultStyle"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1defaultStyle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/title","value":"MPVenue"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPVenue"}]},{"value":"MPMapStyle","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapStyle\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MPMapStyle"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapStyle\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}