{"metadata":{"roleHeading":"Instance Property","title":"entryPoints","navigatorTitle":[{"kind":"identifier","text":"entryPoints"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPVenue(py)entryPoints","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entryPoints","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint"},{"text":"]?","kind":"text"}],"required":true,"modules":[{"name":"MapsIndoors"}],"symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpvenue\/entrypoints"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpvenue\/entrypoints"]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"entryPoints","kind":"identifier"},{"kind":"text","text":": ["},{"text":"MPPoint","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","kind":"typeIdentifier"},{"text":"]? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Array of entry points in this venue."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/entryPoints"},"kind":"symbol","sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/entryPoints":{"type":"topic","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"entryPoints","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","text":"MPPoint","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"entryPoints"}],"url":"\/documentation\/mapsindoors\/mpvenue\/entrypoints","abstract":[{"text":"Array of entry points in this venue.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/entryPoints","kind":"symbol","title":"entryPoints"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPVenue"}],"title":"MPVenue","navigatorTitle":[{"text":"MPVenue","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpvenue","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","role":"symbol","abstract":[{"text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data.","type":"text"}],"type":"topic","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPoint":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPoint"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint","title":"MPPoint","navigatorTitle":[{"text":"MPPoint","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/mapsindoors\/mppoint"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"MapsPeopleWhite.png":{"alt":null,"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"entryPoints"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"entryPoints","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<MPPoint *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"entryPoints","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"entryPoints","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1entryPoints\/title"},{"op":"replace","value":[{"text":"entryPoints","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1entryPoints\/fragments"},{"value":"MPVenue","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/fragments","op":"replace","value":[{"text":"MPVenue","kind":"identifier"}]},{"value":"MPPoint","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPoint\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MPPoint"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPoint\/fragments"}]}]}