{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tilesUrl","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"abstract":[{"text":"The general url template to be used when creating floor layers for this venue. If used by this framework, the url string must have format ","type":"text"},{"code":"\"prefix{param_1}infix{param_N}suffix\"","type":"codeVoice"},{"type":"text","text":", e.g. "},{"type":"codeVoice","code":"\"http:\/\/tiles.url.com\/{floor}\/{x}\/{y}\/{zoom}.png\""},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/tilesUrl"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpvenue\/tilesurl"]},{"paths":["\/documentation\/mapsindoors\/mpvenue\/tilesurl"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tilesUrl"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"tilesUrl","kind":"identifier"}],"role":"symbol","title":"tilesUrl","required":true,"externalID":"c:@M@MapsIndoors@objc(pl)MPVenue(py)tilesUrl","modules":[{"name":"MapsIndoors"}],"symbolKind":"property"},"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPVenue"}],"title":"MPVenue","navigatorTitle":[{"text":"MPVenue","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpvenue","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","role":"symbol","abstract":[{"text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data.","type":"text"}],"type":"topic","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/tilesUrl":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/tilesUrl","title":"tilesUrl","required":true,"role":"symbol","abstract":[{"text":"The general url template to be used when creating floor layers for this venue. If used by this framework, the url string must have format ","type":"text"},{"type":"codeVoice","code":"\"prefix{param_1}infix{param_N}suffix\""},{"text":", e.g. ","type":"text"},{"type":"codeVoice","code":"\"http:\/\/tiles.url.com\/{floor}\/{x}\/{y}\/{zoom}.png\""},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"tilesUrl"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpvenue\/tilesurl","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tilesUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic"},"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"tilesUrl"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"tilesUrl"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"tilesUrl","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/title","value":"MPVenue"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/fragments","value":[{"text":"MPVenue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1tilesUrl\/title","value":"tilesUrl","op":"replace"},{"value":[{"text":"tilesUrl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1tilesUrl\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}