{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpvenue\/venueinfo"]},{"paths":["\/documentation\/mapsindoors\/mpvenue\/venueinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"venueInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPEntityInfo","text":"MPEntityInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntityInfo"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"text":"The VenueInfo from backend. Contains the name, aliases and properties for the venue.","type":"text"}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/venueInfo","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue"]]},"metadata":{"modules":[{"name":"MapsIndoors"}],"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPVenue(py)venueInfo","symbolKind":"property","navigatorTitle":[{"text":"venueInfo","kind":"identifier"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"venueInfo"},{"text":": ","kind":"text"},{"text":"MPEntityInfo","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPEntityInfo","kind":"typeIdentifier"}],"roleHeading":"Instance Property","title":"venueInfo"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPEntityInfo":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntityInfo","type":"topic","role":"symbol","navigatorTitle":[{"text":"MPEntityInfo","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPEntityInfo"}],"url":"\/documentation\/mapsindoors\/mpentityinfo","abstract":[{"text":"MPEntityInfo  is a general class used by ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","type":"reference","isActive":true},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding"},{"text":" and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue"},{"text":" for the relevant info (eg buildingInfo, venueInfo etc)","type":"text"}],"title":"MPEntityInfo"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation":{"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","abstract":[{"type":"text","text":"This holds the data for a single location and a marker to display the data on a map."}],"url":"\/documentation\/mapsindoors\/mplocation","role":"symbol","title":"MPLocation","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"navigatorTitle":[{"text":"MPLocation","kind":"identifier"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding":{"kind":"symbol","abstract":[{"type":"text","text":"Holds relevant data for a single building, and the buildings floor levels."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","navigatorTitle":[{"text":"MPBuilding","kind":"identifier"}],"type":"topic","title":"MPBuilding","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPBuilding","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpbuilding","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/venueInfo":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"venueInfo"}],"url":"\/documentation\/mapsindoors\/mpvenue\/venueinfo","kind":"symbol","type":"topic","abstract":[{"text":"The VenueInfo from backend. Contains the name, aliases and properties for the venue.","type":"text"}],"title":"venueInfo","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/venueInfo","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"venueInfo"},{"kind":"text","text":": "},{"text":"MPEntityInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPEntityInfo"}]},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image","identifier":"MapsPeopleWhite.png","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPVenue"}],"title":"MPVenue","navigatorTitle":[{"text":"MPVenue","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpvenue","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","role":"symbol","abstract":[{"text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data.","type":"text"}],"type":"topic","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"venueInfo","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"venueInfo","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPEntityInfo","text":"MPEntityInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntityInfo"},{"kind":"text","text":" * "},{"kind":"identifier","text":"venueInfo"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntityInfo\/title","value":"MPEntityInfo"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntityInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPEntityInfo"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/title","value":"MPLocation","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPLocation"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/title","op":"replace","value":"MPBuilding"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/fragments","value":[{"kind":"identifier","text":"MPBuilding"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1venueInfo\/title","value":"venueInfo","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"venueInfo"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1venueInfo\/fragments"},{"value":"MPVenue","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/title","op":"replace"},{"value":[{"text":"MPVenue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/fragments","op":"replace"}]}]}