{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addLocationsObserver","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"observer"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationsObserver","text":"MPLocationsObserver","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The observer object."}],"type":"paragraph"}],"name":"observer"}],"kind":"parameters"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource"]]},"abstract":[{"text":"Add an observer that gets callbacks about updates, additions and deletions to locations in this location source.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/addLocationsObserver(_:)"},"kind":"symbol","variants":[{"paths":["\/documentation\/mapsindoors\/mplocationsource\/addlocationsobserver(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mplocationsource\/addlocationsobserver(_:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addLocationsObserver","kind":"identifier"},{"kind":"text","text":"("},{"text":"MPLocationsObserver","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationsObserver","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"addLocationsObserver:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@MapsIndoors@objc(pl)MPLocationSource(im)addLocationsObserver:","modules":[{"name":"MapsIndoors"}],"role":"symbol","required":true,"title":"addLocationsObserver(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSource":{"title":"MPLocationSource","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource","kind":"symbol","abstract":[{"text":"Location source protocol.","type":"text"}],"url":"\/documentation\/mapsindoors\/mplocationsource","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPLocationSource","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MPLocationSource","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSource/addLocationsObserver(_:)":{"required":true,"navigatorTitle":[{"text":"addLocationsObserver:","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/addLocationsObserver(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addLocationsObserver"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationsObserver","text":"MPLocationsObserver"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapsindoors\/mplocationsource\/addlocationsobserver(_:)","type":"topic","abstract":[{"text":"Add an observer that gets callbacks about updates, additions and deletions to locations in this location source.","type":"text"}],"title":"addLocationsObserver(_:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationsObserver":{"kind":"symbol","type":"topic","abstract":[{"text":"Location observer protocol.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver","url":"\/documentation\/mapsindoors\/mplocationsobserver","role":"symbol","title":"MPLocationsObserver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPLocationsObserver","kind":"identifier"}],"navigatorTitle":[{"text":"MPLocationsObserver","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"addLocationsObserver:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"addLocationsObserver:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"addLocationsObserver:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPLocationsObserver","text":"id<MPLocationsObserver>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"observer","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource\/title","value":"MPLocationSource","op":"replace"},{"value":[{"text":"MPLocationSource","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource\/fragments","op":"replace"},{"value":"addLocationsObserver:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource~1addLocationsObserver(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource~1addLocationsObserver(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addLocationsObserver:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationsObserver\/title","value":"MPLocationsObserver"},{"op":"replace","value":[{"kind":"identifier","text":"MPLocationsObserver"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationsObserver\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}