{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/removeLocationsObserver(_:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeLocationsObserver"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"observer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver","text":"MPLocationsObserver","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationsObserver"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"observer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The observer object to remove."}]}]}],"kind":"parameters"}],"metadata":{"navigatorTitle":[{"text":"removeLocationsObserver:","kind":"identifier"}],"required":true,"role":"symbol","modules":[{"name":"MapsIndoors"}],"title":"removeLocationsObserver(_:)","externalID":"c:@M@MapsIndoors@objc(pl)MPLocationSource(im)removeLocationsObserver:","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeLocationsObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MPLocationsObserver","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationsObserver","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource"]]},"sections":[],"abstract":[{"type":"text","text":"Remove an observer that gets callbacks about updates, additions and deletions to locations in this location source."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mplocationsource\/removelocationsobserver(_:)"]},{"paths":["\/documentation\/mapsindoors\/mplocationsource\/removelocationsobserver(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","alt":null,"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSource/removeLocationsObserver(_:)":{"required":true,"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/removeLocationsObserver(_:)","url":"\/documentation\/mapsindoors\/mplocationsource\/removelocationsobserver(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeLocationsObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MPLocationsObserver","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationsObserver"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Remove an observer that gets callbacks about updates, additions and deletions to locations in this location source."}],"title":"removeLocationsObserver(_:)","navigatorTitle":[{"text":"removeLocationsObserver:","kind":"identifier"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationsObserver":{"title":"MPLocationsObserver","abstract":[{"type":"text","text":"Location observer protocol."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPLocationsObserver","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MPLocationsObserver","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mplocationsobserver","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSource":{"title":"MPLocationSource","navigatorTitle":[{"kind":"identifier","text":"MPLocationSource"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPLocationSource","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mplocationsource","abstract":[{"type":"text","text":"Location source protocol."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"removeLocationsObserver:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"removeLocationsObserver:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"removeLocationsObserver:"},{"text":"(","kind":"text"},{"text":"id<MPLocationsObserver>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPLocationsObserver"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"observer"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"removeLocationsObserver:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource~1removeLocationsObserver(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"removeLocationsObserver:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource~1removeLocationsObserver(_:)\/fragments"},{"value":"MPLocationsObserver","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationsObserver\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationsObserver\/fragments","value":[{"text":"MPLocationsObserver","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource\/title","op":"replace","value":"MPLocationSource"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource\/fragments","value":[{"text":"MPLocationSource","kind":"identifier"}]}]}]}