{"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationsource\/status"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationsource\/status"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPLocationSource(py)status","roleHeading":"Instance Property","title":"status","modules":[{"name":"MapsIndoors"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"text":"MPLocationSourceStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPLocationSourceStatus"}],"navigatorTitle":[{"text":"status","kind":"identifier"}],"required":true,"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The status of the location source."}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus","text":"MPLocationSourceStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPLocationSourceStatus"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/status","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSource/status":{"required":true,"url":"\/documentation\/mapsindoors\/mplocationsource\/status","navigatorTitle":[{"text":"status","kind":"identifier"}],"abstract":[{"text":"The status of the location source.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/status","title":"status","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@E@MPLocationSourceStatus","kind":"typeIdentifier","text":"MPLocationSourceStatus"}]},"MapsPeopleWhite.png":{"alt":null,"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSource":{"abstract":[{"text":"Location source protocol.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationSource"}],"navigatorTitle":[{"text":"MPLocationSource","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource","url":"\/documentation\/mapsindoors\/mplocationsource","role":"symbol","kind":"symbol","title":"MPLocationSource"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSourceStatus":{"navigatorTitle":[{"kind":"identifier","text":"MPLocationSourceStatus"}],"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsourcestatus","title":"MPLocationSourceStatus","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPLocationSourceStatus","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"status"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"status"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPLocationSourceStatus","text":"MPLocationSourceStatus","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"status","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource~1status\/title"},{"value":[{"kind":"identifier","text":"status"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource~1status\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource\/title","value":"MPLocationSource"},{"value":[{"text":"MPLocationSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource\/fragments"},{"value":"MPLocationSourceStatus","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus\/fragments","value":[{"text":"MPLocationSourceStatus","kind":"identifier"}],"op":"replace"}]}]}