{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeDisplayRuleForTypeName"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule","text":"MPLocationDisplayRule"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdisplayrulemanager\/removedisplayrulefortypename(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdisplayrulemanager\/removedisplayrulefortypename(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/removeDisplayRuleForTypeName(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeDisplayRuleForTypeName"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule"},{"kind":"text","text":"?"}],"title":"removeDisplayRuleForTypeName(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@MapsIndoors@objc(cs)MPDisplayRuleManager(im)removeDisplayRuleForTypeName:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"removeDisplayRuleForTypeName:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDisplayRuleManager/removeDisplayRuleForTypeName(_:)":{"role":"symbol","title":"removeDisplayRuleForTypeName(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeDisplayRuleForTypeName"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/removeDisplayRuleForTypeName(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeDisplayRuleForTypeName:"}],"url":"\/documentation\/mapsindoors\/mpdisplayrulemanager\/removedisplayrulefortypename(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule":{"role":"symbol","title":"MPLocationDisplayRule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationDisplayRule"}],"abstract":[{"type":"text","text":"This class serves as a display rule for locations."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationDisplayRule"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule"},"doc://MapsIndoors/documentation/MapsIndoors/MPDisplayRuleManager":{"role":"symbol","title":"MPDisplayRuleManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDisplayRuleManager"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDisplayRuleManager"}],"url":"\/documentation\/mapsindoors\/mpdisplayrulemanager"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeDisplayRuleForTypeName:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeDisplayRuleForTypeName:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule","text":"MPLocationDisplayRule"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"removeDisplayRuleForTypeName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"name"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1removeDisplayRuleForTypeName(_:)\/title","value":"removeDisplayRuleForTypeName:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1removeDisplayRuleForTypeName(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeDisplayRuleForTypeName:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule\/title","value":"MPLocationDisplayRule"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule\/fragments","value":[{"kind":"identifier","text":"MPLocationDisplayRule"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager\/title","value":"MPDisplayRuleManager"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager\/fragments","value":[{"kind":"identifier","text":"MPDisplayRuleManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}