{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRuleManager","text":"MPDisplayRuleManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdisplayrulemanager\/sharedinstance"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdisplayrulemanager\/sharedinstance"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/sharedInstance","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDisplayRuleManager","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRuleManager"}],"title":"sharedInstance","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@MapsIndoors@objc(cs)MPDisplayRuleManager(cpy)sharedInstance","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"sharedInstance"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDisplayRuleManager/sharedInstance":{"role":"symbol","title":"sharedInstance","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDisplayRuleManager","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRuleManager"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/sharedInstance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedInstance"}],"url":"\/documentation\/mapsindoors\/mpdisplayrulemanager\/sharedinstance"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDisplayRuleManager":{"role":"symbol","title":"MPDisplayRuleManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDisplayRuleManager"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDisplayRuleManager"}],"url":"\/documentation\/mapsindoors\/mpdisplayrulemanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"sharedInstance"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sharedInstance"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRuleManager","text":"MPDisplayRuleManager"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sharedInstance"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1sharedInstance\/title","value":"sharedInstance"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1sharedInstance\/fragments","value":[{"kind":"identifier","text":"sharedInstance"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager\/title","value":"MPDisplayRuleManager"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager\/fragments","value":[{"kind":"identifier","text":"MPDisplayRuleManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}