{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVenueWithId"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"venueId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":" "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpVenueDetailsHandlerBlockType","preciseIdentifier":"c:MPVenueProvider.h@T@mpVenueDetailsHandlerBlockType","text":"mpVenueDetailsHandlerBlockType"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"venueId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Venue id"}]}]},{"name":"handler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Venue details fetch callback block"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpvenueprovider\/getvenuewithid(_:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpvenueprovider\/getvenuewithid(_:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getVenueWithId(_:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get single venue details object"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVenueWithId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpVenueDetailsHandlerBlockType","preciseIdentifier":"c:MPVenueProvider.h@T@mpVenueDetailsHandlerBlockType"},{"kind":"text","text":"?)"}],"title":"getVenueWithId(_:completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPVenueProvider(im)getVenueWithId:completionHandler:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getVenueWithId:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/getVenueWithId(_:completionHandler:)":{"role":"symbol","title":"getVenueWithId(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVenueWithId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpVenueDetailsHandlerBlockType","preciseIdentifier":"c:MPVenueProvider.h@T@mpVenueDetailsHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get single venue details object"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getVenueWithId(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getVenueWithId:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/getvenuewithid(_:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/mpVenueDetailsHandlerBlockType":{"role":"symbol","title":"mpVenueDetailsHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpVenueDetailsHandlerBlockType"}],"abstract":[{"type":"text","text":"Handler block for fetching venues."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpVenueDetailsHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpVenueDetailsHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpvenuedetailshandlerblocktype"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider":{"role":"symbol","title":"MPVenueProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenueProvider"}],"abstract":[{"type":"text","text":"Venue provider interface, that defines a delegate and a method for venue queries."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenueProvider"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getVenueWithId:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVenueWithId:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getVenueWithId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"venueId"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(MPVenue *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)MPVenue#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"handler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getVenueWithId(_:completionHandler:)\/title","value":"getVenueWithId:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getVenueWithId(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVenueWithId:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpVenueDetailsHandlerBlockType\/title","value":"mpVenueDetailsHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpVenueDetailsHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpVenueDetailsHandlerBlockType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider\/title","value":"MPVenueProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider\/fragments","value":[{"kind":"identifier","text":"MPVenueProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}