{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVenueWithId"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"venueId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"venueId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Venue id"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpvenueprovider\/getvenuewithid(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpvenueprovider\/getvenuewithid(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getVenueWithId(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get a single venue object"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVenueWithId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"getVenueWithId(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPVenueProvider(im)getVenueWithId:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getVenueWithId:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider":{"role":"symbol","title":"MPVenueProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenueProvider"}],"abstract":[{"type":"text","text":"Venue provider interface, that defines a delegate and a method for venue queries."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenueProvider"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/getVenueWithId(_:)":{"role":"symbol","title":"getVenueWithId(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVenueWithId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get a single venue object"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getVenueWithId(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getVenueWithId:"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/getvenuewithid(_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getVenueWithId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVenueWithId:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getVenueWithId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"venueId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider\/title","value":"MPVenueProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider\/fragments","value":[{"kind":"identifier","text":"MPVenueProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getVenueWithId(_:)\/title","value":"getVenueWithId:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getVenueWithId(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVenueWithId:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}