{"metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPMultiPolygonGeometry(im)containsCoordinate:ignorePolygonHoles:containmentMetadata:","modules":[{"name":"MapsIndoors"}],"title":"containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"containsCoordinate"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"ignorePolygonHoles","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"containmentMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometryContainmentMetadata","text":"MPGeometryContainmentMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"kind":"symbol","abstract":[{"type":"text","text":"Check if the given coordinate is contained within the polygon, and optionally return the coordinate closest to the polygon."},{"text":" ","type":"text"},{"text":"If the polygon contains the coordinate, ‘coordinate’ is returned as nearestPoint.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If coordinate is not contained, the nearest point is calculated."}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry"]]},"variants":[{"paths":["\/documentation\/mapsindoors\/mpmultipolygongeometry\/containscoordinate(_:ignorepolygonholes:containmentmetadata:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpmultipolygongeometry\/containscoordinate(_:ignorepolygonholes:containmentmetadata:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"containsCoordinate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"coordinate","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"ignorePolygonHoles","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"containmentMetadata"},{"text":": ","kind":"text"},{"text":"MPGeometryContainmentMetadata","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometryContainmentMetadata","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"coordinate","content":[{"type":"paragraph","inlineContent":[{"text":"Coordinate to check for containment.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Should holes in a polygon be ignored"}]}],"name":"ignorePolygonHoles"},{"content":[{"inlineContent":[{"type":"text","text":"If not nil, the nearest point and distance on the polygon boundary is returned. Note this may be the nearest point on a polygon-hole."}],"type":"paragraph"}],"name":"containmentMetadata"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"False if the coordinate is outside the polygon, or inside any holes in the polygon."}]}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryContainmentMetadata":{"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata","kind":"symbol","type":"topic","title":"MPGeometryContainmentMetadata","url":"\/documentation\/mapsindoors\/mpgeometrycontainmentmetadata","navigatorTitle":[{"kind":"identifier","text":"MPGeometryContainmentMetadata"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeometryContainmentMetadata"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMultiPolygonGeometry/containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)","url":"\/documentation\/mapsindoors\/mpmultipolygongeometry\/containscoordinate(_:ignorepolygonholes:containmentmetadata:)","title":"containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)","abstract":[{"text":"Check if the given coordinate is contained within the polygon, and optionally return the coordinate closest to the polygon.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If the polygon contains the coordinate, ‘coordinate’ is returned as nearestPoint."},{"text":" ","type":"text"},{"text":"If coordinate is not contained, the nearest point is calculated.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"containsCoordinate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"text":"ignorePolygonHoles","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"containmentMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometryContainmentMetadata","kind":"typeIdentifier","text":"MPGeometryContainmentMetadata"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMultiPolygonGeometry":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry","abstract":[],"url":"\/documentation\/mapsindoors\/mpmultipolygongeometry","navigatorTitle":[{"text":"MPMultiPolygonGeometry","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPMultiPolygonGeometry","kind":"identifier"}],"title":"MPMultiPolygonGeometry"},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image","alt":null,"identifier":"MapsPeopleWhite.png"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"containsCoordinate:ignorePolygonHoles:containmentMetadata:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"containsCoordinate:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"coordinate"},{"kind":"text","text":" "},{"text":"ignorePolygonHoles:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"ignorePolygonHoles"},{"kind":"text","text":" "},{"text":"containmentMetadata:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometryContainmentMetadata","text":"MPGeometryContainmentMetadata","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata"},{"text":" *) ","kind":"text"},{"text":"containmentMetadata","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","value":"MPGeometryContainmentMetadata","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryContainmentMetadata\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryContainmentMetadata\/fragments","value":[{"kind":"identifier","text":"MPGeometryContainmentMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)\/title","value":"containsCoordinate:ignorePolygonHoles:containmentMetadata:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry\/title","value":"MPMultiPolygonGeometry"},{"value":[{"text":"MPMultiPolygonGeometry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry\/fragments"}]}]}