{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsLineSegmentFromCoordinate(_:toCoordinate:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"containsLineSegmentFromCoordinate","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"u","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"toCoordinate"},{"kind":"text","text":" "},{"kind":"internalParam","text":"v"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Start coordinate of line segment to check for containment.","type":"text"}],"type":"paragraph"}],"name":"u"},{"content":[{"inlineContent":[{"text":"End coordinate of line segment to check for containment.","type":"text"}],"type":"paragraph"}],"name":"v"}]},{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"True if the coordinate is inside the polygon boundary AND outside any holes in the polygon. False if the coordinate is outside the polygon, or inside any holes in the polygon.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Check if the given line segment is fully contained within the polygon."}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"containsLineSegmentFromCoordinate","kind":"identifier"},{"kind":"text","text":"("},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"toCoordinate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"containsLineSegmentFromCoordinate:toCoordinate:","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPMultiPolygonGeometry(im)containsLineSegmentFromCoordinate:toCoordinate:","symbolKind":"method","role":"symbol","modules":[{"name":"MapsIndoors"}],"roleHeading":"Instance Method","title":"containsLineSegmentFromCoordinate(_:toCoordinate:)"},"kind":"symbol","variants":[{"paths":["\/documentation\/mapsindoors\/mpmultipolygongeometry\/containslinesegmentfromcoordinate(_:tocoordinate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmultipolygongeometry\/containslinesegmentfromcoordinate(_:tocoordinate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMultiPolygonGeometry":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPMultiPolygonGeometry","kind":"identifier"}],"navigatorTitle":[{"text":"MPMultiPolygonGeometry","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/mapsindoors\/mpmultipolygongeometry","title":"MPMultiPolygonGeometry"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMultiPolygonGeometry/containsLineSegmentFromCoordinate(_:toCoordinate:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"containsLineSegmentFromCoordinate","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toCoordinate"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"containsLineSegmentFromCoordinate:toCoordinate:"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsLineSegmentFromCoordinate(_:toCoordinate:)","kind":"symbol","abstract":[{"text":"Check if the given line segment is fully contained within the polygon.","type":"text"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpmultipolygongeometry\/containslinesegmentfromcoordinate(_:tocoordinate:)","title":"containsLineSegmentFromCoordinate(_:toCoordinate:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"containsLineSegmentFromCoordinate:toCoordinate:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"containsLineSegmentFromCoordinate:toCoordinate:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"containsLineSegmentFromCoordinate:"},{"kind":"text","text":"("},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"u","kind":"internalParam"},{"kind":"text","text":" "},{"text":"toCoordinate:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"text":") ","kind":"text"},{"text":"v","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry\/title","value":"MPMultiPolygonGeometry"},{"value":[{"kind":"identifier","text":"MPMultiPolygonGeometry"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1containsLineSegmentFromCoordinate(_:toCoordinate:)\/title","value":"containsLineSegmentFromCoordinate:toCoordinate:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1containsLineSegmentFromCoordinate(_:toCoordinate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsLineSegmentFromCoordinate:toCoordinate:"}],"op":"replace"}]}]}