{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getStartFloorName"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mproutestep-swift.class\/getstartfloorname()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mproutestep-swift.class\/getstartfloorname()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/getStartFloorName()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getStartFloorName"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"title":"getStartFloorName()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPRouteStep(im)getStartFloorName","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getStartFloorName"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class":{"role":"symbol","title":"MPRouteStep","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteStep"}],"abstract":[{"type":"text","text":"Route step model. A step is segment on a "},{"type":"codeVoice","code":"MPRouteLeg"},{"type":"text","text":" ("},{"type":"codeVoice","code":"MPRouteLeg"},{"type":"text","text":" is a segment on a "},{"type":"codeVoice","code":"MPRoute"},{"type":"text","text":"). The step contains start and end locations, distance and duration information, as well as navigational instructions."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteStep"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/getStartFloorName()":{"role":"symbol","title":"getStartFloorName()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getStartFloorName"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/getStartFloorName()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getStartFloorName"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/getstartfloorname()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getStartFloorName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getStartFloorName"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getStartFloorName"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class\/title","value":"MPRouteStep"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class\/fragments","value":[{"kind":"identifier","text":"MPRouteStep"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1getStartFloorName()\/title","value":"getStartFloorName"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1getStartFloorName()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getStartFloorName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}