{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highway"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType","text":"MPHighwayType"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mproutestep-swift.class\/highway"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mproutestep-swift.class\/highway"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/highway","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Way type for this step (part of the route). E.g. footway, steps, elevator, residential etc."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highway"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"},{"kind":"text","text":"?"}],"title":"highway","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPRouteStep(py)highway","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"highway"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/highway":{"role":"symbol","title":"highway","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highway"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Way type for this step (part of the route). E.g. footway, steps, elevator, residential etc."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/highway","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"highway"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/highway"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType":{"role":"symbol","title":"MPHighwayType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPHighwayType"}],"abstract":[{"type":"text","text":"An enumeration of all accepted types of highways."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPHighwayType"}],"url":"\/documentation\/mapsindoors\/mphighwaytype"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class":{"role":"symbol","title":"MPRouteStep","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteStep"}],"abstract":[{"type":"text","text":"Route step model. A step is segment on a "},{"type":"codeVoice","code":"MPRouteLeg"},{"type":"text","text":" ("},{"type":"codeVoice","code":"MPRouteLeg"},{"type":"text","text":" is a segment on a "},{"type":"codeVoice","code":"MPRoute"},{"type":"text","text":"). The step contains start and end locations, distance and duration information, as well as navigational instructions."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteStep"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"highway"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"highway"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *"},{"kind":"identifier","text":"highway"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1highway\/title","value":"highway"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1highway\/fragments","value":[{"kind":"identifier","text":"highway"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType\/title","value":"MPHighwayType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType\/fragments","value":[{"kind":"identifier","text":"MPHighwayType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class\/title","value":"MPRouteStep"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class\/fragments","value":[{"kind":"identifier","text":"MPRouteStep"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}