{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routeContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mproutestep-swift.class\/routecontext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mproutestep-swift.class\/routecontext"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/routeContext","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Context of the step. May be "},{"type":"codeVoice","code":"InsideBuilding"},{"type":"text","text":", "},{"type":"codeVoice","code":"OutsideOnVenue"},{"type":"text","text":" or a custom context e.g. "},{"type":"codeVoice","code":"Security"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routeContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"routeContext","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPRouteStep(py)routeContext","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"routeContext"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/routeContext":{"role":"symbol","title":"routeContext","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routeContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Context of the step. May be "},{"type":"codeVoice","code":"InsideBuilding"},{"type":"text","text":", "},{"type":"codeVoice","code":"OutsideOnVenue"},{"type":"text","text":" or a custom context e.g. "},{"type":"codeVoice","code":"Security"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/routeContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"routeContext"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/routecontext"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class":{"role":"symbol","title":"MPRouteStep","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteStep"}],"abstract":[{"type":"text","text":"Route step model. A step is segment on a "},{"type":"codeVoice","code":"MPRouteLeg"},{"type":"text","text":" ("},{"type":"codeVoice","code":"MPRouteLeg"},{"type":"text","text":" is a segment on a "},{"type":"codeVoice","code":"MPRoute"},{"type":"text","text":"). The step contains start and end locations, distance and duration information, as well as navigational instructions."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteStep"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"routeContext"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"routeContext"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString<Optional>","preciseIdentifier":"c:Q$objc(cs)NSStringobjc(pl)Optional"},{"kind":"text","text":" *"},{"kind":"identifier","text":"routeContext"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1routeContext\/title","value":"routeContext"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1routeContext\/fragments","value":[{"kind":"identifier","text":"routeContext"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class\/title","value":"MPRouteStep"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class\/fragments","value":[{"kind":"identifier","text":"MPRouteStep"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}