{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transit_details"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTransitDetails","preciseIdentifier":"c:objc(cs)MPTransitDetails","text":"MPTransitDetails"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mproutestep-swift.class\/transit_details"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mproutestep-swift.class\/transit_details"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/transit_details","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Transit details. May apply for travel mode "},{"type":"codeVoice","code":"transit"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transit_details"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MPTransitDetails","preciseIdentifier":"c:objc(cs)MPTransitDetails"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"title":"transit_details","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPRouteStep(py)transit_details","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"transit_details"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class":{"role":"symbol","title":"MPRouteStep","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteStep"}],"abstract":[{"type":"text","text":"Route step model. A step is segment on a "},{"type":"codeVoice","code":"MPRouteLeg"},{"type":"text","text":" ("},{"type":"codeVoice","code":"MPRouteLeg"},{"type":"text","text":" is a segment on a "},{"type":"codeVoice","code":"MPRoute"},{"type":"text","text":"). The step contains start and end locations, distance and duration information, as well as navigational instructions."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteStep"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/transit_details":{"role":"symbol","title":"transit_details","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transit_details"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MPTransitDetails","preciseIdentifier":"c:objc(cs)MPTransitDetails"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Transit details. May apply for travel mode "},{"type":"codeVoice","code":"transit"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/transit_details","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"transit_details"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/transit_details"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPTransitDetails":{"role":"symbol","title":"MPTransitDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPTransitDetails"}],"abstract":[{"type":"text","text":"Transit details information."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTransitDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPTransitDetails"}],"url":"\/documentation\/mapsindoors\/mptransitdetails"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"transit_details"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"transit_details"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"MPTransitDetails<Optional>","preciseIdentifier":"c:Q$objc(cs)MPTransitDetailsobjc(pl)Optional"},{"kind":"text","text":" *"},{"kind":"identifier","text":"transit_details"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class\/title","value":"MPRouteStep"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class\/fragments","value":[{"kind":"identifier","text":"MPRouteStep"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1transit_details\/title","value":"transit_details"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1transit_details\/fragments","value":[{"kind":"identifier","text":"transit_details"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTransitDetails\/title","value":"MPTransitDetails"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTransitDetails\/fragments","value":[{"kind":"identifier","text":"MPTransitDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}