{"metadata":{"modules":[{"name":"MapsIndoors"}],"title":"collisionHandling","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collisionHandling","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPCollisionHandling","preciseIdentifier":"c:@M@MapsIndoors@E@MPCollisionHandling","kind":"typeIdentifier"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPSolutionConfig(py)collisionHandling","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"collisionHandling"}]},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"collisionHandling","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling","preciseIdentifier":"c:@M@MapsIndoors@E@MPCollisionHandling","text":"MPCollisionHandling"}],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpsolutionconfig\/collisionhandling"]},{"paths":["\/documentation\/mapsindoors\/mpsolutionconfig\/collisionhandling"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/collisionHandling","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCollisionHandling":{"role":"symbol","navigatorTitle":[{"text":"MPCollisionHandling","kind":"identifier"}],"title":"MPCollisionHandling","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling","url":"\/documentation\/mapsindoors\/mpcollisionhandling","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPCollisionHandling","kind":"identifier"}],"abstract":[{"text":"The different ways to handle collisions of icons and labels on the map.","type":"text"}]},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"type":"image","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolutionConfig/collisionHandling":{"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpsolutionconfig\/collisionhandling","abstract":[],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/collisionHandling","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"collisionHandling","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@E@MPCollisionHandling","text":"MPCollisionHandling","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"collisionHandling","kind":"identifier"}],"title":"collisionHandling"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolutionConfig":{"type":"topic","kind":"symbol","url":"\/documentation\/mapsindoors\/mpsolutionconfig","abstract":[{"type":"text","text":"MPSolutionConfig is the way to access the Solution settings made in the MapsIndoors CMS."}],"title":"MPSolutionConfig","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSolutionConfig"}],"navigatorTitle":[{"kind":"identifier","text":"MPSolutionConfig"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"collisionHandling"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"collisionHandling","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling","preciseIdentifier":"c:@M@MapsIndoors@E@MPCollisionHandling","text":"MPCollisionHandling","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"collisionHandling","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling\/title","op":"replace","value":"MPCollisionHandling"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPCollisionHandling"}]},{"value":"collisionHandling","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig~1collisionHandling\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig~1collisionHandling\/fragments","value":[{"text":"collisionHandling","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig\/title","value":"MPSolutionConfig","op":"replace"},{"value":[{"text":"MPSolutionConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}