{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@MapsIndoors@objc(cs)MPTemperatureLiveUpdate(im)initWithLiveUpdate:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLiveUpdate:"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLiveUpdate:"}],"title":"initWithLiveUpdate:"},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTemperatureLiveUpdate\/initWithLiveUpdate:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithLiveUpdate:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate","text":"MPLiveUpdate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"withLiveUpdate","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTemperatureLiveUpdate"]]},"variants":[{"paths":["\/documentation\/mapsindoors\/mptemperatureliveupdate\/initwithliveupdate:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTemperatureLiveUpdate":{"title":"MPTemperatureLiveUpdate","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTemperatureLiveUpdate","kind":"symbol","abstract":[],"url":"\/documentation\/mapsindoors\/mptemperatureliveupdate","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPTemperatureLiveUpdate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPTemperatureLiveUpdate"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/getLiveUpdate(forDomainType:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getLiveUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forDomainType"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"MPLiveUpdate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate"},{"text":"?","kind":"text"}],"abstract":[{"text":"Get a live update based on a known domain type.","type":"text"}],"url":"\/documentation\/mapsindoors\/mplocation\/getliveupdate(fordomaintype:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getLiveUpdateForDomainType:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","type":"topic","required":true,"title":"getLiveUpdate(forDomainType:)","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveUpdate"}],"url":"\/documentation\/mapsindoors\/mpliveupdate","abstract":[{"text":"Model for a Live Update. Used in ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","type":"reference"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPLiveUpdate"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","title":"MPLiveUpdate","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTemperatureLiveUpdate/initWithLiveUpdate:":{"title":"initWithLiveUpdate:","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTemperatureLiveUpdate\/initWithLiveUpdate:","kind":"symbol","abstract":[],"url":"\/documentation\/mapsindoors\/mptemperatureliveupdate\/initwithliveupdate:","fragments":[{"kind":"text","text":"- "},{"text":"initWithLiveUpdate:","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"initWithLiveUpdate:","kind":"identifier"}]},"MapsPeopleWhite.png":{"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","alt":null}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MPTemperatureLiveUpdate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTemperatureLiveUpdate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTemperatureLiveUpdate\/fragments","value":[{"kind":"identifier","text":"MPTemperatureLiveUpdate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/title","op":"replace","value":"getLiveUpdateForDomainType:"},{"value":[{"text":"- ","kind":"text"},{"text":"getLiveUpdateForDomainType:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/title","value":"MPLiveUpdate"},{"value":[{"kind":"identifier","text":"MPLiveUpdate"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/fragments"}]}]}