{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mptemperatureliveupdate\/temperature"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mptemperatureliveupdate\/temperature"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTemperatureLiveUpdate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","externalID":"c:@M@MapsIndoors@objc(cs)MPTemperatureLiveUpdate(py)temperature","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"temperature"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation11MeasurementV","text":"Measurement","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSUnitTemperature","kind":"typeIdentifier","text":"UnitTemperature"},{"text":">","kind":"text"}],"symbolKind":"property","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"temperature","kind":"identifier"}],"title":"temperature"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTemperatureLiveUpdate\/temperature"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"temperature","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Measurement","preciseIdentifier":"s:10Foundation11MeasurementV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSUnitTemperature","kind":"typeIdentifier","text":"UnitTemperature"},{"kind":"text","text":"> { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"references":{"MapsPeopleWhite.png":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTemperatureLiveUpdate/temperature":{"type":"topic","role":"symbol","url":"\/documentation\/mapsindoors\/mptemperatureliveupdate\/temperature","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"temperature","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Measurement","preciseIdentifier":"s:10Foundation11MeasurementV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSUnitTemperature","text":"UnitTemperature"},{"text":">","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTemperatureLiveUpdate\/temperature","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"temperature"}],"title":"temperature"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTemperatureLiveUpdate":{"type":"topic","role":"symbol","url":"\/documentation\/mapsindoors\/mptemperatureliveupdate","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPTemperatureLiveUpdate"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTemperatureLiveUpdate","abstract":[],"navigatorTitle":[{"text":"MPTemperatureLiveUpdate","kind":"identifier"}],"title":"MPTemperatureLiveUpdate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"temperature","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"temperature"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSMeasurement","text":"NSMeasurement<NSUnitTemperature *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"temperature","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTemperatureLiveUpdate~1temperature\/title","op":"replace","value":"temperature"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTemperatureLiveUpdate~1temperature\/fragments","value":[{"kind":"identifier","text":"temperature"}],"op":"replace"},{"value":"MPTemperatureLiveUpdate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTemperatureLiveUpdate\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTemperatureLiveUpdate\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPTemperatureLiveUpdate"}]}]}]}