{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpbooking\/asdictionary()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpbooking\/asdictionary()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/asDictionary()"},"metadata":{"role":"symbol","externalID":"c:@M@MapsIndoors@objc(cs)MPBooking(im)asDictionary","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"asDictionary"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}],"symbolKind":"method","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"asDictionary"}],"title":"asDictionary()"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asDictionary","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"style":"warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"[INTERNAL - DO NOT USE]"}]}],"name":"Warning","type":"aside"}],"kind":"content"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking":{"navigatorTitle":[{"kind":"identifier","text":"MPBooking"}],"url":"\/documentation\/mapsindoors\/mpbooking","kind":"symbol","role":"symbol","title":"MPBooking","type":"topic","abstract":[{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking","type":"reference","isActive":true},{"text":" represents an existing booking object or a booking to be made.","type":"text"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/bookingId"},{"text":" will be non-","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" for an existing booking, and ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" for a booking to be made."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPBooking"}]},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","alt":null,"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/asDictionary()":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/asDictionary()","navigatorTitle":[{"kind":"identifier","text":"asDictionary"}],"url":"\/documentation\/mapsindoors\/mpbooking\/asdictionary()","title":"asDictionary()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asDictionary","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?","kind":"text"}],"kind":"symbol","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/bookingId":{"navigatorTitle":[{"kind":"identifier","text":"bookingId"}],"url":"\/documentation\/mapsindoors\/mpbooking\/bookingid","kind":"symbol","role":"symbol","title":"bookingId","type":"topic","abstract":[{"text":"The id of the Booking to be used for future references.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/bookingId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bookingId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"asDictionary","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"asDictionary","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id>"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"asDictionary"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking\/title","value":"MPBooking"},{"op":"replace","value":[{"text":"MPBooking","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking\/fragments"},{"value":"asDictionary","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1asDictionary()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1asDictionary()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asDictionary"}]},{"value":"bookingId","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1bookingId\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1bookingId\/fragments","value":[{"text":"bookingId","kind":"identifier"}],"op":"replace"}]}]}