{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"title":"init","externalID":"c:@M@MapsIndoors@objc(cs)MPBooking(im)init","symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/init"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking"]]},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbooking\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/bookingId":{"abstract":[{"type":"text","text":"The id of the Booking to be used for future references."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/bookingId","navigatorTitle":[{"kind":"identifier","text":"bookingId"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bookingId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/mapsindoors\/mpbooking\/bookingid","role":"symbol","type":"topic","kind":"symbol","title":"bookingId"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/init":{"abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/init","title":"init","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpbooking\/init"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking":{"title":"MPBooking","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking","navigatorTitle":[{"text":"MPBooking","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPBooking","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpbooking","role":"symbol","type":"topic","kind":"symbol","abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking"},{"type":"text","text":" represents an existing booking object or a booking to be made."},{"type":"text","text":" "},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/bookingId","type":"reference"},{"text":" will be non-","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" for an existing booking, and ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" for a booking to be made.","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1bookingId\/title","op":"replace","value":"bookingId"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1bookingId\/fragments","value":[{"text":"bookingId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking\/title","value":"MPBooking","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking\/fragments","value":[{"text":"MPBooking","kind":"identifier"}]}]}]}