{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/initWith(dictionary:)"},"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initWith","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dictionary"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":") -> "},{"text":"MPBooking","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:"}],"role":"symbol","modules":[{"name":"MapsIndoors"}],"title":"initWith(dictionary:)","externalID":"c:@M@MapsIndoors@objc(cs)MPBooking(im)initWithDictionary:","roleHeading":"Instance Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dictionary","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking","text":"MPBooking","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"[INTERNAL - DO NOT USE]"}],"type":"paragraph"}],"style":"warning","name":"Warning"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpbooking\/initwith(dictionary:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpbooking\/initwith(dictionary:)"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/initWith(dictionary:)":{"url":"\/documentation\/mapsindoors\/mpbooking\/initwith(dictionary:)","title":"initWith(dictionary:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/initWith(dictionary:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initWith","kind":"identifier"},{"kind":"text","text":"("},{"text":"dictionary","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking","text":"MPBooking","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"initWithDictionary:","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking":{"navigatorTitle":[{"kind":"identifier","text":"MPBooking"}],"role":"symbol","abstract":[{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking","isActive":true,"type":"reference"},{"type":"text","text":" represents an existing booking object or a booking to be made."},{"text":" ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/bookingId","isActive":true},{"type":"text","text":" will be non-"},{"type":"codeVoice","code":"nil"},{"text":" for an existing booking, and ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" for a booking to be made."}],"title":"MPBooking","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking","url":"\/documentation\/mapsindoors\/mpbooking","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPBooking","kind":"identifier"}]},"MapsPeopleWhite.png":{"type":"image","alt":null,"identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/bookingId":{"navigatorTitle":[{"kind":"identifier","text":"bookingId"}],"role":"symbol","abstract":[{"type":"text","text":"The id of the Booking to be used for future references."}],"title":"bookingId","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/bookingId","url":"\/documentation\/mapsindoors\/mpbooking\/bookingid","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bookingId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithDictionary:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithDictionary:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"MPBooking","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking"},{"text":" *) ","kind":"text"},{"text":"initWithDictionary:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"dictionary","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"initWithDictionary:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1initWith(dictionary:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1initWith(dictionary:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithDictionary:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking\/title","value":"MPBooking"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking\/fragments","value":[{"text":"MPBooking","kind":"identifier"}]},{"op":"replace","value":"bookingId","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1bookingId\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1bookingId\/fragments","value":[{"text":"bookingId","kind":"identifier"}]}]}]}