{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"latLngString"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Latitude\/logitude as comma separated string"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppoint-swift.class\/latlngstring()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppoint-swift.class\/latlngstring()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/latLngString()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get latitude\/logitude value as a string"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"latLngString"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"latLngString()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPPoint(im)latLngString","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"latLngString"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPPoint-swift.class":{"role":"symbol","title":"MPPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPoint"}],"abstract":[{"type":"text","text":"Basic point geometry class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPoint"}],"url":"\/documentation\/mapsindoors\/mppoint-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPPoint-swift.class/latLngString()":{"role":"symbol","title":"latLngString()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"latLngString"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Get latitude\/logitude value as a string"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class\/latLngString()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"latLngString"}],"url":"\/documentation\/mapsindoors\/mppoint-swift.class\/latlngstring()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"latLngString"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"latLngString"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"latLngString"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class\/title","value":"MPPoint"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class\/fragments","value":[{"kind":"identifier","text":"MPPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1latLngString()\/title","value":"latLngString"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class~1latLngString()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"latLngString"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}