{"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate\/datasetmanagerwillstartfetchingsyncsizes(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate\/datasetmanagerwillstartfetchingsyncsizes(_:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataSetManagerWillStartFetchingSyncSizes"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dataSetManager"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","kind":"typeIdentifier","text":"MPDataSetCacheManager"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"dataSetManager","content":[{"inlineContent":[{"type":"text","text":"Originator of the callback."}],"type":"paragraph"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManagerWillStartFetchingSyncSizes(_:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate"]]},"abstract":[{"type":"text","text":"Called when the DataSetManager starts determing sync sizes for its managed datasets."}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"dataSetManagerWillStartFetchingSyncSizes:"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManagerSizeDelegate(im)dataSetManagerWillStartFetchingSyncSizes:","roleHeading":"Instance Method","required":true,"modules":[{"name":"MapsIndoors"}],"symbolKind":"method","role":"symbol","title":"dataSetManagerWillStartFetchingSyncSizes(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dataSetManagerWillStartFetchingSyncSizes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MPDataSetCacheManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager"},{"text":")","kind":"text"}]},"references":{"MapsPeopleWhite.png":{"alt":null,"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager":{"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheManager"}],"kind":"symbol","title":"MPDataSetCacheManager","role":"symbol","navigatorTitle":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Data set manager class."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerSizeDelegate/dataSetManagerWillStartFetchingSyncSizes(_:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManagerWillStartFetchingSyncSizes(_:)","title":"dataSetManagerWillStartFetchingSyncSizes(_:)","url":"\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate\/datasetmanagerwillstartfetchingsyncsizes(_:)","kind":"symbol","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dataSetManagerWillStartFetchingSyncSizes:"}],"type":"topic","abstract":[{"text":"Called when the DataSetManager starts determing sync sizes for its managed datasets.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSetManagerWillStartFetchingSyncSizes","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","text":"MPDataSetCacheManager","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerSizeDelegate":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate","title":"MPDataSetCacheManagerSizeDelegate","url":"\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"}],"type":"topic","abstract":[{"text":"Delegate protocol for getting callbacks when determining the size af dataset syncs.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"dataSetManagerWillStartFetchingSyncSizes:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dataSetManagerWillStartFetchingSyncSizes:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"dataSetManagerWillStartFetchingSyncSizes:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCacheManager","kind":"typeIdentifier","text":"id<MPDataSetCacheManager>"},{"text":" *) ","kind":"text"},{"text":"dataSetManager","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title","value":"MPDataSetCacheManager"},{"value":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments"},{"op":"replace","value":"dataSetManagerWillStartFetchingSyncSizes:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate~1dataSetManagerWillStartFetchingSyncSizes(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate~1dataSetManagerWillStartFetchingSyncSizes(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"dataSetManagerWillStartFetchingSyncSizes:","kind":"identifier"}]},{"op":"replace","value":"MPDataSetCacheManagerSizeDelegate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}