{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataSetManagerDidFinishFetchingSyncSizes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"dataSetManager","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","text":"MPDataSetCacheManager","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"Originator of the callback.","type":"text"}],"type":"paragraph"}],"name":"dataSetManager"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate"]]},"abstract":[{"type":"text","text":"Called to indicate that the DataSetManager has finished determining sync sizes for all managed datasets."}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate\/datasetmanagerdidfinishfetchingsyncsizes(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate\/datasetmanagerdidfinishfetchingsyncsizes(_:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManagerDidFinishFetchingSyncSizes(_:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"dataSetManagerDidFinishFetchingSyncSizes","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPDataSetCacheManager","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"dataSetManagerDidFinishFetchingSyncSizes:","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManagerSizeDelegate(im)dataSetManagerDidFinishFetchingSyncSizes:","modules":[{"name":"MapsIndoors"}],"required":true,"role":"symbol","title":"dataSetManagerDidFinishFetchingSyncSizes(_:)","symbolKind":"method"},"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDataSetCacheManager","kind":"identifier"}],"abstract":[{"type":"text","text":"Data set manager class."}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","title":"MPDataSetCacheManager"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerSizeDelegate/dataSetManagerDidFinishFetchingSyncSizes(_:)":{"type":"topic","title":"dataSetManagerDidFinishFetchingSyncSizes(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSetManagerDidFinishFetchingSyncSizes","kind":"identifier"},{"kind":"text","text":"("},{"text":"MPDataSetCacheManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManagerDidFinishFetchingSyncSizes(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"dataSetManagerDidFinishFetchingSyncSizes:"}],"required":true,"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate\/datasetmanagerdidfinishfetchingsyncsizes(_:)","abstract":[{"text":"Called to indicate that the DataSetManager has finished determining sync sizes for all managed datasets.","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerSizeDelegate":{"type":"topic","title":"MPDataSetCacheManagerSizeDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPDataSetCacheManagerSizeDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate","abstract":[{"text":"Delegate protocol for getting callbacks when determining the size af dataset syncs.","type":"text"}]},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"dataSetManagerDidFinishFetchingSyncSizes:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"dataSetManagerDidFinishFetchingSyncSizes:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"dataSetManagerDidFinishFetchingSyncSizes:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCacheManager","text":"id<MPDataSetCacheManager>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"dataSetManager"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title","value":"MPDataSetCacheManager"},{"value":[{"kind":"identifier","text":"MPDataSetCacheManager"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate~1dataSetManagerDidFinishFetchingSyncSizes(_:)\/title","value":"dataSetManagerDidFinishFetchingSyncSizes:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dataSetManagerDidFinishFetchingSyncSizes:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate~1dataSetManagerDidFinishFetchingSyncSizes(_:)\/fragments"},{"value":"MPDataSetCacheManagerSizeDelegate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"}]}]}]}