{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate\/datasetmanager(_:didfetchsyncsizesfordataset:)"]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate\/datasetmanager(_:didfetchsyncsizesfordataset:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSetManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"dataSetManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheManager","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager"},{"text":", ","kind":"text"},{"text":"didFetchSyncSizesForDataSet","kind":"externalParam"},{"kind":"text","text":" "},{"text":"dataset","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache","text":"MPDataSetCache","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Originator of the callback.","type":"text"}]}],"name":"dataSetManager"},{"content":[{"inlineContent":[{"text":"The dataset for which sync size has being determined.","type":"text"}],"type":"paragraph"}],"name":"dataset"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManager(_:didFetchSyncSizesForDataSet:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"MapsIndoors"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManagerSizeDelegate(im)dataSetManager:didFetchSyncSizesForDataSet:","required":true,"title":"dataSetManager(_:didFetchSyncSizesForDataSet:)","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"dataSetManager:didFetchSyncSizesForDataSet:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSetManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","text":"MPDataSetCacheManager"},{"kind":"text","text":", "},{"text":"didFetchSyncSizesForDataSet","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache"},{"text":")","kind":"text"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate"]]},"abstract":[{"type":"text","text":"Called to indicate the fnish of fetching sync size for a single dataset."}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCache":{"navigatorTitle":[{"text":"MPDataSetCache","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Data set cache class.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache","type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcache","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDataSetCache","kind":"identifier"}],"title":"MPDataSetCache"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerSizeDelegate":{"kind":"symbol","role":"symbol","title":"MPDataSetCacheManagerSizeDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate","navigatorTitle":[{"text":"MPDataSetCacheManagerSizeDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate protocol for getting callbacks when determining the size af dataset syncs."}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerSizeDelegate/dataSetManager(_:didFetchSyncSizesForDataSet:)":{"kind":"symbol","role":"symbol","title":"dataSetManager(_:didFetchSyncSizesForDataSet:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataSetManager"},{"kind":"text","text":"("},{"text":"MPDataSetCacheManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager"},{"kind":"text","text":", "},{"text":"didFetchSyncSizesForDataSet","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","kind":"typeIdentifier","text":"MPDataSetCache"},{"kind":"text","text":")"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate\/datasetmanager(_:didfetchsyncsizesfordataset:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManager(_:didFetchSyncSizesForDataSet:)","navigatorTitle":[{"text":"dataSetManager:didFetchSyncSizesForDataSet:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called to indicate the fnish of fetching sync size for a single dataset."}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","title":"MPDataSetCacheManager","role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager","navigatorTitle":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheManager"}],"kind":"symbol","abstract":[{"type":"text","text":"Data set manager class."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"dataSetManager:didFetchSyncSizesForDataSet:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dataSetManager:didFetchSyncSizesForDataSet:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"dataSetManager:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<MPDataSetCacheManager>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCacheManager"},{"text":" *) ","kind":"text"},{"text":"dataSetManager","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didFetchSyncSizesForDataSet:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCache","text":"id<MPDataSetCache>"},{"text":" *) ","kind":"text"},{"text":"dataset","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"MPDataSetCache","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPDataSetCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate\/title","value":"MPDataSetCacheManagerSizeDelegate"},{"value":[{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate\/fragments","op":"replace"},{"op":"replace","value":"dataSetManager:didFetchSyncSizesForDataSet:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate~1dataSetManager(_:didFetchSyncSizesForDataSet:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate~1dataSetManager(_:didFetchSyncSizesForDataSet:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dataSetManager:didFetchSyncSizesForDataSet:"}]},{"value":"MPDataSetCacheManager","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title"},{"value":[{"kind":"identifier","text":"MPDataSetCacheManager"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}