{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSetManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"dataSetManager"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","kind":"typeIdentifier","text":"MPDataSetCacheManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"willStartFetchingSyncSizesForDataSet"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"dataset"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache","kind":"typeIdentifier","text":"MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"dataSetManager","content":[{"type":"paragraph","inlineContent":[{"text":"Originator of the callback.","type":"text"}]}]},{"name":"dataset","content":[{"inlineContent":[{"type":"text","text":"The dataset for which sync size is being determined."}],"type":"paragraph"}]}]}],"abstract":[{"type":"text","text":"Called to indicate the start of fetching sync size for a single dataset."}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManager(_:willStartFetchingSyncSizesForDataSet:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate\/datasetmanager(_:willstartfetchingsyncsizesfordataset:)"]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate\/datasetmanager(_:willstartfetchingsyncsizesfordataset:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"dataSetManager","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","kind":"typeIdentifier","text":"MPDataSetCacheManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"willStartFetchingSyncSizesForDataSet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","text":"MPDataSetCache"},{"text":")","kind":"text"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManagerSizeDelegate(im)dataSetManager:willStartFetchingSyncSizesForDataSet:","roleHeading":"Instance Method","modules":[{"name":"MapsIndoors"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dataSetManager:willStartFetchingSyncSizesForDataSet:"}],"symbolKind":"method","title":"dataSetManager(_:willStartFetchingSyncSizesForDataSet:)"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCache":{"url":"\/documentation\/mapsindoors\/mpdatasetcache","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDataSetCache","kind":"identifier"}],"kind":"symbol","title":"MPDataSetCache","role":"symbol","navigatorTitle":[{"text":"MPDataSetCache","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Data set cache class."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerSizeDelegate/dataSetManager(_:willStartFetchingSyncSizesForDataSet:)":{"abstract":[{"type":"text","text":"Called to indicate the start of fetching sync size for a single dataset."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManager(_:willStartFetchingSyncSizesForDataSet:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dataSetManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MPDataSetCacheManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"willStartFetchingSyncSizesForDataSet"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","kind":"typeIdentifier","text":"MPDataSetCache"},{"text":")","kind":"text"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate\/datasetmanager(_:willstartfetchingsyncsizesfordataset:)","kind":"symbol","title":"dataSetManager(_:willStartFetchingSyncSizesForDataSet:)","type":"topic","navigatorTitle":[{"text":"dataSetManager:willStartFetchingSyncSizesForDataSet:","kind":"identifier"}]},"MapsPeopleWhite.png":{"alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerSizeDelegate":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate","title":"MPDataSetCacheManagerSizeDelegate","url":"\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"}],"type":"topic","abstract":[{"text":"Delegate protocol for getting callbacks when determining the size af dataset syncs.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager":{"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheManager"}],"kind":"symbol","title":"MPDataSetCacheManager","role":"symbol","navigatorTitle":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Data set manager class."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"dataSetManager:willStartFetchingSyncSizesForDataSet:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dataSetManager:willStartFetchingSyncSizesForDataSet:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"dataSetManager:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<MPDataSetCacheManager>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCacheManager"},{"text":" *) ","kind":"text"},{"text":"dataSetManager","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"willStartFetchingSyncSizesForDataSet:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCache","text":"id<MPDataSetCache>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"dataset"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MPDataSetCache","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPDataSetCache"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate~1dataSetManager(_:willStartFetchingSyncSizesForDataSet:)\/title","value":"dataSetManager:willStartFetchingSyncSizesForDataSet:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate~1dataSetManager(_:willStartFetchingSyncSizesForDataSet:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"dataSetManager:willStartFetchingSyncSizesForDataSet:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MPDataSetCacheManagerSizeDelegate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate\/fragments","value":[{"text":"MPDataSetCacheManagerSizeDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title","value":"MPDataSetCacheManager","op":"replace"},{"op":"replace","value":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments"}]}]}