{"sections":[],"metadata":{"navigatorTitle":[{"text":"authClients","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPAuthDetails(py)authClients","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"authClients"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MPAuthClientInfo","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPAuthClientInfo"},{"kind":"text","text":"]"}],"roleHeading":"Instance Property","title":"authClients","modules":[{"name":"MapsIndoors"}],"required":true},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/mapsindoors\/mpauthdetails\/authclients"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpauthdetails\/authclients"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authClients"},{"text":": [","kind":"text"},{"text":"MPAuthClientInfo","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthClientInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPAuthClientInfo"},{"text":"] { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails\/authClients","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAuthDetails":{"url":"\/documentation\/mapsindoors\/mpauthdetails","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The OAuth2 details to be used for performing an OAuth2 login flow in an app using MapsIndoors."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails","title":"MPAuthDetails","navigatorTitle":[{"kind":"identifier","text":"MPAuthDetails"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPAuthDetails"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAuthClientInfo":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthClientInfo","abstract":[],"url":"\/documentation\/mapsindoors\/mpauthclientinfo","navigatorTitle":[{"kind":"identifier","text":"MPAuthClientInfo"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPAuthClientInfo","kind":"identifier"}],"title":"MPAuthClientInfo"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","alt":null,"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAuthDetails/authClients":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails\/authClients","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"authClients","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MPAuthClientInfo","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPAuthClientInfo"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"authClients","kind":"identifier"}],"title":"authClients","url":"\/documentation\/mapsindoors\/mpauthdetails\/authclients","required":true,"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"authClients","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"authClients","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<id<MPAuthClientInfo>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"authClients","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails\/title","value":"MPAuthDetails"},{"value":[{"kind":"identifier","text":"MPAuthDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails\/fragments"},{"value":"MPAuthClientInfo","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthClientInfo\/title","op":"replace"},{"op":"replace","value":[{"text":"MPAuthClientInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthClientInfo\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails~1authClients\/title","value":"authClients","op":"replace"},{"value":[{"kind":"identifier","text":"authClients"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails~1authClients\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}