{"variants":[{"paths":["\/documentation\/mapsindoors\/mpauthdetails\/authissuer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpauthdetails\/authissuer"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails"]]},"metadata":{"navigatorTitle":[{"text":"authIssuer","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPAuthDetails(py)authIssuer","roleHeading":"Instance Property","required":true,"modules":[{"name":"MapsIndoors"}],"symbolKind":"property","role":"symbol","title":"authIssuer","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authIssuer","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authIssuer"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The URL to the Authentication Issuer.","type":"text"}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails\/authIssuer","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAuthDetails":{"abstract":[{"type":"text","text":"The OAuth2 details to be used for performing an OAuth2 login flow in an app using MapsIndoors."}],"type":"topic","title":"MPAuthDetails","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPAuthDetails","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails","url":"\/documentation\/mapsindoors\/mpauthdetails","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPAuthDetails"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAuthDetails/authIssuer":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authIssuer","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"authIssuer","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpauthdetails\/authissuer","kind":"symbol","title":"authIssuer","abstract":[{"type":"text","text":"The URL to the Authentication Issuer."}],"required":true,"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails\/authIssuer"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"authIssuer","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"authIssuer","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"authIssuer","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails\/title","value":"MPAuthDetails","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MPAuthDetails"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails\/fragments"},{"op":"replace","value":"authIssuer","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails~1authIssuer\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails~1authIssuer\/fragments","op":"replace","value":[{"kind":"identifier","text":"authIssuer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}