{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior\/showInfoWindow","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpmapbehavior\/showinfowindow"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpmapbehavior\/showinfowindow"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"showInfoWindow","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","title":"showInfoWindow","navigatorTitle":[{"text":"showInfoWindow","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPMapBehavior(py)showInfoWindow","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"showInfoWindow","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"required":true,"modules":[{"name":"MapsIndoors"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior"]]},"references":{"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapBehavior":{"title":"MPMapBehavior","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPMapBehavior","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpmapbehavior","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MPMapBehavior","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior","abstract":[]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapBehavior/showInfoWindow":{"title":"showInfoWindow","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior\/showInfoWindow","navigatorTitle":[{"text":"showInfoWindow","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpmapbehavior\/showinfowindow","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showInfoWindow","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"showInfoWindow","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"showInfoWindow","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"text":"showInfoWindow","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapBehavior\/title","op":"replace","value":"MPMapBehavior"},{"value":[{"text":"MPMapBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapBehavior\/fragments"},{"value":"showInfoWindow","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapBehavior~1showInfoWindow\/title"},{"op":"replace","value":[{"text":"showInfoWindow","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapBehavior~1showInfoWindow\/fragments"}]}]}