{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"agencies","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitAgency","text":"MPTransitAgency","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitAgency"},{"text":"] { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapsindoors\/mptransitline\/agencies"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mptransitline\/agencies"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/agencies","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An array of "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitAgency","isActive":true},{"text":" objects that each provide information about the operator of the line.","type":"text"}],"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPTransitLine(py)agencies","modules":[{"name":"MapsIndoors"}],"required":true,"symbolKind":"property","title":"agencies","role":"symbol","navigatorTitle":[{"text":"agencies","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"agencies"},{"text":": [","kind":"text"},{"text":"MPTransitAgency","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitAgency"},{"text":"]","kind":"text"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitLine":{"abstract":[{"type":"text","text":"Transit line information."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine","type":"topic","url":"\/documentation\/mapsindoors\/mptransitline","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPTransitLine"}],"kind":"symbol","title":"MPTransitLine","role":"symbol","navigatorTitle":[{"text":"MPTransitLine","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitAgency":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitAgency","type":"topic","url":"\/documentation\/mapsindoors\/mptransitagency","abstract":[{"type":"text","text":"Transit agency information."}],"navigatorTitle":[{"text":"MPTransitAgency","kind":"identifier"}],"title":"MPTransitAgency","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPTransitAgency"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitLine/agencies":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"agencies"},{"text":": [","kind":"text"},{"text":"MPTransitAgency","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitAgency"},{"text":"]","kind":"text"}],"url":"\/documentation\/mapsindoors\/mptransitline\/agencies","title":"agencies","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/agencies","navigatorTitle":[{"kind":"identifier","text":"agencies"}],"type":"topic","abstract":[{"type":"text","text":"An array of "},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitAgency","type":"reference"},{"type":"text","text":" objects that each provide information about the operator of the line."}],"required":true,"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"agencies"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"agencies","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSArray<id<MPTransitAgency>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"agencies","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MPTransitLine","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine\/fragments","op":"replace","value":[{"text":"MPTransitLine","kind":"identifier"}]},{"value":"MPTransitAgency","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitAgency\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitAgency\/fragments","value":[{"text":"MPTransitAgency","kind":"identifier"}],"op":"replace"},{"value":"agencies","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1agencies\/title"},{"value":[{"kind":"identifier","text":"agencies"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1agencies\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}