{"abstract":[{"type":"text","text":"URL for the icon associated with this line."}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@MapsIndoors@objc(pl)MPTransitLine(py)icon","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"modules":[{"name":"MapsIndoors"}],"title":"icon","required":true,"navigatorTitle":[{"text":"icon","kind":"identifier"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/icon"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"icon"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mptransitline\/icon"]},{"paths":["\/documentation\/mapsindoors\/mptransitline\/icon"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitLine/icon":{"role":"symbol","abstract":[{"type":"text","text":"URL for the icon associated with this line."}],"kind":"symbol","required":true,"url":"\/documentation\/mapsindoors\/mptransitline\/icon","navigatorTitle":[{"kind":"identifier","text":"icon"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/icon","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"icon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"icon"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitLine":{"role":"symbol","title":"MPTransitLine","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mptransitline","abstract":[{"text":"Transit line information.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPTransitLine","kind":"identifier"}],"navigatorTitle":[{"text":"MPTransitLine","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine"},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"identifier":"MapsPeopleWhite.png","type":"image"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"icon"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"icon","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"icon","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"icon","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1icon\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"icon"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1icon\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine\/title","op":"replace","value":"MPTransitLine"},{"value":[{"kind":"identifier","text":"MPTransitLine"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}