{"abstract":[{"text":"The short name of this transit line. This will normally be a line number, such as “M7” or “355”.","type":"text"}],"variants":[{"paths":["\/documentation\/mapsindoors\/mptransitline\/short_name"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mptransitline\/short_name"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/short_name","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine"]]},"metadata":{"role":"symbol","modules":[{"name":"MapsIndoors"}],"title":"short_name","required":true,"externalID":"c:@M@MapsIndoors@objc(pl)MPTransitLine(py)short_name","navigatorTitle":[{"text":"short_name","kind":"identifier"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"short_name","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"short_name","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitLine":{"navigatorTitle":[{"text":"MPTransitLine","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine","url":"\/documentation\/mapsindoors\/mptransitline","title":"MPTransitLine","abstract":[{"type":"text","text":"Transit line information."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPTransitLine"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitLine/short_name":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"short_name","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"required":true,"abstract":[{"type":"text","text":"The short name of this transit line. This will normally be a line number, such as “M7” or “355”."}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/short_name","navigatorTitle":[{"text":"short_name","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapsindoors\/mptransitline\/short_name","title":"short_name"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","alt":null,"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"short_name","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"short_name","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"short_name","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine\/title","value":"MPTransitLine","op":"replace"},{"value":[{"kind":"identifier","text":"MPTransitLine"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine\/fragments"},{"op":"replace","value":"short_name","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1short_name\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1short_name\/fragments","op":"replace","value":[{"text":"short_name","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}