{"variants":[{"paths":["\/documentation\/mapsindoors\/mptransitline\/vehicle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mptransitline\/vehicle"]}],"kind":"symbol","metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPTransitLine(py)vehicle","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vehicle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPTransitVehicle","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitVehicle"}],"navigatorTitle":[{"kind":"identifier","text":"vehicle"}],"role":"symbol","modules":[{"name":"MapsIndoors"}],"required":true,"title":"vehicle"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine"]]},"abstract":[{"type":"text","text":"Type of vehicle used on this line. This may include the following properties:"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"vehicle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPTransitVehicle","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitVehicle","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitVehicle"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/vehicle","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitLine/vehicle":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"vehicle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitVehicle","text":"MPTransitVehicle"}],"required":true,"abstract":[{"type":"text","text":"Type of vehicle used on this line. This may include the following properties:"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/vehicle","navigatorTitle":[{"text":"vehicle","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/mapsindoors\/mptransitline\/vehicle","title":"vehicle"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitLine":{"navigatorTitle":[{"text":"MPTransitLine","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine","url":"\/documentation\/mapsindoors\/mptransitline","title":"MPTransitLine","abstract":[{"type":"text","text":"Transit line information."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPTransitLine"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitVehicle":{"url":"\/documentation\/mapsindoors\/mptransitvehicle","role":"symbol","abstract":[],"title":"MPTransitVehicle","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPTransitVehicle"}],"navigatorTitle":[{"kind":"identifier","text":"MPTransitVehicle"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitVehicle"},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"type":"image","alt":null,"identifier":"MapsPeopleWhite.png"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"vehicle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"vehicle"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPTransitVehicle","kind":"typeIdentifier","text":"id<MPTransitVehicle>"},{"text":" * ","kind":"text"},{"text":"vehicle","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1vehicle\/title","value":"vehicle"},{"op":"replace","value":[{"kind":"identifier","text":"vehicle"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1vehicle\/fragments"},{"value":"MPTransitLine","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine\/fragments","value":[{"kind":"identifier","text":"MPTransitLine"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitVehicle\/title","op":"replace","value":"MPTransitVehicle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitVehicle\/fragments","value":[{"kind":"identifier","text":"MPTransitVehicle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}