{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"required","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"points","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"},{"text":"])","kind":"text"}],"languages":["swift"]}]}],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"points"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPoints:"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"init","externalID":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon(im)initWithPoints:","roleHeading":"Initializer","role":"symbol","title":"init(points:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon\/init(points:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpgeopolygon\/init(points:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpgeopolygon\/init(points:)"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPolygon/init(points:)":{"navigatorTitle":[{"text":"initWithPoints:","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon\/init(points:)","title":"init(points:)","role":"symbol","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"points","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":"])"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpgeopolygon\/init(points:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPolygon":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon","title":"MPGeoPolygon","role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpgeopolygon","navigatorTitle":[{"text":"MPGeoPolygon","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPGeoPolygon","kind":"identifier"}],"kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithPoints:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPoints:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithPoints:"},{"text":"(","kind":"text"},{"text":"NSArray<NSValue *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"points"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon~1init(points:)\/title","value":"initWithPoints:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon~1init(points:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPoints:"}]},{"value":"MPGeoPolygon","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon\/fragments","value":[{"text":"MPGeoPolygon","kind":"identifier"}]}]}]}