{"variants":[{"paths":["\/documentation\/mapsindoors\/mpgeopolygon\/points"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpgeopolygon\/points"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon\/points"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon"]]},"metadata":{"role":"symbol","modules":[{"name":"MapsIndoors"}],"title":"points","externalID":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon(py)points","navigatorTitle":[{"kind":"identifier","text":"points"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"points","kind":"identifier"},{"text":": [","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"},{"kind":"text","text":"] { get }"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPolygon":{"url":"\/documentation\/mapsindoors\/mpgeopolygon","kind":"symbol","navigatorTitle":[{"text":"MPGeoPolygon","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon","title":"MPGeoPolygon","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeoPolygon"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPolygon/points":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"points"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"},{"text":"]","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon\/points","type":"topic","abstract":[],"url":"\/documentation\/mapsindoors\/mpgeopolygon\/points","role":"symbol","navigatorTitle":[{"text":"points","kind":"identifier"}],"title":"points"},"MapsPeopleWhite.png":{"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"points"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"points"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"points"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon\/title","value":"MPGeoPolygon","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon\/fragments","value":[{"text":"MPGeoPolygon","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon~1points\/title","value":"points"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon~1points\/fragments","op":"replace","value":[{"kind":"identifier","text":"points"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}