{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"MPGeometryProtocol.polygon","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"polygon","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"polygon","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon","text":"MPGeoPolygon","kind":"typeIdentifier"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon(py)polygon","modules":[{"name":"MapsIndoors"}],"roleHeading":"Instance Property","symbolKind":"property","title":"polygon"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon\/polygon"},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"polygon","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon","text":"MPGeoPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpgeopolygon\/polygon"]},{"paths":["\/documentation\/mapsindoors\/mpgeopolygon\/polygon"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPolygon/polygon":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon\/polygon","title":"polygon","navigatorTitle":[{"text":"polygon","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"polygon","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon","kind":"typeIdentifier","text":"MPGeoPolygon"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpgeopolygon\/polygon","role":"symbol"},"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPolygon":{"abstract":[],"url":"\/documentation\/mapsindoors\/mpgeopolygon","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPGeoPolygon","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPGeoPolygon"}],"title":"MPGeoPolygon"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"polygon","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"polygon"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon","text":"MPGeoPolygon","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon"},{"text":" * ","kind":"text"},{"text":"polygon","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"value":"polygon","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon~1polygon\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon~1polygon\/fragments","value":[{"text":"polygon","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon\/title","value":"MPGeoPolygon","op":"replace"},{"value":[{"kind":"identifier","text":"MPGeoPolygon"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon\/fragments"}]}]}