{"metadata":{"externalID":"c:@M@MapsIndoors@objc(cs)MPLiveTopicCriteria(py)hash","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"symbolKind":"property","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"title":"hash"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mplivetopiccriteria\/hash"]},{"paths":["\/documentation\/mapsindoors\/mplivetopiccriteria\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/hash","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveTopicCriteria/hash":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria\/hash","abstract":[],"kind":"symbol","title":"hash"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveTopicCriteria":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPLiveTopicCriteria","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria","navigatorTitle":[{"text":"MPLiveTopicCriteria","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria","abstract":[],"kind":"symbol","title":"MPLiveTopicCriteria"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"hash"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"hash"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"}]}],"kind":"declarations"}},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1hash\/title"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria~1hash\/fragments"},{"value":"MPLiveTopicCriteria","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria\/title"},{"value":[{"text":"MPLiveTopicCriteria","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}