{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layerType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mponlinetilelayer-swift.class\/layertype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mponlinetilelayer-swift.class\/layertype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPOnlineTileLayer-swift.class\/layerType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Layer type \/ identifier."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layerType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"layerType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPOnlineTileLayer(py)layerType","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"layerType"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPOnlineTileLayer-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPOnlineTileLayer-swift.class/layerType":{"role":"symbol","title":"layerType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layerType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Layer type \/ identifier."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPOnlineTileLayer-swift.class\/layerType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layerType"}],"url":"\/documentation\/mapsindoors\/mponlinetilelayer-swift.class\/layertype"},"doc://MapsIndoors/documentation/MapsIndoors/MPOnlineTileLayer-swift.class":{"role":"symbol","title":"MPOnlineTileLayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPOnlineTileLayer"}],"abstract":[{"type":"text","text":"Online tile layer. Used to serve a google map with a MapsPeople online tileservice."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPOnlineTileLayer-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPOnlineTileLayer"}],"url":"\/documentation\/mapsindoors\/mponlinetilelayer-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"layerType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"layerType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *"},{"kind":"identifier","text":"layerType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPOnlineTileLayer-swift.class~1layerType\/title","value":"layerType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPOnlineTileLayer-swift.class~1layerType\/fragments","value":[{"kind":"identifier","text":"layerType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPOnlineTileLayer-swift.class\/title","value":"MPOnlineTileLayer"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPOnlineTileLayer-swift.class\/fragments","value":[{"kind":"identifier","text":"MPOnlineTileLayer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}