{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"liveUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdate","preciseIdentifier":"c:objc(cs)MPLiveUpdate","text":"MPLiveUpdate"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/didreceive(_:)-409qk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/didreceive(_:)-409qk"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didReceive(_:)-409qk","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when a Live Update was recieved."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didReceiveLiveUpdate:"}],"role":"symbol","title":"didReceive(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLiveUpdate","preciseIdentifier":"c:objc(cs)MPLiveUpdate"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MPLiveDataManagerDelegate(im)didReceiveLiveUpdate:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerDelegate/didReceive(_:)-409qk":{"navigatorTitle":[{"kind":"identifier","text":"didReceiveLiveUpdate:"}],"role":"symbol","title":"didReceive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLiveUpdate","preciseIdentifier":"c:objc(cs)MPLiveUpdate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a Live Update was recieved."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didReceive(_:)-409qk","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/didreceive(_:)-409qk"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerDelegate":{"role":"symbol","title":"MPLiveDataManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManagerDelegate"}],"abstract":[{"type":"text","text":"Live Data Manager Delegate protocol. Conforming to this protocol makes it possible to get Live Updates, state changes, errors and other calls from MPLiveDataManager."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerDelegate"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerdelegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveUpdate":{"role":"symbol","title":"MPLiveUpdate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveUpdate"}],"abstract":[{"type":"text","text":"Model for a Live Update. Used in MPLiveDataManagerDelegate and MPLocation::getLiveUpdate()."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveUpdate"}],"url":"\/documentation\/mapsindoors\/mpliveupdate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didReceiveLiveUpdate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveLiveUpdate:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didReceiveLiveUpdate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdate","preciseIdentifier":"c:objc(cs)MPLiveUpdate","text":"MPLiveUpdate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"liveUpdate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1didReceive(_:)-409qk\/title","value":"didReceiveLiveUpdate:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1didReceive(_:)-409qk\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveLiveUpdate:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate\/title","value":"MPLiveDataManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveUpdate\/title","value":"MPLiveUpdate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveUpdate\/fragments","value":[{"kind":"identifier","text":"MPLiveUpdate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}