{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSubscribe"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"topic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria","text":"MPLiveTopicCriteria"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/didsubscribe(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/didsubscribe(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didSubscribe(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when a Topic Criteria has successfully been subscribed for Live Updates."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didSubscribe:"}],"role":"symbol","title":"didSubscribe(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSubscribe"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MPLiveDataManagerDelegate(im)didSubscribe:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerDelegate":{"role":"symbol","title":"MPLiveDataManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManagerDelegate"}],"abstract":[{"type":"text","text":"Live Data Manager Delegate protocol. Conforming to this protocol makes it possible to get Live Updates, state changes, errors and other calls from MPLiveDataManager."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerDelegate"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerdelegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria":{"role":"symbol","title":"MPLiveTopicCriteria","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Live Topic Criteria model used for subscriptions to Live Updates using MPLiveDataManager."},{"type":"text","text":" "},{"type":"text","text":"A Live Topic Criteria is hierarchical in the way it is defined, and its relation to MapsIndoors data is derivable by its 7 components: Dataset, Venue, Building, Floor, Room, Location and Domain Type."},{"type":"text","text":" "},{"type":"text","text":"All properties can be left out but datasetId will then default to the currently active dataset."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveTopicCriteria"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerDelegate/didSubscribe(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didSubscribe:"}],"role":"symbol","title":"didSubscribe(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSubscribe"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a Topic Criteria has successfully been subscribed for Live Updates."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didSubscribe(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/didsubscribe(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didSubscribe:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didSubscribe:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didSubscribe:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria","text":"MPLiveTopicCriteria"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"topic"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate\/title","value":"MPLiveDataManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria\/title","value":"MPLiveTopicCriteria"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria\/fragments","value":[{"kind":"identifier","text":"MPLiveTopicCriteria"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1didSubscribe(_:)\/title","value":"didSubscribe:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1didSubscribe(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didSubscribe:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}