{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState","preciseIdentifier":"c:@E@MPLiveDataManagerState","text":"MPLiveDataManagerState"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/didupdate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/didupdate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didUpdate(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the state of the Live Data Manager changes."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didUpdateState:"}],"role":"symbol","title":"didUpdate(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLiveDataManagerState","preciseIdentifier":"c:@E@MPLiveDataManagerState"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MPLiveDataManagerDelegate(im)didUpdateState:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerDelegate":{"role":"symbol","title":"MPLiveDataManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManagerDelegate"}],"abstract":[{"type":"text","text":"Live Data Manager Delegate protocol. Conforming to this protocol makes it possible to get Live Updates, state changes, errors and other calls from MPLiveDataManager."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerDelegate"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerdelegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerDelegate/didUpdate(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didUpdateState:"}],"role":"symbol","title":"didUpdate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLiveDataManagerState","preciseIdentifier":"c:@E@MPLiveDataManagerState"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the state of the Live Data Manager changes."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didUpdate(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/didupdate(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerState":{"role":"symbol","title":"MPLiveDataManagerState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManagerState"}],"abstract":[{"type":"text","text":"Enumeration of MPLiveDataManager states."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerState"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerstate"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didUpdateState:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdateState:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didUpdateState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState","preciseIdentifier":"c:@E@MPLiveDataManagerState","text":"MPLiveDataManagerState"},{"kind":"text","text":")"},{"kind":"internalParam","text":"state"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate\/title","value":"MPLiveDataManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1didUpdate(_:)\/title","value":"didUpdateState:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1didUpdate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdateState:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState\/title","value":"MPLiveDataManagerState"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}