{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unsubscription error."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/onerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/onerror(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/onError(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when an error occurs. If the error is due to lack of network connectivity, the Live Data Manager will automatically do reconnection attempts."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onError:"}],"role":"symbol","title":"onError(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MPLiveDataManagerDelegate(im)onError:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerDelegate/onError(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onError:"}],"role":"symbol","title":"onError(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when an error occurs. If the error is due to lack of network connectivity, the Live Data Manager will automatically do reconnection attempts."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/onError(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/onerror(_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerDelegate":{"role":"symbol","title":"MPLiveDataManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManagerDelegate"}],"abstract":[{"type":"text","text":"Live Data Manager Delegate protocol. Conforming to this protocol makes it possible to get Live Updates, state changes, errors and other calls from MPLiveDataManager."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerDelegate"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onError:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1onError(_:)\/title","value":"onError:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1onError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onError:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate\/title","value":"MPLiveDataManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}