{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"layer"},{"kind":"text","text":" "},{"kind":"internalParam","text":"layerType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mponlinetilelayer\/init(layer:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mponlinetilelayer\/init(layer:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPOnlineTileLayer\/init(layer:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Instantiate using a layer type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"init(layer:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)MPOnlineTileLayer(im)initWithLayer:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLayer:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPOnlineTileLayer"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPOnlineTileLayer":{"role":"symbol","title":"MPOnlineTileLayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPOnlineTileLayer"}],"abstract":[{"type":"text","text":"Online tile layer. Used to serve a google map with a MapsPeople online tileservice."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPOnlineTileLayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPOnlineTileLayer"}],"url":"\/documentation\/mapsindoors\/mponlinetilelayer"},"doc://MapsIndoors/documentation/MapsIndoors/MPOnlineTileLayer/init(layer:)":{"role":"symbol","title":"init(layer:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Instantiate using a layer type."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPOnlineTileLayer\/init(layer:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLayer:"}],"url":"\/documentation\/mapsindoors\/mponlinetilelayer\/init(layer:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithLayer:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLayer:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLayer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"layerType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPOnlineTileLayer\/title","value":"MPOnlineTileLayer"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPOnlineTileLayer\/fragments","value":[{"kind":"identifier","text":"MPOnlineTileLayer"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPOnlineTileLayer~1init(layer:)\/title","value":"initWithLayer:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPOnlineTileLayer~1init(layer:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLayer:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}