{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSTileLayer","preciseIdentifier":"c:objc(cs)GMSTileLayer"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mponlinetilelayer\/layer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mponlinetilelayer\/layer"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPOnlineTileLayer\/layer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The google GMSTileLayer object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSTileLayer","preciseIdentifier":"c:objc(cs)GMSTileLayer"},{"kind":"text","text":"?"}],"title":"layer","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPOnlineTileLayer(py)layer","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"layer"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPOnlineTileLayer"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPOnlineTileLayer":{"role":"symbol","title":"MPOnlineTileLayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPOnlineTileLayer"}],"abstract":[{"type":"text","text":"Online tile layer. Used to serve a google map with a MapsPeople online tileservice."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPOnlineTileLayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPOnlineTileLayer"}],"url":"\/documentation\/mapsindoors\/mponlinetilelayer"},"doc://MapsIndoors/documentation/MapsIndoors/MPOnlineTileLayer/layer":{"role":"symbol","title":"layer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSTileLayer","preciseIdentifier":"c:objc(cs)GMSTileLayer"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The google GMSTileLayer object."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPOnlineTileLayer\/layer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layer"}],"url":"\/documentation\/mapsindoors\/mponlinetilelayer\/layer"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"layer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"layer"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"GMSTileLayer","preciseIdentifier":"c:objc(cs)GMSTileLayer"},{"kind":"text","text":" *"},{"kind":"identifier","text":"layer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPOnlineTileLayer\/title","value":"MPOnlineTileLayer"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPOnlineTileLayer\/fragments","value":[{"kind":"identifier","text":"MPOnlineTileLayer"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPOnlineTileLayer~1layer\/title","value":"layer"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPOnlineTileLayer~1layer\/fragments","value":[{"kind":"identifier","text":"layer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}