{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"intersectionAreaBetweenBounds"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"b1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andBounds"},{"kind":"text","text":" "},{"kind":"internalParam","text":"b2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbuildingdataset\/intersectionareabetweenbounds(_:andbounds:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbuildingdataset\/intersectionareabetweenbounds(_:andbounds:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/intersectionAreaBetweenBounds(_:andBounds:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get the intersection area on two GMSCoordinateBounds."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"intersectionAreaBetweenBounds"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andBounds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"intersectionAreaBetweenBounds(_:andBounds:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPBuildingDataset(im)intersectionAreaBetweenBounds:andBounds:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"intersectionAreaBetweenBounds:andBounds:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPBuildingDataset/intersectionAreaBetweenBounds(_:andBounds:)":{"role":"symbol","title":"intersectionAreaBetweenBounds(_:andBounds:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"intersectionAreaBetweenBounds"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andBounds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Get the intersection area on two GMSCoordinateBounds."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/intersectionAreaBetweenBounds(_:andBounds:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"intersectionAreaBetweenBounds:andBounds:"}],"url":"\/documentation\/mapsindoors\/mpbuildingdataset\/intersectionareabetweenbounds(_:andbounds:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuildingDataset":{"role":"symbol","title":"MPBuildingDataset","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuildingDataset"}],"abstract":[{"type":"text","text":"Collection of buildings with some retrieval and calculation functionality."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBuildingDataset"}],"url":"\/documentation\/mapsindoors\/mpbuildingdataset"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"intersectionAreaBetweenBounds:andBounds:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"intersectionAreaBetweenBounds:andBounds:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"identifier","text":"intersectionAreaBetweenBounds:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"b1"},{"kind":"text","text":" "},{"kind":"identifier","text":"andBounds:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"b2"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset~1intersectionAreaBetweenBounds(_:andBounds:)\/title","value":"intersectionAreaBetweenBounds:andBounds:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset~1intersectionAreaBetweenBounds(_:andBounds:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"intersectionAreaBetweenBounds:andBounds:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset\/title","value":"MPBuildingDataset"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset\/fragments","value":[{"kind":"identifier","text":"MPBuildingDataset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}