{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBuildingDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDelegate","preciseIdentifier":"c:objc(pl)MPBuildingDelegate","text":"MPBuildingDelegate"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate object"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbuildingdataset\/setbuildingdelegate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbuildingdataset\/setbuildingdelegate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/setBuildingDelegate(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Assign a delegate object to all buildings in the collection, this object will hold the onBuildingReady:shortName event method."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBuildingDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPBuildingDelegate","preciseIdentifier":"c:objc(pl)MPBuildingDelegate"},{"kind":"text","text":"?)"}],"title":"setBuildingDelegate(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPBuildingDataset(im)setBuildingDelegate:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"setBuildingDelegate:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPBuildingDataset/setBuildingDelegate(_:)":{"role":"symbol","title":"setBuildingDelegate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBuildingDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPBuildingDelegate","preciseIdentifier":"c:objc(pl)MPBuildingDelegate"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Assign a delegate object to all buildings in the collection, this object will hold the onBuildingReady:shortName event method."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset\/setBuildingDelegate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setBuildingDelegate:"}],"url":"\/documentation\/mapsindoors\/mpbuildingdataset\/setbuildingdelegate(_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuildingDelegate":{"role":"symbol","title":"MPBuildingDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuildingDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol that holds the building ready event method. Relevant when using offline mode, as it will take a while to load the database upon first app start."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBuildingDelegate"}],"url":"\/documentation\/mapsindoors\/mpbuildingdelegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuildingDataset":{"role":"symbol","title":"MPBuildingDataset","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuildingDataset"}],"abstract":[{"type":"text","text":"Collection of buildings with some retrieval and calculation functionality."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuildingDataset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBuildingDataset"}],"url":"\/documentation\/mapsindoors\/mpbuildingdataset"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setBuildingDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBuildingDelegate:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setBuildingDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSObject<MPBuildingDelegate>","preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)MPBuildingDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset~1setBuildingDelegate(_:)\/title","value":"setBuildingDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset~1setBuildingDelegate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBuildingDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDelegate\/title","value":"MPBuildingDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDelegate\/fragments","value":[{"kind":"identifier","text":"MPBuildingDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset\/title","value":"MPBuildingDataset"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuildingDataset\/fragments","value":[{"kind":"identifier","text":"MPBuildingDataset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}