{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"list"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class","preciseIdentifier":"c:objc(cs)MPBeacon","text":"MPBeacon"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbeaconcollection\/list"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbeaconcollection\/list"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconCollection\/list","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"list"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPBeacon","preciseIdentifier":"c:objc(cs)MPBeacon"},{"kind":"text","text":"]?"}],"title":"list","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPBeaconCollection(py)list","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"list"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconCollection"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeaconCollection":{"role":"symbol","title":"MPBeaconCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeaconCollection"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBeaconCollection"}],"url":"\/documentation\/mapsindoors\/mpbeaconcollection"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeacon-swift.class":{"role":"symbol","title":"MPBeacon","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeacon"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBeacon"}],"url":"\/documentation\/mapsindoors\/mpbeacon-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeaconCollection/list":{"role":"symbol","title":"list","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"list"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPBeacon","preciseIdentifier":"c:objc(cs)MPBeacon"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconCollection\/list","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"list"}],"url":"\/documentation\/mapsindoors\/mpbeaconcollection\/list"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"list"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"list"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<MPBeacon *><MPBeacon>","preciseIdentifier":"c:Q$objc(cs)NSArrayobjc(pl)MPBeacon"},{"kind":"text","text":" *"},{"kind":"identifier","text":"list"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconCollection\/title","value":"MPBeaconCollection"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconCollection\/fragments","value":[{"kind":"identifier","text":"MPBeaconCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class\/title","value":"MPBeacon"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class\/fragments","value":[{"kind":"identifier","text":"MPBeacon"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconCollection~1list\/title","value":"list"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconCollection~1list\/fragments","value":[{"kind":"identifier","text":"list"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}