{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"onView"},{"kind":"text","text":" "},{"kind":"internalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withText"},{"kind":"text","text":" "},{"kind":"internalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"view","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view to hold the indicator."}]}]},{"name":"text","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The text to display with the indicator."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mploadindicator\/init(onview:withtext:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mploadindicator\/init(onview:withtext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/init(onView:withText:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Instantiates the indicator and places the indicator in a view with a given text."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initOnView:withText:"}],"role":"symbol","title":"init(onView:withText:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"onView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"init","externalID":"c:objc(cs)MPLoadIndicator(im)initOnView:withText:","modules":[{"name":"MapsIndoors"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLoadIndicator/init(onView:withText:)":{"role":"symbol","title":"init(onView:withText:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"onView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Instantiates the indicator and places the indicator in a view with a given text."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/init(onView:withText:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initOnView:withText:"}],"url":"\/documentation\/mapsindoors\/mploadindicator\/init(onview:withtext:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLoadIndicator":{"role":"symbol","title":"MPLoadIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLoadIndicator"}],"abstract":[{"type":"text","text":"A basic load indicator, with the option to set a text."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLoadIndicator"}],"url":"\/documentation\/mapsindoors\/mploadindicator"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initOnView:withText:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initOnView:withText:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initOnView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"view"},{"kind":"text","text":" "},{"kind":"identifier","text":"withText:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"text"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator~1init(onView:withText:)\/title","value":"initOnView:withText:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator~1init(onView:withText:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initOnView:withText:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator\/title","value":"MPLoadIndicator"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator\/fragments","value":[{"kind":"identifier","text":"MPLoadIndicator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}