{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbeaconprovider-swift.class\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbeaconprovider-swift.class\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProvider-swift.class\/init()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)MPBeaconProvider(im)init","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProvider-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeaconProvider-swift.class":{"role":"symbol","title":"MPBeaconProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeaconProvider"}],"abstract":[{"type":"text","text":"Beacons provider that defines a delegate and a method to initiate fetching of Beacons from the provider."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProvider-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBeaconProvider"}],"url":"\/documentation\/mapsindoors\/mpbeaconprovider-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeaconProvider-swift.class/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProvider-swift.class\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/mapsindoors\/mpbeaconprovider-swift.class\/init()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProvider-swift.class\/title","value":"MPBeaconProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProvider-swift.class\/fragments","value":[{"kind":"identifier","text":"MPBeaconProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProvider-swift.class~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProvider-swift.class~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}