{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zIndex"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpfloor-swift.class\/zindex"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpfloor-swift.class\/zindex"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class\/zIndex","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Floor index"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zIndex"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"title":"zIndex","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPFloor(py)zIndex","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"zIndex"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPFloor-swift.class/zIndex":{"role":"symbol","title":"zIndex","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zIndex"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Floor index"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class\/zIndex","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"zIndex"}],"url":"\/documentation\/mapsindoors\/mpfloor-swift.class\/zindex"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloor-swift.class":{"role":"symbol","title":"MPFloor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloor"}],"abstract":[{"type":"text","text":"Floor data model. Holds the floor geometry, display name, z-index and id of the building it belongs to."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPFloor"}],"url":"\/documentation\/mapsindoors\/mpfloor-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"zIndex"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"zIndex"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSNumber<Optional>","preciseIdentifier":"c:Q$objc(cs)NSNumberobjc(pl)Optional"},{"kind":"text","text":" *"},{"kind":"identifier","text":"zIndex"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class~1zIndex\/title","value":"zIndex"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class~1zIndex\/fragments","value":[{"kind":"identifier","text":"zIndex"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class\/title","value":"MPFloor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class\/fragments","value":[{"kind":"identifier","text":"MPFloor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}