{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"animationDuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animationDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPFilterBehavior(py)animationDuration","navigatorTitle":[{"text":"animationDuration","kind":"identifier"}],"symbolKind":"property","role":"symbol","modules":[{"name":"MapsIndoors"}],"title":"animationDuration"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/mapsindoors\/mpfilterbehavior\/animationduration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpfilterbehavior\/animationduration"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior\/animationDuration"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"MPMapBehavior.animationDuration","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilterBehavior/default":{"url":"\/documentation\/mapsindoors\/mpfilterbehavior\/default","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Default filter behavior"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior\/default","title":"default","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`default`"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilterBehavior","kind":"typeIdentifier","text":"MPFilterBehavior"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilterBehavior/animationDuration":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animationDuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"role":"symbol","title":"animationDuration","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior\/animationDuration","navigatorTitle":[{"text":"animationDuration","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpfilterbehavior\/animationduration"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilterBehavior":{"navigatorTitle":[{"text":"MPFilterBehavior","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpfilterbehavior","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Filter behavior class that determines how a filter should be display on the map. Get the default behavior from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior\/default"},{"text":". The default behavior is no camera movement and no infowindow shown.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior","title":"MPFilterBehavior","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFilterBehavior"}]},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"animationDuration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"animationDuration","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"animationDuration","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilterBehavior~1animationDuration\/title","value":"animationDuration"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilterBehavior~1animationDuration\/fragments","op":"replace","value":[{"text":"animationDuration","kind":"identifier"}]},{"value":"MPFilterBehavior","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilterBehavior\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilterBehavior\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPFilterBehavior"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}