{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior\/showInfoWindow"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showInfoWindow"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpfilterbehavior\/showinfowindow"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpfilterbehavior\/showinfowindow"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior"]]},"abstract":[{"type":"text","text":"Whether "},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","type":"reference"},{"type":"text","text":" should show the info window if a filter only contains one Location. The default behavior is no info window is shown ("},{"type":"codeVoice","code":"false"},{"text":").","type":"text"}],"metadata":{"externalID":"c:@M@MapsIndoors@objc(cs)MPFilterBehavior(py)showInfoWindow","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"showInfoWindow","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"showInfoWindow","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"showInfoWindow"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilterBehavior":{"url":"\/documentation\/mapsindoors\/mpfilterbehavior","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPFilterBehavior","kind":"identifier"}],"navigatorTitle":[{"text":"MPFilterBehavior","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Filter behavior class that determines how the result of applying a filter should be displayed on the map. Get the default behavior from "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior\/default","isActive":true,"type":"reference"},{"text":". The default behavior is no camera movement and no infowindow shown.","type":"text"}],"title":"MPFilterBehavior","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilterBehavior/showInfoWindow":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior\/showInfoWindow","navigatorTitle":[{"kind":"identifier","text":"showInfoWindow"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpfilterbehavior\/showinfowindow","role":"symbol","abstract":[{"type":"text","text":"Whether "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"},{"text":" should show the info window if a filter only contains one Location. The default behavior is no info window is shown (","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":")."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"showInfoWindow","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"showInfoWindow","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilterBehavior/default":{"url":"\/documentation\/mapsindoors\/mpfilterbehavior\/default","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior\/default","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"`default`","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilterBehavior","text":"MPFilterBehavior","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Default filter behavior","type":"text"}],"title":"default","kind":"symbol"},"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"title":"MPMapControl","url":"\/documentation\/mapsindoors\/mpmapcontrol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"type":"topic","abstract":[{"text":"This is the control object for the visual representation of the MapsIndoors SDK.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"showInfoWindow","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"showInfoWindow"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"showInfoWindow","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilterBehavior\/title","op":"replace","value":"MPFilterBehavior"},{"value":[{"text":"MPFilterBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilterBehavior\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilterBehavior~1showInfoWindow\/title","value":"showInfoWindow"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilterBehavior~1showInfoWindow\/fragments","value":[{"text":"showInfoWindow","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MPMapControl","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title"},{"op":"replace","value":[{"text":"MPMapControl","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}