{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gmsPathsForHoles"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"GMSPath","preciseIdentifier":"c:objc(cs)GMSPath"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppolygongeometry\/gmspathsforholes()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppolygongeometry\/gmspathsforholes()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/gmsPathsForHoles()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Return an array of GMSPaths for the hole in the polygon."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gmsPathsForHoles"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"GMSPath","preciseIdentifier":"c:objc(cs)GMSPath"},{"kind":"text","text":"]?"}],"title":"gmsPathsForHoles()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPPolygonGeometry(im)gmsPathsForHoles","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"gmsPathsForHoles"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPPolygonGeometry/gmsPathsForHoles()":{"role":"symbol","title":"gmsPathsForHoles()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gmsPathsForHoles"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"GMSPath","preciseIdentifier":"c:objc(cs)GMSPath"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Return an array of GMSPaths for the hole in the polygon."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/gmsPathsForHoles()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gmsPathsForHoles"}],"url":"\/documentation\/mapsindoors\/mppolygongeometry\/gmspathsforholes()"},"doc://MapsIndoors/documentation/MapsIndoors/MPPolygonGeometry":{"role":"symbol","title":"MPPolygonGeometry","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPolygonGeometry"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPolygonGeometry"}],"url":"\/documentation\/mapsindoors\/mppolygongeometry"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"gmsPathsForHoles"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gmsPathsForHoles"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSArray<GMSPath *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"gmsPathsForHoles"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1gmsPathsForHoles()\/title","value":"gmsPathsForHoles"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1gmsPathsForHoles()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gmsPathsForHoles"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry\/title","value":"MPPolygonGeometry"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry\/fragments","value":[{"kind":"identifier","text":"MPPolygonGeometry"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}