{"metadata":{"modules":[{"name":"MapsIndoors"}],"role":"symbol","externalID":"c:@M@MapsIndoors@objc(cs)MPGeometryUtils(cm)closestPointOnLineSegmentWithPoint:lineStart:lineEnd:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"closestPointOnLineSegmentWithPoint:lineStart:lineEnd:"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"closestPointOnLineSegment"},{"text":"(","kind":"text"},{"text":"point","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"lineStart","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"lineEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"},{"text":") -> ","kind":"text"},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"}],"roleHeading":"Type Method","title":"closestPointOnLineSegment(point:lineStart:lineEnd:)"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/closestPointOnLineSegment(point:lineStart:lineEnd:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"closestPointOnLineSegment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"point","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"lineStart"},{"kind":"text","text":": "},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"lineEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpgeometryutils\/closestpointonlinesegment(point:linestart:lineend:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpgeometryutils\/closestpointonlinesegment(point:linestart:lineend:)"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils":{"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils","title":"MPGeometryUtils","navigatorTitle":[{"kind":"identifier","text":"MPGeometryUtils"}],"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/mapsindoors\/mpgeometryutils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPGeometryUtils","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/closestPointOnLineSegment(point:lineStart:lineEnd:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"closestPointOnLineSegment"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"point"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"text":"lineStart","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"lineEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"navigatorTitle":[{"kind":"identifier","text":"closestPointOnLineSegmentWithPoint:lineStart:lineEnd:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/closestPointOnLineSegment(point:lineStart:lineEnd:)","url":"\/documentation\/mapsindoors\/mpgeometryutils\/closestpointonlinesegment(point:linestart:lineend:)","abstract":[],"type":"topic","title":"closestPointOnLineSegment(point:lineStart:lineEnd:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image","alt":null}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"closestPointOnLineSegmentWithPoint:lineStart:lineEnd:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"+ "},{"text":"closestPointOnLineSegmentWithPoint:lineStart:lineEnd:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":") ","kind":"text"},{"text":"closestPointOnLineSegmentWithPoint:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"point","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"lineStart:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") "},{"text":"lineStart","kind":"internalParam"},{"kind":"text","text":" "},{"text":"lineEnd:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"lineEnd"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils\/title","value":"MPGeometryUtils"},{"op":"replace","value":[{"text":"MPGeometryUtils","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils\/fragments"},{"op":"replace","value":"closestPointOnLineSegmentWithPoint:lineStart:lineEnd:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils~1closestPointOnLineSegment(point:lineStart:lineEnd:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"closestPointOnLineSegmentWithPoint:lineStart:lineEnd:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils~1closestPointOnLineSegment(point:lineStart:lineEnd:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}