{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/mapsindoors\/mpgeometryutils\/computeboundingbox(coordinates:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"computeBoundingBox"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"coordinates"},{"text":": [","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds","text":"MPGeoBounds"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/computeBoundingBox(coordinates:)"},"metadata":{"externalID":"s:11MapsIndoors15MPGeometryUtilsC18computeBoundingBox11coordinatesAA11MPGeoBoundsCSaySo22CLLocationCoordinate2DVG_tFZ","modules":[{"name":"MapsIndoors"}],"symbolKind":"method","role":"symbol","title":"computeBoundingBox(coordinates:)","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"computeBoundingBox","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"coordinates"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"text":"MPGeoBounds","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds"}]},"references":{"MapsPeopleWhite.png":{"type":"image","alt":null,"identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/computeBoundingBox(coordinates:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"computeBoundingBox","kind":"identifier"},{"text":"(","kind":"text"},{"text":"coordinates","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","kind":"typeIdentifier","text":"MPGeoBounds"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/computeBoundingBox(coordinates:)","url":"\/documentation\/mapsindoors\/mpgeometryutils\/computeboundingbox(coordinates:)","abstract":[],"type":"topic","title":"computeBoundingBox(coordinates:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils":{"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils","title":"MPGeometryUtils","navigatorTitle":[{"kind":"identifier","text":"MPGeometryUtils"}],"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/mapsindoors\/mpgeometryutils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPGeometryUtils","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoBounds":{"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds","title":"MPGeoBounds","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPGeoBounds"}],"kind":"symbol","abstract":[],"url":"\/documentation\/mapsindoors\/mpgeobounds","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPGeoBounds","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MPGeometryUtils","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils\/title"},{"op":"replace","value":[{"text":"MPGeometryUtils","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoBounds\/title","value":"MPGeoBounds","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MPGeoBounds"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoBounds\/fragments"}]}]}