{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","title":"pointIntersectsPolygon(point:polygon:)","externalID":"s:11MapsIndoors15MPGeometryUtilsC22pointIntersectsPolygon0E07polygonSbAA10MPGeoPointC_AA0iG0CtFZ","roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"MapsIndoors"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pointIntersectsPolygon","kind":"identifier"},{"text":"(","kind":"text"},{"text":"point","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MPGeoPoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPoint"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPGeoPolygon","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/pointIntersectsPolygon(point:polygon:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pointIntersectsPolygon"},{"kind":"text","text":"("},{"kind":"externalParam","text":"point"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPoint","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPoint","text":"MPGeoPoint"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"polygon"},{"text":": ","kind":"text"},{"text":"MPGeoPolygon","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpgeometryutils\/pointintersectspolygon(point:polygon:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/pointIntersectsPolygon(point:polygon:)":{"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/pointIntersectsPolygon(point:polygon:)","title":"pointIntersectsPolygon(point:polygon:)","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/mapsindoors\/mpgeometryutils\/pointintersectspolygon(point:polygon:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pointIntersectsPolygon"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"point"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPoint","text":"MPGeoPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"polygon"},{"kind":"text","text":": "},{"text":"MPGeoPolygon","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils":{"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils","title":"MPGeometryUtils","navigatorTitle":[{"kind":"identifier","text":"MPGeometryUtils"}],"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/mapsindoors\/mpgeometryutils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPGeometryUtils","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPoint":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPoint","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPGeoPoint","kind":"identifier"}],"navigatorTitle":[{"text":"MPGeoPoint","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpgeopoint","kind":"symbol","title":"MPGeoPoint","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPolygon":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPGeoPolygon","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpgeopolygon","abstract":[],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPGeoPolygon"}],"title":"MPGeoPolygon","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"type":"image"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils\/title","value":"MPGeometryUtils"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPGeometryUtils"}]},{"value":"MPGeoPoint","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPoint\/title"},{"value":[{"text":"MPGeoPoint","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPoint\/fragments","op":"replace"},{"op":"replace","value":"MPGeoPolygon","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon\/fragments","value":[{"text":"MPGeoPolygon","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}