{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/polylineIntersectsPolygon(a:b:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpgeometryutils\/polylineintersectspolygon(a:b:)"]}],"kind":"symbol","metadata":{"role":"symbol","externalID":"s:11MapsIndoors15MPGeometryUtilsC25polylineIntersectsPolygon1a1bSbAA13MPGeoPolylineC_AA0hG0CtFZ","roleHeading":"Type Method","modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polylineIntersectsPolygon","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"a"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPGeoPolyline","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolyline"},{"kind":"text","text":", "},{"text":"b","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon","kind":"typeIdentifier","text":"MPGeoPolygon"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","title":"polylineIntersectsPolygon(a:b:)"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polylineIntersectsPolygon","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"a"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolyline","text":"MPGeoPolyline","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolyline"},{"text":", ","kind":"text"},{"text":"b","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon","text":"MPGeoPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/polylineIntersectsPolygon(a:b:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/polylineIntersectsPolygon(a:b:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"polylineIntersectsPolygon","kind":"identifier"},{"text":"(","kind":"text"},{"text":"a","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPGeoPolyline","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolyline"},{"text":", ","kind":"text"},{"text":"b","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon","text":"MPGeoPolygon"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","title":"polylineIntersectsPolygon(a:b:)","role":"symbol","url":"\/documentation\/mapsindoors\/mpgeometryutils\/polylineintersectspolygon(a:b:)","abstract":[]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPolygon":{"abstract":[],"url":"\/documentation\/mapsindoors\/mpgeopolygon","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPGeoPolygon","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPGeoPolygon"}],"title":"MPGeoPolygon"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPGeometryUtils"}],"type":"topic","role":"symbol","url":"\/documentation\/mapsindoors\/mpgeometryutils","kind":"symbol","navigatorTitle":[{"text":"MPGeometryUtils","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils","title":"MPGeometryUtils"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPolyline":{"title":"MPGeoPolyline","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolyline","kind":"symbol","url":"\/documentation\/mapsindoors\/mpgeopolyline","navigatorTitle":[{"text":"MPGeoPolyline","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeoPolyline"}],"role":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon\/title","value":"MPGeoPolygon","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon\/fragments","value":[{"kind":"identifier","text":"MPGeoPolygon"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils\/title","value":"MPGeometryUtils","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils\/fragments","value":[{"text":"MPGeometryUtils","kind":"identifier"}]},{"op":"replace","value":"MPGeoPolyline","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolyline\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolyline\/fragments","op":"replace","value":[{"text":"MPGeoPolyline","kind":"identifier"}]}]}]}