{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils"]]},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"polygonIntersectsPolygon"},{"kind":"text","text":"("},{"kind":"externalParam","text":"a"},{"text":": ","kind":"text"},{"text":"MPGeoPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon"},{"kind":"text","text":", "},{"text":"b","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MPGeoPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"modules":[{"name":"MapsIndoors"}],"role":"symbol","roleHeading":"Type Method","symbolKind":"method","title":"polygonIntersectsPolygon(a:b:)","externalID":"s:11MapsIndoors15MPGeometryUtilsC24polygonIntersectsPolygon1a1bSbAA05MPGeoG0C_AHtFZ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygonIntersectsPolygon","kind":"identifier"},{"text":"(","kind":"text"},{"text":"a","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon","text":"MPGeoPolygon","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"b"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon","text":"MPGeoPolygon","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/polygonIntersectsPolygon(a:b:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpgeometryutils\/polygonintersectspolygon(a:b:)"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/polygonIntersectsPolygon(a:b:)":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mpgeometryutils\/polygonintersectspolygon(a:b:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/polygonIntersectsPolygon(a:b:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"polygonIntersectsPolygon"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"a"},{"kind":"text","text":": "},{"text":"MPGeoPolygon","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"b","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon","text":"MPGeoPolygon"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"title":"polygonIntersectsPolygon(a:b:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPolygon":{"title":"MPGeoPolygon","kind":"symbol","url":"\/documentation\/mapsindoors\/mpgeopolygon","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPGeoPolygon","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPGeoPolygon"}],"abstract":[],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils":{"navigatorTitle":[{"kind":"identifier","text":"MPGeometryUtils"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpgeometryutils","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPGeometryUtils","kind":"identifier"}],"abstract":[],"title":"MPGeometryUtils","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon\/title","op":"replace","value":"MPGeoPolygon"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon\/fragments","value":[{"kind":"identifier","text":"MPGeoPolygon"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils\/title","value":"MPGeometryUtils","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MPGeometryUtils"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}