{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpgeometryutils\/polylineintersectspolyline(a:b:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Type Method","modules":[{"name":"MapsIndoors"}],"externalID":"s:11MapsIndoors15MPGeometryUtilsC26polylineIntersectsPolyline1a1bSbAA05MPGeoG0C_AHtFZ","role":"symbol","title":"polylineIntersectsPolyline(a:b:)","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"polylineIntersectsPolyline"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"a"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolyline","text":"MPGeoPolyline","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"b"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolyline","text":"MPGeoPolyline"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"polylineIntersectsPolyline","kind":"identifier"},{"text":"(","kind":"text"},{"text":"a","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolyline","text":"MPGeoPolyline","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolyline","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"b","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolyline","text":"MPGeoPolyline","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolyline"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/polylineIntersectsPolyline(a:b:)","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils":{"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils","title":"MPGeometryUtils","navigatorTitle":[{"kind":"identifier","text":"MPGeometryUtils"}],"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/mapsindoors\/mpgeometryutils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPGeometryUtils","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/polylineIntersectsPolyline(a:b:)":{"url":"\/documentation\/mapsindoors\/mpgeometryutils\/polylineintersectspolyline(a:b:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/polylineIntersectsPolyline(a:b:)","role":"symbol","abstract":[],"type":"topic","title":"polylineIntersectsPolyline(a:b:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"polylineIntersectsPolyline"},{"text":"(","kind":"text"},{"text":"a","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolyline","text":"MPGeoPolyline"},{"text":", ","kind":"text"},{"text":"b","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolyline","text":"MPGeoPolyline","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"MapsPeopleWhite.png":{"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPolyline":{"url":"\/documentation\/mapsindoors\/mpgeopolyline","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeoPolyline"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolyline","role":"symbol","type":"topic","title":"MPGeoPolyline","navigatorTitle":[{"text":"MPGeoPolyline","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils\/title","value":"MPGeometryUtils"},{"value":[{"text":"MPGeometryUtils","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolyline\/title","op":"replace","value":"MPGeoPolyline"},{"value":[{"text":"MPGeoPolyline","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolyline\/fragments"}]}]}