{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpcontextualinfoscope\/iconandname"]},{"paths":["\/documentation\/mapsindoors\/mpcontextualinfoscope\/iconandname"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"MPContextualInfoScopeIconAndName"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iconAndName","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MapsIndoors@E@MPContextualInfoScope@MPContextualInfoScopeIconAndName","roleHeading":"Case","title":"MPContextualInfoScope.iconAndName","modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iconAndName","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/iconAndName"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoScope/iconAndName":{"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iconAndName","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPContextualInfoScopeIconAndName"}],"abstract":[],"title":"MPContextualInfoScope.iconAndName","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/iconAndName","url":"\/documentation\/mapsindoors\/mpcontextualinfoscope\/iconandname","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoScope":{"url":"\/documentation\/mapsindoors\/mpcontextualinfoscope","type":"topic","role":"symbol","kind":"symbol","title":"MPContextualInfoScope","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPContextualInfoScope","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope","navigatorTitle":[{"text":"MPContextualInfoScope","kind":"identifier"}],"abstract":[{"text":"Which information to show from the Location close to the end of a route leg.","type":"text"}]},"MapsPeopleWhite.png":{"alt":null,"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"MPContextualInfoScopeIconAndName"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"MPContextualInfoScopeIconAndName","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MPContextualInfoScopeIconAndName"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MPContextualInfoScopeIconAndName","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope~1iconAndName\/title"},{"value":[{"text":"MPContextualInfoScopeIconAndName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope~1iconAndName\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope\/title","value":"MPContextualInfoScope","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPContextualInfoScope"}]}]}]}