{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon"}],"navigatorTitle":[{"kind":"identifier","text":"MPContextualInfoScopeIcon"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"case","externalID":"c:@M@MapsIndoors@E@MPContextualInfoScope@MPContextualInfoScopeIcon","role":"symbol","title":"MPContextualInfoScope.icon","roleHeading":"Case"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/mapsindoors\/mpcontextualinfoscope\/icon"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpcontextualinfoscope\/icon"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"icon","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/icon","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoScope":{"title":"MPContextualInfoScope","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPContextualInfoScope"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPContextualInfoScope","kind":"identifier"}],"abstract":[{"type":"text","text":"Which information to show from the Location close to the end of a route leg."}],"url":"\/documentation\/mapsindoors\/mpcontextualinfoscope","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoScope/icon":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/icon","navigatorTitle":[{"text":"MPContextualInfoScopeIcon","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpcontextualinfoscope\/icon","kind":"symbol","title":"MPContextualInfoScope.icon","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"MPContextualInfoScopeIcon","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"MPContextualInfoScopeIcon","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MPContextualInfoScopeIcon"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope\/title","value":"MPContextualInfoScope"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope\/fragments","value":[{"kind":"identifier","text":"MPContextualInfoScope"}]},{"value":"MPContextualInfoScopeIcon","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope~1icon\/title"},{"value":[{"text":"MPContextualInfoScopeIcon","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope~1icon\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}