{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/name","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"externalID":"c:@M@MapsIndoors@E@MPContextualInfoScope@MPContextualInfoScopeName","role":"symbol","modules":[{"name":"MapsIndoors"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"}],"symbolKind":"case","title":"MPContextualInfoScope.name","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"MPContextualInfoScopeName"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpcontextualinfoscope\/name"]},{"paths":["\/documentation\/mapsindoors\/mpcontextualinfoscope\/name"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoScope":{"title":"MPContextualInfoScope","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPContextualInfoScope"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPContextualInfoScope","kind":"identifier"}],"abstract":[{"type":"text","text":"Which information to show from the Location close to the end of a route leg."}],"url":"\/documentation\/mapsindoors\/mpcontextualinfoscope","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoScope/name":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/name","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MPContextualInfoScopeName"}],"title":"MPContextualInfoScope.name","url":"\/documentation\/mapsindoors\/mpcontextualinfoscope\/name","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MPContextualInfoScopeName"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPContextualInfoScopeName"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MPContextualInfoScopeName","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"MPContextualInfoScope","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope\/fragments","op":"replace","value":[{"text":"MPContextualInfoScope","kind":"identifier"}]},{"value":"MPContextualInfoScopeName","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope~1name\/title"},{"value":[{"text":"MPContextualInfoScopeName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope~1name\/fragments"}]}]}