{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"google"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mproutelegtype\/google"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mproutelegtype\/google"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLegType\/google","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"google"}],"title":"MPRouteLegType.google","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MPRouteLegType@MPRouteLegTypeGoogle","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPRouteLegTypeGoogle"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLegType"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLegType":{"role":"symbol","title":"MPRouteLegType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteLegType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLegType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteLegType"}],"url":"\/documentation\/mapsindoors\/mproutelegtype"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLegType/google":{"role":"symbol","title":"MPRouteLegType.google","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"google"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLegType\/google","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteLegTypeGoogle"}],"url":"\/documentation\/mapsindoors\/mproutelegtype\/google"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MPRouteLegTypeGoogle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPRouteLegTypeGoogle"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MPRouteLegTypeGoogle"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLegType\/title","value":"MPRouteLegType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLegType\/fragments","value":[{"kind":"identifier","text":"MPRouteLegType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLegType~1google\/title","value":"MPRouteLegTypeGoogle"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLegType~1google\/fragments","value":[{"kind":"identifier","text":"MPRouteLegTypeGoogle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}