{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rule"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule","text":"MPLocationDisplayRule"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/add(_:)-49g52"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/add(_:)-49g52"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/add(_:)-49g52","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/setDisplayRule(_:)"},{"type":"text","text":" instead."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"addDisplayRule:"}],"role":"symbol","title":"add(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(cs)MPMapControl(im)addDisplayRule:","modules":[{"name":"MapsIndoors"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Replaced by setDisplayRule: in version 3.7.0"}]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl/setDisplayRule(_:)":{"role":"symbol","title":"setDisplayRule(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDisplayRule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Add a location display rule for a specific location type."},{"type":"text","text":" "},{"type":"text","text":"You need to know the types applied to the map locations."},{"type":"text","text":" "},{"type":"text","text":"The display rule name corresponds to the location type we want the rule to apply for."},{"type":"text","text":" "},{"type":"text","text":"Adding a rule with name nil, will apply generally to all types"},{"type":"text","text":" "},{"type":"text","text":"Adding a rule with a name, will override a more general rule"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/setDisplayRule(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDisplayRule:"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/setdisplayrule(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl/add(_:)-49g52":{"deprecated":true,"role":"symbol","title":"add(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/setDisplayRule(_:)"},{"type":"text","text":" instead."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/add(_:)-49g52","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addDisplayRule:"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/add(_:)-49g52"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl":{"role":"symbol","title":"MPMapControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"abstract":[{"type":"text","text":"Convenience class for setting up a Google map with MapsIndoors venues, buildings, locations and other map content."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule":{"role":"symbol","title":"MPLocationDisplayRule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationDisplayRule"}],"abstract":[{"type":"text","text":"This class serves as a display rule for locations."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationDisplayRule"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addDisplayRule:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addDisplayRule:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addDisplayRule:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule","text":"MPLocationDisplayRule"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"rule"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1setDisplayRule(_:)\/title","value":"setDisplayRule:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1setDisplayRule(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDisplayRule:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1add(_:)-49g52\/title","value":"addDisplayRule:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1add(_:)-49g52\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addDisplayRule:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"kind":"identifier","text":"MPMapControl"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule\/title","value":"MPLocationDisplayRule"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule\/fragments","value":[{"kind":"identifier","text":"MPLocationDisplayRule"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}