{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentFloor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/currentfloor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/currentfloor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/currentFloor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The current floor."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentFloor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"title":"currentFloor","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPMapControl(py)currentFloor","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"currentFloor"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl/currentFloor":{"role":"symbol","title":"currentFloor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentFloor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The current floor."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/currentFloor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"currentFloor"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/currentfloor"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl":{"role":"symbol","title":"MPMapControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"abstract":[{"type":"text","text":"Convenience class for setting up a Google map with MapsIndoors venues, buildings, locations and other map content."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"currentFloor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"currentFloor"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"currentFloor"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1currentFloor\/title","value":"currentFloor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1currentFloor\/fragments","value":[{"kind":"identifier","text":"currentFloor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"kind":"identifier","text":"MPMapControl"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}