{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customFloorSelector"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorProtocol","preciseIdentifier":"c:objc(pl)MPFloorSelectorProtocol","text":"MPFloorSelectorProtocol"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/customfloorselector"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/customfloorselector"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/customFloorSelector","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Custom floor selector for the map to use."},{"type":"text","text":" "},{"type":"text","text":"When provided, the MapControl will not create a floor selector control autonomously."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customFloorSelector"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPFloorSelectorProtocol","preciseIdentifier":"c:objc(pl)MPFloorSelectorProtocol"},{"kind":"text","text":"?"}],"title":"customFloorSelector","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPMapControl(py)customFloorSelector","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"customFloorSelector"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl":{"role":"symbol","title":"MPMapControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"abstract":[{"type":"text","text":"Convenience class for setting up a Google map with MapsIndoors venues, buildings, locations and other map content."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl/customFloorSelector":{"role":"symbol","title":"customFloorSelector","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customFloorSelector"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPFloorSelectorProtocol","preciseIdentifier":"c:objc(pl)MPFloorSelectorProtocol"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Custom floor selector for the map to use."},{"type":"text","text":" "},{"type":"text","text":"When provided, the MapControl will not create a floor selector control autonomously."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/customFloorSelector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customFloorSelector"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/customfloorselector"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorSelectorProtocol":{"role":"symbol","title":"MPFloorSelectorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloorSelectorProtocol"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorSelectorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPFloorSelectorProtocol"}],"url":"\/documentation\/mapsindoors\/mpfloorselectorprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"customFloorSelector"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"customFloorSelector"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<MPFloorSelectorProtocol>","preciseIdentifier":"c:Qoobjc(pl)MPFloorSelectorProtocol"},{"kind":"text","text":" *"},{"kind":"identifier","text":"customFloorSelector"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"kind":"identifier","text":"MPMapControl"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1customFloorSelector\/title","value":"customFloorSelector"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1customFloorSelector\/fragments","value":[{"kind":"identifier","text":"customFloorSelector"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorProtocol\/title","value":"MPFloorSelectorProtocol"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorSelectorProtocol\/fragments","value":[{"kind":"identifier","text":"MPFloorSelectorProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}