{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/customclustericon"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/customclustericon"]}],"abstract":[{"type":"text","text":"Get or set the cluster icon generator (if none is set, the default internal will be used)."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/customClusterIcon"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"customClusterIcon"}],"roleHeading":"Instance Property","externalID":"c:@M@MapsIndoors@objc(pl)MPMapControl(py)customClusterIcon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"customClusterIcon","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPCustomClusterIcon","text":"MPCustomClusterIcon"},{"kind":"text","text":"?"}],"required":true,"title":"customClusterIcon","symbolKind":"property","role":"symbol","modules":[{"name":"MapsIndoors"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"customClusterIcon"},{"text":": ","kind":"text"},{"text":"MPCustomClusterIcon","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPCustomClusterIcon","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomClusterIcon"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","abstract":[{"text":"This is the control object for the visual representation of the MapsIndoors SDK.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"title":"MPMapControl","role":"symbol","navigatorTitle":[{"text":"MPMapControl","kind":"identifier"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/customClusterIcon":{"title":"customClusterIcon","role":"symbol","kind":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"customClusterIcon"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPCustomClusterIcon","text":"MPCustomClusterIcon","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Get or set the cluster icon generator (if none is set, the default internal will be used)."}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/customclustericon","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/customClusterIcon","navigatorTitle":[{"text":"customClusterIcon","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomClusterIcon":{"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomClusterIcon","abstract":[{"text":"Optionally create your own cluster icon for the SDK to use.","type":"text"}],"navigatorTitle":[{"text":"MPCustomClusterIcon","kind":"identifier"}],"title":"MPCustomClusterIcon","url":"\/documentation\/mapsindoors\/mpcustomclustericon","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPCustomClusterIcon"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"customClusterIcon","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"customClusterIcon"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPCustomClusterIcon","text":"id<MPCustomClusterIcon>"},{"kind":"text","text":" * "},{"text":"customClusterIcon","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"MPMapControl","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"kind":"identifier","text":"MPMapControl"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1customClusterIcon\/title","value":"customClusterIcon","op":"replace"},{"op":"replace","value":[{"text":"customClusterIcon","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1customClusterIcon\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomClusterIcon\/title","value":"MPCustomClusterIcon"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomClusterIcon\/fragments","value":[{"kind":"identifier","text":"MPCustomClusterIcon"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}