{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/enableLiveData(domain:listener:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MapsIndoors"}],"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPMapControl(im)enableLiveDataWithDomain:listener:","symbolKind":"method","navigatorTitle":[{"text":"enableLiveDataWithDomain:listener:","kind":"identifier"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"enableLiveData","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"domain"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate","text":"MPLiveUpdate","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"roleHeading":"Instance Method","title":"enableLiveData(domain:listener:)"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableLiveData","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"domain"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"MPLiveUpdate","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Convenience: Enable LiveData for a given domain (includes default live data badged icons)."}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/enablelivedata(domain:listener:)"]},{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/enablelivedata(domain:listener:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"MapsPeopleWhite.png":{"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"role":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontrol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPMapControl","kind":"identifier"}],"abstract":[{"text":"This is the control object for the visual representation of the MapsIndoors SDK.","type":"text"}],"navigatorTitle":[{"text":"MPMapControl","kind":"identifier"}],"kind":"symbol","type":"topic","title":"MPMapControl"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/enableLiveData(domain:listener:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/enableLiveData(domain:listener:)","title":"enableLiveData(domain:listener:)","required":true,"role":"symbol","abstract":[{"type":"text","text":"Convenience: Enable LiveData for a given domain (includes default live data badged icons)."}],"navigatorTitle":[{"kind":"identifier","text":"enableLiveDataWithDomain:listener:"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontrol\/enablelivedata(domain:listener:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableLiveData"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"domain"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"MPLiveUpdate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/getLiveUpdate(forDomainType:)":{"abstract":[{"type":"text","text":"Get a live update based on a known domain type."}],"title":"getLiveUpdate(forDomainType:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getLiveUpdate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forDomainType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"MPLiveUpdate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate"},{"kind":"text","text":"?"}],"role":"symbol","required":true,"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","navigatorTitle":[{"text":"getLiveUpdateForDomainType:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mplocation\/getliveupdate(fordomaintype:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate":{"abstract":[{"text":"Model for a Live Update. Used in ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","isActive":true,"type":"reference"}],"title":"MPLiveUpdate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPLiveUpdate"}],"role":"symbol","navigatorTitle":[{"text":"MPLiveUpdate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","type":"topic","url":"\/documentation\/mapsindoors\/mpliveupdate"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enableLiveDataWithDomain:listener:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"enableLiveDataWithDomain:listener:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"enableLiveDataWithDomain:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"domain","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"listener:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(MPLiveUpdate *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@MapsIndoors@objc(cs)MPLiveUpdate)"},{"kind":"text","text":") "},{"text":"listener","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MPMapControl","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"kind":"identifier","text":"MPMapControl"}]},{"value":"enableLiveDataWithDomain:listener:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1enableLiveData(domain:listener:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1enableLiveData(domain:listener:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"enableLiveDataWithDomain:listener:"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/title","op":"replace","value":"getLiveUpdateForDomainType:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getLiveUpdateForDomainType:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/title","value":"MPLiveUpdate","op":"replace"},{"value":[{"kind":"identifier","text":"MPLiveUpdate"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}