{"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Get or set the map styling."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/mapstyle"]},{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/mapstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"]]},"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapStyle"},{"text":": ","kind":"text"},{"text":"MPMapStyle","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPMapStyle","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPMapControl(py)mapStyle","navigatorTitle":[{"kind":"identifier","text":"mapStyle"}],"symbolKind":"property","role":"symbol","required":true,"modules":[{"name":"MapsIndoors"}],"title":"mapStyle"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mapStyle","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapStyle","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPMapStyle","text":"MPMapStyle","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/mapStyle","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"role":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontrol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPMapControl","kind":"identifier"}],"abstract":[{"text":"This is the control object for the visual representation of the MapsIndoors SDK.","type":"text"}],"navigatorTitle":[{"text":"MPMapControl","kind":"identifier"}],"kind":"symbol","type":"topic","title":"MPMapControl"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/mapStyle":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapStyle"},{"text":": ","kind":"text"},{"text":"MPMapStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPMapStyle"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"mapStyle","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/mapStyle","abstract":[{"text":"Get or set the map styling.","type":"text"}],"required":true,"type":"topic","role":"symbol","kind":"symbol","title":"mapStyle","url":"\/documentation\/mapsindoors\/mpmapcontrol\/mapstyle"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapStyle":{"navigatorTitle":[{"text":"MPMapStyle","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPMapStyle","kind":"identifier"}],"title":"MPMapStyle","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapStyle","url":"\/documentation\/mapsindoors\/mpmapstyle","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"mapStyle","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"mapStyle"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<MPMapStyle>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPMapStyle"},{"kind":"text","text":" * "},{"kind":"identifier","text":"mapStyle"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"text":"MPMapControl","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1mapStyle\/title","op":"replace","value":"mapStyle"},{"value":[{"kind":"identifier","text":"mapStyle"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1mapStyle\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapStyle\/title","op":"replace","value":"MPMapStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapStyle\/fragments","value":[{"text":"MPMapStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}