{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"]]},"metadata":{"required":true,"externalID":"c:@M@MapsIndoors@objc(pl)MPMapControl(py)mapsIndoorsZoom","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"mapsIndoorsZoom","kind":"identifier"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"navigatorTitle":[{"text":"mapsIndoorsZoom","kind":"identifier"}],"role":"symbol","modules":[{"name":"MapsIndoors"}],"title":"mapsIndoorsZoom"},"abstract":[{"text":"The zoom level that MapsIndoors is currently using for display icons etc. on the map.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/mapsindoorszoom"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/mapsindoorszoom"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapsIndoorsZoom"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/mapsIndoorsZoom"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"MapsPeopleWhite.png":{"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/mapsIndoorsZoom":{"title":"mapsIndoorsZoom","role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpmapcontrol\/mapsindoorszoom","required":true,"navigatorTitle":[{"kind":"identifier","text":"mapsIndoorsZoom"}],"abstract":[{"type":"text","text":"The zoom level that MapsIndoors is currently using for display icons etc. on the map."}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/mapsIndoorsZoom","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mapsIndoorsZoom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"title":"MPMapControl","url":"\/documentation\/mapsindoors\/mpmapcontrol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"type":"topic","abstract":[{"text":"This is the control object for the visual representation of the MapsIndoors SDK.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"mapsIndoorsZoom","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"mapsIndoorsZoom","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"mapsIndoorsZoom","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"mapsIndoorsZoom","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1mapsIndoorsZoom\/title"},{"value":[{"kind":"identifier","text":"mapsIndoorsZoom"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1mapsIndoorsZoom\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"text":"MPMapControl","kind":"identifier"}],"op":"replace"}]}]}