{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/refresh()","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPMapControl(im)refresh","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"()"}],"required":true,"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"refresh","kind":"identifier"}],"title":"refresh()"},"abstract":[{"type":"text","text":"Force a re-render of the MapsIndoors map."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"refresh","kind":"identifier"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/refresh()"]},{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/refresh()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/refresh()":{"required":true,"role":"symbol","navigatorTitle":[{"text":"refresh","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/refresh()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"refresh","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[{"text":"Force a re-render of the MapsIndoors map.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/refresh()","title":"refresh()","kind":"symbol","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"MapsPeopleWhite.png":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"title":"MPMapControl","url":"\/documentation\/mapsindoors\/mpmapcontrol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"type":"topic","abstract":[{"text":"This is the control object for the visual representation of the MapsIndoors SDK.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"refresh","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"refresh"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"refresh","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1refresh()\/title","value":"refresh"},{"value":[{"kind":"text","text":"- "},{"text":"refresh","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1refresh()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","op":"replace","value":[{"text":"MPMapControl","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}