{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetDisplayRules"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"locations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","preciseIdentifier":"c:objc(cs)MPLocation","text":"MPLocation"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"locations","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MPLocations that should have their specific displayrule removed."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/resetdisplayrules(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/resetdisplayrules(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/resetDisplayRules(for:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Remove any specific displayrule that has been added to the given MPLocations."},{"type":"text","text":" "},{"type":"text","text":"Once the location-specific display rules are removed, the MPLocations will be displayed on map according to their type-displayrule."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetDisplayRules"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":"])"}],"title":"resetDisplayRules(for:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPMapControl(im)resetDisplayRulesForLocations:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"resetDisplayRulesForLocations:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class":{"role":"symbol","title":"MPLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"abstract":[{"type":"text","text":"This class holds the data for a single location and a marker to display the data on a map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl/resetDisplayRules(for:)":{"role":"symbol","title":"resetDisplayRules(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetDisplayRules"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Remove any specific displayrule that has been added to the given MPLocations."},{"type":"text","text":" "},{"type":"text","text":"Once the location-specific display rules are removed, the MPLocations will be displayed on map according to their type-displayrule."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/resetDisplayRules(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resetDisplayRulesForLocations:"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/resetdisplayrules(for:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl":{"role":"symbol","title":"MPMapControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"abstract":[{"type":"text","text":"Convenience class for setting up a Google map with MapsIndoors venues, buildings, locations and other map content."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"resetDisplayRulesForLocations:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetDisplayRulesForLocations:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"resetDisplayRulesForLocations:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<MPLocation *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"locations"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/title","value":"MPLocation"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/fragments","value":[{"kind":"identifier","text":"MPLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1resetDisplayRules(for:)\/title","value":"resetDisplayRulesForLocations:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1resetDisplayRules(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetDisplayRulesForLocations:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"kind":"identifier","text":"MPMapControl"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}