{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"select"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"venue"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPVenue","text":"MPVenue","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"behavior","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSelectionBehavior","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior","kind":"typeIdentifier","text":"MPSelectionBehavior"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"venue","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Venue to select."}]}]},{"name":"behavior","content":[{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior","isActive":true,"type":"reference"},{"type":"text","text":" to apply."}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/select(venue:behavior:)"]},{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/select(venue:behavior:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Select a Venue."}],"sections":[],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/select(venue:behavior:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MapsIndoors"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPMapControl(im)selectWithVenue:behavior:","title":"select(venue:behavior:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"select","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"venue"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPVenue","text":"MPVenue","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"behavior","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPSelectionBehavior","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSelectionBehavior"},{"text":")","kind":"text"}],"required":true,"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"selectWithVenue:behavior:"}],"symbolKind":"method"},"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/select(venue:behavior:)":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"select","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"venue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPVenue","text":"MPVenue","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"behavior"},{"text":": ","kind":"text"},{"text":"MPSelectionBehavior","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSelectionBehavior"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"selectWithVenue:behavior:"}],"abstract":[{"type":"text","text":"Select a Venue."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/select(venue:behavior:)","type":"topic","url":"\/documentation\/mapsindoors\/mpmapcontrol\/select(venue:behavior:)","role":"symbol","kind":"symbol","title":"select(venue:behavior:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue":{"url":"\/documentation\/mapsindoors\/mpvenue","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPVenue"}],"abstract":[{"type":"text","text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data."}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPVenue"}],"title":"MPVenue","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"type":"topic","abstract":[{"text":"This is the control object for the visual representation of the MapsIndoors SDK.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontrol","title":"MPMapControl"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSelectionBehavior":{"type":"topic","kind":"symbol","title":"MPSelectionBehavior","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior","url":"\/documentation\/mapsindoors\/mpselectionbehavior","abstract":[{"text":"Selection behavior class that determines how a location selection should be displayed on the map.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSelectionBehavior"}],"navigatorTitle":[{"text":"MPSelectionBehavior","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"selectWithVenue:behavior:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectWithVenue:behavior:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"selectWithVenue:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPVenue","kind":"typeIdentifier","text":"id<MPVenue>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"venue"},{"text":" ","kind":"text"},{"kind":"identifier","text":"behavior:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSelectionBehavior","kind":"typeIdentifier","text":"MPSelectionBehavior","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior"},{"kind":"text","text":" *) "},{"text":"behavior","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"selectWithVenue:behavior:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1select(venue:behavior:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1select(venue:behavior:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"selectWithVenue:behavior:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/title","value":"MPVenue"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/fragments","value":[{"kind":"identifier","text":"MPVenue"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title","op":"replace","value":"MPMapControl"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"text":"MPMapControl","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSelectionBehavior\/title","value":"MPSelectionBehavior","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSelectionBehavior\/fragments","value":[{"text":"MPSelectionBehavior","kind":"identifier"}]}]}]}