{"abstract":[{"text":"Select a Building.","type":"text"}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"select","kind":"identifier"},{"kind":"text","text":"("},{"text":"building","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPBuilding","kind":"typeIdentifier","text":"MPBuilding","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding"},{"text":"?, ","kind":"text"},{"text":"behavior","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior","text":"MPSelectionBehavior","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSelectionBehavior"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Building to select."}]}],"name":"building"},{"name":"behavior","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior"},{"type":"text","text":" to apply."}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/select(building:behavior:)"]},{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/select(building:behavior:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/select(building:behavior:)","interfaceLanguage":"swift"},"metadata":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"select","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"building"},{"text":": ","kind":"text"},{"text":"MPBuilding","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPBuilding"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"behavior"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSelectionBehavior","kind":"typeIdentifier","text":"MPSelectionBehavior"},{"text":")","kind":"text"}],"modules":[{"name":"MapsIndoors"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","title":"select(building:behavior:)","navigatorTitle":[{"kind":"identifier","text":"selectWithBuilding:behavior:"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPMapControl(im)selectWithBuilding:behavior:"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding":{"url":"\/documentation\/mapsindoors\/mpbuilding","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPBuilding","kind":"identifier"}],"abstract":[{"type":"text","text":"Holds relevant data for a single building, and the buildings floor levels."}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MPBuilding","kind":"identifier"}],"title":"MPBuilding","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSelectionBehavior":{"type":"topic","kind":"symbol","title":"MPSelectionBehavior","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior","url":"\/documentation\/mapsindoors\/mpselectionbehavior","abstract":[{"text":"Selection behavior class that determines how a location selection should be displayed on the map.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSelectionBehavior"}],"navigatorTitle":[{"text":"MPSelectionBehavior","kind":"identifier"}]},"MapsPeopleWhite.png":{"alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/select(building:behavior:)":{"kind":"symbol","abstract":[{"text":"Select a Building.","type":"text"}],"required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"select"},{"kind":"text","text":"("},{"kind":"externalParam","text":"building"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPBuilding","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPBuilding"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"behavior"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSelectionBehavior","text":"MPSelectionBehavior"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"selectWithBuilding:behavior:"}],"title":"select(building:behavior:)","url":"\/documentation\/mapsindoors\/mpmapcontrol\/select(building:behavior:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/select(building:behavior:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"type":"topic","abstract":[{"text":"This is the control object for the visual representation of the MapsIndoors SDK.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontrol","title":"MPMapControl"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"selectWithBuilding:behavior:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"selectWithBuilding:behavior:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"selectWithBuilding:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPBuilding","text":"id<MPBuilding>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"building","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"behavior:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSelectionBehavior","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior","text":"MPSelectionBehavior"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"behavior"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MPBuilding","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/title"},{"value":[{"text":"MPBuilding","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/fragments","op":"replace"},{"value":"MPSelectionBehavior","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSelectionBehavior\/title"},{"op":"replace","value":[{"text":"MPSelectionBehavior","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSelectionBehavior\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1select(building:behavior:)\/title","op":"replace","value":"selectWithBuilding:behavior:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"selectWithBuilding:behavior:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1select(building:behavior:)\/fragments"},{"value":"MPMapControl","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"kind":"identifier","text":"MPMapControl"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}