{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFilter"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"filter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilter","text":"MPFilter"},{"text":", ","kind":"text"},{"text":"behavior","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior","text":"MPFilterBehavior","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilterBehavior","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"filter","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter"},{"type":"text","text":" to apply for which Locations to show on the map."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior","isActive":true},{"text":" to apply.","type":"text"}]}],"name":"behavior"}]}],"kind":"symbol","abstract":[{"text":"Apply a filter to the map. Only show the ","type":"text"},{"code":"MPLocations","type":"codeVoice"},{"type":"text","text":" captured by the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/setfilter(filter:behavior:)"]},{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/setfilter(filter:behavior:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/setFilter(filter:behavior:)"},"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPMapControl(im)setFilterWithFilter:behavior:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setFilter"},{"kind":"text","text":"("},{"text":"filter","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilter","text":"MPFilter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"behavior"},{"kind":"text","text":": "},{"text":"MPFilterBehavior","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilterBehavior"},{"text":")","kind":"text"}],"symbolKind":"method","title":"setFilter(filter:behavior:)","navigatorTitle":[{"kind":"identifier","text":"setFilterWithFilter:behavior:"}],"roleHeading":"Instance Method","modules":[{"name":"MapsIndoors"}],"role":"symbol","required":true},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter":{"role":"symbol","abstract":[{"type":"text","text":"Filter object used when making a request to e.g. "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","isActive":true},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpfilter","navigatorTitle":[{"text":"MPFilter","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPFilter","kind":"identifier"}],"title":"MPFilter"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilterBehavior":{"url":"\/documentation\/mapsindoors\/mpfilterbehavior","abstract":[{"text":"Filter behavior class that determines how a filter should be display on the map. Get the default behavior from ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior\/default","type":"reference"},{"type":"text","text":". The default behavior is no camera movement and no infowindow shown."}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior","title":"MPFilterBehavior","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPFilterBehavior","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPFilterBehavior"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilterBehavior/default":{"url":"\/documentation\/mapsindoors\/mpfilterbehavior\/default","abstract":[{"type":"text","text":"Default filter behavior"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior\/default","title":"default","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilterBehavior","text":"MPFilterBehavior","kind":"typeIdentifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/setFilter(filter:behavior:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setFilter","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"filter"},{"kind":"text","text":": "},{"text":"MPFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilter"},{"text":", ","kind":"text"},{"text":"behavior","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilterBehavior","text":"MPFilterBehavior"},{"kind":"text","text":")"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/setfilter(filter:behavior:)","kind":"symbol","title":"setFilter(filter:behavior:)","abstract":[{"text":"Apply a filter to the map. Only show the ","type":"text"},{"type":"codeVoice","code":"MPLocations"},{"text":" captured by the ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter","isActive":true,"type":"reference"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"setFilterWithFilter:behavior:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/setFilter(filter:behavior:)","type":"topic","required":true,"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"abstract":[{"type":"text","text":"This is the control object for the visual representation of the MapsIndoors SDK."}],"url":"\/documentation\/mapsindoors\/mpmapcontrol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPMapControl"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"type":"topic","kind":"symbol","title":"MPMapControl","role":"symbol"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/locationsWith(query:filter:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"locationsWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"query"},{"text":": ","kind":"text"},{"text":"MPQuery","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPQuery","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"filter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPFilter","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilter"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"kind":"text","text":"]"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"locationsWithQuery:filter:completionHandler:","kind":"identifier"}],"title":"locationsWith(query:filter:)","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/locationswith(query:filter:)","kind":"symbol","required":true,"abstract":[{"type":"text","text":"Search for MPLocations using MPQuery and\/or MPFilter."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"setFilterWithFilter:behavior:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFilterWithFilter:behavior:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setFilterWithFilter:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter","text":"MPFilter","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilter","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"filter"},{"text":" ","kind":"text"},{"kind":"identifier","text":"behavior:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilterBehavior","text":"MPFilterBehavior"},{"text":" *) ","kind":"text"},{"text":"behavior","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"MPFilter","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter\/fragments","value":[{"kind":"identifier","text":"MPFilter"}]},{"op":"replace","value":"MPFilterBehavior","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilterBehavior\/title"},{"value":[{"kind":"identifier","text":"MPFilterBehavior"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilterBehavior\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1setFilter(filter:behavior:)\/title","value":"setFilterWithFilter:behavior:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1setFilter(filter:behavior:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"setFilterWithFilter:behavior:","kind":"identifier"}]},{"value":"MPMapControl","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPMapControl"}]},{"value":"locationsWithQuery:filter:completionHandler:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"locationsWithQuery:filter:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}