{"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setMapLabelFont","kind":"identifier"},{"text":"(","kind":"text"},{"text":"font","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":", "},{"text":"textSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"color","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"labelHaloColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"labelHaloWidth"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"labelHaloBlur","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Sets the font to be used for the label."}],"type":"paragraph"}],"name":"font"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Sets the size of the label’s text."}]}],"name":"textSize"},{"name":"color","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Sets the color of the label’s text."}]}]},{"name":"labelHaloColor","content":[{"inlineContent":[{"type":"text","text":"Sets the color of the halo, a glow-like effect, around the label."}],"type":"paragraph"}]},{"name":"labelHaloWidth","content":[{"inlineContent":[{"type":"text","text":"Sets the width or thickness of the halo around the label. The effect of this is different on MapBox Maps and Google Maps due to differences in the way they render items on the map."}],"type":"paragraph"}]},{"name":"labelHaloBlur","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Sets the blurriness or softness of the halo effect.  The effect of this is different on MapBox Maps and Google Maps due to differences in the way they render items on the map."}]}]}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Set a custom label font, text size, color and halo."}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/setmaplabelfont(font:textsize:color:labelhalocolor:labelhalowidth:labelhaloblur:)-8rq64"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/setmaplabelfont(font:textsize:color:labelhalocolor:labelhalowidth:labelhaloblur:)-8rq64"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMapLabelFont"},{"text":"(","kind":"text"},{"text":"font","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":", "},{"text":"color","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"labelHaloColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"labelHaloWidth"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"labelHaloBlur"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"setMapLabelFontWithFont:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPMapControl(im)setMapLabelFontWithFont:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:","modules":[{"name":"MapsIndoors"}],"roleHeading":"Instance Method","title":"setMapLabelFont(font:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:)","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"]]},"defaultImplementationsSections":[{"title":"MPMapControl Implementations","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/setMapLabelFont(font:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:)-x02e"]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/setMapLabelFont(font:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:)-8rq64","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/setMapLabelFont(font:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:)-x02e":{"type":"topic","abstract":[{"text":"Extension function with optional paramters","type":"text"}],"title":"setMapLabelFont(font:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setMapLabelFont"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"font"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier","text":"UIFont"},{"text":", ","kind":"text"},{"text":"textSize","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"color","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"labelHaloColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"labelHaloWidth","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"labelHaloBlur"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/setMapLabelFont(font:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:)-x02e","url":"\/documentation\/mapsindoors\/mpmapcontrol\/setmaplabelfont(font:textsize:color:labelhalocolor:labelhalowidth:labelhaloblur:)-x02e","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/setMapLabelFont(font:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:)-8rq64":{"type":"topic","abstract":[{"type":"text","text":"Set a custom label font, text size, color and halo."}],"title":"setMapLabelFont(font:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setMapLabelFont"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"font"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textSize"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"color","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"labelHaloColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"labelHaloWidth"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"labelHaloBlur","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/setMapLabelFont(font:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:)-8rq64","url":"\/documentation\/mapsindoors\/mpmapcontrol\/setmaplabelfont(font:textsize:color:labelhalocolor:labelhalowidth:labelhaloblur:)-8rq64","required":true,"role":"symbol","navigatorTitle":[{"text":"setMapLabelFontWithFont:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:","kind":"identifier"}],"defaultImplementations":1},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"abstract":[{"type":"text","text":"This is the control object for the visual representation of the MapsIndoors SDK."}],"url":"\/documentation\/mapsindoors\/mpmapcontrol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPMapControl"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"type":"topic","kind":"symbol","title":"MPMapControl","role":"symbol"},"MapsPeopleWhite.png":{"alt":null,"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"setMapLabelFontWithFont:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setMapLabelFontWithFont:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setMapLabelFontWithFont:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"font"},{"kind":"text","text":" "},{"kind":"identifier","text":"textSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"textSize"},{"text":" ","kind":"text"},{"kind":"identifier","text":"color:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"color","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"labelHaloColor:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *) "},{"text":"labelHaloColor","kind":"internalParam"},{"kind":"text","text":" "},{"text":"labelHaloWidth:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"text":") ","kind":"text"},{"text":"labelHaloWidth","kind":"internalParam"},{"kind":"text","text":" "},{"text":"labelHaloBlur:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"kind":"text","text":") "},{"text":"labelHaloBlur","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"setMapLabelFontWithFont:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1setMapLabelFont(font:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:)-8rq64\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setMapLabelFontWithFont:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1setMapLabelFont(font:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:)-8rq64\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","op":"replace","value":[{"text":"MPMapControl","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}