{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showUserPosition","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPMapControl(py)showUserPosition","required":true,"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"showUserPosition"}],"modules":[{"name":"MapsIndoors"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"showUserPosition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"property","title":"showUserPosition"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/showuserposition"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/showuserposition"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/showUserPosition","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enable\/disable showing the users position with a blue dot (customizable) (requires your application to implement a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider"},{"type":"text","text":")."}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionProvider":{"url":"\/documentation\/mapsindoors\/mppositionprovider","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProvider"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPPositionProvider"}],"title":"MPPositionProvider","abstract":[{"type":"text","text":"Protocol specifying how an indoor positioning provider should be implemented if the users location is to be exposed to "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true},{"type":"text","text":"."}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"abstract":[{"type":"text","text":"This is the control object for the visual representation of the MapsIndoors SDK."}],"url":"\/documentation\/mapsindoors\/mpmapcontrol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPMapControl"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"type":"topic","kind":"symbol","title":"MPMapControl","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/showUserPosition":{"title":"showUserPosition","url":"\/documentation\/mapsindoors\/mpmapcontrol\/showuserposition","type":"topic","navigatorTitle":[{"text":"showUserPosition","kind":"identifier"}],"required":true,"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/showUserPosition","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"showUserPosition","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Enable\/disable showing the users position with a blue dot (customizable) (requires your application to implement a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider"},{"type":"text","text":")."}],"kind":"symbol"},"MapsPeopleWhite.png":{"alt":null,"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"showUserPosition"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"showUserPosition","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"showUserPosition","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MPPositionProvider","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider\/title"},{"value":[{"text":"MPPositionProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider\/fragments","op":"replace"},{"value":"MPMapControl","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MPMapControl"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments"},{"value":"showUserPosition","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1showUserPosition\/title"},{"op":"replace","value":[{"text":"showUserPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1showUserPosition\/fragments"}]}]}