{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showArea"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":" "},{"kind":"internalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","preciseIdentifier":"c:objc(cs)MPLocation","text":"MPLocation"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"location","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Location to show."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/showarea(of:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/showarea(of:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/showArea(of:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Make sure the complete geometry of the given MPLocation is visible on the map."},{"type":"text","text":" "},{"type":"text","text":"If the location is fully visible, the visible area of the map is unchanged."},{"type":"text","text":" "},{"type":"text","text":"If the location is not fully visible, the map is centered around the location, and if needed zoomed."},{"type":"text","text":" "},{"type":"text","text":"This method does not change the shown floor."},{"type":"text","text":" "},{"type":"text","text":"The maps current bearing and vieweing angle is preserved."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showArea"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":")"}],"title":"showArea(of:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPMapControl(im)showAreaOfLocation:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"showAreaOfLocation:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl/showArea(of:)":{"role":"symbol","title":"showArea(of:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showArea"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Make sure the complete geometry of the given MPLocation is visible on the map."},{"type":"text","text":" "},{"type":"text","text":"If the location is fully visible, the visible area of the map is unchanged."},{"type":"text","text":" "},{"type":"text","text":"If the location is not fully visible, the map is centered around the location, and if needed zoomed."},{"type":"text","text":" "},{"type":"text","text":"This method does not change the shown floor."},{"type":"text","text":" "},{"type":"text","text":"The maps current bearing and vieweing angle is preserved."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/showArea(of:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showAreaOfLocation:"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/showarea(of:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class":{"role":"symbol","title":"MPLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"abstract":[{"type":"text","text":"This class holds the data for a single location and a marker to display the data on a map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl":{"role":"symbol","title":"MPMapControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"abstract":[{"type":"text","text":"Convenience class for setting up a Google map with MapsIndoors venues, buildings, locations and other map content."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showAreaOfLocation:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showAreaOfLocation:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showAreaOfLocation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","preciseIdentifier":"c:objc(cs)MPLocation","text":"MPLocation"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"location"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1showArea(of:)\/title","value":"showAreaOfLocation:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1showArea(of:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showAreaOfLocation:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/title","value":"MPLocation"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/fragments","value":[{"kind":"identifier","text":"MPLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"kind":"identifier","text":"MPMapControl"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}