{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zIndexRangeForMapsIndoorsTileLayers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/zindexrangeformapsindoorstilelayers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmapcontrol\/zindexrangeformapsindoorstilelayers"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/zIndexRangeForMapsIndoorsTileLayers","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indexes reserved for MapsIndoors tile layers."},{"type":"text","text":" "},{"type":"text","text":"If you are adding tilelayers to a map with MapsIndoors tiles, you should set the zIndex of your tile layer above this range to make sure your tile layer shows on top of MapsIndoors tiles."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zIndexRangeForMapsIndoorsTileLayers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange"}],"title":"zIndexRangeForMapsIndoorsTileLayers","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPMapControl(py)zIndexRangeForMapsIndoorsTileLayers","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"zIndexRangeForMapsIndoorsTileLayers"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl/zIndexRangeForMapsIndoorsTileLayers":{"role":"symbol","title":"zIndexRangeForMapsIndoorsTileLayers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zIndexRangeForMapsIndoorsTileLayers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange"}],"abstract":[{"type":"text","text":"Indexes reserved for MapsIndoors tile layers."},{"type":"text","text":" "},{"type":"text","text":"If you are adding tilelayers to a map with MapsIndoors tiles, you should set the zIndex of your tile layer above this range to make sure your tile layer shows on top of MapsIndoors tiles."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl\/zIndexRangeForMapsIndoorsTileLayers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"zIndexRangeForMapsIndoorsTileLayers"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/zindexrangeformapsindoorstilelayers"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl":{"role":"symbol","title":"MPMapControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"abstract":[{"type":"text","text":"Convenience class for setting up a Google map with MapsIndoors venues, buildings, locations and other map content."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"zIndexRangeForMapsIndoorsTileLayers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"zIndexRangeForMapsIndoorsTileLayers"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@S@_NSRange"},{"kind":"identifier","text":"zIndexRangeForMapsIndoorsTileLayers"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1zIndexRangeForMapsIndoorsTileLayers\/title","value":"zIndexRangeForMapsIndoorsTileLayers"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl~1zIndexRangeForMapsIndoorsTileLayers\/fragments","value":[{"kind":"identifier","text":"zIndexRangeForMapsIndoorsTileLayers"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"kind":"identifier","text":"MPMapControl"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}