{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"co2Level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Measurement","preciseIdentifier":"s:10Foundation11MeasurementV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Unit","preciseIdentifier":"c:objc(cs)NSUnit"},{"kind":"text","text":"> { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpco2liveupdate\/co2level"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpco2liveupdate\/co2level"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCO2LiveUpdate\/co2Level","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get the measured CO2 level for a given Location. Base unit is Parts Per Million (PPM)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"co2Level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Measurement","preciseIdentifier":"s:10Foundation11MeasurementV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Unit","preciseIdentifier":"c:objc(cs)NSUnit"},{"kind":"text","text":">"}],"title":"co2Level","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPCO2LiveUpdate(py)co2Level","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"co2Level"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCO2LiveUpdate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPCO2LiveUpdate":{"role":"symbol","title":"MPCO2LiveUpdate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPCO2LiveUpdate"}],"abstract":[{"type":"text","text":"Model for live CO2 measurement for a given Location."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCO2LiveUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPCO2LiveUpdate"}],"url":"\/documentation\/mapsindoors\/mpco2liveupdate"},"doc://MapsIndoors/documentation/MapsIndoors/MPCO2LiveUpdate/co2Level":{"role":"symbol","title":"co2Level","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"co2Level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Measurement","preciseIdentifier":"s:10Foundation11MeasurementV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Unit","preciseIdentifier":"c:objc(cs)NSUnit"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Get the measured CO2 level for a given Location. Base unit is Parts Per Million (PPM)."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCO2LiveUpdate\/co2Level","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"co2Level"}],"url":"\/documentation\/mapsindoors\/mpco2liveupdate\/co2level"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"co2Level"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"co2Level"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSMeasurement","preciseIdentifier":"c:objc(cs)NSMeasurement"},{"kind":"text","text":" *"},{"kind":"identifier","text":"co2Level"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCO2LiveUpdate\/title","value":"MPCO2LiveUpdate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCO2LiveUpdate\/fragments","value":[{"kind":"identifier","text":"MPCO2LiveUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCO2LiveUpdate~1co2Level\/title","value":"co2Level"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCO2LiveUpdate~1co2Level\/fragments","value":[{"kind":"identifier","text":"co2Level"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}