{"metadata":{"title":"initWithLiveUpdate:","roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithLiveUpdate:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MapsIndoors@objc(cs)MPCO2LiveUpdate(im)initWithLiveUpdate:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithLiveUpdate:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"MapsIndoors"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithLiveUpdate:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate","text":"MPLiveUpdate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"withLiveUpdate"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCO2LiveUpdate"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCO2LiveUpdate\/initWithLiveUpdate:"},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpco2liveupdate\/initwithliveupdate:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"MapsPeopleWhite.png":{"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null,"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate":{"abstract":[{"text":"Model for a Live Update. Used in ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","isActive":true,"type":"reference"}],"title":"MPLiveUpdate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPLiveUpdate"}],"role":"symbol","navigatorTitle":[{"text":"MPLiveUpdate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","type":"topic","url":"\/documentation\/mapsindoors\/mpliveupdate"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCO2LiveUpdate":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCO2LiveUpdate","abstract":[{"type":"text","text":"Model for live CO2 measurement for a given location."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPCO2LiveUpdate","kind":"identifier"}],"navigatorTitle":[{"text":"MPCO2LiveUpdate","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpco2liveupdate","kind":"symbol","title":"MPCO2LiveUpdate","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCO2LiveUpdate/initWithLiveUpdate:":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCO2LiveUpdate\/initWithLiveUpdate:","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithLiveUpdate:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithLiveUpdate:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpco2liveupdate\/initwithliveupdate:","kind":"symbol","title":"initWithLiveUpdate:","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/getLiveUpdate(forDomainType:)":{"abstract":[{"type":"text","text":"Get a live update based on a known domain type."}],"title":"getLiveUpdate(forDomainType:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getLiveUpdate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forDomainType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"MPLiveUpdate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate"},{"kind":"text","text":"?"}],"role":"symbol","required":true,"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","navigatorTitle":[{"text":"getLiveUpdateForDomainType:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mplocation\/getliveupdate(fordomaintype:)","type":"topic"}},"variantOverrides":[{"patch":[{"value":"MPLiveUpdate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/title"},{"value":[{"kind":"identifier","text":"MPLiveUpdate"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/fragments"},{"value":"MPCO2LiveUpdate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCO2LiveUpdate\/title"},{"value":[{"text":"MPCO2LiveUpdate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCO2LiveUpdate\/fragments"},{"value":"getLiveUpdateForDomainType:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getLiveUpdateForDomainType:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}