{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileSize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpfloortilelayer\/tilesize()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpfloortilelayer\/tilesize()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/tileSize()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get the indoor floor tile-size for rendering."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileSize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"tileSize()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPFloorTileLayer(cm)tileSize","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"tileSize"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPFloorTileLayer":{"role":"symbol","title":"MPFloorTileLayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloorTileLayer"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPFloorTileLayer"}],"url":"\/documentation\/mapsindoors\/mpfloortilelayer"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloorTileLayer/tileSize()":{"role":"symbol","title":"tileSize()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileSize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Get the indoor floor tile-size for rendering."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloorTileLayer\/tileSize()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tileSize"}],"url":"\/documentation\/mapsindoors\/mpfloortilelayer\/tilesize()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"tileSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"tileSize"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"tileSize"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer\/title","value":"MPFloorTileLayer"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer\/fragments","value":[{"kind":"identifier","text":"MPFloorTileLayer"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer~1tileSize()\/title","value":"tileSize"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloorTileLayer~1tileSize()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"tileSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}