{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Triggered when Venue selection has changed (programatically or by camera movement)."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpmapcontroldelegate\/didchange(selectedvenue:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpmapcontroldelegate\/didchange(selectedvenue:)"]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate"]]},"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPMapControlDelegate(im)didChangeWithSelectedVenue:","roleHeading":"Instance Method","title":"didChange(selectedVenue:)","symbolKind":"method","modules":[{"name":"MapsIndoors"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"selectedVenue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPVenue","text":"MPVenue","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"didChangeWithSelectedVenue:","kind":"identifier"}],"required":true,"role":"symbol"},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didChange(selectedVenue:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didChange","kind":"identifier"},{"kind":"text","text":"("},{"text":"selectedVenue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPVenue","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPVenue","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The newly selected Venue.","type":"text"}],"type":"paragraph"}],"name":"selectedVenue"}]},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"text":"Return true to indicate that you will handle the event, and bypass default MapsIndoors SDK behavior. Otherwise return false.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue":{"title":"MPVenue","url":"\/documentation\/mapsindoors\/mpvenue","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPVenue","kind":"identifier"}],"abstract":[{"text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"MPVenue","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue"},"MapsPeopleWhite.png":{"alt":null,"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate":{"url":"\/documentation\/mapsindoors\/mpmapcontroldelegate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate","navigatorTitle":[{"kind":"identifier","text":"MPMapControlDelegate"}],"title":"MPMapControlDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPMapControlDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Delegate protocol specification to react to the events that ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"},{"text":" emits.","type":"text"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"title":"MPMapControl","url":"\/documentation\/mapsindoors\/mpmapcontrol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"type":"topic","abstract":[{"text":"This is the control object for the visual representation of the MapsIndoors SDK.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate/didChange(selectedVenue:)":{"url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/didchange(selectedvenue:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didChange(selectedVenue:)","navigatorTitle":[{"text":"didChangeWithSelectedVenue:","kind":"identifier"}],"title":"didChange(selectedVenue:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"selectedVenue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPVenue","text":"MPVenue","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"text":"Triggered when Venue selection has changed (programatically or by camera movement).","type":"text"}],"type":"topic","kind":"symbol","required":true,"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"didChangeWithSelectedVenue:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didChangeWithSelectedVenue:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"didChangeWithSelectedVenue:"},{"kind":"text","text":"("},{"text":"id<MPVenue>","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPVenue","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"selectedVenue","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"MPVenue","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/fragments","value":[{"text":"MPVenue","kind":"identifier"}]},{"value":"MPMapControlDelegate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/fragments","value":[{"kind":"identifier","text":"MPMapControlDelegate"}],"op":"replace"},{"value":"MPMapControl","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"kind":"identifier","text":"MPMapControl"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didChange(selectedVenue:)\/title","value":"didChangeWithSelectedVenue:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didChange(selectedVenue:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"didChangeWithSelectedVenue:","kind":"identifier"}]}]}]}