{"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTap"},{"kind":"text","text":"("},{"kind":"externalParam","text":"coordinate"},{"text":": ","kind":"text"},{"text":"MPPoint","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"didTap(coordinate:)","externalID":"c:@M@MapsIndoors@objc(pl)MPMapControlDelegate(im)didTapWithCoordinate:","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"didTapWithCoordinate:"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpmapcontroldelegate\/didtap(coordinate:)"]},{"paths":["\/documentation\/mapsindoors\/mpmapcontroldelegate\/didtap(coordinate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didTap(coordinate:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didTap","kind":"identifier"},{"kind":"text","text":"("},{"text":"coordinate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","text":"MPPoint"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"coordinate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Map coordinate that was tapped."}]}]}]},{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Return true to indicate that you will handle the event, and bypass default MapsIndoors SDK behavior. Otherwise return false."}]}],"kind":"content"}],"abstract":[{"text":"Triggered when the map was tapped at the coordinate passed in to the method.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"title":"MPMapControl","url":"\/documentation\/mapsindoors\/mpmapcontrol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"type":"topic","abstract":[{"text":"This is the control object for the visual representation of the MapsIndoors SDK.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate/didTap(coordinate:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didTap(coordinate:)","navigatorTitle":[{"kind":"identifier","text":"didTapWithCoordinate:"}],"url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/didtap(coordinate:)","title":"didTap(coordinate:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTap"},{"kind":"text","text":"("},{"text":"coordinate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","text":"MPPoint"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Triggered when the map was tapped at the coordinate passed in to the method.","type":"text"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate":{"url":"\/documentation\/mapsindoors\/mpmapcontroldelegate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate","navigatorTitle":[{"kind":"identifier","text":"MPMapControlDelegate"}],"title":"MPMapControlDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPMapControlDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Delegate protocol specification to react to the events that ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"},{"text":" emits.","type":"text"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPoint":{"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint","title":"MPPoint","type":"topic","url":"\/documentation\/mapsindoors\/mppoint","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPPoint","kind":"identifier"}],"navigatorTitle":[{"text":"MPPoint","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didTapWithCoordinate:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"didTapWithCoordinate:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"didTapWithCoordinate:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint","kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"coordinate"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl","op":"replace"},{"op":"replace","value":[{"text":"MPMapControl","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didTap(coordinate:)\/title","value":"didTapWithCoordinate:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didTap(coordinate:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didTapWithCoordinate:","kind":"identifier"}]},{"value":"MPMapControlDelegate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/fragments","value":[{"kind":"identifier","text":"MPMapControlDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPoint\/title","value":"MPPoint"},{"op":"replace","value":[{"text":"MPPoint","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPoint\/fragments"}]}]}