{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didTapInfoWindow(location:)"},"sections":[],"abstract":[{"type":"text","text":"Triggered when the info window of a "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","isActive":true,"type":"reference"},{"type":"text","text":" was tapped."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpmapcontroldelegate\/didtapinfowindow(location:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpmapcontroldelegate\/didtapinfowindow(location:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didTapInfoWindow","kind":"identifier"},{"kind":"text","text":"("},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","text":"MPLocation","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}]},{"parameters":[{"name":"location","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","type":"reference","isActive":true},{"type":"text","text":" of the info window that was tapped."}]}]}],"kind":"parameters"},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Return true to indicate that you will handle the event, and bypass default MapsIndoors SDK behavior. Otherwise return false."}]}],"kind":"content"}],"metadata":{"title":"didTapInfoWindow(location:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"didTapInfoWindowWithLocation:"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPMapControlDelegate(im)didTapInfoWindowWithLocation:","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didTapInfoWindow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPLocation","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"role":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontrol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPMapControl","kind":"identifier"}],"abstract":[{"text":"This is the control object for the visual representation of the MapsIndoors SDK.","type":"text"}],"navigatorTitle":[{"text":"MPMapControl","kind":"identifier"}],"kind":"symbol","type":"topic","title":"MPMapControl"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate/didTapInfoWindow(location:)":{"abstract":[{"type":"text","text":"Triggered when the info window of a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation"},{"text":" was tapped.","type":"text"}],"kind":"symbol","title":"didTapInfoWindow(location:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didTapInfoWindow(location:)","navigatorTitle":[{"kind":"identifier","text":"didTapInfoWindowWithLocation:"}],"url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/didtapinfowindow(location:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didTapInfoWindow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","text":"MPLocation"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation":{"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","abstract":[{"type":"text","text":"This holds the data for a single location and a marker to display the data on a map."}],"url":"\/documentation\/mapsindoors\/mplocation","role":"symbol","title":"MPLocation","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"navigatorTitle":[{"text":"MPLocation","kind":"identifier"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPMapControlDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate protocol specification to react to the events that "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"},{"text":" emits.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontroldelegate","title":"MPMapControlDelegate","navigatorTitle":[{"kind":"identifier","text":"MPMapControlDelegate"}]},"MapsPeopleWhite.png":{"alt":null,"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"didTapInfoWindowWithLocation:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didTapInfoWindowWithLocation:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"didTapInfoWindowWithLocation:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPLocation","text":"id<MPLocation>"},{"kind":"text","text":" *) "},{"text":"location","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"MPMapControl","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title"},{"value":[{"text":"MPMapControl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments"},{"value":"didTapInfoWindowWithLocation:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didTapInfoWindow(location:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didTapInfoWindowWithLocation:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didTapInfoWindow(location:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/title","value":"MPLocation"},{"op":"replace","value":[{"text":"MPLocation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/fragments"},{"value":"MPMapControlDelegate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/fragments","value":[{"text":"MPMapControlDelegate","kind":"identifier"}]}]}]}