{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusedBuildingDidChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"building"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","preciseIdentifier":"c:objc(cs)MPLocation","text":"MPLocation"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapcontroldelegate\/focusedbuildingdidchange(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmapcontroldelegate\/focusedbuildingdidchange(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/focusedBuildingDidChange(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"focusedBuildingDidChange:"}],"role":"symbol","title":"focusedBuildingDidChange(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusedBuildingDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:objc(pl)MPMapControlDelegate(im)focusedBuildingDidChange:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControlDelegate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPMapControlDelegate":{"role":"symbol","title":"MPMapControlDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControlDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol specification to hold the floor change event."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControlDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMapControlDelegate"}],"url":"\/documentation\/mapsindoors\/mpmapcontroldelegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class":{"role":"symbol","title":"MPLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"abstract":[{"type":"text","text":"This class holds the data for a single location and a marker to display the data on a map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControlDelegate/focusedBuildingDidChange(_:)":{"navigatorTitle":[{"kind":"identifier","text":"focusedBuildingDidChange:"}],"role":"symbol","title":"focusedBuildingDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusedBuildingDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/focusedBuildingDidChange(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/focusedbuildingdidchange(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"focusedBuildingDidChange:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"focusedBuildingDidChange:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"focusedBuildingDidChange:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","preciseIdentifier":"c:objc(cs)MPLocation","text":"MPLocation"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"building"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/title","value":"MPMapControlDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/fragments","value":[{"kind":"identifier","text":"MPMapControlDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/title","value":"MPLocation"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/fragments","value":[{"kind":"identifier","text":"MPLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1focusedBuildingDidChange(_:)\/title","value":"focusedBuildingDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1focusedBuildingDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"focusedBuildingDidChange:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}