{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getImageSizeForLocationCluster"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCount"},{"kind":"text","text":" "},{"kind":"internalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clusterId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapcontroldelegate\/getimagesizeforlocationcluster(withcount:clusterid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmapcontroldelegate\/getimagesizeforlocationcluster(withcount:clusterid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/getImageSizeForLocationCluster(withCount:clusterId:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getImageSizeForLocationClusterWithCount:clusterId:"}],"role":"symbol","title":"getImageSizeForLocationCluster(withCount:clusterId:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getImageSizeForLocationCluster"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clusterId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"symbolKind":"method","externalID":"c:objc(pl)MPMapControlDelegate(im)getImageSizeForLocationClusterWithCount:clusterId:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControlDelegate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPMapControlDelegate":{"role":"symbol","title":"MPMapControlDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControlDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol specification to hold the floor change event."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControlDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMapControlDelegate"}],"url":"\/documentation\/mapsindoors\/mpmapcontroldelegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControlDelegate/getImageSizeForLocationCluster(withCount:clusterId:)":{"navigatorTitle":[{"kind":"identifier","text":"getImageSizeForLocationClusterWithCount:clusterId:"}],"role":"symbol","title":"getImageSizeForLocationCluster(withCount:clusterId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getImageSizeForLocationCluster"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clusterId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/getImageSizeForLocationCluster(withCount:clusterId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/getimagesizeforlocationcluster(withcount:clusterid:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getImageSizeForLocationClusterWithCount:clusterId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getImageSizeForLocationClusterWithCount:clusterId:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"kind":"identifier","text":"getImageSizeForLocationClusterWithCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"count"},{"kind":"text","text":" "},{"kind":"identifier","text":"clusterId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"clusterId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/title","value":"MPMapControlDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/fragments","value":[{"kind":"identifier","text":"MPMapControlDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1getImageSizeForLocationCluster(withCount:clusterId:)\/title","value":"getImageSizeForLocationClusterWithCount:clusterId:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1getImageSizeForLocationCluster(withCount:clusterId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getImageSizeForLocationClusterWithCount:clusterId:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}