{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate"]]},"sections":[],"metadata":{"modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"onPositionUpdate:","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPMapControlDelegate(im)onPositionUpdate:","symbolKind":"method","title":"onPositionUpdate(position:)","roleHeading":"Instance Method","role":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onPositionUpdate","kind":"identifier"},{"kind":"text","text":"("},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPPositionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPositionResult"},{"text":")","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/onPositionUpdate(position:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(onPositionUpdate:) ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPositionUpdate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"position"},{"text":": ","kind":"text"},{"text":"MPPositionResult","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPositionResult"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The position result as estimated or calculated by a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","isActive":true},{"type":"text","text":"."}]}],"name":"position"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapcontroldelegate\/onpositionupdate(position:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmapcontroldelegate\/onpositionupdate(position:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Called when "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"},{"text":" receives a new user position from the active ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","type":"reference","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"This is the method you should implement if your app needs to be notified about each new user position.","type":"text"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionProvider":{"url":"\/documentation\/mapsindoors\/mppositionprovider","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProvider"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPPositionProvider"}],"title":"MPPositionProvider","abstract":[{"type":"text","text":"Protocol specifying how an indoor positioning provider should be implemented if the users location is to be exposed to "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true},{"type":"text","text":"."}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPMapControlDelegate","kind":"identifier"}],"abstract":[{"text":"Delegate protocol specification to react to the events that ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true},{"text":" emits.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpmapcontroldelegate","title":"MPMapControlDelegate","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPMapControlDelegate"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate/onPositionUpdate(position:)":{"url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/onpositionupdate(position:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/onPositionUpdate(position:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPositionUpdate"},{"text":"(","kind":"text"},{"text":"position","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPositionResult","text":"MPPositionResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","required":true,"title":"onPositionUpdate(position:)","abstract":[{"type":"text","text":"Called when "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true,"type":"reference"},{"type":"text","text":" receives a new user position from the active "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This is the method you should implement if your app needs to be notified about each new user position."}],"navigatorTitle":[{"text":"onPositionUpdate:","kind":"identifier"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"abstract":[{"type":"text","text":"This is the control object for the visual representation of the MapsIndoors SDK."}],"url":"\/documentation\/mapsindoors\/mpmapcontrol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPMapControl"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"type":"topic","kind":"symbol","title":"MPMapControl","role":"symbol"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionResult":{"role":"symbol","abstract":[{"text":"Instances of this class holds a Position result returned by a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","isActive":true},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mppositionresult","navigatorTitle":[{"text":"MPPositionResult","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPPositionResult"}],"title":"MPPositionResult"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"onPositionUpdate:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onPositionUpdate:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onPositionUpdate:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPositionResult","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult","text":"MPPositionResult"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"position"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider\/title","value":"MPPositionProvider","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider\/fragments","value":[{"text":"MPPositionProvider","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/title","value":"MPMapControlDelegate"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/fragments","value":[{"text":"MPMapControlDelegate","kind":"identifier"}],"op":"replace"},{"value":"onPositionUpdate:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1onPositionUpdate(position:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1onPositionUpdate(position:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onPositionUpdate:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"text":"MPMapControl","kind":"identifier"}]},{"value":"MPPositionResult","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult\/title"},{"value":[{"text":"MPPositionResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}