{"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onDirectionsRendererChangedFloor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"floorIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPDirectionsRendererDelegate(im)onDirectionsRendererChangedFloorWithFloorIndex:","navigatorTitle":[{"kind":"identifier","text":"onDirectionsRendererChangedFloorWithFloorIndex:"}],"symbolKind":"method","role":"symbol","required":true,"modules":[{"name":"MapsIndoors"}],"title":"onDirectionsRendererChangedFloor(floorIndex:)"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDirectionsRendererChangedFloor"},{"kind":"text","text":"("},{"text":"floorIndex","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRendererDelegate\/onDirectionsRendererChangedFloor(floorIndex:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRendererDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsrendererdelegate\/ondirectionsrendererchangedfloor(floorindex:)"]},{"paths":["\/documentation\/mapsindoors\/mpdirectionsrendererdelegate\/ondirectionsrendererchangedfloor(floorindex:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsRendererDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPDirectionsRendererDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"MPDirectionsRendererDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRendererDelegate","abstract":[{"type":"text","text":"Protocol to conform to when implementing a directions renderer for MapsIndoors."}],"role":"symbol","type":"topic","kind":"symbol","title":"MPDirectionsRendererDelegate","url":"\/documentation\/mapsindoors\/mpdirectionsrendererdelegate"},"MapsPeopleWhite.png":{"type":"image","alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsRendererDelegate/onDirectionsRendererChangedFloor(floorIndex:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onDirectionsRendererChangedFloor","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"floorIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onDirectionsRendererChangedFloorWithFloorIndex:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRendererDelegate\/onDirectionsRendererChangedFloor(floorIndex:)","abstract":[],"required":true,"type":"topic","role":"symbol","kind":"symbol","title":"onDirectionsRendererChangedFloor(floorIndex:)","url":"\/documentation\/mapsindoors\/mpdirectionsrendererdelegate\/ondirectionsrendererchangedfloor(floorindex:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"onDirectionsRendererChangedFloorWithFloorIndex:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"onDirectionsRendererChangedFloorWithFloorIndex:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"onDirectionsRendererChangedFloorWithFloorIndex:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"floorIndex","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"MPDirectionsRendererDelegate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRendererDelegate\/title"},{"value":[{"kind":"identifier","text":"MPDirectionsRendererDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRendererDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRendererDelegate~1onDirectionsRendererChangedFloor(floorIndex:)\/title","op":"replace","value":"onDirectionsRendererChangedFloorWithFloorIndex:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRendererDelegate~1onDirectionsRendererChangedFloor(floorIndex:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onDirectionsRendererChangedFloorWithFloorIndex:"}]}]}]}