{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"venue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class","preciseIdentifier":"c:objc(cs)MPVenue","text":"MPVenue"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andFloor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"floor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class","preciseIdentifier":"c:objc(cs)MPFloor","text":"MPFloor"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppersistentcachegmstilelayer\/init(venue:andfloor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppersistentcachegmstilelayer\/init(venue:andfloor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/init(venue:andFloor:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Instantiate using a venue and a floor object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"venue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPVenue","preciseIdentifier":"c:objc(cs)MPVenue"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andFloor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPFloor","preciseIdentifier":"c:objc(cs)MPFloor"},{"kind":"text","text":"?)"}],"title":"init(venue:andFloor:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)MPPersistentCacheGMSTileLayer(im)initWithVenue:andFloor:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"initWithVenue:andFloor:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class":{"role":"symbol","title":"MPVenue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenue"}],"abstract":[{"type":"text","text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenue"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloor-swift.class":{"role":"symbol","title":"MPFloor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloor"}],"abstract":[{"type":"text","text":"Floor data model. Holds the floor geometry, display name, z-index and id of the building it belongs to."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPFloor"}],"url":"\/documentation\/mapsindoors\/mpfloor-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPPersistentCacheGMSTileLayer/init(venue:andFloor:)":{"role":"symbol","title":"init(venue:andFloor:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"venue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPVenue","preciseIdentifier":"c:objc(cs)MPVenue"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andFloor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPFloor","preciseIdentifier":"c:objc(cs)MPFloor"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Instantiate using a venue and a floor object."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/init(venue:andFloor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithVenue:andFloor:"}],"url":"\/documentation\/mapsindoors\/mppersistentcachegmstilelayer\/init(venue:andfloor:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPPersistentCacheGMSTileLayer":{"role":"symbol","title":"MPPersistentCacheGMSTileLayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPersistentCacheGMSTileLayer"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPersistentCacheGMSTileLayer"}],"url":"\/documentation\/mapsindoors\/mppersistentcachegmstilelayer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithVenue:andFloor:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVenue:andFloor:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithVenue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class","preciseIdentifier":"c:objc(cs)MPVenue","text":"MPVenue"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"venue"},{"kind":"text","text":" "},{"kind":"identifier","text":"andFloor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class","preciseIdentifier":"c:objc(cs)MPFloor","text":"MPFloor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"floor"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class\/title","value":"MPVenue"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class\/fragments","value":[{"kind":"identifier","text":"MPVenue"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class\/title","value":"MPFloor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class\/fragments","value":[{"kind":"identifier","text":"MPFloor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer~1init(venue:andFloor:)\/title","value":"initWithVenue:andFloor:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer~1init(venue:andFloor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVenue:andFloor:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer\/title","value":"MPPersistentCacheGMSTileLayer"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer\/fragments","value":[{"kind":"identifier","text":"MPPersistentCacheGMSTileLayer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}