{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseUrl"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppersistentcachegmstilelayer\/parseurl()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppersistentcachegmstilelayer\/parseurl()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/parseUrl()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Parse the url template. Normally, this is done automatically"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseUrl"},{"kind":"text","text":"()"}],"title":"parseUrl()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPPersistentCacheGMSTileLayer(im)parseUrl","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"parseUrl"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPPersistentCacheGMSTileLayer":{"role":"symbol","title":"MPPersistentCacheGMSTileLayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPersistentCacheGMSTileLayer"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPersistentCacheGMSTileLayer"}],"url":"\/documentation\/mapsindoors\/mppersistentcachegmstilelayer"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPPersistentCacheGMSTileLayer/parseUrl()":{"role":"symbol","title":"parseUrl()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseUrl"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Parse the url template. Normally, this is done automatically"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/parseUrl()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parseUrl"}],"url":"\/documentation\/mapsindoors\/mppersistentcachegmstilelayer\/parseurl()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"parseUrl"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parseUrl"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"parseUrl"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer\/title","value":"MPPersistentCacheGMSTileLayer"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer\/fragments","value":[{"kind":"identifier","text":"MPPersistentCacheGMSTileLayer"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer~1parseUrl()\/title","value":"parseUrl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer~1parseUrl()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parseUrl"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}