{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subdomains"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppersistentcachegmstilelayer\/subdomains"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppersistentcachegmstilelayer\/subdomains"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/subdomains","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Array of strings identifying subdomains. If this property is set, and the url template contains the parameter {subdomain}, the tilelayer will do round-robin over the subdomains specified."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subdomains"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"title":"subdomains","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPPersistentCacheGMSTileLayer(py)subdomains","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"subdomains"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPPersistentCacheGMSTileLayer/subdomains":{"role":"symbol","title":"subdomains","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subdomains"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Array of strings identifying subdomains. If this property is set, and the url template contains the parameter {subdomain}, the tilelayer will do round-robin over the subdomains specified."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/subdomains","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subdomains"}],"url":"\/documentation\/mapsindoors\/mppersistentcachegmstilelayer\/subdomains"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPPersistentCacheGMSTileLayer":{"role":"symbol","title":"MPPersistentCacheGMSTileLayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPersistentCacheGMSTileLayer"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPersistentCacheGMSTileLayer"}],"url":"\/documentation\/mapsindoors\/mppersistentcachegmstilelayer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"subdomains"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"subdomains"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"subdomains"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer~1subdomains\/title","value":"subdomains"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer~1subdomains\/fragments","value":[{"kind":"identifier","text":"subdomains"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer\/title","value":"MPPersistentCacheGMSTileLayer"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer\/fragments","value":[{"kind":"identifier","text":"MPPersistentCacheGMSTileLayer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}