{"sections":[],"abstract":[{"text":"Called when a Location is selected, and if a UIView is returned from this method that UIView will be shown instead of the default MapsIndoors info window.","type":"text"}],"kind":"symbol","metadata":{"roleHeading":"Instance Method","modules":[{"name":"MapsIndoors"}],"symbolKind":"method","required":true,"navigatorTitle":[{"kind":"identifier","text":"infoWindowForLocation:"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPCustomInfoWindow(im)infoWindowForLocation:","title":"infoWindowFor(location:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"infoWindowFor"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"location"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","kind":"typeIdentifier","text":"MPLocation"},{"text":") -> ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomInfoWindow\/infoWindowFor(location:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomInfoWindow"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpcustominfowindow\/infowindowfor(location:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpcustominfowindow\/infowindowfor(location:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"infoWindowFor","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"location"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","kind":"typeIdentifier","text":"MPLocation"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"location","content":[{"inlineContent":[{"text":"The selected Location","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The view that will replace the default MapsIndoors info window"}],"type":"paragraph"}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomInfoWindow":{"role":"symbol","abstract":[{"text":"Optionally create your own info window for the SDK to use.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpcustominfowindow","navigatorTitle":[{"kind":"identifier","text":"MPCustomInfoWindow"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomInfoWindow","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPCustomInfoWindow","kind":"identifier"}],"title":"MPCustomInfoWindow"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"title":"MPLocation","kind":"symbol","url":"\/documentation\/mapsindoors\/mplocation","abstract":[{"type":"text","text":"This holds the data for a single location and a marker to display the data on a map."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"MapsPeopleWhite.png":{"type":"image","alt":null,"identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomInfoWindow/infoWindowFor(location:)":{"role":"symbol","abstract":[{"text":"Called when a Location is selected, and if a UIView is returned from this method that UIView will be shown instead of the default MapsIndoors info window.","type":"text"}],"kind":"symbol","required":true,"url":"\/documentation\/mapsindoors\/mpcustominfowindow\/infowindowfor(location:)","navigatorTitle":[{"kind":"identifier","text":"infoWindowForLocation:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomInfoWindow\/infoWindowFor(location:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"infoWindowFor"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","text":"MPLocation","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"title":"infoWindowFor(location:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"infoWindowForLocation:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"infoWindowForLocation:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"infoWindowForLocation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<MPLocation>","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPLocation","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"location"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomInfoWindow\/title","op":"replace","value":"MPCustomInfoWindow"},{"value":[{"kind":"identifier","text":"MPCustomInfoWindow"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomInfoWindow\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/title","value":"MPLocation","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MPLocation"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomInfoWindow~1infoWindowFor(location:)\/title","op":"replace","value":"infoWindowForLocation:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomInfoWindow~1infoWindowFor(location:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"infoWindowForLocation:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}