{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQueryMode","preciseIdentifier":"c:@E@MPLocationQueryMode","text":"MPLocationQueryMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The location query mode determines what happens when a MPLocationQuery is re-used, and executed multiple time."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"MPLocationQueryModeNormal:"},{"type":"text","text":" "},{"type":"text","text":"Results will be delivered for all executions of the query."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"MPLocationQueryModeAutocomplete:"},{"type":"text","text":" "},{"type":"text","text":"If a query is already executing it will be cancelled when a new query is started."},{"type":"text","text":" "},{"type":"text","text":"This allows starting a query as th euser types, where only the result of the last query is relevant."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationquery\/querymode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationquery\/querymode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/queryMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Location query mode.  Defaults to MPLocationQueryModeNormal."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationQueryMode","preciseIdentifier":"c:@E@MPLocationQueryMode"}],"title":"queryMode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPLocationQuery(py)queryMode","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"queryMode"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery/queryMode":{"role":"symbol","title":"queryMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationQueryMode","preciseIdentifier":"c:@E@MPLocationQueryMode"}],"abstract":[{"type":"text","text":"Location query mode.  Defaults to MPLocationQueryModeNormal."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery\/queryMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"queryMode"}],"url":"\/documentation\/mapsindoors\/mplocationquery\/querymode"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQueryMode":{"role":"symbol","title":"MPLocationQueryMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationQueryMode"}],"abstract":[{"type":"text","text":"Locations query mode"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQueryMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationQueryMode"}],"url":"\/documentation\/mapsindoors\/mplocationquerymode"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationQuery":{"role":"symbol","title":"MPLocationQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationQuery"}],"abstract":[{"type":"text","text":"Locations query object used in conjunction with the MPLocationsProvider"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationQuery"}],"url":"\/documentation\/mapsindoors\/mplocationquery"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"queryMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"queryMode"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationQueryMode","preciseIdentifier":"c:@E@MPLocationQueryMode","text":"MPLocationQueryMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryMode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1queryMode\/title","value":"queryMode"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery~1queryMode\/fragments","value":[{"kind":"identifier","text":"queryMode"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQueryMode\/title","value":"MPLocationQueryMode"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQueryMode\/fragments","value":[{"kind":"identifier","text":"MPLocationQueryMode"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery\/title","value":"MPLocationQuery"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationQuery\/fragments","value":[{"kind":"identifier","text":"MPLocationQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}