{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightOutlineColor"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationdisplayrule\/highlightoutlinecolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationdisplayrule\/highlightoutlinecolor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/highlightOutlineColor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The highlight outline color."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightOutlineColor"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"title":"highlightOutlineColor","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPLocationDisplayRule(py)highlightOutlineColor","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"highlightOutlineColor"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/highlightOutlineColor":{"role":"symbol","title":"highlightOutlineColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightOutlineColor"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The highlight outline color."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/highlightOutlineColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"highlightOutlineColor"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/highlightoutlinecolor"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule":{"role":"symbol","title":"MPLocationDisplayRule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationDisplayRule"}],"abstract":[{"type":"text","text":"This class serves as a display rule for locations."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationDisplayRule"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"highlightOutlineColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"highlightOutlineColor"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIColor<Optional>","preciseIdentifier":"c:Q$objc(cs)UIColorobjc(pl)Optional"},{"kind":"text","text":" *"},{"kind":"identifier","text":"highlightOutlineColor"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1highlightOutlineColor\/title","value":"highlightOutlineColor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1highlightOutlineColor\/fragments","value":[{"kind":"identifier","text":"highlightOutlineColor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule\/title","value":"MPLocationDisplayRule"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule\/fragments","value":[{"kind":"identifier","text":"MPLocationDisplayRule"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}