{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"zLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationdisplayrule\/show(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationdisplayrule\/show(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/show(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Processes the rule conditions at the given map zoom level."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"show(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPLocationDisplayRule(im)show:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"show:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/show(_:)":{"role":"symbol","title":"show(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Processes the rule conditions at the given map zoom level."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/show(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"show:"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/show(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule":{"role":"symbol","title":"MPLocationDisplayRule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationDisplayRule"}],"abstract":[{"type":"text","text":"This class serves as a display rule for locations."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationDisplayRule"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"show:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"show:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"show:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":")"},{"kind":"internalParam","text":"zLevel"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1show(_:)\/title","value":"show:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1show(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"show:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule\/title","value":"MPLocationDisplayRule"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule\/fragments","value":[{"kind":"identifier","text":"MPLocationDisplayRule"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}