{"abstract":[{"type":"text","text":"Set authentication configuration. This may be used if the Booking Service should book on behalf of an authenticated user. Otherwise the attempted bookings will be anonymous."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"authenticationConfig","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPBookingAuthConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBookingAuthConfig","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingAuthConfig"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"title":"authenticationConfig","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authenticationConfig"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBookingAuthConfig","text":"MPBookingAuthConfig","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"authenticationConfig","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"property","externalID":"c:@M@MapsIndoors@objc(pl)MPBookingService(py)authenticationConfig","roleHeading":"Instance Property","required":true,"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/authenticationConfig","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpbookingservice\/authenticationconfig"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpbookingservice\/authenticationconfig"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService":{"title":"MPBookingService","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPBookingService","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService","navigatorTitle":[{"kind":"identifier","text":"MPBookingService"}],"abstract":[{"type":"text","text":"MPBookingService allows for access to the MapsIndoors booking service."},{"type":"text","text":" "},{"type":"text","text":"The booking service is a special integration that has to be enabled in the MapsIndoors cloud systems."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpbookingservice","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService/authenticationConfig":{"required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/authenticationConfig","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationConfig"},{"text":": ","kind":"text"},{"text":"MPBookingAuthConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBookingAuthConfig"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"authenticationConfig","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpbookingservice\/authenticationconfig","kind":"symbol","title":"authenticationConfig","abstract":[{"text":"Set authentication configuration. This may be used if the Booking Service should book on behalf of an authenticated user. Otherwise the attempted bookings will be anonymous.","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingAuthConfig":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPBookingAuthConfig","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingAuthConfig","navigatorTitle":[{"kind":"identifier","text":"MPBookingAuthConfig"}],"title":"MPBookingAuthConfig","abstract":[{"type":"text","text":"Booking authentication configuration model. This may be used if the "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService","type":"reference","isActive":true},{"type":"text","text":" should book on behalf of an authenticated user."}],"type":"topic","url":"\/documentation\/mapsindoors\/mpbookingauthconfig"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"authenticationConfig"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"authenticationConfig"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingAuthConfig","kind":"typeIdentifier","text":"MPBookingAuthConfig","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBookingAuthConfig"},{"text":" * ","kind":"text"},{"text":"authenticationConfig","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService\/title","value":"MPBookingService","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService\/fragments","value":[{"text":"MPBookingService","kind":"identifier"}]},{"value":"authenticationConfig","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1authenticationConfig\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1authenticationConfig\/fragments","value":[{"kind":"identifier","text":"authenticationConfig"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingAuthConfig\/title","op":"replace","value":"MPBookingAuthConfig"},{"value":[{"text":"MPBookingAuthConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingAuthConfig\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}