{"metadata":{"roleHeading":"Instance Method","required":true,"navigatorTitle":[{"kind":"identifier","text":"bookingsUsingQuery:completionHandler:"}],"title":"bookingsUsing(query:)","symbolKind":"method","externalID":"c:@M@MapsIndoors@objc(pl)MPBookingService(im)bookingsUsingQuery:completionHandler:","modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bookingsUsing","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"text":"MPBookingsQuery","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBookingsQuery","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"MPBooking","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking"},{"kind":"text","text":"]?"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/mapsindoors\/mpbookingservice\/bookingsusing(query:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpbookingservice\/bookingsusing(query:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bookingsUsing","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"query"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPBookingsQuery","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBookingsQuery","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingsQuery"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> [","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking","kind":"typeIdentifier","text":"MPBooking","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking"},{"text":"]?","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"query","content":[{"type":"paragraph","inlineContent":[{"text":"Query to apply.","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The existing bookings within the conditions set by the "},{"code":"query","type":"codeVoice"},{"type":"text","text":" parameter."}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/bookingsUsing(query:)"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService"]]},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Get existing booking according the the given "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingsQuery","isActive":true}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/bookingId":{"abstract":[{"type":"text","text":"The id of the Booking to be used for future references."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/bookingId","navigatorTitle":[{"kind":"identifier","text":"bookingId"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bookingId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/mapsindoors\/mpbooking\/bookingid","role":"symbol","type":"topic","kind":"symbol","title":"bookingId"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking":{"title":"MPBooking","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking","navigatorTitle":[{"text":"MPBooking","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPBooking","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpbooking","role":"symbol","type":"topic","kind":"symbol","abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking"},{"type":"text","text":" represents an existing booking object or a booking to be made."},{"type":"text","text":" "},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/bookingId","type":"reference"},{"text":" will be non-","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" for an existing booking, and ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" for a booking to be made.","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingsQuery":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPBookingsQuery","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingsQuery","abstract":[{"text":"Query object to be used with ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/bookingsUsing(query:)"},{"type":"text","text":" "},{"text":"Queries can be either for a location or a user (organizerId), and may optionally be limited to a given timespan.","type":"text"}],"title":"MPBookingsQuery","navigatorTitle":[{"text":"MPBookingsQuery","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpbookingsquery","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService/bookingsUsing(query:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bookingsUsing"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBookingsQuery","kind":"typeIdentifier","text":"MPBookingsQuery"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking","text":"MPBooking"},{"kind":"text","text":"]?"}],"kind":"symbol","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/bookingsUsing(query:)","abstract":[{"type":"text","text":"Get existing booking according the the given "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingsQuery"}],"title":"bookingsUsing(query:)","navigatorTitle":[{"kind":"identifier","text":"bookingsUsingQuery:completionHandler:"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpbookingservice\/bookingsusing(query:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService":{"title":"MPBookingService","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPBookingService","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService","navigatorTitle":[{"kind":"identifier","text":"MPBookingService"}],"abstract":[{"type":"text","text":"MPBookingService allows for access to the MapsIndoors booking service."},{"type":"text","text":" "},{"type":"text","text":"The booking service is a special integration that has to be enabled in the MapsIndoors cloud systems."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpbookingservice","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"bookingsUsingQuery:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bookingsUsingQuery:completionHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"bookingsUsingQuery:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MPBookingsQuery","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingsQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBookingsQuery"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"query"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completionHandler:"},{"text":"(","kind":"text"},{"text":"void (^)(NSArray<MPBooking *> *, NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)"},{"text":") ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"bookingId","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1bookingId\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1bookingId\/fragments","op":"replace","value":[{"kind":"identifier","text":"bookingId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking\/title","value":"MPBooking"},{"value":[{"text":"MPBooking","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking\/fragments","op":"replace"},{"value":"MPBookingsQuery","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingsQuery\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingsQuery\/fragments","value":[{"kind":"identifier","text":"MPBookingsQuery"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1bookingsUsing(query:)\/title","op":"replace","value":"bookingsUsingQuery:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1bookingsUsing(query:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bookingsUsingQuery:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService\/title","value":"MPBookingService"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService\/fragments","value":[{"text":"MPBookingService","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}