{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationsConfiguredForBooking"},{"kind":"text","text":"("},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookableQuery","preciseIdentifier":"c:objc(cs)MPBookableQuery","text":"MPBookableQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpLocationListCompletion","preciseIdentifier":"c:MPBookingService.h@T@mpLocationListCompletion","text":"mpLocationListCompletion"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"query","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Filter to apply"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Completion handler"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbookingservice\/getlocationsconfiguredforbooking(query:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbookingservice\/getlocationsconfiguredforbooking(query:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookingService\/getLocationsConfiguredForBooking(query:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Query for locations that are configured for booking given the query filter."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationsConfiguredForBooking"},{"kind":"text","text":"("},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPBookableQuery","preciseIdentifier":"c:objc(cs)MPBookableQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpLocationListCompletion","preciseIdentifier":"c:MPBookingService.h@T@mpLocationListCompletion"},{"kind":"text","text":")"}],"title":"getLocationsConfiguredForBooking(query:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPBookingService(im)getLocationsConfiguredForBooking:completion:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getLocationsConfiguredForBooking:completion:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookingService"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/mpLocationListCompletion":{"role":"symbol","title":"mpLocationListCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpLocationListCompletion"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpLocationListCompletion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpLocationListCompletion"}],"url":"\/documentation\/mapsindoors\/mplocationlistcompletion"},"doc://MapsIndoors/documentation/MapsIndoors/MPBookingService":{"role":"symbol","title":"MPBookingService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBookingService"}],"abstract":[{"type":"text","text":"MPBookingService allows for access to the MapsIndoors booking service."},{"type":"text","text":" "},{"type":"text","text":"The booking service is a special integration that has to be enabled in the MapsIndoors cloud systems."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookingService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBookingService"}],"url":"\/documentation\/mapsindoors\/mpbookingservice"},"doc://MapsIndoors/documentation/MapsIndoors/MPBookableQuery":{"role":"symbol","title":"MPBookableQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBookableQuery"}],"abstract":[{"type":"text","text":"Query object to be used with MPBookingService.getBookableLocationsUsingQuery()"},{"type":"text","text":" "},{"type":"text","text":"Queries are defined by a required timespan and a number of optional filter properties."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookableQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBookableQuery"}],"url":"\/documentation\/mapsindoors\/mpbookablequery"},"doc://MapsIndoors/documentation/MapsIndoors/MPBookingService/getLocationsConfiguredForBooking(query:completion:)":{"role":"symbol","title":"getLocationsConfiguredForBooking(query:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationsConfiguredForBooking"},{"kind":"text","text":"("},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPBookableQuery","preciseIdentifier":"c:objc(cs)MPBookableQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpLocationListCompletion","preciseIdentifier":"c:MPBookingService.h@T@mpLocationListCompletion"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Query for locations that are configured for booking given the query filter."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookingService\/getLocationsConfiguredForBooking(query:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getLocationsConfiguredForBooking:completion:"}],"url":"\/documentation\/mapsindoors\/mpbookingservice\/getlocationsconfiguredforbooking(query:completion:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getLocationsConfiguredForBooking:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationsConfiguredForBooking:completion:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getLocationsConfiguredForBooking:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookableQuery","preciseIdentifier":"c:objc(cs)MPBookableQuery","text":"MPBookableQuery"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"query"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<MPLocation *> *, NSError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpLocationListCompletion\/title","value":"mpLocationListCompletion"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpLocationListCompletion\/fragments","value":[{"kind":"identifier","text":"mpLocationListCompletion"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookingService\/title","value":"MPBookingService"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookingService\/fragments","value":[{"kind":"identifier","text":"MPBookingService"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookableQuery\/title","value":"MPBookableQuery"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookableQuery\/fragments","value":[{"kind":"identifier","text":"MPBookableQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookingService~1getLocationsConfiguredForBooking(query:completion:)\/title","value":"getLocationsConfiguredForBooking:completion:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookingService~1getLocationsConfiguredForBooking(query:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationsConfiguredForBooking:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}