{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"performBooking"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"booking","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MPBooking","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking","text":"MPBooking"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Identification of resource, timespan etc to book."}],"type":"paragraph"}],"name":"booking"}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The confirmed booking."}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"performBooking","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MPBooking","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking","text":"MPBooking"},{"text":"?","kind":"text"}],"title":"performBooking(_:)","modules":[{"name":"MapsIndoors"}],"symbolKind":"method","externalID":"c:@M@MapsIndoors@objc(pl)MPBookingService(im)performBooking:completionHandler:","navigatorTitle":[{"kind":"identifier","text":"performBooking:completionHandler:"}],"required":true},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/performBooking(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Book the resource identified by the booking parameter.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpbookingservice\/performbooking(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpbookingservice\/performbooking(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService"]]},"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/bookingId":{"navigatorTitle":[{"kind":"identifier","text":"bookingId"}],"url":"\/documentation\/mapsindoors\/mpbooking\/bookingid","kind":"symbol","role":"symbol","title":"bookingId","type":"topic","abstract":[{"text":"The id of the Booking to be used for future references.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/bookingId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bookingId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService":{"type":"topic","role":"symbol","title":"MPBookingService","url":"\/documentation\/mapsindoors\/mpbookingservice","abstract":[{"type":"text","text":"MPBookingService allows for access to the MapsIndoors booking service."},{"type":"text","text":" "},{"type":"text","text":"The booking service is a special integration that has to be enabled in the MapsIndoors cloud systems."}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBookingService"}],"navigatorTitle":[{"text":"MPBookingService","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService/performBooking(_:)":{"required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"performBooking","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking","text":"MPBooking"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking","text":"MPBooking","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/mapsindoors\/mpbookingservice\/performbooking(_:)","role":"symbol","abstract":[{"text":"Book the resource identified by the booking parameter.","type":"text"}],"title":"performBooking(_:)","navigatorTitle":[{"text":"performBooking:completionHandler:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/performBooking(_:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking":{"navigatorTitle":[{"kind":"identifier","text":"MPBooking"}],"url":"\/documentation\/mapsindoors\/mpbooking","kind":"symbol","role":"symbol","title":"MPBooking","type":"topic","abstract":[{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking","type":"reference","isActive":true},{"text":" represents an existing booking object or a booking to be made.","type":"text"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/bookingId"},{"text":" will be non-","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" for an existing booking, and ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" for a booking to be made."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPBooking"}]},"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"performBooking:completionHandler:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"performBooking:completionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"performBooking:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking","text":"MPBooking"},{"kind":"text","text":" *) "},{"text":"booking","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(MPBooking *, NSError *)","preciseIdentifier":"c:BFv(#*$@M@MapsIndoors@objc(cs)MPBooking#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1bookingId\/title","value":"bookingId"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1bookingId\/fragments","value":[{"text":"bookingId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService\/title","value":"MPBookingService"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService\/fragments","op":"replace","value":[{"text":"MPBookingService","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1performBooking(_:)\/title","value":"performBooking:completionHandler:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"performBooking:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1performBooking(_:)\/fragments"},{"op":"replace","value":"MPBooking","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking\/title"},{"value":[{"kind":"identifier","text":"MPBooking"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking\/fragments"}]}]}