{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bbox"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpvenue-swift.class\/bbox"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpvenue-swift.class\/bbox"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/bbox","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Geographic BBox array [w,s,e,n] for this venue."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bbox"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"title":"bbox","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPVenue(py)bbox","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"bbox"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/bbox":{"role":"symbol","title":"bbox","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bbox"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Geographic BBox array [w,s,e,n] for this venue."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/bbox","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bbox"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/bbox"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class":{"role":"symbol","title":"MPVenue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenue"}],"abstract":[{"type":"text","text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenue"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"bbox"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"bbox"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<Optional>","preciseIdentifier":"c:Q$objc(cs)NSArrayobjc(pl)Optional"},{"kind":"text","text":" *"},{"kind":"identifier","text":"bbox"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1bbox\/title","value":"bbox"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1bbox\/fragments","value":[{"kind":"identifier","text":"bbox"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class\/title","value":"MPVenue"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class\/fragments","value":[{"kind":"identifier","text":"MPVenue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}