{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBounds"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpvenue-swift.class\/getbounds()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpvenue-swift.class\/getbounds()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/getBounds()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get the geographic bounds for the venue"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getVenueBounds"}],"role":"symbol","title":"getBounds()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBounds"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:objc(cs)MPVenue(im)getVenueBounds","modules":[{"name":"MapsIndoors"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use getBoundingBox"}]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class":{"role":"symbol","title":"MPVenue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenue"}],"abstract":[{"type":"text","text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenue"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/getBounds()":{"deprecated":true,"role":"symbol","title":"getBounds()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBounds"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the geographic bounds for the venue"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/getBounds()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getVenueBounds"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/getbounds()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getVenueBounds"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVenueBounds"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getVenueBounds"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class\/title","value":"MPVenue"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class\/fragments","value":[{"kind":"identifier","text":"MPVenue"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1getBounds()\/title","value":"getVenueBounds"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1getBounds()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVenueBounds"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}