{"abstract":[{"text":"The current capacity in terms of maximum number of people for a given Location.","type":"text"}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpoccupancyliveupdate\/capacity"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpoccupancyliveupdate\/capacity"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"MapsIndoors"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPOccupancyLiveUpdate(py)capacity","title":"capacity","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"capacity"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"capacity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPOccupancyLiveUpdate\/capacity","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"capacity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPOccupancyLiveUpdate"]]},"references":{"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPOccupancyLiveUpdate/capacity":{"role":"symbol","abstract":[{"type":"text","text":"The current capacity in terms of maximum number of people for a given Location."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPOccupancyLiveUpdate\/capacity","navigatorTitle":[{"text":"capacity","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpoccupancyliveupdate\/capacity","title":"capacity","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"capacity","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"kind":"symbol","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPOccupancyLiveUpdate":{"role":"symbol","abstract":[{"text":"Model for live occupancy information for a given Location.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPOccupancyLiveUpdate","navigatorTitle":[{"kind":"identifier","text":"MPOccupancyLiveUpdate"}],"url":"\/documentation\/mapsindoors\/mpoccupancyliveupdate","title":"MPOccupancyLiveUpdate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPOccupancyLiveUpdate","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"capacity"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"capacity","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"text":"capacity","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","value":"capacity","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPOccupancyLiveUpdate~1capacity\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPOccupancyLiveUpdate~1capacity\/fragments","value":[{"text":"capacity","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPOccupancyLiveUpdate\/title","value":"MPOccupancyLiveUpdate"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPOccupancyLiveUpdate\/fragments","value":[{"kind":"identifier","text":"MPOccupancyLiveUpdate"}]}]}]}