{"kind":"symbol","metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManagerDelegate(im)dataSetManager:willStartSynchronizingItem:","role":"symbol","modules":[{"name":"MapsIndoors"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"dataSetManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"MPDataSetCacheManager","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willStartSynchronizingItem"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem","text":"MPDataSetCacheItem","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"method","title":"dataSetManager(_:willStartSynchronizingItem:)","roleHeading":"Instance Method","navigatorTitle":[{"text":"dataSetManager:willStartSynchronizingItem:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:willstartsynchronizingitem:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:willstartsynchronizingitem:)"]}],"sections":[],"abstract":[{"text":"Called when a cache item synchronisation is started.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"dataSetManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"dataSetManager","kind":"internalParam"},{"kind":"text","text":": "},{"text":"MPDataSetCacheManager","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager"},{"kind":"text","text":", "},{"text":"willStartSynchronizingItem","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"item"},{"kind":"text","text":": "},{"text":"MPDataSetCacheItem","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"dataSetManager","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Originator of the callback."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Item that will be synchronised.","type":"text"}]}],"name":"item"}]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:willStartSynchronizingItem:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate/dataSetManager(_:willStartSynchronizingItem:)":{"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataSetManager"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","kind":"typeIdentifier","text":"MPDataSetCacheManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willStartSynchronizingItem"},{"kind":"text","text":": "},{"text":"MPDataSetCacheItem","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:willStartSynchronizingItem:)","navigatorTitle":[{"text":"dataSetManager:willStartSynchronizingItem:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:willstartsynchronizingitem:)","kind":"symbol","title":"dataSetManager(_:willStartSynchronizingItem:)","abstract":[{"type":"text","text":"Called when a cache item synchronisation is started."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate":{"navigatorTitle":[{"text":"MPDataSetCacheManagerDelegate","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Data set manager delegate protocol."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate","type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheManagerDelegate"}],"title":"MPDataSetCacheManagerDelegate"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","title":"MPDataSetCacheManager","role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager","navigatorTitle":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheManager"}],"kind":"symbol","abstract":[{"type":"text","text":"Data set manager class."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheItem"}],"navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheItem"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem","abstract":[{"type":"text","text":"Data set cache item class."}],"url":"\/documentation\/mapsindoors\/mpdatasetcacheitem","kind":"symbol","type":"topic","role":"symbol","title":"MPDataSetCacheItem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"dataSetManager:willStartSynchronizingItem:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dataSetManager:willStartSynchronizingItem:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"dataSetManager:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCacheManager","kind":"typeIdentifier","text":"id<MPDataSetCacheManager>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dataSetManager"},{"kind":"text","text":" "},{"text":"willStartSynchronizingItem:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<MPDataSetCacheItem>","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCacheItem"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"item"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":"dataSetManager:willStartSynchronizingItem:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:willStartSynchronizingItem:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dataSetManager:willStartSynchronizingItem:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:willStartSynchronizingItem:)\/fragments"},{"op":"replace","value":"MPDataSetCacheManagerDelegate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate\/title"},{"value":[{"text":"MPDataSetCacheManagerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title","op":"replace","value":"MPDataSetCacheManager"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments","value":[{"text":"MPDataSetCacheManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem\/title","value":"MPDataSetCacheItem"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem\/fragments","value":[{"text":"MPDataSetCacheItem","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}