{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"dataSetManagerDidFinishSynchronizing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"dataSetManager"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPDataSetCacheManager","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"dataSetManager","content":[{"type":"paragraph","inlineContent":[{"text":"Originator of the callback","type":"text"}]}]}]}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"dataSetManagerDidFinishSynchronizing:","kind":"identifier"}],"symbolKind":"method","title":"dataSetManagerDidFinishSynchronizing(_:)","externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManagerDelegate(im)dataSetManagerDidFinishSynchronizing:","modules":[{"name":"MapsIndoors"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSetManagerDidFinishSynchronizing"},{"text":"(","kind":"text"},{"text":"MPDataSetCacheManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager"},{"text":")","kind":"text"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManagerDidFinishSynchronizing(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanagerdidfinishsynchronizing(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanagerdidfinishsynchronizing(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Called when the data set manager has finished synchronization of one or more datasets.","type":"text"}],"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate/dataSetManagerDidFinishSynchronizing(_:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManagerDidFinishSynchronizing(_:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dataSetManagerDidFinishSynchronizing","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","text":"MPDataSetCacheManager"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"dataSetManagerDidFinishSynchronizing:","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanagerdidfinishsynchronizing(_:)","title":"dataSetManagerDidFinishSynchronizing(_:)","abstract":[{"text":"Called when the data set manager has finished synchronization of one or more datasets.","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate":{"navigatorTitle":[{"text":"MPDataSetCacheManagerDelegate","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Data set manager delegate protocol."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate","type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheManagerDelegate"}],"title":"MPDataSetCacheManagerDelegate"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","title":"MPDataSetCacheManager","role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager","navigatorTitle":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheManager"}],"kind":"symbol","abstract":[{"type":"text","text":"Data set manager class."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"dataSetManagerDidFinishSynchronizing:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"dataSetManagerDidFinishSynchronizing:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"dataSetManagerDidFinishSynchronizing:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<MPDataSetCacheManager>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCacheManager"},{"text":" *) ","kind":"text"},{"text":"dataSetManager","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"dataSetManagerDidFinishSynchronizing:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManagerDidFinishSynchronizing(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManagerDidFinishSynchronizing(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dataSetManagerDidFinishSynchronizing:"}]},{"value":"MPDataSetCacheManagerDelegate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate\/title"},{"value":[{"kind":"identifier","text":"MPDataSetCacheManagerDelegate"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title","op":"replace","value":"MPDataSetCacheManager"},{"value":[{"kind":"identifier","text":"MPDataSetCacheManager"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}