{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSetManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dataSetManager"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","text":"MPDataSetCacheManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishSynchronizingDataSet","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"dataset","kind":"internalParam"},{"kind":"text","text":": "},{"text":"MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"dataSetManager","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Originator of the callback."}]}]},{"name":"dataset","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Data set that has finished synchronization."}]}]}],"kind":"parameters"}],"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManagerDelegate(im)dataSetManager:didFinishSynchronizingDataSet:","required":true,"role":"symbol","modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataSetManager"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","kind":"typeIdentifier","text":"MPDataSetCacheManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishSynchronizingDataSet"},{"text":": ","kind":"text"},{"text":"MPDataSetCache","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache"},{"kind":"text","text":")"}],"symbolKind":"method","title":"dataSetManager(_:didFinishSynchronizingDataSet:)","roleHeading":"Instance Method","navigatorTitle":[{"text":"dataSetManager:didFinishSynchronizingDataSet:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didFinishSynchronizingDataSet:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:didfinishsynchronizingdataset:)"]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:didfinishsynchronizingdataset:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Called when a data set has finished synchronization."}],"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","title":"MPDataSetCacheManager","role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager","navigatorTitle":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheManager"}],"kind":"symbol","abstract":[{"type":"text","text":"Data set manager class."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCache":{"navigatorTitle":[{"text":"MPDataSetCache","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Data set cache class.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache","type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcache","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDataSetCache","kind":"identifier"}],"title":"MPDataSetCache"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate/dataSetManager(_:didFinishSynchronizingDataSet:)":{"required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didFinishSynchronizingDataSet:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"dataSetManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","text":"MPDataSetCacheManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishSynchronizingDataSet"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"dataSetManager:didFinishSynchronizingDataSet:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:didfinishsynchronizingdataset:)","abstract":[{"type":"text","text":"Called when a data set has finished synchronization."}],"title":"dataSetManager(_:didFinishSynchronizingDataSet:)","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate":{"navigatorTitle":[{"text":"MPDataSetCacheManagerDelegate","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Data set manager delegate protocol."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate","type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheManagerDelegate"}],"title":"MPDataSetCacheManagerDelegate"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"dataSetManager:didFinishSynchronizingDataSet:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dataSetManager:didFinishSynchronizingDataSet:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"dataSetManager:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MPDataSetCacheManager>","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCacheManager"},{"text":" *) ","kind":"text"},{"text":"dataSetManager","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didFinishSynchronizingDataSet:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCache","text":"id<MPDataSetCache>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dataset"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MPDataSetCacheManager","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheManager"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache\/title","value":"MPDataSetCache"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache\/fragments","value":[{"text":"MPDataSetCache","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:didFinishSynchronizingDataSet:)\/title","value":"dataSetManager:didFinishSynchronizingDataSet:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:didFinishSynchronizingDataSet:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dataSetManager:didFinishSynchronizingDataSet:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate\/title","op":"replace","value":"MPDataSetCacheManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate\/fragments","value":[{"text":"MPDataSetCacheManagerDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}