{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:didfinishsynchronizingitem:)"]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:didfinishsynchronizingitem:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataSetManager"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dataSetManager"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","text":"MPDataSetCacheManager","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishSynchronizingItem","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"item","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem","text":"MPDataSetCacheItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Originator of the callback."}],"type":"paragraph"}],"name":"dataSetManager"},{"name":"item","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Item that was synchronised."}]}]}]}],"sections":[],"abstract":[{"type":"text","text":"Called when a cache item synchronisation is finished."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didFinishSynchronizingItem:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManagerDelegate(im)dataSetManager:didFinishSynchronizingItem:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"dataSetManager:didFinishSynchronizingItem:"}],"modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSetManager"},{"kind":"text","text":"("},{"text":"MPDataSetCacheManager","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishSynchronizingItem","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem","text":"MPDataSetCacheItem"},{"kind":"text","text":")"}],"symbolKind":"method","title":"dataSetManager(_:didFinishSynchronizingItem:)"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate","kind":"symbol","abstract":[{"text":"Data set manager delegate protocol.","type":"text"}],"title":"MPDataSetCacheManagerDelegate","type":"topic","role":"symbol","url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheManagerDelegate"}],"navigatorTitle":[{"text":"MPDataSetCacheManagerDelegate","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager":{"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheManager"}],"kind":"symbol","title":"MPDataSetCacheManager","role":"symbol","navigatorTitle":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Data set manager class."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager"},"MapsPeopleWhite.png":{"alt":null,"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Data set cache item class."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDataSetCacheItem","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem","role":"symbol","url":"\/documentation\/mapsindoors\/mpdatasetcacheitem","title":"MPDataSetCacheItem","navigatorTitle":[{"text":"MPDataSetCacheItem","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate/dataSetManager(_:didFinishSynchronizingItem:)":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:didfinishsynchronizingitem:)","type":"topic","abstract":[{"type":"text","text":"Called when a cache item synchronisation is finished."}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didFinishSynchronizingItem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"dataSetManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MPDataSetCacheManager","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishSynchronizingItem"},{"kind":"text","text":": "},{"text":"MPDataSetCacheItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"dataSetManager:didFinishSynchronizingItem:","kind":"identifier"}],"title":"dataSetManager(_:didFinishSynchronizingItem:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"dataSetManager:didFinishSynchronizingItem:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"dataSetManager:didFinishSynchronizingItem:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"dataSetManager:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCacheManager","text":"id<MPDataSetCacheManager>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dataSetManager"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didFinishSynchronizingItem:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCacheItem","text":"id<MPDataSetCacheItem>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"item"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MPDataSetCacheManagerDelegate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate\/title"},{"value":[{"kind":"identifier","text":"MPDataSetCacheManagerDelegate"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate\/fragments","op":"replace"},{"op":"replace","value":"MPDataSetCacheManager","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title"},{"value":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem\/title","value":"MPDataSetCacheItem","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem\/fragments","value":[{"text":"MPDataSetCacheItem","kind":"identifier"}]},{"value":"dataSetManager:didFinishSynchronizingItem:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:didFinishSynchronizingItem:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"dataSetManager:didFinishSynchronizingItem:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:didFinishSynchronizingItem:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}