{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didAddDataSet:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:didadddataset:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:didadddataset:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Called when a data set is added to a data set manager.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"dataSetManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"dataSetManager","kind":"internalParam"},{"kind":"text","text":": "},{"text":"MPDataSetCacheManager","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didAddDataSet"},{"text":" ","kind":"text"},{"text":"dataset","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache","kind":"typeIdentifier","text":"MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Originator of the callback.","type":"text"}]}],"name":"dataSetManager"},{"name":"dataset","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Data set that was added."}]}]}]}],"metadata":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dataSetManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","text":"MPDataSetCacheManager"},{"kind":"text","text":", "},{"text":"didAddDataSet","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManagerDelegate(im)dataSetManager:didAddDataSet:","navigatorTitle":[{"kind":"identifier","text":"dataSetManager:didAddDataSet:"}],"title":"dataSetManager(_:didAddDataSet:)","role":"symbol","modules":[{"name":"MapsIndoors"}],"symbolKind":"method"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager":{"navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManager"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheManager"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","abstract":[{"type":"text","text":"Data set manager class."}],"title":"MPDataSetCacheManager"},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null,"type":"image","identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate":{"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManagerDelegate"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate","title":"MPDataSetCacheManagerDelegate","type":"topic","abstract":[{"type":"text","text":"Data set manager delegate protocol."}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDataSetCacheManagerDelegate","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate/dataSetManager(_:didAddDataSet:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dataSetManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MPDataSetCacheManager","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didAddDataSet"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","kind":"typeIdentifier","text":"MPDataSetCache"},{"text":")","kind":"text"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:didadddataset:)","type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"dataSetManager:didAddDataSet:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didAddDataSet:)","kind":"symbol","title":"dataSetManager(_:didAddDataSet:)","abstract":[{"type":"text","text":"Called when a data set is added to a data set manager."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCache":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache","abstract":[{"text":"Data set cache class.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCache"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPDataSetCache","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcache","title":"MPDataSetCache"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"dataSetManager:didAddDataSet:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dataSetManager:didAddDataSet:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"dataSetManager:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCacheManager","kind":"typeIdentifier","text":"id<MPDataSetCacheManager>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dataSetManager"},{"text":" ","kind":"text"},{"text":"didAddDataSet:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<MPDataSetCache>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCache"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"dataset"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title","op":"replace","value":"MPDataSetCacheManager"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments","value":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MPDataSetCacheManagerDelegate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPDataSetCacheManagerDelegate"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:didAddDataSet:)\/title","value":"dataSetManager:didAddDataSet:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:didAddDataSet:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"dataSetManager:didAddDataSet:","kind":"identifier"}],"op":"replace"},{"value":"MPDataSetCache","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MPDataSetCache"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache\/fragments"}]}]}