{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didRemoveDataSet:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManagerDelegate(im)dataSetManager:didRemoveDataSet:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"dataSetManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"MPDataSetCacheManager","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didRemoveDataSet","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"dataSetManager:didRemoveDataSet:"}],"title":"dataSetManager(_:didRemoveDataSet:)"},"abstract":[{"text":"Called when a data set is removed from a data set manager.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"dataSetManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dataSetManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","text":"MPDataSetCacheManager"},{"kind":"text","text":", "},{"text":"didRemoveDataSet","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"dataset"},{"text":": ","kind":"text"},{"text":"MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Originator of the callback.","type":"text"}],"type":"paragraph"}],"name":"dataSetManager"},{"content":[{"inlineContent":[{"type":"text","text":"Data set that was removed."}],"type":"paragraph"}],"name":"dataset"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:didremovedataset:)"]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:didremovedataset:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"MapsPeopleWhite.png":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager":{"navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManager"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheManager"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","abstract":[{"type":"text","text":"Data set manager class."}],"title":"MPDataSetCacheManager"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCache":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache","abstract":[{"text":"Data set cache class.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCache"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPDataSetCache","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcache","title":"MPDataSetCache"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate/dataSetManager(_:didRemoveDataSet:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataSetManager"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","text":"MPDataSetCacheManager"},{"text":", ","kind":"text"},{"text":"didRemoveDataSet","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:didremovedataset:)","navigatorTitle":[{"kind":"identifier","text":"dataSetManager:didRemoveDataSet:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didRemoveDataSet:)","kind":"symbol","abstract":[{"type":"text","text":"Called when a data set is removed from a data set manager."}],"title":"dataSetManager(_:didRemoveDataSet:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate":{"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManagerDelegate"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate","title":"MPDataSetCacheManagerDelegate","type":"topic","abstract":[{"type":"text","text":"Data set manager delegate protocol."}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDataSetCacheManagerDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"dataSetManager:didRemoveDataSet:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dataSetManager:didRemoveDataSet:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"dataSetManager:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<MPDataSetCacheManager>","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCacheManager"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dataSetManager"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRemoveDataSet:"},{"kind":"text","text":"("},{"text":"id<MPDataSetCache>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPDataSetCache"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dataset"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title","value":"MPDataSetCacheManager"},{"value":[{"kind":"identifier","text":"MPDataSetCacheManager"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache\/title","value":"MPDataSetCache","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache\/fragments","value":[{"kind":"identifier","text":"MPDataSetCache"}]},{"op":"replace","value":"dataSetManager:didRemoveDataSet:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:didRemoveDataSet:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:didRemoveDataSet:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dataSetManager:didRemoveDataSet:"}],"op":"replace"},{"value":"MPDataSetCacheManagerDelegate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate\/title"},{"value":[{"text":"MPDataSetCacheManagerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate\/fragments"}]}]}