{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProviderDelegate","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPPositionProviderDelegate","text":"MPPositionProviderDelegate","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPPositionProvider(py)delegate","required":true,"roleHeading":"Instance Property","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"text":"MPPositionProviderDelegate","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPPositionProviderDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"symbolKind":"property","title":"delegate"},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider\/delegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mppositionprovider\/delegate"]},{"paths":["\/documentation\/mapsindoors\/mppositionprovider\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The receiver of user positions. "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"},{"type":"text","text":" will hook into this delegate to be able to show the current"},{"text":" ","type":"text"},{"type":"text","text":"user position on the currently shown map."},{"type":"text","text":" "},{"type":"text","text":"If your app needs to be notified about each new user position, you should create a class conforming to"},{"type":"text","text":" "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate","isActive":true,"type":"reference"},{"text":" and set that as the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/delegate","isActive":true},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"User position updates will then be available to you via the","type":"text"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/onPositionUpdate(position:)"},{"type":"text","text":" function that you implement in your class."}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionProvider/delegate":{"role":"symbol","abstract":[{"text":"The receiver of user positions. ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"},{"type":"text","text":" will hook into this delegate to be able to show the current"},{"type":"text","text":" "},{"type":"text","text":"user position on the currently shown map."},{"type":"text","text":" "},{"type":"text","text":"If your app needs to be notified about each new user position, you should create a class conforming to"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate"},{"type":"text","text":" and set that as the "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/delegate","isActive":true,"type":"reference"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"User position updates will then be available to you via the"},{"type":"text","text":" "},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/onPositionUpdate(position:)","type":"reference"},{"type":"text","text":" function that you implement in your class."}],"kind":"symbol","required":true,"url":"\/documentation\/mapsindoors\/mppositionprovider\/delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider\/delegate","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"text":"MPPositionProviderDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPPositionProviderDelegate"},{"kind":"text","text":"?"}],"title":"delegate"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionProviderDelegate":{"role":"symbol","abstract":[{"type":"text","text":"Protocol specifying how an indoor positioning provider delegate should be implemented as the receiver of user positions."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mppositionproviderdelegate","navigatorTitle":[{"text":"MPPositionProviderDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProviderDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPPositionProviderDelegate"}],"title":"MPPositionProviderDelegate"},"MapsPeopleWhite.png":{"type":"image","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"abstract":[{"type":"text","text":"This is the control object for the visual representation of the MapsIndoors SDK."}],"url":"\/documentation\/mapsindoors\/mpmapcontrol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPMapControl"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"type":"topic","kind":"symbol","title":"MPMapControl","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/delegate":{"role":"symbol","abstract":[{"text":"Listen to events.","type":"text"}],"kind":"symbol","required":true,"url":"\/documentation\/mapsindoors\/mpmapcontrol\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/delegate","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPMapControlDelegate","text":"MPMapControlDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"delegate"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionProvider":{"url":"\/documentation\/mapsindoors\/mppositionprovider","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProvider"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPPositionProvider"}],"title":"MPPositionProvider","abstract":[{"type":"text","text":"Protocol specifying how an indoor positioning provider should be implemented if the users location is to be exposed to "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true},{"type":"text","text":"."}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate/onPositionUpdate(position:)":{"url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/onpositionupdate(position:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/onPositionUpdate(position:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPositionUpdate"},{"text":"(","kind":"text"},{"text":"position","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPositionResult","text":"MPPositionResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","required":true,"title":"onPositionUpdate(position:)","abstract":[{"type":"text","text":"Called when "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true,"type":"reference"},{"type":"text","text":" receives a new user position from the active "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This is the method you should implement if your app needs to be notified about each new user position."}],"navigatorTitle":[{"text":"onPositionUpdate:","kind":"identifier"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPMapControlDelegate","kind":"identifier"}],"abstract":[{"text":"Delegate protocol specification to react to the events that ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true},{"text":" emits.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpmapcontroldelegate","title":"MPMapControlDelegate","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPMapControlDelegate"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPPositionProviderDelegate","text":"id<MPPositionProviderDelegate>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"delegate"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider~1delegate\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"value":"MPPositionProviderDelegate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProviderDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProviderDelegate\/fragments","value":[{"text":"MPPositionProviderDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl"},{"value":[{"text":"MPMapControl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1delegate\/title","op":"replace","value":"delegate"},{"op":"replace","value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1delegate\/fragments"},{"value":"MPPositionProvider","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider\/fragments","value":[{"kind":"identifier","text":"MPPositionProvider"}],"op":"replace"},{"value":"onPositionUpdate:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1onPositionUpdate(position:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onPositionUpdate:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1onPositionUpdate(position:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/title","op":"replace","value":"MPMapControlDelegate"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/fragments","value":[{"kind":"identifier","text":"MPMapControlDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}