{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"latestPosition","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult","text":"MPPositionResult","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPositionResult"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider\/latestPosition","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mppositionprovider\/latestposition"]},{"paths":["\/documentation\/mapsindoors\/mppositionprovider\/latestposition"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider"]]},"kind":"symbol","metadata":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"latestPosition"},{"kind":"text","text":": "},{"text":"MPPositionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPositionResult"},{"kind":"text","text":"?"}],"modules":[{"name":"MapsIndoors"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"latestPosition","navigatorTitle":[{"kind":"identifier","text":"latestPosition"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPPositionProvider(py)latestPosition"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Latest position result if any.","type":"text"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionProvider":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","navigatorTitle":[{"kind":"identifier","text":"MPPositionProvider"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mppositionprovider","abstract":[{"type":"text","text":"Protocol specifying how an indoor positioning provider should be implemented if the users location is to be exposed to "},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","type":"reference"},{"text":".","type":"text"}],"title":"MPPositionProvider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPPositionProvider","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionResult":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult","navigatorTitle":[{"text":"MPPositionResult","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mppositionresult","abstract":[{"text":"Instances of this class holds a Position result returned by a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","isActive":true},{"type":"text","text":"."}],"title":"MPPositionResult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionResult"}],"type":"topic","kind":"symbol"},"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionProvider/latestPosition":{"navigatorTitle":[{"kind":"identifier","text":"latestPosition"}],"abstract":[{"type":"text","text":"Latest position result if any."}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider\/latestPosition","title":"latestPosition","required":true,"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"latestPosition"},{"text":": ","kind":"text"},{"text":"MPPositionResult","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPositionResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/mapsindoors\/mppositionprovider\/latestposition"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"type":"topic","abstract":[{"text":"This is the control object for the visual representation of the MapsIndoors SDK.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontrol","title":"MPMapControl"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"latestPosition","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"latestPosition"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPositionResult","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult","text":"MPPositionResult","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"latestPosition"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider\/title","value":"MPPositionProvider"},{"value":[{"text":"MPPositionProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult\/title","op":"replace","value":"MPPositionResult"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult\/fragments","value":[{"kind":"identifier","text":"MPPositionResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider~1latestPosition\/title","value":"latestPosition"},{"value":[{"kind":"identifier","text":"latestPosition"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider~1latestPosition\/fragments","op":"replace"},{"value":"MPMapControl","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"kind":"identifier","text":"MPMapControl"}]}]}]}