{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferAlwaysLocationPermission"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppositionprovider\/preferalwayslocationpermission"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppositionprovider\/preferalwayslocationpermission"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProvider\/preferAlwaysLocationPermission","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set location services flag that determines if app should request location always or only when in use"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"preferAlwaysLocationPermission"}],"role":"symbol","title":"preferAlwaysLocationPermission","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferAlwaysLocationPermission"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"property","externalID":"c:objc(pl)MPPositionProvider(py)preferAlwaysLocationPermission","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProvider":{"role":"symbol","title":"MPPositionProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProvider"}],"abstract":[{"type":"text","text":"Protocol specifying how an indoor positioning provider should be implemented if the users location is to be exposed to MPMapControl"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPositionProvider"}],"url":"\/documentation\/mapsindoors\/mppositionprovider"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProvider/preferAlwaysLocationPermission":{"navigatorTitle":[{"kind":"identifier","text":"preferAlwaysLocationPermission"}],"role":"symbol","title":"preferAlwaysLocationPermission","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferAlwaysLocationPermission"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set location services flag that determines if app should request location always or only when in use"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProvider\/preferAlwaysLocationPermission","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mppositionprovider\/preferalwayslocationpermission"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"preferAlwaysLocationPermission"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"preferAlwaysLocationPermission"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"identifier","text":"preferAlwaysLocationPermission"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProvider\/title","value":"MPPositionProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProvider\/fragments","value":[{"kind":"identifier","text":"MPPositionProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProvider~1preferAlwaysLocationPermission\/title","value":"preferAlwaysLocationPermission"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProvider~1preferAlwaysLocationPermission\/fragments","value":[{"kind":"identifier","text":"preferAlwaysLocationPermission"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}