{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPS_POSITION_PROVIDER"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppositionprovidertype\/gps_position_provider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppositionprovidertype\/gps_position_provider"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/GPS_POSITION_PROVIDER","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPS_POSITION_PROVIDER"}],"title":"MPPositionProviderType.GPS_POSITION_PROVIDER","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MPPositionProviderType@GPS_POSITION_PROVIDER","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"GPS_POSITION_PROVIDER"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProviderType/GPS_POSITION_PROVIDER":{"role":"symbol","title":"MPPositionProviderType.GPS_POSITION_PROVIDER","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"GPS_POSITION_PROVIDER"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType\/GPS_POSITION_PROVIDER","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GPS_POSITION_PROVIDER"}],"url":"\/documentation\/mapsindoors\/mppositionprovidertype\/gps_position_provider"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProviderType":{"role":"symbol","title":"MPPositionProviderType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProviderType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPositionProviderType"}],"url":"\/documentation\/mapsindoors\/mppositionprovidertype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"GPS_POSITION_PROVIDER"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GPS_POSITION_PROVIDER"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"GPS_POSITION_PROVIDER"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderType~1GPS_POSITION_PROVIDER\/title","value":"GPS_POSITION_PROVIDER"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderType~1GPS_POSITION_PROVIDER\/fragments","value":[{"kind":"identifier","text":"GPS_POSITION_PROVIDER"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderType\/title","value":"MPPositionProviderType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderType\/fragments","value":[{"kind":"identifier","text":"MPPositionProviderType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}