{"abstract":[{"type":"text","text":"Animate the rendered path, when displaying a route element on the map."}],"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animate"},{"text":"(","kind":"text"},{"text":"duration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"animateWithDuration:","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"method","externalID":"c:@M@MapsIndoors@objc(pl)MPDirectionsRenderer(im)animateWithDuration:","roleHeading":"Instance Method","required":true,"title":"animate(duration:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderer\/animate(duration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderer\/animate(duration:)"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animate","kind":"identifier"},{"kind":"text","text":"("},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"duration","content":[{"inlineContent":[{"type":"text","text":"The duration of camera animations in seconds. Set to "},{"type":"codeVoice","code":"0"},{"type":"text","text":" to disable animation."}],"type":"paragraph"}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/animate(duration:)"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsRenderer/animate(duration:)":{"navigatorTitle":[{"text":"animateWithDuration:","kind":"identifier"}],"required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"duration"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Animate the rendered path, when displaying a route element on the map."}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/animate(duration:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/animate(duration:)","title":"animate(duration:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsRenderer":{"navigatorTitle":[{"text":"MPDirectionsRenderer","kind":"identifier"}],"role":"symbol","title":"MPDirectionsRenderer","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDirectionsRenderer","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer","type":"topic","abstract":[{"type":"text","text":"This allows for an easy way to display a route on the MapsIndoors map. Each leg of the route can be shown individually and can be navigated by manipulating the selected leg index. Various customization options are available to adjust the polyline styling and camera behavior."}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"animateWithDuration:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"animateWithDuration:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"animateWithDuration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"duration"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1animate(duration:)\/title","op":"replace","value":"animateWithDuration:"},{"value":[{"text":"- ","kind":"text"},{"text":"animateWithDuration:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1animate(duration:)\/fragments","op":"replace"},{"value":"MPDirectionsRenderer","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/title","op":"replace"},{"value":[{"text":"MPDirectionsRenderer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/fragments"}]}]}