{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"clear"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clear","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@MapsIndoors@objc(pl)MPDirectionsRenderer(im)clear","title":"clear()","modules":[{"name":"MapsIndoors"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clear","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/clear()"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer"]]},"variants":[{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderer\/clear()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderer\/clear()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Clears the route from the map."}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsRenderer":{"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer","role":"symbol","title":"MPDirectionsRenderer","kind":"symbol","abstract":[{"type":"text","text":"This allows for an easy way to display a route on the MapsIndoors map. Each leg of the route can be shown individually and can be navigated by manipulating the selected leg index. Various customization options are available to adjust the polyline styling and camera behavior."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPDirectionsRenderer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRenderer"}],"type":"topic"},"MapsPeopleWhite.png":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsRenderer/clear()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clear"},{"text":"()","kind":"text"}],"role":"symbol","required":true,"title":"clear()","url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/clear()","kind":"symbol","navigatorTitle":[{"text":"clear","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/clear()","abstract":[{"text":"Clears the route from the map.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"clear"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clear"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"clear","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/title","value":"MPDirectionsRenderer"},{"value":[{"kind":"identifier","text":"MPDirectionsRenderer"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/fragments"},{"value":"clear","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1clear()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clear"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1clear()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}