{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"edgeInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderer\/edgeinsets"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderer\/edgeinsets"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/edgeInsets","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Intentional egde insets for bounds fitting. The rendering is not guaranteed to respect the specified insets."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"edgeInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"title":"edgeInsets","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPDirectionsRenderer(py)edgeInsets","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"edgeInsets"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer":{"role":"symbol","title":"MPDirectionsRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRenderer"}],"abstract":[{"type":"text","text":"Directions Renderer"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRenderer"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer/edgeInsets":{"role":"symbol","title":"edgeInsets","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"edgeInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"abstract":[{"type":"text","text":"Intentional egde insets for bounds fitting. The rendering is not guaranteed to respect the specified insets."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/edgeInsets","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"edgeInsets"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/edgeinsets"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"edgeInsets"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"edgeInsets"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"},{"kind":"text","text":" "},{"kind":"identifier","text":"edgeInsets"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/title","value":"MPDirectionsRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1edgeInsets\/title","value":"edgeInsets"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1edgeInsets\/fragments","value":[{"kind":"identifier","text":"edgeInsets"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}