{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"property","required":true,"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"fitMode"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPDirectionsRenderer(py)fitMode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fitMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPCameraViewFitMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPCameraViewFitMode"}],"title":"fitMode"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/fitMode"},"sections":[],"abstract":[{"text":"The fit mode of the camera, when displaying route elements on the map.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fitMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode","preciseIdentifier":"c:@M@MapsIndoors@E@MPCameraViewFitMode","text":"MPCameraViewFitMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderer\/fitmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderer\/fitmode"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsRenderer/fitMode":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/fitMode","title":"fitMode","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The fit mode of the camera, when displaying route elements on the map."}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/fitmode","navigatorTitle":[{"text":"fitMode","kind":"identifier"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fitMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@E@MPCameraViewFitMode","text":"MPCameraViewFitMode","kind":"typeIdentifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsRenderer":{"type":"topic","abstract":[{"text":"This allows for an easy way to display a route on the MapsIndoors map. Each leg of the route can be shown individually and can be navigated by manipulating the selected leg index. Various customization options are available to adjust the polyline styling and camera behavior.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer","url":"\/documentation\/mapsindoors\/mpdirectionsrenderer","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDirectionsRenderer"}],"kind":"symbol","title":"MPDirectionsRenderer","navigatorTitle":[{"text":"MPDirectionsRenderer","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraViewFitMode":{"title":"MPCameraViewFitMode","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MPCameraViewFitMode","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpcameraviewfitmode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MPCameraViewFitMode","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode"},"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"fitMode","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"fitMode","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode","preciseIdentifier":"c:@M@MapsIndoors@E@MPCameraViewFitMode","text":"MPCameraViewFitMode"},{"kind":"text","text":" "},{"text":"fitMode","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1fitMode\/title","value":"fitMode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1fitMode\/fragments","value":[{"kind":"identifier","text":"fitMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/title","value":"MPDirectionsRenderer"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/fragments","value":[{"text":"MPDirectionsRenderer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode\/title","value":"MPCameraViewFitMode"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode\/fragments","value":[{"text":"MPCameraViewFitMode","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}