{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"templateString"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpuritemplate\/init(templatestring:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpuritemplate\/init(templatestring:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/init(templateString:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initialization with template string. Must have format “prefix{param_1}infix{param_N}suffix”, e.g.: “http:\/\/tiles.url.com\/{floor}\/{x}\/{y}\/{zoom}.png”"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"templateString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"init(templateString:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)MPURITemplate(im)initWithTemplateString:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTemplateString:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPURITemplate":{"role":"symbol","title":"MPURITemplate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPURITemplate"}],"abstract":[{"type":"text","text":"Generates an url based on an URI template. Template string must have format “prefix{param_1}infix{param_N}suffix”, e.g.: “http:\/\/tiles.url.com\/{floor}\/{x}\/{y}\/{zoom}.png”"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPURITemplate"}],"url":"\/documentation\/mapsindoors\/mpuritemplate"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPURITemplate/init(templateString:)":{"role":"symbol","title":"init(templateString:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"templateString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialization with template string. Must have format “prefix{param_1}infix{param_N}suffix”, e.g.: “http:\/\/tiles.url.com\/{floor}\/{x}\/{y}\/{zoom}.png”"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/init(templateString:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithTemplateString:"}],"url":"\/documentation\/mapsindoors\/mpuritemplate\/init(templatestring:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithTemplateString:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTemplateString:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTemplateString:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"url"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate\/title","value":"MPURITemplate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate\/fragments","value":[{"kind":"identifier","text":"MPURITemplate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate~1init(templateString:)\/title","value":"initWithTemplateString:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate~1init(templateString:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTemplateString:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}