{"metadata":{"roleHeading":"Type Property","role":"symbol","externalID":"c:@M@MapsIndoors@objc(cs)MPHighway(cpy)ramp","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ramp","kind":"identifier"},{"kind":"text","text":": "},{"text":"MPHighway","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","kind":"typeIdentifier"}],"symbolKind":"property","title":"ramp","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"ramp","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ramp","kind":"identifier"},{"kind":"text","text":": "},{"text":"MPHighway","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/ramp","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mphighway\/ramp"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mphighway\/ramp"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/ramp":{"url":"\/documentation\/mapsindoors\/mphighway\/ramp","navigatorTitle":[{"text":"ramp","kind":"identifier"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ramp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPHighway","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","kind":"typeIdentifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/ramp","title":"ramp","kind":"symbol"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPHighway"}],"navigatorTitle":[{"text":"MPHighway","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","abstract":[{"type":"text","text":"Use instances of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway"},{"text":" to describe which type(s) of route elements to use.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","title":"MPHighway","url":"\/documentation\/mapsindoors\/mphighway"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"ramp","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ramp"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"MPHighway","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"ramp"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"ramp","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1ramp\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1ramp\/fragments","op":"replace","value":[{"text":"ramp","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway\/title","value":"MPHighway"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway\/fragments","value":[{"kind":"identifier","text":"MPHighway"}],"op":"replace"}]}]}