{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/wheelchairramp"},"variants":[{"paths":["\/documentation\/mapsindoors\/mphighway\/wheelchairramp"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mphighway\/wheelchairramp"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wheelchairramp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPHighway","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wheelchairramp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPHighway","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway"}],"roleHeading":"Type Property","externalID":"c:@M@MapsIndoors@objc(cs)MPHighway(cpy)wheelchairramp","navigatorTitle":[{"text":"wheelchairramp","kind":"identifier"}],"title":"wheelchairramp","modules":[{"name":"MapsIndoors"}],"symbolKind":"property","role":"symbol"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway":{"navigatorTitle":[{"text":"MPHighway","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","title":"MPHighway","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPHighway","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Use instances of "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","isActive":true},{"type":"text","text":" to describe which type(s) of route elements to use."}],"url":"\/documentation\/mapsindoors\/mphighway"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/wheelchairramp":{"url":"\/documentation\/mapsindoors\/mphighway\/wheelchairramp","role":"symbol","abstract":[],"title":"wheelchairramp","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wheelchairramp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","text":"MPHighway","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"wheelchairramp","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/wheelchairramp"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"wheelchairramp"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"wheelchairramp","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"MPHighway","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"wheelchairramp","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"MPHighway","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway\/fragments","value":[{"text":"MPHighway","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1wheelchairramp\/title","value":"wheelchairramp","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1wheelchairramp\/fragments","op":"replace","value":[{"kind":"identifier","text":"wheelchairramp"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}