{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDistanceMatrix"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOrigins"},{"kind":"text","text":" "},{"kind":"internalParam","text":"origins"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"destinations"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"travelMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":" "},{"kind":"internalParam","text":"restrictions"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"depart"},{"kind":"text","text":" "},{"kind":"internalParam","text":"departureTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"arrive"},{"kind":"text","text":" "},{"kind":"internalParam","text":"arrivalTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":" "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpMatrixHandlerBlockType","preciseIdentifier":"c:MPDistanceMatrixProvider.h@T@mpMatrixHandlerBlockType","text":"mpMatrixHandlerBlockType"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdistancematrixprovider\/getdistancematrix(withorigins:destinations:travelmode:avoid:depart:arrive:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdistancematrixprovider\/getdistancematrix(withorigins:destinations:travelmode:avoid:depart:arrive:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDistanceMatrix"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOrigins"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"destinations"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"travelMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"depart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"arrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpMatrixHandlerBlockType","preciseIdentifier":"c:MPDistanceMatrixProvider.h@T@mpMatrixHandlerBlockType"},{"kind":"text","text":"?)"}],"title":"getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPDistanceMatrixProvider(im)getDistanceMatrixWithOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getDistanceMatrixWithOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixProvider/getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)":{"role":"symbol","title":"getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDistanceMatrix"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOrigins"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"destinations"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"travelMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"depart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"arrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpMatrixHandlerBlockType","preciseIdentifier":"c:MPDistanceMatrixProvider.h@T@mpMatrixHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDistanceMatrixWithOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixprovider\/getdistancematrix(withorigins:destinations:travelmode:avoid:depart:arrive:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixProvider":{"role":"symbol","title":"MPDistanceMatrixProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDistanceMatrixProvider"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDistanceMatrixProvider"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixprovider"},"doc://MapsIndoors/documentation/MapsIndoors/mpMatrixHandlerBlockType":{"role":"symbol","title":"mpMatrixHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpMatrixHandlerBlockType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpMatrixHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpMatrixHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpmatrixhandlerblocktype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getDistanceMatrixWithOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDistanceMatrixWithOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getDistanceMatrixWithOrigins:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"origins"},{"kind":"text","text":" "},{"kind":"identifier","text":"destinations:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"destinations"},{"kind":"text","text":" "},{"kind":"identifier","text":"travelMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"travelMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"avoid:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"restrictions"},{"kind":"text","text":" "},{"kind":"identifier","text":"depart:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"departureTime"},{"kind":"text","text":" "},{"kind":"identifier","text":"arrive:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"arrivalTime"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(MPDistanceMatrixResult *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)MPDistanceMatrixResult#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"handler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)\/title","value":"getDistanceMatrixWithOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1getDistanceMatrix(withOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDistanceMatrixWithOrigins:destinations:travelMode:avoid:depart:arrive:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider\/title","value":"MPDistanceMatrixProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider\/fragments","value":[{"kind":"identifier","text":"MPDistanceMatrixProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpMatrixHandlerBlockType\/title","value":"mpMatrixHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpMatrixHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpMatrixHandlerBlockType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}