{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getGoogleDistanceMatrix"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOrigins"},{"kind":"text","text":" "},{"kind":"internalParam","text":"origins"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"destinations"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"travelMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdistancematrixprovider\/getgoogledistancematrix(withorigins:destinations:travelmode:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdistancematrixprovider\/getgoogledistancematrix(withorigins:destinations:travelmode:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getGoogleDistanceMatrix(withOrigins:destinations:travelMode:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getGoogleDistanceMatrix"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOrigins"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"destinations"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"travelMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"getGoogleDistanceMatrix(withOrigins:destinations:travelMode:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPDistanceMatrixProvider(im)getGoogleDistanceMatrixWithOrigins:destinations:travelMode:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getGoogleDistanceMatrixWithOrigins:destinations:travelMode:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixProvider/getGoogleDistanceMatrix(withOrigins:destinations:travelMode:)":{"role":"symbol","title":"getGoogleDistanceMatrix(withOrigins:destinations:travelMode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getGoogleDistanceMatrix"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOrigins"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"destinations"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"travelMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider\/getGoogleDistanceMatrix(withOrigins:destinations:travelMode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getGoogleDistanceMatrixWithOrigins:destinations:travelMode:"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixprovider\/getgoogledistancematrix(withorigins:destinations:travelmode:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixProvider":{"role":"symbol","title":"MPDistanceMatrixProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDistanceMatrixProvider"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDistanceMatrixProvider"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getGoogleDistanceMatrixWithOrigins:destinations:travelMode:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getGoogleDistanceMatrixWithOrigins:destinations:travelMode:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getGoogleDistanceMatrixWithOrigins:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"origins"},{"kind":"text","text":" "},{"kind":"identifier","text":"destinations:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"destinations"},{"kind":"text","text":" "},{"kind":"identifier","text":"travelMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"travelMode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1getGoogleDistanceMatrix(withOrigins:destinations:travelMode:)\/title","value":"getGoogleDistanceMatrixWithOrigins:destinations:travelMode:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider~1getGoogleDistanceMatrix(withOrigins:destinations:travelMode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getGoogleDistanceMatrixWithOrigins:destinations:travelMode:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider\/title","value":"MPDistanceMatrixProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixProvider\/fragments","value":[{"kind":"identifier","text":"MPDistanceMatrixProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}