{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState","preciseIdentifier":"c:@E@MPSubscriptionState","text":"MPSubscriptionState"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/didupdate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/didupdate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/didUpdate(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didUpdateState:"}],"role":"symbol","title":"didUpdate(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPSubscriptionState","preciseIdentifier":"c:@E@MPSubscriptionState"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MPSubscriptionClientDelegate(im)didUpdateState:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPSubscriptionClientDelegate":{"role":"symbol","title":"MPSubscriptionClientDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSubscriptionClientDelegate"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionClientDelegate"}],"url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPSubscriptionClientDelegate/didUpdate(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didUpdateState:"}],"role":"symbol","title":"didUpdate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPSubscriptionState","preciseIdentifier":"c:@E@MPSubscriptionState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/didUpdate(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/didupdate(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPSubscriptionState":{"role":"symbol","title":"MPSubscriptionState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSubscriptionState"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionState"}],"url":"\/documentation\/mapsindoors\/mpsubscriptionstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didUpdateState:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdateState:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didUpdateState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState","preciseIdentifier":"c:@E@MPSubscriptionState","text":"MPSubscriptionState"},{"kind":"text","text":")"},{"kind":"internalParam","text":"state"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate\/title","value":"MPSubscriptionClientDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate\/fragments","value":[{"kind":"identifier","text":"MPSubscriptionClientDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1didUpdate(_:)\/title","value":"didUpdateState:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1didUpdate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdateState:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionState\/title","value":"MPSubscriptionState"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionState\/fragments","value":[{"kind":"identifier","text":"MPSubscriptionState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}