{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderer\/animate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderer\/animate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/animate(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Start animation of the route leg\/step with given duration. Starting with a "},{"type":"codeVoice","code":"backgroundColor"},{"type":"text","text":" route leg\/step the polyline will be gradually stroked from start to end with the "},{"type":"codeVoice","code":"solidColor"},{"type":"text","text":" at the speed of "},{"type":"codeVoice","code":"leg\/step length \/ duration"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"title":"animate(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPDirectionsRenderer(im)animate:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"animate:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer/animate(_:)":{"role":"symbol","title":"animate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Start animation of the route leg\/step with given duration. Starting with a "},{"type":"codeVoice","code":"backgroundColor"},{"type":"text","text":" route leg\/step the polyline will be gradually stroked from start to end with the "},{"type":"codeVoice","code":"solidColor"},{"type":"text","text":" at the speed of "},{"type":"codeVoice","code":"leg\/step length \/ duration"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer\/animate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animate:"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer\/animate(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRenderer":{"role":"symbol","title":"MPDirectionsRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRenderer"}],"abstract":[{"type":"text","text":"Directions Renderer"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRenderer"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"animate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animate:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"animate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"},{"kind":"internalParam","text":"duration"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1animate(_:)\/title","value":"animate:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer~1animate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animate:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/title","value":"MPDirectionsRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRenderer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}