{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/mapsindoors\/mpliveupdatetopic\/buildingid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpliveupdatetopic\/buildingid"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildingId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"metadata":{"externalID":"c:@M@MapsIndoors@objc(cs)MPLiveUpdateTopic(py)buildingId","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"buildingId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"buildingId"}],"role":"symbol","title":"buildingId","symbolKind":"property","modules":[{"name":"MapsIndoors"}]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic\/buildingId","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get the id of the Building related to this topic if any"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdateTopic":{"role":"symbol","title":"MPLiveUpdateTopic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic","kind":"symbol","abstract":[{"text":"Topic model for a Live Update. A Live Update Topic is hierarchical in the way it is defined, and its relation to MapsIndoors data is derivable by its 7 components: Dataset, Venue, Building, Floor, Room, Location and Domain Type.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPLiveUpdateTopic"}],"navigatorTitle":[{"text":"MPLiveUpdateTopic","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpliveupdatetopic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdateTopic/buildingId":{"title":"buildingId","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"buildingId"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"buildingId","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic\/buildingId","url":"\/documentation\/mapsindoors\/mpliveupdatetopic\/buildingid","abstract":[{"type":"text","text":"Get the id of the Building related to this topic if any"}],"kind":"symbol"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"buildingId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"buildingId","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"buildingId","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic\/title","value":"MPLiveUpdateTopic"},{"value":[{"text":"MPLiveUpdateTopic","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic~1buildingId\/title","value":"buildingId"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic~1buildingId\/fragments","value":[{"text":"buildingId","kind":"identifier"}],"op":"replace"}]}]}