{"metadata":{"role":"symbol","title":"buildingId(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildingId","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"text":"MPLiveUpdateTopic","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdateTopic","kind":"typeIdentifier"}],"symbolKind":"method","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"buildingId:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@MapsIndoors@objc(cs)MPLiveUpdateTopic(im)buildingId:"},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic\/buildingId(_:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpliveupdatetopic\/buildingid(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpliveupdatetopic\/buildingid(_:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buildingId"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"buildingId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdateTopic","text":"MPLiveUpdateTopic"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdateTopic/buildingId(_:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic\/buildingId(_:)","title":"buildingId(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"buildingId:"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpliveupdatetopic\/buildingid(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildingId","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdateTopic","text":"MPLiveUpdateTopic"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdateTopic":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPLiveUpdateTopic"}],"abstract":[{"text":"Topic model for a Live Update. A Live Update Topic is hierarchical in the way it is defined, and its relation to MapsIndoors data is derivable by its 7 components: Dataset, Venue, Building, Floor, Room, Location and Domain Type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MPLiveUpdateTopic"}],"title":"MPLiveUpdateTopic","url":"\/documentation\/mapsindoors\/mpliveupdatetopic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"buildingId:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"buildingId:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic","text":"MPLiveUpdateTopic","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdateTopic"},{"text":" *) ","kind":"text"},{"text":"buildingId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"buildingId"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic~1buildingId(_:)\/title","value":"buildingId:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic~1buildingId(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"buildingId:","kind":"identifier"}]},{"value":"MPLiveUpdateTopic","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic\/fragments","value":[{"kind":"identifier","text":"MPLiveUpdateTopic"}]}]}]}