{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpliveupdatetopic\/datasetid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpliveupdatetopic\/datasetid"]}],"metadata":{"role":"symbol","title":"datasetId","modules":[{"name":"MapsIndoors"}],"symbolKind":"property","externalID":"c:@M@MapsIndoors@objc(cs)MPLiveUpdateTopic(py)datasetId","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"datasetId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"datasetId"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"datasetId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic\/datasetId","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic"]]},"abstract":[{"text":"Get the id of the Dataset related to this topic.","type":"text"}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdateTopic/datasetId":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"datasetId"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"datasetId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/mapsindoors\/mpliveupdatetopic\/datasetid","abstract":[{"type":"text","text":"Get the id of the Dataset related to this topic."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic\/datasetId","title":"datasetId"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdateTopic":{"role":"symbol","title":"MPLiveUpdateTopic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic","kind":"symbol","abstract":[{"text":"Topic model for a Live Update. A Live Update Topic is hierarchical in the way it is defined, and its relation to MapsIndoors data is derivable by its 7 components: Dataset, Venue, Building, Floor, Room, Location and Domain Type.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPLiveUpdateTopic"}],"navigatorTitle":[{"text":"MPLiveUpdateTopic","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpliveupdatetopic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"datasetId","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"datasetId","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"datasetId"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic~1datasetId\/title","op":"replace","value":"datasetId"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic~1datasetId\/fragments","value":[{"text":"datasetId","kind":"identifier"}]},{"op":"replace","value":"MPLiveUpdateTopic","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic\/title"},{"value":[{"kind":"identifier","text":"MPLiveUpdateTopic"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}