{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"matchesCriteria"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"criteria"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria","text":"MPLiveTopicCriteria"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"criteria","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Topic Criteria"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpliveupdatetopic\/matchescriteria(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpliveupdatetopic\/matchescriteria(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic\/matchesCriteria(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Method to determine whether a Live Update Topic qualifies for a given Topic Criteria"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"matchesCriteria"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"matchesCriteria(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPLiveUpdateTopic(im)matchesCriteria:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"matchesCriteria:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLiveUpdateTopic":{"role":"symbol","title":"MPLiveUpdateTopic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveUpdateTopic"}],"abstract":[{"type":"text","text":"Topic model for a Live Update. A Live Update Topic is hierarchical in the way it is defined, and its relation to MapsIndoors data is derivable by its 7 components: Dataset, Venue, Building, Floor, Room, Location and Domain Type"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveUpdateTopic"}],"url":"\/documentation\/mapsindoors\/mpliveupdatetopic"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria":{"role":"symbol","title":"MPLiveTopicCriteria","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Live Topic Criteria model used for subscriptions to Live Updates using MPLiveDataManager."},{"type":"text","text":" "},{"type":"text","text":"A Live Topic Criteria is hierarchical in the way it is defined, and its relation to MapsIndoors data is derivable by its 7 components: Dataset, Venue, Building, Floor, Room, Location and Domain Type."},{"type":"text","text":" "},{"type":"text","text":"All properties can be left out but datasetId will then default to the currently active dataset."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveTopicCriteria"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveUpdateTopic/matchesCriteria(_:)":{"role":"symbol","title":"matchesCriteria(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"matchesCriteria"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Method to determine whether a Live Update Topic qualifies for a given Topic Criteria"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdateTopic\/matchesCriteria(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"matchesCriteria:"}],"url":"\/documentation\/mapsindoors\/mpliveupdatetopic\/matchescriteria(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"matchesCriteria:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"matchesCriteria:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"matchesCriteria:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria","text":"MPLiveTopicCriteria"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"criteria"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic\/title","value":"MPLiveUpdateTopic"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic\/fragments","value":[{"kind":"identifier","text":"MPLiveUpdateTopic"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria\/title","value":"MPLiveTopicCriteria"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria\/fragments","value":[{"kind":"identifier","text":"MPLiveTopicCriteria"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic~1matchesCriteria(_:)\/title","value":"matchesCriteria:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveUpdateTopic~1matchesCriteria(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"matchesCriteria:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}