{"metadata":{"role":"symbol","externalID":"c:@M@MapsIndoors@objc(cs)MPPositionLiveUpdate(im)initWithLiveUpdate:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithLiveUpdate:"}],"modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithLiveUpdate:","kind":"identifier"}],"symbolKind":"method","title":"initWithLiveUpdate:"},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionLiveUpdate\/initWithLiveUpdate:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionLiveUpdate"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mppositionliveupdate\/initwithliveupdate:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithLiveUpdate:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"MPLiveUpdate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"withLiveUpdate"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionLiveUpdate":{"role":"symbol","abstract":[{"text":"Model for live position information for a given Location.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mppositionliveupdate","navigatorTitle":[{"text":"MPPositionLiveUpdate","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionLiveUpdate","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionLiveUpdate"}],"title":"MPPositionLiveUpdate"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/getLiveUpdate(forDomainType:)":{"title":"getLiveUpdate(forDomainType:)","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"getLiveUpdateForDomainType:"}],"type":"topic","abstract":[{"text":"Get a live update based on a known domain type.","type":"text"}],"url":"\/documentation\/mapsindoors\/mplocation\/getliveupdate(fordomaintype:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getLiveUpdate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forDomainType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate","kind":"typeIdentifier","text":"MPLiveUpdate"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","role":"symbol"},"MapsPeopleWhite.png":{"type":"image","alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionLiveUpdate/initWithLiveUpdate:":{"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/mapsindoors\/mppositionliveupdate\/initwithliveupdate:","navigatorTitle":[{"text":"initWithLiveUpdate:","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionLiveUpdate\/initWithLiveUpdate:","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLiveUpdate:"}],"title":"initWithLiveUpdate:"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate":{"url":"\/documentation\/mapsindoors\/mpliveupdate","title":"MPLiveUpdate","navigatorTitle":[{"kind":"identifier","text":"MPLiveUpdate"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","abstract":[{"type":"text","text":"Model for a Live Update. Used in "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","isActive":true,"type":"reference"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLiveUpdate","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionLiveUpdate\/title","op":"replace","value":"MPPositionLiveUpdate"},{"op":"replace","value":[{"text":"MPPositionLiveUpdate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionLiveUpdate\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/title","value":"getLiveUpdateForDomainType:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getLiveUpdateForDomainType:"}]},{"value":"MPLiveUpdate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/fragments","value":[{"text":"MPLiveUpdate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}