{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/delegate","interfaceLanguage":"swift"},"metadata":{"title":"delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"MapsIndoors"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPSubscriptionClient(py)delegate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionClientDelegate","text":"MPSubscriptionClientDelegate","kind":"typeIdentifier"}],"required":true},"variants":[{"paths":["\/documentation\/mapsindoors\/mpsubscriptionclient\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpsubscriptionclient\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionClientDelegate","text":"MPSubscriptionClientDelegate","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClient/delegate":{"required":true,"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/delegate","type":"topic","url":"\/documentation\/mapsindoors\/mpsubscriptionclient\/delegate","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPSubscriptionClientDelegate","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionClientDelegate"}],"title":"delegate"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClient":{"navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionClient"}],"title":"MPSubscriptionClient","type":"topic","url":"\/documentation\/mapsindoors\/mpsubscriptionclient","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPSubscriptionClient","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient","role":"symbol","abstract":[],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClientDelegate":{"navigatorTitle":[{"text":"MPSubscriptionClientDelegate","kind":"identifier"}],"title":"MPSubscriptionClientDelegate","url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPSubscriptionClientDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate","role":"symbol","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"delegate","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPSubscriptionClientDelegate","text":"id<MPSubscriptionClientDelegate>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"delegate","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"delegate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient~1delegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MPSubscriptionClient","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPSubscriptionClient"}]},{"value":"MPSubscriptionClientDelegate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MPSubscriptionClientDelegate"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}