{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/unsubscribe(_:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unsubscribe"},{"kind":"text","text":"("},{"text":"MPSubscriptionTopic","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionTopic"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"unsubscribe:"}],"modules":[{"name":"MapsIndoors"}],"roleHeading":"Instance Method","symbolKind":"method","required":true,"title":"unsubscribe(_:)","externalID":"c:@M@MapsIndoors@objc(pl)MPSubscriptionClient(im)unsubscribe:"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"unsubscribe","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"topic","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionTopic","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionTopic","text":"MPSubscriptionTopic"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpsubscriptionclient\/unsubscribe(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpsubscriptionclient\/unsubscribe(_:)"]}],"references":{"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionTopic":{"url":"\/documentation\/mapsindoors\/mpsubscriptiontopic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPSubscriptionTopic"}],"title":"MPSubscriptionTopic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionTopic","navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionTopic"}],"abstract":[],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClient":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPSubscriptionClient","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MPSubscriptionClient","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpsubscriptionclient","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient","abstract":[],"title":"MPSubscriptionClient"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClient/unsubscribe(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsubscribe"},{"text":"(","kind":"text"},{"text":"MPSubscriptionTopic","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionTopic"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"unsubscribe:"}],"url":"\/documentation\/mapsindoors\/mpsubscriptionclient\/unsubscribe(_:)","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/unsubscribe(_:)","required":true,"abstract":[],"title":"unsubscribe(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"unsubscribe:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unsubscribe:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"unsubscribe:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPSubscriptionTopic","text":"id<MPSubscriptionTopic>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"topic"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionTopic\/title","value":"MPSubscriptionTopic","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionTopic\/fragments","value":[{"text":"MPSubscriptionTopic","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient\/title","value":"MPSubscriptionClient"},{"value":[{"kind":"identifier","text":"MPSubscriptionClient"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient~1unsubscribe(_:)\/title","value":"unsubscribe:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient~1unsubscribe(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"unsubscribe:","kind":"identifier"}]}]}]}