{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class","preciseIdentifier":"c:objc(cs)MPBuilding","text":"MPBuilding"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpvenue-swift.class\/buildings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpvenue-swift.class\/buildings"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/buildings","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Container array for buildings in this venue. Note that this array are not populated initially. "},{"type":"codeVoice","code":"MPMapControl"},{"type":"text","text":" will populate this for the active venue."},{"type":"text","text":" "},{"type":"text","text":"To get the buildings for an arbitrary venue, please use "},{"type":"codeVoice","code":"MPVenueProvider.getBuildingsWithCompletion()"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPBuilding","preciseIdentifier":"c:objc(cs)MPBuilding"},{"kind":"text","text":"]?"}],"title":"buildings","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPVenue(py)buildings","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"buildings"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/buildings":{"role":"symbol","title":"buildings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPBuilding","preciseIdentifier":"c:objc(cs)MPBuilding"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Container array for buildings in this venue. Note that this array are not populated initially. "},{"type":"codeVoice","code":"MPMapControl"},{"type":"text","text":" will populate this for the active venue."},{"type":"text","text":" "},{"type":"text","text":"To get the buildings for an arbitrary venue, please use "},{"type":"codeVoice","code":"MPVenueProvider.getBuildingsWithCompletion()"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/buildings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildings"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/buildings"},"doc://MapsIndoors/documentation/MapsIndoors/MPBuilding-swift.class":{"role":"symbol","title":"MPBuilding","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuilding"}],"abstract":[{"type":"text","text":"Holds relevant data for a single building, and the buildings floor levels."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBuilding-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBuilding"}],"url":"\/documentation\/mapsindoors\/mpbuilding-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class":{"role":"symbol","title":"MPVenue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenue"}],"abstract":[{"type":"text","text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenue"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"buildings"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"buildings"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<MPBuilding *><MPBuilding,Optional>","preciseIdentifier":"c:Q$objc(cs)NSArrayobjc(pl)MPBuildingobjc(pl)Optional"},{"kind":"text","text":" * "},{"kind":"identifier","text":"buildings"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1buildings\/title","value":"buildings"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1buildings\/fragments","value":[{"kind":"identifier","text":"buildings"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class\/title","value":"MPBuilding"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBuilding-swift.class\/fragments","value":[{"kind":"identifier","text":"MPBuilding"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class\/title","value":"MPVenue"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class\/fragments","value":[{"kind":"identifier","text":"MPVenue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}