{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBoundingBox"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpvenue-swift.class\/getboundingbox()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpvenue-swift.class\/getboundingbox()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/getBoundingBox()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get the geographic bounding box for the venue"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBoundingBox"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":"?"}],"title":"getBoundingBox()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPVenue(im)getBoundingBox","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getBoundingBox"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/getBoundingBox()":{"role":"symbol","title":"getBoundingBox()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBoundingBox"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the geographic bounding box for the venue"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/getBoundingBox()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getBoundingBox"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/getboundingbox()"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class":{"role":"symbol","title":"MPVenue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenue"}],"abstract":[{"type":"text","text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenue"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getBoundingBox"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBoundingBox"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getBoundingBox"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1getBoundingBox()\/title","value":"getBoundingBox"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1getBoundingBox()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBoundingBox"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class\/title","value":"MPVenue"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class\/fragments","value":[{"kind":"identifier","text":"MPVenue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}