{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDefaultStyle"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapStyle-swift.class","preciseIdentifier":"c:objc(cs)MPMapStyle","text":"MPMapStyle"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpvenue-swift.class\/getdefaultstyle()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpvenue-swift.class\/getdefaultstyle()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/getDefaultStyle()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get a default style. If none is set, it will be the first string value in the list of map styles"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDefaultStyle"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MPMapStyle","preciseIdentifier":"c:objc(cs)MPMapStyle"},{"kind":"text","text":"?"}],"title":"getDefaultStyle()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPVenue(im)getDefaultStyle","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getDefaultStyle"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class/getDefaultStyle()":{"role":"symbol","title":"getDefaultStyle()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDefaultStyle"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MPMapStyle","preciseIdentifier":"c:objc(cs)MPMapStyle"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get a default style. If none is set, it will be the first string value in the list of map styles"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class\/getDefaultStyle()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDefaultStyle"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class\/getdefaultstyle()"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapStyle-swift.class":{"role":"symbol","title":"MPMapStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapStyle"}],"abstract":[{"type":"text","text":"Map style used by MapsPeoples services. The map style refers to a graphical layout of the building floor plans."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapStyle-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMapStyle"}],"url":"\/documentation\/mapsindoors\/mpmapstyle-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenue-swift.class":{"role":"symbol","title":"MPVenue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenue"}],"abstract":[{"type":"text","text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenue-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenue"}],"url":"\/documentation\/mapsindoors\/mpvenue-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getDefaultStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDefaultStyle"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapStyle-swift.class","preciseIdentifier":"c:objc(cs)MPMapStyle","text":"MPMapStyle"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getDefaultStyle"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1getDefaultStyle()\/title","value":"getDefaultStyle"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class~1getDefaultStyle()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDefaultStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapStyle-swift.class\/title","value":"MPMapStyle"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapStyle-swift.class\/fragments","value":[{"kind":"identifier","text":"MPMapStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class\/title","value":"MPVenue"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenue-swift.class\/fragments","value":[{"kind":"identifier","text":"MPVenue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}