{"kind":"symbol","metadata":{"externalID":"s:s9CodingKeyPsE16debugDescriptionSSvp::SYNTHESIZED::s:11MapsIndoors12MPEntityInfoC10CodingKeysO","roleHeading":"Instance Property","modules":[{"relatedModules":["Swift"],"name":"MapsIndoors"}],"symbolKind":"property","title":"debugDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"debugDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","extendedModule":"Swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"CodingKey.debugDescription","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpentityinfo\/codingkeys\/debugdescription"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debugDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntityInfo","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntityInfo\/CodingKeys","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntityInfo\/CodingKeys\/CodingKey-Implementations"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntityInfo\/CodingKeys\/debugDescription","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPEntityInfo/CodingKeys/debugDescription":{"abstract":[],"title":"debugDescription","type":"topic","role":"symbol","url":"\/documentation\/mapsindoors\/mpentityinfo\/codingkeys\/debugdescription","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"debugDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntityInfo\/CodingKeys\/debugDescription","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding":{"url":"\/documentation\/mapsindoors\/mpbuilding","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPBuilding","kind":"identifier"}],"abstract":[{"type":"text","text":"Holds relevant data for a single building, and the buildings floor levels."}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MPBuilding","kind":"identifier"}],"title":"MPBuilding","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding"},"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","title":"MPLocation","url":"\/documentation\/mapsindoors\/mplocation","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPLocation"}],"type":"topic","abstract":[{"type":"text","text":"This holds the data for a single location and a marker to display the data on a map."}],"role":"symbol","navigatorTitle":[{"text":"MPLocation","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue":{"url":"\/documentation\/mapsindoors\/mpvenue","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPVenue"}],"abstract":[{"type":"text","text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data."}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPVenue"}],"title":"MPVenue","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPEntityInfo/CodingKeys":{"url":"\/documentation\/mapsindoors\/mpentityinfo\/codingkeys","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CodingKeys"}],"abstract":[],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"CodingKeys","kind":"identifier"}],"title":"MPEntityInfo.CodingKeys","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntityInfo\/CodingKeys"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPEntityInfo":{"url":"\/documentation\/mapsindoors\/mpentityinfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPEntityInfo"}],"abstract":[{"type":"text","text":"MPEntityInfo  is a general class used by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","type":"reference","isActive":true},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","type":"reference"},{"type":"text","text":" for the relevant info (eg buildingInfo, venueInfo etc)"}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MPEntityInfo","kind":"identifier"}],"title":"MPEntityInfo","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntityInfo"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPEntityInfo/CodingKeys/CodingKey-Implementations":{"url":"\/documentation\/mapsindoors\/mpentityinfo\/codingkeys\/codingkey-implementations","abstract":[],"role":"collectionGroup","type":"topic","kind":"article","title":"CodingKey Implementations","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntityInfo\/CodingKeys\/CodingKey-Implementations"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/title","value":"MPBuilding"},{"value":[{"text":"MPBuilding","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/title","value":"MPLocation"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPLocation"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/title","op":"replace","value":"MPVenue"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/fragments","value":[{"text":"MPVenue","kind":"identifier"}],"op":"replace"},{"value":"MPEntityInfo","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntityInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntityInfo\/fragments","value":[{"text":"MPEntityInfo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}