{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"relativeHumidity"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation11MeasurementV","kind":"typeIdentifier","text":"Measurement"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHumidity","text":"MPHumidity","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidity","kind":"typeIdentifier"},{"text":"> { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidityLiveUpdate"]]},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"relativeHumidity"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation11MeasurementV","text":"Measurement"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHumidity","text":"MPHumidity","kind":"typeIdentifier"},{"kind":"text","text":">"}],"modules":[{"name":"MapsIndoors"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"relativeHumidity","navigatorTitle":[{"text":"relativeHumidity","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPHumidityLiveUpdate(py)relativeHumidity"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"The measured relative humidity for a given Location.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mphumidityliveupdate\/relativehumidity"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mphumidityliveupdate\/relativehumidity"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidityLiveUpdate\/relativeHumidity","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHumidityLiveUpdate/relativeHumidity":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"relativeHumidity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Measurement","preciseIdentifier":"s:10Foundation11MeasurementV","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHumidity","text":"MPHumidity","kind":"typeIdentifier"},{"kind":"text","text":">"}],"url":"\/documentation\/mapsindoors\/mphumidityliveupdate\/relativehumidity","navigatorTitle":[{"kind":"identifier","text":"relativeHumidity"}],"role":"symbol","abstract":[{"text":"The measured relative humidity for a given Location.","type":"text"}],"title":"relativeHumidity","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidityLiveUpdate\/relativeHumidity"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHumidity":{"role":"symbol","url":"\/documentation\/mapsindoors\/mphumidity","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidity","abstract":[],"navigatorTitle":[{"text":"MPHumidity","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPHumidity"}],"title":"MPHumidity","type":"topic","kind":"symbol"},"MapsPeopleWhite.png":{"alt":null,"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHumidityLiveUpdate":{"role":"symbol","abstract":[{"type":"text","text":"Model for live humidity measurement for a given location."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidityLiveUpdate","navigatorTitle":[{"text":"MPHumidityLiveUpdate","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mphumidityliveupdate","title":"MPHumidityLiveUpdate","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPHumidityLiveUpdate"}],"kind":"symbol","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"relativeHumidity"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"relativeHumidity","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSMeasurement<MPHumidity *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSMeasurement"},{"kind":"text","text":" * "},{"kind":"identifier","text":"relativeHumidity"}]}]}},{"op":"replace","value":"relativeHumidity","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHumidityLiveUpdate~1relativeHumidity\/title"},{"op":"replace","value":[{"kind":"identifier","text":"relativeHumidity"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHumidityLiveUpdate~1relativeHumidity\/fragments"},{"op":"replace","value":"MPHumidity","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHumidity\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHumidity\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPHumidity"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHumidityLiveUpdate\/title","value":"MPHumidityLiveUpdate","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHumidityLiveUpdate\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPHumidityLiveUpdate"}]}]}]}