{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProviderDelegate","preciseIdentifier":"c:objc(pl)MPAppDataProviderDelegate","text":"MPAppDataProviderDelegate"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpappdataprovider\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpappdataprovider\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider\/delegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Delegate object. This is another way of handling data fetching. Using completionHandler block instead is recommended."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPAppDataProviderDelegate","preciseIdentifier":"c:objc(pl)MPAppDataProviderDelegate"},{"kind":"text","text":"?"}],"title":"delegate","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPAppDataProvider(py)delegate","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPAppDataProviderDelegate":{"role":"symbol","title":"MPAppDataProviderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPAppDataProviderDelegate"}],"abstract":[{"type":"text","text":"App data provider delegate."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProviderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPAppDataProviderDelegate"}],"url":"\/documentation\/mapsindoors\/mpappdataproviderdelegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPAppDataProvider":{"role":"symbol","title":"MPAppDataProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPAppDataProvider"}],"abstract":[{"type":"text","text":"The app data provider acts as a service for the metadata (MPAppData) of a MapsIndoors app solution."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPAppDataProvider"}],"url":"\/documentation\/mapsindoors\/mpappdataprovider"},"doc://MapsIndoors/documentation/MapsIndoors/MPAppDataProvider/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPAppDataProviderDelegate","preciseIdentifier":"c:objc(pl)MPAppDataProviderDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Delegate object. This is another way of handling data fetching. Using completionHandler block instead is recommended."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/mapsindoors\/mpappdataprovider\/delegate"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<MPAppDataProviderDelegate>","preciseIdentifier":"c:Qoobjc(pl)MPAppDataProviderDelegate"},{"kind":"text","text":" *"},{"kind":"identifier","text":"delegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProviderDelegate\/title","value":"MPAppDataProviderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProviderDelegate\/fragments","value":[{"kind":"identifier","text":"MPAppDataProviderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider\/title","value":"MPAppDataProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider\/fragments","value":[{"kind":"identifier","text":"MPAppDataProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}