{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCoordinateBounds"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocation-swift.class\/getcoordinatebounds()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocation-swift.class\/getcoordinatebounds()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getCoordinateBounds()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get coordinate bounds for the location object"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCoordinateBounds"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":"?"}],"title":"getCoordinateBounds()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPLocation(im)getCoordinateBounds","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getCoordinateBounds"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/getCoordinateBounds()":{"role":"symbol","title":"getCoordinateBounds()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCoordinateBounds"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get coordinate bounds for the location object"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getCoordinateBounds()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getCoordinateBounds"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/getcoordinatebounds()"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class":{"role":"symbol","title":"MPLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"abstract":[{"type":"text","text":"This class holds the data for a single location and a marker to display the data on a map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getCoordinateBounds"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCoordinateBounds"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"GMSCoordinateBounds","preciseIdentifier":"c:objc(cs)GMSCoordinateBounds"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getCoordinateBounds"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1getCoordinateBounds()\/title","value":"getCoordinateBounds"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1getCoordinateBounds()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCoordinateBounds"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/title","value":"MPLocation"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/fragments","value":[{"kind":"identifier","text":"MPLocation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}