{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLiveUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forDomainType"},{"kind":"text","text":" "},{"kind":"internalParam","text":"domainType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdate","preciseIdentifier":"c:objc(cs)MPLiveUpdate","text":"MPLiveUpdate"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocation-swift.class\/getliveupdate(fordomaintype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocation-swift.class\/getliveupdate(fordomaintype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getLiveUpdate(forDomainType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get a live update based on a known domain type"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLiveUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forDomainType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLiveUpdate","preciseIdentifier":"c:objc(cs)MPLiveUpdate"},{"kind":"text","text":"?"}],"title":"getLiveUpdate(forDomainType:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPLocation(im)getLiveUpdateForDomainType:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getLiveUpdateForDomainType:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLiveUpdate":{"role":"symbol","title":"MPLiveUpdate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveUpdate"}],"abstract":[{"type":"text","text":"Model for a Live Update. Used in MPLiveDataManagerDelegate and MPLocation::getLiveUpdate()."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveUpdate"}],"url":"\/documentation\/mapsindoors\/mpliveupdate"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class/getLiveUpdate(forDomainType:)":{"role":"symbol","title":"getLiveUpdate(forDomainType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLiveUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forDomainType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLiveUpdate","preciseIdentifier":"c:objc(cs)MPLiveUpdate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get a live update based on a known domain type"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class\/getLiveUpdate(forDomainType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getLiveUpdateForDomainType:"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class\/getliveupdate(fordomaintype:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class":{"role":"symbol","title":"MPLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"abstract":[{"type":"text","text":"This class holds the data for a single location and a marker to display the data on a map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getLiveUpdateForDomainType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLiveUpdateForDomainType:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveUpdate","preciseIdentifier":"c:objc(cs)MPLiveUpdate","text":"MPLiveUpdate"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getLiveUpdateForDomainType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"domainType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveUpdate\/title","value":"MPLiveUpdate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveUpdate\/fragments","value":[{"kind":"identifier","text":"MPLiveUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1getLiveUpdate(forDomainType:)\/title","value":"getLiveUpdateForDomainType:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class~1getLiveUpdate(forDomainType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLiveUpdateForDomainType:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/title","value":"MPLocation"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/fragments","value":[{"kind":"identifier","text":"MPLocation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}