{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"properties"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMutableDictionary","preciseIdentifier":"c:objc(cs)NSMutableDictionary"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppositionresult\/properties"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppositionresult\/properties"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/properties","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Properties dictionary"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"properties"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMutableDictionary","preciseIdentifier":"c:objc(cs)NSMutableDictionary"},{"kind":"text","text":"?"}],"title":"properties","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPPositionResult(py)properties","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"properties"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult/properties":{"role":"symbol","title":"properties","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"properties"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMutableDictionary","preciseIdentifier":"c:objc(cs)NSMutableDictionary"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Properties dictionary"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/properties","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"properties"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/properties"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult":{"role":"symbol","title":"MPPositionResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionResult"}],"abstract":[{"type":"text","text":"Position result model"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPositionResult"}],"url":"\/documentation\/mapsindoors\/mppositionresult"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"properties"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"properties"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSMutableDictionary","preciseIdentifier":"c:objc(cs)NSMutableDictionary"},{"kind":"text","text":" *"},{"kind":"identifier","text":"properties"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1properties\/title","value":"properties"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1properties\/fragments","value":[{"kind":"identifier","text":"properties"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult\/title","value":"MPPositionResult"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult\/fragments","value":[{"kind":"identifier","text":"MPPositionResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}