{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"types"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpfilter\/types"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpfilter\/types"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFilter\/types","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Types filter. List of type names as in "},{"type":"codeVoice","code":"MPLocation.type"},{"type":"text","text":". If multiple types are supplied the filter will OR’ed, meaning if a location belongs to at least one of the types it will be considered as a match."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"types"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"title":"types","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPFilter(py)types","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"types"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFilter"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPFilter":{"role":"symbol","title":"MPFilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFilter"}],"abstract":[{"type":"text","text":"Filter object used when making a request to "},{"type":"codeVoice","code":"MPLocationService"},{"type":"text","text":". The filters will be applied in the following order:"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPFilter"}],"url":"\/documentation\/mapsindoors\/mpfilter"},"doc://MapsIndoors/documentation/MapsIndoors/MPFilter/types":{"role":"symbol","title":"types","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"types"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Types filter. List of type names as in "},{"type":"codeVoice","code":"MPLocation.type"},{"type":"text","text":". If multiple types are supplied the filter will OR’ed, meaning if a location belongs to at least one of the types it will be considered as a match."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFilter\/types","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"types"}],"url":"\/documentation\/mapsindoors\/mpfilter\/types"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"types"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"types"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *"},{"kind":"identifier","text":"types"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFilter\/title","value":"MPFilter"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFilter\/fragments","value":[{"kind":"identifier","text":"MPFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFilter~1types\/title","value":"types"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFilter~1types\/fragments","value":[{"kind":"identifier","text":"types"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}