{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addParam"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpuritemplate\/addparam(_:value:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpuritemplate\/addparam(_:value:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/addParam(_:value:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Find the parameter placeholder {name} with given name and replace with given string value"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addParam"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"addParam(_:value:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPURITemplate(im)addParam:value:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"addParam:value:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPURITemplate":{"role":"symbol","title":"MPURITemplate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPURITemplate"}],"abstract":[{"type":"text","text":"Generates an url based on an URI template. Template string must have format “prefix{param_1}infix{param_N}suffix”, e.g.: “http:\/\/tiles.url.com\/{floor}\/{x}\/{y}\/{zoom}.png”"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPURITemplate"}],"url":"\/documentation\/mapsindoors\/mpuritemplate"},"doc://MapsIndoors/documentation/MapsIndoors/MPURITemplate/addParam(_:value:)":{"role":"symbol","title":"addParam(_:value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addParam"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Find the parameter placeholder {name} with given name and replace with given string value"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/addParam(_:value:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addParam:value:"}],"url":"\/documentation\/mapsindoors\/mpuritemplate\/addparam(_:value:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addParam:value:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addParam:value:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addParam:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"name"},{"kind":"text","text":" "},{"kind":"identifier","text":"value:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate\/title","value":"MPURITemplate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate\/fragments","value":[{"kind":"identifier","text":"MPURITemplate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate~1addParam(_:value:)\/title","value":"addParam:value:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate~1addParam(_:value:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addParam:value:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}