{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetParams"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpuritemplate\/resetparams()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpuritemplate\/resetparams()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/resetParams()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Reset the url parameters."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetParams"},{"kind":"text","text":"()"}],"title":"resetParams()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPURITemplate(im)resetParams","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"resetParams"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPURITemplate/resetParams()":{"role":"symbol","title":"resetParams()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetParams"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Reset the url parameters."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/resetParams()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resetParams"}],"url":"\/documentation\/mapsindoors\/mpuritemplate\/resetparams()"},"doc://MapsIndoors/documentation/MapsIndoors/MPURITemplate":{"role":"symbol","title":"MPURITemplate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPURITemplate"}],"abstract":[{"type":"text","text":"Generates an url based on an URI template. Template string must have format “prefix{param_1}infix{param_N}suffix”, e.g.: “http:\/\/tiles.url.com\/{floor}\/{x}\/{y}\/{zoom}.png”"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPURITemplate"}],"url":"\/documentation\/mapsindoors\/mpuritemplate"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"resetParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetParams"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"resetParams"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate~1resetParams()\/title","value":"resetParams"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate~1resetParams()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetParams"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate\/title","value":"MPURITemplate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate\/fragments","value":[{"kind":"identifier","text":"MPURITemplate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}