{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"findNearestRouteSegmentPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"point"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class","preciseIdentifier":"c:objc(cs)MPPoint","text":"MPPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"floor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"floorIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteSegmentPath","preciseIdentifier":"c:@S@MPRouteSegmentPath","text":"MPRouteSegmentPath"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"point","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The point to find the nearest route segment from"}]}]},{"name":"floor","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The floor to search"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mproute-swift.class\/findnearestroutesegmentpath(from:floor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mproute-swift.class\/findnearestroutesegmentpath(from:floor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/findNearestRouteSegmentPath(from:floor:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Find route segment path (route leg and route step) nearest to a point and floor index."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"findNearestRouteSegmentPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"floor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPRouteSegmentPath","preciseIdentifier":"c:@S@MPRouteSegmentPath"}],"title":"findNearestRouteSegmentPath(from:floor:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPRoute(im)findNearestRouteSegmentPathFromPoint:floor:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"findNearestRouteSegmentPathFromPoint:floor:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPRoute-swift.class":{"role":"symbol","title":"MPRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoute"}],"abstract":[{"type":"text","text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the "},{"type":"codeVoice","code":"MPDirectionsService"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRoute"}],"url":"\/documentation\/mapsindoors\/mproute-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoute-swift.class/findNearestRouteSegmentPath(from:floor:)":{"role":"symbol","title":"findNearestRouteSegmentPath(from:floor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"findNearestRouteSegmentPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"floor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPRouteSegmentPath","preciseIdentifier":"c:@S@MPRouteSegmentPath"}],"abstract":[{"type":"text","text":"Find route segment path (route leg and route step) nearest to a point and floor index."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/findNearestRouteSegmentPath(from:floor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"findNearestRouteSegmentPathFromPoint:floor:"}],"url":"\/documentation\/mapsindoors\/mproute-swift.class\/findnearestroutesegmentpath(from:floor:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteSegmentPath":{"role":"symbol","title":"MPRouteSegmentPath","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteSegmentPath"}],"abstract":[{"type":"text","text":"Route segment path model"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteSegmentPath","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteSegmentPath"}],"url":"\/documentation\/mapsindoors\/mproutesegmentpath"},"doc://MapsIndoors/documentation/MapsIndoors/MPPoint-swift.class":{"role":"symbol","title":"MPPoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPoint"}],"abstract":[{"type":"text","text":"Basic point geometry class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPoint"}],"url":"\/documentation\/mapsindoors\/mppoint-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"findNearestRouteSegmentPathFromPoint:floor:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"findNearestRouteSegmentPathFromPoint:floor:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteSegmentPath","preciseIdentifier":"c:@S@MPRouteSegmentPath","text":"MPRouteSegmentPath"},{"kind":"text","text":") "},{"kind":"identifier","text":"findNearestRouteSegmentPathFromPoint:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPoint-swift.class","preciseIdentifier":"c:objc(cs)MPPoint","text":"MPPoint"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"point"},{"kind":"text","text":" "},{"kind":"identifier","text":"floor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"floorIndex"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class\/title","value":"MPRoute"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class\/fragments","value":[{"kind":"identifier","text":"MPRoute"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1findNearestRouteSegmentPath(from:floor:)\/title","value":"findNearestRouteSegmentPathFromPoint:floor:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1findNearestRouteSegmentPath(from:floor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"findNearestRouteSegmentPathFromPoint:floor:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteSegmentPath\/title","value":"MPRouteSegmentPath"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteSegmentPath\/fragments","value":[{"kind":"identifier","text":"MPRouteSegmentPath"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class\/title","value":"MPPoint"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPoint-swift.class\/fragments","value":[{"kind":"identifier","text":"MPPoint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}