{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"legs"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLegProtocol","preciseIdentifier":"c:objc(pl)MPRouteLeg","text":"MPRouteLegProtocol"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mproute-swift.class\/legs"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mproute-swift.class\/legs"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/legs","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The route legs: the different route components. Typically a route from 1st floor to 2nd floor will consist of two route legs."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"legs"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"MPRouteLegProtocol","preciseIdentifier":"c:objc(pl)MPRouteLeg"},{"kind":"text","text":")?"}],"title":"legs","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPRoute(py)legs","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"legs"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLegProtocol":{"role":"symbol","title":"MPRouteLegProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteLegProtocol"}],"abstract":[{"type":"text","text":"Protocol MPRouteLeg specification."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLegProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteLegProtocol"}],"url":"\/documentation\/mapsindoors\/mproutelegprotocol"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoute-swift.class/legs":{"role":"symbol","title":"legs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"legs"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"MPRouteLegProtocol","preciseIdentifier":"c:objc(pl)MPRouteLeg"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The route legs: the different route components. Typically a route from 1st floor to 2nd floor will consist of two route legs."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/legs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"legs"}],"url":"\/documentation\/mapsindoors\/mproute-swift.class\/legs"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoute-swift.class":{"role":"symbol","title":"MPRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoute"}],"abstract":[{"type":"text","text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the "},{"type":"codeVoice","code":"MPDirectionsService"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRoute"}],"url":"\/documentation\/mapsindoors\/mproute-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"legs"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"legs"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSMutableArray<MPRouteLeg *><MPRouteLeg,Optional>","preciseIdentifier":"c:Q$objc(cs)NSMutableArrayobjc(pl)MPRouteLegobjc(pl)Optional"},{"kind":"text","text":" *"},{"kind":"identifier","text":"legs"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLegProtocol\/title","value":"MPRouteLeg"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLegProtocol\/fragments","value":[{"kind":"identifier","text":"MPRouteLeg"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1legs\/title","value":"legs"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1legs\/fragments","value":[{"kind":"identifier","text":"legs"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class\/title","value":"MPRoute"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class\/fragments","value":[{"kind":"identifier","text":"MPRoute"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}