{"abstract":[{"type":"text","text":"Categories filter. List of category keys as in "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/categories"},{"type":"text","text":". If multiple categories are supplied the filter will OR’ed, meaning if a Location belongs to at least one of the categories it will be considered as a match."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"categories"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"role":"symbol","title":"categories","modules":[{"name":"MapsIndoors"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPFilter(py)categories","navigatorTitle":[{"text":"categories","kind":"identifier"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"categories","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/categories","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mapsindoors\/mpfilter\/categories"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpfilter\/categories"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/categories":{"url":"\/documentation\/mapsindoors\/mpfilter\/categories","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/categories","navigatorTitle":[{"text":"categories","kind":"identifier"}],"title":"categories","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"categories","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"abstract":[{"text":"Categories filter. List of category keys as in ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/categories","isActive":true,"type":"reference"},{"type":"text","text":". If multiple categories are supplied the filter will OR’ed, meaning if a Location belongs to at least one of the categories it will be considered as a match."}],"type":"topic","kind":"symbol","role":"symbol"},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null,"identifier":"MapsPeopleWhite.png","type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/categories":{"url":"\/documentation\/mapsindoors\/mplocation\/categories","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/categories","navigatorTitle":[{"kind":"identifier","text":"categories"}],"title":"categories","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"categories","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"abstract":[{"text":"The categories for this location, as an array.","type":"text"}],"kind":"symbol","type":"topic","required":true,"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/locationsWith(query:filter:)":{"required":true,"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/locationswith(query:filter:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","abstract":[{"type":"text","text":"Search for MPLocations using MPQuery and\/or MPFilter."}],"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"locationsWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"query","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPQuery","text":"MPQuery","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"filter"},{"kind":"text","text":": "},{"text":"MPFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilter"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ["},{"text":"MPLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"kind":"text","text":"]"}],"kind":"symbol","title":"locationsWith(query:filter:)","navigatorTitle":[{"kind":"identifier","text":"locationsWithQuery:filter:completionHandler:"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPFilter","kind":"identifier"}],"navigatorTitle":[{"text":"MPFilter","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpfilter","kind":"symbol","abstract":[{"text":"Filter object used when making a request to e.g. ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter","role":"symbol","type":"topic","title":"MPFilter"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"categories","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"categories","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"categories"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"categories","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1categories\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1categories\/fragments","value":[{"kind":"identifier","text":"categories"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1categories\/title","op":"replace","value":"categories"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1categories\/fragments","value":[{"kind":"identifier","text":"categories"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/title","op":"replace","value":"locationsWithQuery:filter:completionHandler:"},{"value":[{"text":"- ","kind":"text"},{"text":"locationsWithQuery:filter:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter\/title","value":"MPFilter","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter\/fragments","value":[{"text":"MPFilter","kind":"identifier"}],"op":"replace"}]}]}