{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpfilter\/init(categories:bounds:parents:take:skip:depth:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpfilter\/init(categories:bounds:parents:take:skip:depth:)"]}],"abstract":[{"text":"Initialise a MPFilter with all properties.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"From Swift all values are optional which will set them to the default values."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"categories"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]? = [], "},{"text":"bounds","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds","text":"MPGeoBounds"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"parents"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]? = [], ","kind":"text"},{"kind":"externalParam","text":"take"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" = Int.max, "},{"text":"skip","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":" = 0, "},{"kind":"externalParam","text":"depth"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" = 1)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/categories"},{"type":"text","text":". Default is an empty array."}],"type":"paragraph"}],"name":"categories"},{"content":[{"inlineContent":[{"type":"text","text":"See "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/bounds","isActive":true},{"text":". Default is ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"bounds"},{"content":[{"inlineContent":[{"type":"text","text":"See "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/parents","isActive":true},{"type":"text","text":". Default is an empty array."}],"type":"paragraph"}],"name":"parents"},{"name":"take","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"See "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/take","isActive":true,"type":"reference"},{"type":"text","text":". Default is maximum integer value (all)."}]}]},{"name":"skip","content":[{"type":"paragraph","inlineContent":[{"text":"See ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/skip","isActive":true,"type":"reference"},{"type":"text","text":". Default is "},{"code":"0","type":"codeVoice"},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"See "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/depth","isActive":true},{"text":". Default is ","type":"text"},{"type":"codeVoice","code":"1"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"depth"}]}],"metadata":{"title":"init(categories:bounds:parents:take:skip:depth:)","symbolKind":"init","roleHeading":"Initializer","role":"symbol","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"initWithCategories:bounds:parents:take:skip:depth:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"categories"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"bounds"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","text":"MPGeoBounds","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"parents"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"take"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"skip","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"depth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPFilter(im)initWithCategories:bounds:parents:take:skip:depth:"},"sections":[],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/init(categories:bounds:parents:take:skip:depth:)","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoBounds":{"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds","title":"MPGeoBounds","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPGeoBounds"}],"kind":"symbol","abstract":[],"url":"\/documentation\/mapsindoors\/mpgeobounds","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPGeoBounds","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/skip":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"skip","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"skip"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/mapsindoors\/mpfilter\/skip","abstract":[{"type":"text","text":"Skip locations in the result, e.g. for pagination."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/skip","title":"skip"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/categories":{"title":"categories","type":"topic","role":"symbol","abstract":[{"text":"Categories filter. List of category keys as in ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/categories"},{"text":". If multiple categories are supplied the filter will OR’ed, meaning if a Location belongs to at least one of the categories it will be considered as a match.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpfilter\/categories","navigatorTitle":[{"kind":"identifier","text":"categories"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/categories","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"categories"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/categories":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/categories","abstract":[{"type":"text","text":"The categories for this location, as an array."}],"url":"\/documentation\/mapsindoors\/mplocation\/categories","kind":"symbol","required":true,"role":"symbol","title":"categories","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"categories","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"categories"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPFilter","kind":"identifier"}],"abstract":[{"type":"text","text":"Filter object used when making a request to e.g. "},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","type":"reference"},{"type":"text","text":"."}],"type":"topic","kind":"symbol","url":"\/documentation\/mapsindoors\/mpfilter","title":"MPFilter","navigatorTitle":[{"text":"MPFilter","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/bounds":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bounds","kind":"identifier"},{"kind":"text","text":": "},{"text":"MPGeoBounds","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"bounds","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/bounds","abstract":[{"text":"Rectangular geographical bounds filter.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","title":"bounds","url":"\/documentation\/mapsindoors\/mpfilter\/bounds"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/locationsWith(query:filter:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","required":true,"role":"symbol","abstract":[{"type":"text","text":"Search for MPLocations using MPQuery and\/or MPFilter."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"locationsWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"query","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPQuery","text":"MPQuery","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"filter","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilter","text":"MPFilter"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> [","kind":"text"},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"text":"]","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/locationswith(query:filter:)","title":"locationsWith(query:filter:)","navigatorTitle":[{"text":"locationsWithQuery:filter:completionHandler:","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/parents":{"title":"parents","url":"\/documentation\/mapsindoors\/mpfilter\/parents","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"parents"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"parents","kind":"identifier"}],"abstract":[{"type":"text","text":"List of location ids that is hierarchically considered as a parent of other locations."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/parents","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/take":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"take","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"take","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpfilter\/take","abstract":[{"type":"text","text":"Limit number of locations in the result."}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/take","kind":"symbol","title":"take"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/init(categories:bounds:parents:take:skip:depth:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/init(categories:bounds:parents:take:skip:depth:)","title":"init(categories:bounds:parents:take:skip:depth:)","role":"symbol","abstract":[{"type":"text","text":"Initialise a MPFilter with all properties."},{"type":"text","text":" "},{"text":"From Swift all values are optional which will set them to the default values.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCategories:bounds:parents:take:skip:depth:"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpfilter\/init(categories:bounds:parents:take:skip:depth:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"categories","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"bounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPGeoBounds","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"parents"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?, ","kind":"text"},{"text":"take","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"skip","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"depth","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/depth":{"navigatorTitle":[{"text":"depth","kind":"identifier"}],"kind":"symbol","title":"depth","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"depth"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","abstract":[{"text":"The depth property makes it possible to get the n’th descendant of a parent location.","type":"text"},{"type":"text","text":" "},{"text":"Thus, the depth property only applies to filters that has set one or more parents.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpfilter\/depth","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/depth"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithCategories:bounds:parents:take:skip:depth:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCategories:bounds:parents:take:skip:depth:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithCategories:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"categories"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bounds:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds","text":"MPGeoBounds"},{"kind":"text","text":" *) "},{"text":"bounds","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"parents:"},{"text":"(","kind":"text"},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"parents","kind":"internalParam"},{"kind":"text","text":" "},{"text":"take:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"take"},{"kind":"text","text":" "},{"text":"skip:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"skip","kind":"internalParam"},{"kind":"text","text":" "},{"text":"depth:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"depth","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoBounds\/title","value":"MPGeoBounds","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoBounds\/fragments","value":[{"kind":"identifier","text":"MPGeoBounds"}]},{"value":"skip","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1skip\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1skip\/fragments","value":[{"kind":"identifier","text":"skip"}]},{"op":"replace","value":"categories","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1categories\/title"},{"op":"replace","value":[{"text":"categories","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1categories\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1categories\/title","value":"categories","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1categories\/fragments","value":[{"kind":"identifier","text":"categories"}]},{"value":"MPFilter","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter\/fragments","value":[{"kind":"identifier","text":"MPFilter"}],"op":"replace"},{"value":"bounds","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1bounds\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1bounds\/fragments","value":[{"text":"bounds","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/title","value":"locationsWithQuery:filter:completionHandler:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationsWithQuery:filter:completionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/fragments"},{"op":"replace","value":"parents","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1parents\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1parents\/fragments","value":[{"kind":"identifier","text":"parents"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1take\/title","value":"take"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1take\/fragments","op":"replace","value":[{"text":"take","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1init(categories:bounds:parents:take:skip:depth:)\/title","value":"initWithCategories:bounds:parents:take:skip:depth:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCategories:bounds:parents:take:skip:depth:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1init(categories:bounds:parents:take:skip:depth:)\/fragments"},{"value":"depth","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1depth\/title"},{"value":[{"text":"depth","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1depth\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}