{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/take"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"take"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"take","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"take","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"property","title":"take","externalID":"c:@M@MapsIndoors@objc(cs)MPFilter(py)take","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Limit number of locations in the result.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpfilter\/take"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpfilter\/take"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/take":{"url":"\/documentation\/mapsindoors\/mpfilter\/take","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"take","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"take","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Limit number of locations in the result."}],"kind":"symbol","title":"take","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/take","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter":{"role":"symbol","abstract":[{"type":"text","text":"Filter object used when making a request to e.g. "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","isActive":true},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpfilter","navigatorTitle":[{"text":"MPFilter","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPFilter","kind":"identifier"}],"title":"MPFilter"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"MapsPeopleWhite.png":{"alt":null,"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/locationsWith(query:filter:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"locationsWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"query"},{"text":": ","kind":"text"},{"text":"MPQuery","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPQuery","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"filter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPFilter","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilter"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"kind":"text","text":"]"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"locationsWithQuery:filter:completionHandler:","kind":"identifier"}],"title":"locationsWith(query:filter:)","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/locationswith(query:filter:)","kind":"symbol","required":true,"abstract":[{"type":"text","text":"Search for MPLocations using MPQuery and\/or MPFilter."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"take"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"take","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"take"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"take","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1take\/title","op":"replace"},{"value":[{"text":"take","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1take\/fragments"},{"value":"MPFilter","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/title","value":"locationsWithQuery:filter:completionHandler:"},{"value":[{"kind":"text","text":"- "},{"text":"locationsWithQuery:filter:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/fragments","op":"replace"}]}]}