{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cachingScope"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope","preciseIdentifier":"c:@E@MPDataSetCacheScope","text":"MPDataSetCacheScope"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcacheitem\/cachingscope"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcacheitem\/cachingscope"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachingScope","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Cache scope for this cache item."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cachingScope"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheScope","preciseIdentifier":"c:@E@MPDataSetCacheScope"}],"title":"cachingScope","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPDataSetCacheItem(py)cachingScope","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"cachingScope"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheItem"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheItem":{"role":"symbol","title":"MPDataSetCacheItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheItem"}],"abstract":[{"type":"text","text":"Data set cache item class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheItem"}],"url":"\/documentation\/mapsindoors\/mpdatasetcacheitem"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheScope":{"role":"symbol","title":"MPDataSetCacheScope","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheScope"}],"abstract":[{"type":"text","text":"Data set caching scope. Currently only a full cache (non-partial) scope is supported (basic and detailed scope will sync full dataset)"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheScope"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachescope"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheItem/cachingScope":{"role":"symbol","title":"cachingScope","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cachingScope"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheScope","preciseIdentifier":"c:@E@MPDataSetCacheScope"}],"abstract":[{"type":"text","text":"Cache scope for this cache item."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachingScope","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cachingScope"}],"url":"\/documentation\/mapsindoors\/mpdatasetcacheitem\/cachingscope"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"cachingScope"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cachingScope"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope","preciseIdentifier":"c:@E@MPDataSetCacheScope","text":"MPDataSetCacheScope"},{"kind":"identifier","text":"cachingScope"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheItem\/title","value":"MPDataSetCacheItem"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheItem\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheItem"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope\/title","value":"MPDataSetCacheScope"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheScope"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1cachingScope\/title","value":"cachingScope"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1cachingScope\/fragments","value":[{"kind":"identifier","text":"cachingScope"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}