{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachingStrategy","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcacheitem\/cachingstrategy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcacheitem\/cachingstrategy"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem(py)cachingStrategy","required":true,"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cachingStrategy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPDataSetCachingStrategy","preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingStrategy","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"cachingStrategy"}],"title":"cachingStrategy"},"abstract":[{"text":"Caching strategy for this cache item.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cachingStrategy"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy","preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingStrategy","kind":"typeIdentifier","text":"MPDataSetCachingStrategy"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem/cachingStrategy":{"kind":"symbol","title":"cachingStrategy","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachingStrategy","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cachingStrategy","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingStrategy","text":"MPDataSetCachingStrategy"}],"role":"symbol","type":"topic","abstract":[{"text":"Caching strategy for this cache item.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpdatasetcacheitem\/cachingstrategy","navigatorTitle":[{"kind":"identifier","text":"cachingStrategy"}],"required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheItem"}],"navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheItem"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem","abstract":[{"type":"text","text":"Data set cache item class."}],"url":"\/documentation\/mapsindoors\/mpdatasetcacheitem","kind":"symbol","type":"topic","role":"symbol","title":"MPDataSetCacheItem"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingStrategy":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mpdatasetcachingstrategy","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDataSetCachingStrategy","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy","abstract":[{"type":"text","text":"Data set caching strategy."}],"navigatorTitle":[{"text":"MPDataSetCachingStrategy","kind":"identifier"}],"title":"MPDataSetCachingStrategy","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"cachingStrategy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"cachingStrategy","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingStrategy","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy","text":"MPDataSetCachingStrategy"},{"kind":"text","text":" "},{"text":"cachingStrategy","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1cachingStrategy\/title","value":"cachingStrategy","op":"replace"},{"op":"replace","value":[{"text":"cachingStrategy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1cachingStrategy\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem\/title","value":"MPDataSetCacheItem"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheItem"}],"op":"replace"},{"op":"replace","value":"MPDataSetCachingStrategy","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy\/fragments","value":[{"kind":"identifier","text":"MPDataSetCachingStrategy"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}