{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessageWithId"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"messageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":" "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpMessageDetailsHandlerBlockType","preciseIdentifier":"c:MPMessageProvider.h@T@mpMessageDetailsHandlerBlockType","text":"mpMessageDetailsHandlerBlockType"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"messageId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The MapsIndoors Message ID."}]}]},{"name":"handler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The handler callback block. Contains the MPMessage object (can be nil) and an NSError object (can be nil)."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmessagesproviderprotocol\/getmessagewithid(_:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmessagesproviderprotocol\/getmessagewithid(_:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessagesProviderProtocol\/getMessageWithId(_:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Method to query a unique Message from the provider based on an id."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getMessageWithId:completionHandler:"}],"role":"symbol","title":"getMessageWithId(_:completionHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessageWithId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpMessageDetailsHandlerBlockType","preciseIdentifier":"c:MPMessageProvider.h@T@mpMessageDetailsHandlerBlockType"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:objc(pl)MPMessagesProvider(im)getMessageWithId:completionHandler:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessagesProviderProtocol"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/mpMessageDetailsHandlerBlockType":{"role":"symbol","title":"mpMessageDetailsHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpMessageDetailsHandlerBlockType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpMessageDetailsHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpMessageDetailsHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpmessagedetailshandlerblocktype"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessagesProviderProtocol/getMessageWithId(_:completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"getMessageWithId:completionHandler:"}],"role":"symbol","title":"getMessageWithId(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessageWithId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpMessageDetailsHandlerBlockType","preciseIdentifier":"c:MPMessageProvider.h@T@mpMessageDetailsHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Method to query a unique Message from the provider based on an id."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessagesProviderProtocol\/getMessageWithId(_:completionHandler:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpmessagesproviderprotocol\/getmessagewithid(_:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessagesProviderProtocol":{"role":"symbol","title":"MPMessagesProviderProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMessagesProviderProtocol"}],"abstract":[{"type":"text","text":"Messages provider protocol."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessagesProviderProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMessagesProviderProtocol"}],"url":"\/documentation\/mapsindoors\/mpmessagesproviderprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getMessageWithId:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMessageWithId:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getMessageWithId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"messageId"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(MPMessage *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)MPMessage#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"handler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpMessageDetailsHandlerBlockType\/title","value":"mpMessageDetailsHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpMessageDetailsHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpMessageDetailsHandlerBlockType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessagesProviderProtocol~1getMessageWithId(_:completionHandler:)\/title","value":"getMessageWithId:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessagesProviderProtocol~1getMessageWithId(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMessageWithId:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessagesProviderProtocol\/title","value":"MPMessagesProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessagesProviderProtocol\/fragments","value":[{"kind":"identifier","text":"MPMessagesProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}