{"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/CodingKeys\/!=(_:_:)"],"title":"Operators"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/CodingKeys"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"Equatable Implementations","modules":[{"name":"MapsIndoors"}],"role":"collectionGroup"},"kind":"article","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/CodingKeys\/Equatable-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpliveupdate\/codingkeys\/equatable-implementations"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveUpdate"}],"url":"\/documentation\/mapsindoors\/mpliveupdate","abstract":[{"text":"Model for a Live Update. Used in ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","type":"reference"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPLiveUpdate"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","title":"MPLiveUpdate","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/getLiveUpdate(forDomainType:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getLiveUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forDomainType"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"MPLiveUpdate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate"},{"text":"?","kind":"text"}],"abstract":[{"text":"Get a live update based on a known domain type.","type":"text"}],"url":"\/documentation\/mapsindoors\/mplocation\/getliveupdate(fordomaintype:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getLiveUpdateForDomainType:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","type":"topic","required":true,"title":"getLiveUpdate(forDomainType:)","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate/CodingKeys":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CodingKeys","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mapsindoors\/mpliveupdate\/codingkeys","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CodingKeys"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/CodingKeys","type":"topic","title":"MPLiveUpdate.CodingKeys","kind":"symbol"},"MapsPeopleWhite.png":{"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate/CodingKeys/!=(_:_:)":{"abstract":[],"title":"!=(_:_:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/CodingKeys\/!=(_:_:)","url":"\/documentation\/mapsindoors\/mpliveupdate\/codingkeys\/!=(_:_:)","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/title","value":"MPLiveUpdate","op":"replace"},{"op":"replace","value":[{"text":"MPLiveUpdate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/title","op":"replace","value":"getLiveUpdateForDomainType:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"getLiveUpdateForDomainType:","kind":"identifier"}],"op":"replace"}]}]}