{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"latestPositionResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult","preciseIdentifier":"c:objc(cs)MPPositionResult","text":"MPPositionResult"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppositionprovider\/latestpositionresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppositionprovider\/latestpositionresult"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProvider\/latestPositionResult","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Latest position result if any."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"latestPositionResult"}],"role":"symbol","title":"latestPositionResult","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"latestPositionResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPositionResult","preciseIdentifier":"c:objc(cs)MPPositionResult"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"c:objc(pl)MPPositionProvider(py)latestPositionResult","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProvider":{"role":"symbol","title":"MPPositionProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProvider"}],"abstract":[{"type":"text","text":"Protocol specifying how an indoor positioning provider should be implemented if the users location is to be exposed to MPMapControl"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPositionProvider"}],"url":"\/documentation\/mapsindoors\/mppositionprovider"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProvider/latestPositionResult":{"navigatorTitle":[{"kind":"identifier","text":"latestPositionResult"}],"role":"symbol","title":"latestPositionResult","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"latestPositionResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPositionResult","preciseIdentifier":"c:objc(cs)MPPositionResult"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Latest position result if any."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProvider\/latestPositionResult","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mppositionprovider\/latestpositionresult"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult":{"role":"symbol","title":"MPPositionResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionResult"}],"abstract":[{"type":"text","text":"Position result model"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPositionResult"}],"url":"\/documentation\/mapsindoors\/mppositionresult"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"latestPositionResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"latestPositionResult"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult","preciseIdentifier":"c:objc(cs)MPPositionResult","text":"MPPositionResult"},{"kind":"text","text":" *"},{"kind":"identifier","text":"latestPositionResult"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProvider\/title","value":"MPPositionProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProvider\/fragments","value":[{"kind":"identifier","text":"MPPositionProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProvider~1latestPositionResult\/title","value":"latestPositionResult"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProvider~1latestPositionResult\/fragments","value":[{"kind":"identifier","text":"latestPositionResult"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult\/title","value":"MPPositionResult"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult\/fragments","value":[{"kind":"identifier","text":"MPPositionResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}