{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"providerType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType","preciseIdentifier":"c:@E@MPPositionProviderType","text":"MPPositionProviderType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppositionprovider\/providertype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppositionprovider\/providertype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProvider\/providerType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Provider type stored as an integer. Currently not used by MPMapControl."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"providerType"}],"role":"symbol","title":"providerType","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"providerType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPositionProviderType","preciseIdentifier":"c:@E@MPPositionProviderType"}],"symbolKind":"property","externalID":"c:objc(pl)MPPositionProvider(py)providerType","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProvider/providerType":{"navigatorTitle":[{"kind":"identifier","text":"providerType"}],"role":"symbol","title":"providerType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"providerType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPositionProviderType","preciseIdentifier":"c:@E@MPPositionProviderType"}],"abstract":[{"type":"text","text":"Provider type stored as an integer. Currently not used by MPMapControl."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProvider\/providerType","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mppositionprovider\/providertype"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProvider":{"role":"symbol","title":"MPPositionProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProvider"}],"abstract":[{"type":"text","text":"Protocol specifying how an indoor positioning provider should be implemented if the users location is to be exposed to MPMapControl"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPositionProvider"}],"url":"\/documentation\/mapsindoors\/mppositionprovider"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionProviderType":{"role":"symbol","title":"MPPositionProviderType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProviderType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPositionProviderType"}],"url":"\/documentation\/mapsindoors\/mppositionprovidertype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"providerType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"providerType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionProviderType","preciseIdentifier":"c:@E@MPPositionProviderType","text":"MPPositionProviderType"},{"kind":"identifier","text":"providerType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProvider~1providerType\/title","value":"providerType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProvider~1providerType\/fragments","value":[{"kind":"identifier","text":"providerType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProvider\/title","value":"MPPositionProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProvider\/fragments","value":[{"kind":"identifier","text":"MPPositionProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderType\/title","value":"MPPositionProviderType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionProviderType\/fragments","value":[{"kind":"identifier","text":"MPPositionProviderType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}