{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"building"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationbasetype\/building"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationbasetype\/building"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationBaseType\/building","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"building"}],"title":"MPLocationBaseType.building","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MPLocationBaseType@MPLocationBaseTypeBuilding","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLocationBaseTypeBuilding"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationBaseType"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationBaseType":{"role":"symbol","title":"MPLocationBaseType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationBaseType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationBaseType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationBaseType"}],"url":"\/documentation\/mapsindoors\/mplocationbasetype"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationBaseType/building":{"role":"symbol","title":"MPLocationBaseType.building","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"building"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationBaseType\/building","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationBaseTypeBuilding"}],"url":"\/documentation\/mapsindoors\/mplocationbasetype\/building"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MPLocationBaseTypeBuilding"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLocationBaseTypeBuilding"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MPLocationBaseTypeBuilding"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationBaseType\/title","value":"MPLocationBaseType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationBaseType\/fragments","value":[{"kind":"identifier","text":"MPLocationBaseType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationBaseType~1building\/title","value":"MPLocationBaseTypeBuilding"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationBaseType~1building\/fragments","value":[{"kind":"identifier","text":"MPLocationBaseTypeBuilding"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}