{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"northEast"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLatLng","preciseIdentifier":"c:objc(cs)MPLatLng","text":"MPLatLng"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplatlngbounds\/northeast"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplatlngbounds\/northeast"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLatLngBounds\/northEast","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"northEast"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLatLng","preciseIdentifier":"c:objc(cs)MPLatLng"},{"kind":"text","text":"?"}],"title":"northEast","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPLatLngBounds(py)northEast","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"northEast"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLatLngBounds"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLatLngBounds":{"role":"symbol","title":"MPLatLngBounds","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLatLngBounds"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLatLngBounds","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLatLngBounds"}],"url":"\/documentation\/mapsindoors\/mplatlngbounds"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLatLng":{"role":"symbol","title":"MPLatLng","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLatLng"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLatLng","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLatLng"}],"url":"\/documentation\/mapsindoors\/mplatlng"},"doc://MapsIndoors/documentation/MapsIndoors/MPLatLngBounds/northEast":{"role":"symbol","title":"northEast","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"northEast"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLatLng","preciseIdentifier":"c:objc(cs)MPLatLng"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLatLngBounds\/northEast","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"northEast"}],"url":"\/documentation\/mapsindoors\/mplatlngbounds\/northeast"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"northEast"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"northEast"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLatLng","preciseIdentifier":"c:objc(cs)MPLatLng","text":"MPLatLng"},{"kind":"text","text":" *"},{"kind":"identifier","text":"northEast"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLatLngBounds\/title","value":"MPLatLngBounds"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLatLngBounds\/fragments","value":[{"kind":"identifier","text":"MPLatLngBounds"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLatLng\/title","value":"MPLatLng"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLatLng\/fragments","value":[{"kind":"identifier","text":"MPLatLng"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLatLngBounds~1northEast\/title","value":"northEast"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLatLngBounds~1northEast\/fragments","value":[{"kind":"identifier","text":"northEast"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}