{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate\/addCategory(categoryKey:)"},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationupdate\/addcategory(categorykey:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationupdate\/addcategory(categorykey:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate"]]},"kind":"symbol","abstract":[{"text":"Add category key. Possible categories can be reviewed in MapsIndoors CMS or programmatically using the ","type":"text"},{"code":"MPCategoriesProvider","type":"codeVoice"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(addCategory:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addCategory"},{"text":"(","kind":"text"},{"text":"categoryKey","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"categoryKey","content":[{"inlineContent":[{"type":"text","text":"The category key"}],"type":"paragraph"}]}],"kind":"parameters"}],"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPLocationUpdate(im)addCategory:","title":"addCategory(categoryKey:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addCategory","kind":"identifier"},{"kind":"text","text":"("},{"text":"categoryKey","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","required":true,"symbolKind":"method","navigatorTitle":[{"text":"addCategory:","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationUpdate/addCategory(categoryKey:)":{"required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate\/addCategory(categoryKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCategory"},{"kind":"text","text":"("},{"text":"categoryKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"addCategory:"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/addcategory(categorykey:)","abstract":[{"text":"Add category key. Possible categories can be reviewed in MapsIndoors CMS or programmatically using the ","type":"text"},{"type":"codeVoice","code":"MPCategoriesProvider"}],"title":"addCategory(categoryKey:)","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationUpdate":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationUpdate"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate","title":"MPLocationUpdate","url":"\/documentation\/mapsindoors\/mplocationupdate","type":"topic","navigatorTitle":[{"text":"MPLocationUpdate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"addCategory:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addCategory:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"addCategory:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"categoryKey","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdate~1addCategory(categoryKey:)\/title","value":"addCategory:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addCategory:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdate~1addCategory(categoryKey:)\/fragments","op":"replace"},{"value":"MPLocationUpdate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdate\/fragments","value":[{"text":"MPLocationUpdate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}