{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mplocationupdate\/updatewithlocation(location:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mplocationupdate\/updatewithlocation(location:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate\/updateWithLocation(location:)"},"abstract":[{"type":"text","text":"Initialiser that creates a MPLocationUpdate instance based on an existing location."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"updateWithLocationWithLocation:","kind":"identifier"}],"title":"updateWithLocation(location:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateWithLocation"},{"kind":"text","text":"("},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPLocation","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationUpdate","kind":"typeIdentifier","text":"MPLocationUpdate"}],"required":true,"roleHeading":"Type Method","symbolKind":"method","externalID":"c:@M@MapsIndoors@objc(pl)MPLocationUpdate(cm)updateWithLocationWithLocation:"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateWithLocation"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"location"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","text":"MPLocation"},{"kind":"text","text":") -> "},{"text":"MPLocationUpdate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationUpdate"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"location","content":[{"type":"paragraph","inlineContent":[{"text":"The existing location.","type":"text"}]}]}]},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The existing location."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate"]]},"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation":{"navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLocation","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mplocation","title":"MPLocation","abstract":[{"type":"text","text":"This holds the data for a single location and a marker to display the data on a map."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationUpdate/updateWithLocation(location:)":{"kind":"symbol","title":"updateWithLocation(location:)","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate\/updateWithLocation(location:)","required":true,"url":"\/documentation\/mapsindoors\/mplocationupdate\/updatewithlocation(location:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateWithLocation","kind":"identifier"},{"kind":"text","text":"("},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","text":"MPLocation","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"MPLocationUpdate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationUpdate"}],"abstract":[{"type":"text","text":"Initialiser that creates a MPLocationUpdate instance based on an existing location."}],"navigatorTitle":[{"text":"updateWithLocationWithLocation:","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationUpdate":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationUpdate"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate","title":"MPLocationUpdate","url":"\/documentation\/mapsindoors\/mplocationupdate","type":"topic","navigatorTitle":[{"text":"MPLocationUpdate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","value":"updateWithLocationWithLocation:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"updateWithLocationWithLocation:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"id<MPLocationUpdate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPLocationUpdate"},{"kind":"text","text":" *) "},{"text":"updateWithLocationWithLocation:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<MPLocation>","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPLocation","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"location"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/title","value":"MPLocation","op":"replace"},{"value":[{"text":"MPLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/fragments"},{"value":"updateWithLocationWithLocation:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdate~1updateWithLocation(location:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"updateWithLocationWithLocation:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdate~1updateWithLocation(location:)\/fragments"},{"value":"MPLocationUpdate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdate\/title"},{"value":[{"kind":"identifier","text":"MPLocationUpdate"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}