{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate\/updateWithId(locationId:fromSource:)"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate"]]},"abstract":[{"type":"text","text":"Initialiser that creates a MPLocationUpdate instance based on an id and a location source."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"updateWithId(locationId:fromSource:)","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"updateWithIdWithLocationId:fromSource:"}],"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPLocationUpdate(cm)updateWithIdWithLocationId:fromSource:","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateWithId","kind":"identifier"},{"kind":"text","text":"("},{"text":"locationId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromSource"},{"kind":"text","text":": "},{"text":"MPLocationSource","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationSource","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"MPLocationUpdate","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationUpdate"}],"required":true,"modules":[{"name":"MapsIndoors"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateWithId"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"locationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"fromSource","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"locationSource"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationSource","kind":"typeIdentifier","text":"MPLocationSource"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationUpdate","text":"MPLocationUpdate"}],"languages":["swift"]}]},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"The Updater object.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"locationId: This id is expected to be unique for a given location source, but not necessarily unique across multiple location sources.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"locationSource: The location source that is going to maintain this location."}],"type":"paragraph"}]}]}],"kind":"content"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mplocationupdate\/updatewithid(locationid:fromsource:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mplocationupdate\/updatewithid(locationid:fromsource:)"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationUpdate":{"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate","type":"topic","url":"\/documentation\/mapsindoors\/mplocationupdate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationUpdate"}],"kind":"symbol","title":"MPLocationUpdate","role":"symbol","navigatorTitle":[{"text":"MPLocationUpdate","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSource":{"abstract":[{"type":"text","text":"Location source protocol."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPLocationSource"}],"title":"MPLocationSource","type":"topic","url":"\/documentation\/mapsindoors\/mplocationsource","navigatorTitle":[{"kind":"identifier","text":"MPLocationSource"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationUpdate/updateWithId(locationId:fromSource:)":{"abstract":[{"text":"Initialiser that creates a MPLocationUpdate instance based on an id and a location source.","type":"text"}],"kind":"symbol","title":"updateWithId(locationId:fromSource:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate\/updateWithId(locationId:fromSource:)","navigatorTitle":[{"text":"updateWithIdWithLocationId:fromSource:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/updatewithid(locationid:fromsource:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateWithId","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"locationId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"fromSource","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPLocationSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationSource"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationUpdate","text":"MPLocationUpdate","kind":"typeIdentifier"}],"type":"topic","required":true},"MapsPeopleWhite.png":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"identifier":"MapsPeopleWhite.png"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"updateWithIdWithLocationId:fromSource:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"updateWithIdWithLocationId:fromSource:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"id<MPLocationUpdate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPLocationUpdate"},{"text":" *) ","kind":"text"},{"text":"updateWithIdWithLocationId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"locationId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fromSource:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<MPLocationSource>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPLocationSource"},{"kind":"text","text":" *) "},{"text":"locationSource","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdate\/title","value":"MPLocationUpdate"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdate\/fragments","value":[{"kind":"identifier","text":"MPLocationUpdate"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource\/title","value":"MPLocationSource","op":"replace"},{"value":[{"text":"MPLocationSource","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource\/fragments","op":"replace"},{"value":"updateWithIdWithLocationId:fromSource:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdate~1updateWithId(locationId:fromSource:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdate~1updateWithId(locationId:fromSource:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"updateWithIdWithLocationId:fromSource:","kind":"identifier"}],"op":"replace"}]}]}