{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transit"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mptravelmode\/transit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mptravelmode\/transit"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/transit","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transit"}],"title":"MPTravelMode.transit","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MPTravelMode@MPTravelModeTransit","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPTravelModeTransit"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPTravelMode/transit":{"role":"symbol","title":"MPTravelMode.transit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transit"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode\/transit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPTravelModeTransit"}],"url":"\/documentation\/mapsindoors\/mptravelmode\/transit"},"doc://MapsIndoors/documentation/MapsIndoors/MPTravelMode":{"role":"symbol","title":"MPTravelMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPTravelMode"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPTravelMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPTravelMode"}],"url":"\/documentation\/mapsindoors\/mptravelmode"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MPTravelModeTransit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPTravelModeTransit"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MPTravelModeTransit"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTravelMode~1transit\/title","value":"MPTravelModeTransit"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTravelMode~1transit\/fragments","value":[{"kind":"identifier","text":"MPTravelModeTransit"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTravelMode\/title","value":"MPTravelMode"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPTravelMode\/fragments","value":[{"kind":"identifier","text":"MPTravelMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}