{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithLiveUpdate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MPLiveUpdate","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"withLiveUpdate","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"text","text":"- "},{"text":"initWithLiveUpdate:","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPAvailabilityLiveUpdate(im)initWithLiveUpdate:","roleHeading":"Instance Method","modules":[{"name":"MapsIndoors"}],"role":"symbol","navigatorTitle":[{"text":"initWithLiveUpdate:","kind":"identifier"}],"symbolKind":"method","title":"initWithLiveUpdate:"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAvailabilityLiveUpdate"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAvailabilityLiveUpdate\/initWithLiveUpdate:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpavailabilityliveupdate\/initwithliveupdate:"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAvailabilityLiveUpdate/initWithLiveUpdate:":{"navigatorTitle":[{"text":"initWithLiveUpdate:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpavailabilityliveupdate\/initwithliveupdate:","fragments":[{"kind":"text","text":"- "},{"text":"initWithLiveUpdate:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAvailabilityLiveUpdate\/initWithLiveUpdate:","type":"topic","role":"symbol","abstract":[],"title":"initWithLiveUpdate:"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAvailabilityLiveUpdate":{"navigatorTitle":[{"text":"MPAvailabilityLiveUpdate","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPAvailabilityLiveUpdate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAvailabilityLiveUpdate","title":"MPAvailabilityLiveUpdate","abstract":[{"type":"text","text":"Model for live availability information for a given Location."}],"type":"topic","url":"\/documentation\/mapsindoors\/mpavailabilityliveupdate"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate":{"url":"\/documentation\/mapsindoors\/mpliveupdate","title":"MPLiveUpdate","navigatorTitle":[{"kind":"identifier","text":"MPLiveUpdate"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","abstract":[{"type":"text","text":"Model for a Live Update. Used in "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","isActive":true,"type":"reference"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLiveUpdate","kind":"identifier"}]},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"type":"image","alt":null,"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/getLiveUpdate(forDomainType:)":{"title":"getLiveUpdate(forDomainType:)","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"getLiveUpdateForDomainType:"}],"type":"topic","abstract":[{"text":"Get a live update based on a known domain type.","type":"text"}],"url":"\/documentation\/mapsindoors\/mplocation\/getliveupdate(fordomaintype:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getLiveUpdate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forDomainType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate","kind":"typeIdentifier","text":"MPLiveUpdate"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAvailabilityLiveUpdate\/title","value":"MPAvailabilityLiveUpdate","op":"replace"},{"op":"replace","value":[{"text":"MPAvailabilityLiveUpdate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAvailabilityLiveUpdate\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/title","value":"MPLiveUpdate","op":"replace"},{"value":[{"text":"MPLiveUpdate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/title","op":"replace","value":"getLiveUpdateForDomainType:"},{"value":[{"text":"- ","kind":"text"},{"text":"getLiveUpdateForDomainType:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}