{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingAuthConfig"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingAuthConfig\/init(accessToken:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessToken"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The access token to use when performing bookings."}]}],"name":"accessToken"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpbookingauthconfig\/init(accesstoken:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpbookingauthconfig\/init(accesstoken:)"]}],"abstract":[{"type":"text","text":"Constructor that takes an access token."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@MapsIndoors@objc(cs)MPBookingAuthConfig(im)initWithAccessToken:","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"accessToken","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(accessToken:)","navigatorTitle":[{"kind":"identifier","text":"initWithAccessToken:"}]},"references":{"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingAuthConfig/init(accessToken:)":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Constructor that takes an access token."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpbookingauthconfig\/init(accesstoken:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accessToken"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"title":"init(accessToken:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingAuthConfig\/init(accessToken:)","navigatorTitle":[{"kind":"identifier","text":"initWithAccessToken:"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingAuthConfig":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Booking authentication configuration model. This may be used if the "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService","isActive":true,"type":"reference"},{"type":"text","text":" should book on behalf of an authenticated user."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpbookingauthconfig","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPBookingAuthConfig","kind":"identifier"}],"title":"MPBookingAuthConfig","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingAuthConfig","navigatorTitle":[{"kind":"identifier","text":"MPBookingAuthConfig"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService":{"type":"topic","role":"symbol","title":"MPBookingService","url":"\/documentation\/mapsindoors\/mpbookingservice","abstract":[{"type":"text","text":"MPBookingService allows for access to the MapsIndoors booking service."},{"type":"text","text":" "},{"type":"text","text":"The booking service is a special integration that has to be enabled in the MapsIndoors cloud systems."}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBookingService"}],"navigatorTitle":[{"text":"MPBookingService","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithAccessToken:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithAccessToken:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithAccessToken:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessToken","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithAccessToken:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingAuthConfig~1init(accessToken:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithAccessToken:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingAuthConfig~1init(accessToken:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingAuthConfig\/title","value":"MPBookingAuthConfig"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingAuthConfig\/fragments","op":"replace","value":[{"text":"MPBookingAuthConfig","kind":"identifier"}]},{"value":"MPBookingService","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService\/title","op":"replace"},{"op":"replace","value":[{"text":"MPBookingService","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService\/fragments"}]}]}