{"metadata":{"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@MapsIndoors@objc(cs)MPGeometry(py)bbox","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bbox","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":"]?"}],"modules":[{"name":"MapsIndoors"}],"title":"bbox","navigatorTitle":[{"text":"bbox","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometry"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bbox"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":"]? { get }","kind":"text"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"If present, it contains two coordinates: [longitude1, latitude1, longitude2, latitude2]."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"Optional bounding box for the geometry object."}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpgeometry\/bbox"]},{"paths":["\/documentation\/mapsindoors\/mpgeometry\/bbox"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometry\/bbox"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometry":{"kind":"symbol","title":"MPGeometry","url":"\/documentation\/mapsindoors\/mpgeometry","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPGeometry","kind":"identifier"}],"navigatorTitle":[{"text":"MPGeometry","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometry"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometry/bbox":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bbox"}],"url":"\/documentation\/mapsindoors\/mpgeometry\/bbox","kind":"symbol","type":"topic","title":"bbox","abstract":[{"type":"text","text":"Optional bounding box for the geometry object."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bbox"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometry\/bbox"},"MapsPeopleWhite.png":{"type":"image","alt":null,"identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"bbox","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"bbox"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSNumber *>"},{"text":" * ","kind":"text"},{"text":"bbox","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometry\/title","value":"MPGeometry","op":"replace"},{"value":[{"text":"MPGeometry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometry\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometry~1bbox\/title","value":"bbox"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometry~1bbox\/fragments","value":[{"text":"bbox","kind":"identifier"}]}]}]}