{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpgeometrycontainmentmetadata\/iscontainedinhole"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpgeometrycontainmentmetadata\/iscontainedinhole"]}],"sections":[],"abstract":[{"type":"text","text":"Inside a polygon hole."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isContainedInHole"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata\/isContainedInHole","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"MapsIndoors"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isContainedInHole","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPGeometryContainmentMetadata(py)isContainedInHole","roleHeading":"Instance Property","navigatorTitle":[{"text":"isContainedInHole","kind":"identifier"}],"title":"isContainedInHole","symbolKind":"property","role":"symbol"},"references":{"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryContainmentMetadata":{"type":"topic","role":"symbol","url":"\/documentation\/mapsindoors\/mpgeometrycontainmentmetadata","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPGeometryContainmentMetadata","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata","abstract":[],"navigatorTitle":[{"text":"MPGeometryContainmentMetadata","kind":"identifier"}],"title":"MPGeometryContainmentMetadata"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryContainmentMetadata/isContainedInHole":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isContainedInHole","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"isContainedInHole","kind":"identifier"}],"abstract":[{"type":"text","text":"Inside a polygon hole."}],"kind":"symbol","title":"isContainedInHole","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata\/isContainedInHole","url":"\/documentation\/mapsindoors\/mpgeometrycontainmentmetadata\/iscontainedinhole","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"isContainedInHole","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"isContainedInHole"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"text":"isContainedInHole","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryContainmentMetadata\/title","value":"MPGeometryContainmentMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryContainmentMetadata\/fragments","value":[{"kind":"identifier","text":"MPGeometryContainmentMetadata"}]},{"op":"replace","value":"isContainedInHole","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryContainmentMetadata~1isContainedInHole\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryContainmentMetadata~1isContainedInHole\/fragments","value":[{"text":"isContainedInHole","kind":"identifier"}]}]}]}