{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"new"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withGeoSpatialObject"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gso"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpgeometrycontainmentmetadata\/new(withgeospatialobject:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpgeometrycontainmentmetadata\/new(withgeospatialobject:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata\/new(withGeoSpatialObject:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"new"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withGeoSpatialObject"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"!"}],"title":"new(withGeoSpatialObject:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPGeometryContainmentMetadata(cm)newWithGeoSpatialObject:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"newWithGeoSpatialObject:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPGeometryContainmentMetadata":{"role":"symbol","title":"MPGeometryContainmentMetadata","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeometryContainmentMetadata"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPGeometryContainmentMetadata"}],"url":"\/documentation\/mapsindoors\/mpgeometrycontainmentmetadata"},"doc://MapsIndoors/documentation/MapsIndoors/MPGeometryContainmentMetadata/new(withGeoSpatialObject:)":{"role":"symbol","title":"new(withGeoSpatialObject:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"new"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withGeoSpatialObject"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata\/new(withGeoSpatialObject:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"newWithGeoSpatialObject:"}],"url":"\/documentation\/mapsindoors\/mpgeometrycontainmentmetadata\/new(withgeospatialobject:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"newWithGeoSpatialObject:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"newWithGeoSpatialObject:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"newWithGeoSpatialObject:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"gso"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryContainmentMetadata\/title","value":"MPGeometryContainmentMetadata"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryContainmentMetadata\/fragments","value":[{"kind":"identifier","text":"MPGeometryContainmentMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryContainmentMetadata~1new(withGeoSpatialObject:)\/title","value":"newWithGeoSpatialObject:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryContainmentMetadata~1new(withGeoSpatialObject:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"newWithGeoSpatialObject:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}