{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingsQuery"]]},"metadata":{"modules":[{"name":"MapsIndoors"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"endTime","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"?"}],"title":"endTime","navigatorTitle":[{"kind":"identifier","text":"endTime"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPBookingsQuery(py)endTime"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endTime","kind":"identifier"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"The date and time the Booking will end,","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpbookingsquery\/endtime"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpbookingsquery\/endtime"]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingsQuery\/endTime","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService/bookingsUsing(query:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bookingsUsing"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBookingsQuery","kind":"typeIdentifier","text":"MPBookingsQuery"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking","text":"MPBooking"},{"kind":"text","text":"]?"}],"kind":"symbol","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/bookingsUsing(query:)","abstract":[{"type":"text","text":"Get existing booking according the the given "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingsQuery"}],"title":"bookingsUsing(query:)","navigatorTitle":[{"kind":"identifier","text":"bookingsUsingQuery:completionHandler:"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpbookingservice\/bookingsusing(query:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingsQuery":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPBookingsQuery","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingsQuery","abstract":[{"text":"Query object to be used with ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/bookingsUsing(query:)"},{"type":"text","text":" "},{"text":"Queries can be either for a location or a user (organizerId), and may optionally be limited to a given timespan.","type":"text"}],"title":"MPBookingsQuery","navigatorTitle":[{"text":"MPBookingsQuery","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpbookingsquery","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingsQuery/endTime":{"navigatorTitle":[{"kind":"identifier","text":"endTime"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"endTime"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[{"text":"The date and time the Booking will end,","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpbookingsquery\/endtime","title":"endTime","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingsQuery\/endTime"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"endTime","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"endTime","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSDate","kind":"typeIdentifier","text":"NSDate"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"endTime"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"bookingsUsingQuery:completionHandler:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1bookingsUsing(query:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bookingsUsingQuery:completionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1bookingsUsing(query:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingsQuery\/title","value":"MPBookingsQuery"},{"op":"replace","value":[{"text":"MPBookingsQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingsQuery\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingsQuery~1endTime\/title","value":"endTime","op":"replace"},{"value":[{"text":"endTime","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingsQuery~1endTime\/fragments"}]}]}