{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingsQuery"]]},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"symbolKind":"method","externalID":"c:@M@MapsIndoors@objc(cs)MPBookingsQuery(im)init","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/mapsindoors\/mpbookingsquery\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingsQuery\/init"},"kind":"symbol","references":{"MapsPeopleWhite.png":{"alt":null,"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService/bookingsUsing(query:)":{"navigatorTitle":[{"text":"bookingsUsingQuery:completionHandler:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpbookingservice\/bookingsusing(query:)","required":true,"role":"symbol","title":"bookingsUsing(query:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bookingsUsing"},{"kind":"text","text":"("},{"text":"query","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPBookingsQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBookingsQuery"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> ["},{"text":"MPBooking","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking"},{"text":"]?","kind":"text"}],"type":"topic","abstract":[{"text":"Get existing booking according the the given ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingsQuery","type":"reference","isActive":true}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/bookingsUsing(query:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingsQuery":{"navigatorTitle":[{"kind":"identifier","text":"MPBookingsQuery"}],"url":"\/documentation\/mapsindoors\/mpbookingsquery","role":"symbol","title":"MPBookingsQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPBookingsQuery","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Query object to be used with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/bookingsUsing(query:)"},{"text":" ","type":"text"},{"type":"text","text":"Queries can be either for a location or a user (organizerId), and may optionally be limited to a given timespan."}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingsQuery"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingsQuery/init":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingsQuery\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/mapsindoors\/mpbookingsquery\/init","title":"init","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1bookingsUsing(query:)\/title","value":"bookingsUsingQuery:completionHandler:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"bookingsUsingQuery:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1bookingsUsing(query:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingsQuery\/title","value":"MPBookingsQuery"},{"value":[{"text":"MPBookingsQuery","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingsQuery\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}