{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpMapsIndoorsSourceId"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapsindoorslocationsource\/mpmapsindoorssourceid()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmapsindoorslocationsource\/mpmapsindoorssourceid()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapsIndoorsLocationSource\/mpMapsIndoorsSourceId()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpMapsIndoorsSourceId"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"mpMapsIndoorsSourceId()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPMapsIndoorsLocationSource(cm)mpMapsIndoorsSourceId","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"mpMapsIndoorsSourceId"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapsIndoorsLocationSource"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapsIndoorsLocationSource":{"role":"symbol","title":"MPMapsIndoorsLocationSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapsIndoorsLocationSource"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapsIndoorsLocationSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMapsIndoorsLocationSource"}],"url":"\/documentation\/mapsindoors\/mpmapsindoorslocationsource"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapsIndoorsLocationSource/mpMapsIndoorsSourceId()":{"role":"symbol","title":"mpMapsIndoorsSourceId()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpMapsIndoorsSourceId"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapsIndoorsLocationSource\/mpMapsIndoorsSourceId()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpMapsIndoorsSourceId"}],"url":"\/documentation\/mapsindoors\/mpmapsindoorslocationsource\/mpmapsindoorssourceid()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"mpMapsIndoorsSourceId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"mpMapsIndoorsSourceId"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"mpMapsIndoorsSourceId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapsIndoorsLocationSource\/title","value":"MPMapsIndoorsLocationSource"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapsIndoorsLocationSource\/fragments","value":[{"kind":"identifier","text":"MPMapsIndoorsLocationSource"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapsIndoorsLocationSource~1mpMapsIndoorsSourceId()\/title","value":"mpMapsIndoorsSourceId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapsIndoorsLocationSource~1mpMapsIndoorsSourceId()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"mpMapsIndoorsSourceId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}