{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAppData"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpappdataprovider\/getappdata()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpappdataprovider\/getappdata()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider\/getAppData()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get app metadata. Assign a delegate object to this instance in order to handle the data fetch."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAppData"},{"kind":"text","text":"()"}],"title":"getAppData()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPAppDataProvider(im)getAppData","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getAppData"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPAppDataProvider/getAppData()":{"role":"symbol","title":"getAppData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAppData"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Get app metadata. Assign a delegate object to this instance in order to handle the data fetch."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider\/getAppData()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAppData"}],"url":"\/documentation\/mapsindoors\/mpappdataprovider\/getappdata()"},"doc://MapsIndoors/documentation/MapsIndoors/MPAppDataProvider":{"role":"symbol","title":"MPAppDataProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPAppDataProvider"}],"abstract":[{"type":"text","text":"The app data provider acts as a service for the metadata (MPAppData) of a MapsIndoors app solution."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPAppDataProvider"}],"url":"\/documentation\/mapsindoors\/mpappdataprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getAppData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAppData"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getAppData"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider~1getAppData()\/title","value":"getAppData"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider~1getAppData()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAppData"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider\/title","value":"MPAppDataProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider\/fragments","value":[{"kind":"identifier","text":"MPAppDataProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}