{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAppData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":" "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpAppDataHandlerBlockType","preciseIdentifier":"c:MPAppDataProvider.h@T@mpAppDataHandlerBlockType","text":"mpAppDataHandlerBlockType"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"handler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Data fetch and error callback handler block"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpappdataprovider\/getappdata(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpappdataprovider\/getappdata(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider\/getAppData(completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get app metadata and handle the data with a callback block"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAppData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpAppDataHandlerBlockType","preciseIdentifier":"c:MPAppDataProvider.h@T@mpAppDataHandlerBlockType"},{"kind":"text","text":"?)"}],"title":"getAppData(completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPAppDataProvider(im)getAppDataWithCompletion:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getAppDataWithCompletion:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPAppDataProvider/getAppData(completion:)":{"role":"symbol","title":"getAppData(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAppData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpAppDataHandlerBlockType","preciseIdentifier":"c:MPAppDataProvider.h@T@mpAppDataHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get app metadata and handle the data with a callback block"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider\/getAppData(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAppDataWithCompletion:"}],"url":"\/documentation\/mapsindoors\/mpappdataprovider\/getappdata(completion:)"},"doc://MapsIndoors/documentation/MapsIndoors/mpAppDataHandlerBlockType":{"role":"symbol","title":"mpAppDataHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpAppDataHandlerBlockType"}],"abstract":[{"type":"text","text":"Callback block for getting app data or handling error in doing so."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpAppDataHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpAppDataHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpappdatahandlerblocktype"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPAppDataProvider":{"role":"symbol","title":"MPAppDataProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPAppDataProvider"}],"abstract":[{"type":"text","text":"The app data provider acts as a service for the metadata (MPAppData) of a MapsIndoors app solution."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAppDataProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPAppDataProvider"}],"url":"\/documentation\/mapsindoors\/mpappdataprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getAppDataWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAppDataWithCompletion:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getAppDataWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(MPAppData *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)MPAppData#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"handler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider~1getAppData(completion:)\/title","value":"getAppDataWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider~1getAppData(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAppDataWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpAppDataHandlerBlockType\/title","value":"mpAppDataHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpAppDataHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpAppDataHandlerBlockType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider\/title","value":"MPAppDataProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAppDataProvider\/fragments","value":[{"kind":"identifier","text":"MPAppDataProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}