{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconAndName"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfoscope\/iconandname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfoscope\/iconandname"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/iconAndName","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Shows both icon and name of POI of defined type along the rendered route"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconAndName"}],"title":"MPDirectionsRendererContextualInfoScope.iconAndName","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MPDirectionsRendererContextualInfoScope@MPDirectionsRendererContextualInfoScopeIconAndName","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScopeIconAndName"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRendererContextualInfoScope":{"role":"symbol","title":"MPDirectionsRendererContextualInfoScope","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScope"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScope"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfoscope"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRendererContextualInfoScope/iconAndName":{"role":"symbol","title":"MPDirectionsRendererContextualInfoScope.iconAndName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconAndName"}],"abstract":[{"type":"text","text":"Shows both icon and name of POI of defined type along the rendered route"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/iconAndName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScopeIconAndName"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfoscope\/iconandname"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MPDirectionsRendererContextualInfoScopeIconAndName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScopeIconAndName"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScopeIconAndName"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoScope\/title","value":"MPDirectionsRendererContextualInfoScope"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoScope\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScope"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoScope~1iconAndName\/title","value":"MPDirectionsRendererContextualInfoScopeIconAndName"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoScope~1iconAndName\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScopeIconAndName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}