{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteResult\/routes","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"MapsIndoors"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"routes"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRoute","kind":"typeIdentifier","text":"MPRoute"},{"text":"]?","kind":"text"}],"title":"routes","required":true,"navigatorTitle":[{"kind":"identifier","text":"routes"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPRouteResult(py)routes","symbolKind":"property"},"abstract":[{"type":"text","text":"Routes in the result."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteResult"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mprouteresult\/routes"]},{"paths":["\/documentation\/mapsindoors\/mprouteresult\/routes"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routes"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRoute","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","text":"MPRoute"},{"kind":"text","text":"]? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPRoute"}],"type":"topic","url":"\/documentation\/mapsindoors\/mproute","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","abstract":[{"text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","isActive":true,"type":"reference"},{"type":"text","text":"."}],"title":"MPRoute","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPRoute","kind":"identifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsService":{"kind":"symbol","navigatorTitle":[{"text":"MPDirectionsService","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdirectionsservice","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","abstract":[],"title":"MPDirectionsService","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDirectionsService","kind":"identifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteResult/routes":{"required":true,"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteResult\/routes","role":"symbol","url":"\/documentation\/mapsindoors\/mprouteresult\/routes","navigatorTitle":[{"text":"routes","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"routes","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MPRoute","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRoute"},{"text":"]?","kind":"text"}],"type":"topic","title":"routes","abstract":[{"type":"text","text":"Routes in the result."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteResult":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteResult","navigatorTitle":[{"kind":"identifier","text":"MPRouteResult"}],"title":"MPRouteResult","role":"symbol","abstract":[{"type":"text","text":"Route result model."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mprouteresult","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPRouteResult","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"routes","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"routes","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<MPRoute>>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"routes"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/title","value":"MPRoute"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/fragments","op":"replace","value":[{"text":"MPRoute","kind":"identifier"}]},{"value":"MPDirectionsService","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/title"},{"value":[{"text":"MPDirectionsService","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/fragments"},{"op":"replace","value":"routes","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteResult~1routes\/title"},{"value":[{"kind":"identifier","text":"routes"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteResult~1routes\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteResult\/title","value":"MPRouteResult"},{"value":[{"text":"MPRouteResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteResult\/fragments","op":"replace"}]}]}