{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mail"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/customfonticon\/mail"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/customfonticon\/mail"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/mail","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mail"}],"title":"CustomFontIcon.mail","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@CustomFontIcon@mail","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"mail"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/mail":{"role":"symbol","title":"CustomFontIcon.mail","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mail"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/mail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mail"}],"url":"\/documentation\/mapsindoors\/customfonticon\/mail"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon":{"role":"symbol","title":"CustomFontIcon","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomFontIcon"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomFontIcon"}],"url":"\/documentation\/mapsindoors\/customfonticon"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"mail"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mail"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"mail"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1mail\/title","value":"mail"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1mail\/fragments","value":[{"kind":"identifier","text":"mail"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon\/title","value":"CustomFontIcon"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon\/fragments","value":[{"kind":"identifier","text":"CustomFontIcon"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}