{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playO2"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/customfonticon\/playo2"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/customfonticon\/playo2"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/playO2","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playO2"}],"title":"CustomFontIcon.playO2","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@CustomFontIcon@playO2","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"playO2"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/playO2":{"role":"symbol","title":"CustomFontIcon.playO2","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playO2"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/playO2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playO2"}],"url":"\/documentation\/mapsindoors\/customfonticon\/playo2"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon":{"role":"symbol","title":"CustomFontIcon","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomFontIcon"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomFontIcon"}],"url":"\/documentation\/mapsindoors\/customfonticon"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"playO2"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"playO2"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"playO2"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1playO2\/title","value":"playO2"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1playO2\/fragments","value":[{"kind":"identifier","text":"playO2"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon\/title","value":"CustomFontIcon"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon\/fragments","value":[{"kind":"identifier","text":"CustomFontIcon"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}