{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wheelchair"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/customfonticon\/wheelchair"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/customfonticon\/wheelchair"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/wheelchair","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wheelchair"}],"title":"CustomFontIcon.wheelchair","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@CustomFontIcon@wheelchair","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"wheelchair"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon":{"role":"symbol","title":"CustomFontIcon","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomFontIcon"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomFontIcon"}],"url":"\/documentation\/mapsindoors\/customfonticon"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/wheelchair":{"role":"symbol","title":"CustomFontIcon.wheelchair","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wheelchair"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/wheelchair","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"wheelchair"}],"url":"\/documentation\/mapsindoors\/customfonticon\/wheelchair"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"wheelchair"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"wheelchair"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"wheelchair"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon\/title","value":"CustomFontIcon"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon\/fragments","value":[{"kind":"identifier","text":"CustomFontIcon"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1wheelchair\/title","value":"wheelchair"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1wheelchair\/fragments","value":[{"kind":"identifier","text":"wheelchair"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}