{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"venues"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpvenuecollection\/venues"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpvenuecollection\/venues"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueCollection\/venues","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The array of venues in this collection."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"venues"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"title":"venues","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPVenueCollection(py)venues","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"venues"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueCollection"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPVenueCollection":{"role":"symbol","title":"MPVenueCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenueCollection"}],"abstract":[{"type":"text","text":"Venue collection model, just holds an array."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenueCollection"}],"url":"\/documentation\/mapsindoors\/mpvenuecollection"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueCollection/venues":{"role":"symbol","title":"venues","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"venues"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The array of venues in this collection."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueCollection\/venues","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"venues"}],"url":"\/documentation\/mapsindoors\/mpvenuecollection\/venues"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"venues"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"venues"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<MPVenue>","preciseIdentifier":"c:Q$objc(cs)NSArrayobjc(pl)MPVenue"},{"kind":"text","text":" *"},{"kind":"identifier","text":"venues"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueCollection\/title","value":"MPVenueCollection"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueCollection\/fragments","value":[{"kind":"identifier","text":"MPVenueCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueCollection~1venues\/title","value":"venues"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueCollection~1venues\/fragments","value":[{"kind":"identifier","text":"venues"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}