{"metadata":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"distanceTo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"other"},{"text":": ","kind":"text"},{"text":"MPGeometryProtocol","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"distanceTo(other:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"distanceToOther:"}],"modules":[{"name":"MapsIndoors"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol(im)distanceToOther:"},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/distanceTo(other:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpgeometryprotocol\/distanceto(other:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpgeometryprotocol\/distanceto(other:)"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"distanceTo"},{"text":"(","kind":"text"},{"text":"other","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol","text":"MPGeometryProtocol","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryProtocol/distanceTo(other:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/distanceTo(other:)","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"distanceTo","kind":"identifier"},{"kind":"text","text":"("},{"text":"other","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol","text":"MPGeometryProtocol"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"url":"\/documentation\/mapsindoors\/mpgeometryprotocol\/distanceto(other:)","title":"distanceTo(other:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"distanceToOther:"}],"type":"topic"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryProtocol":{"url":"\/documentation\/mapsindoors\/mpgeometryprotocol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPGeometryProtocol","kind":"identifier"}],"title":"MPGeometryProtocol","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPGeometryProtocol"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"distanceToOther:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"distanceToOther:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":") ","kind":"text"},{"text":"distanceToOther:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPGeometryProtocol","text":"id<MPGeometryProtocol>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"other"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol~1distanceTo(other:)\/title","value":"distanceToOther:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol~1distanceTo(other:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"distanceToOther:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol\/title","value":"MPGeometryProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol\/fragments","value":[{"text":"MPGeometryProtocol","kind":"identifier"}]}]}]}