{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygon"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon","text":"MPGeoPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol(py)polygon","symbolKind":"property","title":"polygon","roleHeading":"Instance Property","navigatorTitle":[{"text":"polygon","kind":"identifier"}],"role":"symbol","required":true,"modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"polygon"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon","text":"MPGeoPolygon","kind":"typeIdentifier"}]},"variants":[{"paths":["\/documentation\/mapsindoors\/mpgeometryprotocol\/polygon"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpgeometryprotocol\/polygon"]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/polygon","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryProtocol":{"url":"\/documentation\/mapsindoors\/mpgeometryprotocol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPGeometryProtocol","kind":"identifier"}],"title":"MPGeometryProtocol","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPGeometryProtocol"}],"kind":"symbol"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPolygon":{"abstract":[],"url":"\/documentation\/mapsindoors\/mpgeopolygon","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPGeoPolygon","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPGeoPolygon"}],"title":"MPGeoPolygon"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryProtocol/polygon":{"title":"polygon","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"polygon"}],"type":"topic","abstract":[],"url":"\/documentation\/mapsindoors\/mpgeometryprotocol\/polygon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"polygon","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPGeoPolygon","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/polygon","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"polygon"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"polygon"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon","text":"MPGeoPolygon"},{"text":" * ","kind":"text"},{"text":"polygon","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MPGeometryProtocol","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPGeometryProtocol"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon\/title","value":"MPGeoPolygon","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MPGeoPolygon"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol~1polygon\/title","value":"polygon"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol~1polygon\/fragments","value":[{"kind":"identifier","text":"polygon"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}