{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCategoriesWithCompletion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpCategoriesHandlerBlockType","preciseIdentifier":"c:MPCategoriesProvider.h@T@mpCategoriesHandlerBlockType","text":"mpCategoriesHandlerBlockType"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Block with code to execute when categories become available."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpcategoriesprovider\/getcategorieswithcompletion(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpcategoriesprovider\/getcategorieswithcompletion(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider\/getCategoriesWithCompletion(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get Categories from this provider and provide a callback handler."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCategoriesWithCompletion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpCategoriesHandlerBlockType","preciseIdentifier":"c:MPCategoriesProvider.h@T@mpCategoriesHandlerBlockType"},{"kind":"text","text":"?)"}],"title":"getCategoriesWithCompletion(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPCategoriesProvider(im)getCategoriesWithCompletion:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getCategoriesWithCompletion:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPCategoriesProvider":{"role":"symbol","title":"MPCategoriesProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPCategoriesProvider"}],"abstract":[{"type":"text","text":"A categories provider acts as a service for the location categories belonging to a specific MapsIndoors solution\/dataset."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPCategoriesProvider"}],"url":"\/documentation\/mapsindoors\/mpcategoriesprovider"},"doc://MapsIndoors/documentation/MapsIndoors/MPCategoriesProvider/getCategoriesWithCompletion(_:)":{"role":"symbol","title":"getCategoriesWithCompletion(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCategoriesWithCompletion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpCategoriesHandlerBlockType","preciseIdentifier":"c:MPCategoriesProvider.h@T@mpCategoriesHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get Categories from this provider and provide a callback handler."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategoriesProvider\/getCategoriesWithCompletion(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getCategoriesWithCompletion:"}],"url":"\/documentation\/mapsindoors\/mpcategoriesprovider\/getcategorieswithcompletion(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/mpCategoriesHandlerBlockType":{"role":"symbol","title":"mpCategoriesHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpCategoriesHandlerBlockType"}],"abstract":[{"type":"text","text":"Callback block for getting category data or handling error in doing so."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpCategoriesHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpCategoriesHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpcategorieshandlerblocktype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getCategoriesWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCategoriesWithCompletion:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getCategoriesWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<MPDataField *> *, NSError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategoriesProvider\/title","value":"MPCategoriesProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategoriesProvider\/fragments","value":[{"kind":"identifier","text":"MPCategoriesProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategoriesProvider~1getCategoriesWithCompletion(_:)\/title","value":"getCategoriesWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategoriesProvider~1getCategoriesWithCompletion(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCategoriesWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpCategoriesHandlerBlockType\/title","value":"mpCategoriesHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpCategoriesHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpCategoriesHandlerBlockType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}