{"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"near","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint","text":"MPPoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Geographical point that serve as additional horizontal and vertical proximity context for a search. If supplied, locations that are closer to the "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/near","isActive":true,"type":"reference"},{"text":" point will be ranked higher. The proximity calculation is based on direct lines and does not reflect real world travel distances.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpquery\/near"]},{"paths":["\/documentation\/mapsindoors\/mpquery\/near"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"near","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"near"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","text":"MPPoint"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPQuery(py)near","modules":[{"name":"MapsIndoors"}],"roleHeading":"Instance Property","title":"near","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/near"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/locationsWith(query:filter:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"locationsWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"query"},{"text":": ","kind":"text"},{"text":"MPQuery","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPQuery","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"filter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPFilter","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilter"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"kind":"text","text":"]"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"locationsWithQuery:filter:completionHandler:","kind":"identifier"}],"title":"locationsWith(query:filter:)","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/locationswith(query:filter:)","kind":"symbol","required":true,"abstract":[{"type":"text","text":"Search for MPLocations using MPQuery and\/or MPFilter."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPQuery":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPQuery","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"MPQuery","kind":"identifier"}],"title":"MPQuery","url":"\/documentation\/mapsindoors\/mpquery","kind":"symbol","abstract":[{"type":"text","text":"Query object used when making a request to "},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","type":"reference"},{"text":".","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPoint":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"MPPoint","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPoint"}],"type":"topic","title":"MPPoint","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint","url":"\/documentation\/mapsindoors\/mppoint"},"MapsPeopleWhite.png":{"type":"image","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPQuery/near":{"url":"\/documentation\/mapsindoors\/mpquery\/near","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"near"}],"abstract":[{"type":"text","text":"Geographical point that serve as additional horizontal and vertical proximity context for a search. If supplied, locations that are closer to the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/near"},{"text":" point will be ranked higher. The proximity calculation is based on direct lines and does not reflect real world travel distances.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/near","title":"near","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"near","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPPoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"near"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"near","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"MPPoint","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"near"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/title","op":"replace","value":"locationsWithQuery:filter:completionHandler:"},{"value":[{"text":"- ","kind":"text"},{"text":"locationsWithQuery:filter:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/fragments"},{"op":"replace","value":"MPQuery","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery\/fragments","value":[{"text":"MPQuery","kind":"identifier"}],"op":"replace"},{"value":"MPPoint","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPoint\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPoint\/fragments","op":"replace","value":[{"text":"MPPoint","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery~1near\/title","value":"near"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery~1near\/fragments","value":[{"kind":"identifier","text":"near"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}