{"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"List of properties that "},{"code":"MPLocationService","type":"codeVoice"},{"text":" will take into account when finding and sorting matching locations. By default, ","type":"text"},{"code":"MPLocationService","type":"codeVoice"},{"text":" will search in the name, externalId and aliases properties. Possible other properties depend on the location content. E.g. if an ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","isActive":true},{"text":" has a field called ","type":"text"},{"type":"codeVoice","code":"booking-id"},{"text":", the string “booking-id” (case-sensitive) may be added. Query properties added that do not exist in any Locations will be ignored.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"queryProperties"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpquery\/queryproperties"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpquery\/queryproperties"]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/queryProperties"},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"queryProperties","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"queryProperties","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"property","externalID":"c:@M@MapsIndoors@objc(cs)MPQuery(py)queryProperties","role":"symbol","title":"queryProperties","roleHeading":"Instance Property"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPQuery":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPQuery","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Query object used when making a request to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery","title":"MPQuery","navigatorTitle":[{"kind":"identifier","text":"MPQuery"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpquery","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/locationsWith(query:filter:)":{"role":"symbol","navigatorTitle":[{"text":"locationsWithQuery:filter:completionHandler:","kind":"identifier"}],"title":"locationsWith(query:filter:)","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/locationswith(query:filter:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locationsWith","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"query"},{"text":": ","kind":"text"},{"text":"MPQuery","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPQuery","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"filter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilter"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","text":"MPLocation"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","required":true,"abstract":[{"type":"text","text":"Search for MPLocations using MPQuery and\/or MPFilter."}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation":{"navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLocation","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mplocation","title":"MPLocation","abstract":[{"type":"text","text":"This holds the data for a single location and a marker to display the data on a map."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPQuery/queryProperties":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"queryProperties"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"title":"queryProperties","navigatorTitle":[{"kind":"identifier","text":"queryProperties"}],"abstract":[{"text":"List of properties that ","type":"text"},{"code":"MPLocationService","type":"codeVoice"},{"type":"text","text":" will take into account when finding and sorting matching locations. By default, "},{"type":"codeVoice","code":"MPLocationService"},{"type":"text","text":" will search in the name, externalId and aliases properties. Possible other properties depend on the location content. E.g. if an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation"},{"text":" has a field called ","type":"text"},{"type":"codeVoice","code":"booking-id"},{"text":", the string “booking-id” (case-sensitive) may be added. Query properties added that do not exist in any Locations will be ignored.","type":"text"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpquery\/queryproperties","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/queryProperties"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"queryProperties","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"queryProperties","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSString *>"},{"kind":"text","text":" * "},{"text":"queryProperties","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"MPQuery","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery\/title"},{"value":[{"kind":"identifier","text":"MPQuery"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/title","op":"replace","value":"locationsWithQuery:filter:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationsWithQuery:filter:completionHandler:"}]},{"op":"replace","value":"MPLocation","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/title"},{"value":[{"kind":"identifier","text":"MPLocation"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/fragments","op":"replace"},{"op":"replace","value":"queryProperties","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery~1queryProperties\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery~1queryProperties\/fragments","op":"replace","value":[{"text":"queryProperties","kind":"identifier"}]}]}]}