{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessagesWithCompletion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpMessageListHandlerBlockType","preciseIdentifier":"c:MPMessageProvider.h@T@mpMessageListHandlerBlockType","text":"mpMessageListHandlerBlockType"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmessagesproviderprotocol\/getmessageswithcompletion(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmessagesproviderprotocol\/getmessageswithcompletion(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessagesProviderProtocol\/getMessagesWithCompletion(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Method to initiate fetching of all Messages from the provider."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getMessagesWithCompletion:"}],"role":"symbol","title":"getMessagesWithCompletion(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessagesWithCompletion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpMessageListHandlerBlockType","preciseIdentifier":"c:MPMessageProvider.h@T@mpMessageListHandlerBlockType"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:objc(pl)MPMessagesProvider(im)getMessagesWithCompletion:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessagesProviderProtocol"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPMessagesProviderProtocol":{"role":"symbol","title":"MPMessagesProviderProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMessagesProviderProtocol"}],"abstract":[{"type":"text","text":"Messages provider protocol."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessagesProviderProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMessagesProviderProtocol"}],"url":"\/documentation\/mapsindoors\/mpmessagesproviderprotocol"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessagesProviderProtocol/getMessagesWithCompletion(_:)":{"navigatorTitle":[{"kind":"identifier","text":"getMessagesWithCompletion:"}],"role":"symbol","title":"getMessagesWithCompletion(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessagesWithCompletion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpMessageListHandlerBlockType","preciseIdentifier":"c:MPMessageProvider.h@T@mpMessageListHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Method to initiate fetching of all Messages from the provider."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessagesProviderProtocol\/getMessagesWithCompletion(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpmessagesproviderprotocol\/getmessageswithcompletion(_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/mpMessageListHandlerBlockType":{"role":"symbol","title":"mpMessageListHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpMessageListHandlerBlockType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpMessageListHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpMessageListHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpmessagelisthandlerblocktype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getMessagesWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMessagesWithCompletion:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getMessagesWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<MPMessage> *, NSError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArrayobjc(pl)MPMessage#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"handler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessagesProviderProtocol\/title","value":"MPMessagesProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessagesProviderProtocol\/fragments","value":[{"kind":"identifier","text":"MPMessagesProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessagesProviderProtocol~1getMessagesWithCompletion(_:)\/title","value":"getMessagesWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessagesProviderProtocol~1getMessagesWithCompletion(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMessagesWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpMessageListHandlerBlockType\/title","value":"mpMessageListHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpMessageListHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpMessageListHandlerBlockType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}