{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"booking"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBooking","preciseIdentifier":"c:objc(cs)MPBooking","text":"MPBooking"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpBookingCompletion","preciseIdentifier":"c:MPBookingService.h@T@mpBookingCompletion","text":"mpBookingCompletion"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"booking","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Booking to cancel"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Completion handler"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbookingservice\/cancel(_:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbookingservice\/cancel(_:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookingService\/cancel(_:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Cancel the booking identified by the booking parameter."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPBooking","preciseIdentifier":"c:objc(cs)MPBooking"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpBookingCompletion","preciseIdentifier":"c:MPBookingService.h@T@mpBookingCompletion"},{"kind":"text","text":")"}],"title":"cancel(_:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPBookingService(im)cancelBooking:completion:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"cancelBooking:completion:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookingService"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPBookingService/cancel(_:completion:)":{"role":"symbol","title":"cancel(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPBooking","preciseIdentifier":"c:objc(cs)MPBooking"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpBookingCompletion","preciseIdentifier":"c:MPBookingService.h@T@mpBookingCompletion"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Cancel the booking identified by the booking parameter."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookingService\/cancel(_:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cancelBooking:completion:"}],"url":"\/documentation\/mapsindoors\/mpbookingservice\/cancel(_:completion:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPBookingService":{"role":"symbol","title":"MPBookingService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBookingService"}],"abstract":[{"type":"text","text":"MPBookingService allows for access to the MapsIndoors booking service."},{"type":"text","text":" "},{"type":"text","text":"The booking service is a special integration that has to be enabled in the MapsIndoors cloud systems."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookingService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBookingService"}],"url":"\/documentation\/mapsindoors\/mpbookingservice"},"doc://MapsIndoors/documentation/MapsIndoors/MPBooking":{"role":"symbol","title":"MPBooking","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBooking"}],"abstract":[{"type":"text","text":"MPBooking represents an existing booking object or a booking to be made."},{"type":"text","text":" "},{"type":"text","text":"bookingId will be non-null for an existing booking, and null for a booking to be made."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBooking","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBooking"}],"url":"\/documentation\/mapsindoors\/mpbooking"},"doc://MapsIndoors/documentation/MapsIndoors/mpBookingCompletion":{"role":"symbol","title":"mpBookingCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpBookingCompletion"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpBookingCompletion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpBookingCompletion"}],"url":"\/documentation\/mapsindoors\/mpbookingcompletion"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"cancelBooking:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelBooking:completion:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"cancelBooking:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBooking","preciseIdentifier":"c:objc(cs)MPBooking","text":"MPBooking"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"booking"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(MPBooking *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)MPBooking#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookingService~1cancel(_:completion:)\/title","value":"cancelBooking:completion:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookingService~1cancel(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelBooking:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookingService\/title","value":"MPBookingService"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookingService\/fragments","value":[{"kind":"identifier","text":"MPBookingService"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBooking\/title","value":"MPBooking"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBooking\/fragments","value":[{"kind":"identifier","text":"MPBooking"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpBookingCompletion\/title","value":"mpBookingCompletion"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpBookingCompletion\/fragments","value":[{"kind":"identifier","text":"mpBookingCompletion"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}