{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBookingsUsing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"q"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookingsQuery","preciseIdentifier":"c:objc(cs)MPBookingsQuery","text":"MPBookingsQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpBookingListCompletion","preciseIdentifier":"c:MPBookingService.h@T@mpBookingListCompletion","text":"mpBookingListCompletion"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"query","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Filter to apply"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Completion handler"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbookingservice\/getbookingsusing(_:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbookingservice\/getbookingsusing(_:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookingService\/getBookingsUsing(_:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get existing booking according the the given query."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBookingsUsing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPBookingsQuery","preciseIdentifier":"c:objc(cs)MPBookingsQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpBookingListCompletion","preciseIdentifier":"c:MPBookingService.h@T@mpBookingListCompletion"},{"kind":"text","text":")"}],"title":"getBookingsUsing(_:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPBookingService(im)getBookingsUsingQuery:completion:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getBookingsUsingQuery:completion:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookingService"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPBookingService":{"role":"symbol","title":"MPBookingService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBookingService"}],"abstract":[{"type":"text","text":"MPBookingService allows for access to the MapsIndoors booking service."},{"type":"text","text":" "},{"type":"text","text":"The booking service is a special integration that has to be enabled in the MapsIndoors cloud systems."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookingService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBookingService"}],"url":"\/documentation\/mapsindoors\/mpbookingservice"},"doc://MapsIndoors/documentation/MapsIndoors/MPBookingService/getBookingsUsing(_:completion:)":{"role":"symbol","title":"getBookingsUsing(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBookingsUsing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPBookingsQuery","preciseIdentifier":"c:objc(cs)MPBookingsQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpBookingListCompletion","preciseIdentifier":"c:MPBookingService.h@T@mpBookingListCompletion"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get existing booking according the the given query."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookingService\/getBookingsUsing(_:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getBookingsUsingQuery:completion:"}],"url":"\/documentation\/mapsindoors\/mpbookingservice\/getbookingsusing(_:completion:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPBookingsQuery":{"role":"symbol","title":"MPBookingsQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBookingsQuery"}],"abstract":[{"type":"text","text":"Query object to be used with MPBookingService.getBookingsUsingQuery()"},{"type":"text","text":" "},{"type":"text","text":"Queries can be either for a location or a user (organizerId), and may optionally be limited to a given timespan."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookingsQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBookingsQuery"}],"url":"\/documentation\/mapsindoors\/mpbookingsquery"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/mpBookingListCompletion":{"role":"symbol","title":"mpBookingListCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpBookingListCompletion"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpBookingListCompletion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpBookingListCompletion"}],"url":"\/documentation\/mapsindoors\/mpbookinglistcompletion"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getBookingsUsingQuery:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBookingsUsingQuery:completion:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getBookingsUsingQuery:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookingsQuery","preciseIdentifier":"c:objc(cs)MPBookingsQuery","text":"MPBookingsQuery"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"q"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<MPBooking *> *, NSError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookingService\/title","value":"MPBookingService"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookingService\/fragments","value":[{"kind":"identifier","text":"MPBookingService"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookingService~1getBookingsUsing(_:completion:)\/title","value":"getBookingsUsingQuery:completion:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookingService~1getBookingsUsing(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBookingsUsingQuery:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookingsQuery\/title","value":"MPBookingsQuery"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookingsQuery\/fragments","value":[{"kind":"identifier","text":"MPBookingsQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpBookingListCompletion\/title","value":"mpBookingListCompletion"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpBookingListCompletion\/fragments","value":[{"kind":"identifier","text":"mpBookingListCompletion"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}