{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbookablequery\/endtime"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbookablequery\/endtime"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookableQuery\/endTime","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Required end date for your potential booking."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"title":"endTime","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPBookableQuery(py)endTime","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"endTime"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookableQuery"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPBookableQuery/endTime":{"role":"symbol","title":"endTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"abstract":[{"type":"text","text":"Required end date for your potential booking."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookableQuery\/endTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"endTime"}],"url":"\/documentation\/mapsindoors\/mpbookablequery\/endtime"},"doc://MapsIndoors/documentation/MapsIndoors/MPBookableQuery":{"role":"symbol","title":"MPBookableQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBookableQuery"}],"abstract":[{"type":"text","text":"Query object to be used with MPBookingService.getBookableLocationsUsingQuery()"},{"type":"text","text":" "},{"type":"text","text":"Queries are defined by a required timespan and a number of optional filter properties."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBookableQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBookableQuery"}],"url":"\/documentation\/mapsindoors\/mpbookablequery"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"endTime"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"endTime"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonnull"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"endTime"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookableQuery~1endTime\/title","value":"endTime"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookableQuery~1endTime\/fragments","value":[{"kind":"identifier","text":"endTime"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookableQuery\/title","value":"MPBookableQuery"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBookableQuery\/fragments","value":[{"kind":"identifier","text":"MPBookableQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}