{"sections":[],"abstract":[{"type":"text","text":"Required start date for your potential booking."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"startTime","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/startTime"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTime"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"symbolKind":"property","title":"startTime","navigatorTitle":[{"kind":"identifier","text":"startTime"}],"roleHeading":"Instance Property","modules":[{"name":"MapsIndoors"}],"role":"symbol","externalID":"c:@M@MapsIndoors@objc(cs)MPBookableQuery(py)startTime"},"variants":[{"paths":["\/documentation\/mapsindoors\/mpbookablequery\/starttime"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpbookablequery\/starttime"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookableQuery":{"role":"symbol","abstract":[{"type":"text","text":"Query object to be used with MPBookingService.getBookableLocationsUsingQuery()."},{"text":" ","type":"text"},{"type":"text","text":"Queries are defined by a required timespan and a number of optional filter properties."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpbookablequery","navigatorTitle":[{"text":"MPBookableQuery","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPBookableQuery","kind":"identifier"}],"title":"MPBookableQuery"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookableQuery/startTime":{"role":"symbol","abstract":[{"text":"Required start date for your potential booking.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpbookablequery\/starttime","navigatorTitle":[{"text":"startTime","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/startTime","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"startTime","kind":"identifier"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"title":"startTime"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image","identifier":"MapsPeopleWhite.png","alt":null}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"startTime"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"startTime"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"text":"NSDate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate"},{"text":" * ","kind":"text"},{"text":"startTime","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery\/title","op":"replace","value":"MPBookableQuery"},{"value":[{"text":"MPBookableQuery","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1startTime\/title","value":"startTime","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1startTime\/fragments","value":[{"kind":"identifier","text":"startTime"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}