{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"categories","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings"]]},"abstract":[{"type":"text","text":"The Categories of Location that should be used when showing text and icon for a start or end marker."},{"text":" ","type":"text"},{"text":"If no Categories are supplied, all Categories of Locations will be considered.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpcontextualinfosettings\/categories"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpcontextualinfosettings\/categories"]}],"metadata":{"title":"categories","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"categories","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"categories","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@MapsIndoors@objc(cs)MPContextualInfoSettings(py)categories","role":"symbol","modules":[{"name":"MapsIndoors"}],"symbolKind":"property"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/categories","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoSettings/categories":{"title":"categories","role":"symbol","abstract":[{"text":"The Categories of Location that should be used when showing text and icon for a start or end marker.","type":"text"},{"type":"text","text":" "},{"text":"If no Categories are supplied, all Categories of Locations will be considered.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpcontextualinfosettings\/categories","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"categories","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"categories"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/categories","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"title":"MapsIndoors","role":"collection","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","kind":"symbol"},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","type":"image","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoSettings":{"title":"MPContextualInfoSettings","role":"symbol","abstract":[{"type":"text","text":"Settings for showing contextual info along the rendered route."}],"url":"\/documentation\/mapsindoors\/mpcontextualinfosettings","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPContextualInfoSettings","kind":"identifier"}],"navigatorTitle":[{"text":"MPContextualInfoSettings","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"categories","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"categories"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"categories","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"categories","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings~1categories\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings~1categories\/fragments","value":[{"kind":"identifier","text":"categories"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings\/title","value":"MPContextualInfoSettings","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings\/fragments","value":[{"kind":"identifier","text":"MPContextualInfoSettings"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}