{"metadata":{"role":"symbol","modules":[{"name":"MapsIndoors"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"infoScope"},{"kind":"text","text":": "},{"text":"MPContextualInfoScope","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPContextualInfoScope"}],"navigatorTitle":[{"kind":"identifier","text":"infoScope"}],"title":"infoScope","externalID":"c:@M@MapsIndoors@objc(cs)MPContextualInfoSettings(py)infoScope","roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/mapsindoors\/mpcontextualinfosettings\/infoscope"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpcontextualinfosettings\/infoscope"]}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"infoScope"},{"text":": ","kind":"text"},{"text":"MPContextualInfoScope","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPContextualInfoScope","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope"}]}]}],"abstract":[{"type":"text","text":"Which content should be used. Default is "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/iconAndName","isActive":true,"type":"reference"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/infoScope","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoSettings":{"role":"symbol","abstract":[{"text":"Settings for showing contextual info along the rendered route.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MPContextualInfoSettings"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPContextualInfoSettings","kind":"identifier"}],"title":"MPContextualInfoSettings","url":"\/documentation\/mapsindoors\/mpcontextualinfosettings","type":"topic","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoScope":{"title":"MPContextualInfoScope","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPContextualInfoScope"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPContextualInfoScope","kind":"identifier"}],"abstract":[{"type":"text","text":"Which information to show from the Location close to the end of a route leg."}],"url":"\/documentation\/mapsindoors\/mpcontextualinfoscope","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoSettings/infoScope":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"infoScope","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@E@MPContextualInfoScope","kind":"typeIdentifier","text":"MPContextualInfoScope"}],"navigatorTitle":[{"kind":"identifier","text":"infoScope"}],"title":"infoScope","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/infoScope","abstract":[{"type":"text","text":"Which content should be used. Default is "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/iconAndName"},{"type":"text","text":"."}],"url":"\/documentation\/mapsindoors\/mpcontextualinfosettings\/infoscope","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoScope/iconAndName":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconAndName"}],"navigatorTitle":[{"text":"MPContextualInfoScopeIconAndName","kind":"identifier"}],"title":"MPContextualInfoScope.iconAndName","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/iconAndName","url":"\/documentation\/mapsindoors\/mpcontextualinfoscope\/iconandname","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"infoScope","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"infoScope","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPContextualInfoScope","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPContextualInfoScope","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope"},{"kind":"text","text":" "},{"text":"infoScope","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MPContextualInfoSettings","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MPContextualInfoSettings"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope\/title","op":"replace","value":"MPContextualInfoScope"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope\/fragments","value":[{"text":"MPContextualInfoScope","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings~1infoScope\/title","value":"infoScope"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings~1infoScope\/fragments","value":[{"text":"infoScope","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope~1iconAndName\/title","value":"MPContextualInfoScopeIconAndName"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope~1iconAndName\/fragments","value":[{"text":"MPContextualInfoScopeIconAndName","kind":"identifier"}],"op":"replace"}]}]}