{"metadata":{"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"maxDistance","kind":"identifier"}],"title":"maxDistance","externalID":"c:@M@MapsIndoors@objc(cs)MPContextualInfoSettings(py)maxDistance","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxDistance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"property"},"kind":"symbol","abstract":[{"type":"text","text":"The maximum distance in meters allowed for using text and icon from a Location. Default of 5 meters."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDistance"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpcontextualinfosettings\/maxdistance"]},{"paths":["\/documentation\/mapsindoors\/mpcontextualinfosettings\/maxdistance"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/maxDistance","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoSettings/maxDistance":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/maxDistance","role":"symbol","navigatorTitle":[{"text":"maxDistance","kind":"identifier"}],"title":"maxDistance","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxDistance"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpcontextualinfosettings\/maxdistance","abstract":[{"type":"text","text":"The maximum distance in meters allowed for using text and icon from a Location. Default of 5 meters."}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoSettings":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPContextualInfoSettings","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings","url":"\/documentation\/mapsindoors\/mpcontextualinfosettings","type":"topic","kind":"symbol","title":"MPContextualInfoSettings","abstract":[{"text":"Settings for showing contextual info along the rendered route.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPContextualInfoSettings"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"maxDistance","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"maxDistance"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"maxDistance","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"maxDistance","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings~1maxDistance\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings~1maxDistance\/fragments","op":"replace","value":[{"text":"maxDistance","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings\/title","op":"replace","value":"MPContextualInfoSettings"},{"value":[{"kind":"identifier","text":"MPContextualInfoSettings"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings\/fragments","op":"replace"}]}]}