{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"types","roleHeading":"Instance Property","externalID":"c:@M@MapsIndoors@objc(cs)MPContextualInfoSettings(py)types","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"types","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"types","kind":"identifier"}],"symbolKind":"property"},"kind":"symbol","abstract":[{"type":"text","text":"The Types of Location that should be used when showing text and icon for a start or end marker."},{"type":"text","text":" "},{"type":"text","text":"If no Types are supplied, all Types of Locations will be considered."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"types","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpcontextualinfosettings\/types"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpcontextualinfosettings\/types"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/types"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoSettings/types":{"navigatorTitle":[{"text":"types","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"types"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The Types of Location that should be used when showing text and icon for a start or end marker."},{"type":"text","text":" "},{"type":"text","text":"If no Types are supplied, all Types of Locations will be considered."}],"type":"topic","kind":"symbol","url":"\/documentation\/mapsindoors\/mpcontextualinfosettings\/types","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/types","title":"types"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoSettings":{"role":"symbol","abstract":[{"text":"Settings for showing contextual info along the rendered route.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MPContextualInfoSettings"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPContextualInfoSettings","kind":"identifier"}],"title":"MPContextualInfoSettings","url":"\/documentation\/mapsindoors\/mpcontextualinfosettings","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"types"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"types","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"types"}]}]}},{"value":"types","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings~1types\/title","op":"replace"},{"value":[{"kind":"identifier","text":"types"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings~1types\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings\/title","value":"MPContextualInfoSettings","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings\/fragments","value":[{"kind":"identifier","text":"MPContextualInfoSettings"}]}]}]}