{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"list"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataField-swift.class","preciseIdentifier":"c:objc(cs)MPDataField","text":"MPDataField"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpcategories\/list"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpcategories\/list"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategories\/list","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"list"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPDataField","preciseIdentifier":"c:objc(cs)MPDataField"},{"kind":"text","text":"]?"}],"title":"list","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPCategories(py)list","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"list"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategories"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPCategories":{"role":"symbol","title":"MPCategories","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPCategories"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategories","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPCategories"}],"url":"\/documentation\/mapsindoors\/mpcategories"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataField-swift.class":{"role":"symbol","title":"MPDataField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataField"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataField-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataField"}],"url":"\/documentation\/mapsindoors\/mpdatafield-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPCategories/list":{"role":"symbol","title":"list","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"list"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPDataField","preciseIdentifier":"c:objc(cs)MPDataField"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPCategories\/list","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"list"}],"url":"\/documentation\/mapsindoors\/mpcategories\/list"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"list"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"list"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<MPDataField *><MPDataField>","preciseIdentifier":"c:Q$objc(cs)NSArrayobjc(pl)MPDataField"},{"kind":"text","text":" * "},{"kind":"identifier","text":"list"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategories\/title","value":"MPCategories"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategories\/fragments","value":[{"kind":"identifier","text":"MPCategories"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataField-swift.class\/title","value":"MPDataField"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataField-swift.class\/fragments","value":[{"kind":"identifier","text":"MPDataField"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategories~1list\/title","value":"list"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPCategories~1list\/fragments","value":[{"kind":"identifier","text":"list"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}