{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"end_location"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class","preciseIdentifier":"c:objc(cs)MPRouteCoordinate","text":"MPRouteCoordinate"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mprouteleg-swift.class\/end_location"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mprouteleg-swift.class\/end_location"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/end_location","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The route leg end position"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"end_location"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MPRouteCoordinate","preciseIdentifier":"c:objc(cs)MPRouteCoordinate"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"title":"end_location","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPRouteLeg(py)end_location","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"end_location"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLeg-swift.class":{"role":"symbol","title":"MPRouteLeg","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteLeg"}],"abstract":[{"type":"text","text":"Route leg model. A route model will consist of one ore more route legs. Typically a route from 1st floor to 2nd floor will consist of two route legs. Thus, a route leg defines a continueus route part within the same floor and\/or building and\/or vehicle."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteLeg"}],"url":"\/documentation\/mapsindoors\/mprouteleg-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteCoordinate-swift.class":{"role":"symbol","title":"MPRouteCoordinate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteCoordinate"}],"abstract":[{"type":"text","text":"Route coordinate model"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteCoordinate-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteCoordinate"}],"url":"\/documentation\/mapsindoors\/mproutecoordinate-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLeg-swift.class/end_location":{"role":"symbol","title":"end_location","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"end_location"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MPRouteCoordinate","preciseIdentifier":"c:objc(cs)MPRouteCoordinate"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The route leg end position"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/end_location","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"end_location"}],"url":"\/documentation\/mapsindoors\/mprouteleg-swift.class\/end_location"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"end_location"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"end_location"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"MPRouteCoordinate<Optional>","preciseIdentifier":"c:Q$objc(cs)MPRouteCoordinateobjc(pl)Optional"},{"kind":"text","text":" *"},{"kind":"identifier","text":"end_location"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class\/title","value":"MPRouteLeg"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class\/fragments","value":[{"kind":"identifier","text":"MPRouteLeg"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteCoordinate-swift.class\/title","value":"MPRouteCoordinate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteCoordinate-swift.class\/fragments","value":[{"kind":"identifier","text":"MPRouteCoordinate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1end_location\/title","value":"end_location"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1end_location\/fragments","value":[{"kind":"identifier","text":"end_location"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}