{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routeLegType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLegType","preciseIdentifier":"c:@E@MPRouteLegType","text":"MPRouteLegType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mprouteleg-swift.class\/routelegtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mprouteleg-swift.class\/routelegtype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/routeLegType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The type of leg, determined by the source service, Google or MapsIndoors."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routeLegType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPRouteLegType","preciseIdentifier":"c:@E@MPRouteLegType"}],"title":"routeLegType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPRouteLeg(py)routeLegType","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"routeLegType"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLeg-swift.class/routeLegType":{"role":"symbol","title":"routeLegType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routeLegType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPRouteLegType","preciseIdentifier":"c:@E@MPRouteLegType"}],"abstract":[{"type":"text","text":"The type of leg, determined by the source service, Google or MapsIndoors."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/routeLegType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"routeLegType"}],"url":"\/documentation\/mapsindoors\/mprouteleg-swift.class\/routelegtype"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLegType":{"role":"symbol","title":"MPRouteLegType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteLegType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLegType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteLegType"}],"url":"\/documentation\/mapsindoors\/mproutelegtype"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLeg-swift.class":{"role":"symbol","title":"MPRouteLeg","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteLeg"}],"abstract":[{"type":"text","text":"Route leg model. A route model will consist of one ore more route legs. Typically a route from 1st floor to 2nd floor will consist of two route legs. Thus, a route leg defines a continueus route part within the same floor and\/or building and\/or vehicle."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteLeg"}],"url":"\/documentation\/mapsindoors\/mprouteleg-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"routeLegType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"routeLegType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLegType","preciseIdentifier":"c:@E@MPRouteLegType","text":"MPRouteLegType"},{"kind":"identifier","text":"routeLegType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1routeLegType\/title","value":"routeLegType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1routeLegType\/fragments","value":[{"kind":"identifier","text":"routeLegType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLegType\/title","value":"MPRouteLegType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLegType\/fragments","value":[{"kind":"identifier","text":"MPRouteLegType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class\/title","value":"MPRouteLeg"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class\/fragments","value":[{"kind":"identifier","text":"MPRouteLeg"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}