{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"onView"},{"kind":"text","text":" "},{"kind":"internalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mploadindicator\/init(onview:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mploadindicator\/init(onview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/init(onView:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Instantiates the indicator and places the indicator in a view."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initOnView:"}],"role":"symbol","title":"init(onView:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"onView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"symbolKind":"init","externalID":"c:objc(cs)MPLoadIndicator(im)initOnView:","modules":[{"name":"MapsIndoors"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLoadIndicator":{"role":"symbol","title":"MPLoadIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLoadIndicator"}],"abstract":[{"type":"text","text":"A basic load indicator, with the option to set a text."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLoadIndicator"}],"url":"\/documentation\/mapsindoors\/mploadindicator"},"doc://MapsIndoors/documentation/MapsIndoors/MPLoadIndicator/init(onView:)":{"role":"symbol","title":"init(onView:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"onView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Instantiates the indicator and places the indicator in a view."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/init(onView:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initOnView:"}],"url":"\/documentation\/mapsindoors\/mploadindicator\/init(onview:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initOnView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initOnView:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initOnView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"view"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator\/title","value":"MPLoadIndicator"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator\/fragments","value":[{"kind":"identifier","text":"MPLoadIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator~1init(onView:)\/title","value":"initOnView:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator~1init(onView:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initOnView:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}