{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bearing","kind":"identifier"},{"kind":"text","text":": "},{"text":"CLLocationDirection","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"The bearing of the map, measured in degrees clockwise from true north.","type":"text"}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpcameraposition\/bearing"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpcameraposition\/bearing"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPCameraPosition(py)bearing","navigatorTitle":[{"text":"bearing","kind":"identifier"}],"role":"symbol","required":true,"title":"bearing","modules":[{"name":"MapsIndoors"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bearing"},{"kind":"text","text":": "},{"text":"CLLocationDirection","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/bearing","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraPosition":{"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MPCameraPosition"}],"role":"symbol","title":"MPCameraPosition","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPCameraPosition","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpcameraposition"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraPosition/bearing":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/bearing","abstract":[{"type":"text","text":"The bearing of the map, measured in degrees clockwise from true north."}],"url":"\/documentation\/mapsindoors\/mpcameraposition\/bearing","kind":"symbol","required":true,"type":"topic","navigatorTitle":[{"kind":"identifier","text":"bearing"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bearing"},{"text":": ","kind":"text"},{"text":"CLLocationDirection","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection"}],"title":"bearing"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"bearing"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"bearing"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"CLLocationDirection","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection"},{"kind":"text","text":" "},{"text":"bearing","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition\/title","value":"MPCameraPosition","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition\/fragments","value":[{"text":"MPCameraPosition","kind":"identifier"}],"op":"replace"},{"value":"bearing","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1bearing\/title","op":"replace"},{"value":[{"kind":"identifier","text":"bearing"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1bearing\/fragments","op":"replace"}]}]}