{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpcameraposition\/camera(target:zoom:)"]},{"paths":["\/documentation\/mapsindoors\/mpcameraposition\/camera(target:zoom:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition"]]},"sections":[],"abstract":[{"text":"Get a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition","isActive":true},{"type":"text","text":" for a particular target and zoom level."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"camera","kind":"identifier"},{"kind":"text","text":"("},{"text":"target","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"zoom","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPCameraPosition","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition","text":"MPCameraPosition","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"target","content":[{"inlineContent":[{"text":"Coordinates on Earth the camera is positioned at.","type":"text"}],"type":"paragraph"}]},{"name":"zoom","content":[{"inlineContent":[{"type":"text","text":"The desired zoom level of the camera."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"A camera position with the specified parameters."}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"This will set the bearing and viewingAngle properties of this camera to zero defaults (i.e., directly facing the Earth’s surface, with the top of the screen pointing north)."}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/camera(target:zoom:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPCameraPosition(im)cameraWithTarget:zoom:","required":true,"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cameraWithTarget:zoom:"}],"modules":[{"name":"MapsIndoors"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"kind":"text","text":"("},{"text":"target","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"text":"zoom","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPCameraPosition","text":"MPCameraPosition"},{"text":"?","kind":"text"}],"symbolKind":"method","title":"camera(target:zoom:)"},"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraPosition":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition","role":"symbol","url":"\/documentation\/mapsindoors\/mpcameraposition","navigatorTitle":[{"text":"MPCameraPosition","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPCameraPosition"}],"type":"topic","title":"MPCameraPosition","abstract":[]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraPosition/camera(target:zoom:)":{"required":true,"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/camera(target:zoom:)","role":"symbol","url":"\/documentation\/mapsindoors\/mpcameraposition\/camera(target:zoom:)","navigatorTitle":[{"kind":"identifier","text":"cameraWithTarget:zoom:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"camera"},{"text":"(","kind":"text"},{"text":"target","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"zoom","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPCameraPosition","kind":"typeIdentifier","text":"MPCameraPosition"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get a "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition","isActive":true,"type":"reference"},{"type":"text","text":" for a particular target and zoom level."}],"title":"camera(target:zoom:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"cameraWithTarget:zoom:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cameraWithTarget:zoom:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPCameraPosition","text":"id<MPCameraPosition>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"cameraWithTarget:"},{"text":"(","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") "},{"text":"target","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"zoom:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"text":") ","kind":"text"},{"text":"zoom","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"MPCameraPosition","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition\/fragments","value":[{"kind":"identifier","text":"MPCameraPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1camera(target:zoom:)\/title","value":"cameraWithTarget:zoom:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cameraWithTarget:zoom:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1camera(target:zoom:)\/fragments","op":"replace"}]}]}