{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/viewingAngle","interfaceLanguage":"swift"},"metadata":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewingAngle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"modules":[{"name":"MapsIndoors"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"viewingAngle","navigatorTitle":[{"text":"viewingAngle","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPCameraPosition(py)viewingAngle"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"viewingAngle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition"]]},"abstract":[{"text":"The angle toward the horizon measured in degrees, with 0 degrees resulting in a top-down view for a two-dimensional map.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpcameraposition\/viewingangle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpcameraposition\/viewingangle"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraPosition":{"title":"MPCameraPosition","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPCameraPosition","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPCameraPosition"}],"url":"\/documentation\/mapsindoors\/mpcameraposition"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraPosition/viewingAngle":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/viewingAngle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewingAngle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"viewingAngle","navigatorTitle":[{"text":"viewingAngle","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpcameraposition\/viewingangle","abstract":[{"text":"The angle toward the horizon measured in degrees, with 0 degrees resulting in a top-down view for a two-dimensional map.","type":"text"}],"required":true,"kind":"symbol","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"type":"image"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"viewingAngle","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"viewingAngle","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"text":"viewingAngle","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"MPCameraPosition","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition\/title"},{"value":[{"text":"MPCameraPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1viewingAngle\/title","value":"viewingAngle","op":"replace"},{"op":"replace","value":[{"text":"viewingAngle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1viewingAngle\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}