{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPropertyValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":" "},{"kind":"internalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"value","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The string value for the property"}]}]},{"name":"key","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The key for the property"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationupdate\/addpropertyvalue(_:forkey:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationupdate\/addpropertyvalue(_:forkey:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/addPropertyValue(_:forKey:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Adds a property to the location update. Some keys will be recognised as a key for a known property on the resulting "},{"type":"codeVoice","code":"MPLocation"},{"type":"text","text":". If they are not recognised or the known property only supports one value, the property will be added as a field on "},{"type":"codeVoice","code":"MPLocation.fields"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPropertyValue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"addPropertyValue(_:forKey:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPLocationUpdate(im)addPropertyValue:forKey:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"addPropertyValue:forKey:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate/addPropertyValue(_:forKey:)":{"role":"symbol","title":"addPropertyValue(_:forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPropertyValue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Adds a property to the location update. Some keys will be recognised as a key for a known property on the resulting "},{"type":"codeVoice","code":"MPLocation"},{"type":"text","text":". If they are not recognised or the known property only supports one value, the property will be added as a field on "},{"type":"codeVoice","code":"MPLocation.fields"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/addPropertyValue(_:forKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addPropertyValue:forKey:"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/addpropertyvalue(_:forkey:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate":{"role":"symbol","title":"MPLocationUpdate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationUpdate"}],"abstract":[{"type":"text","text":"Location Update \/ Builder class"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationUpdate"}],"url":"\/documentation\/mapsindoors\/mplocationupdate"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addPropertyValue:forKey:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addPropertyValue:forKey:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addPropertyValue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"value"},{"kind":"text","text":" "},{"kind":"identifier","text":"forKey:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"key"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1addPropertyValue(_:forKey:)\/title","value":"addPropertyValue:forKey:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1addPropertyValue(_:forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addPropertyValue:forKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate\/title","value":"MPLocationUpdate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate\/fragments","value":[{"kind":"identifier","text":"MPLocationUpdate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}