{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationupdate\/icon"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationupdate\/icon"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/icon","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Location icon. If not set, the location will either get an icon from the settings configured for the type of location or a default appearance that is configurable through "},{"type":"codeVoice","code":"MPMapControl"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"title":"icon","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPLocationUpdate(py)icon","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"icon"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate":{"role":"symbol","title":"MPLocationUpdate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationUpdate"}],"abstract":[{"type":"text","text":"Location Update \/ Builder class"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationUpdate"}],"url":"\/documentation\/mapsindoors\/mplocationupdate"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate/icon":{"role":"symbol","title":"icon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"abstract":[{"type":"text","text":"Location icon. If not set, the location will either get an icon from the settings configured for the type of location or a default appearance that is configurable through "},{"type":"codeVoice","code":"MPMapControl"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/icon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"icon"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/icon"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"icon"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"icon"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *"},{"kind":"identifier","text":"icon"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate\/title","value":"MPLocationUpdate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate\/fragments","value":[{"kind":"identifier","text":"MPLocationUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1icon\/title","value":"icon"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1icon\/fragments","value":[{"kind":"identifier","text":"icon"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}