{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"\/*not inherited*\/ "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":" "},{"kind":"internalParam","text":"locationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromSource"},{"kind":"text","text":" "},{"kind":"internalParam","text":"locationSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationSource","preciseIdentifier":"c:objc(pl)MPLocationSource","text":"MPLocationSource"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The updater object."}]}]},{"kind":"parameters","parameters":[{"name":"locationId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Location id. This id is expected to be unique for a given location source, but not necessarily unique across multiple location sources."}]}]},{"name":"locationSource","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The location source that is going to maintain this location."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationupdate\/init(id:fromsource:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationupdate\/init(id:fromsource:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/init(id:fromSource:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initialiser that creates a MPLocationUpdate instance based on an id and a location source."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"updateWithId:fromSource:"}],"role":"symbol","title":"init(id:fromSource:)","roleHeading":"Initializer","fragments":[{"kind":"text","text":"\/*not inherited*\/ "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationSource","preciseIdentifier":"c:objc(pl)MPLocationSource"},{"kind":"text","text":")"}],"symbolKind":"init","externalID":"c:objc(cs)MPLocationUpdate(cm)updateWithId:fromSource:","modules":[{"name":"MapsIndoors"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate":{"role":"symbol","title":"MPLocationUpdate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationUpdate"}],"abstract":[{"type":"text","text":"Location Update \/ Builder class"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationUpdate"}],"url":"\/documentation\/mapsindoors\/mplocationupdate"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate/init(id:fromSource:)":{"role":"symbol","title":"init(id:fromSource:)","fragments":[{"kind":"text","text":"\/*not inherited*\/ "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationSource","preciseIdentifier":"c:objc(pl)MPLocationSource"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialiser that creates a MPLocationUpdate instance based on an id and a location source."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/init(id:fromSource:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateWithId:fromSource:"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/init(id:fromsource:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationSource":{"role":"symbol","title":"MPLocationSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationSource"}],"abstract":[{"type":"text","text":"Location source protocol."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationSource"}],"url":"\/documentation\/mapsindoors\/mplocationsource"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"updateWithId:fromSource:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"updateWithId:fromSource:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate","preciseIdentifier":"c:objc(cs)MPLocationUpdate","text":"MPLocationUpdate"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"updateWithId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"locationId"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromSource:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MPLocationSource>","preciseIdentifier":"c:Qoobjc(pl)MPLocationSource"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"locationSource"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate\/title","value":"MPLocationUpdate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate\/fragments","value":[{"kind":"identifier","text":"MPLocationUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1init(id:fromSource:)\/title","value":"updateWithId:fromSource:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1init(id:fromSource:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"updateWithId:fromSource:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationSource\/title","value":"MPLocationSource"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationSource\/fragments","value":[{"kind":"identifier","text":"MPLocationSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}