{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentScope"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope","preciseIdentifier":"c:@E@MPDirectionsRendererContextualInfoScope","text":"MPDirectionsRendererContextualInfoScope"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfosettings\/contentscope"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfosettings\/contentscope"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoSettings\/contentScope","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Which content should be used. Default is IconAndName."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentScope"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDirectionsRendererContextualInfoScope","preciseIdentifier":"c:@E@MPDirectionsRendererContextualInfoScope"}],"title":"contentScope","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPDirectionsRendererContextualInfoSettings(py)contentScope","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"contentScope"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoSettings"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRendererContextualInfoSettings":{"role":"symbol","title":"MPDirectionsRendererContextualInfoSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRendererContextualInfoSettings"}],"abstract":[{"type":"text","text":"Settings for showing contextual info along the rendered route"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoSettings"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfosettings"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRendererContextualInfoScope":{"role":"symbol","title":"MPDirectionsRendererContextualInfoScope","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScope"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScope"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfoscope"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRendererContextualInfoSettings/contentScope":{"role":"symbol","title":"contentScope","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentScope"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDirectionsRendererContextualInfoScope","preciseIdentifier":"c:@E@MPDirectionsRendererContextualInfoScope"}],"abstract":[{"type":"text","text":"Which content should be used. Default is IconAndName."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoSettings\/contentScope","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentScope"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfosettings\/contentscope"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"contentScope"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"contentScope"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope","preciseIdentifier":"c:@E@MPDirectionsRendererContextualInfoScope","text":"MPDirectionsRendererContextualInfoScope"},{"kind":"identifier","text":"contentScope"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoSettings\/title","value":"MPDirectionsRendererContextualInfoSettings"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoSettings\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoScope\/title","value":"MPDirectionsRendererContextualInfoScope"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoScope\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScope"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoSettings~1contentScope\/title","value":"contentScope"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoSettings~1contentScope\/fragments","value":[{"kind":"identifier","text":"contentScope"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}