{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpgeopoint\/bearingto(point:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpgeopoint\/bearingto(point:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPoint"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bearingTo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"point"},{"kind":"text","text":": "},{"text":"MPGeoPoint","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPoint","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPoint"},{"kind":"text","text":") -> "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@M@MapsIndoors@objc(cs)MPGeoPoint(im)bearingToPoint:","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"bearingToPoint:","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bearingTo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"point"},{"kind":"text","text":": "},{"text":"MPGeoPoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPoint"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"symbolKind":"method","title":"bearingTo(point:)"},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPoint\/bearingTo(point:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPoint/bearingTo(point:)":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bearingTo"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"point"},{"text":": ","kind":"text"},{"text":"MPGeoPoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPoint"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"url":"\/documentation\/mapsindoors\/mpgeopoint\/bearingto(point:)","title":"bearingTo(point:)","navigatorTitle":[{"text":"bearingToPoint:","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPoint\/bearingTo(point:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPoint":{"title":"MPGeoPoint","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPGeoPoint"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPoint","navigatorTitle":[{"kind":"identifier","text":"MPGeoPoint"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/mapsindoors\/mpgeopoint"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"bearingToPoint:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bearingToPoint:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"identifier","text":"bearingToPoint:"},{"kind":"text","text":"("},{"text":"MPGeoPoint","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPoint","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPoint"},{"text":" *) ","kind":"text"},{"text":"point","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPoint~1bearingTo(point:)\/title","value":"bearingToPoint:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPoint~1bearingTo(point:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bearingToPoint:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPoint\/title","value":"MPGeoPoint"},{"value":[{"kind":"identifier","text":"MPGeoPoint"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPoint\/fragments"}]}]}