{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPoint"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"intersectsWithOther:","kind":"identifier"}],"title":"intersectsWith(other:)","symbolKind":"method","modules":[{"name":"MapsIndoors"}],"roleHeading":"Instance Method","externalID":"c:@M@MapsIndoors@objc(cs)MPGeoPoint(im)intersectsWithOther:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intersectsWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"other","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol","text":"MPGeometryProtocol"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPoint\/intersectsWith(other:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MPGeometryProtocol.intersectsWith(other:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpgeopoint\/intersectswith(other:)"]},{"paths":["\/documentation\/mapsindoors\/mpgeopoint\/intersectswith(other:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"intersectsWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"other","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol","text":"MPGeometryProtocol","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"]}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPoint":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPoint","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPGeoPoint","kind":"identifier"}],"navigatorTitle":[{"text":"MPGeoPoint","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpgeopoint","kind":"symbol","title":"MPGeoPoint","type":"topic"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPoint/intersectsWith(other:)":{"abstract":[],"kind":"symbol","title":"intersectsWith(other:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPoint\/intersectsWith(other:)","navigatorTitle":[{"text":"intersectsWithOther:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpgeopoint\/intersectswith(other:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"intersectsWith","kind":"identifier"},{"kind":"text","text":"("},{"text":"other","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol","text":"MPGeometryProtocol","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryProtocol":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"MPGeometryProtocol","kind":"identifier"}],"title":"MPGeometryProtocol","url":"\/documentation\/mapsindoors\/mpgeometryprotocol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPGeometryProtocol","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"intersectsWithOther:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"intersectsWithOther:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"intersectsWithOther:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPGeometryProtocol","text":"id<MPGeometryProtocol>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"other","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPoint\/title","value":"MPGeoPoint"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPoint\/fragments","op":"replace","value":[{"text":"MPGeoPoint","kind":"identifier"}]},{"value":"intersectsWithOther:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPoint~1intersectsWith(other:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPoint~1intersectsWith(other:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"intersectsWithOther:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol\/title","value":"MPGeometryProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol\/fragments","value":[{"text":"MPGeometryProtocol","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}