{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLocationsUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"locationUpdates"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","preciseIdentifier":"c:objc(cs)MPLocation","text":"MPLocation"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationSource","preciseIdentifier":"c:objc(pl)MPLocationSource","text":"MPLocationSource"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"locationUpdates","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Array of updated locations."}]}]},{"name":"source","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The source of the updated locations."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationsobserver\/onlocationsupdate(_:source:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationsobserver\/onlocationsupdate(_:source:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsObserver\/onLocationsUpdate(_:source:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Location update event method."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onLocationsUpdate:source:"}],"role":"symbol","title":"onLocationsUpdate(_:source:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLocationsUpdate"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationSource","preciseIdentifier":"c:objc(pl)MPLocationSource"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MPLocationsObserver(im)onLocationsUpdate:source:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsObserver"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsObserver":{"role":"symbol","title":"MPLocationsObserver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationsObserver"}],"abstract":[{"type":"text","text":"Location observer protocol."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsObserver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationsObserver"}],"url":"\/documentation\/mapsindoors\/mplocationsobserver"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationSource":{"role":"symbol","title":"MPLocationSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationSource"}],"abstract":[{"type":"text","text":"Location source protocol."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationSource"}],"url":"\/documentation\/mapsindoors\/mplocationsource"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class":{"role":"symbol","title":"MPLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"abstract":[{"type":"text","text":"This class holds the data for a single location and a marker to display the data on a map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsObserver/onLocationsUpdate(_:source:)":{"navigatorTitle":[{"kind":"identifier","text":"onLocationsUpdate:source:"}],"role":"symbol","title":"onLocationsUpdate(_:source:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLocationsUpdate"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationSource","preciseIdentifier":"c:objc(pl)MPLocationSource"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Location update event method."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsObserver\/onLocationsUpdate(_:source:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsobserver\/onlocationsupdate(_:source:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onLocationsUpdate:source:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onLocationsUpdate:source:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onLocationsUpdate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<MPLocation *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"locationUpdates"},{"kind":"text","text":" "},{"kind":"identifier","text":"source:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MPLocationSource>","preciseIdentifier":"c:Qoobjc(pl)MPLocationSource"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"source"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsObserver\/title","value":"MPLocationsObserver"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsObserver\/fragments","value":[{"kind":"identifier","text":"MPLocationsObserver"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationSource\/title","value":"MPLocationSource"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationSource\/fragments","value":[{"kind":"identifier","text":"MPLocationSource"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/title","value":"MPLocation"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/fragments","value":[{"kind":"identifier","text":"MPLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsObserver~1onLocationsUpdate(_:source:)\/title","value":"onLocationsUpdate:source:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsObserver~1onLocationsUpdate(_:source:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onLocationsUpdate:source:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}