{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLocationsDelete"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"locations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationSource","preciseIdentifier":"c:objc(pl)MPLocationSource","text":"MPLocationSource"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"locations","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Array of deleted location ids."}]}]},{"name":"source","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The source of the deleted locations."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationsobserver\/onlocationsdelete(_:source:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationsobserver\/onlocationsdelete(_:source:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsObserver\/onLocationsDelete(_:source:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Location delete event method."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onLocationsDelete:source:"}],"role":"symbol","title":"onLocationsDelete(_:source:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLocationsDelete"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationSource","preciseIdentifier":"c:objc(pl)MPLocationSource"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MPLocationsObserver(im)onLocationsDelete:source:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsObserver"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsObserver":{"role":"symbol","title":"MPLocationsObserver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationsObserver"}],"abstract":[{"type":"text","text":"Location observer protocol."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsObserver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationsObserver"}],"url":"\/documentation\/mapsindoors\/mplocationsobserver"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsObserver/onLocationsDelete(_:source:)":{"navigatorTitle":[{"kind":"identifier","text":"onLocationsDelete:source:"}],"role":"symbol","title":"onLocationsDelete(_:source:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLocationsDelete"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationSource","preciseIdentifier":"c:objc(pl)MPLocationSource"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Location delete event method."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsObserver\/onLocationsDelete(_:source:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsobserver\/onlocationsdelete(_:source:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationSource":{"role":"symbol","title":"MPLocationSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationSource"}],"abstract":[{"type":"text","text":"Location source protocol."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationSource"}],"url":"\/documentation\/mapsindoors\/mplocationsource"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onLocationsDelete:source:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onLocationsDelete:source:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onLocationsDelete:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"locations"},{"kind":"text","text":" "},{"kind":"identifier","text":"source:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MPLocationSource>","preciseIdentifier":"c:Qoobjc(pl)MPLocationSource"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"source"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsObserver\/title","value":"MPLocationsObserver"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsObserver\/fragments","value":[{"kind":"identifier","text":"MPLocationsObserver"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsObserver~1onLocationsDelete(_:source:)\/title","value":"onLocationsDelete:source:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsObserver~1onLocationsDelete(_:source:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onLocationsDelete:source:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationSource\/title","value":"MPLocationSource"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationSource\/fragments","value":[{"kind":"identifier","text":"MPLocationSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}