{"abstract":[{"type":"text","text":"Status change event method."}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"onStatusChange:source:","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"roleHeading":"Instance Method","title":"onStatusChange(_:source:)","externalID":"c:@M@MapsIndoors@objc(pl)MPLocationsObserver(im)onStatusChange:source:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onStatusChange","kind":"identifier"},{"kind":"text","text":"("},{"text":"MPLocationSourceStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPLocationSourceStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"source"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationSource","text":"MPLocationSource"},{"text":")","kind":"text"}],"required":true},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver\/onStatusChange(_:source:)"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onStatusChange","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"status"},{"kind":"text","text":": "},{"text":"MPLocationSourceStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPLocationSourceStatus","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus"},{"kind":"text","text":", "},{"text":"source","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationSource","text":"MPLocationSource"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"name":"status","content":[{"inlineContent":[{"type":"text","text":"The new status of the location source."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The location source changing status."}],"type":"paragraph"}],"name":"source"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationsobserver\/onstatuschange(_:source:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationsobserver\/onstatuschange(_:source:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSourceStatus":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"MPLocationSourceStatus","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLocationSourceStatus","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mplocationsourcestatus","title":"MPLocationSourceStatus","role":"symbol","abstract":[]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSource":{"title":"MPLocationSource","navigatorTitle":[{"kind":"identifier","text":"MPLocationSource"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPLocationSource","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mplocationsource","abstract":[{"type":"text","text":"Location source protocol."}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationsObserver":{"title":"MPLocationsObserver","abstract":[{"type":"text","text":"Location observer protocol."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPLocationsObserver","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MPLocationsObserver","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mplocationsobserver","role":"symbol"},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"identifier":"MapsPeopleWhite.png","type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationsObserver/onStatusChange(_:source:)":{"abstract":[{"text":"Status change event method.","type":"text"}],"type":"topic","title":"onStatusChange(_:source:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onStatusChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MPLocationSourceStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPLocationSourceStatus"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationSource","kind":"typeIdentifier","text":"MPLocationSource"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver\/onStatusChange(_:source:)","url":"\/documentation\/mapsindoors\/mplocationsobserver\/onstatuschange(_:source:)","required":true,"role":"symbol","navigatorTitle":[{"text":"onStatusChange:source:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"onStatusChange:source:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"onStatusChange:source:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onStatusChange:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@E@MPLocationSourceStatus","text":"MPLocationSourceStatus","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"status","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"source:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPLocationSource","text":"id<MPLocationSource>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"source"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus\/title","value":"MPLocationSourceStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus\/fragments","value":[{"text":"MPLocationSourceStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource\/title","value":"MPLocationSource"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPLocationSource"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationsObserver\/title","op":"replace","value":"MPLocationsObserver"},{"value":[{"kind":"identifier","text":"MPLocationsObserver"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationsObserver\/fragments"},{"value":"onStatusChange:source:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationsObserver~1onStatusChange(_:source:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onStatusChange:source:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationsObserver~1onStatusChange(_:source:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}