{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProviderDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProviderDelegate\/onPositionUpdate(position:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPositionUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"position"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult","text":"MPPositionResult","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPositionResult","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The position as estimated or calculated by a "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","isActive":true},{"type":"text","text":"."}]}],"name":"position"}],"kind":"parameters"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/mapsindoors\/mppositionproviderdelegate\/onpositionupdate(position:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppositionproviderdelegate\/onpositionupdate(position:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPositionUpdate","kind":"identifier"},{"kind":"text","text":"("},{"text":"position","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPositionResult","text":"MPPositionResult"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onPositionUpdateWithPosition:","kind":"identifier"}],"role":"symbol","modules":[{"name":"MapsIndoors"}],"title":"onPositionUpdate(position:)","externalID":"c:@M@MapsIndoors@objc(pl)MPPositionProviderDelegate(im)onPositionUpdateWithPosition:","roleHeading":"Instance Method","required":true},"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"},{"type":"text","text":" is dependent on this method to show the current user position on the"},{"text":" ","type":"text"},{"text":"currently showing map. If your app needs to be notified about each new user position, you should create","type":"text"},{"text":" ","type":"text"},{"text":"a class conforming to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate"},{"text":" and set that as the ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/delegate","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"User position updates will then be available via the"},{"type":"text","text":" "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/onPositionUpdate(position:)","isActive":true,"type":"reference"},{"text":" function that you implement in your class.","type":"text"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"abstract":[{"type":"text","text":"This is the control object for the visual representation of the MapsIndoors SDK."}],"url":"\/documentation\/mapsindoors\/mpmapcontrol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPMapControl"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"type":"topic","kind":"symbol","title":"MPMapControl","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPMapControlDelegate","kind":"identifier"}],"abstract":[{"text":"Delegate protocol specification to react to the events that ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true},{"text":" emits.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpmapcontroldelegate","title":"MPMapControlDelegate","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPMapControlDelegate"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionProvider":{"url":"\/documentation\/mapsindoors\/mppositionprovider","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProvider"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPPositionProvider"}],"title":"MPPositionProvider","abstract":[{"type":"text","text":"Protocol specifying how an indoor positioning provider should be implemented if the users location is to be exposed to "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true},{"type":"text","text":"."}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionProviderDelegate/onPositionUpdate(position:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProviderDelegate\/onPositionUpdate(position:)","url":"\/documentation\/mapsindoors\/mppositionproviderdelegate\/onpositionupdate(position:)","kind":"symbol","role":"symbol","type":"topic","title":"onPositionUpdate(position:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"onPositionUpdateWithPosition:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onPositionUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPPositionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPositionResult"},{"text":")","kind":"text"}],"abstract":[{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","type":"reference"},{"type":"text","text":" is dependent on this method to show the current user position on the"},{"text":" ","type":"text"},{"type":"text","text":"currently showing map. If your app needs to be notified about each new user position, you should create"},{"type":"text","text":" "},{"type":"text","text":"a class conforming to "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate","isActive":true},{"type":"text","text":" and set that as the "},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/delegate","type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"User position updates will then be available via the"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/onPositionUpdate(position:)","type":"reference"},{"type":"text","text":" function that you implement in your class."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate/onPositionUpdate(position:)":{"url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/onpositionupdate(position:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/onPositionUpdate(position:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPositionUpdate"},{"text":"(","kind":"text"},{"text":"position","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPositionResult","text":"MPPositionResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","required":true,"title":"onPositionUpdate(position:)","abstract":[{"type":"text","text":"Called when "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true,"type":"reference"},{"type":"text","text":" receives a new user position from the active "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This is the method you should implement if your app needs to be notified about each new user position."}],"navigatorTitle":[{"text":"onPositionUpdate:","kind":"identifier"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionResult":{"role":"symbol","abstract":[{"text":"Instances of this class holds a Position result returned by a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","isActive":true},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mppositionresult","navigatorTitle":[{"text":"MPPositionResult","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPPositionResult"}],"title":"MPPositionResult"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/delegate":{"role":"symbol","abstract":[{"text":"Listen to events.","type":"text"}],"kind":"symbol","required":true,"url":"\/documentation\/mapsindoors\/mpmapcontrol\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/delegate","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPMapControlDelegate","text":"MPMapControlDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"delegate"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionProviderDelegate":{"role":"symbol","abstract":[{"type":"text","text":"Protocol specifying how an indoor positioning provider delegate should be implemented as the receiver of user positions."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mppositionproviderdelegate","navigatorTitle":[{"text":"MPPositionProviderDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProviderDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPPositionProviderDelegate"}],"title":"MPPositionProviderDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"onPositionUpdateWithPosition:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onPositionUpdateWithPosition:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onPositionUpdateWithPosition:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult","text":"MPPositionResult","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPositionResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"position","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"kind":"identifier","text":"MPMapControl"}],"op":"replace"},{"value":"MPMapControlDelegate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/title"},{"value":[{"text":"MPMapControlDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/fragments"},{"op":"replace","value":"MPPositionProvider","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MPPositionProvider"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProviderDelegate~1onPositionUpdate(position:)\/title","value":"onPositionUpdateWithPosition:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onPositionUpdateWithPosition:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProviderDelegate~1onPositionUpdate(position:)\/fragments"},{"op":"replace","value":"onPositionUpdate:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1onPositionUpdate(position:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onPositionUpdate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1onPositionUpdate(position:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult\/title","value":"MPPositionResult"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult\/fragments","value":[{"text":"MPPositionResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1delegate\/title","value":"delegate","op":"replace"},{"op":"replace","value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1delegate\/fragments"},{"op":"replace","value":"MPPositionProviderDelegate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProviderDelegate\/title"},{"value":[{"text":"MPPositionProviderDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProviderDelegate\/fragments"}]}]}