{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationSourceStatus","preciseIdentifier":"c:@E@MPLocationSourceStatus","text":"MPLocationSourceStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationsource\/status()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationsource\/status()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationSource\/status()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"status"}],"role":"symbol","title":"status()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MPLocationSourceStatus","preciseIdentifier":"c:@E@MPLocationSourceStatus"}],"symbolKind":"method","externalID":"c:objc(pl)MPLocationSource(im)status","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationSource"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationSourceStatus":{"role":"symbol","title":"MPLocationSourceStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationSourceStatus"}],"abstract":[{"type":"text","text":"Available      Available status. The location source is expected to provide data but may not have data from all data sources yet;"},{"type":"text","text":" "},{"type":"text","text":"Unavailable    unavailable but expected to provide data under normal circumstances;"},{"type":"text","text":" "},{"type":"text","text":"Initialising   processing and expected to provide data when initialised;"},{"type":"text","text":" "},{"type":"text","text":"Inactive       intentionally inactive and not expected to provide data;"},{"type":"text","text":" "},{"type":"text","text":"Complete       The location service is ready to be used;"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationSourceStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationSourceStatus"}],"url":"\/documentation\/mapsindoors\/mplocationsourcestatus"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationSource":{"role":"symbol","title":"MPLocationSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationSource"}],"abstract":[{"type":"text","text":"Location source protocol."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationSource"}],"url":"\/documentation\/mapsindoors\/mplocationsource"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationSource/status()":{"navigatorTitle":[{"kind":"identifier","text":"status"}],"role":"symbol","title":"status()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MPLocationSourceStatus","preciseIdentifier":"c:@E@MPLocationSourceStatus"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationSource\/status()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsource\/status()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"status"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"status"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationSourceStatus","preciseIdentifier":"c:@E@MPLocationSourceStatus","text":"MPLocationSourceStatus"},{"kind":"text","text":") "},{"kind":"identifier","text":"status"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationSourceStatus\/title","value":"MPLocationSourceStatus"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationSourceStatus\/fragments","value":[{"kind":"identifier","text":"MPLocationSourceStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationSource\/title","value":"MPLocationSource"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationSource\/fragments","value":[{"kind":"identifier","text":"MPLocationSource"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationSource~1status()\/title","value":"status"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationSource~1status()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"status"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}