{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"MapsIndoors"}],"roleHeading":"Instance Property","externalID":"c:@M@MapsIndoors@objc(cs)MPRouteSegmentPath(py)legIndex","title":"legIndex","navigatorTitle":[{"kind":"identifier","text":"legIndex"}],"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"legIndex","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"legIndex"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath"]]},"variants":[{"paths":["\/documentation\/mapsindoors\/mproutesegmentpath\/legindex"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mproutesegmentpath\/legindex"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Leg index.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath\/legIndex"},"references":{"MapsPeopleWhite.png":{"alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteSegmentPath/legIndex":{"abstract":[{"text":"Leg index.","type":"text"}],"title":"legIndex","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"legIndex"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"legIndex","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath\/legIndex","type":"topic","role":"symbol","url":"\/documentation\/mapsindoors\/mproutesegmentpath\/legindex"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteSegmentPath":{"navigatorTitle":[{"text":"MPRouteSegmentPath","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mproutesegmentpath","kind":"symbol","role":"symbol","title":"MPRouteSegmentPath","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteSegmentPath"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"legIndex"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"legIndex"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"text":"legIndex","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"legIndex","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteSegmentPath~1legIndex\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteSegmentPath~1legIndex\/fragments","value":[{"text":"legIndex","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteSegmentPath\/title","op":"replace","value":"MPRouteSegmentPath"},{"value":[{"text":"MPRouteSegmentPath","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteSegmentPath\/fragments"}]}]}