{"abstract":[{"type":"text","text":"Available and expected to provide data."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"available","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/mapsindoors\/mplocationsourcestatus\/available"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mplocationsourcestatus\/available"]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"MPLocationSourceStatusAvailable","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@MapsIndoors@E@MPLocationSourceStatus@MPLocationSourceStatusAvailable","modules":[{"name":"MapsIndoors"}],"symbolKind":"case","title":"MPLocationSourceStatus.available","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"available"}]},"sections":[],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/available","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSourceStatus":{"navigatorTitle":[{"kind":"identifier","text":"MPLocationSourceStatus"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLocationSourceStatus","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/mapsindoors\/mplocationsourcestatus","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus","title":"MPLocationSourceStatus"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSourceStatus/available":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"available","kind":"identifier"}],"title":"MPLocationSourceStatus.available","url":"\/documentation\/mapsindoors\/mplocationsourcestatus\/available","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/available","role":"symbol","navigatorTitle":[{"text":"MPLocationSourceStatusAvailable","kind":"identifier"}],"abstract":[{"type":"text","text":"Available and expected to provide data."}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"MPLocationSourceStatusAvailable","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"MPLocationSourceStatusAvailable","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"MPLocationSourceStatusAvailable","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus\/title","value":"MPLocationSourceStatus"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus\/fragments","value":[{"kind":"identifier","text":"MPLocationSourceStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus~1available\/title","value":"MPLocationSourceStatusAvailable","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MPLocationSourceStatusAvailable"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus~1available\/fragments"}]}]}