{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inactive"}]}]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/inactive","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MapsIndoors"}],"roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"text":"MPLocationSourceStatusInactive","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@E@MPLocationSourceStatus@MPLocationSourceStatusInactive","title":"MPLocationSourceStatus.inactive","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inactive","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus"]]},"abstract":[{"type":"text","text":"Intentionally inactive and not expected to provide data."}],"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationsourcestatus\/inactive"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationsourcestatus\/inactive"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSourceStatus/inactive":{"url":"\/documentation\/mapsindoors\/mplocationsourcestatus\/inactive","kind":"symbol","navigatorTitle":[{"text":"MPLocationSourceStatusInactive","kind":"identifier"}],"abstract":[{"text":"Intentionally inactive and not expected to provide data.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/inactive","title":"MPLocationSourceStatus.inactive","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inactive"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSourceStatus":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"MPLocationSourceStatus","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLocationSourceStatus","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mplocationsourcestatus","title":"MPLocationSourceStatus","role":"symbol","abstract":[]},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","alt":null,"type":"image"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MPLocationSourceStatusInactive"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"MPLocationSourceStatusInactive","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MPLocationSourceStatusInactive","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus~1inactive\/title","op":"replace","value":"MPLocationSourceStatusInactive"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus~1inactive\/fragments","value":[{"kind":"identifier","text":"MPLocationSourceStatusInactive"}],"op":"replace"},{"op":"replace","value":"MPLocationSourceStatus","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus\/fragments","value":[{"text":"MPLocationSourceStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}