{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unavailable","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Unavailable but expected to provide data under normal circumstances.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus"]]},"metadata":{"externalID":"c:@M@MapsIndoors@E@MPLocationSourceStatus@MPLocationSourceStatusUnavailable","roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unavailable","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"MPLocationSourceStatusUnavailable","kind":"identifier"}],"title":"MPLocationSourceStatus.unavailable"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mplocationsourcestatus\/unavailable"]},{"paths":["\/documentation\/mapsindoors\/mplocationsourcestatus\/unavailable"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/unavailable","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSourceStatus/unavailable":{"navigatorTitle":[{"text":"MPLocationSourceStatusUnavailable","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unavailable"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Unavailable but expected to provide data under normal circumstances."}],"url":"\/documentation\/mapsindoors\/mplocationsourcestatus\/unavailable","title":"MPLocationSourceStatus.unavailable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/unavailable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSourceStatus":{"navigatorTitle":[{"kind":"identifier","text":"MPLocationSourceStatus"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLocationSourceStatus","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/mapsindoors\/mplocationsourcestatus","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus","title":"MPLocationSourceStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MPLocationSourceStatusUnavailable","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"MPLocationSourceStatusUnavailable","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MPLocationSourceStatusUnavailable","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus~1unavailable\/title","value":"MPLocationSourceStatusUnavailable","op":"replace"},{"value":[{"text":"MPLocationSourceStatusUnavailable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus~1unavailable\/fragments"},{"value":"MPLocationSourceStatus","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus\/fragments","value":[{"text":"MPLocationSourceStatus","kind":"identifier"}]}]}]}