{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds\/expandWith(coord:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"expandWith","kind":"identifier"},{"kind":"text","text":"("},{"text":"coord","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"text":"MPGeoBounds","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds"}],"modules":[{"name":"MapsIndoors"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","title":"expandWith(coord:)","navigatorTitle":[{"kind":"identifier","text":"expandWithCoord:"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPGeoBounds(im)expandWithCoord:"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"expandWith"},{"text":"(","kind":"text"},{"text":"coord","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds","kind":"typeIdentifier","text":"MPGeoBounds"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds"]]},"variants":[{"paths":["\/documentation\/mapsindoors\/mpgeobounds\/expandwith(coord:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpgeobounds\/expandwith(coord:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoBounds":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPGeoBounds","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MPGeoBounds","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpgeobounds","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds","title":"MPGeoBounds","abstract":[],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoBounds/expandWith(coord:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds\/expandWith(coord:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"expandWith","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"coord"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"MPGeoBounds","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","kind":"typeIdentifier"}],"title":"expandWith(coord:)","kind":"symbol","abstract":[],"url":"\/documentation\/mapsindoors\/mpgeobounds\/expandwith(coord:)","navigatorTitle":[{"kind":"identifier","text":"expandWithCoord:"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null,"type":"image","identifier":"MapsPeopleWhite.png"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"expandWithCoord:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"expandWithCoord:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds","text":"MPGeoBounds","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"expandWithCoord:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":") ","kind":"text"},{"text":"coord","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MPGeoBounds","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoBounds\/title"},{"op":"replace","value":[{"text":"MPGeoBounds","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoBounds\/fragments"},{"value":"expandWithCoord:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoBounds~1expandWith(coord:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoBounds~1expandWith(coord:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"expandWithCoord:","kind":"identifier"}]}]}]}