{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds\/expandWith(other:)"},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expandWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"other","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPGeometryProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","text":"MPGeoBounds"}],"navigatorTitle":[{"kind":"identifier","text":"expandWithOther:"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPGeoBounds(im)expandWithOther:","role":"symbol","modules":[{"name":"MapsIndoors"}],"title":"expandWith(other:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"expandWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"other","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPGeometryProtocol","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds","text":"MPGeoBounds","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpgeobounds\/expandwith(other:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpgeobounds\/expandwith(other:)"]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoBounds":{"url":"\/documentation\/mapsindoors\/mpgeobounds","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds","navigatorTitle":[{"text":"MPGeoBounds","kind":"identifier"}],"title":"MPGeoBounds","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPGeoBounds","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryProtocol":{"url":"\/documentation\/mapsindoors\/mpgeometryprotocol","kind":"symbol","navigatorTitle":[{"text":"MPGeometryProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol","title":"MPGeometryProtocol","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeometryProtocol"}]},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoBounds/expandWith(other:)":{"role":"symbol","navigatorTitle":[{"text":"expandWithOther:","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpgeobounds\/expandwith(other:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expandWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"other","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPGeometryProtocol","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol"},{"kind":"text","text":") -> "},{"text":"MPGeoBounds","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds\/expandWith(other:)","abstract":[],"title":"expandWith(other:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"expandWithOther:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"expandWithOther:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"MPGeoBounds","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"expandWithOther:"},{"kind":"text","text":"("},{"text":"id<MPGeometryProtocol>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPGeometryProtocol"},{"text":" *) ","kind":"text"},{"text":"other","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoBounds\/title","op":"replace","value":"MPGeoBounds"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoBounds\/fragments","value":[{"text":"MPGeoBounds","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol\/title","value":"MPGeometryProtocol"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol\/fragments","op":"replace","value":[{"text":"MPGeometryProtocol","kind":"identifier"}]},{"value":"expandWithOther:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoBounds~1expandWith(other:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoBounds~1expandWith(other:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"expandWithOther:","kind":"identifier"}],"op":"replace"}]}]}