{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"intersectsWith"},{"kind":"text","text":"("},{"text":"other","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol","text":"MPGeometryProtocol","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds\/intersectsWith(other:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mapsindoors\/mpgeobounds\/intersectswith(other:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpgeobounds\/intersectswith(other:)"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"intersectsWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"other","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol","text":"MPGeometryProtocol","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPGeoBounds(im)intersectsWithOther:","roleHeading":"Instance Method","modules":[{"name":"MapsIndoors"}],"role":"symbol","navigatorTitle":[{"text":"intersectsWithOther:","kind":"identifier"}],"symbolKind":"method","title":"intersectsWith(other:)"},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MPGeometryProtocol.intersectsWith(other:)"},{"type":"text","text":"."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","alt":null,"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryProtocol":{"url":"\/documentation\/mapsindoors\/mpgeometryprotocol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPGeometryProtocol","kind":"identifier"}],"title":"MPGeometryProtocol","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPGeometryProtocol"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoBounds/intersectsWith(other:)":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds\/intersectsWith(other:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"intersectsWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"other","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol","text":"MPGeometryProtocol","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"intersectsWith(other:)","url":"\/documentation\/mapsindoors\/mpgeobounds\/intersectswith(other:)","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"intersectsWithOther:","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoBounds":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds","url":"\/documentation\/mapsindoors\/mpgeobounds","navigatorTitle":[{"kind":"identifier","text":"MPGeoBounds"}],"abstract":[],"title":"MPGeoBounds","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeoBounds"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"intersectsWithOther:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"intersectsWithOther:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"intersectsWithOther:"},{"text":"(","kind":"text"},{"text":"id<MPGeometryProtocol>","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPGeometryProtocol","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"other","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MPGeometryProtocol","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MPGeometryProtocol"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoBounds~1intersectsWith(other:)\/title","value":"intersectsWithOther:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoBounds~1intersectsWith(other:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"intersectsWithOther:","kind":"identifier"}]},{"op":"replace","value":"MPGeoBounds","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoBounds\/title"},{"value":[{"kind":"identifier","text":"MPGeoBounds"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoBounds\/fragments","op":"replace"}]}]}