{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribe"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"topic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria","text":"MPLiveTopicCriteria"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplivedatamanager\/subscribe(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplivedatamanager\/subscribe(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/subscribe(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Subscribe to Live Updates with a given Topic Criteria. If no previous subscriptions have been made, the Live Data Manager will first connect to the Live Update remote services."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribe"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"},{"kind":"text","text":")"}],"title":"subscribe(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPLiveDataManager(im)subscribe:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"subscribe:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManager":{"role":"symbol","title":"MPLiveDataManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManager"}],"abstract":[{"type":"text","text":"The Live Data Manager class is the central class for managing Live Update subscriptions."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManager"}],"url":"\/documentation\/mapsindoors\/mplivedatamanager"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveTopicCriteria":{"role":"symbol","title":"MPLiveTopicCriteria","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveTopicCriteria"}],"abstract":[{"type":"text","text":"Live Topic Criteria model used for subscriptions to Live Updates using MPLiveDataManager."},{"type":"text","text":" "},{"type":"text","text":"A Live Topic Criteria is hierarchical in the way it is defined, and its relation to MapsIndoors data is derivable by its 7 components: Dataset, Venue, Building, Floor, Room, Location and Domain Type."},{"type":"text","text":" "},{"type":"text","text":"All properties can be left out but datasetId will then default to the currently active dataset."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveTopicCriteria"}],"url":"\/documentation\/mapsindoors\/mplivetopiccriteria"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManager/subscribe(_:)":{"role":"symbol","title":"subscribe(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribe"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Subscribe to Live Updates with a given Topic Criteria. If no previous subscriptions have been made, the Live Data Manager will first connect to the Live Update remote services."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/subscribe(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subscribe:"}],"url":"\/documentation\/mapsindoors\/mplivedatamanager\/subscribe(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"subscribe:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"subscribe:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"subscribe:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria","text":"MPLiveTopicCriteria"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"topic"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager\/title","value":"MPLiveDataManager"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManager"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria\/title","value":"MPLiveTopicCriteria"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveTopicCriteria\/fragments","value":[{"kind":"identifier","text":"MPLiveTopicCriteria"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1subscribe(_:)\/title","value":"subscribe:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1subscribe(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"subscribe:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}