{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateLiveDataInfo"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplivedatamanager\/updatelivedatainfo()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplivedatamanager\/updatelivedatainfo()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/updateLiveDataInfo()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Update Live Data information, including list of active Domain Types for the current dataset."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateLiveDataInfo"},{"kind":"text","text":"()"}],"title":"updateLiveDataInfo()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPLiveDataManager(im)updateLiveDataInfo","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"updateLiveDataInfo"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManager":{"role":"symbol","title":"MPLiveDataManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManager"}],"abstract":[{"type":"text","text":"The Live Data Manager class is the central class for managing Live Update subscriptions."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManager"}],"url":"\/documentation\/mapsindoors\/mplivedatamanager"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManager/updateLiveDataInfo()":{"role":"symbol","title":"updateLiveDataInfo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateLiveDataInfo"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Update Live Data information, including list of active Domain Types for the current dataset."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManager\/updateLiveDataInfo()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateLiveDataInfo"}],"url":"\/documentation\/mapsindoors\/mplivedatamanager\/updatelivedatainfo()"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateLiveDataInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateLiveDataInfo"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateLiveDataInfo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager\/title","value":"MPLiveDataManager"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManager"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1updateLiveDataInfo()\/title","value":"updateLiveDataInfo"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManager~1updateLiveDataInfo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateLiveDataInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}