{"kind":"symbol","variants":[{"paths":["\/documentation\/mapsindoors\/mppoint\/init(latitude:longitude:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppoint\/init(latitude:longitude:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"required","kind":"keyword"},{"kind":"text","text":" "},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"latitude"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"longitude","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Regular geographic point geometry initialization."}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint\/init(latitude:longitude:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"longitude","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithLatitude:longitude:","kind":"identifier"}],"role":"symbol","modules":[{"name":"MapsIndoors"}],"title":"init(latitude:longitude:)","externalID":"c:@M@MapsIndoors@objc(cs)MPPoint(im)initWithLatitude:longitude:","roleHeading":"Initializer","symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPoint":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"MPPoint","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPoint"}],"type":"topic","title":"MPPoint","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint","url":"\/documentation\/mapsindoors\/mppoint"},"MapsPeopleWhite.png":{"alt":null,"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPoint/init(latitude:longitude:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"longitude"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/mapsindoors\/mppoint\/init(latitude:longitude:)","kind":"symbol","title":"init(latitude:longitude:)","abstract":[{"text":"Regular geographic point geometry initialization.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLatitude:longitude:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint\/init(latitude:longitude:)","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithLatitude:longitude:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithLatitude:longitude:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithLatitude:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"latitude"},{"kind":"text","text":" "},{"kind":"identifier","text":"longitude:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"longitude"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPoint\/title","value":"MPPoint","op":"replace"},{"value":[{"kind":"identifier","text":"MPPoint"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPoint\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPoint~1init(latitude:longitude:)\/title","value":"initWithLatitude:longitude:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPoint~1init(latitude:longitude:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLatitude:longitude:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}