{"abstract":[{"type":"text","text":"Arrival stop contains information about the arrival stop\/station for this part of the trip."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"required":true,"roleHeading":"Instance Property","title":"arrival_stop","navigatorTitle":[{"kind":"identifier","text":"arrival_stop"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPTransitDetails(py)arrival_stop","symbolKind":"property","modules":[{"name":"MapsIndoors"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"arrival_stop"},{"kind":"text","text":": "},{"text":"MPTransitStop","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitStop","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/mapsindoors\/mptransitdetails\/arrival_stop"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mptransitdetails\/arrival_stop"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"arrival_stop","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitStop","text":"MPTransitStop","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitStop","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/arrival_stop"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails"]]},"references":{"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null,"identifier":"MapsPeopleWhite.png","type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitDetails":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPTransitDetails","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mptransitdetails","title":"MPTransitDetails","navigatorTitle":[{"kind":"identifier","text":"MPTransitDetails"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails","role":"symbol","kind":"symbol","abstract":[{"text":"Transit details information.","type":"text"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitDetails/arrival_stop":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"arrival_stop","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitStop","kind":"typeIdentifier","text":"MPTransitStop"},{"kind":"text","text":"?"}],"url":"\/documentation\/mapsindoors\/mptransitdetails\/arrival_stop","title":"arrival_stop","required":true,"navigatorTitle":[{"text":"arrival_stop","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/arrival_stop","role":"symbol","abstract":[{"type":"text","text":"Arrival stop contains information about the arrival stop\/station for this part of the trip."}],"kind":"symbol","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitStop":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPTransitStop"}],"url":"\/documentation\/mapsindoors\/mptransitstop","title":"MPTransitStop","navigatorTitle":[{"kind":"identifier","text":"MPTransitStop"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitStop","role":"symbol","kind":"symbol","abstract":[{"text":"Transit stop information.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"arrival_stop","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"arrival_stop"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPTransitStop","text":"id<MPTransitStop>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"arrival_stop","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails\/title","value":"MPTransitDetails"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails\/fragments","value":[{"kind":"identifier","text":"MPTransitDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1arrival_stop\/title","op":"replace","value":"arrival_stop"},{"op":"replace","value":[{"kind":"identifier","text":"arrival_stop"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1arrival_stop\/fragments"},{"value":"MPTransitStop","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitStop\/title"},{"value":[{"text":"MPTransitStop","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitStop\/fragments"}]}]}