{"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"arrival_time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPTransitTime","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitTime"},{"kind":"text","text":"?"}],"modules":[{"name":"MapsIndoors"}],"role":"symbol","required":true,"title":"arrival_time","symbolKind":"property","externalID":"c:@M@MapsIndoors@objc(pl)MPTransitDetails(py)arrival_time","roleHeading":"Instance Property","navigatorTitle":[{"text":"arrival_time","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/arrival_time"},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mptransitdetails\/arrival_time"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mptransitdetails\/arrival_time"]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Contains the arrival times for this leg of the journey."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"arrival_time"},{"text":": ","kind":"text"},{"text":"MPTransitTime","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitTime","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitTime"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitTime":{"abstract":[{"type":"text","text":"Transit time information."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitTime","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPTransitTime","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mptransittime","title":"MPTransitTime","navigatorTitle":[{"text":"MPTransitTime","kind":"identifier"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitDetails":{"url":"\/documentation\/mapsindoors\/mptransitdetails","navigatorTitle":[{"text":"MPTransitDetails","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Transit details information."}],"role":"symbol","title":"MPTransitDetails","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPTransitDetails"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"MapsPeopleWhite.png":{"alt":null,"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitDetails/arrival_time":{"abstract":[{"text":"Contains the arrival times for this leg of the journey.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/arrival_time","required":true,"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"arrival_time"},{"kind":"text","text":": "},{"text":"MPTransitTime","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitTime"},{"kind":"text","text":"?"}],"url":"\/documentation\/mapsindoors\/mptransitdetails\/arrival_time","title":"arrival_time","navigatorTitle":[{"kind":"identifier","text":"arrival_time"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"arrival_time","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"arrival_time","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<MPTransitTime>","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPTransitTime"},{"kind":"text","text":" * "},{"kind":"identifier","text":"arrival_time"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MPTransitTime","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitTime\/title","op":"replace"},{"value":[{"text":"MPTransitTime","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitTime\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails\/title","value":"MPTransitDetails"},{"value":[{"kind":"identifier","text":"MPTransitDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails\/fragments"},{"value":"arrival_time","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1arrival_time\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1arrival_time\/fragments","value":[{"kind":"identifier","text":"arrival_time"}],"op":"replace"}]}]}