{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mptransitdetails\/departure_time"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mptransitdetails\/departure_time"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"departure_time","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitTime","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitTime","kind":"typeIdentifier","text":"MPTransitTime"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Contains the departure times for this leg of the journey.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails"]]},"metadata":{"title":"departure_time","roleHeading":"Instance Property","navigatorTitle":[{"text":"departure_time","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPTransitDetails(py)departure_time","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"departure_time"},{"kind":"text","text":": "},{"text":"MPTransitTime","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitTime","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"required":true,"modules":[{"name":"MapsIndoors"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/departure_time","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitTime":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPTransitTime","kind":"identifier"}],"navigatorTitle":[{"text":"MPTransitTime","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mptransittime","abstract":[{"type":"text","text":"Transit time information."}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitTime","kind":"symbol","title":"MPTransitTime"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitDetails":{"type":"topic","url":"\/documentation\/mapsindoors\/mptransitdetails","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPTransitDetails","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPTransitDetails"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails","abstract":[{"type":"text","text":"Transit details information."}],"role":"symbol","title":"MPTransitDetails"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitDetails/departure_time":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/departure_time","abstract":[{"text":"Contains the departure times for this leg of the journey.","type":"text"}],"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"departure_time","kind":"identifier"},{"kind":"text","text":": "},{"text":"MPTransitTime","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitTime"},{"text":"?","kind":"text"}],"url":"\/documentation\/mapsindoors\/mptransitdetails\/departure_time","kind":"symbol","title":"departure_time","navigatorTitle":[{"text":"departure_time","kind":"identifier"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"departure_time","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"departure_time","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"id<MPTransitTime>","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPTransitTime"},{"kind":"text","text":" * "},{"text":"departure_time","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitTime\/title","op":"replace","value":"MPTransitTime"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitTime\/fragments","value":[{"text":"MPTransitTime","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails\/title","value":"MPTransitDetails"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails\/fragments","value":[{"kind":"identifier","text":"MPTransitDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1departure_time\/title","value":"departure_time","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"departure_time"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1departure_time\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}