{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floorId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationcoordinate3d\/floorid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationcoordinate3d\/floorid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D\/floorId","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floorId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"floorId","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@S@MPLocationCoordinate3D@FI@floorId","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"floorId"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationCoordinate3D/floorId":{"role":"symbol","title":"floorId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floorId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D\/floorId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floorId"}],"url":"\/documentation\/mapsindoors\/mplocationcoordinate3d\/floorid"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationCoordinate3D":{"role":"symbol","title":"MPLocationCoordinate3D","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationCoordinate3D"}],"abstract":[{"type":"text","text":"A structure that contains a coordinate in 3D space: latitude\/longitude and floor."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationCoordinate3D"}],"url":"\/documentation\/mapsindoors\/mplocationcoordinate3d"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"floorId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"floorId"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"floorId"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationCoordinate3D~1floorId\/title","value":"floorId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationCoordinate3D~1floorId\/fragments","value":[{"kind":"identifier","text":"floorId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationCoordinate3D\/title","value":"MPLocationCoordinate3D"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationCoordinate3D\/fragments","value":[{"kind":"identifier","text":"MPLocationCoordinate3D"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}