{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"mapsIndoorsSolutionId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"solutionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"googleApiKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mproutingprovider\/init(mapsindoorssolutionid:googleapikey:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mproutingprovider\/init(mapsindoorssolutionid:googleapikey:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/init(mapsIndoorsSolutionId:googleApiKey:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"mapsIndoorsSolutionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"googleApiKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"init(mapsIndoorsSolutionId:googleApiKey:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)MPRoutingProvider(im)initWithMapsIndoorsSolutionId:googleApiKey:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"initWithMapsIndoorsSolutionId:googleApiKey:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider":{"role":"symbol","title":"MPRoutingProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoutingProvider"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRoutingProvider"}],"url":"\/documentation\/mapsindoors\/mproutingprovider"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/init(mapsIndoorsSolutionId:googleApiKey:)":{"role":"symbol","title":"init(mapsIndoorsSolutionId:googleApiKey:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"mapsIndoorsSolutionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"googleApiKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/init(mapsIndoorsSolutionId:googleApiKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMapsIndoorsSolutionId:googleApiKey:"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/init(mapsindoorssolutionid:googleapikey:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithMapsIndoorsSolutionId:googleApiKey:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMapsIndoorsSolutionId:googleApiKey:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMapsIndoorsSolutionId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"solutionId"},{"kind":"text","text":" "},{"kind":"identifier","text":"googleApiKey:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"googleApiKey"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider\/title","value":"MPRoutingProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider\/fragments","value":[{"kind":"identifier","text":"MPRoutingProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1init(mapsIndoorsSolutionId:googleApiKey:)\/title","value":"initWithMapsIndoorsSolutionId:googleApiKey:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1init(mapsIndoorsSolutionId:googleApiKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMapsIndoorsSolutionId:googleApiKey:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}