{"sections":[],"metadata":{"roleHeading":"Case","role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"MPDataSetCachingScopeBasic","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@E@MPDataSetCachingScope@MPDataSetCachingScopeBasic","modules":[{"name":"MapsIndoors"}],"title":"MPDataSetCachingScope.basic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"basic","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope"]]},"abstract":[{"type":"text","text":"Basic cache scope. Information about locations, buildings and venue and type images."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachingscope\/basic"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachingscope\/basic"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"basic","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/basic","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingScope/basic":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"basic"}],"abstract":[{"type":"text","text":"Basic cache scope. Information about locations, buildings and venue and type images."}],"url":"\/documentation\/mapsindoors\/mpdatasetcachingscope\/basic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCachingScopeBasic"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/basic","title":"MPDataSetCachingScope.basic","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingScope":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope","abstract":[{"type":"text","text":"Data set caching scope. Currently only a full cache (non-partial) scope is supported (basic and detailed scope will sync full dataset)."}],"kind":"symbol","navigatorTitle":[{"text":"MPDataSetCachingScope","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCachingScope"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachingscope","title":"MPDataSetCachingScope"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MPDataSetCachingScopeBasic","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MPDataSetCachingScopeBasic","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"MPDataSetCachingScopeBasic","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"MPDataSetCachingScopeBasic","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope~1basic\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope~1basic\/fragments","value":[{"text":"MPDataSetCachingScopeBasic","kind":"identifier"}]},{"op":"replace","value":"MPDataSetCachingScope","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope\/fragments","value":[{"kind":"identifier","text":"MPDataSetCachingScope"}],"op":"replace"}]}]}