{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope"]]},"sections":[],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@MapsIndoors@E@MPDataSetCachingScope@MPDataSetCachingScopeDetailed","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detailed","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"case","navigatorTitle":[{"text":"MPDataSetCachingScopeDetailed","kind":"identifier"}],"title":"MPDataSetCachingScope.detailed"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/detailed"},"abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/basic"},{"text":" + location-specific images.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcachingscope\/detailed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachingscope\/detailed"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detailed"}],"platforms":["iOS"]}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingScope/basic":{"title":"MPDataSetCachingScope.basic","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/basic","role":"symbol","abstract":[{"text":"Basic cache scope. Information about locations, buildings and venue and type images.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"basic","kind":"identifier"}],"navigatorTitle":[{"text":"MPDataSetCachingScopeBasic","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachingscope\/basic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingScope/detailed":{"title":"MPDataSetCachingScope.detailed","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/detailed","role":"symbol","abstract":[{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/basic","isActive":true},{"type":"text","text":" + location-specific images."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"detailed","kind":"identifier"}],"navigatorTitle":[{"text":"MPDataSetCachingScopeDetailed","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachingscope\/detailed"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingScope":{"navigatorTitle":[{"text":"MPDataSetCachingScope","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapsindoors\/mpdatasetcachingscope","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope","title":"MPDataSetCachingScope","role":"symbol","abstract":[{"text":"Data set caching scope. Currently only a full cache (non-partial) scope is supported (basic and detailed scope will sync full dataset).","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCachingScope"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MPDataSetCachingScopeDetailed"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MPDataSetCachingScopeDetailed","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"MPDataSetCachingScopeDetailed","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope~1basic\/title","op":"replace","value":"MPDataSetCachingScopeBasic"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope~1basic\/fragments","op":"replace","value":[{"text":"MPDataSetCachingScopeBasic","kind":"identifier"}]},{"value":"MPDataSetCachingScopeDetailed","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope~1detailed\/title","op":"replace"},{"op":"replace","value":[{"text":"MPDataSetCachingScopeDetailed","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope~1detailed\/fragments"},{"op":"replace","value":"MPDataSetCachingScope","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPDataSetCachingScope"}]}]}]}