{"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcachingscope\/full"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachingscope\/full"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"full","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPDataSetCachingScopeFull"}],"externalID":"c:@M@MapsIndoors@E@MPDataSetCachingScope@MPDataSetCachingScopeFull","symbolKind":"case","role":"symbol","title":"MPDataSetCachingScope.full","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"full"}]},"abstract":[{"type":"text","text":"Full cache scope. All necessary content is downloaded for a data set to work offline."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/full"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope"]]},"references":{"MapsPeopleWhite.png":{"alt":null,"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingScope":{"navigatorTitle":[{"text":"MPDataSetCachingScope","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapsindoors\/mpdatasetcachingscope","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope","title":"MPDataSetCachingScope","role":"symbol","abstract":[{"text":"Data set caching scope. Currently only a full cache (non-partial) scope is supported (basic and detailed scope will sync full dataset).","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCachingScope"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingScope/full":{"navigatorTitle":[{"text":"MPDataSetCachingScopeFull","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachingscope\/full","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/full","title":"MPDataSetCachingScope.full","role":"symbol","abstract":[{"type":"text","text":"Full cache scope. All necessary content is downloaded for a data set to work offline."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"full","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MPDataSetCachingScopeFull"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"MPDataSetCachingScopeFull"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"MPDataSetCachingScopeFull","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"MPDataSetCachingScope","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope\/fragments","value":[{"kind":"identifier","text":"MPDataSetCachingScope"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope~1full\/title","value":"MPDataSetCachingScopeFull","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope~1full\/fragments","value":[{"kind":"identifier","text":"MPDataSetCachingScopeFull"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}