{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSolutionsReady"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"solution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolution","preciseIdentifier":"c:objc(cs)MPSolution","text":"MPSolution"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpsolutionproviderdelegate\/onsolutionsready(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpsolutionproviderdelegate\/onsolutionsready(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProviderDelegate\/onSolutionsReady(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onSolutionsReady:"}],"role":"symbol","title":"onSolutionsReady(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSolutionsReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPSolution","preciseIdentifier":"c:objc(cs)MPSolution"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MPSolutionProviderDelegate(im)onSolutionsReady:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProviderDelegate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPSolutionProviderDelegate":{"role":"symbol","title":"MPSolutionProviderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSolutionProviderDelegate"}],"abstract":[{"type":"text","text":"Solution provider delegate."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProviderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPSolutionProviderDelegate"}],"url":"\/documentation\/mapsindoors\/mpsolutionproviderdelegate"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPSolution":{"role":"symbol","title":"MPSolution","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSolution"}],"abstract":[{"type":"text","text":"The solution model holds data about the buildings and floors in a solution, plus additional meta-data."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolution","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPSolution"}],"url":"\/documentation\/mapsindoors\/mpsolution"},"doc://MapsIndoors/documentation/MapsIndoors/MPSolutionProviderDelegate/onSolutionsReady(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onSolutionsReady:"}],"role":"symbol","title":"onSolutionsReady(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSolutionsReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPSolution","preciseIdentifier":"c:objc(cs)MPSolution"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProviderDelegate\/onSolutionsReady(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpsolutionproviderdelegate\/onsolutionsready(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onSolutionsReady:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSolutionsReady:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onSolutionsReady:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolution","preciseIdentifier":"c:objc(cs)MPSolution","text":"MPSolution"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"solution"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProviderDelegate\/title","value":"MPSolutionProviderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProviderDelegate\/fragments","value":[{"kind":"identifier","text":"MPSolutionProviderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolution\/title","value":"MPSolution"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolution\/fragments","value":[{"kind":"identifier","text":"MPSolution"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProviderDelegate~1onSolutionsReady(_:)\/title","value":"onSolutionsReady:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProviderDelegate~1onSolutionsReady(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSolutionsReady:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}