{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFloorIndexChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"floorIndex"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":")"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloorSelectorDelegate"]]},"abstract":[{"text":"Floor change event method. Must be implemented by delegate object.","type":"text"}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloorSelectorDelegate\/onFloorIndexChanged(_:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpfloorselectordelegate\/onfloorindexchanged(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpfloorselectordelegate\/onfloorindexchanged(_:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onFloorIndexChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onFloorIndexChanged:"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@MapsIndoors@objc(pl)MPFloorSelectorDelegate(im)onFloorIndexChanged:","modules":[{"name":"MapsIndoors"}],"role":"symbol","required":true,"title":"onFloorIndexChanged(_:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFloorSelectorDelegate/onFloorIndexChanged(_:)":{"type":"topic","abstract":[{"type":"text","text":"Floor change event method. Must be implemented by delegate object."}],"url":"\/documentation\/mapsindoors\/mpfloorselectordelegate\/onfloorindexchanged(_:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloorSelectorDelegate\/onFloorIndexChanged(_:)","required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onFloorIndexChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onFloorIndexChanged:"}],"role":"symbol","title":"onFloorIndexChanged(_:)"},"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFloorSelectorDelegate":{"type":"topic","abstract":[{"type":"text","text":"Delegate protocol specification to hold the floor change event."}],"url":"\/documentation\/mapsindoors\/mpfloorselectordelegate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloorSelectorDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloorSelectorDelegate"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPFloorSelectorDelegate"}],"role":"symbol","title":"MPFloorSelectorDelegate"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"onFloorIndexChanged:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onFloorIndexChanged:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onFloorIndexChanged:"},{"text":"(","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *) "},{"text":"floorIndex","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"onFloorIndexChanged:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloorSelectorDelegate~1onFloorIndexChanged(_:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloorSelectorDelegate~1onFloorIndexChanged(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onFloorIndexChanged:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloorSelectorDelegate\/title","value":"MPFloorSelectorDelegate","op":"replace"},{"value":[{"text":"MPFloorSelectorDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloorSelectorDelegate\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}