{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cachingScope_Full"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcachescope\/cachingscope_full"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachescope\/cachingscope_full"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/cachingScope_Full","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Basic + location-specific images."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cachingScope_Full"}],"title":"MPDataSetCacheScope.cachingScope_Full","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MPDataSetCacheScope@MPDataSetCachingScope_Full","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPDataSetCachingScope_Full"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheScope/cachingScope_Full":{"role":"symbol","title":"MPDataSetCacheScope.cachingScope_Full","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cachingScope_Full"}],"abstract":[{"type":"text","text":"Basic + location-specific images."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope\/cachingScope_Full","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCachingScope_Full"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachescope\/cachingscope_full"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheScope":{"role":"symbol","title":"MPDataSetCacheScope","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheScope"}],"abstract":[{"type":"text","text":"Data set caching scope. Currently only a full cache (non-partial) scope is supported (basic and detailed scope will sync full dataset)"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheScope","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheScope"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachescope"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MPDataSetCachingScope_Full"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPDataSetCachingScope_Full"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MPDataSetCachingScope_Full"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope~1cachingScope_Full\/title","value":"MPDataSetCachingScope_Full"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope~1cachingScope_Full\/fragments","value":[{"kind":"identifier","text":"MPDataSetCachingScope_Full"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope\/title","value":"MPDataSetCacheScope"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheScope\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheScope"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}