{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contains"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"coordinate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/contains(_:)-37jlx"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/contains(_:)-37jlx"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/contains(_:)-37jlx","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Check if the given coordinate is contained within the polygon."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"containsCoordinate:"}],"role":"symbol","title":"contains(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contains"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:objc(pl)MPGeometryQueryProtocol(im)containsCoordinate:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPGeometryQueryProtocol/contains(_:)-37jlx":{"navigatorTitle":[{"kind":"identifier","text":"containsCoordinate:"}],"role":"symbol","title":"contains(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contains"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Check if the given coordinate is contained within the polygon."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/contains(_:)-37jlx","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/contains(_:)-37jlx"},"doc://MapsIndoors/documentation/MapsIndoors/MPGeometryQueryProtocol":{"role":"symbol","title":"MPGeometryQueryProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeometryQueryProtocol"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPGeometryQueryProtocol"}],"url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"containsCoordinate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsCoordinate:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"containsCoordinate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":")"},{"kind":"internalParam","text":"coordinate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1contains(_:)-37jlx\/title","value":"containsCoordinate:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1contains(_:)-37jlx\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsCoordinate:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol\/title","value":"MPGeometryQueryProtocol"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol\/fragments","value":[{"kind":"identifier","text":"MPGeometryQueryProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}