{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contains"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"coordinate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ignorePolygonHoles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"containmentMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata","preciseIdentifier":"c:objc(cs)MPGeometryContainmentMetadata","text":"MPGeometryContainmentMetadata"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/contains(_:ignorepolygonholes:containmentmetadata:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/contains(_:ignorepolygonholes:containmentmetadata:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/contains(_:ignorePolygonHoles:containmentMetadata:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Check if the given coordinate is contained within the polygon, and optionally return the coordinate closest to the polygon."},{"type":"text","text":" "},{"type":"text","text":"If the polygon contains the coordinate, ‘coordinate’ is returned as nearestPoint."},{"type":"text","text":" "},{"type":"text","text":"If coordinate is not contained, the nearest point is calculated."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:"}],"role":"symbol","title":"contains(_:ignorePolygonHoles:containmentMetadata:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contains"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ignorePolygonHoles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"containmentMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPGeometryContainmentMetadata","preciseIdentifier":"c:objc(cs)MPGeometryContainmentMetadata"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:objc(pl)MPGeometryQueryProtocol(im)containsCoordinate:ignorePolygonHoles:containmentMetadata:","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPGeometryQueryProtocol/contains(_:ignorePolygonHoles:containmentMetadata:)":{"navigatorTitle":[{"kind":"identifier","text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:"}],"role":"symbol","title":"contains(_:ignorePolygonHoles:containmentMetadata:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contains"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ignorePolygonHoles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"containmentMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPGeometryContainmentMetadata","preciseIdentifier":"c:objc(cs)MPGeometryContainmentMetadata"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Check if the given coordinate is contained within the polygon, and optionally return the coordinate closest to the polygon."},{"type":"text","text":" "},{"type":"text","text":"If the polygon contains the coordinate, ‘coordinate’ is returned as nearestPoint."},{"type":"text","text":" "},{"type":"text","text":"If coordinate is not contained, the nearest point is calculated."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/contains(_:ignorePolygonHoles:containmentMetadata:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/contains(_:ignorepolygonholes:containmentmetadata:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPGeometryContainmentMetadata":{"role":"symbol","title":"MPGeometryContainmentMetadata","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeometryContainmentMetadata"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPGeometryContainmentMetadata"}],"url":"\/documentation\/mapsindoors\/mpgeometrycontainmentmetadata"},"doc://MapsIndoors/documentation/MapsIndoors/MPGeometryQueryProtocol":{"role":"symbol","title":"MPGeometryQueryProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeometryQueryProtocol"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPGeometryQueryProtocol"}],"url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"containsCoordinate:ignorePolygonHoles:containmentMetadata:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"containsCoordinate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":")"},{"kind":"internalParam","text":"coordinate"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignorePolygonHoles:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"ignorePolygonHoles"},{"kind":"text","text":" "},{"kind":"identifier","text":"containmentMetadata:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryContainmentMetadata","preciseIdentifier":"c:objc(cs)MPGeometryContainmentMetadata","text":"MPGeometryContainmentMetadata"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"containmentMetadata"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1contains(_:ignorePolygonHoles:containmentMetadata:)\/title","value":"containsCoordinate:ignorePolygonHoles:containmentMetadata:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1contains(_:ignorePolygonHoles:containmentMetadata:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryContainmentMetadata\/title","value":"MPGeometryContainmentMetadata"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryContainmentMetadata\/fragments","value":[{"kind":"identifier","text":"MPGeometryContainmentMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol\/title","value":"MPGeometryQueryProtocol"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol\/fragments","value":[{"kind":"identifier","text":"MPGeometryQueryProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}