{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/logLevel","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevel"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@EA@os_log_type_t","text":"OSLogType"}]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mplog\/loglevel"]},{"paths":["\/documentation\/mapsindoors\/mplog\/loglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@EA@os_log_type_t","text":"OSLogType"}],"modules":[{"name":"MapsIndoors"}],"role":"symbol","roleHeading":"Type Property","symbolKind":"property","title":"logLevel","navigatorTitle":[{"text":"logLevel","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPLog(cpy)logLevel"},"abstract":[{"type":"text","text":"Set the log level for MapsIndoors. Defaults to "},{"type":"codeVoice","code":"debug"},{"type":"text","text":"."}],"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLog":{"navigatorTitle":[{"kind":"identifier","text":"MPLog"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mplog","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPLog","kind":"identifier"}],"abstract":[{"text":"The logger used internally by MapsIndoors.","type":"text"}],"title":"MPLog","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLog/logLevel":{"type":"topic","role":"symbol","url":"\/documentation\/mapsindoors\/mplog\/loglevel","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OSLogType","kind":"typeIdentifier","preciseIdentifier":"c:@EA@os_log_type_t"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/logLevel","abstract":[{"text":"Set the log level for MapsIndoors. Defaults to ","type":"text"},{"code":"debug","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"logLevel","kind":"identifier"}],"title":"logLevel"},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"type":"image","identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"logLevel"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"logLevel","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"os_log_type_t","preciseIdentifier":"c:@EA@os_log_type_t"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevel"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog\/title","value":"MPLog"},{"op":"replace","value":[{"kind":"identifier","text":"MPLog"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog~1logLevel\/title","value":"logLevel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog~1logLevel\/fragments","value":[{"text":"logLevel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}