{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDataSet"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dataSetId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCache","preciseIdentifier":"c:objc(cs)MPDataSetCache","text":"MPDataSetCache"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The cache object if data set was successfully added as a result of this call, if the dataset already existed this method returns nil."}]}]},{"kind":"parameters","parameters":[{"name":"dataSetId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Data set id of the data set that should be added."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/adddataset(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager\/adddataset(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/addDataSet(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Add data set to the list of managed data sets."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDataSet"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPDataSetCache","preciseIdentifier":"c:objc(cs)MPDataSetCache"},{"kind":"text","text":"?"}],"title":"addDataSet(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPDataSetCacheManager(im)addDataSet:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"addDataSet:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheManager":{"role":"symbol","title":"MPDataSetCacheManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheManager"}],"abstract":[{"type":"text","text":"Data set manager class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManager"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCacheManager/addDataSet(_:)":{"role":"symbol","title":"addDataSet(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDataSet"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPDataSetCache","preciseIdentifier":"c:objc(cs)MPDataSetCache"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Add data set to the list of managed data sets."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/addDataSet(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addDataSet:"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/adddataset(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCache":{"role":"symbol","title":"MPDataSetCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCache"}],"abstract":[{"type":"text","text":"Data set cache class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCache"}],"url":"\/documentation\/mapsindoors\/mpdatasetcache"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addDataSet:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addDataSet:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCache","preciseIdentifier":"c:objc(cs)MPDataSetCache","text":"MPDataSetCache"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"addDataSet:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"dataSetId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title","value":"MPDataSetCacheManager"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheManager"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1addDataSet(_:)\/title","value":"addDataSet:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1addDataSet(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addDataSet:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCache\/title","value":"MPDataSetCache"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCache\/fragments","value":[{"kind":"identifier","text":"MPDataSetCache"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}