{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBeacons"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"beaconIds"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbeaconprovider-swift.class\/getbeacons(_:clientid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbeaconprovider-swift.class\/getbeacons(_:clientid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProvider-swift.class\/getBeacons(_:clientId:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Method to initiate fetching of Beacons from the provider."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getBeacons:clientId:"}],"role":"symbol","title":"getBeacons(_:clientId:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBeacons"},{"kind":"text","text":"(["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(cs)MPBeaconProvider(im)getBeacons:clientId:","modules":[{"name":"MapsIndoors"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProvider-swift.class"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use -(void)getBeacons:(NSString*)solutionId instead"}]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeaconProvider-swift.class":{"role":"symbol","title":"MPBeaconProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeaconProvider"}],"abstract":[{"type":"text","text":"Beacons provider that defines a delegate and a method to initiate fetching of Beacons from the provider."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProvider-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBeaconProvider"}],"url":"\/documentation\/mapsindoors\/mpbeaconprovider-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeaconProvider-swift.class/getBeacons(_:clientId:)":{"deprecated":true,"role":"symbol","title":"getBeacons(_:clientId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBeacons"},{"kind":"text","text":"(["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method to initiate fetching of Beacons from the provider."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeaconProvider-swift.class\/getBeacons(_:clientId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getBeacons:clientId:"}],"url":"\/documentation\/mapsindoors\/mpbeaconprovider-swift.class\/getbeacons(_:clientid:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getBeacons:clientId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBeacons:clientId:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getBeacons:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"beaconIds"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"clientId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProvider-swift.class\/title","value":"MPBeaconProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProvider-swift.class\/fragments","value":[{"kind":"identifier","text":"MPBeaconProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProvider-swift.class~1getBeacons(_:clientId:)\/title","value":"getBeacons:clientId:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeaconProvider-swift.class~1getBeacons(_:clientId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBeacons:clientId:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}