{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstStepAligned","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpcameraviewfitmode\/firststepaligned"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpcameraviewfitmode\/firststepaligned"]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode"]]},"metadata":{"externalID":"c:@M@MapsIndoors@E@MPCameraViewFitMode@MPCameraViewFitModeFirstStepAligned","symbolKind":"case","navigatorTitle":[{"text":"MPCameraViewFitModeFirstStepAligned","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"firstStepAligned"}],"roleHeading":"Case","title":"MPCameraViewFitMode.firstStepAligned","modules":[{"name":"MapsIndoors"}]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/firstStepAligned","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Fit the "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/bearing","isActive":true,"type":"reference"},{"text":" to point towards the first step of a route.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraPosition/bearing":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/bearing","abstract":[{"type":"text","text":"The bearing of the map, measured in degrees clockwise from true north."}],"url":"\/documentation\/mapsindoors\/mpcameraposition\/bearing","kind":"symbol","required":true,"type":"topic","navigatorTitle":[{"kind":"identifier","text":"bearing"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bearing"},{"text":": ","kind":"text"},{"text":"CLLocationDirection","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection"}],"title":"bearing"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraViewFitMode/firstStepAligned":{"url":"\/documentation\/mapsindoors\/mpcameraviewfitmode\/firststepaligned","abstract":[{"type":"text","text":"Fit the "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/bearing","isActive":true,"type":"reference"},{"text":" to point towards the first step of a route.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/firstStepAligned","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPCameraViewFitModeFirstStepAligned"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstStepAligned"}],"title":"MPCameraViewFitMode.firstStepAligned"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraViewFitMode":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mpcameraviewfitmode","role":"symbol","title":"MPCameraViewFitMode","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode","navigatorTitle":[{"text":"MPCameraViewFitMode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPCameraViewFitMode"}],"type":"topic","abstract":[]},"MapsPeopleWhite.png":{"alt":null,"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MPCameraViewFitModeFirstStepAligned"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPCameraViewFitModeFirstStepAligned"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MPCameraViewFitModeFirstStepAligned"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1bearing\/title","op":"replace","value":"bearing"},{"value":[{"kind":"identifier","text":"bearing"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1bearing\/fragments"},{"op":"replace","value":"MPCameraViewFitModeFirstStepAligned","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode~1firstStepAligned\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode~1firstStepAligned\/fragments","value":[{"text":"MPCameraViewFitModeFirstStepAligned","kind":"identifier"}]},{"value":"MPCameraViewFitMode","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode\/fragments","op":"replace","value":[{"text":"MPCameraViewFitMode","kind":"identifier"}]}]}]}