{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/northAligned","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Fit the "},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/bearing","type":"reference"},{"text":" to point towards north.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/mapsindoors\/mpcameraviewfitmode\/northaligned"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpcameraviewfitmode\/northaligned"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"northAligned"}]}]}],"metadata":{"roleHeading":"Case","externalID":"c:@M@MapsIndoors@E@MPCameraViewFitMode@MPCameraViewFitModeNorthAligned","title":"MPCameraViewFitMode.northAligned","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"MPCameraViewFitModeNorthAligned","kind":"identifier"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"northAligned","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraPosition/bearing":{"role":"symbol","url":"\/documentation\/mapsindoors\/mpcameraposition\/bearing","navigatorTitle":[{"kind":"identifier","text":"bearing"}],"abstract":[{"text":"The bearing of the map, measured in degrees clockwise from true north.","type":"text"}],"required":true,"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bearing","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/bearing","title":"bearing"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraViewFitMode":{"role":"symbol","url":"\/documentation\/mapsindoors\/mpcameraviewfitmode","navigatorTitle":[{"text":"MPCameraViewFitMode","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MPCameraViewFitMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode","title":"MPCameraViewFitMode"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraViewFitMode/northAligned":{"role":"symbol","url":"\/documentation\/mapsindoors\/mpcameraviewfitmode\/northaligned","navigatorTitle":[{"kind":"identifier","text":"MPCameraViewFitModeNorthAligned"}],"abstract":[{"type":"text","text":"Fit the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/bearing"},{"type":"text","text":" to point towards north."}],"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"northAligned","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/northAligned","title":"MPCameraViewFitMode.northAligned"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MPCameraViewFitModeNorthAligned"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MPCameraViewFitModeNorthAligned","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"MPCameraViewFitModeNorthAligned"}]}],"kind":"declarations"}},{"value":"bearing","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1bearing\/title"},{"value":[{"kind":"identifier","text":"bearing"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1bearing\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode\/title","value":"MPCameraViewFitMode"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode\/fragments","value":[{"text":"MPCameraViewFitMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode~1northAligned\/title","value":"MPCameraViewFitModeNorthAligned","op":"replace"},{"value":[{"kind":"identifier","text":"MPCameraViewFitModeNorthAligned"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode~1northAligned\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}