{"variants":[{"paths":["\/documentation\/mapsindoors\/mpcameraviewfitmode\/starttoendaligned"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpcameraviewfitmode\/starttoendaligned"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Fit the "},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/bearing","type":"reference"},{"text":" to point towards the entire route.","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startToEndAligned"}],"navigatorTitle":[{"kind":"identifier","text":"MPCameraViewFitModeStartToEndAligned"}],"symbolKind":"case","modules":[{"name":"MapsIndoors"}],"externalID":"c:@M@MapsIndoors@E@MPCameraViewFitMode@MPCameraViewFitModeStartToEndAligned","title":"MPCameraViewFitMode.startToEndAligned","roleHeading":"Case","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/startToEndAligned","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startToEndAligned"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraPosition/bearing":{"title":"bearing","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bearing","kind":"identifier"},{"kind":"text","text":": "},{"text":"CLLocationDirection","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection"}],"abstract":[{"type":"text","text":"The bearing of the map, measured in degrees clockwise from true north."}],"url":"\/documentation\/mapsindoors\/mpcameraposition\/bearing","navigatorTitle":[{"text":"bearing","kind":"identifier"}],"kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/bearing","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraViewFitMode":{"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpcameraviewfitmode","title":"MPCameraViewFitMode","navigatorTitle":[{"text":"MPCameraViewFitMode","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MPCameraViewFitMode","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraViewFitMode/startToEndAligned":{"title":"MPCameraViewFitMode.startToEndAligned","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startToEndAligned"}],"abstract":[{"type":"text","text":"Fit the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/bearing"},{"type":"text","text":" to point towards the entire route."}],"url":"\/documentation\/mapsindoors\/mpcameraviewfitmode\/starttoendaligned","navigatorTitle":[{"kind":"identifier","text":"MPCameraViewFitModeStartToEndAligned"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/startToEndAligned"},"MapsPeopleWhite.png":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"identifier":"MapsPeopleWhite.png"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MPCameraViewFitModeStartToEndAligned","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MPCameraViewFitModeStartToEndAligned"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MPCameraViewFitModeStartToEndAligned","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1bearing\/title","value":"bearing"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1bearing\/fragments","op":"replace","value":[{"text":"bearing","kind":"identifier"}]},{"op":"replace","value":"MPCameraViewFitMode","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode\/fragments","value":[{"kind":"identifier","text":"MPCameraViewFitMode"}],"op":"replace"},{"value":"MPCameraViewFitModeStartToEndAligned","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode~1startToEndAligned\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode~1startToEndAligned\/fragments","value":[{"text":"MPCameraViewFitModeStartToEndAligned","kind":"identifier"}]}]}]}