{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomFontIcon"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/customfonticon"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/customfonticon"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH","doc:\/\/MapsIndoors\/SY","doc:\/\/MapsIndoors\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"CustomIcon Icons."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomFontIcon"}],"title":"CustomFontIcon","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@CustomFontIcon","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"CustomFontIcon"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/airplane","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/bicycle","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/bookmark","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/building","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/bus","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/car","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/compass","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/film","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/home","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/hospital","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/image","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/levels","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/mail","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/mansilhouette","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/motorbike","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/navigation","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/play","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/playO","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/playO2","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/tag","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/tags","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/train","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/truck","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/university","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/vehicle","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/wheelchair"]},{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/Equatable-Implementations","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/navigation":{"role":"symbol","title":"CustomFontIcon.navigation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigation"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/navigation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"navigation"}],"url":"\/documentation\/mapsindoors\/customfonticon\/navigation"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/home":{"role":"symbol","title":"CustomFontIcon.home","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"home"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/home","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"home"}],"url":"\/documentation\/mapsindoors\/customfonticon\/home"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/university":{"role":"symbol","title":"CustomFontIcon.university","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"university"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/university","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"university"}],"url":"\/documentation\/mapsindoors\/customfonticon\/university"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/bookmark":{"role":"symbol","title":"CustomFontIcon.bookmark","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bookmark"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/bookmark","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bookmark"}],"url":"\/documentation\/mapsindoors\/customfonticon\/bookmark"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/levels":{"role":"symbol","title":"CustomFontIcon.levels","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"levels"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/levels","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"levels"}],"url":"\/documentation\/mapsindoors\/customfonticon\/levels"},"doc://MapsIndoors/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/MapsIndoors\/s8SendableP"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon":{"role":"symbol","title":"CustomFontIcon","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomFontIcon"}],"abstract":[{"type":"text","text":"CustomIcon Icons."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomFontIcon"}],"url":"\/documentation\/mapsindoors\/customfonticon"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/film":{"role":"symbol","title":"CustomFontIcon.film","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"film"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/film","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"film"}],"url":"\/documentation\/mapsindoors\/customfonticon\/film"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/customfonticon\/equatable-implementations"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/playO":{"role":"symbol","title":"CustomFontIcon.playO","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playO"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/playO","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playO"}],"url":"\/documentation\/mapsindoors\/customfonticon\/playo"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/customfonticon\/init(rawvalue:)"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/bus":{"role":"symbol","title":"CustomFontIcon.bus","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bus"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/bus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bus"}],"url":"\/documentation\/mapsindoors\/customfonticon\/bus"},"doc://MapsIndoors/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/MapsIndoors\/SY"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/motorbike":{"role":"symbol","title":"CustomFontIcon.motorbike","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"motorbike"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/motorbike","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"motorbike"}],"url":"\/documentation\/mapsindoors\/customfonticon\/motorbike"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/play":{"role":"symbol","title":"CustomFontIcon.play","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"play"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/play","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"play"}],"url":"\/documentation\/mapsindoors\/customfonticon\/play"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/bicycle":{"role":"symbol","title":"CustomFontIcon.bicycle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bicycle"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/bicycle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bicycle"}],"url":"\/documentation\/mapsindoors\/customfonticon\/bicycle"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/truck":{"role":"symbol","title":"CustomFontIcon.truck","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"truck"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/truck","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"truck"}],"url":"\/documentation\/mapsindoors\/customfonticon\/truck"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/hospital":{"role":"symbol","title":"CustomFontIcon.hospital","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hospital"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/hospital","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hospital"}],"url":"\/documentation\/mapsindoors\/customfonticon\/hospital"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/playO2":{"role":"symbol","title":"CustomFontIcon.playO2","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playO2"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/playO2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playO2"}],"url":"\/documentation\/mapsindoors\/customfonticon\/playo2"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/image":{"role":"symbol","title":"CustomFontIcon.image","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/image","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"image"}],"url":"\/documentation\/mapsindoors\/customfonticon\/image"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/tag":{"role":"symbol","title":"CustomFontIcon.tag","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tag"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/tag","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tag"}],"url":"\/documentation\/mapsindoors\/customfonticon\/tag"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/vehicle":{"role":"symbol","title":"CustomFontIcon.vehicle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"vehicle"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/vehicle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"vehicle"}],"url":"\/documentation\/mapsindoors\/customfonticon\/vehicle"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/mail":{"role":"symbol","title":"CustomFontIcon.mail","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mail"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/mail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mail"}],"url":"\/documentation\/mapsindoors\/customfonticon\/mail"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/wheelchair":{"role":"symbol","title":"CustomFontIcon.wheelchair","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wheelchair"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/wheelchair","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"wheelchair"}],"url":"\/documentation\/mapsindoors\/customfonticon\/wheelchair"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/car":{"role":"symbol","title":"CustomFontIcon.car","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"car"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/car","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"car"}],"url":"\/documentation\/mapsindoors\/customfonticon\/car"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/mansilhouette":{"role":"symbol","title":"CustomFontIcon.mansilhouette","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mansilhouette"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/mansilhouette","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mansilhouette"}],"url":"\/documentation\/mapsindoors\/customfonticon\/mansilhouette"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/building":{"role":"symbol","title":"CustomFontIcon.building","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"building"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/building","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"building"}],"url":"\/documentation\/mapsindoors\/customfonticon\/building"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/tags":{"role":"symbol","title":"CustomFontIcon.tags","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tags"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/tags","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tags"}],"url":"\/documentation\/mapsindoors\/customfonticon\/tags"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/airplane":{"role":"symbol","title":"CustomFontIcon.airplane","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airplane"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/airplane","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"airplane"}],"url":"\/documentation\/mapsindoors\/customfonticon\/airplane"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/train":{"role":"symbol","title":"CustomFontIcon.train","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"train"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/train","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"train"}],"url":"\/documentation\/mapsindoors\/customfonticon\/train"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/customfonticon\/rawrepresentable-implementations"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/compass":{"role":"symbol","title":"CustomFontIcon.compass","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"compass"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/compass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"compass"}],"url":"\/documentation\/mapsindoors\/customfonticon\/compass"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"CustomFontIcon"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CustomFontIcon"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CustomFontIcon"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/airplane","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/bicycle","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/bookmark","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/building","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/bus","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/car","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/compass","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/film","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/home","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/hospital","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/image","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/levels","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/mail","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/mansilhouette","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/motorbike","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/navigation","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/play","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/playO","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/playO2","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/tag","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/tags","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/train","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/truck","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/university","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/vehicle","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/wheelchair"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomFontIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1navigation\/title","value":"navigation"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1navigation\/fragments","value":[{"kind":"identifier","text":"navigation"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1home\/title","value":"home"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1home\/fragments","value":[{"kind":"identifier","text":"home"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1university\/title","value":"university"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1university\/fragments","value":[{"kind":"identifier","text":"university"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1bookmark\/title","value":"bookmark"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1bookmark\/fragments","value":[{"kind":"identifier","text":"bookmark"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1levels\/title","value":"levels"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1levels\/fragments","value":[{"kind":"identifier","text":"levels"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon\/title","value":"CustomFontIcon"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon\/fragments","value":[{"kind":"identifier","text":"CustomFontIcon"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1film\/title","value":"film"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1film\/fragments","value":[{"kind":"identifier","text":"film"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1playO\/title","value":"playO"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1playO\/fragments","value":[{"kind":"identifier","text":"playO"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1bus\/title","value":"bus"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1bus\/fragments","value":[{"kind":"identifier","text":"bus"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1motorbike\/title","value":"motorbike"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1motorbike\/fragments","value":[{"kind":"identifier","text":"motorbike"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1play\/title","value":"play"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1play\/fragments","value":[{"kind":"identifier","text":"play"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1bicycle\/title","value":"bicycle"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1bicycle\/fragments","value":[{"kind":"identifier","text":"bicycle"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1truck\/title","value":"truck"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1truck\/fragments","value":[{"kind":"identifier","text":"truck"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1hospital\/title","value":"hospital"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1hospital\/fragments","value":[{"kind":"identifier","text":"hospital"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1playO2\/title","value":"playO2"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1playO2\/fragments","value":[{"kind":"identifier","text":"playO2"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1image\/title","value":"image"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1image\/fragments","value":[{"kind":"identifier","text":"image"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1tag\/title","value":"tag"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1tag\/fragments","value":[{"kind":"identifier","text":"tag"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1vehicle\/title","value":"vehicle"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1vehicle\/fragments","value":[{"kind":"identifier","text":"vehicle"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1mail\/title","value":"mail"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1mail\/fragments","value":[{"kind":"identifier","text":"mail"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1wheelchair\/title","value":"wheelchair"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1wheelchair\/fragments","value":[{"kind":"identifier","text":"wheelchair"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1car\/title","value":"car"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1car\/fragments","value":[{"kind":"identifier","text":"car"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1mansilhouette\/title","value":"mansilhouette"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1mansilhouette\/fragments","value":[{"kind":"identifier","text":"mansilhouette"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1building\/title","value":"building"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1building\/fragments","value":[{"kind":"identifier","text":"building"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1tags\/title","value":"tags"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1tags\/fragments","value":[{"kind":"identifier","text":"tags"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1airplane\/title","value":"airplane"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1airplane\/fragments","value":[{"kind":"identifier","text":"airplane"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1train\/title","value":"train"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1train\/fragments","value":[{"kind":"identifier","text":"train"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1compass\/title","value":"compass"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1compass\/fragments","value":[{"kind":"identifier","text":"compass"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}