{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeDependingConnectionWasLost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/kmperrorcodedependingconnectionwaslost"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/kmperrorcodedependingconnectionwaslost"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/kMPErrorCodeDependingConnectionWasLost","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeDependingConnectionWasLost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"kMPErrorCodeDependingConnectionWasLost","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:MPErrorCodes.h@2659@macro@kMPErrorCodeDependingConnectionWasLost","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"kMPErrorCodeDependingConnectionWasLost"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/kMPErrorCodeDependingConnectionWasLost":{"role":"symbol","title":"kMPErrorCodeDependingConnectionWasLost","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeDependingConnectionWasLost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/kMPErrorCodeDependingConnectionWasLost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kMPErrorCodeDependingConnectionWasLost"}],"url":"\/documentation\/mapsindoors\/kmperrorcodedependingconnectionwaslost"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Macro"},{"op":"replace","path":"\/metadata\/title","value":"kMPErrorCodeDependingConnectionWasLost"},{"op":"replace","path":"\/metadata\/symbolKind","value":"macro"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeDependingConnectionWasLost"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1kMPErrorCodeDependingConnectionWasLost\/title","value":"kMPErrorCodeDependingConnectionWasLost"}],"traits":[{"interfaceLanguage":"occ"}]}]}