{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeMessagesNotFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/kmperrorcodemessagesnotfound"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/kmperrorcodemessagesnotfound"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/kMPErrorCodeMessagesNotFound","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeMessagesNotFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"kMPErrorCodeMessagesNotFound","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:MPErrorCodes.h@897@macro@kMPErrorCodeMessagesNotFound","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"kMPErrorCodeMessagesNotFound"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/kMPErrorCodeMessagesNotFound":{"role":"symbol","title":"kMPErrorCodeMessagesNotFound","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeMessagesNotFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/kMPErrorCodeMessagesNotFound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kMPErrorCodeMessagesNotFound"}],"url":"\/documentation\/mapsindoors\/kmperrorcodemessagesnotfound"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Macro"},{"op":"replace","path":"\/metadata\/title","value":"kMPErrorCodeMessagesNotFound"},{"op":"replace","path":"\/metadata\/symbolKind","value":"macro"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMPErrorCodeMessagesNotFound"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1kMPErrorCodeMessagesNotFound\/title","value":"kMPErrorCodeMessagesNotFound"}],"traits":[{"interfaceLanguage":"occ"}]}]}