{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"kind":"symbol","metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MapsIndoorsShared","role":"symbol","roleHeading":"Protocol","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"MapsIndoorsShared"}],"modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapsIndoorsShared"}],"title":"MapsIndoorsShared"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared"},"abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared"},{"type":"text","text":" describes the main entry point to the SDK which is accessed via "},{"code":"MPMapsIndoors\/shared","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/mapsindoors\/mapsindoorsshared"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mapsindoorsshared"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/apiKey","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/authToken","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/availableUserRoles","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/bookingService","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/datasetCacheManager","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/directionsService","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/eventLoggingDisabled","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/imageProvider","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/language","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/positionProvider","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/ready","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/sdkVersion","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/solution","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/userRoles"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/appData()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/apply(userRoles:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/buildingIn(bounds:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/buildingWith(id:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/buildings()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/categories()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/displayRuleFor(displayRuleType:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/displayRuleFor(location:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/displayRuleFor(type:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/fetchAuthDetails()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/isApiKeyValid(apiKey:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/isOfflineDataAvailable(apiKey:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/load(apiKey:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationWith(locationId:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(externalIds:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/register(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/set(displayRule:location:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/shutdown()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/synchronize()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/venueWith(id:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/venues()"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/createLocationUpdateFactory()"],"title":"Type Methods"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapsIndoorsShared"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"inlineContent":[{"type":"text","text":"Access this shared instance to load, reload or close MapsIndoors solutions using an API key, and navigate the MapsIndoors data."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Create new MapControl instances to visualize the MapsIndoors data from the shared instance, in an interactive map engine (Google Maps or Mapbox Maps)."}]}],"kind":"content"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/positionProvider":{"abstract":[{"text":"The position provider that MapsIndoors should use when user location services are needed.","type":"text"}],"title":"positionProvider","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/positionProvider","navigatorTitle":[{"text":"positionProvider","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/positionprovider","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"positionProvider","kind":"identifier"},{"kind":"text","text":": "},{"text":"MPPositionProvider","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPPositionProvider","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/solution":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"solution"},{"text":": ","kind":"text"},{"text":"MPSolution","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSolution","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"solution"}],"abstract":[{"type":"text","text":"Returns the solution object for the currently loaded MapsIndoors solution."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/solution","required":true,"type":"topic","role":"symbol","kind":"symbol","title":"solution","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/solution"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/datasetCacheManager":{"abstract":[{"type":"text","text":"Dataset cache manager."}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/datasetcachemanager","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"datasetCacheManager","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","text":"MPDataSetCacheManager","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/datasetCacheManager","type":"topic","kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"datasetCacheManager"}],"title":"datasetCacheManager"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/buildingWith(id:)":{"abstract":[{"text":"Get the building with a given id.","type":"text"}],"kind":"symbol","title":"buildingWith(id:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/buildingWith(id:)","navigatorTitle":[{"kind":"identifier","text":"buildingWithId:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/buildingwith(id:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"buildingWith","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"id"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"text":"MPBuilding","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPBuilding"},{"text":"?","kind":"text"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/synchronize()":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/synchronize()","required":true,"role":"symbol","abstract":[{"text":"Reload an already loaded MapsIndoors solution.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"synchronize","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/synchronize()","title":"synchronize()","navigatorTitle":[{"kind":"identifier","text":"synchronizeWithCompletionHandler:"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/displayRuleFor(type:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/displayRuleFor(type:)","title":"displayRuleFor(type:)","required":true,"role":"symbol","abstract":[{"text":"Get the display rule for a given type.","type":"text"}],"navigatorTitle":[{"text":"displayRuleForType:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/displayrulefor(type:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"displayRuleFor","kind":"identifier"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule","text":"MPDisplayRule"},{"kind":"text","text":"?"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/eventLoggingDisabled":{"abstract":[{"text":"Disable or enable anonymous SDK feature usage logging (enabled by default).","type":"text"}],"title":"eventLoggingDisabled","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/eventLoggingDisabled","navigatorTitle":[{"text":"eventLoggingDisabled","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/eventloggingdisabled","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventLoggingDisabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/imageProvider":{"role":"symbol","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/imageprovider","navigatorTitle":[{"text":"imageProvider","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/imageProvider","title":"imageProvider","type":"topic","abstract":[{"type":"text","text":"The image provider that MapsIndoors should use when image resources are needed."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageProvider"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPImageProviderProtocol","text":"MPImageProviderProtocol","kind":"typeIdentifier"}],"kind":"symbol","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/userRoles":{"abstract":[{"type":"text","text":"Get or set the current list of applied user roles. If you want to apply user roles and wait for the SDK to load, use "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/apply(userRoles:)"},{"type":"text","text":" asynchronously."}],"kind":"symbol","title":"userRoles","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/userRoles","navigatorTitle":[{"kind":"identifier","text":"userRoles"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/userroles","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userRoles","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MPUserRole","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPUserRole","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/locationsWith(externalIds:)":{"abstract":[{"text":"Get the Locations that have the provided external IDs associated.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Multiple Locations may have the same external ID associated, so a request with e.g. two external IDs may return more than two Locations."}],"kind":"symbol","title":"locationsWith(externalIds:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(externalIds:)","navigatorTitle":[{"text":"locationsWithExternalIds:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/locationswith(externalids:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"locationsWith","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"externalIds"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]) -> ["},{"text":"MPLocation","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/shutdown()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutdown"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"shutdown","kind":"identifier"}],"abstract":[{"text":"Close the MapsIndoors SDK (clears the internal state of the SDK).","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/shutdown()","required":true,"type":"topic","role":"symbol","kind":"symbol","title":"shutdown()","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/shutdown()"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/isOfflineDataAvailable(apiKey:)":{"abstract":[{"type":"text","text":"Check whether offline data is available for a given MapsIndoors API key."}],"title":"isOfflineDataAvailable(apiKey:)","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/isOfflineDataAvailable(apiKey:)","navigatorTitle":[{"kind":"identifier","text":"isOfflineDataAvailableWithApiKey:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/isofflinedataavailable(apikey:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isOfflineDataAvailable","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"apiKey"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/buildings()":{"title":"buildings()","abstract":[{"text":"Get all buildings.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/buildings()","navigatorTitle":[{"kind":"identifier","text":"buildingsWithCompletionHandler:"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/buildings()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildings"},{"kind":"text","text":"() "},{"text":"async","kind":"keyword"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPBuilding","text":"MPBuilding","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/appData()":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/appdata()","navigatorTitle":[{"kind":"identifier","text":"appDataWithCompletionHandler:"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appData"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPAppConfig","text":"MPAppConfig"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"App configuration data."}],"title":"appData()","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/appData()"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/register(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"register","kind":"identifier"},{"text":"([","kind":"text"},{"text":"MPLocationSource","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationSource","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"register:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/register(_:)","required":true,"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/register(_:)","type":"topic","abstract":[{"text":"Register Location","type":"text"}],"title":"register(_:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/categories()":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/categories()","title":"categories()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"categoriesWithCompletionHandler:"}],"type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"categories"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataField","kind":"typeIdentifier","text":"MPDataField"},{"text":"]","kind":"text"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/categories()","role":"symbol","abstract":[{"type":"text","text":"Categories."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/sdkVersion":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"sdkVersion","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"sdkVersion"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/sdkVersion","title":"sdkVersion","role":"symbol","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/sdkversion","required":true,"abstract":[{"type":"text","text":"A string representation of the version of the MapsIndoors SDK."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/isApiKeyValid(apiKey:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isApiKeyValid"},{"kind":"text","text":"("},{"text":"apiKey","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isApiKeyValidWithApiKey:completionHandler:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/isApiKeyValid(apiKey:)","required":true,"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/isapikeyvalid(apikey:)","type":"topic","abstract":[{"type":"text","text":"Validate a MapsIndoors API key (requires online connectivity)."}],"title":"isApiKeyValid(apiKey:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/authToken":{"type":"topic","role":"symbol","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/authtoken","kind":"symbol","required":true,"navigatorTitle":[{"text":"authToken","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authToken"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"authToken","abstract":[{"text":"The authentication token to use when using MapsIndoors SSO.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/authToken"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/load(apiKey:)":{"abstract":[{"text":"Load a MapsIndoors solution using an API key.","type":"text"}],"role":"symbol","type":"topic","title":"load(apiKey:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"load","kind":"identifier"},{"text":"(","kind":"text"},{"text":"apiKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"loadWithApiKey:completionHandler:","kind":"identifier"}],"required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/load(apiKey:)","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/load(apikey:)","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPBookingService","kind":"identifier"}],"navigatorTitle":[{"text":"MPBookingService","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService","abstract":[{"type":"text","text":"MPBookingService allows for access to the MapsIndoors booking service."},{"text":" ","type":"text"},{"type":"text","text":"The booking service is a special integration that has to be enabled in the MapsIndoors cloud systems."}],"role":"symbol","type":"topic","kind":"symbol","title":"MPBookingService","url":"\/documentation\/mapsindoors\/mpbookingservice"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/set(displayRule:location:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"set"},{"text":"(","kind":"text"},{"text":"displayRule","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule","text":"MPDisplayRule","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"text":"MPLocation","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Set and apply a display rule for the given MPLocation."}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/set(displayrule:location:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/set(displayRule:location:)","required":true,"title":"set(displayRule:location:)","role":"symbol","navigatorTitle":[{"text":"setWithDisplayRule:location:","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsService":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDirectionsService","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPDirectionsService"}],"url":"\/documentation\/mapsindoors\/mpdirectionsservice","kind":"symbol","title":"MPDirectionsService","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/apiKey":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/apiKey","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"apiKey"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/apikey","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"required":true,"role":"symbol","type":"topic","title":"apiKey","abstract":[{"type":"text","text":"Returns the currently set MapsIndoors api key."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/language":{"abstract":[{"type":"text","text":"Get or set the current language code (Uses the two-letter language code ISO 639-1)."}],"kind":"symbol","title":"language","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/language","navigatorTitle":[{"kind":"identifier","text":"language"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/language","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"language","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/ready":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ready"}],"type":"topic","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/ready","abstract":[{"type":"text","text":"Ready flag, indicating whether the SDK is loaded correctly and ready for use."}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/ready","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ready"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"ready"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/fetchAuthDetails()":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/fetchAuthDetails()","abstract":[{"type":"text","text":"Fetch authentication details using MapsIndoors API key."}],"required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchAuthDetails"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"MPAuthDetails","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPAuthDetails"},{"text":"?","kind":"text"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/fetchauthdetails()","kind":"symbol","title":"fetchAuthDetails()","navigatorTitle":[{"kind":"identifier","text":"fetchAuthDetailsWithCompletionHandler:"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/createLocationUpdateFactory()":{"title":"createLocationUpdateFactory()","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/createLocationUpdateFactory()","type":"topic","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/createlocationupdatefactory()","abstract":[{"text":"For creating instances of ``MPLocationUpdate`","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This approach of creating instances is subject to change"}],"navigatorTitle":[{"text":"createLocationUpdateFactory","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createLocationUpdateFactory","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationUpdateFactory","kind":"typeIdentifier","text":"MPLocationUpdateFactory"}],"kind":"symbol","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/directionsService":{"abstract":[{"type":"text","text":"Get a "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","isActive":true},{"type":"text","text":" to calculate a route between Locations."}],"kind":"symbol","title":"directionsService","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/directionsService","navigatorTitle":[{"text":"directionsService","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/directionsservice","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"directionsService","kind":"identifier"},{"kind":"text","text":": "},{"text":"MPDirectionsService","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDirectionsService","kind":"typeIdentifier"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/displayRuleFor(displayRuleType:)":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"displayRuleFor","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"displayRuleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDisplayRuleType","preciseIdentifier":"c:@M@MapsIndoors@E@MPDisplayRuleType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule","text":"MPDisplayRule","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"required":true,"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/displayrulefor(displayruletype:)","navigatorTitle":[{"kind":"identifier","text":"displayRuleForDisplayRuleType:"}],"title":"displayRuleFor(displayRuleType:)","abstract":[{"type":"text","text":"Get display rules used for various general styling (e.g. building outline)."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/displayRuleFor(displayRuleType:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/apply(userRoles:)":{"abstract":[{"text":"Set and apply a list of ","type":"text"},{"type":"codeVoice","code":"MPUserRole"},{"text":"s asynchronously","type":"text"}],"kind":"symbol","title":"apply(userRoles:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/apply(userRoles:)","navigatorTitle":[{"text":"applyWithUserRoles:completionHandler:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/apply(userroles:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"apply","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userRoles","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPUserRole","text":"MPUserRole","kind":"typeIdentifier"},{"text":"]) ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/locationWith(locationId:)":{"navigatorTitle":[{"text":"locationWithLocationId:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/locationwith(locationid:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locationWith","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"locationId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","text":"MPLocation"},{"kind":"text","text":"?"}],"abstract":[{"text":"Get the MPLocation with a given location id - if one exists.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationWith(locationId:)","type":"topic","title":"locationWith(locationId:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/buildingIn(bounds:)":{"title":"buildingIn(bounds:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"buildingIn","kind":"identifier"},{"kind":"text","text":"("},{"text":"bounds","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","text":"MPGeoBounds","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPBuilding","text":"MPBuilding"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get a buildings which lies within the given bounds."}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/buildingin(bounds:)","navigatorTitle":[{"text":"buildingInBounds:completionHandler:","kind":"identifier"}],"kind":"symbol","required":true,"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/buildingIn(bounds:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/venues()":{"abstract":[{"text":"Get all venues.","type":"text"}],"title":"venues()","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/venues()","navigatorTitle":[{"kind":"identifier","text":"venuesWithCompletionHandler:"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/venues()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"venues","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> ["},{"text":"MPVenue","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPVenue"},{"kind":"text","text":"]"}],"type":"topic","required":true},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/displayRuleFor(location:)":{"abstract":[{"text":"Get the display rule for a given MPLocation.","type":"text"}],"title":"displayRuleFor(location:)","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/displayRuleFor(location:)","navigatorTitle":[{"kind":"identifier","text":"displayRuleForLocation:"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/displayrulefor(location:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"displayRuleFor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","text":"MPLocation"},{"kind":"text","text":") -> "},{"text":"MPDisplayRule","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapsIndoorsShared","kind":"identifier"}],"navigatorTitle":[{"text":"MapsIndoorsShared","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared","abstract":[{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared","isActive":true},{"type":"text","text":" describes the main entry point to the SDK which is accessed via "},{"type":"codeVoice","code":"MPMapsIndoors\/shared"},{"text":".","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","title":"MapsIndoorsShared","url":"\/documentation\/mapsindoors\/mapsindoorsshared"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/availableUserRoles":{"title":"availableUserRoles","kind":"symbol","abstract":[{"type":"text","text":"Get the list of available user roles in the current solution."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/availableUserRoles","navigatorTitle":[{"text":"availableUserRoles","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/availableuserroles","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableUserRoles"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPUserRole","text":"MPUserRole","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/bookingService":{"role":"symbol","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/bookingservice","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/bookingService","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bookingService","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPBookingService","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPBookingService","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"bookingService","kind":"identifier"}],"type":"topic","abstract":[{"text":"Get a ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService","isActive":true,"type":"reference"},{"text":" to perform bookings in the booking system configured in the MapsIndoors CMS.","type":"text"}],"required":true,"title":"bookingService"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/locationsWith(query:filter:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","required":true,"role":"symbol","abstract":[{"type":"text","text":"Search for MPLocations using MPQuery and\/or MPFilter."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"locationsWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"query","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPQuery","text":"MPQuery","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"filter","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilter","text":"MPFilter"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> [","kind":"text"},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"text":"]","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/locationswith(query:filter:)","title":"locationsWith(query:filter:)","navigatorTitle":[{"text":"locationsWithQuery:filter:completionHandler:","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/venueWith(id:)":{"abstract":[{"type":"text","text":"Get the venue with a given id."}],"kind":"symbol","title":"venueWith(id:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/venueWith(id:)","navigatorTitle":[{"text":"venueWithId:completionHandler:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/venuewith(id:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"venueWith"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"text":"MPVenue","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPVenue"},{"kind":"text","text":"?"}],"type":"topic","required":true}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MapsIndoorsShared"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MapsIndoorsShared","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MapsIndoorsShared","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/apiKey","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/authToken","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/availableUserRoles","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/bookingService","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/datasetCacheManager","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/directionsService","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/eventLoggingDisabled","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/imageProvider","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/language","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/positionProvider","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/ready","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/sdkVersion","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/solution","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/userRoles"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/appData()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/apply(userRoles:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/buildingIn(bounds:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/buildingWith(id:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/buildings()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/categories()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/displayRuleFor(displayRuleType:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/displayRuleFor(location:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/displayRuleFor(type:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/fetchAuthDetails()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/isApiKeyValid(apiKey:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/isOfflineDataAvailable(apiKey:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/load(apiKey:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationWith(locationId:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(externalIds:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/register(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/set(displayRule:location:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/shutdown()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/synchronize()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/venueWith(id:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/venues()"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/createLocationUpdateFactory()"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsIndoorsShared"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"positionProvider","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1positionProvider\/title"},{"value":[{"text":"positionProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1positionProvider\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1solution\/title","value":"solution"},{"value":[{"text":"solution","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1solution\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1datasetCacheManager\/title","value":"datasetCacheManager","op":"replace"},{"value":[{"text":"datasetCacheManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1datasetCacheManager\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1buildingWith(id:)\/title","op":"replace","value":"buildingWithId:completionHandler:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1buildingWith(id:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"buildingWithId:completionHandler:"}],"op":"replace"},{"op":"replace","value":"synchronizeWithCompletionHandler:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1synchronize()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"synchronizeWithCompletionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1synchronize()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1displayRuleFor(type:)\/title","value":"displayRuleForType:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"displayRuleForType:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1displayRuleFor(type:)\/fragments"},{"value":"eventLoggingDisabled","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1eventLoggingDisabled\/title"},{"op":"replace","value":[{"kind":"identifier","text":"eventLoggingDisabled"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1eventLoggingDisabled\/fragments"},{"op":"replace","value":"imageProvider","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1imageProvider\/title"},{"value":[{"kind":"identifier","text":"imageProvider"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1imageProvider\/fragments","op":"replace"},{"value":"userRoles","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1userRoles\/title"},{"value":[{"text":"userRoles","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1userRoles\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(externalIds:)\/title","op":"replace","value":"locationsWithExternalIds:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"locationsWithExternalIds:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(externalIds:)\/fragments"},{"op":"replace","value":"shutdown","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1shutdown()\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1shutdown()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"shutdown"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1isOfflineDataAvailable(apiKey:)\/title","op":"replace","value":"isOfflineDataAvailableWithApiKey:completionHandler:"},{"value":[{"text":"- ","kind":"text"},{"text":"isOfflineDataAvailableWithApiKey:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1isOfflineDataAvailable(apiKey:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1buildings()\/title","value":"buildingsWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1buildings()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"buildingsWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1appData()\/title","value":"appDataWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1appData()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appDataWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1register(_:)\/title","value":"register:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1register(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"register:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1categories()\/title","value":"categoriesWithCompletionHandler:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1categories()\/fragments","value":[{"kind":"text","text":"- "},{"text":"categoriesWithCompletionHandler:","kind":"identifier"}]},{"op":"replace","value":"sdkVersion","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1sdkVersion\/title"},{"value":[{"kind":"identifier","text":"sdkVersion"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1sdkVersion\/fragments","op":"replace"},{"op":"replace","value":"isApiKeyValidWithApiKey:completionHandler:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1isApiKeyValid(apiKey:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1isApiKeyValid(apiKey:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isApiKeyValidWithApiKey:completionHandler:"}]},{"op":"replace","value":"authToken","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1authToken\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1authToken\/fragments","value":[{"text":"authToken","kind":"identifier"}]},{"op":"replace","value":"loadWithApiKey:completionHandler:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1load(apiKey:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadWithApiKey:completionHandler:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1load(apiKey:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService\/title","value":"MPBookingService"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService\/fragments","value":[{"text":"MPBookingService","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1set(displayRule:location:)\/title","op":"replace","value":"setWithDisplayRule:location:"},{"value":[{"text":"- ","kind":"text"},{"text":"setWithDisplayRule:location:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1set(displayRule:location:)\/fragments"},{"value":"MPDirectionsService","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPDirectionsService"}]},{"value":"apiKey","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1apiKey\/title","op":"replace"},{"value":[{"text":"apiKey","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1apiKey\/fragments"},{"value":"language","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1language\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1language\/fragments","value":[{"kind":"identifier","text":"language"}],"op":"replace"},{"value":"ready","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1ready\/title"},{"value":[{"kind":"identifier","text":"ready"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1ready\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1fetchAuthDetails()\/title","value":"fetchAuthDetailsWithCompletionHandler:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1fetchAuthDetails()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"fetchAuthDetailsWithCompletionHandler:"}],"op":"replace"},{"value":"createLocationUpdateFactory","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1createLocationUpdateFactory()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1createLocationUpdateFactory()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createLocationUpdateFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1directionsService\/title","value":"directionsService"},{"value":[{"text":"directionsService","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1directionsService\/fragments","op":"replace"},{"value":"displayRuleForDisplayRuleType:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1displayRuleFor(displayRuleType:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1displayRuleFor(displayRuleType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"displayRuleForDisplayRuleType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1apply(userRoles:)\/title","value":"applyWithUserRoles:completionHandler:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1apply(userRoles:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"applyWithUserRoles:completionHandler:","kind":"identifier"}]},{"value":"locationWithLocationId:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationWith(locationId:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationWith(locationId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"locationWithLocationId:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1buildingIn(bounds:)\/title","value":"buildingInBounds:completionHandler:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1buildingIn(bounds:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"buildingInBounds:completionHandler:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1venues()\/title","op":"replace","value":"venuesWithCompletionHandler:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1venues()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"venuesWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1displayRuleFor(location:)\/title","value":"displayRuleForLocation:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"displayRuleForLocation:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1displayRuleFor(location:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared\/title","value":"MapsIndoorsShared"},{"op":"replace","value":[{"kind":"identifier","text":"MapsIndoorsShared"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared\/fragments"},{"value":"availableUserRoles","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1availableUserRoles\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1availableUserRoles\/fragments","value":[{"text":"availableUserRoles","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1bookingService\/title","value":"bookingService","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1bookingService\/fragments","op":"replace","value":[{"kind":"identifier","text":"bookingService"}]},{"value":"locationsWithQuery:filter:completionHandler:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"locationsWithQuery:filter:completionHandler:","kind":"identifier"}]},{"value":"venueWithId:completionHandler:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1venueWith(id:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"venueWithId:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1venueWith(id:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}