{"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/appSettings","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/colorAccent","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/colorPrimary","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/colorPrimaryDark","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/menuInfo","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/venueImages"]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig"],"title":"MapsIndoors configuration data","generated":true}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPAppConfig","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPAppConfig","modules":[{"name":"MapsIndoors"}],"symbolKind":"protocol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPAppConfig"}],"navigatorTitle":[{"kind":"identifier","text":"MPAppConfig"}],"roleHeading":"Protocol","title":"MPAppConfig"},"abstract":[{"type":"text","text":"Provides the contextual information needed for setting up a map with specific MapsPeople site data."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/mapsindoors\/mpappconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpappconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"MapsPeopleWhite.png":{"type":"image","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAppConfig/venueImages":{"role":"symbol","abstract":[{"type":"text","text":"The list of URLs to download images for each venue."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"venueImages","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"kind":"symbol","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/venueImages","navigatorTitle":[{"kind":"identifier","text":"venueImages"}],"title":"venueImages","type":"topic","url":"\/documentation\/mapsindoors\/mpappconfig\/venueimages"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAppConfig":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig","abstract":[{"text":"Provides the contextual information needed for setting up a map with specific MapsPeople site data.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpappconfig","kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPAppConfig"}],"role":"symbol","title":"MPAppConfig","navigatorTitle":[{"kind":"identifier","text":"MPAppConfig"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAppConfig/colorPrimary":{"kind":"symbol","title":"colorPrimary","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/colorPrimary","type":"topic","role":"symbol","abstract":[{"text":"The primary color to use in the app.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpappconfig\/colorprimary","navigatorTitle":[{"text":"colorPrimary","kind":"identifier"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"colorPrimary","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAppConfig/menuInfo":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/menuInfo","title":"menuInfo","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An ordered list of menu items for a specified menu."}],"url":"\/documentation\/mapsindoors\/mpappconfig\/menuinfo","navigatorTitle":[{"kind":"identifier","text":"menuInfo"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"menuInfo","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPMenuInfo","text":"MPMenuInfo"},{"text":"]]?","kind":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolutionConfig":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig","abstract":[{"text":"MPSolutionConfig is the way to access the Solution settings made in the MapsIndoors CMS.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpsolutionconfig","navigatorTitle":[{"kind":"identifier","text":"MPSolutionConfig"}],"kind":"symbol","title":"MPSolutionConfig","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPSolutionConfig"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolution":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPSolution","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPSolution"}],"kind":"symbol","title":"MPSolution","abstract":[{"text":"The solution model holds data about the buildings and floors in a solution, plus additional meta-data.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution","url":"\/documentation\/mapsindoors\/mpsolution","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAppConfig/appSettings":{"kind":"symbol","title":"appSettings","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/appSettings","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The list of settings that have been defined for this solution in the CMS."}],"url":"\/documentation\/mapsindoors\/mpappconfig\/appsettings","navigatorTitle":[{"text":"appSettings","kind":"identifier"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appSettings"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAppConfig/colorPrimaryDark":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/colorPrimaryDark","title":"colorPrimaryDark","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The primary color to use for dark mode in the app."}],"url":"\/documentation\/mapsindoors\/mpappconfig\/colorprimarydark","navigatorTitle":[{"kind":"identifier","text":"colorPrimaryDark"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"colorPrimaryDark","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAppConfig/colorAccent":{"navigatorTitle":[{"kind":"identifier","text":"colorAccent"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/colorAccent","abstract":[{"type":"text","text":"The accent color to use in the app."}],"url":"\/documentation\/mapsindoors\/mpappconfig\/coloraccent","kind":"symbol","type":"topic","required":true,"role":"symbol","title":"colorAccent","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"colorAccent","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPAppConfig"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPAppConfig"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPAppConfig"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/appSettings","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/colorAccent","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/colorPrimary","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/colorPrimaryDark","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/menuInfo","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig\/venueImages"]}]},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig"],"generated":true,"title":"MapsIndoors configuration data"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPAppConfig","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig~1venueImages\/title","value":"venueImages"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig~1venueImages\/fragments","value":[{"text":"venueImages","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig\/title","value":"MPAppConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig\/fragments","value":[{"kind":"identifier","text":"MPAppConfig"}]},{"value":"colorPrimary","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig~1colorPrimary\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig~1colorPrimary\/fragments","value":[{"text":"colorPrimary","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig~1menuInfo\/title","op":"replace","value":"menuInfo"},{"value":[{"text":"menuInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig~1menuInfo\/fragments"},{"op":"replace","value":"MPSolutionConfig","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig\/fragments","value":[{"kind":"identifier","text":"MPSolutionConfig"}],"op":"replace"},{"value":"MPSolution","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution\/title","op":"replace"},{"value":[{"text":"MPSolution","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig~1appSettings\/title","value":"appSettings","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig~1appSettings\/fragments","value":[{"text":"appSettings","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig~1colorPrimaryDark\/title","value":"colorPrimaryDark"},{"value":[{"text":"colorPrimaryDark","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig~1colorPrimaryDark\/fragments"},{"op":"replace","value":"colorAccent","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig~1colorAccent\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig~1colorAccent\/fragments","value":[{"kind":"identifier","text":"colorAccent"}],"op":"replace"}]}]}