{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpAuthDetailsHandlerBlockType"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAuthDetails","preciseIdentifier":"c:objc(pl)MPAuthDetails","text":"MPAuthDetails"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"authDetails","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MPAuthDetails object with necessary authentication information."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error object."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpauthdetailshandlerblocktype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpauthdetailshandlerblocktype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpAuthDetailsHandlerBlockType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Authentication details callback handler block"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpAuthDetailsHandlerBlockType"}],"title":"mpAuthDetailsHandlerBlockType","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias","externalID":"c:MPMapsIndoors.h@T@mpAuthDetailsHandlerBlockType","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"mpAuthDetailsHandlerBlockType"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/mpAuthDetailsHandlerBlockType":{"role":"symbol","title":"mpAuthDetailsHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpAuthDetailsHandlerBlockType"}],"abstract":[{"type":"text","text":"Authentication details callback handler block"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpAuthDetailsHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpAuthDetailsHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpauthdetailshandlerblocktype"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPAuthDetails":{"role":"symbol","title":"MPAuthDetails","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPAuthDetails"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPAuthDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPAuthDetails"}],"url":"\/documentation\/mapsindoors\/mpauthdetails"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"mpAuthDetailsHandlerBlockType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mpAuthDetailsHandlerBlockType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"mpAuthDetailsHandlerBlockType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(id<MPAuthDetails>, NSError *)","preciseIdentifier":"c:BFv(#*Qoobjc(pl)MPAuthDetails#*$objc(cs)NSError)"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpAuthDetailsHandlerBlockType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpAuthDetailsHandlerBlockType\/title","value":"mpAuthDetailsHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpAuthDetailsHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpAuthDetailsHandlerBlockType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAuthDetails\/title","value":"MPAuthDetails"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPAuthDetails\/fragments","value":[{"kind":"identifier","text":"MPAuthDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}