{"variants":[{"paths":["\/documentation\/mapsindoors\/mpauthdetails"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpauthdetails"]}],"metadata":{"navigatorTitle":[{"text":"MPAuthDetails","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPAuthDetails","modules":[{"name":"MapsIndoors"}],"symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPAuthDetails","kind":"identifier"}],"roleHeading":"Protocol","title":"MPAuthDetails"},"abstract":[{"type":"text","text":"The OAuth2 details to be used for performing an OAuth2 login flow in an app using MapsIndoors."}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails\/authClients","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails\/authIssuer","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails\/authScope","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails\/isAuthRequired"],"title":"Instance Properties"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPAuthDetails","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAuthDetails":{"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpauthdetails","abstract":[{"type":"text","text":"The OAuth2 details to be used for performing an OAuth2 login flow in an app using MapsIndoors."}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPAuthDetails"}],"navigatorTitle":[{"text":"MPAuthDetails","kind":"identifier"}],"title":"MPAuthDetails"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAuthDetails/authIssuer":{"required":true,"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpauthdetails\/authissuer","abstract":[{"text":"The URL to the Authentication Issuer.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails\/authIssuer","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"authIssuer","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"authIssuer","kind":"identifier"}],"title":"authIssuer"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAuthDetails/authClients":{"required":true,"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpauthdetails\/authclients","abstract":[],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails\/authClients","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authClients"},{"text":": [","kind":"text"},{"text":"MPAuthClientInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPAuthClientInfo"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"authClients","kind":"identifier"}],"title":"authClients"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAuthDetails/isAuthRequired":{"required":true,"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpauthdetails\/isauthrequired","abstract":[{"text":"Find out if external authentication is required.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails\/isAuthRequired","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isAuthRequired","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isAuthRequired","kind":"identifier"}],"title":"isAuthRequired"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAuthDetails/authScope":{"required":true,"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpauthdetails\/authscope","abstract":[],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails\/authScope","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authScope"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"authScope"}],"title":"authScope"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MPAuthDetails"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","value":[{"text":"MPAuthDetails","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MPAuthDetails","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails\/authClients","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails\/authIssuer","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails\/authScope","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails\/isAuthRequired"]}]},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPAuthDetails","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails\/title","op":"replace","value":"MPAuthDetails"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails\/fragments","value":[{"kind":"identifier","text":"MPAuthDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails~1authIssuer\/title","value":"authIssuer","op":"replace"},{"value":[{"text":"authIssuer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails~1authIssuer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails~1authClients\/title","value":"authClients"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails~1authClients\/fragments","op":"replace","value":[{"kind":"identifier","text":"authClients"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails~1isAuthRequired\/title","op":"replace","value":"isAuthRequired"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails~1isAuthRequired\/fragments","value":[{"text":"isAuthRequired","kind":"identifier"}]},{"value":"authScope","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails~1authScope\/title","op":"replace"},{"value":[{"text":"authScope","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails~1authScope\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}