{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPAuthClientInfo","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPAuthClientInfo","kind":"identifier"}],"roleHeading":"Protocol","symbolKind":"protocol","role":"symbol","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"MPAuthClientInfo","kind":"identifier"}],"title":"MPAuthClientInfo"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPAuthClientInfo","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthClientInfo\/clientID","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthClientInfo\/preferredIDPS"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpauthclientinfo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpauthclientinfo"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthClientInfo"},"kind":"symbol","references":{"MapsPeopleWhite.png":{"alt":null,"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAuthClientInfo":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthClientInfo","abstract":[],"url":"\/documentation\/mapsindoors\/mpauthclientinfo","navigatorTitle":[{"kind":"identifier","text":"MPAuthClientInfo"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPAuthClientInfo","kind":"identifier"}],"title":"MPAuthClientInfo"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAuthClientInfo/clientID":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The Client ID from the Auth provider."}],"url":"\/documentation\/mapsindoors\/mpauthclientinfo\/clientid","role":"symbol","navigatorTitle":[{"text":"clientID","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthClientInfo\/clientID","type":"topic","required":true,"title":"clientID","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAuthClientInfo/preferredIDPS":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthClientInfo\/preferredIDPS","abstract":[{"type":"text","text":"A prioritzed list of service providers. They will be used in the order they appear in the array."}],"url":"\/documentation\/mapsindoors\/mpauthclientinfo\/preferredidps","navigatorTitle":[{"text":"preferredIDPS","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredIDPS"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"title":"preferredIDPS","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MPAuthClientInfo"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MPAuthClientInfo","kind":"identifier"}]},{"op":"replace","value":[{"text":"MPAuthClientInfo","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthClientInfo\/clientID","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthClientInfo\/preferredIDPS"]}],"op":"replace","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPAuthClientInfo","kind":"identifier"}]}],"kind":"declarations"}},{"value":"MPAuthClientInfo","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthClientInfo\/title"},{"value":[{"text":"MPAuthClientInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthClientInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthClientInfo~1clientID\/title","value":"clientID"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthClientInfo~1clientID\/fragments","op":"replace","value":[{"kind":"identifier","text":"clientID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthClientInfo~1preferredIDPS\/title","value":"preferredIDPS"},{"op":"replace","value":[{"text":"preferredIDPS","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthClientInfo~1preferredIDPS\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}