{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeacon"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbeacon-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbeacon-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)JSONModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)NSCopying","doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding","doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/beaconId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/building","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/floor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/geometry","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/latestTimeStamp","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/maxTxDistance","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/maxTxPower","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/rssi","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/venue"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeacon"}],"title":"MPBeacon","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPBeacon","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPBeacon"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeacon-swift.class/geometry":{"role":"symbol","title":"geometry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/geometry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"geometry"}],"url":"\/documentation\/mapsindoors\/mpbeacon-swift.class\/geometry"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeacon-swift.class/beaconId":{"role":"symbol","title":"beaconId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"beaconId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/beaconId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"beaconId"}],"url":"\/documentation\/mapsindoors\/mpbeacon-swift.class\/beaconid"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeacon-swift.class/venue":{"role":"symbol","title":"venue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"venue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/venue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"venue"}],"url":"\/documentation\/mapsindoors\/mpbeacon-swift.class\/venue"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeacon-swift.class/maxTxDistance":{"role":"symbol","title":"maxTxDistance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxTxDistance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/maxTxDistance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxTxDistance"}],"url":"\/documentation\/mapsindoors\/mpbeacon-swift.class\/maxtxdistance"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeacon-swift.class/floor":{"role":"symbol","title":"floor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/floor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floor"}],"url":"\/documentation\/mapsindoors\/mpbeacon-swift.class\/floor"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeacon-swift.class":{"role":"symbol","title":"MPBeacon","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeacon"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBeacon"}],"url":"\/documentation\/mapsindoors\/mpbeacon-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeacon-swift.class/building":{"role":"symbol","title":"building","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"building"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/building","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"building"}],"url":"\/documentation\/mapsindoors\/mpbeacon-swift.class\/building"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeacon-swift.class/latestTimeStamp":{"role":"symbol","title":"latestTimeStamp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"latestTimeStamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/latestTimeStamp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"latestTimeStamp"}],"url":"\/documentation\/mapsindoors\/mpbeacon-swift.class\/latesttimestamp"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeacon-swift.class/rssi":{"role":"symbol","title":"rssi","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rssi"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/rssi","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RSSI"}],"url":"\/documentation\/mapsindoors\/mpbeacon-swift.class\/rssi"},"doc://MapsIndoors/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCopying"},"doc://MapsIndoors/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPBeacon-swift.class/maxTxPower":{"role":"symbol","title":"maxTxPower","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxTxPower"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/maxTxPower","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxTxPower"}],"url":"\/documentation\/mapsindoors\/mpbeacon-swift.class\/maxtxpower"},"doc://MapsIndoors/objc(pl)AbstractJSONModelProtocol":{"type":"unresolvable","title":"JSONModel.AbstractJSONModelProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol"},"doc://MapsIndoors/objc(cs)JSONModel":{"type":"unresolvable","title":"JSONModel","identifier":"doc:\/\/MapsIndoors\/objc(cs)JSONModel"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPBeacon"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPBeacon"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPBeacon"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/beaconId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/building","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/floor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/geometry","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/latestTimeStamp","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/maxTxDistance","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/maxTxPower","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/rssi","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBeacon-swift.class\/venue"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBeacon"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSONModel","preciseIdentifier":"c:objc(cs)JSONModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class~1geometry\/title","value":"geometry"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class~1geometry\/fragments","value":[{"kind":"identifier","text":"geometry"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class~1beaconId\/title","value":"beaconId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class~1beaconId\/fragments","value":[{"kind":"identifier","text":"beaconId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class~1venue\/title","value":"venue"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class~1venue\/fragments","value":[{"kind":"identifier","text":"venue"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class~1maxTxDistance\/title","value":"maxTxDistance"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class~1maxTxDistance\/fragments","value":[{"kind":"identifier","text":"maxTxDistance"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class~1floor\/title","value":"floor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class~1floor\/fragments","value":[{"kind":"identifier","text":"floor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class\/title","value":"MPBeacon"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class\/fragments","value":[{"kind":"identifier","text":"MPBeacon"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class~1building\/title","value":"building"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class~1building\/fragments","value":[{"kind":"identifier","text":"building"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class~1latestTimeStamp\/title","value":"latestTimeStamp"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class~1latestTimeStamp\/fragments","value":[{"kind":"identifier","text":"latestTimeStamp"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class~1rssi\/title","value":"RSSI"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class~1rssi\/fragments","value":[{"kind":"identifier","text":"RSSI"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class~1maxTxPower\/title","value":"maxTxPower"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBeacon-swift.class~1maxTxPower\/fragments","value":[{"kind":"identifier","text":"maxTxPower"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}