{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpBookingCompletion"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBooking","preciseIdentifier":"c:objc(cs)MPBooking","text":"MPBooking"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbookingcompletion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbookingcompletion"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpBookingCompletion","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpBookingCompletion"}],"title":"mpBookingCompletion","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias","externalID":"c:MPBookingService.h@T@mpBookingCompletion","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"mpBookingCompletion"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPBooking":{"role":"symbol","title":"MPBooking","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBooking"}],"abstract":[{"type":"text","text":"MPBooking represents an existing booking object or a booking to be made."},{"type":"text","text":" "},{"type":"text","text":"bookingId will be non-null for an existing booking, and null for a booking to be made."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPBooking","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBooking"}],"url":"\/documentation\/mapsindoors\/mpbooking"},"doc://MapsIndoors/documentation/MapsIndoors/mpBookingCompletion":{"role":"symbol","title":"mpBookingCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpBookingCompletion"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpBookingCompletion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpBookingCompletion"}],"url":"\/documentation\/mapsindoors\/mpbookingcompletion"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"mpBookingCompletion"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mpBookingCompletion"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"mpBookingCompletion"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(MPBooking *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)MPBooking#*$objc(cs)NSError)"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpBookingCompletion"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBooking\/title","value":"MPBooking"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPBooking\/fragments","value":[{"kind":"identifier","text":"MPBooking"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpBookingCompletion\/title","value":"mpBookingCompletion"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpBookingCompletion\/fragments","value":[{"kind":"identifier","text":"mpBookingCompletion"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}