{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"type":"conformsTo","title":"Conforms To"}],"metadata":{"modules":[{"name":"MapsIndoors"}],"symbolKind":"class","roleHeading":"Class","title":"MPBooking","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBooking"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPBooking","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPBooking"}]},"abstract":[{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking","isActive":true,"type":"reference"},{"type":"text","text":" represents an existing booking object or a booking to be made."},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/bookingId"},{"type":"text","text":" will be non-"},{"code":"nil","type":"codeVoice"},{"text":" for an existing booking, and ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for a booking to be made."}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbooking"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpbooking"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBooking"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/bookingDescription","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/bookingId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/endTime","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/isManaged","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/location","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/locationId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/participantIds","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/startTime","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/title"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/asDictionary()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/initWith(dictionary:)"]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/Se":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se","title":"Swift.Decodable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/locationId":{"url":"\/documentation\/mapsindoors\/mpbooking\/locationid","title":"locationId","kind":"symbol","abstract":[{"type":"text","text":"The id of the Location the Booking occupies."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/locationId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"locationId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"locationId"}],"type":"topic","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/startTime":{"url":"\/documentation\/mapsindoors\/mpbooking\/starttime","title":"startTime","kind":"symbol","abstract":[{"type":"text","text":"The date and time the Booking starts,"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/startTime","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"startTime","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"startTime"}],"type":"topic","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/bookingDescription":{"url":"\/documentation\/mapsindoors\/mpbooking\/bookingdescription","title":"bookingDescription","kind":"symbol","abstract":[{"type":"text","text":"A description of the Booking. This will be the description in the associated event in the calendar system configured in the MapsIndoors CMS."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/bookingDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bookingDescription"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"bookingDescription"}],"type":"topic","role":"symbol"},"doc://com.mapspeople.mapsindoors/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapspeople.mapsindoors/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/location":{"url":"\/documentation\/mapsindoors\/mpbooking\/location","title":"location","kind":"symbol","abstract":[{"type":"text","text":"The Location the Booking occupies."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/location","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"location","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","text":"MPLocation","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"location"}],"type":"topic","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/endTime":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endTime"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"?"}],"url":"\/documentation\/mapsindoors\/mpbooking\/endtime","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/endTime","navigatorTitle":[{"kind":"identifier","text":"endTime"}],"role":"symbol","abstract":[{"text":"The date and time the Booking will end,","type":"text"}],"title":"endTime"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/init":{"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpbooking\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/init","type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"title":"init"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking":{"navigatorTitle":[{"kind":"identifier","text":"MPBooking"}],"role":"symbol","abstract":[{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking","isActive":true,"type":"reference"},{"type":"text","text":" represents an existing booking object or a booking to be made."},{"text":" ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/bookingId","isActive":true},{"type":"text","text":" will be non-"},{"type":"codeVoice","code":"nil"},{"text":" for an existing booking, and ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" for a booking to be made."}],"title":"MPBooking","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking","url":"\/documentation\/mapsindoors\/mpbooking","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPBooking","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/bookingId":{"navigatorTitle":[{"kind":"identifier","text":"bookingId"}],"role":"symbol","abstract":[{"type":"text","text":"The id of the Booking to be used for future references."}],"title":"bookingId","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/bookingId","url":"\/documentation\/mapsindoors\/mpbooking\/bookingid","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bookingId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/isManaged":{"navigatorTitle":[{"kind":"identifier","text":"isManaged"}],"url":"\/documentation\/mapsindoors\/mpbooking\/ismanaged","abstract":[{"type":"text","text":"Indicates whether this booking is managed by the MapsIndoors Booking Service or has been created by other means. Managed bookings are cancellable by the booking service."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/isManaged","kind":"symbol","title":"isManaged","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isManaged"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/title":{"type":"topic","abstract":[{"type":"text","text":"The title of the event in the calendar system configured in the MapsIndoors CMS."}],"title":"title","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"title"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/title","url":"\/documentation\/mapsindoors\/mpbooking\/title","role":"symbol","navigatorTitle":[{"text":"title","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/participantIds":{"title":"participantIds","role":"symbol","url":"\/documentation\/mapsindoors\/mpbooking\/participantids","abstract":[{"text":"The list of participants. The ids in the list are determined by the calendar system configured in the MapsIndoors CMS.","type":"text"}],"navigatorTitle":[{"text":"participantIds","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/participantIds","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"participantIds","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/initWith(dictionary:)":{"url":"\/documentation\/mapsindoors\/mpbooking\/initwith(dictionary:)","title":"initWith(dictionary:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/initWith(dictionary:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initWith","kind":"identifier"},{"kind":"text","text":"("},{"text":"dictionary","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking","text":"MPBooking","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"initWithDictionary:","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/asDictionary()":{"url":"\/documentation\/mapsindoors\/mpbooking\/asdictionary()","title":"asDictionary()","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/asDictionary()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"asDictionary","kind":"identifier"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"text":"asDictionary","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBooking/init(from:)":{"url":"\/documentation\/mapsindoors\/mpbooking\/init(from:)","title":"init(from:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"type":"topic","role":"symbol"},"doc://com.mapspeople.mapsindoors/SQ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapspeople.mapsindoors/SE":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MPBooking"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"MPBooking"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPBooking"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/bookingDescription","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/bookingId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/endTime","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/isManaged","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/location","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/locationId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/participantIds","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/startTime","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/title"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/asDictionary()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/init","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBooking\/initWith(dictionary:)"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBooking"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1locationId\/title","value":"locationId"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1locationId\/fragments","value":[{"kind":"identifier","text":"locationId"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1startTime\/title","op":"replace","value":"startTime"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1startTime\/fragments","value":[{"text":"startTime","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1bookingDescription\/title","value":"bookingDescription"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1bookingDescription\/fragments","op":"replace","value":[{"text":"bookingDescription","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1location\/title","op":"replace","value":"location"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1location\/fragments","value":[{"kind":"identifier","text":"location"}]},{"value":"endTime","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1endTime\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"endTime"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1endTime\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking\/title","value":"MPBooking","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPBooking"}]},{"op":"replace","value":"bookingId","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1bookingId\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1bookingId\/fragments","value":[{"kind":"identifier","text":"bookingId"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1isManaged\/title","value":"isManaged","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1isManaged\/fragments","value":[{"text":"isManaged","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"title","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1title\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1title\/fragments","value":[{"text":"title","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1participantIds\/title","value":"participantIds","op":"replace"},{"value":[{"text":"participantIds","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1participantIds\/fragments","op":"replace"},{"value":"initWithDictionary:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1initWith(dictionary:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDictionary:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1initWith(dictionary:)\/fragments","op":"replace"},{"value":"asDictionary","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1asDictionary()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBooking~1asDictionary()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"asDictionary","kind":"identifier"}]}]}]}