{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"metadata":{"externalID":"c:@M@MapsIndoors@objc(cs)MPBookableQuery","modules":[{"name":"MapsIndoors"}],"symbolKind":"class","title":"MPBookableQuery","role":"symbol","navigatorTitle":[{"text":"MPBookableQuery","kind":"identifier"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPBookableQuery"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBookableQuery"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Query object to be used with MPBookingService.getBookableLocationsUsingQuery().","type":"text"},{"type":"text","text":" "},{"text":"Queries are defined by a required timespan and a number of optional filter properties.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/init(startTime:endTime:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/building","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/category","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/endTime","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/floorIndex","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/location","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/locationType","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/startTime","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/venue"],"title":"Instance Properties"}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpbookablequery"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpbookablequery"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookableQuery/location":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mpbookablequery\/location","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/location","type":"topic","title":"location","abstract":[{"type":"text","text":"Optional filter for which Location the found Locations should either be or be contained in."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"location"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"location"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","text":"MPLocation","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookableQuery/init(startTime:endTime:)":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mpbookablequery\/init(starttime:endtime:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/init(startTime:endTime:)","type":"topic","title":"init(startTime:endTime:)","abstract":[{"text":"Initialize a query to see which Locations are available given the specified requirements.","type":"text"},{"type":"text","text":" "},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/startTime","type":"reference"},{"text":" and ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/endTime","type":"reference","isActive":true},{"text":" are required as a minimum.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"initWithStartTime:endTime:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"startTime","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":", "},{"text":"endTime","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookableQuery/category":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/category","title":"category","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"category","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"category","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpbookablequery\/category","abstract":[{"text":"Optional filter for which Category the found Locations should belong to.","type":"text"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookableQuery/venue":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"venue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPVenue","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPVenue"},{"text":"?","kind":"text"}],"title":"venue","navigatorTitle":[{"kind":"identifier","text":"venue"}],"url":"\/documentation\/mapsindoors\/mpbookablequery\/venue","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/venue","role":"symbol","abstract":[{"text":"Optional filter for which Venue the found Locations should be contained in.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookableQuery":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPBookableQuery","kind":"identifier"}],"title":"MPBookableQuery","navigatorTitle":[{"text":"MPBookableQuery","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpbookablequery","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery","role":"symbol","abstract":[{"type":"text","text":"Query object to be used with MPBookingService.getBookableLocationsUsingQuery()."},{"type":"text","text":" "},{"text":"Queries are defined by a required timespan and a number of optional filter properties.","type":"text"}],"type":"topic","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookableQuery/locationType":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mpbookablequery\/locationtype","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/locationType","type":"topic","title":"locationType","abstract":[{"text":"Optional filter for what the found Locations should belong to.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"locationType","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"locationType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookableQuery/startTime":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mpbookablequery\/starttime","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/startTime","type":"topic","title":"startTime","abstract":[{"type":"text","text":"Required start date for your potential booking."}],"role":"symbol","navigatorTitle":[{"text":"startTime","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"startTime","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookableQuery/endTime":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mpbookablequery\/endtime","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/endTime","title":"endTime","abstract":[{"text":"Required end date for your potential booking.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"endTime","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"endTime"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookableQuery/building":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mpbookablequery\/building","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/building","type":"topic","title":"building","abstract":[{"text":"Optional filter for which Building the found Locations should be contained in.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"building"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"building","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPBuilding","text":"MPBuilding","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP"},"doc://com.mapspeople.mapsindoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP"},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookableQuery/floorIndex":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mpbookablequery\/floorindex","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/floorIndex","type":"topic","title":"floorIndex","abstract":[{"text":"Optional filter for which Floor the found Locations should belong to.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"floorIndex","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"floorIndex","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}]},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"identifier":"MapsPeopleWhite.png","type":"image"},"doc://com.mapspeople.mapsindoors/SQ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MPBookableQuery","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MPBookableQuery","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MPBookableQuery","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/building","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/category","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/endTime","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/floorIndex","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/location","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/locationType","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/startTime","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/venue"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookableQuery\/init(startTime:endTime:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPBookableQuery","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]},"op":"replace"},{"op":"replace","value":"location","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1location\/title"},{"op":"replace","value":[{"kind":"identifier","text":"location"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1location\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1init(startTime:endTime:)\/title","op":"replace","value":"initWithStartTime:endTime:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1init(startTime:endTime:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStartTime:endTime:"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1category\/title","value":"category","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"category"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1category\/fragments"},{"value":"venue","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1venue\/title"},{"value":[{"text":"venue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1venue\/fragments","op":"replace"},{"value":"MPBookableQuery","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery\/fragments","value":[{"kind":"identifier","text":"MPBookableQuery"}]},{"op":"replace","value":"locationType","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1locationType\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1locationType\/fragments","op":"replace","value":[{"kind":"identifier","text":"locationType"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1startTime\/title","value":"startTime","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1startTime\/fragments","value":[{"kind":"identifier","text":"startTime"}]},{"op":"replace","value":"endTime","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1endTime\/title"},{"value":[{"kind":"identifier","text":"endTime"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1endTime\/fragments"},{"value":"building","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1building\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1building\/fragments","value":[{"kind":"identifier","text":"building"}]},{"value":"floorIndex","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1floorIndex\/title"},{"op":"replace","value":[{"text":"floorIndex","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookableQuery~1floorIndex\/fragments"}]}]}