{"abstract":[{"text":"Booking authentication configuration model. This may be used if the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService"},{"type":"text","text":" should book on behalf of an authenticated user."}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingAuthConfig\/init(accessToken:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingAuthConfig\/accessToken","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingAuthConfig\/tenantId"]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPBookingAuthConfig","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPBookingAuthConfig","roleHeading":"Class","modules":[{"name":"MapsIndoors"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPBookingAuthConfig"}],"title":"MPBookingAuthConfig","symbolKind":"class"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingAuthConfig","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPBookingAuthConfig","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpbookingauthconfig"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpbookingauthconfig"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingAuthConfig":{"role":"symbol","abstract":[{"text":"Booking authentication configuration model. This may be used if the ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService","isActive":true,"type":"reference"},{"type":"text","text":" should book on behalf of an authenticated user."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpbookingauthconfig","navigatorTitle":[{"kind":"identifier","text":"MPBookingAuthConfig"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingAuthConfig","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBookingAuthConfig"}],"title":"MPBookingAuthConfig"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingAuthConfig/accessToken":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingAuthConfig\/accessToken","navigatorTitle":[{"kind":"identifier","text":"accessToken"}],"abstract":[{"text":"Set the access token that must be used when performing bookings.","type":"text"}],"role":"symbol","title":"accessToken","url":"\/documentation\/mapsindoors\/mpbookingauthconfig\/accesstoken","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessToken","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingAuthConfig/init(accessToken:)":{"abstract":[{"text":"Constructor that takes an access token.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingAuthConfig\/init(accessToken:)","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"accessToken","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithAccessToken:"}],"title":"init(accessToken:)","url":"\/documentation\/mapsindoors\/mpbookingauthconfig\/init(accesstoken:)"},"doc://com.mapspeople.mapsindoors/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapspeople.mapsindoors/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","title":"Swift.Equatable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingAuthConfig/tenantId":{"abstract":[{"type":"text","text":"Set the tenant id that must be used when performing bookings. This is relevant in scenarios where a location can be booked in more than one tenant."}],"type":"topic","title":"tenantId","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tenantId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingAuthConfig\/tenantId","url":"\/documentation\/mapsindoors\/mpbookingauthconfig\/tenantid","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tenantId"}]},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP"},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/SH":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"MapsPeopleWhite.png":{"alt":null,"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService":{"navigatorTitle":[{"text":"MPBookingService","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"MPBookingService allows for access to the MapsIndoors booking service."},{"type":"text","text":" "},{"text":"The booking service is a special integration that has to be enabled in the MapsIndoors cloud systems.","type":"text"}],"title":"MPBookingService","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService","url":"\/documentation\/mapsindoors\/mpbookingservice","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPBookingService","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MPBookingAuthConfig"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPBookingAuthConfig"}]},{"value":[{"kind":"identifier","text":"MPBookingAuthConfig"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingAuthConfig\/accessToken","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingAuthConfig\/tenantId"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingAuthConfig\/init(accessToken:)"]}]},{"value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPBookingAuthConfig"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingAuthConfig\/title","value":"MPBookingAuthConfig","op":"replace"},{"value":[{"text":"MPBookingAuthConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingAuthConfig\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingAuthConfig~1accessToken\/title","value":"accessToken"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingAuthConfig~1accessToken\/fragments","value":[{"kind":"identifier","text":"accessToken"}],"op":"replace"},{"value":"initWithAccessToken:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingAuthConfig~1init(accessToken:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingAuthConfig~1init(accessToken:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAccessToken:"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingAuthConfig~1tenantId\/title","value":"tenantId","op":"replace"},{"value":[{"kind":"identifier","text":"tenantId"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingAuthConfig~1tenantId\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService\/title","value":"MPBookingService","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService\/fragments","value":[{"kind":"identifier","text":"MPBookingService"}],"op":"replace"}]}]}