{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpbookingservice"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpbookingservice"]}],"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/authenticationConfig"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/bookableLocationsUsing(query:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/bookingsUsing(query:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/cancelBooking(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/locationsConfiguredForBooking(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/performBooking(_:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/sharedInstance"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPBookingService","kind":"identifier"}]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"inlineContent":[{"text":"The service allows for:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"querying for bookable items, e.g. find a “meeting room from 10-12”.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"getting the current bookings for a user or a location, e.g. “when is this room booked”."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"booking and cancelling bookings."}],"type":"paragraph"}]}]}]}],"sections":[],"abstract":[{"type":"text","text":"MPBookingService allows for access to the MapsIndoors booking service."},{"text":" ","type":"text"},{"type":"text","text":"The booking service is a special integration that has to be enabled in the MapsIndoors cloud systems."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService"},"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPBookingService"}],"navigatorTitle":[{"text":"MPBookingService","kind":"identifier"}],"role":"symbol","modules":[{"name":"MapsIndoors"}],"title":"MPBookingService","externalID":"c:@M@MapsIndoors@objc(pl)MPBookingService","roleHeading":"Protocol","symbolKind":"protocol"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService/bookingsUsing(query:)":{"role":"symbol","kind":"symbol","title":"bookingsUsing(query:)","url":"\/documentation\/mapsindoors\/mpbookingservice\/bookingsusing(query:)","abstract":[{"type":"text","text":"Get existing booking according the the given "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingsQuery","isActive":true}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"bookingsUsingQuery:completionHandler:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bookingsUsing","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"query"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBookingsQuery","text":"MPBookingsQuery"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking","text":"MPBooking","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/bookingsUsing(query:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService/authenticationConfig":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mpbookingservice\/authenticationconfig","type":"topic","abstract":[{"text":"Set authentication configuration. This may be used if the Booking Service should book on behalf of an authenticated user. Otherwise the attempted bookings will be anonymous.","type":"text"}],"required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/authenticationConfig","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authenticationConfig"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBookingAuthConfig","text":"MPBookingAuthConfig","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"authenticationConfig","kind":"identifier"}],"title":"authenticationConfig"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService/bookableLocationsUsing(query:)":{"abstract":[{"text":"Query for bookable locations given the query filter.","type":"text"}],"type":"topic","title":"bookableLocationsUsing(query:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bookableLocationsUsing"},{"text":"(","kind":"text"},{"text":"query","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBookableQuery","text":"MPBookableQuery","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"kind":"text","text":"]?"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/bookableLocationsUsing(query:)","url":"\/documentation\/mapsindoors\/mpbookingservice\/bookablelocationsusing(query:)","required":true,"role":"symbol","navigatorTitle":[{"text":"bookableLocationsUsingQuery:completionHandler:","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService/performBooking(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"performBooking","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking","text":"MPBooking","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"MPBooking","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"performBooking:completionHandler:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Book the resource identified by the booking parameter.","type":"text"}],"title":"performBooking(_:)","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/performBooking(_:)","url":"\/documentation\/mapsindoors\/mpbookingservice\/performbooking(_:)","type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService/locationsConfiguredForBooking(_:)":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/locationsConfiguredForBooking(_:)","abstract":[{"type":"text","text":"Query for locations that are configured for booking given the query."}],"title":"locationsConfiguredForBooking(_:)","kind":"symbol","navigatorTitle":[{"text":"locationsConfiguredForBooking:completionHandler:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpbookingservice\/locationsconfiguredforbooking(_:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"locationsConfiguredForBooking","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBookableQuery","text":"MPBookableQuery","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"MPLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"text":"]?","kind":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService/sharedInstance":{"role":"symbol","abstract":[],"kind":"symbol","required":true,"url":"\/documentation\/mapsindoors\/mpbookingservice\/sharedinstance","navigatorTitle":[{"text":"sharedInstance","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/sharedInstance","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"text":": ","kind":"text"},{"text":"MPBookingService","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPBookingService","kind":"typeIdentifier"}],"title":"sharedInstance"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService":{"navigatorTitle":[{"text":"MPBookingService","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"MPBookingService allows for access to the MapsIndoors booking service."},{"type":"text","text":" "},{"text":"The booking service is a special integration that has to be enabled in the MapsIndoors cloud systems.","type":"text"}],"title":"MPBookingService","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService","url":"\/documentation\/mapsindoors\/mpbookingservice","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPBookingService","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService/cancelBooking(_:)":{"role":"symbol","abstract":[{"type":"text","text":"Cancel the booking identified by the booking parameter."}],"kind":"symbol","required":true,"url":"\/documentation\/mapsindoors\/mpbookingservice\/cancelbooking(_:)","navigatorTitle":[{"kind":"identifier","text":"cancelBooking:completionHandler:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/cancelBooking(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancelBooking"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPBooking","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPBooking","text":"MPBooking","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"cancelBooking(_:)"},"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingsQuery":{"role":"symbol","kind":"symbol","title":"MPBookingsQuery","url":"\/documentation\/mapsindoors\/mpbookingsquery","abstract":[{"type":"text","text":"Query object to be used with "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/bookingsUsing(query:)","isActive":true},{"type":"text","text":" "},{"type":"text","text":"Queries can be either for a location or a user (organizerId), and may optionally be limited to a given timespan."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPBookingsQuery"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPBookingsQuery","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingsQuery"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MPBookingService","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"MPBookingService","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MPBookingService","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/authenticationConfig"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/bookableLocationsUsing(query:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/bookingsUsing(query:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/cancelBooking(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/locationsConfiguredForBooking(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/performBooking(_:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService\/sharedInstance"],"title":"Type Properties"}],"op":"replace","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPBookingService","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"bookingsUsingQuery:completionHandler:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1bookingsUsing(query:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1bookingsUsing(query:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"bookingsUsingQuery:completionHandler:","kind":"identifier"}],"op":"replace"},{"value":"authenticationConfig","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1authenticationConfig\/title"},{"value":[{"kind":"identifier","text":"authenticationConfig"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1authenticationConfig\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1bookableLocationsUsing(query:)\/title","value":"bookableLocationsUsingQuery:completionHandler:"},{"value":[{"kind":"text","text":"- "},{"text":"bookableLocationsUsingQuery:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1bookableLocationsUsing(query:)\/fragments","op":"replace"},{"value":"performBooking:completionHandler:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1performBooking(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"performBooking:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1performBooking(_:)\/fragments"},{"value":"locationsConfiguredForBooking:completionHandler:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1locationsConfiguredForBooking(_:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1locationsConfiguredForBooking(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"locationsConfiguredForBooking:completionHandler:"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1sharedInstance\/title","value":"sharedInstance","op":"replace"},{"value":[{"text":"sharedInstance","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1sharedInstance\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService\/title","op":"replace","value":"MPBookingService"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService\/fragments","value":[{"text":"MPBookingService","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1cancelBooking(_:)\/title","value":"cancelBooking:completionHandler:"},{"value":[{"kind":"text","text":"- "},{"text":"cancelBooking:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService~1cancelBooking(_:)\/fragments"},{"value":"MPBookingsQuery","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingsQuery\/title","op":"replace"},{"op":"replace","value":[{"text":"MPBookingsQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingsQuery\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}