{"sections":[],"abstract":[{"type":"text","text":"Holds relevant data for a single building, and the buildings floor levels."}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"metadata":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPBuilding"}],"roleHeading":"Protocol","symbolKind":"protocol","title":"MPBuilding","navigatorTitle":[{"kind":"identifier","text":"MPBuilding"}],"modules":[{"name":"MapsIndoors"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPBuilding"},"variants":[{"paths":["\/documentation\/mapsindoors\/mpbuilding"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbuilding"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation"],"title":"MapsIndoors entities","generated":true}],"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/address","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/administrativeId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/anchor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/boundingBox","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/buildingId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/currentFloor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/defaultFloor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/externalId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/floors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/geometry","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/properties","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/venueId"],"title":"Instance Properties"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(MPBuilding) ","kind":"text"},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPBuilding","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPEntity","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity","kind":"typeIdentifier","text":"MPEntity"}]}],"kind":"declarations"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue":{"role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPVenue"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","navigatorTitle":[{"kind":"identifier","text":"MPVenue"}],"url":"\/documentation\/mapsindoors\/mpvenue","kind":"symbol","title":"MPVenue","abstract":[{"text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data.","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPEntity":{"role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPEntity","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity","navigatorTitle":[{"kind":"identifier","text":"MPEntity"}],"url":"\/documentation\/mapsindoors\/mpentity","kind":"symbol","title":"MPEntity","abstract":[{"text":"MPEntity is a general protocol implemented by ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","isActive":true},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","type":"reference"},{"type":"text","text":"."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding/administrativeId":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"administrativeId","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/administrativeId","navigatorTitle":[{"text":"administrativeId","kind":"identifier"}],"abstract":[{"type":"text","text":"The Building administrative id."}],"url":"\/documentation\/mapsindoors\/mpbuilding\/administrativeid","type":"topic","kind":"symbol","role":"symbol","title":"administrativeId"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding/currentFloor":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"currentFloor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Holds the current floor."}],"required":true,"navigatorTitle":[{"text":"currentFloor","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpbuilding\/currentfloor","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/currentFloor","title":"currentFloor","role":"symbol","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding/buildingId":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buildingId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"text":"The Building id.","type":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"buildingId"}],"url":"\/documentation\/mapsindoors\/mpbuilding\/buildingid","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/buildingId","title":"buildingId","role":"symbol","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding/venueId":{"title":"venueId","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/venueId","navigatorTitle":[{"kind":"identifier","text":"venueId"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"venueId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/mapsindoors\/mpbuilding\/venueid","role":"symbol","required":true,"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The id of the Venue the Building is part of."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFloor":{"url":"\/documentation\/mapsindoors\/mpfloor","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor","type":"topic","abstract":[{"text":"Floor data model. Holds the floor geometry, display name, z-index and id of the building it belongs to.","type":"text"}],"kind":"symbol","title":"MPFloor","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPFloor","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPFloor"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding/address":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"address","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"The Building address."}],"required":true,"navigatorTitle":[{"text":"address","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpbuilding\/address","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/address","title":"address","role":"symbol","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding/properties":{"required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/properties","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"properties"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationField","text":"MPLocationField","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"properties"}],"url":"\/documentation\/mapsindoors\/mpbuilding\/properties","abstract":[{"type":"text","text":"Dictionary of custom properties of the Building."}],"title":"properties","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding/boundingBox":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"boundingBox"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","text":"MPGeoBounds","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"The geographic bounds for the building."}],"required":true,"navigatorTitle":[{"text":"boundingBox","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpbuilding\/boundingbox","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/boundingBox","title":"boundingBox","role":"symbol","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding/name":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","abstract":[{"text":"The Building name.","type":"text"}],"required":true,"navigatorTitle":[{"text":"name","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpbuilding\/name","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/name","title":"name","role":"symbol","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding/anchor":{"title":"anchor","type":"topic","url":"\/documentation\/mapsindoors\/mpbuilding\/anchor","required":true,"abstract":[{"type":"text","text":"The Building anchor coordinate."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"anchor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","text":"MPPoint"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"anchor","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/anchor"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation":{"navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLocation","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mplocation","title":"MPLocation","abstract":[{"type":"text","text":"This holds the data for a single location and a marker to display the data on a map."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding/floors":{"title":"floors","url":"\/documentation\/mapsindoors\/mpbuilding\/floors","type":"topic","required":true,"abstract":[{"text":"The Building floors. Since this is a Dictionary the order of floors is not guaranteed.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"floors","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"MPFloor","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPFloor"},{"text":"]?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"floors"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/floors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding/geometry":{"required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/geometry","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPolygonGeometry","kind":"typeIdentifier","text":"MPPolygonGeometry"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"geometry","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpbuilding\/geometry","abstract":[{"text":"The polygon geometry describing the Building outline.","type":"text"}],"title":"geometry","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPBuilding"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPBuilding"}],"type":"topic","abstract":[{"text":"Holds relevant data for a single building, and the buildings floor levels.","type":"text"}],"title":"MPBuilding","url":"\/documentation\/mapsindoors\/mpbuilding","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding/defaultFloor":{"kind":"symbol","navigatorTitle":[{"text":"defaultFloor","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultFloor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"text":"The buildings default floor. Is used by MPMapControl to determine which floor to show if a user have not already selected a floor.","type":"text"}],"title":"defaultFloor","url":"\/documentation\/mapsindoors\/mpbuilding\/defaultfloor","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/defaultFloor","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding/externalId":{"required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/externalId","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"externalId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"externalId","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpbuilding\/externalid","kind":"symbol","title":"externalId","abstract":[{"type":"text","text":"External id."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"value":"MPBuilding","op":"replace","path":"\/metadata\/title"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MPBuilding"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"MPBuilding","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/address","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/administrativeId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/anchor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/boundingBox","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/buildingId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/currentFloor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/defaultFloor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/externalId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/floors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/geometry","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/properties","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/venueId"]}]},{"value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"MapsIndoors entities","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"MPBuilding","kind":"identifier"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPEntity","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity","kind":"typeIdentifier","text":"MPEntity"},{"kind":"text","text":">"}],"platforms":["iOS"]}]}},{"value":"MPVenue","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/fragments","value":[{"kind":"identifier","text":"MPVenue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntity\/title","value":"MPEntity"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntity\/fragments","value":[{"kind":"identifier","text":"MPEntity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1administrativeId\/title","value":"administrativeId"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1administrativeId\/fragments","value":[{"text":"administrativeId","kind":"identifier"}],"op":"replace"},{"value":"currentFloor","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1currentFloor\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1currentFloor\/fragments","op":"replace","value":[{"kind":"identifier","text":"currentFloor"}]},{"op":"replace","value":"buildingId","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1buildingId\/title"},{"value":[{"kind":"identifier","text":"buildingId"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1buildingId\/fragments","op":"replace"},{"op":"replace","value":"venueId","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1venueId\/title"},{"value":[{"text":"venueId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1venueId\/fragments","op":"replace"},{"value":"MPFloor","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MPFloor"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor\/fragments","op":"replace"},{"op":"replace","value":"address","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1address\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1address\/fragments","value":[{"text":"address","kind":"identifier"}]},{"value":"properties","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1properties\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1properties\/fragments","value":[{"text":"properties","kind":"identifier"}]},{"value":"boundingBox","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1boundingBox\/title"},{"op":"replace","value":[{"text":"boundingBox","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1boundingBox\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1name\/title","op":"replace","value":"name"},{"value":[{"kind":"identifier","text":"name"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1name\/fragments","op":"replace"},{"value":"anchor","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1anchor\/title"},{"value":[{"text":"anchor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1anchor\/fragments","op":"replace"},{"value":"MPLocation","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/fragments","op":"replace","value":[{"text":"MPLocation","kind":"identifier"}]},{"op":"replace","value":"floors","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1floors\/title"},{"op":"replace","value":[{"text":"floors","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1floors\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1geometry\/title","value":"geometry"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1geometry\/fragments","value":[{"kind":"identifier","text":"geometry"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/title","op":"replace","value":"MPBuilding"},{"value":[{"kind":"identifier","text":"MPBuilding"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/fragments"},{"value":"defaultFloor","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1defaultFloor\/title"},{"value":[{"kind":"identifier","text":"defaultFloor"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1defaultFloor\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1externalId\/title","value":"externalId"},{"value":[{"text":"externalId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1externalId\/fragments"}]}]}