{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Protocol","externalID":"c:@M@MapsIndoors@objc(pl)MPCameraPosition","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPCameraPosition","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPCameraPosition"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"protocol","title":"MPCameraPosition"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPCameraPosition","kind":"identifier"}]}],"kind":"declarations"}],"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/bearing","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/target","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/viewingAngle","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/zoom"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/camera(target:zoom:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpcameraposition"]},{"paths":["\/documentation\/mapsindoors\/mpcameraposition"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraPosition/zoom":{"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/zoom","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"zoom"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"navigatorTitle":[{"kind":"identifier","text":"zoom"}],"required":true,"title":"zoom","abstract":[{"text":"The zoom level of the camera.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpcameraposition\/zoom"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraPosition/target":{"title":"target","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/target","abstract":[{"type":"text","text":"Location on the Earth towards which the camera points."}],"type":"topic","role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"target"},{"kind":"text","text":": "},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"navigatorTitle":[{"kind":"identifier","text":"target"}],"url":"\/documentation\/mapsindoors\/mpcameraposition\/target"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraPosition/bearing":{"required":true,"title":"bearing","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"bearing"}],"url":"\/documentation\/mapsindoors\/mpcameraposition\/bearing","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bearing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/bearing","abstract":[{"text":"The bearing of the map, measured in degrees clockwise from true north.","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraPosition/camera(target:zoom:)":{"required":true,"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Get a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition"},{"text":" for a particular target and zoom level.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"target"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"zoom","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPCameraPosition","text":"MPCameraPosition"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"cameraWithTarget:zoom:"}],"url":"\/documentation\/mapsindoors\/mpcameraposition\/camera(target:zoom:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/camera(target:zoom:)","title":"camera(target:zoom:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraPosition":{"title":"MPCameraPosition","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPCameraPosition","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPCameraPosition"}],"url":"\/documentation\/mapsindoors\/mpcameraposition"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraPosition/viewingAngle":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/viewingAngle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewingAngle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"viewingAngle","navigatorTitle":[{"text":"viewingAngle","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpcameraposition\/viewingangle","abstract":[{"text":"The angle toward the horizon measured in degrees, with 0 degrees resulting in a top-down view for a two-dimensional map.","type":"text"}],"required":true,"kind":"symbol","role":"symbol"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","value":"MPCameraPosition","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"text":"MPCameraPosition","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MPCameraPosition","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/bearing","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/target","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/viewingAngle","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/zoom"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/camera(target:zoom:)"]}]},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPCameraPosition","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1zoom\/title","op":"replace","value":"zoom"},{"value":[{"kind":"identifier","text":"zoom"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1zoom\/fragments"},{"op":"replace","value":"target","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1target\/title"},{"value":[{"text":"target","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1target\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1bearing\/title","value":"bearing"},{"op":"replace","value":[{"text":"bearing","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1bearing\/fragments"},{"value":"cameraWithTarget:zoom:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1camera(target:zoom:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1camera(target:zoom:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"cameraWithTarget:zoom:","kind":"identifier"}]},{"value":"MPCameraPosition","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPCameraPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1viewingAngle\/title","value":"viewingAngle"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1viewingAngle\/fragments","value":[{"text":"viewingAngle","kind":"identifier"}],"op":"replace"}]}]}