{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPCameraViewFitMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/mapsindoors\/mpcameraviewfitmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpcameraviewfitmode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH","doc:\/\/com.mapspeople.mapsindoors\/SY"],"title":"Conforms To","type":"conformsTo"}],"kind":"symbol","metadata":{"externalID":"c:@M@MapsIndoors@E@MPCameraViewFitMode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPCameraViewFitMode"}],"symbolKind":"enum","roleHeading":"Enumeration","title":"MPCameraViewFitMode","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"MPCameraViewFitMode","kind":"identifier"}]},"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/firstStepAligned","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/northAligned","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/startToEndAligned"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/Equatable-Implementations","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"sections":[],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraViewFitMode/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/mapsindoors\/mpcameraviewfitmode\/rawrepresentable-implementations","kind":"article","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/RawRepresentable-Implementations"},"doc://com.mapspeople.mapsindoors/SY":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SY","title":"Swift.RawRepresentable"},"doc://com.mapspeople.mapsindoors/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","title":"Swift.Equatable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraViewFitMode/init(rawValue:)":{"title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"url":"\/documentation\/mapsindoors\/mpcameraviewfitmode\/init(rawvalue:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/init(rawValue:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraViewFitMode":{"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpcameraviewfitmode","title":"MPCameraViewFitMode","navigatorTitle":[{"text":"MPCameraViewFitMode","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MPCameraViewFitMode","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraViewFitMode/Equatable-Implementations":{"kind":"article","abstract":[],"type":"topic","url":"\/documentation\/mapsindoors\/mpcameraviewfitmode\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/Equatable-Implementations"},"doc://com.mapspeople.mapsindoors/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraViewFitMode/firstStepAligned":{"title":"MPCameraViewFitMode.firstStepAligned","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"firstStepAligned"}],"abstract":[{"type":"text","text":"Fit the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/bearing"},{"type":"text","text":" to point towards the first step of a route."}],"url":"\/documentation\/mapsindoors\/mpcameraviewfitmode\/firststepaligned","navigatorTitle":[{"text":"MPCameraViewFitModeFirstStepAligned","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/firstStepAligned","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraViewFitMode/northAligned":{"title":"MPCameraViewFitMode.northAligned","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"northAligned","kind":"identifier"}],"abstract":[{"text":"Fit the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/bearing"},{"type":"text","text":" to point towards north."}],"url":"\/documentation\/mapsindoors\/mpcameraviewfitmode\/northaligned","navigatorTitle":[{"text":"MPCameraViewFitModeNorthAligned","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/northAligned"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraViewFitMode/startToEndAligned":{"title":"MPCameraViewFitMode.startToEndAligned","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startToEndAligned"}],"abstract":[{"type":"text","text":"Fit the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/bearing"},{"type":"text","text":" to point towards the entire route."}],"url":"\/documentation\/mapsindoors\/mpcameraviewfitmode\/starttoendaligned","navigatorTitle":[{"kind":"identifier","text":"MPCameraViewFitModeStartToEndAligned"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/startToEndAligned"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCameraPosition/bearing":{"title":"bearing","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bearing","kind":"identifier"},{"kind":"text","text":": "},{"text":"CLLocationDirection","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection"}],"abstract":[{"type":"text","text":"The bearing of the map, measured in degrees clockwise from true north."}],"url":"\/documentation\/mapsindoors\/mpcameraposition\/bearing","navigatorTitle":[{"text":"bearing","kind":"identifier"}],"kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraPosition\/bearing","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"MPCameraViewFitMode","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"MPCameraViewFitMode","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPCameraViewFitMode"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/firstStepAligned","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/northAligned","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCameraViewFitMode\/startToEndAligned"],"title":"Enumeration Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPCameraViewFitMode"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"MPCameraViewFitMode","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPCameraViewFitMode"}]},{"op":"replace","value":"MPCameraViewFitModeFirstStepAligned","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode~1firstStepAligned\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode~1firstStepAligned\/fragments","value":[{"kind":"identifier","text":"MPCameraViewFitModeFirstStepAligned"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode~1northAligned\/title","op":"replace","value":"MPCameraViewFitModeNorthAligned"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode~1northAligned\/fragments","value":[{"text":"MPCameraViewFitModeNorthAligned","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode~1startToEndAligned\/title","value":"MPCameraViewFitModeStartToEndAligned","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraViewFitMode~1startToEndAligned\/fragments","value":[{"kind":"identifier","text":"MPCameraViewFitModeStartToEndAligned"}],"op":"replace"},{"value":"bearing","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1bearing\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCameraPosition~1bearing\/fragments","value":[{"kind":"identifier","text":"bearing"}]}]}]}