{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpCategoriesHandlerBlockType"},{"kind":"text","text":" = (["},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataField-swift.class","preciseIdentifier":"c:objc(cs)MPDataField","text":"MPDataField"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"categories","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Array of categories. Will be nil if an error occurred"}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error object. Will be nil if fetching was complete"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpcategorieshandlerblocktype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpcategorieshandlerblocktype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpCategoriesHandlerBlockType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Callback block for getting category data or handling error in doing so."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpCategoriesHandlerBlockType"}],"title":"mpCategoriesHandlerBlockType","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias","externalID":"c:MPCategoriesProvider.h@T@mpCategoriesHandlerBlockType","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"mpCategoriesHandlerBlockType"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/mpCategoriesHandlerBlockType":{"role":"symbol","title":"mpCategoriesHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpCategoriesHandlerBlockType"}],"abstract":[{"type":"text","text":"Callback block for getting category data or handling error in doing so."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpCategoriesHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpCategoriesHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpcategorieshandlerblocktype"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataField-swift.class":{"role":"symbol","title":"MPDataField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataField"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataField-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataField"}],"url":"\/documentation\/mapsindoors\/mpdatafield-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"mpCategoriesHandlerBlockType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mpCategoriesHandlerBlockType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"mpCategoriesHandlerBlockType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(NSArray<MPDataField *> *, NSError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpCategoriesHandlerBlockType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpCategoriesHandlerBlockType\/title","value":"mpCategoriesHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpCategoriesHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpCategoriesHandlerBlockType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataField-swift.class\/title","value":"MPDataField"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataField-swift.class\/fragments","value":[{"kind":"identifier","text":"MPDataField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}