{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"sections":[],"metadata":{"modules":[{"name":"MapsIndoors"}],"roleHeading":"Class","role":"symbol","title":"MPContextualInfoSettings","externalID":"c:@M@MapsIndoors@objc(cs)MPContextualInfoSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPContextualInfoSettings"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"MPContextualInfoSettings"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"text":"Settings for showing contextual info along the rendered route.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/categories","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/infoScope","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/maxDistance","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/types"],"title":"Instance Properties"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPContextualInfoSettings"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpcontextualinfosettings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpcontextualinfosettings"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoScope/iconAndName":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconAndName"}],"navigatorTitle":[{"text":"MPContextualInfoScopeIconAndName","kind":"identifier"}],"title":"MPContextualInfoScope.iconAndName","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/iconAndName","url":"\/documentation\/mapsindoors\/mpcontextualinfoscope\/iconandname","type":"topic"},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoSettings/categories":{"navigatorTitle":[{"kind":"identifier","text":"categories"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/categories","url":"\/documentation\/mapsindoors\/mpcontextualinfosettings\/categories","title":"categories","abstract":[{"type":"text","text":"The Categories of Location that should be used when showing text and icon for a start or end marker."},{"type":"text","text":" "},{"type":"text","text":"If no Categories are supplied, all Categories of Locations will be considered."}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"categories","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoSettings/maxDistance":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/maxDistance","kind":"symbol","role":"symbol","title":"maxDistance","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxDistance","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpcontextualinfosettings\/maxdistance","abstract":[{"text":"The maximum distance in meters allowed for using text and icon from a Location. Default of 5 meters.","type":"text"}],"navigatorTitle":[{"text":"maxDistance","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoSettings/types":{"navigatorTitle":[{"text":"types","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"types"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The Types of Location that should be used when showing text and icon for a start or end marker."},{"type":"text","text":" "},{"type":"text","text":"If no Types are supplied, all Types of Locations will be considered."}],"type":"topic","kind":"symbol","url":"\/documentation\/mapsindoors\/mpcontextualinfosettings\/types","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/types","title":"types"},"doc://com.mapspeople.mapsindoors/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoSettings":{"role":"symbol","abstract":[{"text":"Settings for showing contextual info along the rendered route.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MPContextualInfoSettings"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPContextualInfoSettings","kind":"identifier"}],"title":"MPContextualInfoSettings","url":"\/documentation\/mapsindoors\/mpcontextualinfosettings","type":"topic","kind":"symbol"},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP"},"doc://com.mapspeople.mapsindoors/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoSettings/init":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"title":"init","url":"\/documentation\/mapsindoors\/mpcontextualinfosettings\/init","type":"topic","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoSettings/infoScope":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"infoScope","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@E@MPContextualInfoScope","kind":"typeIdentifier","text":"MPContextualInfoScope"}],"navigatorTitle":[{"kind":"identifier","text":"infoScope"}],"title":"infoScope","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/infoScope","abstract":[{"type":"text","text":"Which content should be used. Default is "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/iconAndName"},{"type":"text","text":"."}],"url":"\/documentation\/mapsindoors\/mpcontextualinfosettings\/infoscope","type":"topic"},"doc://com.mapspeople.mapsindoors/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MPContextualInfoSettings"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"MPContextualInfoSettings","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPContextualInfoSettings"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/categories","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/infoScope","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/maxDistance","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/types"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoSettings\/init"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPContextualInfoSettings"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MPContextualInfoScopeIconAndName","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope~1iconAndName\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MPContextualInfoScopeIconAndName"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope~1iconAndName\/fragments"},{"value":"categories","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings~1categories\/title"},{"value":[{"text":"categories","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings~1categories\/fragments","op":"replace"},{"value":"maxDistance","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings~1maxDistance\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings~1maxDistance\/fragments","op":"replace","value":[{"kind":"identifier","text":"maxDistance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings~1types\/title","value":"types"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings~1types\/fragments","value":[{"text":"types","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings\/title","value":"MPContextualInfoSettings","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings\/fragments","value":[{"kind":"identifier","text":"MPContextualInfoSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings~1infoScope\/title","value":"infoScope"},{"op":"replace","value":[{"text":"infoScope","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoSettings~1infoScope\/fragments"}]}]}