{"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH","doc:\/\/com.mapspeople.mapsindoors\/SY"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope"},"variants":[{"paths":["\/documentation\/mapsindoors\/mpcontextualinfoscope"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpcontextualinfoscope"]}],"metadata":{"externalID":"c:@M@MapsIndoors@E@MPContextualInfoScope","roleHeading":"Enumeration","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPContextualInfoScope"}],"symbolKind":"enum","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"MPContextualInfoScope","kind":"identifier"}],"title":"MPContextualInfoScope"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Which information to show from the Location close to the end of a route leg."}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/icon","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/iconAndName","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/name"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/Equatable-Implementations","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPContextualInfoScope"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoScope/name":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/name","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MPContextualInfoScopeName"}],"title":"MPContextualInfoScope.name","url":"\/documentation\/mapsindoors\/mpcontextualinfoscope\/name","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoScope/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/mapsindoors\/mpcontextualinfoscope\/rawrepresentable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/RawRepresentable-Implementations","type":"topic","kind":"article"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoScope/icon":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/icon","navigatorTitle":[{"text":"MPContextualInfoScopeIcon","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpcontextualinfoscope\/icon","kind":"symbol","title":"MPContextualInfoScope.icon","abstract":[]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoScope":{"title":"MPContextualInfoScope","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPContextualInfoScope"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPContextualInfoScope","kind":"identifier"}],"abstract":[{"type":"text","text":"Which information to show from the Location close to the end of a route leg."}],"url":"\/documentation\/mapsindoors\/mpcontextualinfoscope","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope","kind":"symbol"},"doc://com.mapspeople.mapsindoors/SY":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SY","title":"Swift.RawRepresentable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoScope/init(rawValue:)":{"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/mapsindoors\/mpcontextualinfoscope\/init(rawvalue:)","role":"symbol","type":"topic","kind":"symbol","title":"init(rawValue:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoScope/Equatable-Implementations":{"kind":"article","role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/mapsindoors\/mpcontextualinfoscope\/equatable-implementations","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/Equatable-Implementations","abstract":[],"type":"topic"},"doc://com.mapspeople.mapsindoors/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","title":"Swift.Equatable"},"doc://com.mapspeople.mapsindoors/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPContextualInfoScope/iconAndName":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconAndName"}],"navigatorTitle":[{"text":"MPContextualInfoScopeIconAndName","kind":"identifier"}],"title":"MPContextualInfoScope.iconAndName","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/iconAndName","url":"\/documentation\/mapsindoors\/mpcontextualinfoscope\/iconandname","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"MPContextualInfoScope"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MPContextualInfoScope","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MPContextualInfoScope","kind":"identifier"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/icon","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/iconAndName","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPContextualInfoScope\/name"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPContextualInfoScope"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope~1name\/title","op":"replace","value":"MPContextualInfoScopeName"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope~1name\/fragments","value":[{"kind":"identifier","text":"MPContextualInfoScopeName"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope~1icon\/title","op":"replace","value":"MPContextualInfoScopeIcon"},{"op":"replace","value":[{"text":"MPContextualInfoScopeIcon","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope~1icon\/fragments"},{"value":"MPContextualInfoScope","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope\/title"},{"value":[{"kind":"identifier","text":"MPContextualInfoScope"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope~1iconAndName\/title","value":"MPContextualInfoScopeIconAndName"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPContextualInfoScope~1iconAndName\/fragments","value":[{"kind":"identifier","text":"MPContextualInfoScopeIconAndName"}],"op":"replace"}]}]}