{"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Model for live event information for a given Location."}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpcountliveupdate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpcountliveupdate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCountLiveUpdate"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate"]},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"metadata":{"roleHeading":"Class","role":"symbol","externalID":"c:@M@MapsIndoors@objc(cs)MPCountLiveUpdate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPCountLiveUpdate","kind":"identifier"}],"symbolKind":"class","title":"MPCountLiveUpdate","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"MPCountLiveUpdate","kind":"identifier"}]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCountLiveUpdate\/count"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPCountLiveUpdate","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/SE":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCountLiveUpdate/initWithLiveUpdate:":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCountLiveUpdate\/initWithLiveUpdate:","fragments":[{"kind":"text","text":"- "},{"text":"initWithLiveUpdate:","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpcountliveupdate\/initwithliveupdate:","navigatorTitle":[{"kind":"identifier","text":"initWithLiveUpdate:"}],"title":"initWithLiveUpdate:","abstract":[],"role":"symbol","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate":{"abstract":[{"text":"Model for a Live Update. Used in ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","isActive":true,"type":"reference"}],"title":"MPLiveUpdate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPLiveUpdate"}],"role":"symbol","navigatorTitle":[{"text":"MPLiveUpdate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","type":"topic","url":"\/documentation\/mapsindoors\/mpliveupdate"},"doc://com.mapspeople.mapsindoors/SQ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCountLiveUpdate/count":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"count","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"count"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCountLiveUpdate\/count","url":"\/documentation\/mapsindoors\/mpcountliveupdate\/count","type":"topic","abstract":[{"type":"text","text":"The number of times an arbitrary event has been fired for a given Location."}],"title":"count","role":"symbol"},"doc://com.mapspeople.mapsindoors/SH":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/getLiveUpdate(forDomainType:)":{"abstract":[{"type":"text","text":"Get a live update based on a known domain type."}],"title":"getLiveUpdate(forDomainType:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getLiveUpdate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forDomainType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"MPLiveUpdate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate"},{"kind":"text","text":"?"}],"role":"symbol","required":true,"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","navigatorTitle":[{"text":"getLiveUpdateForDomainType:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mplocation\/getliveupdate(fordomaintype:)","type":"topic"},"doc://com.mapspeople.mapsindoors/Se":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCountLiveUpdate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPCountLiveUpdate"}],"navigatorTitle":[{"text":"MPCountLiveUpdate","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCountLiveUpdate","url":"\/documentation\/mapsindoors\/mpcountliveupdate","abstract":[{"type":"text","text":"Model for live event information for a given Location."}],"type":"topic","title":"MPCountLiveUpdate","role":"symbol"},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","value":"MPCountLiveUpdate","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MPCountLiveUpdate","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"MPCountLiveUpdate"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCountLiveUpdate\/count"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCountLiveUpdate\/initWithLiveUpdate:"],"title":"Instance Methods"}],"path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"MPCountLiveUpdate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"MPLiveUpdate","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/title","value":"MPLiveUpdate"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/fragments","value":[{"text":"MPLiveUpdate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCountLiveUpdate~1count\/title","value":"count","op":"replace"},{"value":[{"text":"count","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCountLiveUpdate~1count\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/title","op":"replace","value":"getLiveUpdateForDomainType:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getLiveUpdateForDomainType:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCountLiveUpdate\/title","value":"MPCountLiveUpdate"},{"value":[{"kind":"identifier","text":"MPCountLiveUpdate"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCountLiveUpdate\/fragments"}]}]}