{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"The different ways to handle collisions of icons and labels on the map.","type":"text"}],"sections":[],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH","doc:\/\/com.mapspeople.mapsindoors\/SY"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MPCollisionHandling","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"variants":[{"paths":["\/documentation\/mapsindoors\/mpcollisionhandling"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpcollisionhandling"]}],"metadata":{"symbolKind":"enum","externalID":"c:@M@MapsIndoors@E@MPCollisionHandling","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPCollisionHandling"}],"role":"symbol","modules":[{"name":"MapsIndoors"}],"title":"MPCollisionHandling","navigatorTitle":[{"text":"MPCollisionHandling","kind":"identifier"}],"roleHeading":"Enumeration"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/allowOverLap","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/removeIconAndLabel","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/removeIconFirst","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/removeLabelFirst"]},{"title":"Initializers","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/Equatable-Implementations","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCollisionHandling":{"role":"symbol","navigatorTitle":[{"text":"MPCollisionHandling","kind":"identifier"}],"title":"MPCollisionHandling","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling","url":"\/documentation\/mapsindoors\/mpcollisionhandling","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPCollisionHandling","kind":"identifier"}],"abstract":[{"text":"The different ways to handle collisions of icons and labels on the map.","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCollisionHandling/removeIconAndLabel":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeIconAndLabel","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpcollisionhandling\/removeiconandlabel","abstract":[{"type":"text","text":"Will hide markers if they are overlapping with another marker."}],"title":"MPCollisionHandling.removeIconAndLabel","navigatorTitle":[{"kind":"identifier","text":"MPCollisionHandlingRemoveIconAndLabel"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/removeIconAndLabel","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCollisionHandling/removeIconFirst":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"removeIconFirst","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpcollisionhandling\/removeiconfirst","abstract":[{"type":"text","text":"Will hide icons if they are overlapping with another feature such as an icon or another label."}],"title":"MPCollisionHandling.removeIconFirst","navigatorTitle":[{"text":"MPCollisionHandlingRemoveIconFirst","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/removeIconFirst","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCollisionHandling/Equatable-Implementations":{"role":"collectionGroup","url":"\/documentation\/mapsindoors\/mpcollisionhandling\/equatable-implementations","abstract":[],"title":"Equatable Implementations","kind":"article","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/Equatable-Implementations","type":"topic"},"doc://com.mapspeople.mapsindoors/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se"},"doc://com.mapspeople.mapsindoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH"},"doc://com.mapspeople.mapsindoors/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCollisionHandling/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","abstract":[],"kind":"article","url":"\/documentation\/mapsindoors\/mpcollisionhandling\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/RawRepresentable-Implementations","role":"collectionGroup"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCollisionHandling/allowOverLap":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"allowOverLap","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpcollisionhandling\/allowoverlap","abstract":[{"type":"text","text":"Will allow markers to overlap, nothing will be removed."}],"title":"MPCollisionHandling.allowOverLap","navigatorTitle":[{"kind":"identifier","text":"MPCollisionHandlingAllowOverLap"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/allowOverLap","type":"topic"},"doc://com.mapspeople.mapsindoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCollisionHandling/removeLabelFirst":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeLabelFirst","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpcollisionhandling\/removelabelfirst","abstract":[{"type":"text","text":"Will hide labels if they are overlapping with another feature such as an icon or another label."}],"title":"MPCollisionHandling.removeLabelFirst","navigatorTitle":[{"kind":"identifier","text":"MPCollisionHandlingRemoveLabelFirst"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/removeLabelFirst","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCollisionHandling/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpcollisionhandling\/init(rawvalue:)","abstract":[],"title":"init(rawValue:)","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/init(rawValue:)","type":"topic"},"doc://com.mapspeople.mapsindoors/SY":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image","alt":null}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"MPCollisionHandling","path":"\/metadata\/title","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPCollisionHandling"}]},{"op":"replace","value":[{"text":"MPCollisionHandling","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/allowOverLap","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/removeIconAndLabel","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/removeIconFirst","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCollisionHandling\/removeLabelFirst"]}],"op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPCollisionHandling","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"MPCollisionHandling","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling\/title"},{"op":"replace","value":[{"text":"MPCollisionHandling","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling~1removeIconAndLabel\/title","value":"MPCollisionHandlingRemoveIconAndLabel","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling~1removeIconAndLabel\/fragments","op":"replace","value":[{"text":"MPCollisionHandlingRemoveIconAndLabel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling~1removeIconFirst\/title","value":"MPCollisionHandlingRemoveIconFirst","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MPCollisionHandlingRemoveIconFirst"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling~1removeIconFirst\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling~1allowOverLap\/title","value":"MPCollisionHandlingAllowOverLap"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling~1allowOverLap\/fragments","value":[{"text":"MPCollisionHandlingAllowOverLap","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling~1removeLabelFirst\/title","op":"replace","value":"MPCollisionHandlingRemoveLabelFirst"},{"value":[{"text":"MPCollisionHandlingRemoveLabelFirst","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCollisionHandling~1removeLabelFirst\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}