{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPCustomClusterIcon","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"MPCustomClusterIcon"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPCustomClusterIcon","modules":[{"name":"MapsIndoors"}],"title":"MPCustomClusterIcon","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPCustomClusterIcon","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomClusterIcon","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Optionally create your own cluster icon for the SDK to use."}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomClusterIcon\/clusterIconFor(type:size:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpcustomclustericon"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpcustomclustericon"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomClusterIcon":{"url":"\/documentation\/mapsindoors\/mpcustomclustericon","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomClusterIcon","title":"MPCustomClusterIcon","abstract":[{"text":"Optionally create your own cluster icon for the SDK to use.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"MPCustomClusterIcon","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPCustomClusterIcon"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomClusterIcon/clusterIconFor(type:size:)":{"title":"clusterIconFor(type:size:)","role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpcustomclustericon\/clustericonfor(type:size:)","required":true,"navigatorTitle":[{"text":"clusterIconForType:size:","kind":"identifier"}],"abstract":[{"type":"text","text":"Given a cluster of a given type and size, provide an appropriate icon to represent the cluster."}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomClusterIcon\/clusterIconFor(type:size:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clusterIconFor","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"size","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","alt":null,"type":"image"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"value":"MPCustomClusterIcon","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"op":"replace","value":[{"kind":"identifier","text":"MPCustomClusterIcon"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPCustomClusterIcon"}],"op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomClusterIcon\/clusterIconFor(type:size:)"]}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"MPCustomClusterIcon","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomClusterIcon\/title","value":"MPCustomClusterIcon","op":"replace"},{"value":[{"kind":"identifier","text":"MPCustomClusterIcon"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomClusterIcon\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomClusterIcon~1clusterIconFor(type:size:)\/title","value":"clusterIconForType:size:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomClusterIcon~1clusterIconFor(type:size:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"clusterIconForType:size:","kind":"identifier"}]}]}]}