{"variants":[{"paths":["\/documentation\/mapsindoors\/mpcustomfloorselector"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpcustomfloorselector"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPCustomFloorSelector","kind":"identifier"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector"},"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/building","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/delegate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/floorIndex"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/onHide()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/onShow()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/remove()"],"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The protocol to conform to when building a floor selector for MapsIndoors."}],"metadata":{"navigatorTitle":[{"text":"MPCustomFloorSelector","kind":"identifier"}],"title":"MPCustomFloorSelector","symbolKind":"protocol","modules":[{"name":"MapsIndoors"}],"roleHeading":"Protocol","externalID":"c:@M@MapsIndoors@objc(pl)MPCustomFloorSelector","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPCustomFloorSelector"}],"role":"symbol"},"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomFloorSelector/onShow()":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/onShow()","title":"onShow()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onShow","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"onShow","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpcustomfloorselector\/onshow()","abstract":[{"type":"text","text":"Invoked when the SDK indicates to show the floor selector (e.g. a building is present in the viewport)."}],"required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomFloorSelector/floorIndex":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/floorIndex","title":"floorIndex","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"floorIndex","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"floorIndex"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpcustomfloorselector\/floorindex","abstract":[{"type":"text","text":"The current floor index of the floor selector. Setting this will switch to another Floor."}],"required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomFloorSelector/onHide()":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/onHide()","title":"onHide()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onHide"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"onHide","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpcustomfloorselector\/onhide()","abstract":[{"type":"text","text":"Invoked when the SDK indicates to hide the floor selector (e.g. no buildings are present in the viewport)."}],"required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomFloorSelector/delegate":{"kind":"symbol","abstract":[{"type":"text","text":"Delegate object to hold the floor change event method."}],"url":"\/documentation\/mapsindoors\/mpcustomfloorselector\/delegate","type":"topic","title":"delegate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPFloorSelectorDelegate","text":"MPFloorSelectorDelegate"},{"kind":"text","text":"?"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomFloorSelector/building":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/building","title":"building","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"building"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPBuilding","kind":"typeIdentifier","text":"MPBuilding"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"building","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpcustomfloorselector\/building","abstract":[{"type":"text","text":"The current building whose floors are shown in the floor selector. Setting this will switch to another Building."}],"required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomFloorSelector":{"title":"MPCustomFloorSelector","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPCustomFloorSelector","kind":"identifier"}],"abstract":[{"type":"text","text":"The protocol to conform to when building a floor selector for MapsIndoors."}],"url":"\/documentation\/mapsindoors\/mpcustomfloorselector","navigatorTitle":[{"text":"MPCustomFloorSelector","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector","type":"topic"},"MapsPeopleWhite.png":{"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null,"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomFloorSelector/remove()":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/remove()","title":"remove()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"remove"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpcustomfloorselector\/remove()","abstract":[{"type":"text","text":"Removes the floor selector view from its super view (usually the map view)."}],"required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"MPCustomFloorSelector","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"text":"MPCustomFloorSelector","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MPCustomFloorSelector","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/building","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/delegate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/floorIndex"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/onHide()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/onShow()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomFloorSelector\/remove()"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"MPCustomFloorSelector","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1onShow()\/title","value":"onShow","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onShow"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1onShow()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1floorIndex\/title","value":"floorIndex"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1floorIndex\/fragments","value":[{"text":"floorIndex","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1onHide()\/title","value":"onHide","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1onHide()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onHide","kind":"identifier"}],"op":"replace"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1delegate\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1delegate\/fragments","op":"replace","value":[{"text":"delegate","kind":"identifier"}]},{"value":"building","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1building\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1building\/fragments","value":[{"kind":"identifier","text":"building"}],"op":"replace"},{"value":"MPCustomFloorSelector","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector\/fragments","op":"replace","value":[{"text":"MPCustomFloorSelector","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1remove()\/title","op":"replace","value":"remove"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"remove"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomFloorSelector~1remove()\/fragments"}]}]}