{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomInfoWindow"},"kind":"symbol","abstract":[{"type":"text","text":"Optionally create your own info window for the SDK to use."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/mapsindoors\/mpcustominfowindow"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpcustominfowindow"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPCustomInfoWindow","kind":"identifier"}]}]}],"metadata":{"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPCustomInfoWindow","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"MPCustomInfoWindow"}],"modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPCustomInfoWindow"}],"symbolKind":"protocol","title":"MPCustomInfoWindow"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"sections":[],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomInfoWindow\/infoWindowFor(location:)"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomInfoWindow":{"role":"symbol","abstract":[{"text":"Optionally create your own info window for the SDK to use.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpcustominfowindow","navigatorTitle":[{"kind":"identifier","text":"MPCustomInfoWindow"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomInfoWindow","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPCustomInfoWindow","kind":"identifier"}],"title":"MPCustomInfoWindow"},"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCustomInfoWindow/infoWindowFor(location:)":{"role":"symbol","abstract":[{"text":"Called when a Location is selected, and if a UIView is returned from this method that UIView will be shown instead of the default MapsIndoors info window.","type":"text"}],"kind":"symbol","required":true,"url":"\/documentation\/mapsindoors\/mpcustominfowindow\/infowindowfor(location:)","navigatorTitle":[{"kind":"identifier","text":"infoWindowForLocation:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomInfoWindow\/infoWindowFor(location:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"infoWindowFor"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","text":"MPLocation","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"title":"infoWindowFor(location:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MPCustomInfoWindow","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"text":"MPCustomInfoWindow","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MPCustomInfoWindow"}]},{"value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCustomInfoWindow\/infoWindowFor(location:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPCustomInfoWindow"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomInfoWindow\/title","value":"MPCustomInfoWindow"},{"value":[{"kind":"identifier","text":"MPCustomInfoWindow"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomInfoWindow\/fragments","op":"replace"},{"value":"infoWindowForLocation:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomInfoWindow~1infoWindowFor(location:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCustomInfoWindow~1infoWindowFor(location:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"infoWindowForLocation:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}