{"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/basic","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/detailed","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/full"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/Equatable-Implementations","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCachingScope"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachingscope"]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachingscope"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Data set caching scope. Currently only a full cache (non-partial) scope is supported (basic and detailed scope will sync full dataset).","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope"},"sections":[],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH","doc:\/\/com.mapspeople.mapsindoors\/SY"],"kind":"relationships"}],"metadata":{"title":"MPDataSetCachingScope","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCachingScope"}],"roleHeading":"Enumeration","symbolKind":"enum","externalID":"c:@M@MapsIndoors@E@MPDataSetCachingScope","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCachingScope"}],"modules":[{"name":"MapsIndoors"}],"role":"symbol"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingScope/basic":{"title":"MPDataSetCachingScope.basic","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/basic","role":"symbol","abstract":[{"text":"Basic cache scope. Information about locations, buildings and venue and type images.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"basic","kind":"identifier"}],"navigatorTitle":[{"text":"MPDataSetCachingScopeBasic","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachingscope\/basic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingScope/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/init(rawValue:)","title":"init(rawValue:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachingscope\/init(rawvalue:)"},"doc://com.mapspeople.mapsindoors/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ"},"doc://com.mapspeople.mapsindoors/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SY"},"doc://com.mapspeople.mapsindoors/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingScope/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/RawRepresentable-Implementations","kind":"article","url":"\/documentation\/mapsindoors\/mpdatasetcachingscope\/rawrepresentable-implementations","abstract":[]},"MapsPeopleWhite.png":{"type":"image","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingScope/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/Equatable-Implementations","title":"Equatable Implementations","abstract":[],"kind":"article","role":"collectionGroup","url":"\/documentation\/mapsindoors\/mpdatasetcachingscope\/equatable-implementations"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingScope":{"navigatorTitle":[{"text":"MPDataSetCachingScope","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapsindoors\/mpdatasetcachingscope","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope","title":"MPDataSetCachingScope","role":"symbol","abstract":[{"text":"Data set caching scope. Currently only a full cache (non-partial) scope is supported (basic and detailed scope will sync full dataset).","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCachingScope"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingScope/full":{"navigatorTitle":[{"text":"MPDataSetCachingScopeFull","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachingscope\/full","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/full","title":"MPDataSetCachingScope.full","role":"symbol","abstract":[{"type":"text","text":"Full cache scope. All necessary content is downloaded for a data set to work offline."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"full","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingScope/detailed":{"title":"MPDataSetCachingScope.detailed","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/detailed","role":"symbol","abstract":[{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/basic","isActive":true},{"type":"text","text":" + location-specific images."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"detailed","kind":"identifier"}],"navigatorTitle":[{"text":"MPDataSetCachingScopeDetailed","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachingscope\/detailed"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","value":"MPDataSetCachingScope","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"kind":"identifier","text":"MPDataSetCachingScope"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MPDataSetCachingScope","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/basic","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/detailed","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingScope\/full"],"title":"Enumeration Cases"}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDataSetCachingScope","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope~1basic\/title","value":"MPDataSetCachingScopeBasic"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope~1basic\/fragments","op":"replace","value":[{"text":"MPDataSetCachingScopeBasic","kind":"identifier"}]},{"value":"MPDataSetCachingScope","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope\/title"},{"op":"replace","value":[{"text":"MPDataSetCachingScope","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope\/fragments"},{"value":"MPDataSetCachingScopeFull","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope~1full\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope~1full\/fragments","value":[{"text":"MPDataSetCachingScopeFull","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MPDataSetCachingScopeDetailed","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope~1detailed\/title"},{"value":[{"text":"MPDataSetCachingScopeDetailed","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingScope~1detailed\/fragments"}]}]}