{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPDataSetCacheManagerSizeDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Delegate protocol for getting callbacks when determining the size af dataset syncs.","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManager(_:didFetchSyncSizesForDataSet:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManager(_:willStartFetchingSyncSizesForDataSet:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManagerDidFinishFetchingSyncSizes(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManagerWillStartFetchingSyncSizes(_:)"],"title":"Instance Methods"}],"metadata":{"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManagerSizeDelegate","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPDataSetCacheManagerSizeDelegate","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"protocol","navigatorTitle":[{"text":"MPDataSetCacheManagerSizeDelegate","kind":"identifier"}],"title":"MPDataSetCacheManagerSizeDelegate"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerSizeDelegate/dataSetManager(_:didFetchSyncSizesForDataSet:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManager(_:didFetchSyncSizesForDataSet:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dataSetManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","text":"MPDataSetCacheManager"},{"kind":"text","text":", "},{"text":"didFetchSyncSizesForDataSet","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","text":"MPDataSetCache","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"dataSetManager(_:didFetchSyncSizesForDataSet:)","abstract":[{"type":"text","text":"Called to indicate the fnish of fetching sync size for a single dataset."}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate\/datasetmanager(_:didfetchsyncsizesfordataset:)","navigatorTitle":[{"text":"dataSetManager:didFetchSyncSizesForDataSet:","kind":"identifier"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerSizeDelegate/dataSetManager(_:willStartFetchingSyncSizesForDataSet:)":{"type":"topic","role":"symbol","url":"\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate\/datasetmanager(_:willstartfetchingsyncsizesfordataset:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSetManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","text":"MPDataSetCacheManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willStartFetchingSyncSizesForDataSet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","text":"MPDataSetCache"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManager(_:willStartFetchingSyncSizesForDataSet:)","abstract":[{"text":"Called to indicate the start of fetching sync size for a single dataset.","type":"text"}],"navigatorTitle":[{"text":"dataSetManager:willStartFetchingSyncSizesForDataSet:","kind":"identifier"}],"title":"dataSetManager(_:willStartFetchingSyncSizesForDataSet:)","required":true},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerSizeDelegate/dataSetManagerWillStartFetchingSyncSizes(_:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataSetManagerWillStartFetchingSyncSizes"},{"text":"(","kind":"text"},{"text":"MPDataSetCacheManager","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate\/datasetmanagerwillstartfetchingsyncsizes(_:)","role":"symbol","abstract":[{"type":"text","text":"Called when the DataSetManager starts determing sync sizes for its managed datasets."}],"title":"dataSetManagerWillStartFetchingSyncSizes(_:)","navigatorTitle":[{"text":"dataSetManagerWillStartFetchingSyncSizes:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManagerWillStartFetchingSyncSizes(_:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerSizeDelegate/dataSetManagerDidFinishFetchingSyncSizes(_:)":{"type":"topic","title":"dataSetManagerDidFinishFetchingSyncSizes(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSetManagerDidFinishFetchingSyncSizes","kind":"identifier"},{"kind":"text","text":"("},{"text":"MPDataSetCacheManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManagerDidFinishFetchingSyncSizes(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"dataSetManagerDidFinishFetchingSyncSizes:"}],"required":true,"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate\/datasetmanagerdidfinishfetchingsyncsizes(_:)","abstract":[{"text":"Called to indicate that the DataSetManager has finished determining sync sizes for all managed datasets.","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerSizeDelegate":{"type":"topic","title":"MPDataSetCacheManagerSizeDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPDataSetCacheManagerSizeDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagersizedelegate","abstract":[{"text":"Delegate protocol for getting callbacks when determining the size af dataset syncs.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPDataSetCacheManagerSizeDelegate"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MPDataSetCacheManagerSizeDelegate","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManager(_:didFetchSyncSizesForDataSet:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManager(_:willStartFetchingSyncSizesForDataSet:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManagerDidFinishFetchingSyncSizes(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerSizeDelegate\/dataSetManagerWillStartFetchingSyncSizes(_:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"text":">","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate~1dataSetManager(_:didFetchSyncSizesForDataSet:)\/title","value":"dataSetManager:didFetchSyncSizesForDataSet:"},{"value":[{"kind":"text","text":"- "},{"text":"dataSetManager:didFetchSyncSizesForDataSet:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate~1dataSetManager(_:didFetchSyncSizesForDataSet:)\/fragments"},{"op":"replace","value":"dataSetManager:willStartFetchingSyncSizesForDataSet:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate~1dataSetManager(_:willStartFetchingSyncSizesForDataSet:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dataSetManager:willStartFetchingSyncSizesForDataSet:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate~1dataSetManager(_:willStartFetchingSyncSizesForDataSet:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate~1dataSetManagerWillStartFetchingSyncSizes(_:)\/title","value":"dataSetManagerWillStartFetchingSyncSizes:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate~1dataSetManagerWillStartFetchingSyncSizes(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dataSetManagerWillStartFetchingSyncSizes:"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate~1dataSetManagerDidFinishFetchingSyncSizes(_:)\/title","op":"replace","value":"dataSetManagerDidFinishFetchingSyncSizes:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dataSetManagerDidFinishFetchingSyncSizes:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate~1dataSetManagerDidFinishFetchingSyncSizes(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate\/title","value":"MPDataSetCacheManagerSizeDelegate"},{"value":[{"kind":"identifier","text":"MPDataSetCacheManagerSizeDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerSizeDelegate\/fragments"}]}]}