{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Data set manager class.","type":"text"}],"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDataSetCacheManager","kind":"identifier"}],"roleHeading":"Protocol","externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManager"}],"title":"MPDataSetCacheManager","modules":[{"name":"MapsIndoors"}],"role":"symbol"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/delegate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/isSyncing","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/managedDataSets"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/addDataSet(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/addDataSet(_:cachingScope:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/cancelSynchronization()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/cancelSynchronizationOfCacheItems(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/dataSetForCurrentMapsIndoorsAPIKey()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/dataSetWithId(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/fetchSyncSizesFor(dataSetCaches:delegate:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/removeDataSet(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/setCachingScope(_:cacheItem:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/setCachingStrategy(_:cacheItem:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/synchronizeCacheItems(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/synchronizeContent()"],"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCacheManager"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanager"]}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/setCachingStrategy(_:cacheItem:)":{"title":"setCachingStrategy(_:cacheItem:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/setCachingStrategy(_:cacheItem:)","abstract":[{"type":"text","text":"Set a caching strategy for given cache item."}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/setcachingstrategy(_:cacheitem:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setCachingStrategy","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingStrategy","kind":"typeIdentifier","text":"MPDataSetCachingStrategy"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cacheItem"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem","text":"MPDataSetCacheItem"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"setCachingStrategy:cacheItem:"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/synchronizeContent()":{"title":"synchronizeContent()","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/synchronizeContent()","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/synchronizecontent()","abstract":[{"type":"text","text":"Fetch and update content for all managed data sets. The delegate object receives the completion event."}],"required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"synchronizeContent"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"synchronizeContent"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/cancelSynchronizationOfCacheItems(_:)":{"title":"cancelSynchronizationOfCacheItems(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/cancelSynchronizationOfCacheItems(_:)","abstract":[{"type":"text","text":"Cancel synchronization of data for the given cache items."}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/cancelsynchronizationofcacheitems(_:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"cancelSynchronizationOfCacheItems","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem","text":"MPDataSetCacheItem"},{"text":"])","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"cancelSynchronizationOfCacheItems:"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/dataSetWithId(_:)":{"title":"dataSetWithId(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/dataSetWithId(_:)","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/datasetwithid(_:)","abstract":[{"type":"text","text":"Get the dataset object for the given dataSetId."}],"required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSetWithId"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"dataSetWithId:","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/managedDataSets":{"title":"managedDataSets","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/managedDataSets","abstract":[{"type":"text","text":"List of managed data sets."}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/manageddatasets","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"managedDataSets","kind":"identifier"},{"kind":"text","text":": ["},{"text":"MPDataSetCache","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"managedDataSets"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/addDataSet(_:cachingScope:)":{"title":"addDataSet(_:cachingScope:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/addDataSet(_:cachingScope:)","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/adddataset(_:cachingscope:)","abstract":[{"type":"text","text":"Add data set to the list of managed data sets."}],"required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addDataSet"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"cachingScope","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingScope","kind":"typeIdentifier","text":"MPDataSetCachingScope"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","text":"MPDataSetCache"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"addDataSet:cachingScope:","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/fetchSyncSizesFor(dataSetCaches:delegate:)":{"title":"fetchSyncSizesFor(dataSetCaches:delegate:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/fetchSyncSizesFor(dataSetCaches:delegate:)","abstract":[{"text":"Determine synchronization sizes for the given set of MPDataSetCaches.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/fetchsyncsizesfor(datasetcaches:delegate:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchSyncSizesFor"},{"kind":"text","text":"("},{"text":"dataSetCaches","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache"},{"kind":"text","text":"], "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MPDataSetCacheManagerSizeDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManagerSizeDelegate"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"fetchSyncSizesForDataSetCaches:delegate:"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/addDataSet(_:)":{"title":"addDataSet(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/addDataSet(_:)","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/adddataset(_:)","abstract":[{"type":"text","text":"Add data set to the list of managed data sets."}],"required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addDataSet"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","text":"MPDataSetCache","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"addDataSet:"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/isSyncing":{"title":"isSyncing","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/isSyncing","abstract":[{"type":"text","text":"Synchronization state of manager. If true, the manager is currently synchronising."}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/issyncing","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isSyncing"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"isSyncing"}]},"MapsPeopleWhite.png":{"type":"image","alt":null,"identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/synchronizeCacheItems(_:)":{"navigatorTitle":[{"text":"synchronizeCacheItems:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/synchronizecacheitems(_:)","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"synchronizeCacheItems"},{"kind":"text","text":"(["},{"text":"MPDataSetCacheItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem"},{"kind":"text","text":"])"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/synchronizeCacheItems(_:)","abstract":[{"type":"text","text":"Fetch and update content for given cache items. The delegate object receives the completion event."}],"title":"synchronizeCacheItems(_:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/setCachingScope(_:cacheItem:)":{"title":"setCachingScope(_:cacheItem:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/setCachingScope(_:cacheItem:)","abstract":[{"type":"text","text":"Set a caching scope for given cache item."}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/setcachingscope(_:cacheitem:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCachingScope"},{"text":"(","kind":"text"},{"text":"MPDataSetCachingScope","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingScope"},{"kind":"text","text":", "},{"text":"cacheItem","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem","text":"MPDataSetCacheItem"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"setCachingScope:cacheItem:","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/cancelSynchronization()":{"title":"cancelSynchronization()","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/cancelSynchronization()","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/cancelsynchronization()","abstract":[{"type":"text","text":"Cancel any running synchronization of data sets."}],"required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelSynchronization"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"cancelSynchronization","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager":{"navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManager"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheManager"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager","abstract":[{"type":"text","text":"Data set manager class."}],"title":"MPDataSetCacheManager"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/dataSetForCurrentMapsIndoorsAPIKey()":{"title":"dataSetForCurrentMapsIndoorsAPIKey()","type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/datasetforcurrentmapsindoorsapikey()","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/dataSetForCurrentMapsIndoorsAPIKey()","role":"symbol","abstract":[{"type":"text","text":"The dataset-object for the current MapsIndoors API key \/ solution"}],"required":true,"navigatorTitle":[{"text":"dataSetForCurrentMapsIndoorsAPIKey","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataSetForCurrentMapsIndoorsAPIKey"},{"kind":"text","text":"() -> "},{"text":"MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/removeDataSet(_:)":{"type":"topic","title":"removeDataSet(_:)","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/removedataset(_:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/removeDataSet(_:)","role":"symbol","abstract":[{"type":"text","text":"Remove data set from the list of managed data sets. This will remove any cached content for that data set as well."}],"required":true,"navigatorTitle":[{"text":"removeDataSet:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeDataSet"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManager/delegate":{"title":"delegate","type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachemanager\/delegate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/delegate","role":"symbol","abstract":[{"type":"text","text":"Data set manager delegate."}],"required":true,"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManagerDelegate","text":"MPDataSetCacheManagerDelegate"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPDataSetCacheManager"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/delegate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/isSyncing","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/managedDataSets"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/addDataSet(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/addDataSet(_:cachingScope:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/cancelSynchronization()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/cancelSynchronizationOfCacheItems(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/dataSetForCurrentMapsIndoorsAPIKey()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/dataSetWithId(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/fetchSyncSizesFor(dataSetCaches:delegate:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/removeDataSet(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/setCachingScope(_:cacheItem:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/setCachingStrategy(_:cacheItem:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/synchronizeCacheItems(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManager\/synchronizeContent()"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDataSetCacheManager","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1setCachingStrategy(_:cacheItem:)\/title","value":"setCachingStrategy:cacheItem:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1setCachingStrategy(_:cacheItem:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setCachingStrategy:cacheItem:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1synchronizeContent()\/title","op":"replace","value":"synchronizeContent"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1synchronizeContent()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"synchronizeContent","kind":"identifier"}]},{"value":"cancelSynchronizationOfCacheItems:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1cancelSynchronizationOfCacheItems(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1cancelSynchronizationOfCacheItems(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"cancelSynchronizationOfCacheItems:","kind":"identifier"}]},{"op":"replace","value":"dataSetWithId:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1dataSetWithId(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dataSetWithId:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1dataSetWithId(_:)\/fragments"},{"value":"managedDataSets","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1managedDataSets\/title"},{"value":[{"kind":"identifier","text":"managedDataSets"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1managedDataSets\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1addDataSet(_:cachingScope:)\/title","value":"addDataSet:cachingScope:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1addDataSet(_:cachingScope:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addDataSet:cachingScope:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1fetchSyncSizesFor(dataSetCaches:delegate:)\/title","value":"fetchSyncSizesForDataSetCaches:delegate:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1fetchSyncSizesFor(dataSetCaches:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"fetchSyncSizesForDataSetCaches:delegate:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1addDataSet(_:)\/title","value":"addDataSet:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addDataSet:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1addDataSet(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1isSyncing\/title","value":"isSyncing"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1isSyncing\/fragments","value":[{"kind":"identifier","text":"isSyncing"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1synchronizeCacheItems(_:)\/title","value":"synchronizeCacheItems:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1synchronizeCacheItems(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"synchronizeCacheItems:"}]},{"value":"setCachingScope:cacheItem:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1setCachingScope(_:cacheItem:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCachingScope:cacheItem:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1setCachingScope(_:cacheItem:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1cancelSynchronization()\/title","value":"cancelSynchronization","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1cancelSynchronization()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"cancelSynchronization","kind":"identifier"}]},{"op":"replace","value":"MPDataSetCacheManager","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/title"},{"value":[{"text":"MPDataSetCacheManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1dataSetForCurrentMapsIndoorsAPIKey()\/title","value":"dataSetForCurrentMapsIndoorsAPIKey","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1dataSetForCurrentMapsIndoorsAPIKey()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"dataSetForCurrentMapsIndoorsAPIKey","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1removeDataSet(_:)\/title","value":"removeDataSet:"},{"value":[{"kind":"text","text":"- "},{"text":"removeDataSet:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1removeDataSet(_:)\/fragments"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1delegate\/title"},{"op":"replace","value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManager~1delegate\/fragments"}]}]}