{"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheManagerDelegate"}],"role":"symbol","modules":[{"name":"MapsIndoors"}],"roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManagerDelegate"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManagerDelegate","title":"MPDataSetCacheManagerDelegate","symbolKind":"protocol"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didAddDataSet:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didFinishSynchronizingDataSet:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didFinishSynchronizingItem:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didRemoveDataSet:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:willStartSynchronizingDataSet:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:willStartSynchronizingItem:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManagerDidFinishSynchronizing(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManagerWillStartSynchronizing(_:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate"]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDataSetCacheManagerDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}]}]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Data set manager delegate protocol."}],"references":{"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","title":"NSObject"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate/dataSetManager(_:willStartSynchronizingItem:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataSetManager","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"MPDataSetCacheManager","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willStartSynchronizingItem"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem","text":"MPDataSetCacheItem","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a cache item synchronisation is started."}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:willstartsynchronizingitem:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dataSetManager:willStartSynchronizingItem:"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:willStartSynchronizingItem:)","title":"dataSetManager(_:willStartSynchronizingItem:)","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate/dataSetManager(_:didRemoveDataSet:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataSetManager"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","text":"MPDataSetCacheManager"},{"text":", ","kind":"text"},{"text":"didRemoveDataSet","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:didremovedataset:)","navigatorTitle":[{"kind":"identifier","text":"dataSetManager:didRemoveDataSet:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didRemoveDataSet:)","kind":"symbol","abstract":[{"type":"text","text":"Called when a data set is removed from a data set manager."}],"title":"dataSetManager(_:didRemoveDataSet:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate/dataSetManager(_:willStartSynchronizingDataSet:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"dataSetManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MPDataSetCacheManager","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willStartSynchronizingDataSet"},{"text":": ","kind":"text"},{"text":"MPDataSetCache","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:willstartsynchronizingdataset:)","abstract":[{"type":"text","text":"Called when a data set is scheduled for synchronization by the dataset manager."}],"role":"symbol","navigatorTitle":[{"text":"dataSetManager:willStartSynchronizingDataSet:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:willStartSynchronizingDataSet:)","title":"dataSetManager(_:willStartSynchronizingDataSet:)","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate/dataSetManager(_:didFinishSynchronizingDataSet:)":{"type":"topic","title":"dataSetManager(_:didFinishSynchronizingDataSet:)","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didFinishSynchronizingDataSet:)","navigatorTitle":[{"kind":"identifier","text":"dataSetManager:didFinishSynchronizingDataSet:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"dataSetManager","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","text":"MPDataSetCacheManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishSynchronizingDataSet","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","text":"MPDataSetCache"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Called when a data set has finished synchronization."}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:didfinishsynchronizingdataset:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate":{"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheManagerDelegate"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate","title":"MPDataSetCacheManagerDelegate","type":"topic","abstract":[{"type":"text","text":"Data set manager delegate protocol."}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDataSetCacheManagerDelegate","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate/dataSetManager(_:didAddDataSet:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dataSetManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MPDataSetCacheManager","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didAddDataSet"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCache","kind":"typeIdentifier","text":"MPDataSetCache"},{"text":")","kind":"text"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:didadddataset:)","type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"dataSetManager:didAddDataSet:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didAddDataSet:)","kind":"symbol","title":"dataSetManager(_:didAddDataSet:)","abstract":[{"type":"text","text":"Called when a data set is added to a data set manager."}]},"MapsPeopleWhite.png":{"alt":null,"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate/dataSetManager(_:didFinishSynchronizingItem:)":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanager(_:didfinishsynchronizingitem:)","navigatorTitle":[{"kind":"identifier","text":"dataSetManager:didFinishSynchronizingItem:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didFinishSynchronizingItem:)","title":"dataSetManager(_:didFinishSynchronizingItem:)","type":"topic","abstract":[{"type":"text","text":"Called when a cache item synchronisation is finished."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dataSetManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPDataSetCacheManager","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishSynchronizingItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCacheItem","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem"},{"kind":"text","text":")"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate/dataSetManagerDidFinishSynchronizing(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataSetManagerDidFinishSynchronizing"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","text":"MPDataSetCacheManager"},{"text":")","kind":"text"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanagerdidfinishsynchronizing(_:)","type":"topic","navigatorTitle":[{"text":"dataSetManagerDidFinishSynchronizing:","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManagerDidFinishSynchronizing(_:)","kind":"symbol","title":"dataSetManagerDidFinishSynchronizing(_:)","abstract":[{"type":"text","text":"Called when the data set manager has finished synchronization of one or more datasets."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheManagerDelegate/dataSetManagerWillStartSynchronizing(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataSetManagerWillStartSynchronizing"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheManager","kind":"typeIdentifier","text":"MPDataSetCacheManager"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcachemanagerdelegate\/datasetmanagerwillstartsynchronizing(_:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"dataSetManagerWillStartSynchronizing:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManagerWillStartSynchronizing(_:)","kind":"symbol","abstract":[{"type":"text","text":"Called when the data set manager starts to synchronize one or more datasets."}],"title":"dataSetManagerWillStartSynchronizing(_:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","value":"MPDataSetCacheManagerDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"kind":"identifier","text":"MPDataSetCacheManagerDelegate"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MPDataSetCacheManagerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didAddDataSet:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didFinishSynchronizingDataSet:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didFinishSynchronizingItem:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:didRemoveDataSet:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:willStartSynchronizingDataSet:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManager(_:willStartSynchronizingItem:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManagerDidFinishSynchronizing(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheManagerDelegate\/dataSetManagerWillStartSynchronizing(_:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheManagerDelegate"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:willStartSynchronizingItem:)\/title","op":"replace","value":"dataSetManager:willStartSynchronizingItem:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:willStartSynchronizingItem:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"dataSetManager:willStartSynchronizingItem:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:didRemoveDataSet:)\/title","value":"dataSetManager:didRemoveDataSet:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:didRemoveDataSet:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"dataSetManager:didRemoveDataSet:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:willStartSynchronizingDataSet:)\/title","value":"dataSetManager:willStartSynchronizingDataSet:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:willStartSynchronizingDataSet:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dataSetManager:willStartSynchronizingDataSet:"}]},{"value":"dataSetManager:didFinishSynchronizingDataSet:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:didFinishSynchronizingDataSet:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dataSetManager:didFinishSynchronizingDataSet:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:didFinishSynchronizingDataSet:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate\/title","value":"MPDataSetCacheManagerDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate\/fragments","value":[{"text":"MPDataSetCacheManagerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:didAddDataSet:)\/title","value":"dataSetManager:didAddDataSet:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dataSetManager:didAddDataSet:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:didAddDataSet:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:didFinishSynchronizingItem:)\/title","value":"dataSetManager:didFinishSynchronizingItem:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManager(_:didFinishSynchronizingItem:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"dataSetManager:didFinishSynchronizingItem:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManagerDidFinishSynchronizing(_:)\/title","value":"dataSetManagerDidFinishSynchronizing:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManagerDidFinishSynchronizing(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"dataSetManagerDidFinishSynchronizing:","kind":"identifier"}]},{"op":"replace","value":"dataSetManagerWillStartSynchronizing:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManagerWillStartSynchronizing(_:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheManagerDelegate~1dataSetManagerWillStartSynchronizing(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"dataSetManagerWillStartSynchronizing:","kind":"identifier"}],"op":"replace"}]}]}