{"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"],"type":"inheritsFrom"}],"sections":[],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcacheitem"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcacheitem"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCacheItem","roleHeading":"Protocol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPDataSetCacheItem","kind":"identifier"}],"symbolKind":"protocol","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"MPDataSetCacheItem","kind":"identifier"}],"title":"MPDataSetCacheItem"},"abstract":[{"text":"Data set cache item class.","type":"text"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/init(id:)"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachedSize","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachedTimestamp","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachingItemId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachingScope","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachingStrategy","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/isCached","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/isSyncing","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/language","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/syncResult","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/syncSize","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/syncTimestamp"],"title":"Instance Properties"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDataSetCacheItem","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem/cachingScope":{"kind":"symbol","title":"cachingScope","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachingScope","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cachingScope","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingScope","kind":"typeIdentifier","text":"MPDataSetCachingScope"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Cache scope for this cache item."}],"url":"\/documentation\/mapsindoors\/mpdatasetcacheitem\/cachingscope","navigatorTitle":[{"text":"cachingScope","kind":"identifier"}],"required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem/syncResult":{"required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/syncResult","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"syncResult","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"syncResult"}],"url":"\/documentation\/mapsindoors\/mpdatasetcacheitem\/syncresult","kind":"symbol","title":"syncResult","abstract":[{"text":"Latest synchronisation result as an error object. If nil, either no synchronisation has been performed or latest synchronisation was successful.","type":"text"}]},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem/syncTimestamp":{"navigatorTitle":[{"text":"syncTimestamp","kind":"identifier"}],"required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncTimestamp"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}],"abstract":[{"text":"Date of last content synchronisation performed for this cache item.","type":"text"},{"type":"text","text":" "},{"text":"Note this does not indicate success or failure, just that a synchronization finished at a certain point in time.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapsindoors\/mpdatasetcacheitem\/synctimestamp","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/syncTimestamp","title":"syncTimestamp"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem/init(id:)":{"kind":"symbol","title":"init(id:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/init(id:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Initialise a data set cache item with an id."}],"url":"\/documentation\/mapsindoors\/mpdatasetcacheitem\/init(id:)","navigatorTitle":[{"kind":"identifier","text":"initWithId:"}],"required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem/cachingStrategy":{"kind":"symbol","title":"cachingStrategy","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachingStrategy","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cachingStrategy","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingStrategy","text":"MPDataSetCachingStrategy"}],"role":"symbol","type":"topic","abstract":[{"text":"Caching strategy for this cache item.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpdatasetcacheitem\/cachingstrategy","navigatorTitle":[{"kind":"identifier","text":"cachingStrategy"}],"required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCacheItem"}],"navigatorTitle":[{"kind":"identifier","text":"MPDataSetCacheItem"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem","abstract":[{"type":"text","text":"Data set cache item class."}],"url":"\/documentation\/mapsindoors\/mpdatasetcacheitem","kind":"symbol","type":"topic","role":"symbol","title":"MPDataSetCacheItem"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem/isSyncing":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isSyncing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/isSyncing","navigatorTitle":[{"kind":"identifier","text":"isSyncing"}],"abstract":[{"type":"text","text":"Synchronisation state. If true, content is currently being synchronised for this cache item."}],"url":"\/documentation\/mapsindoors\/mpdatasetcacheitem\/issyncing","type":"topic","kind":"symbol","role":"symbol","title":"isSyncing"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem/cachingItemId":{"url":"\/documentation\/mapsindoors\/mpdatasetcacheitem\/cachingitemid","kind":"symbol","abstract":[{"type":"text","text":"Cache item id."}],"role":"symbol","title":"cachingItemId","type":"topic","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachingItemId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cachingItemId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"cachingItemId","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem/isCached":{"kind":"symbol","title":"isCached","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/isCached","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCached"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Cache state. If true, content is cached for this cache item."}],"url":"\/documentation\/mapsindoors\/mpdatasetcacheitem\/iscached","navigatorTitle":[{"kind":"identifier","text":"isCached"}],"required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem/language":{"kind":"symbol","role":"symbol","title":"language","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"language","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/mapsindoors\/mpdatasetcacheitem\/language","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/language","navigatorTitle":[{"text":"language","kind":"identifier"}],"type":"topic","abstract":[{"text":"Cache item content language.","type":"text"}],"required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem/cachedSize":{"navigatorTitle":[{"text":"cachedSize","kind":"identifier"}],"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cachedSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"abstract":[{"text":"Disk size in bytes for the currently cached content of this cache item.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/mapsindoors\/mpdatasetcacheitem\/cachedsize","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachedSize","title":"cachedSize"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem/cachedTimestamp":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"cachedTimestamp"}],"abstract":[{"type":"text","text":"Date of last successfull caching performed for this cache item."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachedTimestamp","url":"\/documentation\/mapsindoors\/mpdatasetcacheitem\/cachedtimestamp","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cachedTimestamp"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","title":"cachedTimestamp","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem/name":{"title":"name","type":"topic","role":"symbol","url":"\/documentation\/mapsindoors\/mpdatasetcacheitem\/name","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/name","abstract":[{"text":"Cache item name.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"name","kind":"identifier"}],"required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCacheItem/syncSize":{"type":"topic","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"syncSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"url":"\/documentation\/mapsindoors\/mpdatasetcacheitem\/syncsize","title":"syncSize","navigatorTitle":[{"kind":"identifier","text":"syncSize"}],"abstract":[{"text":"Estimated possible synchronization size, if no content has been synchronised yet for this cache item.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/syncSize"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPDataSetCacheItem"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"MPDataSetCacheItem"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPDataSetCacheItem"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachedSize","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachedTimestamp","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachingItemId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachingScope","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/cachingStrategy","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/isCached","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/isSyncing","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/language","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/syncResult","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/syncSize","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/syncTimestamp"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCacheItem\/init(id:)"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDataSetCacheItem","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"cachingScope","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1cachingScope\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1cachingScope\/fragments","value":[{"text":"cachingScope","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1syncResult\/title","op":"replace","value":"syncResult"},{"value":[{"text":"syncResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1syncResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1syncTimestamp\/title","value":"syncTimestamp"},{"value":[{"kind":"identifier","text":"syncTimestamp"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1syncTimestamp\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1init(id:)\/title","value":"initWithId:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1init(id:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithId:","kind":"identifier"}]},{"value":"cachingStrategy","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1cachingStrategy\/title"},{"value":[{"text":"cachingStrategy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1cachingStrategy\/fragments"},{"op":"replace","value":"MPDataSetCacheItem","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem\/fragments","value":[{"kind":"identifier","text":"MPDataSetCacheItem"}],"op":"replace"},{"value":"isSyncing","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1isSyncing\/title"},{"value":[{"kind":"identifier","text":"isSyncing"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1isSyncing\/fragments"},{"value":"cachingItemId","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1cachingItemId\/title"},{"value":[{"text":"cachingItemId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1cachingItemId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1isCached\/title","value":"isCached"},{"value":[{"text":"isCached","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1isCached\/fragments"},{"value":"language","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1language\/title"},{"value":[{"kind":"identifier","text":"language"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1language\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1cachedSize\/title","op":"replace","value":"cachedSize"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1cachedSize\/fragments","op":"replace","value":[{"text":"cachedSize","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1cachedTimestamp\/title","value":"cachedTimestamp"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1cachedTimestamp\/fragments","op":"replace","value":[{"text":"cachedTimestamp","kind":"identifier"}]},{"op":"replace","value":"name","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1name\/title"},{"value":[{"kind":"identifier","text":"name"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1name\/fragments","op":"replace"},{"op":"replace","value":"syncSize","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1syncSize\/title"},{"value":[{"kind":"identifier","text":"syncSize"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCacheItem~1syncSize\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}