{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Data set caching strategy."}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH","doc:\/\/com.mapspeople.mapsindoors\/SY"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcachingstrategy"]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcachingstrategy"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/automatic","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/dontCache","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/manual"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/Equatable-Implementations","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"metadata":{"roleHeading":"Enumeration","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCachingStrategy"}],"title":"MPDataSetCachingStrategy","modules":[{"name":"MapsIndoors"}],"symbolKind":"enum","externalID":"c:@M@MapsIndoors@E@MPDataSetCachingStrategy","navigatorTitle":[{"text":"MPDataSetCachingStrategy","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCachingStrategy"}]}]}],"references":{"doc://com.mapspeople.mapsindoors/SY":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/SQ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","title":"Swift.Equatable","type":"unresolvable"},"MapsPeopleWhite.png":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingStrategy/RawRepresentable-Implementations":{"url":"\/documentation\/mapsindoors\/mpdatasetcachingstrategy\/rawrepresentable-implementations","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations","abstract":[],"type":"topic","role":"collectionGroup"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingStrategy":{"type":"topic","navigatorTitle":[{"text":"MPDataSetCachingStrategy","kind":"identifier"}],"title":"MPDataSetCachingStrategy","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDataSetCachingStrategy","kind":"identifier"}],"abstract":[{"type":"text","text":"Data set caching strategy."}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy","url":"\/documentation\/mapsindoors\/mpdatasetcachingstrategy"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingStrategy/automatic":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/automatic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automatic"}],"title":"MPDataSetCachingStrategy.automatic","kind":"symbol","abstract":[{"type":"text","text":"Cache automatically. Data will be kept or removed according to internal behaviors."}],"url":"\/documentation\/mapsindoors\/mpdatasetcachingstrategy\/automatic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCachingStrategyAutomatic"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingStrategy/init(rawValue:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"init(rawValue:)","kind":"symbol","abstract":[],"url":"\/documentation\/mapsindoors\/mpdatasetcachingstrategy\/init(rawvalue:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingStrategy/Equatable-Implementations":{"url":"\/documentation\/mapsindoors\/mpdatasetcachingstrategy\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/Equatable-Implementations","title":"Equatable Implementations","type":"topic","kind":"article","abstract":[]},"doc://com.mapspeople.mapsindoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingStrategy/manual":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/manual","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"manual"}],"title":"MPDataSetCachingStrategy.manual","kind":"symbol","abstract":[{"type":"text","text":"Cache manually. Data will be kept until data set is removed manually in the data set manager."}],"url":"\/documentation\/mapsindoors\/mpdatasetcachingstrategy\/manual","navigatorTitle":[{"text":"MPDataSetCachingStrategyManual","kind":"identifier"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingStrategy/dontCache":{"navigatorTitle":[{"text":"MPDataSetCachingStrategyDontCache","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdatasetcachingstrategy\/dontcache","kind":"symbol","role":"symbol","title":"MPDataSetCachingStrategy.dontCache","type":"topic","abstract":[{"type":"text","text":"Don’t cache. Data will be removed at any point after usage."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/dontCache","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"dontCache","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MPDataSetCachingStrategy"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPDataSetCachingStrategy"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MPDataSetCachingStrategy","kind":"identifier"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/automatic","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/dontCache","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy\/manual"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDataSetCachingStrategy","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy\/title","value":"MPDataSetCachingStrategy"},{"op":"replace","value":[{"text":"MPDataSetCachingStrategy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy~1automatic\/title","value":"MPDataSetCachingStrategyAutomatic","op":"replace"},{"value":[{"kind":"identifier","text":"MPDataSetCachingStrategyAutomatic"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy~1automatic\/fragments","op":"replace"},{"value":"MPDataSetCachingStrategyManual","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy~1manual\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MPDataSetCachingStrategyManual"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy~1manual\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy~1dontCache\/title","value":"MPDataSetCachingStrategyDontCache","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy~1dontCache\/fragments","op":"replace","value":[{"text":"MPDataSetCachingStrategyDontCache","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}