{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataField\/fields","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataField\/key","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataField\/value"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataField"},"sections":[],"abstract":[{"type":"text","text":"Data field model, e.g. used for categories."}],"relationshipsSections":[{"type":"conformingTypes","kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataFieldCodable"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPDataField","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdatafield"]},{"paths":["\/documentation\/mapsindoors\/mpdatafield"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPDataField","symbolKind":"protocol","roleHeading":"Protocol","navigatorTitle":[{"text":"MPDataField","kind":"identifier"}],"role":"symbol","title":"MPDataField","modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDataField","kind":"identifier"}]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataField/key":{"kind":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"key"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataField\/key","type":"topic","url":"\/documentation\/mapsindoors\/mpdatafield\/key","title":"key","abstract":[{"type":"text","text":"The key of the data field."}],"navigatorTitle":[{"text":"key","kind":"identifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataField/value":{"kind":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataField\/value","type":"topic","url":"\/documentation\/mapsindoors\/mpdatafield\/value","abstract":[{"type":"text","text":"The value of the data field."}],"title":"value","navigatorTitle":[{"kind":"identifier","text":"value"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataFieldCodable":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPDataFieldCodable","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPDataFieldCodable"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataFieldCodable","type":"topic","url":"\/documentation\/mapsindoors\/mpdatafieldcodable","title":"MPDataFieldCodable","abstract":[],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataField":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataField"}],"navigatorTitle":[{"text":"MPDataField","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataField","type":"topic","url":"\/documentation\/mapsindoors\/mpdatafield","abstract":[{"type":"text","text":"Data field model, e.g. used for categories."}],"title":"MPDataField","role":"symbol"},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","alt":null,"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataField/fields":{"kind":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fields","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationField","kind":"typeIdentifier","text":"MPLocationField"},{"text":"]?","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataField\/fields","type":"topic","url":"\/documentation\/mapsindoors\/mpdatafield\/fields","abstract":[{"type":"text","text":"Dictionary of custom fields."}],"title":"fields","navigatorTitle":[{"kind":"identifier","text":"fields"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"value":"MPDataField","op":"replace","path":"\/metadata\/title"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MPDataField","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MPDataField","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataField\/fields","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataField\/key","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataField\/value"]}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDataField","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataField~1key\/title","op":"replace","value":"key"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataField~1key\/fragments","value":[{"text":"key","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataField~1value\/title","op":"replace","value":"value"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataField~1value\/fragments","value":[{"text":"value","kind":"identifier"}]},{"value":"MPDataField","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataField\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataField\/fragments","op":"replace","value":[{"text":"MPDataField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataField~1fields\/title","value":"fields"},{"op":"replace","value":[{"text":"fields","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataField~1fields\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}