{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScope"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfoscope"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfoscope"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH","doc:\/\/MapsIndoors\/SY","doc:\/\/MapsIndoors\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/iconAndName","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/iconOnly","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/nameOnly"]},{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/Equatable-Implementations","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScope"}],"title":"MPDirectionsRendererContextualInfoScope","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@MPDirectionsRendererContextualInfoScope","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScope"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRendererContextualInfoScope/iconOnly":{"role":"symbol","title":"MPDirectionsRendererContextualInfoScope.iconOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconOnly"}],"abstract":[{"type":"text","text":"Shows only icon of POI of defined type along the rendered route"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/iconOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScopeIconOnly"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfoscope\/icononly"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRendererContextualInfoScope":{"role":"symbol","title":"MPDirectionsRendererContextualInfoScope","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScope"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScope"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfoscope"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRendererContextualInfoScope/nameOnly":{"role":"symbol","title":"MPDirectionsRendererContextualInfoScope.nameOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nameOnly"}],"abstract":[{"type":"text","text":"Shows only name of POI of defined type along the rendered route"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/nameOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScopeNameOnly"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfoscope\/nameonly"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRendererContextualInfoScope/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfoscope\/rawrepresentable-implementations"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRendererContextualInfoScope/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfoscope\/equatable-implementations"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRendererContextualInfoScope/iconAndName":{"role":"symbol","title":"MPDirectionsRendererContextualInfoScope.iconAndName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconAndName"}],"abstract":[{"type":"text","text":"Shows both icon and name of POI of defined type along the rendered route"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/iconAndName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScopeIconAndName"}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfoscope\/iconandname"},"doc://MapsIndoors/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/MapsIndoors\/SY"},"doc://MapsIndoors/documentation/MapsIndoors/MPDirectionsRendererContextualInfoScope/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpdirectionsrenderercontextualinfoscope\/init(rawvalue:)"},"doc://MapsIndoors/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/MapsIndoors\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"MPDirectionsRendererContextualInfoScope"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScope"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScope"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/iconAndName","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/iconOnly","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDirectionsRendererContextualInfoScope\/nameOnly"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScope"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoScope~1iconOnly\/title","value":"MPDirectionsRendererContextualInfoScopeIconOnly"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoScope~1iconOnly\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScopeIconOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoScope\/title","value":"MPDirectionsRendererContextualInfoScope"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoScope\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScope"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoScope~1nameOnly\/title","value":"MPDirectionsRendererContextualInfoScopeNameOnly"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoScope~1nameOnly\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScopeNameOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoScope~1iconAndName\/title","value":"MPDirectionsRendererContextualInfoScopeIconAndName"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDirectionsRendererContextualInfoScope~1iconAndName\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRendererContextualInfoScopeIconAndName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}