{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsservice"]},{"paths":["\/documentation\/mapsindoors\/mpdirectionsservice"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Protocol","externalID":"c:@M@MapsIndoors@objc(pl)MPDirectionsService","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPDirectionsService","kind":"identifier"}],"navigatorTitle":[{"text":"MPDirectionsService","kind":"identifier"}],"role":"symbol","title":"MPDirectionsService","symbolKind":"protocol","modules":[{"name":"MapsIndoors"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService\/routingWith(query:)"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDirectionsService"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"MapsPeopleWhite.png":{"alt":null,"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsService":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDirectionsService","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPDirectionsService"}],"url":"\/documentation\/mapsindoors\/mpdirectionsservice","kind":"symbol","title":"MPDirectionsService","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPDirectionsQuery","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPDirectionsQuery"}],"url":"\/documentation\/mapsindoors\/mpdirectionsquery","kind":"symbol","title":"MPDirectionsQuery","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsService/routingWith(query:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"routingWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"query","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MPDirectionsQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDirectionsQuery"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"MPRoute","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRoute"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"routingWithQuery:completionHandler:","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService\/routingWith(query:)","title":"routingWith(query:)","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/mapsindoors\/mpdirectionsservice\/routingwith(query:)","required":true,"abstract":[{"type":"text","text":"Get directions as specified in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery"},{"type":"text","text":"."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MPDirectionsService"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"text":"MPDirectionsService","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MPDirectionsService"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService\/routingWith(query:)"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"MPDirectionsService","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/title","value":"MPDirectionsService"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/fragments","value":[{"kind":"identifier","text":"MPDirectionsService"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/title","op":"replace","value":"MPDirectionsQuery"},{"op":"replace","value":[{"text":"MPDirectionsQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/fragments"},{"value":"routingWithQuery:completionHandler:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService~1routingWith(query:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"routingWithQuery:completionHandler:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService~1routingWith(query:)\/fragments"}]}]}