{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule"},"abstract":[{"text":"This class represents a Display Rule, a MapsIndoors concept which describes a number of styling values for MapsIndoors objects.","type":"text"},{"text":" ","type":"text"},{"text":"The values contained within dictates how the MapsIndoors SDK renders a given object on the map (POI, area, selection, model, etc.).","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MPDisplayRule"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDisplayRule"}],"role":"symbol","modules":[{"name":"MapsIndoors"}],"roleHeading":"Class","externalID":"c:@M@MapsIndoors@objc(cs)MPDisplayRule","symbolKind":"class","title":"MPDisplayRule"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init(dictionary:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init(from:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init(name:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init(rule:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init(rule:parent:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init(ruleData:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/debugDescription","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/extrusionColor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/extrusionHeight","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/extrusionVisible","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/extrusionZoomFrom","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/extrusionZoomTo","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/icon","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/iconSize","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/iconURL","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/iconVisible","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/label","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/labelMaxWidth","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/labelVisible","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/labelZoomFrom","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/labelZoomTo","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DBearing","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DHeightMeters","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DModel","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DVisible","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DWidthMeters","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DZoomFrom","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DZoomTo","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DModel","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DRotationX","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DRotationY","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DRotationZ","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DScale","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DVisible","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DZoomFrom","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DZoomTo","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonFillColor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonFillOpacity","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonStrokeColor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonStrokeOpacity","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonStrokeWidth","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonVisible","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonZoomFrom","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonZoomTo","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/visible","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/wallsColor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/wallsHeight","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/wallsVisible","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/wallsZoomFrom","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/wallsZoomTo","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/zoomFrom","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/zoomTo"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/encode(to:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/reset()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/showAt(zoom:)"],"title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDisplayRule","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Display Rule data can be edited through the MapsIndoors CMS, and can be modified at runtime in SDKs. Invoke "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/reset()","isActive":true},{"type":"text","text":" on a "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule","isActive":true},{"type":"text","text":" to reset all values to those from the CMS."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdisplayrule"]},{"paths":["\/documentation\/mapsindoors\/mpdisplayrule"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/visible":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/visible","abstract":[{"text":"Whether or not to show the location.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"visible","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visible","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/visible","title":"visible"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/label":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/label","abstract":[{"type":"text","text":"The label to show for the marker. It can be a fixed string or a label template, e.g. "},{"code":"\"{{name}}\"","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"\"{{roomId}}\""},{"type":"text","text":", "},{"code":"\"Room #{{roomId}}\"","type":"codeVoice"},{"text":" etc..","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"label","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/label","title":"label"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/wallsZoomTo":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/wallsZoomTo","abstract":[{"text":"The map zoom level beneatch which the walls should be visible.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"wallsZoomTo","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"wallsZoomTo","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/wallszoomto","title":"wallsZoomTo"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/reset()":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/reset()","abstract":[{"text":"Resets the DisplayRule to the original state.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"reset","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"reset","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/reset()","title":"reset()"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/polygonZoomFrom":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonZoomFrom","abstract":[{"type":"text","text":"The map zoom level above which the location polygon should be visible."}],"kind":"symbol","navigatorTitle":[{"text":"polygonZoomFrom","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"polygonZoomFrom","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/polygonzoomfrom","title":"polygonZoomFrom"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/encode(to:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/encode(to:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s7EncoderP","text":"Encoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/encode(to:)","title":"encode(to:)"},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","alt":null,"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/wallsZoomFrom":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/wallsZoomFrom","abstract":[{"type":"text","text":"The map zoom level above which the walls should be visible."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"wallsZoomFrom"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wallsZoomFrom","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/wallszoomfrom","title":"wallsZoomFrom"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/init(name:)":{"title":"init(name:)","kind":"symbol","navigatorTitle":[{"text":"initWithName:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init(name:)","url":"\/documentation\/mapsindoors\/mpdisplayrule\/init(name:)","type":"topic","abstract":[],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/init(dictionary:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dictionary","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!) ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"initWithDictionary:error:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdisplayrule\/init(dictionary:)","title":"init(dictionary:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init(dictionary:)","abstract":[{"type":"text","text":"Populate with data via JSONModel."},{"text":" ","type":"text"},{"type":"text","text":"Should never be used from outside the MapsIndoors SDK."}],"type":"topic","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/model3DModel":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DModel","abstract":[{"text":"Model URL of the 3D model on the map.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"model3DModel","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"model3DModel","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/model3dmodel","title":"model3DModel"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/extrusionZoomFrom":{"title":"extrusionZoomFrom","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/extrusionZoomFrom","navigatorTitle":[{"kind":"identifier","text":"extrusionZoomFrom"}],"abstract":[{"text":"The map zoom level above which the extrusion should be visible.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extrusionZoomFrom","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/extrusionzoomfrom"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/polygonFillOpacity":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonFillOpacity","abstract":[{"type":"text","text":"The opacity of the polygon fill color drawn on the map."}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygonFillOpacity","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/polygonfillopacity","title":"polygonFillOpacity"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/model2DZoomFrom":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DZoomFrom","abstract":[{"text":"The 2D model zoom value from dictates from which zoom level the model should start being shown.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"model2DZoomFrom","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"model2DZoomFrom"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/model2dzoomfrom","title":"model2DZoomFrom"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/model2DHeightMeters":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DHeightMeters","abstract":[{"type":"text","text":"The height of the 2D model. The value is in meters to make it easy to associate with the real world."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"model2DHeightMeters"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"model2DHeightMeters","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/model2dheightmeters","title":"model2DHeightMeters"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/extrusionColor":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/extrusionColor","abstract":[{"text":"The color which the extrusion should be drawn with.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"extrusionColor","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"extrusionColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/extrusioncolor","title":"extrusionColor"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/model2DZoomTo":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DZoomTo","abstract":[{"type":"text","text":"The 2D model zoom to value dictates from which zoom level the model should stop being shown."}],"kind":"symbol","navigatorTitle":[{"text":"model2DZoomTo","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"model2DZoomTo"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/model2dzoomto","title":"model2DZoomTo"},"doc://com.mapspeople.mapsindoors/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/debugDescription":{"url":"\/documentation\/mapsindoors\/mpdisplayrule\/debugdescription","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/debugDescription","navigatorTitle":[{"text":"debugDescription","kind":"identifier"}],"title":"debugDescription","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"debugDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/extrusionVisible":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/extrusionVisible","abstract":[{"text":"Whether or not to show the location extrusion on the map.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"extrusionVisible"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/extrusionvisible","title":"extrusionVisible"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule":{"abstract":[{"text":"This class represents a Display Rule, a MapsIndoors concept which describes a number of styling values for MapsIndoors objects.","type":"text"},{"type":"text","text":" "},{"text":"The values contained within dictates how the MapsIndoors SDK renders a given object on the map (POI, area, selection, model, etc.).","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDisplayRule"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule","navigatorTitle":[{"kind":"identifier","text":"MPDisplayRule"}],"title":"MPDisplayRule","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule","role":"symbol","kind":"symbol"},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/model3DScale":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DScale","abstract":[{"text":"Scale factor of the 3D model on the map.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"model3DScale"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"model3DScale","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/model3dscale","title":"model3DScale"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/model3DZoomFrom":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DZoomFrom","abstract":[{"text":"The zoom level from where the 3D model should start showing on the map.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"model3DZoomFrom"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"model3DZoomFrom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/model3dzoomfrom","title":"model3DZoomFrom"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/labelVisible":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/labelVisible","abstract":[{"type":"text","text":"Whether or not to show a text label. See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/label"},{"text":" property.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"labelVisible"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"labelVisible","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/labelvisible","title":"labelVisible"},"doc://com.mapspeople.mapsindoors/Se":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/polygonStrokeWidth":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonStrokeWidth","abstract":[{"type":"text","text":"The stroke width of the polygon drawn on the map."}],"kind":"symbol","navigatorTitle":[{"text":"polygonStrokeWidth","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"polygonStrokeWidth"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/polygonstrokewidth","title":"polygonStrokeWidth"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/init()":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init()","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/init()","title":"init()"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/model3DZoomTo":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DZoomTo","abstract":[{"text":"The zoom level from where the 3D model should stop showing on the map.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"model3DZoomTo","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"model3DZoomTo","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/model3dzoomto","title":"model3DZoomTo"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/model3DVisible":{"abstract":[{"type":"text","text":"Whether or not to show the 3D model on the map."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"model3DVisible"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/model3dvisible","navigatorTitle":[{"text":"model3DVisible","kind":"identifier"}],"title":"model3DVisible","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DVisible","role":"symbol","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/name":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/name","abstract":[{"text":"Name\/identifier of the rule. Also used as the rule condition for the location types.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"name","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/name","title":"name"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/showAt(zoom:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/showAt(zoom:)","abstract":[{"type":"text","text":"Should anything be shown at the provided zoom level?"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"showAtZoom:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"showAt","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"zoom"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/showat(zoom:)","title":"showAt(zoom:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/zoomFrom":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/zoomFrom","abstract":[{"text":"The map zoom level above which the location should be visible.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"zoomFrom"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"zoomFrom"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/zoomfrom","title":"zoomFrom"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/polygonZoomTo":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonZoomTo","abstract":[{"text":"The map zoom level beneath which the location Polygon should be visible.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"polygonZoomTo"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonZoomTo"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/polygonzoomto","title":"polygonZoomTo"},"doc://com.mapspeople.mapsindoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/model3DRotationX":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DRotationX","abstract":[{"type":"text","text":"Rotation on the X-axis applied to the 3D model on the map."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"model3DRotationX"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"model3DRotationX","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/model3drotationx","title":"model3DRotationX"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/init(rule:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init(rule:)","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"initWithRule:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"rule","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPDisplayRule","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/init(rule:)","title":"init(rule:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/wallsHeight":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/wallsHeight","abstract":[{"type":"text","text":"The height of the walls on the map."}],"kind":"symbol","navigatorTitle":[{"text":"wallsHeight","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"wallsHeight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/wallsheight","title":"wallsHeight"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/polygonVisible":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygonVisible","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"polygonVisible","abstract":[{"type":"text","text":"Whether or not to show the location polygon on the map."}],"navigatorTitle":[{"kind":"identifier","text":"polygonVisible"}],"url":"\/documentation\/mapsindoors\/mpdisplayrule\/polygonvisible","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonVisible","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/init(ruleData:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init(ruleData:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ruleData"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11MapsIndoors17MPDisplayRuleDataV","text":"MPDisplayRuleData","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/init(ruledata:)","title":"init(ruleData:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/iconVisible":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/iconVisible","abstract":[{"text":"Whether or not to show an icon.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"iconVisible"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iconVisible","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/iconvisible","title":"iconVisible"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/iconSize":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/iconSize","abstract":[{"type":"text","text":"Size of the icon image."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"iconSize"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"iconSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/iconsize","title":"iconSize"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/icon":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/icon","abstract":[{"type":"text","text":"The marker icon to use on markers that apply to the display rule."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"icon"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"icon","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/icon","title":"icon"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/labelZoomTo":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/labelZoomTo","abstract":[{"text":"The zoom level beneath the location label should be shown.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"labelZoomTo","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"labelZoomTo"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/labelzoomto","title":"labelZoomTo"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/extrusionHeight":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/extrusionHeight","abstract":[{"type":"text","text":"The height of the extrusion on the map."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"extrusionHeight"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"extrusionHeight","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/extrusionheight","title":"extrusionHeight"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/wallsVisible":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/wallsVisible","abstract":[{"type":"text","text":"Whether or not to show the location walls on the map."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"wallsVisible","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/wallsvisible","title":"wallsVisible"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/init(rule:parent:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init(rule:parent:)","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithRule:parent:"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"rule","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPDisplayRule","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule"},{"text":", ","kind":"text"},{"text":"parent","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDisplayRule","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/init(rule:parent:)","title":"init(rule:parent:)"},"doc://com.mapspeople.mapsindoors/SQ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/iconURL":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/iconURL","abstract":[{"text":"URL to the marker icon to use.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"iconURL","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"iconURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/iconurl","title":"iconURL"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/extrusionZoomTo":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/extrusionZoomTo","abstract":[{"type":"text","text":"The map zoom level beneatch which the extrusion should be visible."}],"kind":"symbol","navigatorTitle":[{"text":"extrusionZoomTo","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"extrusionZoomTo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/extrusionzoomto","title":"extrusionZoomTo"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/polygonStrokeOpacity":{"url":"\/documentation\/mapsindoors\/mpdisplayrule\/polygonstrokeopacity","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonStrokeOpacity","abstract":[{"text":"the opacity of the polygon stroke drawn on the map.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonStrokeOpacity"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"?","kind":"text"}],"role":"symbol","title":"polygonStrokeOpacity","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/model2DBearing":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DBearing","abstract":[{"text":"The bearing of the 2D model. The value is the rotation in degrees clockwise from north.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"model2DBearing","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"model2DBearing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/model2dbearing","title":"model2DBearing"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/wallsColor":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/wallsColor","abstract":[{"text":"The color which the walls should be drawn with.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"wallsColor","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wallsColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/wallscolor","title":"wallsColor"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/labelMaxWidth":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/labelMaxWidth","abstract":[{"text":"Maximum width in points of the label shown on the map. If the text shown in the label","type":"text"},{"type":"text","text":" "},{"text":"(typically the Location name) is longer than the labelMaxWidth the text will flow onto as many","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"lines as needed."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"labelMaxWidth"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"labelMaxWidth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/labelmaxwidth","title":"labelMaxWidth"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/model2DModel":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DModel","abstract":[{"text":"The URL of the image for the 2D model.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpdisplayrule\/model2dmodel","navigatorTitle":[{"text":"model2DModel","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"model2DModel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"model2DModel"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/model3DRotationZ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DRotationZ","abstract":[{"text":"Rotation on the Z-axis applied to the 3D model on the map.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"model3DRotationZ"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"model3DRotationZ","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/model3drotationz","title":"model3DRotationZ"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/model2DWidthMeters":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DWidthMeters","abstract":[{"type":"text","text":"The width of the 2D model. The value is in meters to make it easy to associate with the real world."}],"kind":"symbol","navigatorTitle":[{"text":"model2DWidthMeters","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"model2DWidthMeters"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/model2dwidthmeters","title":"model2DWidthMeters"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/model3DRotationY":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DRotationY","abstract":[{"type":"text","text":"Rotation on the Y-axis applied to the 3D model on the map."}],"kind":"symbol","navigatorTitle":[{"text":"model3DRotationY","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"model3DRotationY","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/model3drotationy","title":"model3DRotationY"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/polygonStrokeColor":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonStrokeColor","abstract":[{"text":"The stroke color of the polygon drawn on the map.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"polygonStrokeColor","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"polygonStrokeColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/polygonstrokecolor","title":"polygonStrokeColor"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/labelZoomFrom":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/labelZoomFrom","abstract":[{"type":"text","text":"The zoom level above the location label should be shown."}],"kind":"symbol","navigatorTitle":[{"text":"labelZoomFrom","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"labelZoomFrom"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/labelzoomfrom","title":"labelZoomFrom"},"doc://com.mapspeople.mapsindoors/SE":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/model2DVisible":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DVisible","abstract":[{"type":"text","text":"Determines the visibility of the 2D model."}],"kind":"symbol","navigatorTitle":[{"text":"model2DVisible","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"model2DVisible"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/model2dvisible","title":"model2DVisible"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/polygonFillColor":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonFillColor","abstract":[{"text":"The fill color of the polygon drawn on the map.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"polygonFillColor","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygonFillColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/polygonfillcolor","title":"polygonFillColor"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/init(from:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init(from:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/init(from:)","title":"init(from:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule/zoomTo":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/zoomTo","abstract":[{"text":"The map zoom level beneath which the location should be visible.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"zoomTo","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zoomTo","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule\/zoomto","title":"zoomTo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MPDisplayRule"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MPDisplayRule","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MPDisplayRule","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/debugDescription","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/extrusionColor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/extrusionHeight","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/extrusionZoomFrom","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/extrusionZoomTo","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/icon","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/iconSize","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/iconURL","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/iconVisible","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/label","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/labelMaxWidth","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/labelVisible","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/labelZoomFrom","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/labelZoomTo","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DBearing","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DHeightMeters","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DModel","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DVisible","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DWidthMeters","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DZoomFrom","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model2DZoomTo","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DModel","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DRotationX","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DRotationY","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DRotationZ","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DScale","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DVisible","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DZoomFrom","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/model3DZoomTo","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonFillColor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonStrokeColor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonStrokeWidth","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonVisible","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonZoomFrom","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/polygonZoomTo","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/visible","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/wallsColor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/wallsHeight","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/wallsZoomFrom","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/wallsZoomTo","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/zoomFrom","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/zoomTo"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init(dictionary:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init(name:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init(rule:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/init(rule:parent:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/reset()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule\/showAt(zoom:)"]}]},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDisplayRule","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1visible\/title","value":"visible"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1visible\/fragments","op":"replace","value":[{"text":"visible","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1label\/title","value":"label","op":"replace"},{"op":"replace","value":[{"text":"label","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1label\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1wallsZoomTo\/title","value":"wallsZoomTo"},{"op":"replace","value":[{"kind":"identifier","text":"wallsZoomTo"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1wallsZoomTo\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1reset()\/title","value":"reset","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1reset()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"reset","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1polygonZoomFrom\/title","value":"polygonZoomFrom"},{"value":[{"text":"polygonZoomFrom","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1polygonZoomFrom\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1wallsZoomFrom\/title","value":"wallsZoomFrom","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"wallsZoomFrom"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1wallsZoomFrom\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1init(name:)\/title","op":"replace","value":"initWithName:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1init(name:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithName:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1init(dictionary:)\/title","value":"initWithDictionary:error:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1init(dictionary:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDictionary:error:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DModel\/title","value":"model3DModel"},{"value":[{"kind":"identifier","text":"model3DModel"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DModel\/fragments"},{"op":"replace","value":"extrusionZoomFrom","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1extrusionZoomFrom\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1extrusionZoomFrom\/fragments","value":[{"text":"extrusionZoomFrom","kind":"identifier"}]},{"value":"model2DZoomFrom","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model2DZoomFrom\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model2DZoomFrom\/fragments","value":[{"kind":"identifier","text":"model2DZoomFrom"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model2DHeightMeters\/title","value":"model2DHeightMeters"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model2DHeightMeters\/fragments","value":[{"text":"model2DHeightMeters","kind":"identifier"}]},{"op":"replace","value":"extrusionColor","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1extrusionColor\/title"},{"op":"replace","value":[{"text":"extrusionColor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1extrusionColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model2DZoomTo\/title","value":"model2DZoomTo"},{"value":[{"kind":"identifier","text":"model2DZoomTo"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model2DZoomTo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1debugDescription\/title","value":"debugDescription"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1debugDescription\/fragments","value":[{"kind":"identifier","text":"debugDescription"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/title","value":"MPDisplayRule","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/fragments","value":[{"text":"MPDisplayRule","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DScale\/title","op":"replace","value":"model3DScale"},{"value":[{"kind":"identifier","text":"model3DScale"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DScale\/fragments","op":"replace"},{"op":"replace","value":"model3DZoomFrom","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DZoomFrom\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DZoomFrom\/fragments","value":[{"text":"model3DZoomFrom","kind":"identifier"}]},{"value":"labelVisible","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1labelVisible\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1labelVisible\/fragments","value":[{"kind":"identifier","text":"labelVisible"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1polygonStrokeWidth\/title","value":"polygonStrokeWidth","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1polygonStrokeWidth\/fragments","value":[{"kind":"identifier","text":"polygonStrokeWidth"}],"op":"replace"},{"value":"init","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1init()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1init()\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},{"op":"replace","value":"model3DZoomTo","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DZoomTo\/title"},{"value":[{"kind":"identifier","text":"model3DZoomTo"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DZoomTo\/fragments"},{"value":"model3DVisible","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DVisible\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DVisible\/fragments","op":"replace","value":[{"kind":"identifier","text":"model3DVisible"}]},{"value":"name","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1name\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1name\/fragments","op":"replace","value":[{"text":"name","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1showAt(zoom:)\/title","value":"showAtZoom:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showAtZoom:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1showAt(zoom:)\/fragments","op":"replace"},{"op":"replace","value":"zoomFrom","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1zoomFrom\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1zoomFrom\/fragments","value":[{"kind":"identifier","text":"zoomFrom"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1polygonZoomTo\/title","value":"polygonZoomTo"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1polygonZoomTo\/fragments","value":[{"text":"polygonZoomTo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DRotationX\/title","value":"model3DRotationX"},{"op":"replace","value":[{"kind":"identifier","text":"model3DRotationX"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DRotationX\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1init(rule:)\/title","value":"initWithRule:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1init(rule:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithRule:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1wallsHeight\/title","value":"wallsHeight"},{"op":"replace","value":[{"kind":"identifier","text":"wallsHeight"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1wallsHeight\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1polygonVisible\/title","value":"polygonVisible"},{"value":[{"kind":"identifier","text":"polygonVisible"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1polygonVisible\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1iconVisible\/title","value":"iconVisible","op":"replace"},{"value":[{"text":"iconVisible","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1iconVisible\/fragments","op":"replace"},{"op":"replace","value":"iconSize","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1iconSize\/title"},{"value":[{"kind":"identifier","text":"iconSize"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1iconSize\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1icon\/title","value":"icon"},{"value":[{"text":"icon","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1icon\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1labelZoomTo\/title","op":"replace","value":"labelZoomTo"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1labelZoomTo\/fragments","value":[{"kind":"identifier","text":"labelZoomTo"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1extrusionHeight\/title","op":"replace","value":"extrusionHeight"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1extrusionHeight\/fragments","value":[{"text":"extrusionHeight","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"initWithRule:parent:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1init(rule:parent:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithRule:parent:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1init(rule:parent:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1iconURL\/title","value":"iconURL"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1iconURL\/fragments","value":[{"text":"iconURL","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1extrusionZoomTo\/title","value":"extrusionZoomTo"},{"op":"replace","value":[{"kind":"identifier","text":"extrusionZoomTo"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1extrusionZoomTo\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model2DBearing\/title","value":"model2DBearing","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model2DBearing\/fragments","value":[{"kind":"identifier","text":"model2DBearing"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1wallsColor\/title","value":"wallsColor"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1wallsColor\/fragments","value":[{"text":"wallsColor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1labelMaxWidth\/title","value":"labelMaxWidth","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1labelMaxWidth\/fragments","value":[{"kind":"identifier","text":"labelMaxWidth"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model2DModel\/title","value":"model2DModel"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model2DModel\/fragments","value":[{"text":"model2DModel","kind":"identifier"}]},{"op":"replace","value":"model3DRotationZ","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DRotationZ\/title"},{"value":[{"kind":"identifier","text":"model3DRotationZ"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DRotationZ\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model2DWidthMeters\/title","value":"model2DWidthMeters","op":"replace"},{"op":"replace","value":[{"text":"model2DWidthMeters","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model2DWidthMeters\/fragments"},{"value":"model3DRotationY","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DRotationY\/title"},{"op":"replace","value":[{"text":"model3DRotationY","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model3DRotationY\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1polygonStrokeColor\/title","value":"polygonStrokeColor"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1polygonStrokeColor\/fragments","value":[{"text":"polygonStrokeColor","kind":"identifier"}],"op":"replace"},{"value":"labelZoomFrom","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1labelZoomFrom\/title"},{"op":"replace","value":[{"text":"labelZoomFrom","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1labelZoomFrom\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model2DVisible\/title","op":"replace","value":"model2DVisible"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1model2DVisible\/fragments","value":[{"text":"model2DVisible","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1polygonFillColor\/title","value":"polygonFillColor","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1polygonFillColor\/fragments","value":[{"kind":"identifier","text":"polygonFillColor"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1zoomTo\/title","value":"zoomTo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule~1zoomTo\/fragments","value":[{"text":"zoomTo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}