{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDisplayRuleManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdisplayrulemanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdisplayrulemanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/defaultDisplayRule"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/getDisplayRuleFor(location:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/getDisplayRuleForTypeName(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/getEffectiveDisplayRuleFor(location:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/removeDisplayRuleForTypeName(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/resetDisplayRuleForLocation(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/resolveDisplayRuleForLocation(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/setDisplayRule(_:forLocation:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/setDisplayRule(_:forLocationId:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/setDisplayRule(_:forTypeName:)"]},{"title":"Type Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/sharedInstance"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDisplayRuleManager"}],"title":"MPDisplayRuleManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@MapsIndoors@objc(cs)MPDisplayRuleManager","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPDisplayRuleManager"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPDisplayRuleManager/getDisplayRuleForTypeName(_:)":{"role":"symbol","title":"getDisplayRuleForTypeName(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDisplayRuleForTypeName"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/getDisplayRuleForTypeName(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDisplayRuleForTypeName:"}],"url":"\/documentation\/mapsindoors\/mpdisplayrulemanager\/getdisplayrulefortypename(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPDisplayRuleManager/removeDisplayRuleForTypeName(_:)":{"role":"symbol","title":"removeDisplayRuleForTypeName(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeDisplayRuleForTypeName"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/removeDisplayRuleForTypeName(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeDisplayRuleForTypeName:"}],"url":"\/documentation\/mapsindoors\/mpdisplayrulemanager\/removedisplayrulefortypename(_:)"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(cs)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPDisplayRuleManager/getDisplayRuleFor(location:)":{"role":"symbol","title":"getDisplayRuleFor(location:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDisplayRuleFor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/getDisplayRuleFor(location:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDisplayRuleForLocation:"}],"url":"\/documentation\/mapsindoors\/mpdisplayrulemanager\/getdisplayrulefor(location:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPDisplayRuleManager/sharedInstance":{"role":"symbol","title":"sharedInstance","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDisplayRuleManager","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRuleManager"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/sharedInstance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedInstance"}],"url":"\/documentation\/mapsindoors\/mpdisplayrulemanager\/sharedinstance"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPDisplayRuleManager/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/mapsindoors\/mpdisplayrulemanager\/init"},"doc://MapsIndoors/documentation/MapsIndoors/MPDisplayRuleManager/setDisplayRule(_:forLocation:)":{"role":"symbol","title":"setDisplayRule(_:forLocation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDisplayRule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/setDisplayRule(_:forLocation:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDisplayRule:forLocation:"}],"url":"\/documentation\/mapsindoors\/mpdisplayrulemanager\/setdisplayrule(_:forlocation:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPDisplayRuleManager/defaultDisplayRule":{"role":"symbol","title":"defaultDisplayRule","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultDisplayRule"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/defaultDisplayRule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultDisplayRule"}],"url":"\/documentation\/mapsindoors\/mpdisplayrulemanager\/defaultdisplayrule"},"doc://MapsIndoors/documentation/MapsIndoors/MPDisplayRuleManager":{"role":"symbol","title":"MPDisplayRuleManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDisplayRuleManager"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDisplayRuleManager"}],"url":"\/documentation\/mapsindoors\/mpdisplayrulemanager"},"doc://MapsIndoors/documentation/MapsIndoors/MPDisplayRuleManager/setDisplayRule(_:forTypeName:)":{"role":"symbol","title":"setDisplayRule(_:forTypeName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDisplayRule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forTypeName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/setDisplayRule(_:forTypeName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDisplayRule:forTypeName:"}],"url":"\/documentation\/mapsindoors\/mpdisplayrulemanager\/setdisplayrule(_:fortypename:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDisplayRuleManager/resolveDisplayRuleForLocation(_:)":{"role":"symbol","title":"resolveDisplayRuleForLocation(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolveDisplayRuleForLocation"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/resolveDisplayRuleForLocation(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resolveDisplayRuleForLocation:"}],"url":"\/documentation\/mapsindoors\/mpdisplayrulemanager\/resolvedisplayruleforlocation(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPDisplayRuleManager/getEffectiveDisplayRuleFor(location:)":{"role":"symbol","title":"getEffectiveDisplayRuleFor(location:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getEffectiveDisplayRuleFor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/getEffectiveDisplayRuleFor(location:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getEffectiveDisplayRuleForLocation:"}],"url":"\/documentation\/mapsindoors\/mpdisplayrulemanager\/geteffectivedisplayrulefor(location:)"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPDisplayRuleManager/setDisplayRule(_:forLocationId:)":{"role":"symbol","title":"setDisplayRule(_:forLocationId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDisplayRule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forLocationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/setDisplayRule(_:forLocationId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDisplayRule:forLocationId:"}],"url":"\/documentation\/mapsindoors\/mpdisplayrulemanager\/setdisplayrule(_:forlocationid:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPDisplayRuleManager/resetDisplayRuleForLocation(_:)":{"role":"symbol","title":"resetDisplayRuleForLocation(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetDisplayRuleForLocation"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/resetDisplayRuleForLocation(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resetDisplayRuleForLocation:"}],"url":"\/documentation\/mapsindoors\/mpdisplayrulemanager\/resetdisplayruleforlocation(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPDisplayRuleManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPDisplayRuleManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPDisplayRuleManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/defaultDisplayRule"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/getDisplayRuleFor(location:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/getDisplayRuleForTypeName(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/getEffectiveDisplayRuleFor(location:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/init","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/removeDisplayRuleForTypeName(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/resetDisplayRuleForLocation(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/resolveDisplayRuleForLocation(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/setDisplayRule(_:forLocation:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/setDisplayRule(_:forLocationId:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/setDisplayRule(_:forTypeName:)"]},{"title":"Type Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDisplayRuleManager\/sharedInstance"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDisplayRuleManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1getDisplayRuleForTypeName(_:)\/title","value":"getDisplayRuleForTypeName:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1getDisplayRuleForTypeName(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDisplayRuleForTypeName:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1removeDisplayRuleForTypeName(_:)\/title","value":"removeDisplayRuleForTypeName:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1removeDisplayRuleForTypeName(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeDisplayRuleForTypeName:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1getDisplayRuleFor(location:)\/title","value":"getDisplayRuleForLocation:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1getDisplayRuleFor(location:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDisplayRuleForLocation:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1sharedInstance\/title","value":"sharedInstance"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1sharedInstance\/fragments","value":[{"kind":"identifier","text":"sharedInstance"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1setDisplayRule(_:forLocation:)\/title","value":"setDisplayRule:forLocation:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1setDisplayRule(_:forLocation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDisplayRule:forLocation:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1defaultDisplayRule\/title","value":"defaultDisplayRule"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1defaultDisplayRule\/fragments","value":[{"kind":"identifier","text":"defaultDisplayRule"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager\/title","value":"MPDisplayRuleManager"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager\/fragments","value":[{"kind":"identifier","text":"MPDisplayRuleManager"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1setDisplayRule(_:forTypeName:)\/title","value":"setDisplayRule:forTypeName:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1setDisplayRule(_:forTypeName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDisplayRule:forTypeName:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1resolveDisplayRuleForLocation(_:)\/title","value":"resolveDisplayRuleForLocation:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1resolveDisplayRuleForLocation(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resolveDisplayRuleForLocation:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1getEffectiveDisplayRuleFor(location:)\/title","value":"getEffectiveDisplayRuleForLocation:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1getEffectiveDisplayRuleFor(location:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getEffectiveDisplayRuleForLocation:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1setDisplayRule(_:forLocationId:)\/title","value":"setDisplayRule:forLocationId:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1setDisplayRule(_:forLocationId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDisplayRule:forLocationId:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1resetDisplayRuleForLocation(_:)\/title","value":"resetDisplayRuleForLocation:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDisplayRuleManager~1resetDisplayRuleForLocation(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetDisplayRuleForLocation:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}