{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsQuery"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsquery"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsquery"]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer"],"generated":true,"title":"Directions"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@MapsIndoors@objc(cs)MPDirectionsQuery","role":"symbol","roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsQuery"}],"modules":[{"name":"MapsIndoors"}],"title":"MPDirectionsQuery","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsQuery"}]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/init(origin:destination:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/init(originPoint:destinationPoint:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/arrival","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/avoidWayTypes","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/departure","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/destination","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/destinationPoint","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/excludeWayTypes","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/origin","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/originPoint","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/travelMode"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTravelMode/walking":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTravelMode\/walking","kind":"symbol","title":"MPTravelMode.walking","type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"walking"}],"url":"\/documentation\/mapsindoors\/mptravelmode\/walking","role":"symbol","navigatorTitle":[{"text":"MPTravelModeWalking","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery/origin":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/origin","role":"symbol","abstract":[{"type":"text","text":"Origin location."}],"title":"origin","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"origin","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"origin"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpdirectionsquery\/origin"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery/originPoint":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/originPoint","title":"originPoint","type":"topic","abstract":[{"type":"text","text":"Origin point."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"originPoint","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","kind":"typeIdentifier","text":"MPPoint"},{"text":"?","kind":"text"}],"url":"\/documentation\/mapsindoors\/mpdirectionsquery\/originpoint","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"originPoint"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery/travelMode":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"travelMode"},{"kind":"text","text":": "},{"text":"MPTravelMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPTravelMode"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/travelMode","type":"topic","abstract":[{"type":"text","text":"Set travel mode. Default is "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTravelMode\/walking","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/mapsindoors\/mpdirectionsquery\/travelmode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"travelMode"}],"title":"travelMode"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLeg":{"url":"\/documentation\/mapsindoors\/mprouteleg","navigatorTitle":[{"kind":"identifier","text":"MPRouteLeg"}],"type":"topic","abstract":[{"text":"Route leg model. A route model will consist of one ore more route legs. Typically a route from 1st floor to 2nd floor will consist of two route legs. Thus, a route leg defines a continuous route part within the same floor and\/or building and\/or vehicle.","type":"text"}],"role":"symbol","title":"MPRouteLeg","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRouteLeg"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery","kind":"symbol","url":"\/documentation\/mapsindoors\/mpdirectionsquery","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsQuery"}],"navigatorTitle":[{"text":"MPDirectionsQuery","kind":"identifier"}],"type":"topic","title":"MPDirectionsQuery"},"doc://com.mapspeople.mapsindoors/SH":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute":{"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","title":"MPRoute","type":"topic","url":"\/documentation\/mapsindoors\/mproute","abstract":[{"type":"text","text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRoute"}],"navigatorTitle":[{"text":"MPRoute","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/SQ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery/avoidWayTypes":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/avoidWayTypes","url":"\/documentation\/mapsindoors\/mpdirectionsquery\/avoidwaytypes","abstract":[{"text":"Way types that should be avoided (may be used if no other routes can be found)  when calculating routes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Supports any "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"If a way type also occurs in "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/excludeWayTypes","isActive":true},{"type":"text","text":" it will be excluded."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"avoidWayTypes"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MPHighway","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"avoidWayTypes","kind":"identifier"}],"type":"topic","title":"avoidWayTypes"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery/departure":{"abstract":[{"type":"text","text":"Date for departure. Setting both arrival and departure will result in undefined behavior."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/departure","kind":"symbol","navigatorTitle":[{"text":"departure","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpdirectionsquery\/departure","title":"departure","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"departure"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsRenderer":{"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer","role":"symbol","title":"MPDirectionsRenderer","kind":"symbol","abstract":[{"type":"text","text":"This allows for an easy way to display a route on the MapsIndoors map. Each leg of the route can be shown individually and can be navigated by manipulating the selected leg index. Various customization options are available to adjust the polyline styling and camera behavior."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPDirectionsRenderer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRenderer"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery/destination":{"title":"destination","abstract":[{"text":"Destination location.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"destination"},{"text":": ","kind":"text"},{"text":"MPLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"destination"}],"url":"\/documentation\/mapsindoors\/mpdirectionsquery\/destination","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/destination"},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery/destinationPoint":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/destinationPoint","kind":"symbol","title":"destinationPoint","type":"topic","abstract":[{"type":"text","text":"Destination point"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"destinationPoint","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","text":"MPPoint"},{"kind":"text","text":"?"}],"url":"\/documentation\/mapsindoors\/mpdirectionsquery\/destinationpoint","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"destinationPoint"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery/excludeWayTypes":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/excludeWayTypes","url":"\/documentation\/mapsindoors\/mpdirectionsquery\/excludewaytypes","abstract":[{"type":"text","text":"Way types that should be excluded (will never be used for a route) when calculating routes."},{"type":"text","text":" "},{"type":"text","text":"Supports any "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"If a way type also occurs in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/avoidWayTypes"},{"type":"text","text":" it will be excluded."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"excludeWayTypes","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MPHighway","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"excludeWayTypes"}],"type":"topic","title":"excludeWayTypes"},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","type":"image","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery/init(originPoint:destinationPoint:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/init(originPoint:destinationPoint:)","kind":"symbol","title":"init(originPoint:destinationPoint:)","type":"topic","abstract":[{"type":"text","text":"Initialiser that takes points as origin and destination."}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"originPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint"},{"text":", ","kind":"text"},{"text":"destinationPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint"},{"text":")","kind":"text"}],"url":"\/documentation\/mapsindoors\/mpdirectionsquery\/init(originpoint:destinationpoint:)","role":"symbol","navigatorTitle":[{"text":"initWithOriginPoint:destinationPoint:","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery/arrival":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/arrival","title":"arrival","type":"topic","abstract":[{"text":"Date for arrival. Setting both arrival and departure will result in undefined behavior.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"arrival","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"url":"\/documentation\/mapsindoors\/mpdirectionsquery\/arrival","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"arrival"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery/init(origin:destination:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/init(origin:destination:)","kind":"symbol","title":"init(origin:destination:)","type":"topic","abstract":[{"type":"text","text":"Initialiser that takes locations as origin and destination."}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"origin","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"text":", ","kind":"text"},{"text":"destination","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"text":")","kind":"text"}],"url":"\/documentation\/mapsindoors\/mpdirectionsquery\/init(origin:destination:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithOrigin:destination:"}]},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway":{"navigatorTitle":[{"text":"MPHighway","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","title":"MPHighway","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPHighway","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Use instances of "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","isActive":true},{"type":"text","text":" to describe which type(s) of route elements to use."}],"url":"\/documentation\/mapsindoors\/mphighway"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsService":{"abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","title":"MPDirectionsService","url":"\/documentation\/mapsindoors\/mpdirectionsservice","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsService"}],"type":"topic","navigatorTitle":[{"text":"MPDirectionsService","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MPDirectionsQuery"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"MPDirectionsQuery","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MPDirectionsQuery","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/arrival","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/avoidWayTypes","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/departure","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/destination","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/destinationPoint","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/excludeWayTypes","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/origin","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/originPoint","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/travelMode"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/init(origin:destination:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery\/init(originPoint:destinationPoint:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Directions","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDirectionsQuery"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"MPTravelModeWalking","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTravelMode~1walking\/title"},{"value":[{"text":"MPTravelModeWalking","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTravelMode~1walking\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1origin\/title","value":"origin","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1origin\/fragments","value":[{"text":"origin","kind":"identifier"}]},{"value":"originPoint","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1originPoint\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1originPoint\/fragments","value":[{"text":"originPoint","kind":"identifier"}]},{"value":"travelMode","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1travelMode\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1travelMode\/fragments","value":[{"kind":"identifier","text":"travelMode"}]},{"op":"replace","value":"MPRouteLeg","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPRouteLeg"}]},{"value":"MPDirectionsQuery","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/fragments","op":"replace","value":[{"text":"MPDirectionsQuery","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/title","value":"MPRoute"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/fragments","value":[{"kind":"identifier","text":"MPRoute"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1avoidWayTypes\/title","op":"replace","value":"avoidWayTypes"},{"op":"replace","value":[{"text":"avoidWayTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1avoidWayTypes\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1departure\/title","value":"departure","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1departure\/fragments","value":[{"text":"departure","kind":"identifier"}]},{"op":"replace","value":"MPDirectionsRenderer","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPDirectionsRenderer"}]},{"value":"destination","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1destination\/title"},{"value":[{"kind":"identifier","text":"destination"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1destination\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1destinationPoint\/title","value":"destinationPoint"},{"value":[{"kind":"identifier","text":"destinationPoint"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1destinationPoint\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1excludeWayTypes\/title","value":"excludeWayTypes"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1excludeWayTypes\/fragments","value":[{"kind":"identifier","text":"excludeWayTypes"}],"op":"replace"},{"value":"initWithOriginPoint:destinationPoint:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1init(originPoint:destinationPoint:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithOriginPoint:destinationPoint:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1init(originPoint:destinationPoint:)\/fragments"},{"value":"arrival","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1arrival\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1arrival\/fragments","value":[{"text":"arrival","kind":"identifier"}]},{"op":"replace","value":"initWithOrigin:destination:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1init(origin:destination:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery~1init(origin:destination:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithOrigin:destination:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway\/title","value":"MPHighway"},{"value":[{"kind":"identifier","text":"MPHighway"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/title","op":"replace","value":"MPDirectionsService"},{"op":"replace","value":[{"kind":"identifier","text":"MPDirectionsService"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/fragments"}]}]}