{"metadata":{"role":"symbol","title":"MPDisplayRuleType","modules":[{"name":"MapsIndoors"}],"externalID":"c:@M@MapsIndoors@E@MPDisplayRuleType","navigatorTitle":[{"text":"MPDisplayRuleType","kind":"identifier"}],"symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDisplayRuleType","kind":"identifier"}],"roleHeading":"Enumeration"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDisplayRuleType"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"inlineContent":[{"text":"Display rules are internally structured as a hierarchy where inheritance is applied. The inheritance of values flow as: ","type":"text"},{"code":"default","type":"codeVoice"},{"text":" -> ","type":"text"},{"code":"main","type":"codeVoice"},{"type":"text","text":" -> "},{"type":"codeVoice","code":"type"},{"text":" -> ","type":"text"},{"code":"location","type":"codeVoice"},{"type":"text","text":" (e.g. if a "},{"type":"codeVoice","code":"type"},{"type":"text","text":" rule is missing a value, it gets it from "},{"code":"main","type":"codeVoice"},{"type":"text","text":")."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The default rule is guaranteed to have non-nil values for all properties."}],"type":"paragraph"}]}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH","doc:\/\/com.mapspeople.mapsindoors\/SY"]}],"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdisplayruletype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdisplayruletype"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The MapsIndoors SDK contains a number of display rules used to style non-location content (blue dot, buildings or locations when they are selected)."}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/blueDot","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/buildingOutline","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/default","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/main","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/selectionHighlight"]},{"title":"Initializers","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/init(rawValue:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/Equatable-Implementations","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/RawRepresentable-Implementations"]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRuleType/selectionHighlight":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"selectionHighlight","kind":"identifier"}],"navigatorTitle":[{"text":"MPDisplayRuleTypeSelectionHighlight","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdisplayruletype\/selectionhighlight","title":"MPDisplayRuleType.selectionHighlight","role":"symbol","abstract":[{"text":"The display rule used for drawing a location, if it is selected. This display rule is entirely respected.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/selectionHighlight"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRuleType/Equatable-Implementations":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/Equatable-Implementations","role":"collectionGroup","kind":"article","abstract":[],"type":"topic","title":"Equatable Implementations","url":"\/documentation\/mapsindoors\/mpdisplayruletype\/equatable-implementations"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRuleType/main":{"title":"MPDisplayRuleType.main","role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayruletype\/main","navigatorTitle":[{"text":"MPDisplayRuleTypeMain","kind":"identifier"}],"abstract":[{"type":"text","text":"The display rule which may be edited via the CMS. The main rule inherits from the default rule."}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/main","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"main"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRuleType/RawRepresentable-Implementations":{"role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/RawRepresentable-Implementations","abstract":[],"url":"\/documentation\/mapsindoors\/mpdisplayruletype\/rawrepresentable-implementations","title":"RawRepresentable Implementations"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRuleType/blueDot":{"abstract":[{"type":"text","text":"The display rule used for drawing the blue dot, only parts of this display rule is respected."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"blueDot"}],"navigatorTitle":[{"text":"MPDisplayRuleTypeBlueDot","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/blueDot","title":"MPDisplayRuleType.blueDot","url":"\/documentation\/mapsindoors\/mpdisplayruletype\/bluedot"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRuleType/init(rawValue:)":{"type":"topic","title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/init(rawValue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/mapsindoors\/mpdisplayruletype\/init(rawvalue:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRuleType/buildingOutline":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/buildingOutline","abstract":[{"type":"text","text":"The display  rule used for drawing outline of the current building, only parts of this display rule is respected."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"buildingOutline","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPDisplayRuleTypeBuildingOutline"}],"title":"MPDisplayRuleType.buildingOutline","url":"\/documentation\/mapsindoors\/mpdisplayruletype\/buildingoutline","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRuleType":{"type":"topic","title":"MPDisplayRuleType","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType","navigatorTitle":[{"text":"MPDisplayRuleType","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MPDisplayRuleType","kind":"identifier"}],"abstract":[{"text":"The MapsIndoors SDK contains a number of display rules used to style non-location content (blue dot, buildings or locations when they are selected).","type":"text"}],"url":"\/documentation\/mapsindoors\/mpdisplayruletype"},"doc://com.mapspeople.mapsindoors/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se"},"doc://com.mapspeople.mapsindoors/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRuleType/default":{"title":"MPDisplayRuleType.default","role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayruletype\/default","navigatorTitle":[{"text":"MPDisplayRuleTypeDefault","kind":"identifier"}],"abstract":[{"type":"text","text":"The display rule at the root of the display rule inheritance. This is hardcoded into the MapsIndoors SDK. The main rule inherits from the default rule."}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/default","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}]},"doc://com.mapspeople.mapsindoors/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ"},"doc://com.mapspeople.mapsindoors/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH"},"doc://com.mapspeople.mapsindoors/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SY"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"MPDisplayRuleType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MPDisplayRuleType","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPDisplayRuleType"}]},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/blueDot","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/buildingOutline","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/default","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/main","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType\/selectionHighlight"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MPDisplayRuleType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType~1selectionHighlight\/title","value":"MPDisplayRuleTypeSelectionHighlight","op":"replace"},{"value":[{"text":"MPDisplayRuleTypeSelectionHighlight","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType~1selectionHighlight\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType~1main\/title","op":"replace","value":"MPDisplayRuleTypeMain"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType~1main\/fragments","value":[{"kind":"identifier","text":"MPDisplayRuleTypeMain"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType~1blueDot\/title","value":"MPDisplayRuleTypeBlueDot","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType~1blueDot\/fragments","value":[{"kind":"identifier","text":"MPDisplayRuleTypeBlueDot"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType~1buildingOutline\/title","value":"MPDisplayRuleTypeBuildingOutline"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType~1buildingOutline\/fragments","op":"replace","value":[{"text":"MPDisplayRuleTypeBuildingOutline","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType\/title","op":"replace","value":"MPDisplayRuleType"},{"value":[{"kind":"identifier","text":"MPDisplayRuleType"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType~1default\/title","value":"MPDisplayRuleTypeDefault"},{"value":[{"text":"MPDisplayRuleTypeDefault","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType~1default\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}