{"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRendererDelegate\/onDirectionsRendererChangedFloor(floorIndex:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRendererDelegate"}]}]},{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"inlineContent":[{"type":"text","text":"A default implementation can be accessed and used via "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/newDirectionsRenderer()","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdirectionsrendererdelegate"]},{"paths":["\/documentation\/mapsindoors\/mpdirectionsrendererdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRendererDelegate"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"sections":[],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"protocol","externalID":"c:@M@MapsIndoors@objc(pl)MPDirectionsRendererDelegate","title":"MPDirectionsRendererDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsRendererDelegate"}],"navigatorTitle":[{"text":"MPDirectionsRendererDelegate","kind":"identifier"}],"roleHeading":"Protocol","modules":[{"name":"MapsIndoors"}]},"abstract":[{"text":"Protocol to conform to when implementing a directions renderer for MapsIndoors.","type":"text"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsRendererDelegate":{"type":"topic","abstract":[{"type":"text","text":"Protocol to conform to when implementing a directions renderer for MapsIndoors."}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRendererDelegate","url":"\/documentation\/mapsindoors\/mpdirectionsrendererdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDirectionsRendererDelegate"}],"title":"MPDirectionsRendererDelegate","kind":"symbol","navigatorTitle":[{"text":"MPDirectionsRendererDelegate","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoute"}],"url":"\/documentation\/mapsindoors\/mproute","navigatorTitle":[{"kind":"identifier","text":"MPRoute"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","title":"MPRoute","role":"symbol","abstract":[{"text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","isActive":true,"type":"reference"},{"text":".","type":"text"}]},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","alt":null,"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsRendererDelegate/onDirectionsRendererChangedFloor(floorIndex:)":{"type":"topic","role":"symbol","url":"\/documentation\/mapsindoors\/mpdirectionsrendererdelegate\/ondirectionsrendererchangedfloor(floorindex:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onDirectionsRendererChangedFloor","kind":"identifier"},{"kind":"text","text":"("},{"text":"floorIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRendererDelegate\/onDirectionsRendererChangedFloor(floorIndex:)","abstract":[],"navigatorTitle":[{"text":"onDirectionsRendererChangedFloorWithFloorIndex:","kind":"identifier"}],"title":"onDirectionsRendererChangedFloor(floorIndex:)","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsRenderer":{"type":"topic","abstract":[{"text":"This allows for an easy way to display a route on the MapsIndoors map. Each leg of the route can be shown individually and can be navigated by manipulating the selected leg index. Various customization options are available to adjust the polyline styling and camera behavior.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer","url":"\/documentation\/mapsindoors\/mpdirectionsrenderer","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDirectionsRenderer"}],"kind":"symbol","title":"MPDirectionsRenderer","navigatorTitle":[{"text":"MPDirectionsRenderer","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/newDirectionsRenderer()":{"abstract":[{"type":"text","text":"Get a "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer","isActive":true},{"type":"text","text":" to show a "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","isActive":true},{"text":" on the map.","type":"text"}],"required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"newDirectionsRenderer","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDirectionsRenderer","text":"MPDirectionsRenderer","kind":"typeIdentifier"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/newdirectionsrenderer()","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/newDirectionsRenderer()","navigatorTitle":[{"text":"newDirectionsRenderer","kind":"identifier"}],"type":"topic","title":"newDirectionsRenderer()","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MPDirectionsRendererDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPDirectionsRendererDelegate"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPDirectionsRendererDelegate"}]},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRendererDelegate\/onDirectionsRendererChangedFloor(floorIndex:)"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDirectionsRendererDelegate"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"MPDirectionsRendererDelegate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRendererDelegate\/title"},{"value":[{"text":"MPDirectionsRendererDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRendererDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/title","value":"MPRoute","op":"replace"},{"op":"replace","value":[{"text":"MPRoute","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/fragments"},{"op":"replace","value":"onDirectionsRendererChangedFloorWithFloorIndex:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRendererDelegate~1onDirectionsRendererChangedFloor(floorIndex:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRendererDelegate~1onDirectionsRendererChangedFloor(floorIndex:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDirectionsRendererChangedFloorWithFloorIndex:"}]},{"value":"MPDirectionsRenderer","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/title"},{"value":[{"text":"MPDirectionsRenderer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/fragments"},{"value":"newDirectionsRenderer","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1newDirectionsRenderer()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"newDirectionsRenderer"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1newDirectionsRenderer()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}