{"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"MPEntity"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPEntity"}],"role":"symbol","modules":[{"name":"MapsIndoors"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPEntity","roleHeading":"Protocol","symbolKind":"protocol","title":"MPEntity"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"abstract":[{"type":"text","text":"MPEntity is a general protocol implemented by "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","isActive":true},{"type":"text","text":", "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","isActive":true,"type":"reference"},{"text":" and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue"},{"text":".","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity\/entityBounds","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity\/entityIsPoint","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity\/entityPosition"],"title":"Instance Properties"}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpentity"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpentity"]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritedBy","title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPEntity","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFloor":{"type":"topic","navigatorTitle":[{"text":"MPFloor","kind":"identifier"}],"abstract":[{"text":"Floor data model. Holds the floor geometry, display name, z-index and id of the building it belongs to.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor","kind":"symbol","url":"\/documentation\/mapsindoors\/mpfloor","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPFloor","kind":"identifier"}],"title":"MPFloor"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue":{"title":"MPVenue","url":"\/documentation\/mapsindoors\/mpvenue","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPVenue","kind":"identifier"}],"abstract":[{"text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"MPVenue","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue"},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"type":"image","identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation":{"url":"\/documentation\/mapsindoors\/mplocation","abstract":[{"type":"text","text":"This holds the data for a single location and a marker to display the data on a map."}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPLocation","kind":"identifier"}],"title":"MPLocation","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MPLocation","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding":{"abstract":[{"text":"Holds relevant data for a single building, and the buildings floor levels.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","title":"MPBuilding","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPBuilding"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpbuilding","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPBuilding"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPEntity":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPEntity"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity","abstract":[{"text":"MPEntity is a general protocol implemented by ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","isActive":true},{"type":"text","text":", "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","isActive":true,"type":"reference"},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","isActive":true},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpentity","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPEntity","kind":"identifier"}],"title":"MPEntity"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPEntity/entityIsPoint":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity\/entityIsPoint","kind":"symbol","url":"\/documentation\/mapsindoors\/mpentity\/entityispoint","navigatorTitle":[{"kind":"identifier","text":"entityIsPoint"}],"abstract":[{"type":"text","text":"Indicates if the entity’s geometry is a point or a polygon."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entityIsPoint","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","required":true,"type":"topic","title":"entityIsPoint"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPEntity/entityPosition":{"url":"\/documentation\/mapsindoors\/mpentity\/entityposition","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity\/entityPosition","navigatorTitle":[{"kind":"identifier","text":"entityPosition"}],"abstract":[{"text":"The MapsIndoors entity’s point.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"entityPosition","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","text":"MPPoint","kind":"typeIdentifier"}],"role":"symbol","required":true,"title":"entityPosition","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPEntity/entityBounds":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity\/entityBounds","kind":"symbol","url":"\/documentation\/mapsindoors\/mpentity\/entitybounds","navigatorTitle":[{"kind":"identifier","text":"entityBounds"}],"abstract":[{"type":"text","text":"The MapsIndoors entity’s bounding box."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entityBounds","kind":"identifier"},{"kind":"text","text":": "},{"text":"MPGeoBounds","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds"}],"role":"symbol","required":true,"type":"topic","title":"entityBounds"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"value":"MPEntity","op":"replace","path":"\/metadata\/title"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MPEntity","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MPEntity"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity\/entityBounds","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity\/entityIsPoint","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity\/entityPosition"]}]},{"path":"\/relationshipsSections","value":[{"type":"inheritedBy","title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue"]}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPEntity","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"MPFloor","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor\/fragments","value":[{"text":"MPFloor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/title","value":"MPVenue","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/fragments","value":[{"text":"MPVenue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/title","value":"MPLocation"},{"value":[{"kind":"identifier","text":"MPLocation"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/title","value":"MPBuilding"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/fragments","value":[{"kind":"identifier","text":"MPBuilding"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntity\/title","value":"MPEntity"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntity\/fragments","value":[{"text":"MPEntity","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntity~1entityIsPoint\/title","op":"replace","value":"entityIsPoint"},{"value":[{"kind":"identifier","text":"entityIsPoint"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntity~1entityIsPoint\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntity~1entityPosition\/title","value":"entityPosition","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"entityPosition"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntity~1entityPosition\/fragments"},{"op":"replace","value":"entityBounds","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntity~1entityBounds\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntity~1entityBounds\/fragments","value":[{"kind":"identifier","text":"entityBounds"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}