{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPEncodedPolyline","kind":"identifier"}]}]}],"metadata":{"modules":[{"name":"MapsIndoors"}],"symbolKind":"protocol","roleHeading":"Protocol","title":"MPEncodedPolyline","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPEncodedPolyline"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPEncodedPolyline","role":"symbol","navigatorTitle":[{"text":"MPEncodedPolyline","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEncodedPolyline"},"kind":"symbol","variants":[{"paths":["\/documentation\/mapsindoors\/mpencodedpolyline"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpencodedpolyline"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEncodedPolyline\/points"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPEncodedPolyline/points":{"title":"points","navigatorTitle":[{"text":"points","kind":"identifier"}],"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"kind":"symbol","required":true,"url":"\/documentation\/mapsindoors\/mpencodedpolyline\/points","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEncodedPolyline\/points","type":"topic","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null,"identifier":"MapsPeopleWhite.png","type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPEncodedPolyline":{"title":"MPEncodedPolyline","navigatorTitle":[{"kind":"identifier","text":"MPEncodedPolyline"}],"abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPEncodedPolyline"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpencodedpolyline","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEncodedPolyline","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPEncodedPolyline"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPEncodedPolyline"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MPEncodedPolyline","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEncodedPolyline\/points"],"title":"Instance Properties"}],"path":"\/topicSections","op":"replace"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPEncodedPolyline"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEncodedPolyline~1points\/title","value":"points","op":"replace"},{"value":[{"kind":"identifier","text":"points"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEncodedPolyline~1points\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEncodedPolyline\/title","value":"MPEncodedPolyline","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEncodedPolyline\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPEncodedPolyline"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}