{"relationshipsSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/s5ErrorP","doc:\/\/com.mapspeople.mapsindoors\/SH","doc:\/\/com.mapspeople.mapsindoors\/SY","doc:\/\/com.mapspeople.mapsindoors\/s8SendableP"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPError","kind":"identifier"}],"languages":["swift"]}]}],"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/directionsMatrixNotFound","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/directionsRouteNotFound","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/imageAssetNotFound","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/invalidApiKey","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/networkError","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/unknownError"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/description"],"title":"Instance Properties"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/Equatable-Implementations","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/Error-Implementations","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/RawRepresentable-Implementations"]}],"abstract":[{"type":"text","text":"MapsIndoors error codes"}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/mapsindoors\/mperror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mperror"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"metadata":{"modules":[{"name":"MapsIndoors"}],"symbolKind":"enum","roleHeading":"Enumeration","title":"MPError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPError","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@E@MPError","role":"symbol","navigatorTitle":[{"text":"MPError","kind":"identifier"}]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.mapspeople.mapsindoors/SQ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/SY":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError/description":{"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/mapsindoors\/mperror\/description","title":"description","kind":"symbol","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError/imageAssetNotFound":{"navigatorTitle":[{"kind":"identifier","text":"MPErrorImageAssetNotFound"}],"url":"\/documentation\/mapsindoors\/mperror\/imageassetnotfound","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/imageAssetNotFound","kind":"symbol","title":"MPError.imageAssetNotFound","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageAssetNotFound"}]},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"identifier":"MapsPeopleWhite.png","type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError/directionsRouteNotFound":{"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/directionsRouteNotFound","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"directionsRouteNotFound"}],"url":"\/documentation\/mapsindoors\/mperror\/directionsroutenotfound","type":"topic","title":"MPError.directionsRouteNotFound","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPErrorDirectionsRouteNotFound"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError/networkError":{"url":"\/documentation\/mapsindoors\/mperror\/networkerror","title":"MPError.networkError","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"networkError","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/networkError","navigatorTitle":[{"text":"MPErrorNetworkError","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError/directionsMatrixNotFound":{"abstract":[],"type":"topic","title":"MPError.directionsMatrixNotFound","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"directionsMatrixNotFound","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/directionsMatrixNotFound","url":"\/documentation\/mapsindoors\/mperror\/directionsmatrixnotfound","role":"symbol","navigatorTitle":[{"text":"MPErrorDirectionsMatrixNotFound","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError/unknownError":{"navigatorTitle":[{"text":"MPErrorUnknownError","kind":"identifier"}],"abstract":[],"type":"topic","title":"MPError.unknownError","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/unknownError","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mperror\/unknownerror"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError/RawRepresentable-Implementations":{"url":"\/documentation\/mapsindoors\/mperror\/rawrepresentable-implementations","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/RawRepresentable-Implementations","role":"collectionGroup","title":"RawRepresentable Implementations","kind":"article"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError":{"type":"topic","navigatorTitle":[{"text":"MPError","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError","abstract":[{"type":"text","text":"MapsIndoors error codes"}],"title":"MPError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPError","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mperror","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError/invalidApiKey":{"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/invalidApiKey","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidApiKey","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mperror\/invalidapikey","type":"topic","kind":"symbol","title":"MPError.invalidApiKey","navigatorTitle":[{"text":"MPErrorInvalidApiKey","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/SH":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/Se":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/s8SendableP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/s5ErrorP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s5ErrorP","title":"Swift.Error","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/SE":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError/init(rawValue:)":{"role":"symbol","url":"\/documentation\/mapsindoors\/mperror\/init(rawvalue:)","type":"topic","kind":"symbol","title":"init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/init(rawValue:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError/Error-Implementations":{"kind":"article","role":"collectionGroup","type":"topic","abstract":[],"title":"Error Implementations","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/Error-Implementations","url":"\/documentation\/mapsindoors\/mperror\/error-implementations"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError/Equatable-Implementations":{"kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mperror\/equatable-implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/Equatable-Implementations","title":"Equatable Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","value":"MPError","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPError"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MPError"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/directionsMatrixNotFound","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/directionsRouteNotFound","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/imageAssetNotFound","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/invalidApiKey","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/networkError","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/unknownError"]}],"op":"replace"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MPError","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1imageAssetNotFound\/title","value":"MPErrorImageAssetNotFound"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1imageAssetNotFound\/fragments","value":[{"text":"MPErrorImageAssetNotFound","kind":"identifier"}],"op":"replace"},{"value":"MPErrorDirectionsRouteNotFound","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1directionsRouteNotFound\/title","op":"replace"},{"value":[{"text":"MPErrorDirectionsRouteNotFound","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1directionsRouteNotFound\/fragments"},{"value":"MPErrorNetworkError","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1networkError\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1networkError\/fragments","value":[{"kind":"identifier","text":"MPErrorNetworkError"}]},{"value":"MPErrorDirectionsMatrixNotFound","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1directionsMatrixNotFound\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1directionsMatrixNotFound\/fragments","value":[{"kind":"identifier","text":"MPErrorDirectionsMatrixNotFound"}]},{"value":"MPErrorUnknownError","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1unknownError\/title","op":"replace"},{"op":"replace","value":[{"text":"MPErrorUnknownError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1unknownError\/fragments"},{"value":"MPError","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError\/fragments","value":[{"kind":"identifier","text":"MPError"}]},{"value":"MPErrorInvalidApiKey","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1invalidApiKey\/title"},{"value":[{"kind":"identifier","text":"MPErrorInvalidApiKey"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1invalidApiKey\/fragments"}]}]}