{"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter","interfaceLanguage":"swift"},"abstract":[{"text":"Filter object used when making a request to e.g. ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFilter"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"inlineContent":[{"text":"The filters will be applied in the following order:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Bounds filter","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Locations filter"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Floor index filter"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Categories filter"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Types filter"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Parents and depth filter","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Take filter"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Skip filter"}]}]}],"type":"orderedList"},{"inlineContent":[{"text":"Locations must pass all filters to be part of the result.","type":"text"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpfilter"]},{"paths":["\/documentation\/mapsindoors\/mpfilter"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"Searching for Locations","generated":true,"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/init()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/init(categories:bounds:parents:take:skip:depth:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/init(from:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/bounds","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/categories","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/depth","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/floorIndex","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/ignoreActiveStatus","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/ignoreSearchableStatus","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/locations","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/parents","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/skip","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/take","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/types"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/encode(to:)"],"title":"Instance Methods"}],"metadata":{"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"MPFilter"}],"modules":[{"name":"MapsIndoors"}],"roleHeading":"Class","title":"MPFilter","externalID":"c:@M@MapsIndoors@objc(cs)MPFilter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPFilter","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/ignoreSearchableStatus":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ignoreSearchableStatus"}],"url":"\/documentation\/mapsindoors\/mpfilter\/ignoresearchablestatus","kind":"symbol","type":"topic","title":"ignoreSearchableStatus","abstract":[{"text":"Include otherwise unsearchable locations in your search. Default value is false.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignoreSearchableStatus"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/ignoreSearchableStatus"},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/categories":{"url":"\/documentation\/mapsindoors\/mpfilter\/categories","title":"categories","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"categories","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/categories","abstract":[{"type":"text","text":"Categories filter. List of category keys as in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/categories"},{"type":"text","text":". If multiple categories are supplied the filter will OR’ed, meaning if a Location belongs to at least one of the categories it will be considered as a match."}],"role":"symbol","navigatorTitle":[{"text":"categories","kind":"identifier"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/SH":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable","type":"unresolvable"},"MapsPeopleWhite.png":{"alt":null,"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/locationId":{"title":"locationId","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"locationId"}],"type":"topic","abstract":[{"type":"text","text":"Location id property."}],"url":"\/documentation\/mapsindoors\/mplocation\/locationid","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"locationId","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/locationId","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/init()":{"role":"symbol","abstract":[{"text":"Initialise a MPFilter with all properties set to default values as described in ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/init(categories:bounds:parents:take:skip:depth:)","type":"reference","isActive":true},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpfilter\/init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/init()","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"title":"init()"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/init(categories:bounds:parents:take:skip:depth:)":{"role":"symbol","abstract":[{"text":"Initialise a MPFilter with all properties.","type":"text"},{"text":" ","type":"text"},{"text":"From Swift all values are optional which will set them to the default values.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpfilter\/init(categories:bounds:parents:take:skip:depth:)","navigatorTitle":[{"kind":"identifier","text":"initWithCategories:bounds:parents:take:skip:depth:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/init(categories:bounds:parents:take:skip:depth:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"categories","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"bounds","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","text":"MPGeoBounds","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"parents","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"take"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"skip"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"depth","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(categories:bounds:parents:take:skip:depth:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/locations":{"role":"symbol","abstract":[{"type":"text","text":"Locations filter. List of location ids as in "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/locationId","type":"reference","isActive":true},{"type":"text","text":". If multiple locations are supplied the filter will OR’ed."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpfilter\/locations","navigatorTitle":[{"text":"locations","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/locations","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"locations","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]","kind":"text"}],"title":"locations"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter":{"role":"symbol","abstract":[{"type":"text","text":"Filter object used when making a request to e.g. "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","isActive":true},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpfilter","navigatorTitle":[{"text":"MPFilter","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPFilter","kind":"identifier"}],"title":"MPFilter"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/take":{"url":"\/documentation\/mapsindoors\/mpfilter\/take","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"take","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"take","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Limit number of locations in the result."}],"kind":"symbol","title":"take","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/take","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/locationsWith(query:filter:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"locationsWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"query"},{"text":": ","kind":"text"},{"text":"MPQuery","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPQuery","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"filter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPFilter","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilter"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"kind":"text","text":"]"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"locationsWithQuery:filter:completionHandler:","kind":"identifier"}],"title":"locationsWith(query:filter:)","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/locationswith(query:filter:)","kind":"symbol","required":true,"abstract":[{"type":"text","text":"Search for MPLocations using MPQuery and\/or MPFilter."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/bounds":{"url":"\/documentation\/mapsindoors\/mpfilter\/bounds","title":"bounds","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bounds"},{"kind":"text","text":": "},{"text":"MPGeoBounds","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/bounds","abstract":[{"type":"text","text":"Rectangular geographical bounds filter."}],"role":"symbol","navigatorTitle":[{"text":"bounds","kind":"identifier"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/init(from:)":{"role":"symbol","url":"\/documentation\/mapsindoors\/mpfilter\/init(from:)","kind":"symbol","type":"topic","title":"init(from:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Decoder","preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/init(from:)"},"doc://com.mapspeople.mapsindoors/SQ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/SE":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/skip":{"url":"\/documentation\/mapsindoors\/mpfilter\/skip","title":"skip","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"skip"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/skip","abstract":[{"type":"text","text":"Skip locations in the result, e.g. for pagination."}],"role":"symbol","navigatorTitle":[{"text":"skip","kind":"identifier"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/encode(to:)":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpfilter\/encode(to:)","title":"encode(to:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Encoder","preciseIdentifier":"s:s7EncoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/encode(to:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/parents":{"role":"symbol","abstract":[{"text":"List of location ids that is hierarchically considered as a parent of other locations.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpfilter\/parents","navigatorTitle":[{"text":"parents","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/parents","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parents","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"title":"parents"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/floorIndex":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/floorIndex","kind":"symbol","title":"floorIndex","type":"topic","url":"\/documentation\/mapsindoors\/mpfilter\/floorindex","abstract":[{"text":"Filter by floor index. Note that there is a difference between the displayed floor name (e.g. “LG”) and the index (e.g. -1).","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"floorIndex","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"floorIndex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/types":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/types","navigatorTitle":[{"kind":"identifier","text":"types"}],"abstract":[{"text":"Types filter. List of type names as in ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/type"},{"text":". If multiple types are supplied the filter will OR’ed, meaning if a location belongs to at least one of the types it will be considered as a match.","type":"text"}],"role":"symbol","title":"types","url":"\/documentation\/mapsindoors\/mpfilter\/types","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"types"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/Se":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/categories":{"title":"categories","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"categories"}],"type":"topic","abstract":[{"type":"text","text":"The categories for this location, as an array."}],"url":"\/documentation\/mapsindoors\/mplocation\/categories","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"categories"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/categories","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/ignoreActiveStatus":{"abstract":[{"type":"text","text":"Include otherwise inactive locations in your search. Default value is false."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/ignoreActiveStatus","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ignoreActiveStatus"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ignoreActiveStatus"}],"title":"ignoreActiveStatus","url":"\/documentation\/mapsindoors\/mpfilter\/ignoreactivestatus"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/type":{"title":"type","required":true,"kind":"symbol","navigatorTitle":[{"text":"type","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Location type property."}],"url":"\/documentation\/mapsindoors\/mplocation\/type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/type","role":"symbol"},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter/depth":{"url":"\/documentation\/mapsindoors\/mpfilter\/depth","title":"depth","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"depth"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/depth","abstract":[{"text":"The depth property makes it possible to get the n’th descendant of a parent location.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Thus, the depth property only applies to filters that has set one or more parents."}],"role":"symbol","navigatorTitle":[{"text":"depth","kind":"identifier"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPQuery":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPQuery","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"MPQuery","kind":"identifier"}],"title":"MPQuery","url":"\/documentation\/mapsindoors\/mpquery","kind":"symbol","abstract":[{"type":"text","text":"Query object used when making a request to "},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","type":"reference"},{"text":".","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"MPFilter","path":"\/metadata\/title","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"MPFilter","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MPFilter","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/bounds","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/categories","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/depth","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/floorIndex","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/ignoreActiveStatus","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/ignoreSearchableStatus","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/locations","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/parents","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/skip","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/take","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/types"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/init()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter\/init(categories:bounds:parents:take:skip:depth:)"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"Searching for Locations","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery"]}]},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFilter"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1ignoreSearchableStatus\/title","value":"ignoreSearchableStatus"},{"op":"replace","value":[{"kind":"identifier","text":"ignoreSearchableStatus"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1ignoreSearchableStatus\/fragments"},{"value":"categories","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1categories\/title"},{"value":[{"text":"categories","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1categories\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1locationId\/title","value":"locationId","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1locationId\/fragments","value":[{"text":"locationId","kind":"identifier"}]},{"op":"replace","value":"init","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1init()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1init(categories:bounds:parents:take:skip:depth:)\/title","value":"initWithCategories:bounds:parents:take:skip:depth:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCategories:bounds:parents:take:skip:depth:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1init(categories:bounds:parents:take:skip:depth:)\/fragments"},{"value":"locations","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1locations\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1locations\/fragments","value":[{"text":"locations","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MPFilter","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MPFilter"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1take\/title","value":"take","op":"replace"},{"value":[{"text":"take","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1take\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/title","op":"replace","value":"locationsWithQuery:filter:completionHandler:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"locationsWithQuery:filter:completionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1bounds\/title","value":"bounds"},{"value":[{"text":"bounds","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1bounds\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1skip\/title","value":"skip"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1skip\/fragments","value":[{"kind":"identifier","text":"skip"}],"op":"replace"},{"value":"parents","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1parents\/title","op":"replace"},{"value":[{"kind":"identifier","text":"parents"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1parents\/fragments","op":"replace"},{"value":"floorIndex","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1floorIndex\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1floorIndex\/fragments","value":[{"text":"floorIndex","kind":"identifier"}]},{"value":"types","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1types\/title","op":"replace"},{"value":[{"kind":"identifier","text":"types"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1types\/fragments"},{"value":"categories","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1categories\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1categories\/fragments","op":"replace","value":[{"kind":"identifier","text":"categories"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1ignoreActiveStatus\/title","value":"ignoreActiveStatus"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1ignoreActiveStatus\/fragments","value":[{"text":"ignoreActiveStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1type\/title","value":"type"},{"value":[{"text":"type","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1type\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1depth\/title","op":"replace","value":"depth"},{"value":[{"text":"depth","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter~1depth\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery\/title","value":"MPQuery"},{"value":[{"kind":"identifier","text":"MPQuery"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery\/fragments"}]}]}