{"metadata":{"roleHeading":"Protocol","title":"MPFloor","navigatorTitle":[{"kind":"identifier","text":"MPFloor"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPFloor","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPFloor"}],"symbolKind":"protocol","modules":[{"name":"MapsIndoors"}]},"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/aliases","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/buildingId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/floorId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/floorIndex","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/style"],"title":"Instance Properties"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity"],"kind":"relationships"}],"kind":"symbol","abstract":[{"type":"text","text":"Floor data model. Holds the floor geometry, display name, z-index and id of the building it belongs to."}],"seeAlsoSections":[{"title":"MapsIndoors entities","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(MPFloor) ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPFloor"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPEntity","text":"MPEntity"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpfloor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpfloor"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor","interfaceLanguage":"swift"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFloor/style":{"title":"style","kind":"symbol","abstract":[{"type":"text","text":"The Floor layer style, if any."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/style","navigatorTitle":[{"kind":"identifier","text":"style"}],"url":"\/documentation\/mapsindoors\/mpfloor\/style","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFloor/name":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/name","abstract":[{"type":"text","text":"The Floor name."}],"url":"\/documentation\/mapsindoors\/mpfloor\/name","title":"name","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"required":true,"navigatorTitle":[{"text":"name","kind":"identifier"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFloor/buildingId":{"required":true,"role":"symbol","title":"buildingId","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildingId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"The id of the Building this Floor belongs to.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/buildingId","url":"\/documentation\/mapsindoors\/mpfloor\/buildingid","navigatorTitle":[{"text":"buildingId","kind":"identifier"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFloor":{"role":"symbol","type":"topic","title":"MPFloor","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPFloor","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpfloor","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor","abstract":[{"type":"text","text":"Floor data model. Holds the floor geometry, display name, z-index and id of the building it belongs to."}],"navigatorTitle":[{"text":"MPFloor","kind":"identifier"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding":{"kind":"symbol","abstract":[{"type":"text","text":"Holds relevant data for a single building, and the buildings floor levels."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","navigatorTitle":[{"text":"MPBuilding","kind":"identifier"}],"type":"topic","title":"MPBuilding","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPBuilding","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpbuilding","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPEntity":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPEntity"}],"navigatorTitle":[{"kind":"identifier","text":"MPEntity"}],"url":"\/documentation\/mapsindoors\/mpentity","abstract":[{"type":"text","text":"MPEntity is a general protocol implemented by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation"},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","isActive":true},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue"},{"type":"text","text":"."}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity","kind":"symbol","title":"MPEntity"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPVenue"}],"title":"MPVenue","navigatorTitle":[{"text":"MPVenue","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpvenue","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","role":"symbol","abstract":[{"text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data.","type":"text"}],"type":"topic","kind":"symbol"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFloor/floorIndex":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"floorIndex","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"floorIndex"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/floorIndex","abstract":[{"type":"text","text":"The Floor index."}],"required":true,"type":"topic","role":"symbol","kind":"symbol","title":"floorIndex","url":"\/documentation\/mapsindoors\/mpfloor\/floorindex"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFloor/floorId":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"floorId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"floorId"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/floorId","abstract":[{"text":"The Floor id.","type":"text"}],"required":true,"type":"topic","role":"symbol","kind":"symbol","title":"floorId","url":"\/documentation\/mapsindoors\/mpfloor\/floorid"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFloor/aliases":{"required":true,"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aliases"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/aliases","abstract":[{"type":"text","text":"The Floor aliases."}],"url":"\/documentation\/mapsindoors\/mpfloor\/aliases","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"aliases"}],"title":"aliases"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation":{"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","abstract":[{"type":"text","text":"This holds the data for a single location and a marker to display the data on a map."}],"url":"\/documentation\/mapsindoors\/mplocation","role":"symbol","title":"MPLocation","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"navigatorTitle":[{"text":"MPLocation","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"MPFloor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPFloor"}],"op":"replace"},{"op":"replace","value":[{"text":"MPFloor","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/aliases","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/buildingId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/floorId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/floorIndex","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/style"]}],"path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"title":"MapsIndoors entities","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation"],"generated":true}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPFloor","kind":"identifier"},{"kind":"text","text":" <"},{"text":"MPEntity","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPEntity"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"style","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor~1style\/title"},{"value":[{"kind":"identifier","text":"style"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor~1style\/fragments","op":"replace"},{"op":"replace","value":"name","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor~1name\/title"},{"value":[{"text":"name","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor~1name\/fragments"},{"op":"replace","value":"buildingId","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor~1buildingId\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor~1buildingId\/fragments","value":[{"kind":"identifier","text":"buildingId"}],"op":"replace"},{"value":"MPFloor","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor\/title"},{"value":[{"text":"MPFloor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor\/fragments","op":"replace"},{"value":"MPBuilding","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/title"},{"value":[{"text":"MPBuilding","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/fragments"},{"value":"MPEntity","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntity\/title","op":"replace"},{"value":[{"text":"MPEntity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntity\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/title","value":"MPVenue"},{"value":[{"text":"MPVenue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor~1floorIndex\/title","op":"replace","value":"floorIndex"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor~1floorIndex\/fragments","value":[{"kind":"identifier","text":"floorIndex"}]},{"value":"floorId","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor~1floorId\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor~1floorId\/fragments","op":"replace","value":[{"kind":"identifier","text":"floorId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor~1aliases\/title","value":"aliases"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor~1aliases\/fragments","value":[{"text":"aliases","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/title","value":"MPLocation","op":"replace"},{"value":[{"text":"MPLocation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}