{"kind":"symbol","metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPGeoRegion","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"roleHeading":"Class","title":"MPGeoRegion","externalID":"c:@M@MapsIndoors@objc(cs)MPGeoRegion","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPGeoRegion"}],"symbolKind":"class"},"variants":[{"paths":["\/documentation\/mapsindoors\/mpgeoregion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpgeoregion"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/init(from:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/init(nearLeft:farLeft:farRight:nearRight:)"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/area","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/bounds","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/center","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/farLeft","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/farRight","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/nearLeft","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/nearRight","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/polygon"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/distanceTo(other:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/encode(to:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/intersectsWith(other:)"],"title":"Instance Methods"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPGeoRegion"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol","doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"title":"Conforms To","kind":"relationships"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoRegion/nearRight":{"kind":"symbol","title":"nearRight","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/nearRight","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nearRight"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"}],"role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/mapsindoors\/mpgeoregion\/nearright","navigatorTitle":[{"text":"nearRight","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoRegion/distanceTo(other:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"distanceTo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"other"},{"text":": ","kind":"text"},{"text":"MPGeometryProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol"},{"kind":"text","text":") -> "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/distanceTo(other:)","title":"distanceTo(other:)","navigatorTitle":[{"kind":"identifier","text":"distanceToOther:"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpgeoregion\/distanceto(other:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoRegion/nearLeft":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nearLeft"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/nearLeft","abstract":[],"title":"nearLeft","navigatorTitle":[{"kind":"identifier","text":"nearLeft"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpgeoregion\/nearleft","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoRegion/init(from:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Decoder","preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/mapsindoors\/mpgeoregion\/init(from:)","title":"init(from:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/init(from:)"},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoRegion/center":{"abstract":[],"title":"center","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/center","role":"symbol","navigatorTitle":[{"text":"center","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpgeoregion\/center","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"center"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPoint","text":"MPGeoPoint"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoRegion":{"abstract":[],"title":"MPGeoRegion","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPGeoRegion"}],"url":"\/documentation\/mapsindoors\/mpgeoregion","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPGeoRegion"}]},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoRegion/encode(to:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s7EncoderP","kind":"typeIdentifier","text":"Encoder"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/encode(to:)","title":"encode(to:)","role":"symbol","url":"\/documentation\/mapsindoors\/mpgeoregion\/encode(to:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoRegion/intersectsWith(other:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intersectsWith"},{"kind":"text","text":"("},{"text":"other","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MPGeometryProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/intersectsWith(other:)","abstract":[],"title":"intersectsWith(other:)","navigatorTitle":[{"kind":"identifier","text":"intersectsWithOther:"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpgeoregion\/intersectswith(other:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoRegion/init(nearLeft:farLeft:farRight:nearRight:)":{"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"nearLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"farLeft"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"farRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"nearRight"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/init(nearLeft:farLeft:farRight:nearRight:)","navigatorTitle":[{"kind":"identifier","text":"initWithNearLeft:farLeft:farRight:nearRight:"}],"url":"\/documentation\/mapsindoors\/mpgeoregion\/init(nearleft:farleft:farright:nearright:)","kind":"symbol","title":"init(nearLeft:farLeft:farRight:nearRight:)","abstract":[]},"doc://com.mapspeople.mapsindoors/Se":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se","title":"Swift.Decodable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryProtocol":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MPGeometryProtocol","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPGeometryProtocol","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mapsindoors\/mpgeometryprotocol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol","title":"MPGeometryProtocol"},"doc://com.mapspeople.mapsindoors/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","title":"Swift.Equatable"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoRegion/area":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"area","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/area","abstract":[],"title":"area","navigatorTitle":[{"text":"area","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpgeoregion\/area","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoRegion/farLeft":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"farLeft","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/farLeft","title":"farLeft","navigatorTitle":[{"kind":"identifier","text":"farLeft"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpgeoregion\/farleft","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoRegion/farRight":{"role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"farRight","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/farRight","navigatorTitle":[{"text":"farRight","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpgeoregion\/farright","kind":"symbol","title":"farRight","abstract":[]},"doc://com.mapspeople.mapsindoors/SE":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE","title":"Swift.Encodable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoRegion/polygon":{"navigatorTitle":[{"text":"polygon","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygon","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPGeoPolygon","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon"}],"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/mapsindoors\/mpgeoregion\/polygon","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/polygon","title":"polygon"},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoRegion/bounds":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bounds","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","kind":"typeIdentifier","text":"MPGeoBounds"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/bounds","title":"bounds","navigatorTitle":[{"text":"bounds","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpgeoregion\/bounds","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"MPGeoRegion","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPGeoRegion"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPGeoRegion"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/area","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/bounds","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/center","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/farLeft","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/farRight","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/nearLeft","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/nearRight","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/polygon"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/distanceTo(other:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/init(nearLeft:farLeft:farRight:nearRight:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion\/intersectsWith(other:)"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"MPGeoRegion","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"nearRight","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1nearRight\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1nearRight\/fragments","value":[{"kind":"identifier","text":"nearRight"}],"op":"replace"},{"value":"distanceToOther:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1distanceTo(other:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"distanceToOther:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1distanceTo(other:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1nearLeft\/title","op":"replace","value":"nearLeft"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1nearLeft\/fragments","value":[{"kind":"identifier","text":"nearLeft"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1center\/title","value":"center"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1center\/fragments","op":"replace","value":[{"text":"center","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion\/title","value":"MPGeoRegion","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion\/fragments","op":"replace","value":[{"text":"MPGeoRegion","kind":"identifier"}]},{"value":"intersectsWithOther:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1intersectsWith(other:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"intersectsWithOther:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1intersectsWith(other:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1init(nearLeft:farLeft:farRight:nearRight:)\/title","value":"initWithNearLeft:farLeft:farRight:nearRight:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithNearLeft:farLeft:farRight:nearRight:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1init(nearLeft:farLeft:farRight:nearRight:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol\/title","value":"MPGeometryProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol\/fragments","value":[{"kind":"identifier","text":"MPGeometryProtocol"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1area\/title","op":"replace","value":"area"},{"value":[{"kind":"identifier","text":"area"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1area\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1farLeft\/title","value":"farLeft"},{"value":[{"kind":"identifier","text":"farLeft"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1farLeft\/fragments","op":"replace"},{"op":"replace","value":"farRight","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1farRight\/title"},{"value":[{"text":"farRight","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1farRight\/fragments"},{"value":"polygon","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1polygon\/title"},{"value":[{"kind":"identifier","text":"polygon"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1polygon\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1bounds\/title","value":"bounds"},{"value":[{"kind":"identifier","text":"bounds"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion~1bounds\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}