{"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/area"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsCoordinate(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsCoordinate(_:ignorePolygonHoles:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsLineSegmentFromCoordinate(_:toCoordinate:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsPoint(_:)"],"title":"Instance Methods"}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpgeometryqueryprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpgeometryqueryprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"metadata":{"symbolKind":"protocol","title":"MPGeometryQueryProtocol","navigatorTitle":[{"text":"MPGeometryQueryProtocol","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPGeometryQueryProtocol"}],"role":"symbol","roleHeading":"Protocol","externalID":"c:@M@MapsIndoors@objc(pl)MPGeometryQueryProtocol"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"],"kind":"relationships"},{"kind":"relationships","type":"conformingTypes","title":"Conforming Types","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPGeometryQueryProtocol"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"type":"aside","name":"Warning","style":"warning","content":[{"inlineContent":[{"text":"[INTERNAL - DO NOT USE]","type":"text"}],"type":"paragraph"}]}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryQueryProtocol/containsCoordinate(_:ignorePolygonHoles:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsCoordinate(_:ignorePolygonHoles:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"containsCoordinate","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":", "},{"text":"ignorePolygonHoles","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"containsCoordinate(_:ignorePolygonHoles:)","navigatorTitle":[{"text":"containsCoordinate:ignorePolygonHoles:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/containscoordinate(_:ignorepolygonholes:)","type":"topic","abstract":[{"type":"text","text":"Check if the given coordinate is contained within the polygon."}],"required":true,"kind":"symbol","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMultiPolygonGeometry":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry","navigatorTitle":[{"text":"MPMultiPolygonGeometry","kind":"identifier"}],"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMultiPolygonGeometry"}],"url":"\/documentation\/mapsindoors\/mpmultipolygongeometry","type":"topic","title":"MPMultiPolygonGeometry","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryQueryProtocol":{"navigatorTitle":[{"text":"MPGeometryQueryProtocol","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol","kind":"symbol","role":"symbol","title":"MPGeometryQueryProtocol","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPGeometryQueryProtocol","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryQueryProtocol/containsLineSegmentFromCoordinate(_:toCoordinate:)":{"title":"containsLineSegmentFromCoordinate(_:toCoordinate:)","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsLineSegmentFromCoordinate(_:toCoordinate:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"containsLineSegmentFromCoordinate:toCoordinate:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"containsLineSegmentFromCoordinate"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"toCoordinate"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/containslinesegmentfromcoordinate(_:tocoordinate:)","abstract":[{"type":"text","text":"Check if the given line segment is fully contained within the polygon."}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPolygonGeometry":{"navigatorTitle":[{"text":"MPPolygonGeometry","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry","url":"\/documentation\/mapsindoors\/mppolygongeometry","type":"topic","role":"symbol","kind":"symbol","title":"MPPolygonGeometry","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPPolygonGeometry","kind":"identifier"}],"abstract":[]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryQueryProtocol/containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)":{"required":true,"abstract":[{"type":"text","text":"Check if the given coordinate is contained within the polygon, and optionally return the coordinate closest to the polygon."},{"text":" ","type":"text"},{"type":"text","text":"If the polygon contains the coordinate, ‘coordinate’ is returned as nearestPoint."},{"type":"text","text":" "},{"text":"If coordinate is not contained, the nearest point is calculated.","type":"text"}],"navigatorTitle":[{"text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:","kind":"identifier"}],"title":"containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"containsCoordinate"},{"kind":"text","text":"("},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ignorePolygonHoles"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"containmentMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometryContainmentMetadata","text":"MPGeometryContainmentMetadata","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/containscoordinate(_:ignorepolygonholes:containmentmetadata:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryQueryProtocol/containsPoint(_:)":{"required":true,"navigatorTitle":[{"text":"containsPoint:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/containspoint(_:)","kind":"symbol","role":"symbol","title":"containsPoint(_:)","type":"topic","abstract":[{"text":"Check if the given point is contained within the polygon.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsPoint(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"containsPoint","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","text":"MPPoint","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryQueryProtocol/area":{"title":"area","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/area","kind":"symbol","required":true,"navigatorTitle":[{"text":"area","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"area","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/area","abstract":[{"type":"text","text":"The area of the polygon computed as the area of the outer path with the area of all holes subtracted."}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","title":"NSObject"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryQueryProtocol/containsCoordinate(_:)":{"type":"topic","role":"symbol","url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol\/containscoordinate(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"containsCoordinate","kind":"identifier"},{"kind":"text","text":"("},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsCoordinate(_:)","abstract":[{"text":"Check if the given coordinate is contained within the polygon.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"containsCoordinate:"}],"title":"containsCoordinate(_:)","required":true},"MapsPeopleWhite.png":{"type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","alt":null}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPGeometryQueryProtocol"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPGeometryQueryProtocol"}]},{"op":"replace","value":[{"kind":"identifier","text":"MPGeometryQueryProtocol"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/area"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsCoordinate(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsCoordinate(_:ignorePolygonHoles:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsLineSegmentFromCoordinate(_:toCoordinate:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol\/containsPoint(_:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformingTypes","kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPolygonGeometry"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"MPGeometryQueryProtocol","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1containsCoordinate(_:ignorePolygonHoles:)\/title","op":"replace","value":"containsCoordinate:ignorePolygonHoles:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1containsCoordinate(_:ignorePolygonHoles:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"containsCoordinate:ignorePolygonHoles:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry\/title","value":"MPMultiPolygonGeometry"},{"op":"replace","value":[{"kind":"identifier","text":"MPMultiPolygonGeometry"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry\/fragments"},{"value":"MPGeometryQueryProtocol","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MPGeometryQueryProtocol"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol\/fragments"},{"value":"containsLineSegmentFromCoordinate:toCoordinate:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1containsLineSegmentFromCoordinate(_:toCoordinate:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1containsLineSegmentFromCoordinate(_:toCoordinate:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"containsLineSegmentFromCoordinate:toCoordinate:","kind":"identifier"}],"op":"replace"},{"value":"MPPolygonGeometry","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPolygonGeometry\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPolygonGeometry\/fragments","value":[{"kind":"identifier","text":"MPPolygonGeometry"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)\/title","op":"replace","value":"containsCoordinate:ignorePolygonHoles:containmentMetadata:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:"}]},{"value":"containsPoint:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1containsPoint(_:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsPoint:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1containsPoint(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1area\/title","value":"area","op":"replace"},{"value":[{"kind":"identifier","text":"area"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1area\/fragments"},{"value":"containsCoordinate:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1containsCoordinate(_:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol~1containsCoordinate(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"containsCoordinate:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}