{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpgeometryprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpgeometryprotocol"]}],"metadata":{"title":"MPGeometryProtocol","externalID":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol","navigatorTitle":[{"text":"MPGeometryProtocol","kind":"identifier"}],"roleHeading":"Protocol","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPGeometryProtocol","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol"},"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/bounds","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/center","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/polygon"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/distanceTo(other:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/intersectsWith(other:)"],"title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPGeometryProtocol","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"relationshipsSections":[{"title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPExtendableGeometry"],"kind":"relationships"},{"title":"Conforming Types","type":"conformingTypes","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPoint","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolyline","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion"],"kind":"relationships"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoRegion":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mpgeoregion","navigatorTitle":[{"text":"MPGeoRegion","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPGeoRegion","kind":"identifier"}],"type":"topic","title":"MPGeoRegion","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryProtocol":{"url":"\/documentation\/mapsindoors\/mpgeometryprotocol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPGeometryProtocol","kind":"identifier"}],"title":"MPGeometryProtocol","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPGeometryProtocol"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryProtocol/polygon":{"title":"polygon","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"polygon"}],"type":"topic","abstract":[],"url":"\/documentation\/mapsindoors\/mpgeometryprotocol\/polygon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"polygon","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPGeoPolygon","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/polygon","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPolyline":{"title":"MPGeoPolyline","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolyline","kind":"symbol","url":"\/documentation\/mapsindoors\/mpgeopolyline","navigatorTitle":[{"text":"MPGeoPolyline","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeoPolyline"}],"role":"symbol","abstract":[]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPExtendableGeometry":{"title":"MPExtendableGeometry","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPExtendableGeometry"}],"navigatorTitle":[{"text":"MPExtendableGeometry","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPExtendableGeometry","type":"topic","abstract":[],"url":"\/documentation\/mapsindoors\/mpextendablegeometry"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoBounds":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds","url":"\/documentation\/mapsindoors\/mpgeobounds","navigatorTitle":[{"kind":"identifier","text":"MPGeoBounds"}],"abstract":[],"title":"MPGeoBounds","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeoBounds"}],"type":"topic"},"MapsPeopleWhite.png":{"type":"image","alt":null,"identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryProtocol/distanceTo(other:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/distanceTo(other:)","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"distanceTo","kind":"identifier"},{"kind":"text","text":"("},{"text":"other","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol","text":"MPGeometryProtocol"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"url":"\/documentation\/mapsindoors\/mpgeometryprotocol\/distanceto(other:)","title":"distanceTo(other:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"distanceToOther:"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPoint":{"navigatorTitle":[{"text":"MPGeoPoint","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPGeoPoint"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPoint","url":"\/documentation\/mapsindoors\/mpgeopoint","title":"MPGeoPoint","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryProtocol/bounds":{"title":"bounds","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"bounds"}],"type":"topic","abstract":[],"url":"\/documentation\/mapsindoors\/mpgeometryprotocol\/bounds","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bounds","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","text":"MPGeoBounds"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/bounds","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryProtocol/intersectsWith(other:)":{"role":"symbol","abstract":[],"kind":"symbol","required":true,"url":"\/documentation\/mapsindoors\/mpgeometryprotocol\/intersectswith(other:)","navigatorTitle":[{"text":"intersectsWithOther:","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/intersectsWith(other:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intersectsWith"},{"kind":"text","text":"("},{"text":"other","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPGeometryProtocol","text":"MPGeometryProtocol","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"intersectsWith(other:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeoPolygon":{"abstract":[],"url":"\/documentation\/mapsindoors\/mpgeopolygon","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPolygon","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPGeoPolygon","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPGeoPolygon"}],"title":"MPGeoPolygon"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryProtocol/center":{"title":"center","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"center"}],"type":"topic","abstract":[],"url":"\/documentation\/mapsindoors\/mpgeometryprotocol\/center","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"center","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPGeoPoint","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPoint","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/center","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"value":"MPGeometryProtocol","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPGeometryProtocol"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MPGeometryProtocol"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/bounds","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/center","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/polygon"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/distanceTo(other:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryProtocol\/intersectsWith(other:)"]}]},{"value":[{"title":"Conforming Types","type":"conformingTypes","kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoBounds","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoPoint","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeoRegion"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPGeometryProtocol","kind":"identifier"}]}]},"op":"replace"},{"op":"replace","value":"MPGeoRegion","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion\/title"},{"value":[{"kind":"identifier","text":"MPGeoRegion"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoRegion\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol\/title","value":"MPGeometryProtocol"},{"value":[{"kind":"identifier","text":"MPGeometryProtocol"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol~1polygon\/title","value":"polygon"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol~1polygon\/fragments","value":[{"text":"polygon","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolyline\/title","value":"MPGeoPolyline","op":"replace"},{"value":[{"text":"MPGeoPolyline","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolyline\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoBounds\/title","value":"MPGeoBounds"},{"value":[{"kind":"identifier","text":"MPGeoBounds"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoBounds\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol~1distanceTo(other:)\/title","value":"distanceToOther:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"distanceToOther:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol~1distanceTo(other:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPoint\/title","op":"replace","value":"MPGeoPoint"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPoint\/fragments","op":"replace","value":[{"text":"MPGeoPoint","kind":"identifier"}]},{"op":"replace","value":"bounds","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol~1bounds\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol~1bounds\/fragments","value":[{"kind":"identifier","text":"bounds"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol~1intersectsWith(other:)\/title","value":"intersectsWithOther:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol~1intersectsWith(other:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"intersectsWithOther:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon\/title","value":"MPGeoPolygon","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeoPolygon\/fragments","value":[{"text":"MPGeoPolygon","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol~1center\/title","value":"center"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryProtocol~1center\/fragments","value":[{"text":"center","kind":"identifier"}]}]}]}