{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPGeometryUtils","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"type":"aside","style":"warning","content":[{"type":"paragraph","inlineContent":[{"text":"[INTERNAL - DO NOT USE]","type":"text"}]}],"name":"Warning"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpgeometryutils"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpgeometryutils"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils"},"metadata":{"navigatorTitle":[{"text":"MPGeometryUtils","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeometryUtils"}],"modules":[{"name":"MapsIndoors"}],"title":"MPGeometryUtils","symbolKind":"class","externalID":"c:@M@MapsIndoors@objc(cs)MPGeometryUtils","roleHeading":"Class","role":"symbol"},"sections":[],"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/bearingBetweenPoints(from:to:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/closestPointOnLineSegment(point:lineStart:lineEnd:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/computeBoundingBox(coordinates:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/coordinateInQuadCurve(p0:p1:p2:t:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/distance(from:to:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/distanceLineToLine(a1:a2:b1:b2:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/distancePointToLine(point:lineStart:lineEnd:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/interpolate(from:to:fraction:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/pointIntersectsPolygon(point:polygon:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/polygonIntersectsPolygon(a:b:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/polylineIntersectsPolygon(a:b:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/polylineIntersectsPolyline(a:b:)"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils":{"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils","title":"MPGeometryUtils","navigatorTitle":[{"kind":"identifier","text":"MPGeometryUtils"}],"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/mapsindoors\/mpgeometryutils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPGeometryUtils","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/polygonIntersectsPolygon(a:b:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonIntersectsPolygon"},{"text":"(","kind":"text"},{"text":"a","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MPGeoPolygon","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"b","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPGeoPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/polygonIntersectsPolygon(a:b:)","url":"\/documentation\/mapsindoors\/mpgeometryutils\/polygonintersectspolygon(a:b:)","abstract":[],"type":"topic","title":"polygonIntersectsPolygon(a:b:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/pointIntersectsPolygon(point:polygon:)":{"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/pointIntersectsPolygon(point:polygon:)","title":"pointIntersectsPolygon(point:polygon:)","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/mapsindoors\/mpgeometryutils\/pointintersectspolygon(point:polygon:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pointIntersectsPolygon"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"point"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPoint","text":"MPGeoPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"polygon"},{"kind":"text","text":": "},{"text":"MPGeoPolygon","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/init":{"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/init","url":"\/documentation\/mapsindoors\/mpgeometryutils\/init","abstract":[],"type":"topic","title":"init","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/polylineIntersectsPolyline(a:b:)":{"url":"\/documentation\/mapsindoors\/mpgeometryutils\/polylineintersectspolyline(a:b:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/polylineIntersectsPolyline(a:b:)","role":"symbol","abstract":[],"type":"topic","title":"polylineIntersectsPolyline(a:b:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"polylineIntersectsPolyline"},{"text":"(","kind":"text"},{"text":"a","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolyline","text":"MPGeoPolyline"},{"text":", ","kind":"text"},{"text":"b","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolyline","text":"MPGeoPolyline","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/computeBoundingBox(coordinates:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"computeBoundingBox","kind":"identifier"},{"text":"(","kind":"text"},{"text":"coordinates","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","kind":"typeIdentifier","text":"MPGeoBounds"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/computeBoundingBox(coordinates:)","url":"\/documentation\/mapsindoors\/mpgeometryutils\/computeboundingbox(coordinates:)","abstract":[],"type":"topic","title":"computeBoundingBox(coordinates:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/distance(from:to:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"distance","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPGeoPoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPoint"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPGeoPoint","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPoint"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"distanceFrom:to:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/distance(from:to:)","url":"\/documentation\/mapsindoors\/mpgeometryutils\/distance(from:to:)","type":"topic","abstract":[],"title":"distance(from:to:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/interpolate(from:to:fraction:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"interpolate"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"fraction","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"}],"navigatorTitle":[{"text":"interpolateFrom:to:fraction:","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/interpolate(from:to:fraction:)","url":"\/documentation\/mapsindoors\/mpgeometryutils\/interpolate(from:to:fraction:)","type":"topic","abstract":[],"title":"interpolate(from:to:fraction:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/polylineIntersectsPolygon(a:b:)":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"polylineIntersectsPolygon"},{"text":"(","kind":"text"},{"text":"a","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MPGeoPolyline","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolyline","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"b","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPGeoPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoPolygon"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/polylineIntersectsPolygon(a:b:)","url":"\/documentation\/mapsindoors\/mpgeometryutils\/polylineintersectspolygon(a:b:)","abstract":[],"type":"topic","title":"polylineIntersectsPolygon(a:b:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/bearingBetweenPoints(from:to:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bearingBetweenPoints","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"bearingBetweenPointsFrom:to:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/bearingBetweenPoints(from:to:)","url":"\/documentation\/mapsindoors\/mpgeometryutils\/bearingbetweenpoints(from:to:)","type":"topic","abstract":[],"title":"bearingBetweenPoints(from:to:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/coordinateInQuadCurve(p0:p1:p2:t:)":{"url":"\/documentation\/mapsindoors\/mpgeometryutils\/coordinateinquadcurve(p0:p1:p2:t:)","type":"topic","title":"coordinateInQuadCurve(p0:p1:p2:t:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"coordinateInQuadCurve"},{"text":"(","kind":"text"},{"text":"p0","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"p1","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"p2","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"t","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"role":"symbol","abstract":[{"text":"Calculates a coordinate in a Quadratic Bézier Curve","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/coordinateInQuadCurve(p0:p1:p2:t:)"},"doc://com.mapspeople.mapsindoors/SQ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/distancePointToLine(point:lineStart:lineEnd:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"distancePointToLine"},{"kind":"text","text":"("},{"text":"point","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"lineStart","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"lineEnd","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/distancePointToLine(point:lineStart:lineEnd:)","url":"\/documentation\/mapsindoors\/mpgeometryutils\/distancepointtoline(point:linestart:lineend:)","type":"topic","abstract":[],"title":"distancePointToLine(point:lineStart:lineEnd:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/distanceLineToLine(a1:a2:b1:b2:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"distanceLineToLine","kind":"identifier"},{"text":"(","kind":"text"},{"text":"a1","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"a2"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"b1"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"b2"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/distanceLineToLine(a1:a2:b1:b2:)","url":"\/documentation\/mapsindoors\/mpgeometryutils\/distancelinetoline(a1:a2:b1:b2:)","abstract":[],"type":"topic","title":"distanceLineToLine(a1:a2:b1:b2:)","role":"symbol"},"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryUtils/closestPointOnLineSegment(point:lineStart:lineEnd:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"closestPointOnLineSegment"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"point"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"text":"lineStart","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"lineEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"navigatorTitle":[{"kind":"identifier","text":"closestPointOnLineSegmentWithPoint:lineStart:lineEnd:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/closestPointOnLineSegment(point:lineStart:lineEnd:)","url":"\/documentation\/mapsindoors\/mpgeometryutils\/closestpointonlinesegment(point:linestart:lineend:)","abstract":[],"type":"topic","title":"closestPointOnLineSegment(point:lineStart:lineEnd:)","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MPGeometryUtils"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MPGeometryUtils","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPGeometryUtils"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/init"]},{"title":"Type Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/bearingBetweenPoints(from:to:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/closestPointOnLineSegment(point:lineStart:lineEnd:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/distance(from:to:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryUtils\/interpolate(from:to:fraction:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeometryUtils"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils\/title","value":"MPGeometryUtils"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils\/fragments","value":[{"text":"MPGeometryUtils","kind":"identifier"}],"op":"replace"},{"value":"distanceFrom:to:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils~1distance(from:to:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"distanceFrom:to:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils~1distance(from:to:)\/fragments"},{"value":"interpolateFrom:to:fraction:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils~1interpolate(from:to:fraction:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils~1interpolate(from:to:fraction:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"interpolateFrom:to:fraction:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils~1bearingBetweenPoints(from:to:)\/title","value":"bearingBetweenPointsFrom:to:"},{"value":[{"text":"+ ","kind":"text"},{"text":"bearingBetweenPointsFrom:to:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils~1bearingBetweenPoints(from:to:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils~1closestPointOnLineSegment(point:lineStart:lineEnd:)\/title","value":"closestPointOnLineSegmentWithPoint:lineStart:lineEnd:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"closestPointOnLineSegmentWithPoint:lineStart:lineEnd:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryUtils~1closestPointOnLineSegment(point:lineStart:lineEnd:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}