{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPHighwayType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mphighwaytype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mphighwaytype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH","doc:\/\/MapsIndoors\/SY","doc:\/\/MapsIndoors\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An enumeration of all accepted types of highways."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPHighwayType"}],"title":"MPHighwayType","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:MPDefines.h@T@MPHighwayType","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPHighwayType"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/init(rawValue:)"]},{"title":"Type Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/elevator","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/escalator","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/footway","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/ladder","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/ramp","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/residential","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/service","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/stairs","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/travelator","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/unclassified","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/wheelChairLift","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/wheelChairRamp"]},{"title":"Default Implementations","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/Equatable-Implementations","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/RawRepresentable-Implementations","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/_SwiftNewtypeWrapper-Implementations"],"generated":true}],"references":{"doc://MapsIndoors/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/MapsIndoors\/SY"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType/service":{"role":"symbol","title":"service","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"service"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/service","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeService"}],"url":"\/documentation\/mapsindoors\/mphighwaytype\/service"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType/escalator":{"role":"symbol","title":"escalator","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"escalator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/escalator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeEscalator"}],"url":"\/documentation\/mapsindoors\/mphighwaytype\/escalator"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType/footway":{"role":"symbol","title":"footway","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"footway"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/footway","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeFootway"}],"url":"\/documentation\/mapsindoors\/mphighwaytype\/footway"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mphighwaytype\/init(rawvalue:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType/ladder":{"role":"symbol","title":"ladder","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ladder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/ladder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeLadder"}],"url":"\/documentation\/mapsindoors\/mphighwaytype\/ladder"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType/travelator":{"role":"symbol","title":"travelator","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"travelator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/travelator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeTravelator"}],"url":"\/documentation\/mapsindoors\/mphighwaytype\/travelator"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType/wheelChairRamp":{"role":"symbol","title":"wheelChairRamp","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"wheelChairRamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/wheelChairRamp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeWheelChairRamp"}],"url":"\/documentation\/mapsindoors\/mphighwaytype\/wheelchairramp"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType/residential":{"role":"symbol","title":"residential","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"residential"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/residential","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeResidential"}],"url":"\/documentation\/mapsindoors\/mphighwaytype\/residential"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType/wheelChairLift":{"role":"symbol","title":"wheelChairLift","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"wheelChairLift"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/wheelChairLift","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeWheelChairLift"}],"url":"\/documentation\/mapsindoors\/mphighwaytype\/wheelchairlift"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType/elevator":{"role":"symbol","title":"elevator","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"elevator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/elevator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeElevator"}],"url":"\/documentation\/mapsindoors\/mphighwaytype\/elevator"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType/unclassified":{"role":"symbol","title":"unclassified","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"unclassified"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/unclassified","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeUnclassified"}],"url":"\/documentation\/mapsindoors\/mphighwaytype\/unclassified"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType/ramp":{"role":"symbol","title":"ramp","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ramp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/ramp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeRamp"}],"url":"\/documentation\/mapsindoors\/mphighwaytype\/ramp"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mphighwaytype\/rawrepresentable-implementations"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType/stairs":{"role":"symbol","title":"stairs","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"stairs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/stairs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeStairs"}],"url":"\/documentation\/mapsindoors\/mphighwaytype\/stairs"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType/_SwiftNewtypeWrapper-Implementations":{"role":"collectionGroup","title":"_SwiftNewtypeWrapper Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/_SwiftNewtypeWrapper-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mphighwaytype\/_swiftnewtypewrapper-implementations"},"doc://MapsIndoors/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/MapsIndoors\/s8SendableP"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType":{"role":"symbol","title":"MPHighwayType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPHighwayType"}],"abstract":[{"type":"text","text":"An enumeration of all accepted types of highways."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPHighwayType"}],"url":"\/documentation\/mapsindoors\/mphighwaytype"},"doc://MapsIndoors/documentation/MapsIndoors/MPHighwayType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mphighwaytype\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"MPHighwayType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPHighwayType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPHighwayType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/elevator","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/escalator","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/footway","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/ladder","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/ramp","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/residential","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/service","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/stairs","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/travelator","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/unclassified","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/wheelChairLift","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPHighwayType\/wheelChairRamp"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"MPHighwayType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1service\/title","value":"MPHighwayTypeService"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1service\/fragments","value":[{"kind":"identifier","text":"MPHighwayTypeService"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1escalator\/title","value":"MPHighwayTypeEscalator"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1escalator\/fragments","value":[{"kind":"identifier","text":"MPHighwayTypeEscalator"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1footway\/title","value":"MPHighwayTypeFootway"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1footway\/fragments","value":[{"kind":"identifier","text":"MPHighwayTypeFootway"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1ladder\/title","value":"MPHighwayTypeLadder"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1ladder\/fragments","value":[{"kind":"identifier","text":"MPHighwayTypeLadder"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1travelator\/title","value":"MPHighwayTypeTravelator"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1travelator\/fragments","value":[{"kind":"identifier","text":"MPHighwayTypeTravelator"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1wheelChairRamp\/title","value":"MPHighwayTypeWheelChairRamp"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1wheelChairRamp\/fragments","value":[{"kind":"identifier","text":"MPHighwayTypeWheelChairRamp"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1residential\/title","value":"MPHighwayTypeResidential"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1residential\/fragments","value":[{"kind":"identifier","text":"MPHighwayTypeResidential"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1wheelChairLift\/title","value":"MPHighwayTypeWheelChairLift"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1wheelChairLift\/fragments","value":[{"kind":"identifier","text":"MPHighwayTypeWheelChairLift"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1elevator\/title","value":"MPHighwayTypeElevator"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1elevator\/fragments","value":[{"kind":"identifier","text":"MPHighwayTypeElevator"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1unclassified\/title","value":"MPHighwayTypeUnclassified"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1unclassified\/fragments","value":[{"kind":"identifier","text":"MPHighwayTypeUnclassified"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1ramp\/title","value":"MPHighwayTypeRamp"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1ramp\/fragments","value":[{"kind":"identifier","text":"MPHighwayTypeRamp"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1stairs\/title","value":"MPHighwayTypeStairs"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType~1stairs\/fragments","value":[{"kind":"identifier","text":"MPHighwayTypeStairs"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType\/title","value":"MPHighwayType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPHighwayType\/fragments","value":[{"kind":"identifier","text":"MPHighwayType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}