{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPHighway","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mphighway"]},{"paths":["\/documentation\/mapsindoors\/mphighway"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Use instances of "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","isActive":true},{"type":"text","text":" to describe which type(s) of route elements to use."}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/init(from:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/init(typeString:)"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/type","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/typeString"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/encode(to:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/elevator","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/escalator","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/footway","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/ladder","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/ramp","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/residential","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/service","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/stairs","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/travelator","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/unclassified","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/wheelchairlift","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/wheelchairramp"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/highwaysAsStrings(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/stringsAsHighways(_:)"],"title":"Type Methods"},{"title":"Enumerations","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/CodingKeys"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"metadata":{"modules":[{"name":"MapsIndoors"}],"symbolKind":"class","roleHeading":"Class","title":"MPHighway","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPHighway"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPHighway","role":"symbol","navigatorTitle":[{"text":"MPHighway","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"references":{"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/CodingKeys":{"title":"MPHighway.CodingKeys","role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mphighway\/codingkeys","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/CodingKeys","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CodingKeys","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CodingKeys"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/travelator":{"type":"topic","abstract":[],"title":"travelator","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"travelator"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","kind":"typeIdentifier","text":"MPHighway"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/travelator","url":"\/documentation\/mapsindoors\/mphighway\/travelator","role":"symbol","navigatorTitle":[{"text":"travelator","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/stairs":{"abstract":[],"type":"topic","title":"stairs","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stairs"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","kind":"typeIdentifier","text":"MPHighway"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/stairs","url":"\/documentation\/mapsindoors\/mphighway\/stairs","role":"symbol","navigatorTitle":[{"text":"stairs","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/ramp":{"type":"topic","abstract":[],"title":"ramp","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ramp"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","kind":"typeIdentifier","text":"MPHighway"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/ramp","url":"\/documentation\/mapsindoors\/mphighway\/ramp","role":"symbol","navigatorTitle":[{"text":"ramp","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/service":{"title":"service","role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mphighway\/service","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/service","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"service","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","text":"MPHighway"}],"navigatorTitle":[{"kind":"identifier","text":"service"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/wheelchairramp":{"abstract":[],"type":"topic","title":"wheelchairramp","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"wheelchairramp"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","kind":"typeIdentifier","text":"MPHighway"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/wheelchairramp","url":"\/documentation\/mapsindoors\/mphighway\/wheelchairramp","role":"symbol","navigatorTitle":[{"text":"wheelchairramp","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapspeople.mapsindoors/SE":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/type":{"abstract":[{"text":"The actual type of the route element.","type":"text"}],"type":"topic","title":"type","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"text":"MPHighwayType","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPHighwayType"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/type","url":"\/documentation\/mapsindoors\/mphighway\/type","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"type"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/typeString":{"type":"topic","abstract":[{"type":"text","text":"A textual description of the route element type."}],"title":"typeString","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeString"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/typeString","url":"\/documentation\/mapsindoors\/mphighway\/typestring","role":"symbol","navigatorTitle":[{"text":"typeString","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/ladder":{"abstract":[],"type":"topic","title":"ladder","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ladder"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","kind":"typeIdentifier","text":"MPHighway"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/ladder","url":"\/documentation\/mapsindoors\/mphighway\/ladder","role":"symbol","navigatorTitle":[{"text":"ladder","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/stringsAsHighways(_:)":{"role":"symbol","abstract":[{"type":"text","text":"Transform array of Strings to array of "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","isActive":true}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mphighway\/stringsashighways(_:)","navigatorTitle":[{"text":"stringsAsHighways:","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/stringsAsHighways(_:)","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stringsAsHighways"},{"kind":"text","text":"(["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]) -> ["},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","text":"MPHighway","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"stringsAsHighways(_:)"},"doc://com.mapspeople.mapsindoors/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighwayType/unclassified":{"abstract":[],"type":"topic","title":"MPHighwayType.unclassified","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unclassified","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighwayType\/unclassified","url":"\/documentation\/mapsindoors\/mphighwaytype\/unclassified","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPHighwayTypeUnclassified"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/highwaysAsStrings(_:)":{"type":"topic","abstract":[{"text":"Transform array of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway"},{"type":"text","text":" to array of Strings"}],"title":"highwaysAsStrings(_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"highwaysAsStrings","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","text":"MPHighway"},{"text":"]) -> [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/highwaysAsStrings(_:)","url":"\/documentation\/mapsindoors\/mphighway\/highwaysasstrings(_:)","role":"symbol","navigatorTitle":[{"text":"highwaysAsStrings:","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/init(from:)":{"abstract":[],"type":"topic","title":"init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/init(from:)","url":"\/documentation\/mapsindoors\/mphighway\/init(from:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/residential":{"type":"topic","abstract":[],"title":"residential","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"residential"},{"text":": ","kind":"text"},{"text":"MPHighway","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/residential","url":"\/documentation\/mapsindoors\/mphighway\/residential","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"residential"}]},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/encode(to:)":{"type":"topic","abstract":[],"title":"encode(to:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"encode","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Encoder","kind":"typeIdentifier","preciseIdentifier":"s:s7EncoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/encode(to:)","url":"\/documentation\/mapsindoors\/mphighway\/encode(to:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/unclassified":{"abstract":[{"type":"text","text":"Convenience values."}],"type":"topic","title":"unclassified","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unclassified"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","kind":"typeIdentifier","text":"MPHighway"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/unclassified","url":"\/documentation\/mapsindoors\/mphighway\/unclassified","role":"symbol","navigatorTitle":[{"text":"unclassified","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/Se":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se","title":"Swift.Decodable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/elevator":{"abstract":[],"type":"topic","title":"elevator","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"elevator","kind":"identifier"},{"kind":"text","text":": "},{"text":"MPHighway","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/elevator","url":"\/documentation\/mapsindoors\/mphighway\/elevator","role":"symbol","navigatorTitle":[{"text":"elevator","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/footway":{"type":"topic","abstract":[],"title":"footway","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"footway"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","kind":"typeIdentifier","text":"MPHighway"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/footway","url":"\/documentation\/mapsindoors\/mphighway\/footway","role":"symbol","navigatorTitle":[{"text":"footway","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/escalator":{"abstract":[],"type":"topic","title":"escalator","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"escalator","kind":"identifier"},{"kind":"text","text":": "},{"text":"MPHighway","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/escalator","url":"\/documentation\/mapsindoors\/mphighway\/escalator","role":"symbol","navigatorTitle":[{"text":"escalator","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/wheelchairlift":{"type":"topic","abstract":[],"title":"wheelchairlift","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wheelchairlift"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway","kind":"typeIdentifier","text":"MPHighway"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/wheelchairlift","url":"\/documentation\/mapsindoors\/mphighway\/wheelchairlift","role":"symbol","navigatorTitle":[{"text":"wheelchairlift","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway/init(typeString:)":{"abstract":[{"type":"text","text":"Initialise with the name of a specific route element type. If the name is unknown the type will be "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighwayType\/unclassified"},{"type":"text","text":"."}],"type":"topic","title":"init(typeString:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"typeString"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/init(typeString:)","url":"\/documentation\/mapsindoors\/mphighway\/init(typestring:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithTypeString:"}]},"doc://com.mapspeople.mapsindoors/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/SH":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable","type":"unresolvable"},"MapsPeopleWhite.png":{"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null,"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHighway":{"title":"MPHighway","role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mphighway","abstract":[{"text":"Use instances of ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","isActive":true},{"type":"text","text":" to describe which type(s) of route elements to use."}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPHighway"}],"navigatorTitle":[{"kind":"identifier","text":"MPHighway"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MPHighway"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MPHighway","kind":"identifier"}]},{"value":[{"text":"MPHighway","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/type","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/typeString"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/init(typeString:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/elevator","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/escalator","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/footway","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/ladder","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/ramp","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/residential","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/service","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/stairs","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/travelator","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/unclassified","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/wheelchairlift","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/wheelchairramp"]},{"title":"Type Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/highwaysAsStrings(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHighway\/stringsAsHighways(_:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPHighway"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"travelator","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1travelator\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1travelator\/fragments","op":"replace","value":[{"text":"travelator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1stairs\/title","value":"stairs"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1stairs\/fragments","op":"replace","value":[{"text":"stairs","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1ramp\/title","value":"ramp","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1ramp\/fragments","value":[{"text":"ramp","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1service\/title","value":"service","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1service\/fragments","value":[{"text":"service","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1wheelchairramp\/title","op":"replace","value":"wheelchairramp"},{"value":[{"text":"wheelchairramp","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1wheelchairramp\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"value":"typeString","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1typeString\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1typeString\/fragments","value":[{"kind":"identifier","text":"typeString"}]},{"op":"replace","value":"ladder","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1ladder\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1ladder\/fragments","value":[{"text":"ladder","kind":"identifier"}]},{"value":"stringsAsHighways:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1stringsAsHighways(_:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"stringsAsHighways:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1stringsAsHighways(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighwayType~1unclassified\/title","op":"replace","value":"MPHighwayTypeUnclassified"},{"op":"replace","value":[{"kind":"identifier","text":"MPHighwayTypeUnclassified"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighwayType~1unclassified\/fragments"},{"value":"highwaysAsStrings:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1highwaysAsStrings(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"highwaysAsStrings:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1highwaysAsStrings(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1residential\/title","op":"replace","value":"residential"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1residential\/fragments","value":[{"text":"residential","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"unclassified","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1unclassified\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1unclassified\/fragments","op":"replace","value":[{"text":"unclassified","kind":"identifier"}]},{"op":"replace","value":"elevator","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1elevator\/title"},{"value":[{"kind":"identifier","text":"elevator"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1elevator\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1footway\/title","value":"footway","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1footway\/fragments","value":[{"kind":"identifier","text":"footway"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1escalator\/title","value":"escalator","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1escalator\/fragments","op":"replace","value":[{"kind":"identifier","text":"escalator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1wheelchairlift\/title","value":"wheelchairlift"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1wheelchairlift\/fragments","value":[{"text":"wheelchairlift","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1init(typeString:)\/title","value":"initWithTypeString:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway~1init(typeString:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTypeString:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway\/title","value":"MPHighway","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MPHighway"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHighway\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}