{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidity","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mphumidity"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mphumidity"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPHumidity"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSDimension"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSCoding","doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSCopying","doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSSecureCoding","doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"type":"conformsTo","title":"Conforms To"}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPHumidity","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MapsIndoors@objc(cs)MPHumidity","navigatorTitle":[{"text":"MPHumidity","kind":"identifier"}],"title":"MPHumidity","symbolKind":"class","roleHeading":"Class","modules":[{"name":"MapsIndoors"}]},"references":{"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapspeople.mapsindoors/objc(pl)NSCopying":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSCopying","type":"unresolvable","title":"Foundation.NSCopying"},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.mapspeople.mapsindoors/objc(pl)NSSecureCoding":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSSecureCoding","type":"unresolvable","title":"Foundation.NSSecureCoding"},"doc://com.mapspeople.mapsindoors/SQ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapspeople.mapsindoors/objc(pl)NSCoding":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHumidity/initWithSymbol:converter:":{"url":"\/documentation\/mapsindoors\/mphumidity\/initwithsymbol:converter:","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidity\/initWithSymbol:converter:","kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithSymbol:converter:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSymbol:converter:"}],"type":"topic","title":"initWithSymbol:converter:","abstract":[]},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHumidity":{"url":"\/documentation\/mapsindoors\/mphumidity","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidity","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPHumidity","kind":"identifier"}],"navigatorTitle":[{"text":"MPHumidity","kind":"identifier"}],"title":"MPHumidity","type":"topic","abstract":[]},"doc://com.mapspeople.mapsindoors/objc(cs)NSDimension":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSDimension","title":"NSDimension"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHumidity/initWithCoder:":{"url":"\/documentation\/mapsindoors\/mphumidity\/initwithcoder:","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidity\/initWithCoder:","kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"title":"initWithCoder:","type":"topic","abstract":[]},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapspeople.mapsindoors/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"MPHumidity","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MPHumidity","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MPHumidity","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidity\/initWithCoder:","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidity\/initWithSymbol:converter:"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSDimension"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPHumidity"},{"text":" : ","kind":"text"},{"text":"NSDimension","preciseIdentifier":"c:objc(cs)NSDimension","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"MPHumidity","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHumidity\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHumidity\/fragments","value":[{"text":"MPHumidity","kind":"identifier"}]}]}]}