{"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidityLiveUpdate\/relativeHumidity"],"title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPHumidityLiveUpdate"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/mapsindoors\/mphumidityliveupdate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mphumidityliveupdate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidityLiveUpdate"},"metadata":{"title":"MPHumidityLiveUpdate","externalID":"c:@M@MapsIndoors@objc(cs)MPHumidityLiveUpdate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPHumidityLiveUpdate","kind":"identifier"}],"role":"symbol","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"MPHumidityLiveUpdate"}],"modules":[{"name":"MapsIndoors"}],"roleHeading":"Class"},"relationshipsSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"sections":[],"abstract":[{"type":"text","text":"Model for live humidity measurement for a given location."}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHumidityLiveUpdate/relativeHumidity":{"abstract":[{"type":"text","text":"The measured relative humidity for a given Location."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidityLiveUpdate\/relativeHumidity","title":"relativeHumidity","type":"topic","role":"symbol","navigatorTitle":[{"text":"relativeHumidity","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mphumidityliveupdate\/relativehumidity","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"relativeHumidity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Measurement","preciseIdentifier":"s:10Foundation11MeasurementV"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"MPHumidity","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHumidity"},{"kind":"text","text":">"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP"},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP"},"doc://com.mapspeople.mapsindoors/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHumidityLiveUpdate/initWithLiveUpdate:":{"navigatorTitle":[{"text":"initWithLiveUpdate:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidityLiveUpdate\/initWithLiveUpdate:","kind":"symbol","title":"initWithLiveUpdate:","url":"\/documentation\/mapsindoors\/mphumidityliveupdate\/initwithliveupdate:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithLiveUpdate:"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/getLiveUpdate(forDomainType:)":{"abstract":[{"type":"text","text":"Get a live update based on a known domain type."}],"title":"getLiveUpdate(forDomainType:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getLiveUpdate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forDomainType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"MPLiveUpdate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate"},{"kind":"text","text":"?"}],"role":"symbol","required":true,"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","navigatorTitle":[{"text":"getLiveUpdateForDomainType:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mplocation\/getliveupdate(fordomaintype:)","type":"topic"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate":{"abstract":[{"text":"Model for a Live Update. Used in ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","isActive":true,"type":"reference"}],"title":"MPLiveUpdate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPLiveUpdate"}],"role":"symbol","navigatorTitle":[{"text":"MPLiveUpdate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","type":"topic","url":"\/documentation\/mapsindoors\/mpliveupdate"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHumidityLiveUpdate":{"abstract":[{"type":"text","text":"Model for live humidity measurement for a given location."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidityLiveUpdate","type":"topic","title":"MPHumidityLiveUpdate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPHumidityLiveUpdate"}],"url":"\/documentation\/mapsindoors\/mphumidityliveupdate","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPHumidityLiveUpdate"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ"},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP"},"doc://com.mapspeople.mapsindoors/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"MPHumidityLiveUpdate","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPHumidityLiveUpdate"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MPHumidityLiveUpdate","kind":"identifier"}]},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidityLiveUpdate\/relativeHumidity"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidityLiveUpdate\/initWithLiveUpdate:"],"title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPHumidityLiveUpdate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"MPLiveUpdate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHumidityLiveUpdate~1relativeHumidity\/title","value":"relativeHumidity"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHumidityLiveUpdate~1relativeHumidity\/fragments","value":[{"text":"relativeHumidity","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/title","value":"getLiveUpdateForDomainType:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getLiveUpdateForDomainType:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/title","op":"replace","value":"MPLiveUpdate"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/fragments","value":[{"text":"MPLiveUpdate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHumidityLiveUpdate\/title","value":"MPHumidityLiveUpdate"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHumidityLiveUpdate\/fragments","value":[{"text":"MPHumidityLiveUpdate","kind":"identifier"}]}]}]}