{"kind":"symbol","topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPImageProviderProtocol\/getLocalImageFrom(urlString:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPImageProviderProtocol\/imageFrom(urlString:imageSize:)"]}],"variants":[{"paths":["\/documentation\/mapsindoors\/mpimageproviderprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpimageproviderprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"MPImageProviderProtocol","modules":[{"name":"MapsIndoors"}],"symbolKind":"protocol","externalID":"c:@M@MapsIndoors@objc(pl)MPImageProviderProtocol","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPImageProviderProtocol","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPImageProviderProtocol"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPImageProviderProtocol"}]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"inlineContent":[{"text":"A default implementation can be accessed and used via ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/imageProvider"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPImageProviderProtocol","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"abstract":[{"text":"Protocol to conform to when implementing an image provider for MapsIndoors.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","type":"image","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPImageProviderProtocol":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPImageProviderProtocol"}],"navigatorTitle":[{"text":"MPImageProviderProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPImageProviderProtocol","url":"\/documentation\/mapsindoors\/mpimageproviderprotocol","abstract":[{"text":"Protocol to conform to when implementing an image provider for MapsIndoors.","type":"text"}],"type":"topic","title":"MPImageProviderProtocol","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/imageProvider":{"role":"symbol","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/imageprovider","navigatorTitle":[{"text":"imageProvider","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/imageProvider","title":"imageProvider","type":"topic","abstract":[{"type":"text","text":"The image provider that MapsIndoors should use when image resources are needed."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageProvider"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPImageProviderProtocol","text":"MPImageProviderProtocol","kind":"typeIdentifier"}],"kind":"symbol","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPImageProviderProtocol/getLocalImageFrom(urlString:)":{"navigatorTitle":[{"kind":"identifier","text":"getLocalImageFromUrlString:completionHandler:"}],"title":"getLocalImageFrom(urlString:)","url":"\/documentation\/mapsindoors\/mpimageproviderprotocol\/getlocalimagefrom(urlstring:)","required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocalImageFrom"},{"text":"(","kind":"text"},{"text":"urlString","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPImageProviderProtocol\/getLocalImageFrom(urlString:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPImageProviderProtocol/imageFrom(urlString:imageSize:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"imageFrom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"urlString","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"imageSize","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"imageFromUrlString:imageSize:completionHandler:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPImageProviderProtocol\/imageFrom(urlString:imageSize:)","required":true,"url":"\/documentation\/mapsindoors\/mpimageproviderprotocol\/imagefrom(urlstring:imagesize:)","abstract":[],"type":"topic","title":"imageFrom(urlString:imageSize:)","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"value":"MPImageProviderProtocol","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"text":"MPImageProviderProtocol","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MPImageProviderProtocol","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPImageProviderProtocol\/getLocalImageFrom(urlString:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPImageProviderProtocol\/imageFrom(urlString:imageSize:)"]}],"path":"\/topicSections","op":"replace"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPImageProviderProtocol"}]}]},"op":"replace"},{"value":"MPImageProviderProtocol","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPImageProviderProtocol\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MPImageProviderProtocol"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPImageProviderProtocol\/fragments"},{"value":"imageProvider","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1imageProvider\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1imageProvider\/fragments","value":[{"text":"imageProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPImageProviderProtocol~1getLocalImageFrom(urlString:)\/title","value":"getLocalImageFromUrlString:completionHandler:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPImageProviderProtocol~1getLocalImageFrom(urlString:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getLocalImageFromUrlString:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPImageProviderProtocol~1imageFrom(urlString:imageSize:)\/title","value":"imageFromUrlString:imageSize:completionHandler:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPImageProviderProtocol~1imageFrom(urlString:imageSize:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imageFromUrlString:imageSize:completionHandler:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}