{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPImageRenderer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpimagerenderer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpimagerenderer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPImageRenderer","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPImageRenderer\/image(with:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPImageRenderer\/image(with:opaque:from:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPImageRenderer\/imageResize(_:andResizeTo:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPImageRenderer\/scaledIcon(from:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPImageRenderer"}],"title":"MPImageRenderer","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPImageRenderer","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPImageRenderer"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPImageRenderer":{"role":"symbol","title":"MPImageRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPImageRenderer"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPImageRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPImageRenderer"}],"url":"\/documentation\/mapsindoors\/mpimagerenderer"},"doc://MapsIndoors/documentation/MapsIndoors/MPImageRenderer/imageResize(_:andResizeTo:)":{"role":"symbol","title":"imageResize(_:andResizeTo:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageResize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andResizeTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPImageRenderer\/imageResize(_:andResizeTo:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageResize:andResizeTo:"}],"url":"\/documentation\/mapsindoors\/mpimagerenderer\/imageresize(_:andresizeto:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPImageRenderer/image(with:)":{"role":"symbol","title":"image(with:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPImageRenderer\/image(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageWithView:"}],"url":"\/documentation\/mapsindoors\/mpimagerenderer\/image(with:)"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPImageRenderer/image(with:opaque:from:)":{"role":"symbol","title":"image(with:opaque:from:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"opaque"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CALayer","preciseIdentifier":"c:objc(cs)CALayer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPImageRenderer\/image(with:opaque:from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageWithSize:opaque:fromLayer:"}],"url":"\/documentation\/mapsindoors\/mpimagerenderer\/image(with:opaque:from:)"},"doc://MapsIndoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(cs)NSObject"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPImageRenderer/scaledIcon(from:)":{"role":"symbol","title":"scaledIcon(from:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaledIcon"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPImageRenderer\/scaledIcon(from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scaledIconFromImage:"}],"url":"\/documentation\/mapsindoors\/mpimagerenderer\/scaledicon(from:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPImageRenderer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPImageRenderer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPImageRenderer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPImageRenderer\/image(with:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPImageRenderer\/image(with:opaque:from:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPImageRenderer\/imageResize(_:andResizeTo:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPImageRenderer\/scaledIcon(from:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPImageRenderer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPImageRenderer\/title","value":"MPImageRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPImageRenderer\/fragments","value":[{"kind":"identifier","text":"MPImageRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPImageRenderer~1imageResize(_:andResizeTo:)\/title","value":"imageResize:andResizeTo:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPImageRenderer~1imageResize(_:andResizeTo:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"imageResize:andResizeTo:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPImageRenderer~1image(with:)\/title","value":"imageWithView:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPImageRenderer~1image(with:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"imageWithView:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPImageRenderer~1image(with:opaque:from:)\/title","value":"imageWithSize:opaque:fromLayer:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPImageRenderer~1image(with:opaque:from:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"imageWithSize:opaque:fromLayer:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPImageRenderer~1scaledIcon(from:)\/title","value":"scaledIconFromImage:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPImageRenderer~1scaledIcon(from:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"scaledIconFromImage:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}