{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLatLng"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplatlng"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplatlng"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)JSONModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)NSCopying","doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding","doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLatLng","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLatLng\/lat","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLatLng\/lng"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLatLng"}],"title":"MPLatLng","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPLatLng","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLatLng"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLatLng":{"role":"symbol","title":"MPLatLng","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLatLng"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLatLng","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLatLng"}],"url":"\/documentation\/mapsindoors\/mplatlng"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLatLng/lng":{"role":"symbol","title":"lng","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lng"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLatLng\/lng","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lng"}],"url":"\/documentation\/mapsindoors\/mplatlng\/lng"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/objc(pl)AbstractJSONModelProtocol":{"type":"unresolvable","title":"JSONModel.AbstractJSONModelProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding"},"doc://MapsIndoors/objc(cs)JSONModel":{"type":"unresolvable","title":"JSONModel","identifier":"doc:\/\/MapsIndoors\/objc(cs)JSONModel"},"doc://MapsIndoors/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCopying"},"doc://MapsIndoors/documentation/MapsIndoors/MPLatLng/lat":{"role":"symbol","title":"lat","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLatLng\/lat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lat"}],"url":"\/documentation\/mapsindoors\/mplatlng\/lat"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPLatLng"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLatLng"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPLatLng"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLatLng\/lat","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLatLng\/lng"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLatLng"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSONModel","preciseIdentifier":"c:objc(cs)JSONModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLatLng\/title","value":"MPLatLng"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLatLng\/fragments","value":[{"kind":"identifier","text":"MPLatLng"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLatLng~1lng\/title","value":"lng"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLatLng~1lng\/fragments","value":[{"kind":"identifier","text":"lng"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLatLng~1lat\/title","value":"lat"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLatLng~1lat\/fragments","value":[{"kind":"identifier","text":"lat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}