{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManagerState"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplivedatamanagerstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplivedatamanagerstate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH","doc:\/\/MapsIndoors\/SY","doc:\/\/MapsIndoors\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enumeration of MPLiveDataManager states."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManagerState"}],"title":"MPLiveDataManagerState","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@MPLiveDataManagerState","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerState"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/closed","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/connected","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/connecting","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/disconnecting"]},{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/Equatable-Implementations","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerState":{"role":"symbol","title":"MPLiveDataManagerState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManagerState"}],"abstract":[{"type":"text","text":"Enumeration of MPLiveDataManager states."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerState"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerstate"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerState/connected":{"role":"symbol","title":"MPLiveDataManagerState.connected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}],"abstract":[{"type":"text","text":"The Connected state relfects the state of being connected to the Live Update remote services."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/connected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerStateConnected"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerstate\/connected"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerState/closed":{"role":"symbol","title":"MPLiveDataManagerState.closed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closed"}],"abstract":[{"type":"text","text":"The Closed state is the initial state before any subscriptions has been made in the Live Data Manager. It is also the state for when the Live Data Manager lost the connection or intentionally disconnected the Live Update remote services."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/closed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerStateClosed"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerstate\/closed"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/MapsIndoors\/s8SendableP"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/MapsIndoors\/SY"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerState/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mplivedatamanagerstate\/rawrepresentable-implementations"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerState/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mplivedatamanagerstate\/equatable-implementations"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerState/connecting":{"role":"symbol","title":"MPLiveDataManagerState.connecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"abstract":[{"type":"text","text":"The Connecting state reflects the process of creating a valid connection with the Live Update remote services."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/connecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerStateConnecting"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerstate\/connecting"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerState/disconnecting":{"role":"symbol","title":"MPLiveDataManagerState.disconnecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnecting"}],"abstract":[{"type":"text","text":"The Disconnecting state reflects the process of disconnecting the Live Update remote services."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/disconnecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerStateDisconnecting"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerstate\/disconnecting"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mplivedatamanagerstate\/init(rawvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"MPLiveDataManagerState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerState"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPLiveDataManagerState"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/closed","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/connected","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/connecting","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/disconnecting"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManagerState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState\/title","value":"MPLiveDataManagerState"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerState"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState~1connected\/title","value":"MPLiveDataManagerStateConnected"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState~1connected\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerStateConnected"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState~1closed\/title","value":"MPLiveDataManagerStateClosed"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState~1closed\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerStateClosed"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState~1connecting\/title","value":"MPLiveDataManagerStateConnecting"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState~1connecting\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerStateConnecting"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState~1disconnecting\/title","value":"MPLiveDataManagerStateDisconnecting"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState~1disconnecting\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerStateDisconnecting"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}