{"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/availability","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/co2","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/count","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/humidity","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/occupancy","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/position","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/temperature"]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"variants":[{"paths":["\/documentation\/mapsindoors\/mplivedomaintype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mplivedomaintype"]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Class","role":"symbol","symbolKind":"class","navigatorTitle":[{"text":"MPLiveDomainType","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPLiveDomainType","modules":[{"name":"MapsIndoors"}],"title":"MPLiveDomainType","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLiveDomainType","kind":"identifier"}]},"sections":[],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPLiveDomainType","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveDomainType/availability":{"abstract":[{"type":"text","text":"Availability Domain Type"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"availability","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"availability","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/availability","kind":"symbol","url":"\/documentation\/mapsindoors\/mplivedomaintype\/availability","title":"availability"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveDomainType/temperature":{"navigatorTitle":[{"text":"temperature","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"temperature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"text":"Temperature Domain Type","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/temperature","title":"temperature","url":"\/documentation\/mapsindoors\/mplivedomaintype\/temperature","kind":"symbol","type":"topic","role":"symbol"},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveDomainType/co2":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/co2","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"co2","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"co2","abstract":[{"type":"text","text":"CO2 Domain Type"}],"url":"\/documentation\/mapsindoors\/mplivedomaintype\/co2","role":"symbol","navigatorTitle":[{"text":"co2","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveDomainType/init":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/init","title":"init","type":"topic","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"url":"\/documentation\/mapsindoors\/mplivedomaintype\/init","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.mapspeople.mapsindoors/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveDomainType":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType","url":"\/documentation\/mapsindoors\/mplivedomaintype","title":"MPLiveDomainType","navigatorTitle":[{"text":"MPLiveDomainType","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPLiveDomainType","kind":"identifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveDomainType/count":{"role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mplivedomaintype\/count","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"count","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"count","kind":"identifier"}],"abstract":[{"text":"Count Domain Type","type":"text"}],"kind":"symbol","title":"count","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/count"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveDomainType/occupancy":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/occupancy","role":"symbol","abstract":[{"type":"text","text":"Occupancy Domain Type"}],"title":"occupancy","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"occupancy"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"occupancy"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mplivedomaintype\/occupancy"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveDomainType/position":{"title":"position","role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mplivedomaintype\/position","navigatorTitle":[{"kind":"identifier","text":"position"}],"abstract":[{"text":"Position Domain Type","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/position","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.mapspeople.mapsindoors/SQ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveDomainType/humidity":{"abstract":[{"type":"text","text":"Humidity Domain Type"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"humidity","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mplivedomaintype\/humidity","title":"humidity","navigatorTitle":[{"kind":"identifier","text":"humidity"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/humidity"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"type":"image"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.mapspeople.mapsindoors/SH":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"MPLiveDomainType","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"MPLiveDomainType"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"MPLiveDomainType","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/init"]},{"title":"Type Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/availability","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/co2","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/count","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/humidity","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/occupancy","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/position","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveDomainType\/temperature"]}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"MPLiveDomainType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveDomainType~1availability\/title","value":"availability"},{"value":[{"text":"availability","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveDomainType~1availability\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveDomainType~1temperature\/title","value":"temperature"},{"op":"replace","value":[{"text":"temperature","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveDomainType~1temperature\/fragments"},{"value":"co2","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveDomainType~1co2\/title"},{"value":[{"kind":"identifier","text":"co2"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveDomainType~1co2\/fragments"},{"op":"replace","value":"MPLiveDomainType","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveDomainType\/title"},{"value":[{"kind":"identifier","text":"MPLiveDomainType"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveDomainType\/fragments","op":"replace"},{"value":"count","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveDomainType~1count\/title"},{"op":"replace","value":[{"text":"count","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveDomainType~1count\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveDomainType~1occupancy\/title","value":"occupancy","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveDomainType~1occupancy\/fragments","op":"replace","value":[{"kind":"identifier","text":"occupancy"}]},{"value":"position","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveDomainType~1position\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveDomainType~1position\/fragments","op":"replace","value":[{"kind":"identifier","text":"position"}]},{"value":"humidity","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveDomainType~1humidity\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveDomainType~1humidity\/fragments","value":[{"text":"humidity","kind":"identifier"}]}]}]}