{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManagerDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplivedatamanagerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplivedatamanagerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Live Data Manager Delegate protocol. Conforming to this protocol makes it possible to get Live Updates, state changes, errors and other calls from MPLiveDataManager."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManagerDelegate"}],"title":"MPLiveDataManagerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)MPLiveDataManagerDelegate","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didReceive(_:)-409qk","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didReceive(_:)-68von","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didSubscribe(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didUnsubscribe(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didUpdate(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/onError(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/onSubscriptionError(_:topic:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/onUnsubscriptionError(_:topic:)"]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerDelegate/didReceive(_:)-68von":{"navigatorTitle":[{"kind":"identifier","text":"didReceiveLiveDataInfo:"}],"role":"symbol","title":"didReceive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLiveDataInfo","preciseIdentifier":"c:objc(cs)MPLiveDataInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when information about Liva Data for for a dataset is determined. The information will contain the currently active domain types."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didReceive(_:)-68von","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/didreceive(_:)-68von"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerDelegate/didUnsubscribe(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didUnsubscribe:"}],"role":"symbol","title":"didUnsubscribe(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUnsubscribe"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a Topic Criteria has successfully ended subscription for Live Updates."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didUnsubscribe(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/didunsubscribe(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerDelegate/didReceive(_:)-409qk":{"navigatorTitle":[{"kind":"identifier","text":"didReceiveLiveUpdate:"}],"role":"symbol","title":"didReceive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLiveUpdate","preciseIdentifier":"c:objc(cs)MPLiveUpdate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a Live Update was recieved."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didReceive(_:)-409qk","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/didreceive(_:)-409qk"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerDelegate/onError(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onError:"}],"role":"symbol","title":"onError(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when an error occurs. If the error is due to lack of network connectivity, the Live Data Manager will automatically do reconnection attempts."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/onError(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/onerror(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerDelegate/didSubscribe(_:)":{"role":"symbol","title":"didSubscribe(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSubscribe"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a Topic Criteria has successfully been subscribed for Live Updates."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didSubscribe(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didSubscribe:"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/didsubscribe(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerDelegate/onUnsubscriptionError(_:topic:)":{"navigatorTitle":[{"kind":"identifier","text":"onUnsubscriptionError:topic:"}],"role":"symbol","title":"onUnsubscriptionError(_:topic:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUnsubscriptionError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a unsubscription fails. The unsubscription will be not automatically be retried."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/onUnsubscriptionError(_:topic:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/onunsubscriptionerror(_:topic:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerDelegate":{"role":"symbol","title":"MPLiveDataManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManagerDelegate"}],"abstract":[{"type":"text","text":"Live Data Manager Delegate protocol. Conforming to this protocol makes it possible to get Live Updates, state changes, errors and other calls from MPLiveDataManager."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerDelegate"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerdelegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerDelegate/didUpdate(_:)":{"role":"symbol","title":"didUpdate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLiveDataManagerState","preciseIdentifier":"c:@E@MPLiveDataManagerState"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the state of the Live Data Manager changes."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didUpdate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didUpdateState:"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/didupdate(_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerDelegate/onSubscriptionError(_:topic:)":{"navigatorTitle":[{"kind":"identifier","text":"onSubscriptionError:topic:"}],"role":"symbol","title":"onSubscriptionError(_:topic:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSubscriptionError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLiveTopicCriteria","preciseIdentifier":"c:objc(cs)MPLiveTopicCriteria"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a subscription fails. The subscription will be not automatically be retried."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/onSubscriptionError(_:topic:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplivedatamanagerdelegate\/onsubscriptionerror(_:topic:)"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPLiveDataManagerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPLiveDataManagerDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didReceive(_:)-409qk","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didReceive(_:)-68von","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didSubscribe(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didUnsubscribe(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/didUpdate(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/onError(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/onSubscriptionError(_:topic:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerDelegate\/onUnsubscriptionError(_:topic:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManagerDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1didReceive(_:)-68von\/title","value":"didReceiveLiveDataInfo:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1didReceive(_:)-68von\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveLiveDataInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1didUnsubscribe(_:)\/title","value":"didUnsubscribe:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1didUnsubscribe(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUnsubscribe:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1didReceive(_:)-409qk\/title","value":"didReceiveLiveUpdate:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1didReceive(_:)-409qk\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveLiveUpdate:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1onError(_:)\/title","value":"onError:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1onError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onError:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1didSubscribe(_:)\/title","value":"didSubscribe:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1didSubscribe(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didSubscribe:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1onUnsubscriptionError(_:topic:)\/title","value":"onUnsubscriptionError:topic:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1onUnsubscriptionError(_:topic:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUnsubscriptionError:topic:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate\/title","value":"MPLiveDataManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1didUpdate(_:)\/title","value":"didUpdateState:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1didUpdate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdateState:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1onSubscriptionError(_:topic:)\/title","value":"onSubscriptionError:topic:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerDelegate~1onSubscriptionError(_:topic:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSubscriptionError:topic:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}