{"abstract":[{"type":"text","text":"Model for a Live Update. Used in "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","isActive":true,"type":"reference"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpliveupdate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpliveupdate"]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"]},{"kind":"relationships","type":"inheritedBy","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAvailabilityLiveUpdate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCO2LiveUpdate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCountLiveUpdate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidityLiveUpdate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPOccupancyLiveUpdate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionLiveUpdate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTemperatureLiveUpdate"],"title":"Inherited By"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveUpdate"}]}],"kind":"declarations"}],"sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/init(from:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/init(withLiveUpdate:)"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/itemId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/originSourceId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/properties","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/timestamp","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/topic"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/encode(to:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/getLiveValueForKey(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/liveUpdateWithDictionary(_:topic:)"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/CodingKeys"],"title":"Enumerations"}],"metadata":{"modules":[{"name":"MapsIndoors"}],"roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"MPLiveUpdate"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate","title":"MPLiveUpdate","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLiveUpdate","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"references":{"doc://com.mapspeople.mapsindoors/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCountLiveUpdate":{"role":"symbol","type":"topic","abstract":[{"text":"Model for live event information for a given Location.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCountLiveUpdate","title":"MPCountLiveUpdate","kind":"symbol","navigatorTitle":[{"text":"MPCountLiveUpdate","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpcountliveupdate","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPCountLiveUpdate","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/getLiveUpdate(forDomainType:)":{"title":"getLiveUpdate(forDomainType:)","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"getLiveUpdateForDomainType:"}],"type":"topic","abstract":[{"text":"Get a live update based on a known domain type.","type":"text"}],"url":"\/documentation\/mapsindoors\/mplocation\/getliveupdate(fordomaintype:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getLiveUpdate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forDomainType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate","kind":"typeIdentifier","text":"MPLiveUpdate"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate/liveUpdateWithDictionary(_:topic:)":{"url":"\/documentation\/mapsindoors\/mpliveupdate\/liveupdatewithdictionary(_:topic:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"liveUpdateWithDictionary:topic:"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/liveUpdateWithDictionary(_:topic:)","title":"liveUpdateWithDictionary(_:topic:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"liveUpdateWithDictionary"},{"text":"([","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"topic"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"text":"MPLiveUpdate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate/itemId":{"navigatorTitle":[{"text":"itemId","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpliveupdate\/itemid","abstract":[{"type":"text","text":"Get the item id that a Live Update relates to. In most cases this would be the id of a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation"},{"text":".","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/itemId","kind":"symbol","title":"itemId","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"itemId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate/timestamp":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/timestamp","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"title":"timestamp","url":"\/documentation\/mapsindoors\/mpliveupdate\/timestamp","abstract":[{"type":"text","text":"Get the timestamp for a Live Update."}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate/properties":{"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpliveupdate\/properties","navigatorTitle":[{"text":"properties","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/properties","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"properties"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]","kind":"text"}],"title":"properties"},"doc://com.mapspeople.mapsindoors/SH":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate/init(from:)":{"url":"\/documentation\/mapsindoors\/mpliveupdate\/init(from:)","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/init(from:)","title":"init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPOccupancyLiveUpdate":{"role":"symbol","abstract":[{"type":"text","text":"Model for live occupancy information for a given Location."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpoccupancyliveupdate","navigatorTitle":[{"kind":"identifier","text":"MPOccupancyLiveUpdate"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPOccupancyLiveUpdate","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPOccupancyLiveUpdate"}],"title":"MPOccupancyLiveUpdate"},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"title":"MPLocation","kind":"symbol","url":"\/documentation\/mapsindoors\/mplocation","abstract":[{"type":"text","text":"This holds the data for a single location and a marker to display the data on a map."}]},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate/getLiveValueForKey(_:)":{"url":"\/documentation\/mapsindoors\/mpliveupdate\/getlivevalueforkey(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"getLiveValueForKey:"}],"abstract":[{"type":"text","text":"Get a value from a specific Live Update property. If no value exists the method returns "},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/getLiveValueForKey(_:)","title":"getLiveValueForKey(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getLiveValueForKey","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"role":"symbol"},"MapsPeopleWhite.png":{"alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTemperatureLiveUpdate":{"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/mapsindoors\/mptemperatureliveupdate","navigatorTitle":[{"text":"MPTemperatureLiveUpdate","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTemperatureLiveUpdate","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPTemperatureLiveUpdate","kind":"identifier"}],"title":"MPTemperatureLiveUpdate"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate/init(withLiveUpdate:)":{"url":"\/documentation\/mapsindoors\/mpliveupdate\/init(withliveupdate:)","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/init(withLiveUpdate:)","title":"init(withLiveUpdate:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLiveUpdate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate","text":"MPLiveUpdate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionLiveUpdate":{"role":"symbol","abstract":[{"text":"Model for live position information for a given Location.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mppositionliveupdate","navigatorTitle":[{"text":"MPPositionLiveUpdate","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionLiveUpdate","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionLiveUpdate"}],"title":"MPPositionLiveUpdate"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate/originSourceId":{"title":"originSourceId","role":"symbol","url":"\/documentation\/mapsindoors\/mpliveupdate\/originsourceid","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/originSourceId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"originSourceId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"type":"text","text":"Get the id for the origin source entity of a Live Update. Often the Live Update comes from another entity or device in a 3rd party system. For example an id of a meeting room calendar in a booking system or an id of a room temperature sensor."}],"kind":"symbol","navigatorTitle":[{"text":"originSourceId","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate":{"url":"\/documentation\/mapsindoors\/mpliveupdate","title":"MPLiveUpdate","navigatorTitle":[{"kind":"identifier","text":"MPLiveUpdate"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","abstract":[{"type":"text","text":"Model for a Live Update. Used in "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","isActive":true,"type":"reference"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLiveUpdate","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAvailabilityLiveUpdate":{"navigatorTitle":[{"text":"MPAvailabilityLiveUpdate","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPAvailabilityLiveUpdate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAvailabilityLiveUpdate","title":"MPAvailabilityLiveUpdate","abstract":[{"type":"text","text":"Model for live availability information for a given Location."}],"type":"topic","url":"\/documentation\/mapsindoors\/mpavailabilityliveupdate"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate/encode(to:)":{"url":"\/documentation\/mapsindoors\/mpliveupdate\/encode(to:)","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/encode(to:)","title":"encode(to:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s7EncoderP","kind":"typeIdentifier","text":"Encoder"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate/CodingKeys":{"url":"\/documentation\/mapsindoors\/mpliveupdate\/codingkeys","title":"MPLiveUpdate.CodingKeys","navigatorTitle":[{"kind":"identifier","text":"CodingKeys"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/CodingKeys","abstract":[],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CodingKeys","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPCO2LiveUpdate":{"role":"symbol","abstract":[{"text":"Model for live CO2 measurement for a given location.","type":"text"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpco2liveupdate","navigatorTitle":[{"text":"MPCO2LiveUpdate","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCO2LiveUpdate","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPCO2LiveUpdate","kind":"identifier"}],"title":"MPCO2LiveUpdate"},"doc://com.mapspeople.mapsindoors/SE":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/SQ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPHumidityLiveUpdate":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Model for live humidity measurement for a given location."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidityLiveUpdate","title":"MPHumidityLiveUpdate","kind":"symbol","navigatorTitle":[{"text":"MPHumidityLiveUpdate","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mphumidityliveupdate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPHumidityLiveUpdate"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate/topic":{"abstract":[{"type":"text","text":"Get the Topic of the Live Update."}],"navigatorTitle":[{"kind":"identifier","text":"topic"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"topic","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPLiveUpdateTopic","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdateTopic"}],"url":"\/documentation\/mapsindoors\/mpliveupdate\/topic","title":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"MPLiveUpdate","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"MPLiveUpdate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MPLiveUpdate","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/itemId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/originSourceId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/properties","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/timestamp","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/topic"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/getLiveValueForKey(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate\/liveUpdateWithDictionary(_:topic:)"]}]},{"value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","type":"inheritedBy","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAvailabilityLiveUpdate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCO2LiveUpdate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPCountLiveUpdate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPHumidityLiveUpdate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPOccupancyLiveUpdate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionLiveUpdate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTemperatureLiveUpdate"],"title":"Inherited By"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"MPLiveUpdate","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"MPCountLiveUpdate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCountLiveUpdate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCountLiveUpdate\/fragments","value":[{"kind":"identifier","text":"MPCountLiveUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/title","value":"getLiveUpdateForDomainType:"},{"value":[{"text":"- ","kind":"text"},{"text":"getLiveUpdateForDomainType:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/fragments"},{"value":"liveUpdateWithDictionary:topic:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate~1liveUpdateWithDictionary(_:topic:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate~1liveUpdateWithDictionary(_:topic:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"liveUpdateWithDictionary:topic:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate~1itemId\/title","value":"itemId","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate~1itemId\/fragments","op":"replace","value":[{"kind":"identifier","text":"itemId"}]},{"value":"timestamp","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate~1timestamp\/title"},{"value":[{"kind":"identifier","text":"timestamp"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate~1timestamp\/fragments"},{"value":"properties","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate~1properties\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate~1properties\/fragments","value":[{"text":"properties","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPOccupancyLiveUpdate\/title","value":"MPOccupancyLiveUpdate","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPOccupancyLiveUpdate\/fragments","op":"replace","value":[{"text":"MPOccupancyLiveUpdate","kind":"identifier"}]},{"value":"MPLocation","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/title"},{"value":[{"kind":"identifier","text":"MPLocation"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/fragments"},{"value":"getLiveValueForKey:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate~1getLiveValueForKey(_:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate~1getLiveValueForKey(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getLiveValueForKey:"}],"op":"replace"},{"value":"MPTemperatureLiveUpdate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTemperatureLiveUpdate\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTemperatureLiveUpdate\/fragments","value":[{"text":"MPTemperatureLiveUpdate","kind":"identifier"}],"op":"replace"},{"value":"MPPositionLiveUpdate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionLiveUpdate\/title"},{"op":"replace","value":[{"text":"MPPositionLiveUpdate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionLiveUpdate\/fragments"},{"value":"originSourceId","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate~1originSourceId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"originSourceId"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate~1originSourceId\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/title","value":"MPLiveUpdate","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/fragments","value":[{"kind":"identifier","text":"MPLiveUpdate"}],"op":"replace"},{"value":"MPAvailabilityLiveUpdate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAvailabilityLiveUpdate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAvailabilityLiveUpdate\/fragments","value":[{"text":"MPAvailabilityLiveUpdate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCO2LiveUpdate\/title","value":"MPCO2LiveUpdate"},{"value":[{"text":"MPCO2LiveUpdate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPCO2LiveUpdate\/fragments"},{"value":"MPHumidityLiveUpdate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHumidityLiveUpdate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MPHumidityLiveUpdate"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPHumidityLiveUpdate\/fragments","op":"replace"},{"value":"topic","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate~1topic\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate~1topic\/fragments","value":[{"kind":"identifier","text":"topic"}]}]}]}