{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPLocationsObserver","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mplocationsobserver"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mplocationsobserver"]}],"metadata":{"roleHeading":"Protocol","title":"MPLocationsObserver","externalID":"c:@M@MapsIndoors@objc(pl)MPLocationsObserver","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLocationsObserver","kind":"identifier"}],"role":"symbol","symbolKind":"protocol","navigatorTitle":[{"text":"MPLocationsObserver","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Location observer protocol."}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver\/onLocationsDelete(_:source:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver\/onLocationsUpdate(_:source:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver\/onStatusChange(_:source:)"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationsObserver/onStatusChange(_:source:)":{"title":"onStatusChange(_:source:)","url":"\/documentation\/mapsindoors\/mplocationsobserver\/onstatuschange(_:source:)","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Status change event method."}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"onStatusChange:source:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver\/onStatusChange(_:source:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onStatusChange"},{"text":"(","kind":"text"},{"text":"MPLocationSourceStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPLocationSourceStatus"},{"kind":"text","text":", "},{"text":"source","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MPLocationSource","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationSource","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationsObserver/onLocationsDelete(_:source:)":{"title":"onLocationsDelete(_:source:)","url":"\/documentation\/mapsindoors\/mplocationsobserver\/onlocationsdelete(_:source:)","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Location delete event method."}],"required":true,"navigatorTitle":[{"text":"onLocationsDelete:source:","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver\/onLocationsDelete(_:source:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onLocationsDelete","kind":"identifier"},{"kind":"text","text":"(["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"source"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationSource","text":"MPLocationSource","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationsObserver":{"title":"MPLocationsObserver","url":"\/documentation\/mapsindoors\/mplocationsobserver","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Location observer protocol.","type":"text"}],"navigatorTitle":[{"text":"MPLocationsObserver","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPLocationsObserver"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationsObserver/onLocationsUpdate(_:source:)":{"title":"onLocationsUpdate(_:source:)","url":"\/documentation\/mapsindoors\/mplocationsobserver\/onlocationsupdate(_:source:)","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Location update event method."}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"onLocationsUpdate:source:"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver\/onLocationsUpdate(_:source:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onLocationsUpdate","kind":"identifier"},{"kind":"text","text":"(["},{"text":"MPLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"kind":"text","text":"], "},{"text":"source","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MPLocationSource","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationSource","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"MPLocationsObserver","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"MPLocationsObserver","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"MPLocationsObserver","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver\/onLocationsDelete(_:source:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver\/onLocationsUpdate(_:source:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationsObserver\/onStatusChange(_:source:)"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"MPLocationsObserver","kind":"identifier"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationsObserver~1onStatusChange(_:source:)\/title","op":"replace","value":"onStatusChange:source:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onStatusChange:source:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationsObserver~1onStatusChange(_:source:)\/fragments"},{"value":"onLocationsDelete:source:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationsObserver~1onLocationsDelete(_:source:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationsObserver~1onLocationsDelete(_:source:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onLocationsDelete:source:"}],"op":"replace"},{"value":"MPLocationsObserver","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationsObserver\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationsObserver\/fragments","value":[{"text":"MPLocationsObserver","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationsObserver~1onLocationsUpdate(_:source:)\/title","value":"onLocationsUpdate:source:"},{"value":[{"kind":"text","text":"- "},{"text":"onLocationsUpdate:source:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationsObserver~1onLocationsUpdate(_:source:)\/fragments"}]}]}