{"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/aliases","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/baseType","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/building","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/categories","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/coordinateBounds","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/externalId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/fields","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/floorIndex","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/floorName","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/geometry","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/icon","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/iconUrl","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/imageURL","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/isBookable","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/locationDescription","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/locationId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/position","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/restrictions","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/type","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/venue"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveValue(forKey:domainType:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/property(key:)"],"title":"Instance Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mplocation"]}],"metadata":{"role":"symbol","title":"MPLocation","modules":[{"name":"MapsIndoors"}],"symbolKind":"protocol","externalID":"c:@M@MapsIndoors@objc(pl)MPLocation","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPLocation"}],"navigatorTitle":[{"text":"MPLocation","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPLocation","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPEntity","text":"MPEntity"}],"languages":["swift"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"abstract":[{"type":"text","text":"This holds the data for a single location and a marker to display the data on a map."}],"seeAlsoSections":[{"title":"MapsIndoors entities","generated":true,"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor"]}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding/administrativeId":{"required":true,"type":"topic","title":"administrativeId","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"administrativeId"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"administrativeId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"The Building administrative id.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/administrativeId","url":"\/documentation\/mapsindoors\/mpbuilding\/administrativeid"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/property(key:)":{"title":"property(key:)","role":"symbol","navigatorTitle":[{"text":"propertyWithKey:","kind":"identifier"}],"type":"topic","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/property(key:)","abstract":[{"text":"Get data for custom field with key, disregarding casing of key.","type":"text"}],"url":"\/documentation\/mapsindoors\/mplocation\/property(key:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"property"},{"kind":"text","text":"("},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"MPLocationField","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/administrativeId":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/administrativeId","title":"administrativeId","required":true,"role":"symbol","abstract":[{"text":"Get venue administrative id.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"administrativeId"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpvenue\/administrativeid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"administrativeId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/getLiveUpdate(forDomainType:)":{"abstract":[{"type":"text","text":"Get a live update based on a known domain type."}],"title":"getLiveUpdate(forDomainType:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getLiveUpdate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forDomainType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"MPLiveUpdate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate"},{"kind":"text","text":"?"}],"role":"symbol","required":true,"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","navigatorTitle":[{"text":"getLiveUpdateForDomainType:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mplocation\/getliveupdate(fordomaintype:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation":{"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","abstract":[{"type":"text","text":"This holds the data for a single location and a marker to display the data on a map."}],"url":"\/documentation\/mapsindoors\/mplocation","role":"symbol","title":"MPLocation","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"navigatorTitle":[{"text":"MPLocation","kind":"identifier"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/iconUrl":{"title":"iconUrl","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"iconUrl"}],"type":"topic","required":true,"url":"\/documentation\/mapsindoors\/mplocation\/iconurl","abstract":[{"type":"text","text":"Location icon as a URL. If icon is originally set as a UIImage, this property will be ignored."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/iconUrl","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconUrl"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/position":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/position","title":"position","required":true,"role":"symbol","abstract":[{"type":"text","text":"Position as "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint","isActive":true,"type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"position","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mplocation\/position","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","kind":"typeIdentifier","text":"MPPoint"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/restrictions":{"kind":"symbol","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/restrictions","abstract":[{"text":"If set, Location is restricted to the given set of app user roles.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"restrictions","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"restrictions"}],"role":"symbol","title":"restrictions","url":"\/documentation\/mapsindoors\/mplocation\/restrictions"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/coordinateBounds":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"coordinateBounds"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mplocation\/coordinatebounds","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/coordinateBounds","title":"coordinateBounds","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"coordinateBounds","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","text":"MPGeoBounds","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding":{"kind":"symbol","abstract":[{"type":"text","text":"Holds relevant data for a single building, and the buildings floor levels."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","navigatorTitle":[{"text":"MPBuilding","kind":"identifier"}],"type":"topic","title":"MPBuilding","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPBuilding","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpbuilding","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFloor":{"role":"symbol","type":"topic","title":"MPFloor","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPFloor","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpfloor","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor","abstract":[{"type":"text","text":"Floor data model. Holds the floor geometry, display name, z-index and id of the building it belongs to."}],"navigatorTitle":[{"text":"MPFloor","kind":"identifier"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/externalId":{"title":"externalId","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"externalId"}],"type":"topic","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/externalId","abstract":[{"type":"text","text":"Location external id property."}],"url":"\/documentation\/mapsindoors\/mplocation\/externalid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"externalId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/fields":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"fields","kind":"identifier"}],"type":"topic","required":true,"url":"\/documentation\/mapsindoors\/mplocation\/fields","abstract":[{"type":"text","text":"Custom fields associated with the location object."},{"text":" ","type":"text"},{"type":"text","text":"Keys are case sensitive.  For case-insensitive access to custom fields use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/property(key:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/fields","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationField","text":"MPLocationField","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"title":"fields"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/venue":{"title":"venue","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"venue"}],"type":"topic","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/venue","abstract":[{"type":"text","text":"Location venue property. This string correlates with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/administrativeId"},{"text":".","type":"text"}],"url":"\/documentation\/mapsindoors\/mplocation\/venue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"venue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPoint":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPoint"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPoint","title":"MPPoint","navigatorTitle":[{"text":"MPPoint","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/mapsindoors\/mppoint"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/icon":{"required":true,"url":"\/documentation\/mapsindoors\/mplocation\/icon","title":"icon","abstract":[{"type":"text","text":"Location icon. If nil, the location will either get an icon from the settings configured for the type of location or a default appearance that is configurable through ``MPMapControl`."}],"navigatorTitle":[{"kind":"identifier","text":"icon"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/icon","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"icon"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?","kind":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/building":{"abstract":[{"type":"text","text":"Location building property. This string correlates with "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/administrativeId","type":"reference","isActive":true},{"type":"text","text":"."}],"kind":"symbol","title":"building","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/building","navigatorTitle":[{"kind":"identifier","text":"building"}],"url":"\/documentation\/mapsindoors\/mplocation\/building","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"building"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/type":{"abstract":[{"type":"text","text":"Location type property."}],"url":"\/documentation\/mapsindoors\/mplocation\/type","title":"type","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"type"}],"required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/type","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/isBookable":{"abstract":[{"text":"Determines if the Location is bookable using the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService"},{"type":"text","text":"."}],"kind":"symbol","title":"isBookable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/isBookable","navigatorTitle":[{"text":"isBookable","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mplocation\/isbookable","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isBookable","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/baseType":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"baseType","kind":"identifier"}],"type":"topic","required":true,"url":"\/documentation\/mapsindoors\/mplocation\/basetype","abstract":[{"type":"text","text":"Location base type."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/baseType","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseType"},{"text":": ","kind":"text"},{"text":"MPLocationBaseType","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPLocationBaseType"}],"title":"baseType"},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","type":"image","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/imageURL":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageURL","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/mapsindoors\/mplocation\/imageurl","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/imageURL","role":"symbol","navigatorTitle":[{"text":"imageURL","kind":"identifier"}],"title":"imageURL","abstract":[{"text":"URL for image associated with this ``MPLocation`.","type":"text"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/locationId":{"kind":"symbol","navigatorTitle":[{"text":"locationId","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locationId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"text":"Location id property.","type":"text"}],"type":"topic","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/locationId","title":"locationId","url":"\/documentation\/mapsindoors\/mplocation\/locationid"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/geometry":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"geometry","kind":"identifier"}],"type":"topic","required":true,"url":"\/documentation\/mapsindoors\/mplocation\/geometry","abstract":[{"type":"text","text":"The geometry representing the location."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/geometry","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometry"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometry","text":"MPGeometry","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"geometry"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/floorName":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mplocation\/floorname","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/floorName","type":"topic","title":"floorName","abstract":[{"text":"If the location resides on a specific floor level, the name of that floor level can be retrieved here.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"floorName","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"floorName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/aliases":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"aliases"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"aliases","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/aliases","abstract":[{"text":"Aliases for Location.","type":"text"}],"required":true,"type":"topic","role":"symbol","kind":"symbol","title":"aliases","url":"\/documentation\/mapsindoors\/mplocation\/aliases"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFloor/floorIndex":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"floorIndex","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"floorIndex"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/floorIndex","abstract":[{"type":"text","text":"The Floor index."}],"required":true,"type":"topic","role":"symbol","kind":"symbol","title":"floorIndex","url":"\/documentation\/mapsindoors\/mpfloor\/floorindex"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBookingService":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPBookingService","kind":"identifier"}],"navigatorTitle":[{"text":"MPBookingService","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBookingService","abstract":[{"type":"text","text":"MPBookingService allows for access to the MapsIndoors booking service."},{"text":" ","type":"text"},{"type":"text","text":"The booking service is a special integration that has to be enabled in the MapsIndoors cloud systems."}],"role":"symbol","type":"topic","kind":"symbol","title":"MPBookingService","url":"\/documentation\/mapsindoors\/mpbookingservice"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/categories":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/categories","abstract":[{"type":"text","text":"The categories for this location, as an array."}],"url":"\/documentation\/mapsindoors\/mplocation\/categories","kind":"symbol","required":true,"role":"symbol","title":"categories","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"categories","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"categories"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/locationDescription":{"title":"locationDescription","kind":"symbol","abstract":[{"type":"text","text":"Location description property."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/locationDescription","navigatorTitle":[{"text":"locationDescription","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mplocation\/locationdescription","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"locationDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPEntity":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPEntity"}],"navigatorTitle":[{"kind":"identifier","text":"MPEntity"}],"url":"\/documentation\/mapsindoors\/mpentity","abstract":[{"type":"text","text":"MPEntity is a general protocol implemented by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation"},{"text":", ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","isActive":true},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue"},{"type":"text","text":"."}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity","kind":"symbol","title":"MPEntity"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPVenue"}],"title":"MPVenue","navigatorTitle":[{"text":"MPVenue","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpvenue","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","role":"symbol","abstract":[{"text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data.","type":"text"}],"type":"topic","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/getLiveValue(forKey:domainType:)":{"title":"getLiveValue(forKey:domainType:)","role":"symbol","navigatorTitle":[{"text":"getLiveValueForKey:domainType:","kind":"identifier"}],"type":"topic","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveValue(forKey:domainType:)","abstract":[{"text":"Get a live property value based on a known key and domain type","type":"text"}],"url":"\/documentation\/mapsindoors\/mplocation\/getlivevalue(forkey:domaintype:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getLiveValue"},{"kind":"text","text":"("},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"domainType"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s9AnyObjecta","text":"AnyObject","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/name":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/name","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/mapsindoors\/mplocation\/name","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"required":true,"role":"symbol","type":"topic","title":"name","abstract":[{"text":"Location name.","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/floorIndex":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"floorIndex","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"}],"navigatorTitle":[{"kind":"identifier","text":"floorIndex"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/floorIndex","abstract":[{"type":"text","text":"If the location resides on a specific floor level, this property is set. This value correlates with "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor\/floorIndex","isActive":true},{"type":"text","text":"."}],"required":true,"type":"topic","role":"symbol","kind":"symbol","title":"floorIndex","url":"\/documentation\/mapsindoors\/mplocation\/floorindex"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MPLocation","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPLocation"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MPLocation","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/aliases","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/baseType","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/building","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/categories","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/coordinateBounds","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/externalId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/fields","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/floorIndex","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/floorName","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/geometry","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/icon","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/iconUrl","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/imageURL","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/isBookable","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/locationDescription","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/locationId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/position","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/restrictions","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/type","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/venue"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveValue(forKey:domainType:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/property(key:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"MapsIndoors entities","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor"],"generated":true}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLocation","kind":"identifier"},{"text":" <","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPEntity","text":"MPEntity"},{"text":">","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1administrativeId\/title","value":"administrativeId","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1administrativeId\/fragments","op":"replace","value":[{"kind":"identifier","text":"administrativeId"}]},{"value":"propertyWithKey:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1property(key:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1property(key:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"propertyWithKey:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1administrativeId\/title","op":"replace","value":"administrativeId"},{"value":[{"text":"administrativeId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1administrativeId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/title","value":"getLiveUpdateForDomainType:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getLiveUpdateForDomainType:"}],"op":"replace"},{"op":"replace","value":"MPLocation","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/fragments","value":[{"text":"MPLocation","kind":"identifier"}]},{"value":"iconUrl","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1iconUrl\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1iconUrl\/fragments","value":[{"text":"iconUrl","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1position\/title","value":"position","op":"replace"},{"value":[{"text":"position","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1position\/fragments"},{"value":"restrictions","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1restrictions\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1restrictions\/fragments","value":[{"kind":"identifier","text":"restrictions"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1coordinateBounds\/title","value":"coordinateBounds","op":"replace"},{"value":[{"text":"coordinateBounds","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1coordinateBounds\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/title","value":"MPBuilding"},{"value":[{"text":"MPBuilding","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/fragments"},{"value":"MPFloor","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor\/fragments","value":[{"text":"MPFloor","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1externalId\/title","value":"externalId"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1externalId\/fragments","value":[{"text":"externalId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1fields\/title","value":"fields","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1fields\/fragments","value":[{"kind":"identifier","text":"fields"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1venue\/title","value":"venue"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1venue\/fragments","op":"replace","value":[{"text":"venue","kind":"identifier"}]},{"op":"replace","value":"MPPoint","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPoint\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPoint\/fragments","value":[{"text":"MPPoint","kind":"identifier"}],"op":"replace"},{"value":"icon","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1icon\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1icon\/fragments","op":"replace","value":[{"kind":"identifier","text":"icon"}]},{"value":"building","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1building\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1building\/fragments","value":[{"text":"building","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1type\/title","value":"type","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1isBookable\/title","value":"isBookable","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1isBookable\/fragments","value":[{"kind":"identifier","text":"isBookable"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1baseType\/title","op":"replace","value":"baseType"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1baseType\/fragments","value":[{"kind":"identifier","text":"baseType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1imageURL\/title","value":"imageURL"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1imageURL\/fragments","value":[{"kind":"identifier","text":"imageURL"}],"op":"replace"},{"value":"locationId","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1locationId\/title"},{"value":[{"text":"locationId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1locationId\/fragments"},{"op":"replace","value":"geometry","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1geometry\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1geometry\/fragments","value":[{"text":"geometry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1floorName\/title","op":"replace","value":"floorName"},{"value":[{"text":"floorName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1floorName\/fragments","op":"replace"},{"value":"aliases","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1aliases\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1aliases\/fragments","value":[{"kind":"identifier","text":"aliases"}]},{"value":"floorIndex","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor~1floorIndex\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor~1floorIndex\/fragments","value":[{"text":"floorIndex","kind":"identifier"}]},{"value":"MPBookingService","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBookingService\/fragments","value":[{"text":"MPBookingService","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1categories\/title","value":"categories","op":"replace"},{"value":[{"kind":"identifier","text":"categories"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1categories\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1locationDescription\/title","value":"locationDescription"},{"value":[{"text":"locationDescription","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1locationDescription\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntity\/title","value":"MPEntity","op":"replace"},{"value":[{"text":"MPEntity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntity\/fragments"},{"value":"MPVenue","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/fragments","value":[{"text":"MPVenue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveValue(forKey:domainType:)\/title","value":"getLiveValueForKey:domainType:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveValue(forKey:domainType:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"getLiveValueForKey:domainType:","kind":"identifier"}]},{"value":"name","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1name\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1name\/fragments","op":"replace","value":[{"text":"name","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1floorIndex\/title","value":"floorIndex"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1floorIndex\/fragments","value":[{"kind":"identifier","text":"floorIndex"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}