{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationCoordinate3D"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Fields:"},{"type":"text","text":" "},{"type":"text","text":"latLng:"},{"type":"text","text":" "},{"type":"text","text":"The geographical location (latitude\/longitude( in degrees."},{"type":"text","text":" "},{"type":"text","text":"floorId:"},{"type":"text","text":" "},{"type":"text","text":"The id of the floor.  Additional information about the floor can be found in the solution\/building data."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationcoordinate3d"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationcoordinate3d"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A structure that contains a coordinate in 3D space: latitude\/longitude and floor."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationCoordinate3D"}],"title":"MPLocationCoordinate3D","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:@S@MPLocationCoordinate3D","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLocationCoordinate3D"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D\/init()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D\/init(latLng:floorId:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D\/floorId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D\/latLng"]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationCoordinate3D/latLng":{"role":"symbol","title":"latLng","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"latLng"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D\/latLng","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"latLng"}],"url":"\/documentation\/mapsindoors\/mplocationcoordinate3d\/latlng"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationCoordinate3D":{"role":"symbol","title":"MPLocationCoordinate3D","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationCoordinate3D"}],"abstract":[{"type":"text","text":"A structure that contains a coordinate in 3D space: latitude\/longitude and floor."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationCoordinate3D"}],"url":"\/documentation\/mapsindoors\/mplocationcoordinate3d"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationCoordinate3D/floorId":{"role":"symbol","title":"floorId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floorId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D\/floorId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floorId"}],"url":"\/documentation\/mapsindoors\/mplocationcoordinate3d\/floorid"},"doc://MapsIndoors/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/MapsIndoors\/s8SendableP"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationCoordinate3D/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D\/init()","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mplocationcoordinate3d\/init()"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationCoordinate3D/init(latLng:floorId:)":{"role":"symbol","title":"init(latLng:floorId:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"latLng"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"floorId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D\/init(latLng:floorId:)","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mplocationcoordinate3d\/init(latlng:floorid:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Structure"},{"op":"replace","path":"\/metadata\/title","value":"MPLocationCoordinate3D"},{"op":"replace","path":"\/metadata\/symbolKind","value":"struct"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLocationCoordinate3D"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPLocationCoordinate3D"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D\/floorId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D\/latLng"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationCoordinate3D"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationCoordinate3D~1latLng\/title","value":"latLng"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationCoordinate3D~1latLng\/fragments","value":[{"kind":"identifier","text":"latLng"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationCoordinate3D\/title","value":"MPLocationCoordinate3D"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationCoordinate3D\/fragments","value":[{"kind":"identifier","text":"MPLocationCoordinate3D"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationCoordinate3D~1floorId\/title","value":"floorId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationCoordinate3D~1floorId\/fragments","value":[{"kind":"identifier","text":"floorId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}