{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationDisplayRule"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationdisplayrule"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationdisplayrule"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)JSONModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)NSCopying","doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding","doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This class serves as a display rule for locations."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationDisplayRule"}],"title":"MPLocationDisplayRule","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPLocationDisplayRule","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLocationDisplayRule"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/init(name:AndIcon:AndZoomLevelOn:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/init(name:AndIconURL:AndZoomLevelOn:AndShowLabel:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/init(name:andIcon:andZoomLevelOn:andShowLabel:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/init(name:andZoomLevelOn:andShowLabel:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/clusteringId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/displayRank","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/highlightFillColor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/highlightOutlineColor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/highlightStrokeWidth","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/icon","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/iconPath","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/iconSize","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/label","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/labelMaxWidth","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/name","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/polygonFillColor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/polygonStrokeColor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/polygonStrokeWidth","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/showIcon","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/showLabel","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/showOutline","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/showPolygon","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/visible","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/zOff","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/zOffPolygon","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/zOn","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/zOnPolygon"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/fetchIcon(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/getLabelContent(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/show(_:)"]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/polygonStrokeColor":{"role":"symbol","title":"polygonStrokeColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonStrokeColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The stroke color of the polygon drawn on the map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/polygonStrokeColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"polygonStrokeColor"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/polygonstrokecolor"},"doc://MapsIndoors/objc(cs)JSONModel":{"type":"unresolvable","title":"JSONModel","identifier":"doc:\/\/MapsIndoors\/objc(cs)JSONModel"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/zOffPolygon":{"role":"symbol","title":"zOffPolygon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zOffPolygon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The map zoom level beneath which the location marker should be visible."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/zOffPolygon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"zOffPolygon"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/zoffpolygon"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/clusteringId":{"role":"symbol","title":"clusteringId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clusteringId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The grouping or clustering id of this displayrule."},{"type":"text","text":" "},{"type":"text","text":"MPLocations sharing the same clusteringId may be grouped on the map if necessary."},{"type":"text","text":" "},{"type":"text","text":"Default value is nil"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/clusteringId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clusteringId"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/clusteringid"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/polygonFillColor":{"role":"symbol","title":"polygonFillColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonFillColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The fill color of the polygon drawn on the map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/polygonFillColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"polygonFillColor"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/polygonfillcolor"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/showPolygon":{"role":"symbol","title":"showPolygon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showPolygon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"BOOL indicating if the locations polygon should be shown on the map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/showPolygon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showPolygon"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/showpolygon"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCopying"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/fetchIcon(_:)":{"role":"symbol","title":"fetchIcon(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchIcon"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Retrieve the icon from the ressources and store in memory."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/fetchIcon(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchIcon:"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/fetchicon(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/zOn":{"role":"symbol","title":"zOn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zOn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The map zoom level above which the location marker should be visible."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/zOn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"zOn"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/zon"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/visible":{"role":"symbol","title":"visible","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether or not to show the icon."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/visible","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"visible"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/visible"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Name\/identifier of the rule. Also used as the rule condition for the location types."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/name"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/show(_:)":{"role":"symbol","title":"show(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Processes the rule conditions at the given map zoom level."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/show(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"show:"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/show(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/init(name:andZoomLevelOn:andShowLabel:)":{"role":"symbol","title":"init(name:andZoomLevelOn:andShowLabel:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andZoomLevelOn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andShowLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Instantiate a display rule with parameters."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/init(name:andZoomLevelOn:andShowLabel:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithName:AndZoomLevelOn:AndShowLabel:"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/init(name:andzoomlevelon:andshowlabel:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/iconPath":{"role":"symbol","title":"iconPath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Relative path of the marker icon to use, without extension. Format is png."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/iconPath","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iconPath"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/iconpath"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/init(name:AndIconURL:AndZoomLevelOn:AndShowLabel:)":{"role":"symbol","title":"init(name:AndIconURL:AndZoomLevelOn:AndShowLabel:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"AndIconURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"AndZoomLevelOn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"AndShowLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Defered instantiate a display rule with parameters."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/init(name:AndIconURL:AndZoomLevelOn:AndShowLabel:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithName:AndIconURL:AndZoomLevelOn:AndShowLabel:"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/init(name:andiconurl:andzoomlevelon:andshowlabel:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/init(name:AndIcon:AndZoomLevelOn:)":{"role":"symbol","title":"init(name:AndIcon:AndZoomLevelOn:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"AndIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"AndZoomLevelOn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Instantiate a display rule with parameters."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/init(name:AndIcon:AndZoomLevelOn:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithName:AndIcon:AndZoomLevelOn:"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/init(name:andicon:andzoomlevelon:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/icon":{"role":"symbol","title":"icon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Ignore","preciseIdentifier":"c:objc(pl)Ignore"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The marker icon to use on markers that apply to the display rule."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/icon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"icon"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/icon"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/init(name:andIcon:andZoomLevelOn:andShowLabel:)":{"role":"symbol","title":"init(name:andIcon:andZoomLevelOn:andShowLabel:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andZoomLevelOn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andShowLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Instantiate a display rule with parameters."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/init(name:andIcon:andZoomLevelOn:andShowLabel:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithName:AndIcon:AndZoomLevelOn:AndShowLabel:"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/init(name:andicon:andzoomlevelon:andshowlabel:)"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/zOff":{"role":"symbol","title":"zOff","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zOff"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The map zoom level beneath which the location marker should be visible."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/zOff","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"zOff"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/zoff"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/objc(pl)AbstractJSONModelProtocol":{"type":"unresolvable","title":"JSONModel.AbstractJSONModelProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/highlightStrokeWidth":{"role":"symbol","title":"highlightStrokeWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightStrokeWidth"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The highlight stroke width."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/highlightStrokeWidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"highlightStrokeWidth"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/highlightstrokewidth"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule":{"role":"symbol","title":"MPLocationDisplayRule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationDisplayRule"}],"abstract":[{"type":"text","text":"This class serves as a display rule for locations."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationDisplayRule"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/labelMaxWidth":{"role":"symbol","title":"labelMaxWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"labelMaxWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Maximum width in points of the label shown on the map. If the text shown in the label"},{"type":"text","text":" "},{"type":"text","text":"(typically the location name) is longer than the labelMaxWidth the text will flow onto as many"},{"type":"text","text":" "},{"type":"text","text":"lines as needed."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/labelMaxWidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"labelMaxWidth"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/labelmaxwidth"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/showOutline":{"role":"symbol","title":"showOutline","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showOutline"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether or not to show an outline."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/showOutline","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showOutline"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/showoutline"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/polygonStrokeWidth":{"role":"symbol","title":"polygonStrokeWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonStrokeWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The stroke width of the polygon drawn on the map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/polygonStrokeWidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"polygonStrokeWidth"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/polygonstrokewidth"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/highlightFillColor":{"role":"symbol","title":"highlightFillColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightFillColor"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The highlight fill color."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/highlightFillColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"highlightFillColor"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/highlightfillcolor"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/label":{"role":"symbol","title":"label","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Label template for the resulting location marker - e.g. “{{name}}”, “{{roomId}}”, “Room #{{roomId}}” etc.."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/label","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"label"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/label"},"doc://MapsIndoors/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/iconSize":{"role":"symbol","title":"iconSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"Size of the icon image"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/iconSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iconSize"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/iconsize"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/showLabel":{"role":"symbol","title":"showLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether or not to show a text label. See label property"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/showLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showLabel"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/showlabel"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/showIcon":{"role":"symbol","title":"showIcon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether or not to show an icon."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/showIcon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showIcon"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/showicon"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/displayRank":{"role":"symbol","title":"displayRank","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayRank"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Display rank determines which POI (or group of POIs) will be displayed in case of conflicts \/ overlaps."},{"type":"text","text":" "},{"type":"text","text":"Higher ranks wins over lower."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/displayRank","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"displayRank"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/displayrank"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/highlightOutlineColor":{"role":"symbol","title":"highlightOutlineColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightOutlineColor"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The highlight outline color."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/highlightOutlineColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"highlightOutlineColor"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/highlightoutlinecolor"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/zOnPolygon":{"role":"symbol","title":"zOnPolygon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zOnPolygon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The map zoom level above which the location polygon should be visible."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/zOnPolygon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"zOnPolygon"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/zonpolygon"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationDisplayRule/getLabelContent(_:)":{"role":"symbol","title":"getLabelContent(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLabelContent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the label from the display rule, based on the location input."},{"type":"text","text":" "},{"type":"text","text":"- Returns: An string."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/getLabelContent(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getLabelContent:"}],"url":"\/documentation\/mapsindoors\/mplocationdisplayrule\/getlabelcontent(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPLocationDisplayRule"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLocationDisplayRule"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPLocationDisplayRule"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/clusteringId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/displayRank","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/highlightFillColor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/highlightOutlineColor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/highlightStrokeWidth","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/icon","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/iconPath","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/iconSize","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/label","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/labelMaxWidth","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/name","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/polygonFillColor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/polygonStrokeColor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/polygonStrokeWidth","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/showIcon","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/showLabel","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/showOutline","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/showPolygon","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/visible","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/zOff","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/zOffPolygon","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/zOn","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/zOnPolygon"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/fetchIcon(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/getLabelContent(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/init(name:AndIcon:AndZoomLevelOn:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/init(name:AndIconURL:AndZoomLevelOn:AndShowLabel:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/init(name:andIcon:andZoomLevelOn:andShowLabel:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/init(name:andZoomLevelOn:andShowLabel:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationDisplayRule\/show(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationDisplayRule"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSONModel","preciseIdentifier":"c:objc(cs)JSONModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1polygonStrokeColor\/title","value":"polygonStrokeColor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1polygonStrokeColor\/fragments","value":[{"kind":"identifier","text":"polygonStrokeColor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1zOffPolygon\/title","value":"zOffPolygon"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1zOffPolygon\/fragments","value":[{"kind":"identifier","text":"zOffPolygon"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1clusteringId\/title","value":"clusteringId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1clusteringId\/fragments","value":[{"kind":"identifier","text":"clusteringId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1polygonFillColor\/title","value":"polygonFillColor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1polygonFillColor\/fragments","value":[{"kind":"identifier","text":"polygonFillColor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1showPolygon\/title","value":"showPolygon"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1showPolygon\/fragments","value":[{"kind":"identifier","text":"showPolygon"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1fetchIcon(_:)\/title","value":"fetchIcon:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1fetchIcon(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchIcon:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1zOn\/title","value":"zOn"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1zOn\/fragments","value":[{"kind":"identifier","text":"zOn"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1visible\/title","value":"visible"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1visible\/fragments","value":[{"kind":"identifier","text":"visible"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1name\/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1show(_:)\/title","value":"show:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1show(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"show:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1init(name:andZoomLevelOn:andShowLabel:)\/title","value":"initWithName:AndZoomLevelOn:AndShowLabel:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1init(name:andZoomLevelOn:andShowLabel:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:AndZoomLevelOn:AndShowLabel:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1iconPath\/title","value":"iconPath"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1iconPath\/fragments","value":[{"kind":"identifier","text":"iconPath"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1init(name:AndIconURL:AndZoomLevelOn:AndShowLabel:)\/title","value":"initWithName:AndIconURL:AndZoomLevelOn:AndShowLabel:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1init(name:AndIconURL:AndZoomLevelOn:AndShowLabel:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:AndIconURL:AndZoomLevelOn:AndShowLabel:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1init(name:AndIcon:AndZoomLevelOn:)\/title","value":"initWithName:AndIcon:AndZoomLevelOn:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1init(name:AndIcon:AndZoomLevelOn:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:AndIcon:AndZoomLevelOn:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1icon\/title","value":"icon"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1icon\/fragments","value":[{"kind":"identifier","text":"icon"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1init(name:andIcon:andZoomLevelOn:andShowLabel:)\/title","value":"initWithName:AndIcon:AndZoomLevelOn:AndShowLabel:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1init(name:andIcon:andZoomLevelOn:andShowLabel:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:AndIcon:AndZoomLevelOn:AndShowLabel:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1zOff\/title","value":"zOff"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1zOff\/fragments","value":[{"kind":"identifier","text":"zOff"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1highlightStrokeWidth\/title","value":"highlightStrokeWidth"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1highlightStrokeWidth\/fragments","value":[{"kind":"identifier","text":"highlightStrokeWidth"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule\/title","value":"MPLocationDisplayRule"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule\/fragments","value":[{"kind":"identifier","text":"MPLocationDisplayRule"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1labelMaxWidth\/title","value":"labelMaxWidth"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1labelMaxWidth\/fragments","value":[{"kind":"identifier","text":"labelMaxWidth"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1showOutline\/title","value":"showOutline"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1showOutline\/fragments","value":[{"kind":"identifier","text":"showOutline"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1polygonStrokeWidth\/title","value":"polygonStrokeWidth"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1polygonStrokeWidth\/fragments","value":[{"kind":"identifier","text":"polygonStrokeWidth"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1highlightFillColor\/title","value":"highlightFillColor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1highlightFillColor\/fragments","value":[{"kind":"identifier","text":"highlightFillColor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1label\/title","value":"label"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1label\/fragments","value":[{"kind":"identifier","text":"label"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1iconSize\/title","value":"iconSize"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1iconSize\/fragments","value":[{"kind":"identifier","text":"iconSize"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1showLabel\/title","value":"showLabel"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1showLabel\/fragments","value":[{"kind":"identifier","text":"showLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1showIcon\/title","value":"showIcon"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1showIcon\/fragments","value":[{"kind":"identifier","text":"showIcon"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1displayRank\/title","value":"displayRank"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1displayRank\/fragments","value":[{"kind":"identifier","text":"displayRank"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1highlightOutlineColor\/title","value":"highlightOutlineColor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1highlightOutlineColor\/fragments","value":[{"kind":"identifier","text":"highlightOutlineColor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1zOnPolygon\/title","value":"zOnPolygon"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1zOnPolygon\/fragments","value":[{"kind":"identifier","text":"zOnPolygon"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1getLabelContent(_:)\/title","value":"getLabelContent:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationDisplayRule~1getLabelContent(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLabelContent:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}