{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLoadIndicator"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mploadindicator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mploadindicator"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A basic load indicator, with the option to set a text."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLoadIndicator"}],"title":"MPLoadIndicator","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPLoadIndicator","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLoadIndicator"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/init(onView:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/init(onView:withText:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/indicatorView","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/parentView","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/textView"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/start()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/stop()"]}],"references":{"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(cs)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPLoadIndicator/start()":{"role":"symbol","title":"start()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Start and show the indicator animation"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/start()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"start"}],"url":"\/documentation\/mapsindoors\/mploadindicator\/start()"},"doc://MapsIndoors/documentation/MapsIndoors/MPLoadIndicator/init(onView:)":{"role":"symbol","title":"init(onView:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"onView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Instantiates the indicator and places the indicator in a view."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/init(onView:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initOnView:"}],"url":"\/documentation\/mapsindoors\/mploadindicator\/init(onview:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPLoadIndicator/init(onView:withText:)":{"role":"symbol","title":"init(onView:withText:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"onView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Instantiates the indicator and places the indicator in a view with a given text."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/init(onView:withText:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initOnView:withText:"}],"url":"\/documentation\/mapsindoors\/mploadindicator\/init(onview:withtext:)"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MPLoadIndicator/parentView":{"role":"symbol","title":"parentView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"View holding the load indicator."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/parentView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parentView"}],"url":"\/documentation\/mapsindoors\/mploadindicator\/parentview"},"doc://MapsIndoors/documentation/MapsIndoors/MPLoadIndicator/textView":{"role":"symbol","title":"textView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The text view"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/textView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textView"}],"url":"\/documentation\/mapsindoors\/mploadindicator\/textview"},"doc://MapsIndoors/documentation/MapsIndoors/MPLoadIndicator":{"role":"symbol","title":"MPLoadIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLoadIndicator"}],"abstract":[{"type":"text","text":"A basic load indicator, with the option to set a text."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLoadIndicator"}],"url":"\/documentation\/mapsindoors\/mploadindicator"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPLoadIndicator/stop()":{"role":"symbol","title":"stop()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stop and hide the indicator animation"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/stop()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stop"}],"url":"\/documentation\/mapsindoors\/mploadindicator\/stop()"},"doc://MapsIndoors/documentation/MapsIndoors/MPLoadIndicator/indicatorView":{"role":"symbol","title":"indicatorView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"indicatorView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivityIndicatorView","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The indicator view."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/indicatorView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"indicatorView"}],"url":"\/documentation\/mapsindoors\/mploadindicator\/indicatorview"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPLoadIndicator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLoadIndicator"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPLoadIndicator"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/indicatorView","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/parentView","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/textView"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/init(onView:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/init(onView:withText:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/start()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLoadIndicator\/stop()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLoadIndicator"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator~1start()\/title","value":"start"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator~1start()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"start"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator~1init(onView:)\/title","value":"initOnView:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator~1init(onView:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initOnView:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator~1init(onView:withText:)\/title","value":"initOnView:withText:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator~1init(onView:withText:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initOnView:withText:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator~1parentView\/title","value":"parentView"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator~1parentView\/fragments","value":[{"kind":"identifier","text":"parentView"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator~1textView\/title","value":"textView"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator~1textView\/fragments","value":[{"kind":"identifier","text":"textView"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator\/title","value":"MPLoadIndicator"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator\/fragments","value":[{"kind":"identifier","text":"MPLoadIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator~1stop()\/title","value":"stop"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator~1stop()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stop"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator~1indicatorView\/title","value":"indicatorView"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLoadIndicator~1indicatorView\/fragments","value":[{"kind":"identifier","text":"indicatorView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}