{"sections":[],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"MPLog","symbolKind":"class","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPLog","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPLog","modules":[{"name":"MapsIndoors"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPLog"}]},"abstract":[{"text":"The logger used internally by MapsIndoors.","type":"text"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/mapsindoors\/mplog"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplog"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(MPLog) ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPLog","kind":"identifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The logging uses "},{"identifier":"https:\/\/developer.apple.com\/documentation\/os\/logging\/generating_log_messages_from_your_code#3665947","type":"reference","isActive":true},{"text":", so the log levels are the ones described there.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"You should only need to change the "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/logLevel","isActive":true},{"text":" if instructed by MapsPeople support.","type":"text"}]}]}],"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/debug(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/error(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/fault(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/info(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/notice(_:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/core","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/google","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/logLevel","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/mapbox","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/mapsindoors"],"title":"Type Properties"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLog/error(_:)":{"title":"error(_:)","navigatorTitle":[{"text":"error:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/error(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mplog\/error(_:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLog/info(_:)":{"title":"info(_:)","navigatorTitle":[{"text":"info:","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/info(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mplog\/info(_:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLog/mapsindoors":{"title":"mapsindoors","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/mapsindoors","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapsindoors","kind":"identifier"},{"kind":"text","text":": "},{"text":"MPLog","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLog"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mplog\/mapsindoors","role":"symbol"},"doc://com.mapspeople.mapsindoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLog/mapbox":{"title":"mapbox","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/mapbox","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapbox","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLog","kind":"typeIdentifier","text":"MPLog"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mplog\/mapbox","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLog/debug(_:)":{"title":"debug(_:)","navigatorTitle":[{"kind":"identifier","text":"debug:"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/debug(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mplog\/debug(_:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLog/core":{"title":"core","navigatorTitle":[{"kind":"identifier","text":"core"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/core","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"core","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLog","kind":"typeIdentifier","text":"MPLog"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mplog\/core","role":"symbol"},"MapsPeopleWhite.png":{"type":"image","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLog/logLevel":{"title":"logLevel","navigatorTitle":[{"kind":"identifier","text":"logLevel"}],"type":"topic","abstract":[{"type":"text","text":"Set the log level for MapsIndoors. Defaults to "},{"type":"codeVoice","code":"debug"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/logLevel","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OSLogType","preciseIdentifier":"c:@EA@os_log_type_t"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mplog\/loglevel","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLog/google":{"title":"google","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/google","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"google","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPLog","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLog"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mplog\/google","role":"symbol"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLog/fault(_:)":{"title":"fault(_:)","url":"\/documentation\/mapsindoors\/mplog\/fault(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"fault:"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fault","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/fault(_:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLog/notice(_:)":{"title":"notice(_:)","navigatorTitle":[{"kind":"identifier","text":"notice:"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/notice(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notice","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mplog\/notice(_:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/SQ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLog":{"title":"MPLog","url":"\/documentation\/mapsindoors\/mplog","abstract":[{"type":"text","text":"The logger used internally by MapsIndoors."}],"navigatorTitle":[{"kind":"identifier","text":"MPLog"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPLog","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog"},"doc://com.mapspeople.mapsindoors/SH":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable","type":"unresolvable"},"https://developer.apple.com/documentation/os/logging/generating_log_messages_from_your_code#3665947":{"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/os\/logging\/generating_log_messages_from_your_code#3665947","url":"https:\/\/developer.apple.com\/documentation\/os\/logging\/generating_log_messages_from_your_code#3665947","title":"Unified Logging","titleInlineContent":[{"text":"Unified Logging","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"MPLog","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MPLog","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MPLog","kind":"identifier"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/debug(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/error(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/fault(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/info(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/notice(_:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/core","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLog\/logLevel"],"title":"Type Properties"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"MPLog","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"error:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog~1error(_:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog~1error(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"error:","kind":"identifier"}],"op":"replace"},{"value":"info:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog~1info(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog~1info(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"info:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog~1debug(_:)\/title","value":"debug:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog~1debug(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"debug:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog~1core\/title","value":"core","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog~1core\/fragments","value":[{"text":"core","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog~1logLevel\/title","value":"logLevel"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog~1logLevel\/fragments","value":[{"kind":"identifier","text":"logLevel"}],"op":"replace"},{"op":"replace","value":"fault:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog~1fault(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"fault:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog~1fault(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog~1notice(_:)\/title","op":"replace","value":"notice:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"notice:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog~1notice(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog\/title","op":"replace","value":"MPLog"},{"op":"replace","value":[{"kind":"identifier","text":"MPLog"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLog\/fragments"}]}]}