{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdateFactory","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"MapsIndoors"}],"roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPLocationUpdateFactory"}],"title":"MPLocationUpdateFactory","externalID":"c:@M@MapsIndoors@objc(pl)MPLocationUpdateFactory","navigatorTitle":[{"kind":"identifier","text":"MPLocationUpdateFactory"}]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdateFactory\/updateWithId(locationId:fromSource:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdateFactory\/updateWithLocation(location:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mplocationupdatefactory"]},{"paths":["\/documentation\/mapsindoors\/mplocationupdatefactory"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationUpdateFactory"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Protocol  to create instance of "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate","isActive":true,"type":"reference"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationUpdateFactory/updateWithId(locationId:fromSource:)":{"abstract":[],"role":"symbol","kind":"symbol","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdateFactory\/updateWithId(locationId:fromSource:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateWithId"},{"kind":"text","text":"("},{"kind":"externalParam","text":"locationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"fromSource","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPLocationSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationSource"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationUpdate","kind":"typeIdentifier","text":"MPLocationUpdate"}],"title":"updateWithId(locationId:fromSource:)","url":"\/documentation\/mapsindoors\/mplocationupdatefactory\/updatewithid(locationid:fromsource:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateWithId:fromSource:"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationUpdate":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationUpdate"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate","title":"MPLocationUpdate","url":"\/documentation\/mapsindoors\/mplocationupdate","type":"topic","navigatorTitle":[{"text":"MPLocationUpdate","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationUpdateFactory":{"abstract":[{"type":"text","text":"Protocol  to create instance of "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate","isActive":true}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPLocationUpdateFactory","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdateFactory","title":"MPLocationUpdateFactory","url":"\/documentation\/mapsindoors\/mplocationupdatefactory","type":"topic","navigatorTitle":[{"text":"MPLocationUpdateFactory","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationUpdateFactory/updateWithLocation(location:)":{"abstract":[],"role":"symbol","kind":"symbol","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdateFactory\/updateWithLocation(location:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateWithLocation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"location"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","text":"MPLocation","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationUpdate","kind":"typeIdentifier","text":"MPLocationUpdate"}],"title":"updateWithLocation(location:)","url":"\/documentation\/mapsindoors\/mplocationupdatefactory\/updatewithlocation(location:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateWithLocation:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MPLocationUpdateFactory"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MPLocationUpdateFactory"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPLocationUpdateFactory"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdateFactory\/updateWithId(locationId:fromSource:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdateFactory\/updateWithLocation(location:)"]}]},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"MPLocationUpdateFactory","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"updateWithId:fromSource:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdateFactory~1updateWithId(locationId:fromSource:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"updateWithId:fromSource:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdateFactory~1updateWithId(locationId:fromSource:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdate\/title","value":"MPLocationUpdate","op":"replace"},{"value":[{"text":"MPLocationUpdate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdateFactory\/title","value":"MPLocationUpdateFactory"},{"value":[{"text":"MPLocationUpdateFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdateFactory\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdateFactory~1updateWithLocation(location:)\/title","value":"updateWithLocation:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdateFactory~1updateWithLocation(location:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateWithLocation:"}],"op":"replace"}]}]}