{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationServiceDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationservicedelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationservicedelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationServiceDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This delegate informs about the status of loading the Locations of the current"},{"type":"text","text":" "},{"type":"text","text":"Solution."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationServiceDelegate"}],"title":"MPLocationServiceDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)MPLocationServiceDelegate","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLocationServiceDelegate"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationServiceDelegate\/locationsReady()"]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationServiceDelegate/locationsReady()":{"navigatorTitle":[{"kind":"identifier","text":"locationsReady"}],"role":"symbol","title":"locationsReady()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationsReady"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This method on the delegate is invoked when the Locations in the current"},{"type":"text","text":" "},{"type":"text","text":"Solution are all loaded and ready to be worked with, e.g. search in them."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationServiceDelegate\/locationsReady()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationservicedelegate\/locationsready()"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationServiceDelegate":{"role":"symbol","title":"MPLocationServiceDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationServiceDelegate"}],"abstract":[{"type":"text","text":"This delegate informs about the status of loading the Locations of the current"},{"type":"text","text":" "},{"type":"text","text":"Solution."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationServiceDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationServiceDelegate"}],"url":"\/documentation\/mapsindoors\/mplocationservicedelegate"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPLocationServiceDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLocationServiceDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPLocationServiceDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationServiceDelegate\/locationsReady()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationServiceDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationServiceDelegate~1locationsReady()\/title","value":"locationsReady"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationServiceDelegate~1locationsReady()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationsReady"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationServiceDelegate\/title","value":"MPLocationServiceDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationServiceDelegate\/fragments","value":[{"kind":"identifier","text":"MPLocationServiceDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}