{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLocationField","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationfield"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mplocationfield"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationFieldCodable"],"title":"Conforming Types","type":"conformingTypes"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationField"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"metadata":{"role":"symbol","roleHeading":"Protocol","symbolKind":"protocol","title":"MPLocationField","modules":[{"name":"MapsIndoors"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationField"}],"navigatorTitle":[{"text":"MPLocationField","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPLocationField"},"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationField\/text","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationField\/type","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationField\/value"],"title":"Instance Properties"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationField/text":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationField\/text","navigatorTitle":[{"text":"text","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mplocationfield\/text","role":"symbol","required":true,"title":"text"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationField/type":{"role":"symbol","url":"\/documentation\/mapsindoors\/mplocationfield\/type","type":"topic","navigatorTitle":[{"text":"type","kind":"identifier"}],"kind":"symbol","required":true,"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationField\/type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"type"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationField":{"navigatorTitle":[{"kind":"identifier","text":"MPLocationField"}],"title":"MPLocationField","url":"\/documentation\/mapsindoors\/mplocationfield","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationField","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLocationField","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationField/value":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationField\/value","required":true,"url":"\/documentation\/mapsindoors\/mplocationfield\/value","navigatorTitle":[{"text":"value","kind":"identifier"}],"title":"value","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"value","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationFieldCodable":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationFieldCodable","url":"\/documentation\/mapsindoors\/mplocationfieldcodable","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPLocationFieldCodable","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"MPLocationFieldCodable","navigatorTitle":[{"text":"MPLocationFieldCodable","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPLocationField"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"value":[{"text":"MPLocationField","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPLocationField"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationField\/text","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationField\/type","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationField\/value"]}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationField"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"text","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationField~1text\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationField~1text\/fragments","value":[{"text":"text","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationField~1type\/title","op":"replace","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationField~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationField\/title","value":"MPLocationField"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationField\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPLocationField"}]},{"value":"value","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationField~1value\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationField~1value\/fragments","value":[{"kind":"identifier","text":"value"}]}]}]}