{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationUpdate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationupdate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationupdate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Location Update \/ Builder class"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationUpdate"}],"title":"MPLocationUpdate","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPLocationUpdate","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLocationUpdate"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/init(id:fromSource:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/init(location:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/floor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/icon","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/iconMapAnchor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/iconUrl","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/locationId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/name","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/position","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/sourceId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/addCategory(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/addPropertyValue(_:forKey:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/location()"]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate/locationId":{"role":"symbol","title":"locationId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The id of the Location. This id is not unique across multiple location sources."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/locationId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"locationId"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/locationid"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate/init(id:fromSource:)":{"role":"symbol","title":"init(id:fromSource:)","fragments":[{"kind":"text","text":"\/*not inherited*\/ "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationSource","preciseIdentifier":"c:objc(pl)MPLocationSource"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialiser that creates a MPLocationUpdate instance based on an id and a location source."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/init(id:fromSource:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateWithId:fromSource:"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/init(id:fromsource:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate/iconUrl":{"role":"symbol","title":"iconUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"abstract":[{"type":"text","text":"Location icon as a URL. If icon is set as a UIImage, this property will be ignored."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/iconUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iconUrl"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/iconurl"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate/addPropertyValue(_:forKey:)":{"role":"symbol","title":"addPropertyValue(_:forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addPropertyValue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Adds a property to the location update. Some keys will be recognised as a key for a known property on the resulting "},{"type":"codeVoice","code":"MPLocation"},{"type":"text","text":". If they are not recognised or the known property only supports one value, the property will be added as a field on "},{"type":"codeVoice","code":"MPLocation.fields"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/addPropertyValue(_:forKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addPropertyValue:forKey:"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/addpropertyvalue(_:forkey:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate/init(location:)":{"role":"symbol","title":"init(location:)","fragments":[{"kind":"text","text":"\/*not inherited*\/ "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialiser that creates a MPLocationUpdate instance based on an existing location."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/init(location:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateWithLocation:"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/init(location:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate/floor":{"role":"symbol","title":"floor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The floor index of the Location. Must be set to a valid floor index. If unknown, these can be seen in MapsIndoors CMS."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/floor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floor"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/floor"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate":{"role":"symbol","title":"MPLocationUpdate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationUpdate"}],"abstract":[{"type":"text","text":"Location Update \/ Builder class"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationUpdate"}],"url":"\/documentation\/mapsindoors\/mplocationupdate"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The type of the Location."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/type"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate/position":{"role":"symbol","title":"position","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"abstract":[{"type":"text","text":"The geographical position of the Location."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/position","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"position"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/position"},"doc://MapsIndoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(cs)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The name of the Location."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/name"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate/iconMapAnchor":{"role":"symbol","title":"iconMapAnchor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconMapAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"}],"abstract":[{"type":"text","text":"Icon map anchor specifies the point in the icon image that is anchored to the marker’s position on the Earth’s surface. E.g. point 0.5, 0.5 is the middle of the image."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/iconMapAnchor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iconMapAnchor"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/iconmapanchor"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate/icon":{"role":"symbol","title":"icon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"abstract":[{"type":"text","text":"Location icon. If not set, the location will either get an icon from the settings configured for the type of location or a default appearance that is configurable through "},{"type":"codeVoice","code":"MPMapControl"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/icon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"icon"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/icon"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate/sourceId":{"role":"symbol","title":"sourceId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The id of the Location Source where this location was created"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/sourceId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sourceId"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/sourceid"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate/addCategory(_:)":{"role":"symbol","title":"addCategory(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCategory"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Add category key. Possible categories can be reviewed in MapsIndoors CMS or programmatically using the "},{"type":"codeVoice","code":"MPCategoriesProvider"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/addCategory(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addCategory:"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/addcategory(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationUpdate/location()":{"role":"symbol","title":"location()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"location"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MPLocation","preciseIdentifier":"c:objc(cs)MPLocation"}],"abstract":[{"type":"text","text":"Builds the location object. Should only be called once per intended location instance."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/location()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"location"}],"url":"\/documentation\/mapsindoors\/mplocationupdate\/location()"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPLocationUpdate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLocationUpdate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPLocationUpdate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/floor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/icon","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/iconMapAnchor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/iconUrl","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/locationId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/name","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/position","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/sourceId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/addCategory(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/addPropertyValue(_:forKey:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/location()"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/init(id:fromSource:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationUpdate\/init(location:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationUpdate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1locationId\/title","value":"locationId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1locationId\/fragments","value":[{"kind":"identifier","text":"locationId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1init(id:fromSource:)\/title","value":"updateWithId:fromSource:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1init(id:fromSource:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"updateWithId:fromSource:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1iconUrl\/title","value":"iconUrl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1iconUrl\/fragments","value":[{"kind":"identifier","text":"iconUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1addPropertyValue(_:forKey:)\/title","value":"addPropertyValue:forKey:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1addPropertyValue(_:forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addPropertyValue:forKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1init(location:)\/title","value":"updateWithLocation:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1init(location:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"updateWithLocation:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1floor\/title","value":"floor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1floor\/fragments","value":[{"kind":"identifier","text":"floor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate\/title","value":"MPLocationUpdate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate\/fragments","value":[{"kind":"identifier","text":"MPLocationUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1position\/title","value":"position"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1position\/fragments","value":[{"kind":"identifier","text":"position"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1name\/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1iconMapAnchor\/title","value":"iconMapAnchor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1iconMapAnchor\/fragments","value":[{"kind":"identifier","text":"iconMapAnchor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1icon\/title","value":"icon"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1icon\/fragments","value":[{"kind":"identifier","text":"icon"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1sourceId\/title","value":"sourceId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1sourceId\/fragments","value":[{"kind":"identifier","text":"sourceId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1addCategory(_:)\/title","value":"addCategory:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1addCategory(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCategory:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1location()\/title","value":"location"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationUpdate~1location()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"location"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}