{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpLocationsHandlerBlockType"},{"kind":"text","text":" = (["},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","preciseIdentifier":"c:objc(cs)MPLocation","text":"MPLocation"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"locations","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Locations result array"}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error object"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationshandlerblocktype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationshandlerblocktype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpLocationsHandlerBlockType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Handler block for a locations query"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpLocationsHandlerBlockType"}],"title":"mpLocationsHandlerBlockType","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias","externalID":"c:MPLocationService.h@T@mpLocationsHandlerBlockType","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"mpLocationsHandlerBlockType"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/mpLocationsHandlerBlockType":{"role":"symbol","title":"mpLocationsHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpLocationsHandlerBlockType"}],"abstract":[{"type":"text","text":"Handler block for a locations query"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpLocationsHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpLocationsHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mplocationshandlerblocktype"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocation-swift.class":{"role":"symbol","title":"MPLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocation"}],"abstract":[{"type":"text","text":"This class holds the data for a single location and a marker to display the data on a map."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"url":"\/documentation\/mapsindoors\/mplocation-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"mpLocationsHandlerBlockType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mpLocationsHandlerBlockType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"mpLocationsHandlerBlockType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(NSArray<MPLocation *> *, NSError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpLocationsHandlerBlockType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpLocationsHandlerBlockType\/title","value":"mpLocationsHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpLocationsHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpLocationsHandlerBlockType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/title","value":"MPLocation"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocation-swift.class\/fragments","value":[{"kind":"identifier","text":"MPLocation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}