{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationsProviderProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationsproviderprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationsproviderprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProvider-swift.class"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Locations provider protocol."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationsProviderProtocol"}],"title":"MPLocationsProviderProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)MPLocationsProvider","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLocationsProviderProtocol"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationDetailsAsync(_:withId:language:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationDetailsAsync(_:withId:language:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationWithId(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationWithId(_:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocations()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsAsync(_:language:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsAsync(_:language:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsUsing(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsUsing(_:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsUsingQueryAsync(_:language:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsUsingQueryAsync(_:language:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsWithCompletion(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsWithIds(_:completionHandler:)"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/isOfflineDataAvailable(forSolutionId:language:)"]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/getLocationsAsync(_:language:)":{"navigatorTitle":[{"kind":"identifier","text":"getLocationsAsync:language:"}],"deprecated":true,"role":"symbol","title":"getLocationsAsync(_:language:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationsAsync"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method to initiate fetching of all locations from the provider in a specific translation."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsAsync(_:language:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocationsasync(_:language:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/getLocationsUsing(_:completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"getLocationsUsingQuery:completionHandler:"}],"role":"symbol","title":"getLocationsUsing(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationsUsing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocationQuery","preciseIdentifier":"c:objc(cs)MPLocationQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpLocationListHandlerBlockType","preciseIdentifier":"c:MPLocationsProvider.h@T@mpLocationListHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Method to query a subset of locations from the provider."},{"type":"text","text":" "},{"type":"text","text":"Data is returned in the current translation ([MapsIndoors getLanguage])."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsUsing(_:completionHandler:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocationsusing(_:completionhandler:)"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/getLocationsUsingQueryAsync(_:language:)":{"navigatorTitle":[{"kind":"identifier","text":"getLocationsUsingQueryAsync:language:"}],"deprecated":true,"role":"symbol","title":"getLocationsUsingQueryAsync(_:language:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationsUsingQueryAsync"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocationQuery","preciseIdentifier":"c:objc(cs)MPLocationQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method to query a subset of locations from the provider."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsUsingQueryAsync(_:language:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocationsusingqueryasync(_:language:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/getLocationsUsingQueryAsync(_:language:completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"getLocationsUsingQueryAsync:language:completionHandler:"}],"deprecated":true,"role":"symbol","title":"getLocationsUsingQueryAsync(_:language:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationsUsingQueryAsync"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocationQuery","preciseIdentifier":"c:objc(cs)MPLocationQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpLocationListHandlerBlockType","preciseIdentifier":"c:MPLocationsProvider.h@T@mpLocationListHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Method to query a subset of locations from the provider."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsUsingQueryAsync(_:language:completionHandler:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocationsusingqueryasync(_:language:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/getLocationWithId(_:completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"getLocationWithId:completionHandler:"}],"role":"symbol","title":"getLocationWithId(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationWithId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpLocationDetailsHandlerBlockType","preciseIdentifier":"c:MPLocationsProvider.h@T@mpLocationDetailsHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Method to query a unique location from the provider based on an id."},{"type":"text","text":" "},{"type":"text","text":"Data is returned in the current translation ([MapsIndoors getLanguage])."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationWithId(_:completionHandler:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocationwithid(_:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/getLocationDetailsAsync(_:withId:language:)":{"navigatorTitle":[{"kind":"identifier","text":"getLocationDetailsAsync:withId:language:"}],"deprecated":true,"role":"symbol","title":"getLocationDetailsAsync(_:withId:language:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationDetailsAsync"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method to query a unique location from the provider based on an id."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationDetailsAsync(_:withId:language:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocationdetailsasync(_:withid:language:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol":{"role":"symbol","title":"MPLocationsProviderProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationsProviderProtocol"}],"abstract":[{"type":"text","text":"Locations provider protocol."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationsProviderProtocol"}],"url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProvider-swift.class":{"deprecated":true,"role":"symbol","title":"MPLocationsProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationsProvider"}],"abstract":[{"type":"text","text":"Locations provider that defines a delegate and a method to initiate fetching of locations from the provider."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProvider-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationsProvider"}],"url":"\/documentation\/mapsindoors\/mplocationsprovider-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/getLocationDetailsAsync(_:withId:language:completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"getLocationDetailsAsync:withId:language:completionHandler:"}],"deprecated":true,"role":"symbol","title":"getLocationDetailsAsync(_:withId:language:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationDetailsAsync"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpLocationDetailsHandlerBlockType","preciseIdentifier":"c:MPLocationsProvider.h@T@mpLocationDetailsHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Method to query a unique location from the provider based on an id."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationDetailsAsync(_:withId:language:completionHandler:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocationdetailsasync(_:withid:language:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/getLocations()":{"navigatorTitle":[{"kind":"identifier","text":"getLocations"}],"role":"symbol","title":"getLocations()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocations"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Method to initiate fetching of all locations from the provider in the current translation ([MapsIndoors getLanguage])."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocations()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocations()"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/getLocationsWithCompletion(_:)":{"navigatorTitle":[{"kind":"identifier","text":"getLocationsWithCompletion:"}],"role":"symbol","title":"getLocationsWithCompletion(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationsWithCompletion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpLocationListHandlerBlockType","preciseIdentifier":"c:MPLocationsProvider.h@T@mpLocationListHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Method to initiate fetching of all locations from the provider in the current translation ([MapsIndoors getLanguage])."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsWithCompletion(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocationswithcompletion(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/isOfflineDataAvailable(forSolutionId:language:)":{"navigatorTitle":[{"kind":"identifier","text":"isOfflineDataAvailableForSolutionId:language:"}],"role":"symbol","title":"isOfflineDataAvailable(forSolutionId:language:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOfflineDataAvailable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSolutionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determine if cached or preloaded data is available for the given solutionId."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/isOfflineDataAvailable(forSolutionId:language:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/isofflinedataavailable(forsolutionid:language:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/delegate":{"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPLocationsProviderDelegate","preciseIdentifier":"c:objc(pl)MPLocationsProviderDelegate"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/delegate","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/delegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/getLocationsAsync(_:language:completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"getLocationsAsync:language:completionHandler:"}],"deprecated":true,"role":"symbol","title":"getLocationsAsync(_:language:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationsAsync"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpLocationListHandlerBlockType","preciseIdentifier":"c:MPLocationsProvider.h@T@mpLocationListHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Method to initiate fetching of all locations from the provider in a specific translation."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsAsync(_:language:completionHandler:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocationsasync(_:language:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/getLocationsWithIds(_:completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"getLocationsWithIds:completionHandler:"}],"role":"symbol","title":"getLocationsWithIds(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationsWithIds"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpLocationListHandlerBlockType","preciseIdentifier":"c:MPLocationsProvider.h@T@mpLocationListHandlerBlockType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method to query for a batch of locations given their ids."},{"type":"text","text":" "},{"type":"text","text":"Data is returned in the current translation ([MapsIndoors getLanguage])."},{"type":"text","text":" "},{"type":"text","text":"The order of the returned locations is indeterminate, and not in the order of the locationIds parameter."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsWithIds(_:completionHandler:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocationswithids(_:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/getLocationWithId(_:)":{"navigatorTitle":[{"kind":"identifier","text":"getLocationWithId:"}],"role":"symbol","title":"getLocationWithId(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationWithId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method to query a unique location from the provider based on an id."},{"type":"text","text":" "},{"type":"text","text":"Data is returned in the current translation ([MapsIndoors getLanguage])."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationWithId(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocationwithid(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationsProviderProtocol/getLocationsUsing(_:)":{"navigatorTitle":[{"kind":"identifier","text":"getLocationsUsingQuery:"}],"role":"symbol","title":"getLocationsUsing(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationsUsing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocationQuery","preciseIdentifier":"c:objc(cs)MPLocationQuery"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method to query a subset of locations from the provider."},{"type":"text","text":" "},{"type":"text","text":"Data is returned in the current translation ([MapsIndoors getLanguage])."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsUsing(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationsproviderprotocol\/getlocationsusing(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPLocationsProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLocationsProvider"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPLocationsProvider"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationDetailsAsync(_:withId:language:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationDetailsAsync(_:withId:language:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationWithId(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationWithId(_:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocations()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsAsync(_:language:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsAsync(_:language:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsUsing(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsUsing(_:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsUsingQueryAsync(_:language:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsUsingQueryAsync(_:language:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsWithCompletion(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/getLocationsWithIds(_:completionHandler:)"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProviderProtocol\/isOfflineDataAvailable(forSolutionId:language:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationsProvider-swift.class"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationsProvider"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationsAsync(_:language:)\/title","value":"getLocationsAsync:language:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationsAsync(_:language:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationsAsync:language:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationsUsing(_:completionHandler:)\/title","value":"getLocationsUsingQuery:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationsUsing(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationsUsingQuery:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationsUsingQueryAsync(_:language:)\/title","value":"getLocationsUsingQueryAsync:language:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationsUsingQueryAsync(_:language:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationsUsingQueryAsync:language:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationsUsingQueryAsync(_:language:completionHandler:)\/title","value":"getLocationsUsingQueryAsync:language:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationsUsingQueryAsync(_:language:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationsUsingQueryAsync:language:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationWithId(_:completionHandler:)\/title","value":"getLocationWithId:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationWithId(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationWithId:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationDetailsAsync(_:withId:language:)\/title","value":"getLocationDetailsAsync:withId:language:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationDetailsAsync(_:withId:language:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationDetailsAsync:withId:language:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol\/title","value":"MPLocationsProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol\/fragments","value":[{"kind":"identifier","text":"MPLocationsProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProvider-swift.class\/title","value":"MPLocationsProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProvider-swift.class\/fragments","value":[{"kind":"identifier","text":"MPLocationsProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationDetailsAsync(_:withId:language:completionHandler:)\/title","value":"getLocationDetailsAsync:withId:language:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationDetailsAsync(_:withId:language:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationDetailsAsync:withId:language:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocations()\/title","value":"getLocations"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocations()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocations"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationsWithCompletion(_:)\/title","value":"getLocationsWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationsWithCompletion(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationsWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1isOfflineDataAvailable(forSolutionId:language:)\/title","value":"isOfflineDataAvailableForSolutionId:language:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1isOfflineDataAvailable(forSolutionId:language:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isOfflineDataAvailableForSolutionId:language:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationsAsync(_:language:completionHandler:)\/title","value":"getLocationsAsync:language:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationsAsync(_:language:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationsAsync:language:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationsWithIds(_:completionHandler:)\/title","value":"getLocationsWithIds:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationsWithIds(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationsWithIds:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationWithId(_:)\/title","value":"getLocationWithId:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationWithId(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationWithId:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationsUsing(_:)\/title","value":"getLocationsUsingQuery:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationsProviderProtocol~1getLocationsUsing(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationsUsingQuery:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}