{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationBaseType"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH","doc:\/\/com.mapspeople.mapsindoors\/SY"],"type":"conformsTo","title":"Conforms To"}],"metadata":{"roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","navigatorTitle":[{"text":"MPLocationBaseType","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@E@MPLocationBaseType","modules":[{"name":"MapsIndoors"}],"title":"MPLocationBaseType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPLocationBaseType"}]},"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/area","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/building","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/floor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/pointOfInterest","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/room","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/venue"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/Equatable-Implementations","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationbasetype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mplocationbasetype"]}],"references":{"doc://com.mapspeople.mapsindoors/SQ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapspeople.mapsindoors/SE":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationBaseType/pointOfInterest":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPLocationBaseTypePointOfInterest"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/pointOfInterest","url":"\/documentation\/mapsindoors\/mplocationbasetype\/pointofinterest","title":"MPLocationBaseType.pointOfInterest","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"pointOfInterest","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationBaseType/area":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPLocationBaseTypeArea"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/area","url":"\/documentation\/mapsindoors\/mplocationbasetype\/area","title":"MPLocationBaseType.area","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"area"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationBaseType/floor":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mplocationbasetype\/floor","role":"symbol","navigatorTitle":[{"text":"MPLocationBaseTypeFloor","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"floor","kind":"identifier"}],"abstract":[],"title":"MPLocationBaseType.floor","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/floor"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationBaseType/building":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPLocationBaseTypeBuilding"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mplocationbasetype\/building","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/building","title":"MPLocationBaseType.building","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"building","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationBaseType/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/mapsindoors\/mplocationbasetype\/rawrepresentable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","kind":"article"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationBaseType/init(rawValue:)":{"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/init(rawValue:)","url":"\/documentation\/mapsindoors\/mplocationbasetype\/init(rawvalue:)","title":"init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SY","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationBaseType/venue":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPLocationBaseTypeVenue"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/venue","url":"\/documentation\/mapsindoors\/mplocationbasetype\/venue","title":"MPLocationBaseType.venue","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"venue"}]},"doc://com.mapspeople.mapsindoors/Se":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se","title":"Swift.Decodable"},"MapsPeopleWhite.png":{"alt":null,"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationBaseType":{"type":"topic","navigatorTitle":[{"text":"MPLocationBaseType","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType","kind":"symbol","url":"\/documentation\/mapsindoors\/mplocationbasetype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPLocationBaseType","kind":"identifier"}],"title":"MPLocationBaseType"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationBaseType/Equatable-Implementations":{"url":"\/documentation\/mapsindoors\/mplocationbasetype\/equatable-implementations","abstract":[],"role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/Equatable-Implementations","title":"Equatable Implementations","kind":"article"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationBaseType/room":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPLocationBaseTypeRoom"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mplocationbasetype\/room","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/room","title":"MPLocationBaseType.room","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"room"}]},"doc://com.mapspeople.mapsindoors/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"MPLocationBaseType","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MPLocationBaseType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MPLocationBaseType","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/area","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/building","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/floor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/pointOfInterest","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/room","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/venue"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationBaseType"},{"kind":"text","text":": "},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType~1pointOfInterest\/title","op":"replace","value":"MPLocationBaseTypePointOfInterest"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType~1pointOfInterest\/fragments","value":[{"text":"MPLocationBaseTypePointOfInterest","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType~1area\/title","value":"MPLocationBaseTypeArea"},{"value":[{"kind":"identifier","text":"MPLocationBaseTypeArea"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType~1area\/fragments"},{"value":"MPLocationBaseTypeFloor","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType~1floor\/title"},{"value":[{"kind":"identifier","text":"MPLocationBaseTypeFloor"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType~1floor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType~1building\/title","value":"MPLocationBaseTypeBuilding"},{"value":[{"kind":"identifier","text":"MPLocationBaseTypeBuilding"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType~1building\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType~1venue\/title","value":"MPLocationBaseTypeVenue","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType~1venue\/fragments","value":[{"text":"MPLocationBaseTypeVenue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType\/title","op":"replace","value":"MPLocationBaseType"},{"value":[{"text":"MPLocationBaseType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType\/fragments"},{"value":"MPLocationBaseTypeRoom","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType~1room\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType~1room\/fragments","value":[{"text":"MPLocationBaseTypeRoom","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}