{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPLocationSource","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","roleHeading":"Protocol","navigatorTitle":[{"text":"MPLocationSource","kind":"identifier"}],"symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPLocationSource"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPLocationSource","title":"MPLocationSource","modules":[{"name":"MapsIndoors"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mplocationsource"]},{"paths":["\/documentation\/mapsindoors\/mplocationsource"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"abstract":[{"text":"Location source protocol.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/sourceId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/status"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/addLocationsObserver(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/getLocations()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/removeLocationsObserver(_:)"],"title":"Instance Methods"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"],"kind":"relationships"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSource/status":{"title":"status","role":"symbol","navigatorTitle":[{"text":"status","kind":"identifier"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPLocationSourceStatus","preciseIdentifier":"c:@M@MapsIndoors@E@MPLocationSourceStatus","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The status of the location source."}],"url":"\/documentation\/mapsindoors\/mplocationsource\/status","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/status","kind":"symbol"},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSource":{"title":"MPLocationSource","role":"symbol","navigatorTitle":[{"text":"MPLocationSource","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPLocationSource","kind":"identifier"}],"abstract":[{"text":"Location source protocol.","type":"text"}],"url":"\/documentation\/mapsindoors\/mplocationsource","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSource/addLocationsObserver(_:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addLocationsObserver:"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addLocationsObserver"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPLocationsObserver","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationsObserver"},{"kind":"text","text":")"}],"abstract":[{"text":"Add an observer that gets callbacks about updates, additions and deletions to locations in this location source.","type":"text"}],"url":"\/documentation\/mapsindoors\/mplocationsource\/addlocationsobserver(_:)","type":"topic","title":"addLocationsObserver(_:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/addLocationsObserver(_:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSource/removeLocationsObserver(_:)":{"title":"removeLocationsObserver(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"removeLocationsObserver:"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeLocationsObserver"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationsObserver","text":"MPLocationsObserver","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"text":"Remove an observer that gets callbacks about updates, additions and deletions to locations in this location source.","type":"text"}],"url":"\/documentation\/mapsindoors\/mplocationsource\/removelocationsobserver(_:)","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/removeLocationsObserver(_:)","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSource/getLocations()":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getLocations"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getLocations","kind":"identifier"},{"kind":"text","text":"() -> ["},{"text":"MPLocation","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[{"text":"Get the locations available from the location source at this point in time.","type":"text"}],"url":"\/documentation\/mapsindoors\/mplocationsource\/getlocations()","type":"topic","title":"getLocations()","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/getLocations()"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSource/sourceId":{"title":"sourceId","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sourceId"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceId"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The id of the location source."}],"url":"\/documentation\/mapsindoors\/mplocationsource\/sourceid","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/sourceId","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","value":"MPLocationSource","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLocationSource"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MPLocationSource"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/sourceId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/status"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/addLocationsObserver(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/getLocations()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSource\/removeLocationsObserver(_:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPLocationSource","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"status","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource~1status\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource~1status\/fragments","value":[{"text":"status","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource\/title","value":"MPLocationSource"},{"value":[{"text":"MPLocationSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource~1addLocationsObserver(_:)\/title","value":"addLocationsObserver:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource~1addLocationsObserver(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"addLocationsObserver:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource~1removeLocationsObserver(_:)\/title","value":"removeLocationsObserver:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource~1removeLocationsObserver(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeLocationsObserver:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource~1getLocations()\/title","value":"getLocations","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getLocations"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource~1getLocations()\/fragments"},{"value":"sourceId","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource~1sourceId\/title","op":"replace"},{"value":[{"text":"sourceId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSource~1sourceId\/fragments"}]}]}