{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mplocationsourcestatus"]},{"paths":["\/documentation\/mapsindoors\/mplocationsourcestatus"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH","doc:\/\/com.mapspeople.mapsindoors\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPLocationSourceStatus","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/available","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/complete","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/inactive","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/initialising","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/unavailable"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/Equatable-Implementations","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/RawRepresentable-Implementations"]}],"metadata":{"modules":[{"name":"MapsIndoors"}],"symbolKind":"enum","roleHeading":"Enumeration","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationSourceStatus"}],"title":"MPLocationSourceStatus","navigatorTitle":[{"text":"MPLocationSourceStatus","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@E@MPLocationSourceStatus"},"references":{"doc://com.mapspeople.mapsindoors/SY":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SY","title":"Swift.RawRepresentable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSourceStatus/unavailable":{"navigatorTitle":[{"text":"MPLocationSourceStatusUnavailable","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unavailable"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Unavailable but expected to provide data under normal circumstances."}],"url":"\/documentation\/mapsindoors\/mplocationsourcestatus\/unavailable","title":"MPLocationSourceStatus.unavailable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/unavailable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSourceStatus":{"navigatorTitle":[{"kind":"identifier","text":"MPLocationSourceStatus"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLocationSourceStatus","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/mapsindoors\/mplocationsourcestatus","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus","title":"MPLocationSourceStatus"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSourceStatus/inactive":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inactive"}],"url":"\/documentation\/mapsindoors\/mplocationsourcestatus\/inactive","title":"MPLocationSourceStatus.inactive","navigatorTitle":[{"kind":"identifier","text":"MPLocationSourceStatusInactive"}],"abstract":[{"text":"Intentionally inactive and not expected to provide data.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/inactive"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSourceStatus/available":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"available","kind":"identifier"}],"title":"MPLocationSourceStatus.available","url":"\/documentation\/mapsindoors\/mplocationsourcestatus\/available","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/available","role":"symbol","navigatorTitle":[{"text":"MPLocationSourceStatusAvailable","kind":"identifier"}],"abstract":[{"type":"text","text":"Available and expected to provide data."}],"type":"topic"},"doc://com.mapspeople.mapsindoors/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","title":"Swift.Equatable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSourceStatus/complete":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"complete"}],"url":"\/documentation\/mapsindoors\/mplocationsourcestatus\/complete","title":"MPLocationSourceStatus.complete","navigatorTitle":[{"kind":"identifier","text":"MPLocationSourceStatusComplete"}],"abstract":[{"text":"MapsIndoors internal state is fully populated with data.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/complete"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSourceStatus/init(rawValue:)":{"type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"url":"\/documentation\/mapsindoors\/mplocationsourcestatus\/init(rawvalue:)","title":"init(rawValue:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/init(rawValue:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSourceStatus/Equatable-Implementations":{"type":"topic","role":"collectionGroup","url":"\/documentation\/mapsindoors\/mplocationsourcestatus\/equatable-implementations","title":"Equatable Implementations","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/Equatable-Implementations"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSourceStatus/initialising":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialising"}],"url":"\/documentation\/mapsindoors\/mplocationsourcestatus\/initialising","title":"MPLocationSourceStatus.initialising","navigatorTitle":[{"kind":"identifier","text":"MPLocationSourceStatusInitialising"}],"abstract":[{"type":"text","text":"Processing and expected to provide data when initialised."}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/initialising"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationSourceStatus/RawRepresentable-Implementations":{"role":"collectionGroup","kind":"article","type":"topic","abstract":[],"url":"\/documentation\/mapsindoors\/mplocationsourcestatus\/rawrepresentable-implementations","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/RawRepresentable-Implementations","title":"RawRepresentable Implementations"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","value":"MPLocationSourceStatus","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MPLocationSourceStatus","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPLocationSourceStatus"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/available","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/complete","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/inactive","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/initialising","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationSourceStatus\/unavailable"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPLocationSourceStatus","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"MPLocationSourceStatusUnavailable","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus~1unavailable\/title"},{"value":[{"kind":"identifier","text":"MPLocationSourceStatusUnavailable"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus~1unavailable\/fragments","op":"replace"},{"op":"replace","value":"MPLocationSourceStatus","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus\/title"},{"value":[{"text":"MPLocationSourceStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus\/fragments","op":"replace"},{"value":"MPLocationSourceStatusInactive","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus~1inactive\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus~1inactive\/fragments","value":[{"text":"MPLocationSourceStatusInactive","kind":"identifier"}]},{"value":"MPLocationSourceStatusAvailable","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus~1available\/title","op":"replace"},{"value":[{"text":"MPLocationSourceStatusAvailable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus~1available\/fragments"},{"value":"MPLocationSourceStatusComplete","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus~1complete\/title"},{"value":[{"kind":"identifier","text":"MPLocationSourceStatusComplete"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus~1complete\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus~1initialising\/title","value":"MPLocationSourceStatusInitialising"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationSourceStatus~1initialising\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPLocationSourceStatusInitialising"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}