{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapConfig"},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPMapConfig"}],"navigatorTitle":[{"kind":"identifier","text":"MPMapConfig"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"class","externalID":"c:@M@MapsIndoors@objc(cs)MPMapConfig","roleHeading":"Class","title":"MPMapConfig","role":"symbol"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPMapConfig","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"Google-Maps","text":"Google Maps","level":3,"type":"heading"},{"type":"codeListing","syntax":"swift","code":["self.mapView = GMSMapView(frame: CGRect.zero)","","try await MPMapsIndoors.shared.load(apiKey: solutionId)","let mapConfig = MPMapConfig(gmsMapView: mapView, googleApiKey: googleKey)","self.mapControl = MPMapsIndoors.createMapControl(mapConfig: mapConfig)"]},{"anchor":"Mapbox-Maps","type":"heading","level":3,"text":"Mapbox Maps"},{"type":"codeListing","code":["let mapboxResourceOptions = ResourceOptions(accessToken: AppDelegate.mapboxKey)","let mapboxMapInitOptions = MapInitOptions(resourceOptions: mapboxResourceOptions, styleURI: StyleURI.light)","self.mapView = MapView(frame: view.bounds, mapInitOptions: mapboxMapInitOptions)","","try await MPMapsIndoors.shared.load(apiKey: solutionId)","let mapConfig = MPMapConfig(mapBoxView: mapView, accessToken: mapboxKey)","self.mapControl = MPMapsIndoors.createMapControl(mapConfig: mapConfig)"],"syntax":"swift"}]}],"sections":[],"abstract":[{"type":"text","text":"A "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapConfig","isActive":true},{"type":"text","text":" is needed to initialise "},{"code":"MPMapsIndoors","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Depending on if you use Google Maps or Mapbox Maps as the map engine, this must be created differently.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpmapconfig"]}],"references":{"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapspeople.mapsindoors/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapConfig/init":{"url":"\/documentation\/mapsindoors\/mpmapconfig\/init","title":"init","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapConfig\/init","abstract":[],"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapConfig":{"url":"\/documentation\/mapsindoors\/mpmapconfig","title":"MPMapConfig","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapConfig","abstract":[{"type":"text","text":"A "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapConfig","isActive":true},{"type":"text","text":" is needed to initialise "},{"type":"codeVoice","code":"MPMapsIndoors"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Depending on if you use Google Maps or Mapbox Maps as the map engine, this must be created differently."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPMapConfig","kind":"identifier"}],"navigatorTitle":[{"text":"MPMapConfig","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.mapspeople.mapsindoors/SQ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapspeople.mapsindoors/SH":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MPMapConfig","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MPMapConfig","kind":"identifier"}]},{"value":[{"text":"MPMapConfig","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapConfig\/init"]}],"op":"add"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPMapConfig","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapConfig\/title","value":"MPMapConfig","op":"replace"},{"op":"replace","value":[{"text":"MPMapConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapConfig\/fragments"}]}]}