{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPMapControlDelegate","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPMapControlDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"MPMapControlDelegate","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"protocol","externalID":"c:@M@MapsIndoors@objc(pl)MPMapControlDelegate","roleHeading":"Protocol","title":"MPMapControlDelegate","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpmapcontroldelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpmapcontroldelegate"]}],"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/cameraIdle()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/cameraWillMove()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didChange(floorIndex:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didChange(selectedBuilding:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didChange(selectedLocation:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didChange(selectedVenue:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didChangeCameraPosition()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didTap(coordinate:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didTapIcon(location:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didTapInfoWindow(location:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/onPositionUpdate(position:)"],"title":"Instance Methods"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"kind":"symbol","abstract":[{"type":"text","text":"Delegate protocol specification to react to the events that "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true},{"text":" emits.","type":"text"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate/onPositionUpdate(position:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/onPositionUpdate(position:)","kind":"symbol","role":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/onpositionupdate(position:)","navigatorTitle":[{"kind":"identifier","text":"onPositionUpdate:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPositionUpdate","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"text":"MPPositionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPositionResult"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Called when "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"},{"text":" receives a new user position from the active ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This is the method you should implement if your app needs to be notified about each new user position."}],"title":"onPositionUpdate(position:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate/didChange(selectedLocation:)":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didChange(selectedLocation:)","role":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/didchange(selectedlocation:)","navigatorTitle":[{"kind":"identifier","text":"didChangeWithSelectedLocation:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"selectedLocation"},{"text":": ","kind":"text"},{"text":"MPLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Triggered when Location selection has changed."}],"type":"topic","title":"didChange(selectedLocation:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate":{"abstract":[{"text":"Delegate protocol specification to react to the events that ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"},{"text":" emits.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MPMapControlDelegate"}],"title":"MPMapControlDelegate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPMapControlDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontroldelegate","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate/didChange(floorIndex:)":{"required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didChange(floorIndex:)","kind":"symbol","role":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/didchange(floorindex:)","navigatorTitle":[{"text":"didChangeWithFloorIndex:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"floorIndex","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Triggered when the selected floor index has changed  (programatically or by camera movement).","type":"text"}],"title":"didChange(floorIndex:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation":{"navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLocation","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mplocation","title":"MPLocation","abstract":[{"type":"text","text":"This holds the data for a single location and a marker to display the data on a map."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate/cameraIdle()":{"required":true,"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/cameraIdle()","role":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/cameraidle()","navigatorTitle":[{"text":"cameraIdle","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"cameraIdle","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Is invoked once the camera position on MapView becomes idle.","type":"text"}],"title":"cameraIdle()","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate/didChangeCameraPosition()":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didChangeCameraPosition()","kind":"symbol","role":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/didchangecameraposition()","navigatorTitle":[{"kind":"identifier","text":"didChangeCameraPosition"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didChangeCameraPosition","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Is called repeatedly during a gesture or animation.","type":"text"}],"title":"didChangeCameraPosition()","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate/didChange(selectedVenue:)":{"required":true,"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didChange(selectedVenue:)","role":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/didchange(selectedvenue:)","navigatorTitle":[{"kind":"identifier","text":"didChangeWithSelectedVenue:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didChange","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"selectedVenue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPVenue","text":"MPVenue"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Triggered when Venue selection has changed (programatically or by camera movement).","type":"text"}],"title":"didChange(selectedVenue:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate/cameraWillMove()":{"navigatorTitle":[{"text":"cameraWillMove","kind":"identifier"}],"title":"cameraWillMove()","url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/camerawillmove()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraWillMove"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/cameraWillMove()","role":"symbol","abstract":[{"text":"Indicates that the camera position is about to change.","type":"text"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate/didChange(selectedBuilding:)":{"navigatorTitle":[{"kind":"identifier","text":"didChangeWithSelectedBuilding:"}],"title":"didChange(selectedBuilding:)","url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/didchange(selectedbuilding:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didChange"},{"kind":"text","text":"("},{"text":"selectedBuilding","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPBuilding","text":"MPBuilding"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didChange(selectedBuilding:)","role":"symbol","abstract":[{"type":"text","text":"Triggered when Building selection has changed  (programatically or by camera movement)."}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","abstract":[{"text":"This is the control object for the visual representation of the MapsIndoors SDK.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"title":"MPMapControl","role":"symbol","navigatorTitle":[{"text":"MPMapControl","kind":"identifier"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate/didTapInfoWindow(location:)":{"navigatorTitle":[{"kind":"identifier","text":"didTapInfoWindowWithLocation:"}],"title":"didTapInfoWindow(location:)","url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/didtapinfowindow(location:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didTapInfoWindow","kind":"identifier"},{"kind":"text","text":"("},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didTapInfoWindow(location:)","role":"symbol","abstract":[{"text":"Triggered when the info window of a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","isActive":true},{"text":" was tapped.","type":"text"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate/didTap(coordinate:)":{"abstract":[{"text":"Triggered when the map was tapped at the coordinate passed in to the method.","type":"text"}],"navigatorTitle":[{"text":"didTapWithCoordinate:","kind":"identifier"}],"title":"didTap(coordinate:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didTap(coordinate:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didTap"},{"kind":"text","text":"("},{"kind":"externalParam","text":"coordinate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","text":"MPPoint","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/didtap(coordinate:)","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionProvider":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProvider"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","navigatorTitle":[{"text":"MPPositionProvider","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mppositionprovider","kind":"symbol","title":"MPPositionProvider","abstract":[{"type":"text","text":"Protocol specifying how an indoor positioning provider should be implemented if the users location is to be exposed to "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true},{"type":"text","text":"."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate/didTapIcon(location:)":{"role":"symbol","navigatorTitle":[{"text":"didTapIconWithLocation:","kind":"identifier"}],"title":"didTapIcon(location:)","url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/didtapicon(location:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didTapIcon"},{"text":"(","kind":"text"},{"text":"location","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","text":"MPLocation"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didTapIcon(location:)","required":true,"abstract":[{"type":"text","text":"Triggered when the map with a given marker icon was tapped."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"MPMapControlDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MPMapControlDelegate","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MPMapControlDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/cameraIdle()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/cameraWillMove()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didChange(floorIndex:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didChange(selectedBuilding:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didChange(selectedLocation:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didChange(selectedVenue:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didChangeCameraPosition()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didTap(coordinate:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didTapIcon(location:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/didTapInfoWindow(location:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/onPositionUpdate(position:)"]}]},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControlDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1onPositionUpdate(position:)\/title","op":"replace","value":"onPositionUpdate:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onPositionUpdate:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1onPositionUpdate(position:)\/fragments"},{"value":"didChangeWithSelectedLocation:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didChange(selectedLocation:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didChange(selectedLocation:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didChangeWithSelectedLocation:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/title","value":"MPMapControlDelegate"},{"value":[{"text":"MPMapControlDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didChange(floorIndex:)\/title","op":"replace","value":"didChangeWithFloorIndex:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didChange(floorIndex:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didChangeWithFloorIndex:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/title","op":"replace","value":"MPLocation"},{"value":[{"kind":"identifier","text":"MPLocation"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1cameraIdle()\/title","value":"cameraIdle"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"cameraIdle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1cameraIdle()\/fragments"},{"op":"replace","value":"didChangeCameraPosition","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didChangeCameraPosition()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"didChangeCameraPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didChangeCameraPosition()\/fragments","op":"replace"},{"value":"didChangeWithSelectedVenue:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didChange(selectedVenue:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"didChangeWithSelectedVenue:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didChange(selectedVenue:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1cameraWillMove()\/title","value":"cameraWillMove","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1cameraWillMove()\/fragments","value":[{"kind":"text","text":"- "},{"text":"cameraWillMove","kind":"identifier"}],"op":"replace"},{"value":"didChangeWithSelectedBuilding:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didChange(selectedBuilding:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"didChangeWithSelectedBuilding:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didChange(selectedBuilding:)\/fragments"},{"value":"MPMapControl","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title","op":"replace"},{"value":[{"text":"MPMapControl","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","op":"replace"},{"value":"didTapInfoWindowWithLocation:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didTapInfoWindow(location:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didTapInfoWindow(location:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"didTapInfoWindowWithLocation:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didTap(coordinate:)\/title","value":"didTapWithCoordinate:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"didTapWithCoordinate:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didTap(coordinate:)\/fragments"},{"value":"MPPositionProvider","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider\/fragments","value":[{"kind":"identifier","text":"MPPositionProvider"}]},{"value":"didTapIconWithLocation:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didTapIcon(location:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1didTapIcon(location:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didTapIconWithLocation:"}]}]}]}