{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpMatrixHandlerBlockType"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult","preciseIdentifier":"c:objc(cs)MPDistanceMatrixResult","text":"MPDistanceMatrixResult"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmatrixhandlerblocktype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmatrixhandlerblocktype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpMatrixHandlerBlockType","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpMatrixHandlerBlockType"}],"title":"mpMatrixHandlerBlockType","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias","externalID":"c:MPDistanceMatrixProvider.h@T@mpMatrixHandlerBlockType","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"mpMatrixHandlerBlockType"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/mpMatrixHandlerBlockType":{"role":"symbol","title":"mpMatrixHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpMatrixHandlerBlockType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpMatrixHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpMatrixHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpmatrixhandlerblocktype"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixResult":{"role":"symbol","title":"MPDistanceMatrixResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDistanceMatrixResult"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDistanceMatrixResult"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixresult"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"mpMatrixHandlerBlockType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mpMatrixHandlerBlockType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"mpMatrixHandlerBlockType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(MPDistanceMatrixResult *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)MPDistanceMatrixResult#*$objc(cs)NSError)"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpMatrixHandlerBlockType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpMatrixHandlerBlockType\/title","value":"mpMatrixHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpMatrixHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpMatrixHandlerBlockType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult\/title","value":"MPDistanceMatrixResult"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixResult\/fragments","value":[{"kind":"identifier","text":"MPDistanceMatrixResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}