{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPMapBehavior"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior"],"type":"conformingTypes","kind":"relationships","title":"Conforming Types"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior\/allowFloorChange","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior\/animationDuration","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior\/moveCamera","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior\/showInfoWindow"]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpmapbehavior"]},{"paths":["\/documentation\/mapsindoors\/mpmapbehavior"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"MPMapBehavior","kind":"identifier"}],"symbolKind":"protocol","roleHeading":"Protocol","externalID":"c:@M@MapsIndoors@objc(pl)MPMapBehavior","modules":[{"name":"MapsIndoors"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPMapBehavior"}],"title":"MPMapBehavior"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapBehavior/animationDuration":{"title":"animationDuration","abstract":[],"url":"\/documentation\/mapsindoors\/mpmapbehavior\/animationduration","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior\/animationDuration","required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"animationDuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"animationDuration","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilterBehavior/default":{"url":"\/documentation\/mapsindoors\/mpfilterbehavior\/default","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior\/default","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"`default`","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilterBehavior","text":"MPFilterBehavior","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Default filter behavior","type":"text"}],"title":"default","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSelectionBehavior":{"title":"MPSelectionBehavior","url":"\/documentation\/mapsindoors\/mpselectionbehavior","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSelectionBehavior"}],"abstract":[{"text":"Selection behavior class that determines how a location selection should be displayed on the map.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPSelectionBehavior"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapBehavior/moveCamera":{"title":"moveCamera","abstract":[],"url":"\/documentation\/mapsindoors\/mpmapbehavior\/movecamera","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior\/moveCamera","required":true,"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveCamera","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"moveCamera"}],"role":"symbol","type":"topic"},"MapsPeopleWhite.png":{"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilterBehavior":{"url":"\/documentation\/mapsindoors\/mpfilterbehavior","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPFilterBehavior","kind":"identifier"}],"navigatorTitle":[{"text":"MPFilterBehavior","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Filter behavior class that determines how the result of applying a filter should be displayed on the map. Get the default behavior from "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior\/default","isActive":true,"type":"reference"},{"text":". The default behavior is no camera movement and no infowindow shown.","type":"text"}],"title":"MPFilterBehavior","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapBehavior/showInfoWindow":{"title":"showInfoWindow","abstract":[],"url":"\/documentation\/mapsindoors\/mpmapbehavior\/showinfowindow","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior\/showInfoWindow","required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"showInfoWindow","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"showInfoWindow","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapBehavior":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior","kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPMapBehavior"}],"title":"MPMapBehavior","abstract":[],"url":"\/documentation\/mapsindoors\/mpmapbehavior","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPMapBehavior"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapBehavior/allowFloorChange":{"title":"allowFloorChange","abstract":[],"url":"\/documentation\/mapsindoors\/mpmapbehavior\/allowfloorchange","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior\/allowFloorChange","required":true,"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowFloorChange","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"allowFloorChange"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MPMapBehavior"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"value":[{"text":"MPMapBehavior","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MPMapBehavior"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior\/allowFloorChange","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior\/animationDuration","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior\/moveCamera","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior\/showInfoWindow"]}]},{"path":"\/relationshipsSections","value":[{"type":"conformingTypes","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilterBehavior","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior"],"kind":"relationships","title":"Conforming Types"}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapBehavior"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapBehavior~1animationDuration\/title","value":"animationDuration"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapBehavior~1animationDuration\/fragments","value":[{"kind":"identifier","text":"animationDuration"}]},{"op":"replace","value":"MPSelectionBehavior","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSelectionBehavior\/title"},{"value":[{"text":"MPSelectionBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSelectionBehavior\/fragments"},{"op":"replace","value":"moveCamera","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapBehavior~1moveCamera\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapBehavior~1moveCamera\/fragments","value":[{"text":"moveCamera","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilterBehavior\/title","op":"replace","value":"MPFilterBehavior"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilterBehavior\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPFilterBehavior"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapBehavior~1showInfoWindow\/title","value":"showInfoWindow","op":"replace"},{"value":[{"text":"showInfoWindow","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapBehavior~1showInfoWindow\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapBehavior\/title","op":"replace","value":"MPMapBehavior"},{"value":[{"text":"MPMapBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapBehavior\/fragments"},{"op":"replace","value":"allowFloorChange","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapBehavior~1allowFloorChange\/title"},{"value":[{"text":"allowFloorChange","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapBehavior~1allowFloorChange\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}