{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPMapControl"}]}]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPMapControl"}],"navigatorTitle":[{"text":"MPMapControl","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"protocol","externalID":"c:@M@MapsIndoors@objc(pl)MPMapControl","role":"symbol","roleHeading":"Protocol","title":"MPMapControl"},"kind":"symbol","abstract":[{"text":"This is the control object for the visual representation of the MapsIndoors SDK.","type":"text"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/cameraPosition","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/currentBuilding","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/currentFloorIndex","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/currentVenue","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/customClusterIcon","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/customInfoWindow","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/delegate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/floorSelector","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/hideFloorSelector","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/mapPadding","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/mapStyle","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/positionProvider","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/selectedLocation","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/showInfoWindowOnClickedLocation","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/showUserPosition"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/clearFilter()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/disableLiveData(domain:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/enableLiveData(domain:listener:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/goTo(entity:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/newDirectionsRenderer()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/refresh()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/select(building:behavior:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/select(floorIndex:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/select(location:behavior:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/select(venue:behavior:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/setFilter(filter:behavior:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/setFilter(locations:behavior:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/setMapLabelFont(font:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:)-8rq64"],"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmapcontrol"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpmapcontrol"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/refresh()":{"required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/refresh()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refresh","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"refresh"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/refresh()","kind":"symbol","title":"refresh()","abstract":[{"text":"Force a re-render of the MapsIndoors map.","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/hideFloorSelector":{"title":"hideFloorSelector","role":"symbol","kind":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hideFloorSelector","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[{"text":"Hide or show the floor selector, defaults to false.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/hidefloorselector","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/hideFloorSelector","navigatorTitle":[{"text":"hideFloorSelector","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/customInfoWindow":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"customInfoWindow"},{"text":": ","kind":"text"},{"text":"MPCustomInfoWindow","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPCustomInfoWindow"},{"text":"?","kind":"text"}],"abstract":[{"text":"Get or set the info window generator (if none i set, the default internal will be used).","type":"text"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/custominfowindow","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/customInfoWindow","navigatorTitle":[{"kind":"identifier","text":"customInfoWindow"}],"type":"topic","role":"symbol","kind":"symbol","title":"customInfoWindow"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/mapStyle":{"kind":"symbol","title":"mapStyle","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/mapStyle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mapStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPMapStyle","text":"MPMapStyle","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","abstract":[{"text":"Get or set the map styling.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/mapstyle","navigatorTitle":[{"kind":"identifier","text":"mapStyle"}],"required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/setFilter(filter:behavior:)":{"kind":"symbol","role":"symbol","title":"setFilter(filter:behavior:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setFilter","kind":"identifier"},{"text":"(","kind":"text"},{"text":"filter","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilter","text":"MPFilter"},{"text":", ","kind":"text"},{"text":"behavior","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MPFilterBehavior","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilterBehavior"},{"text":")","kind":"text"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/setfilter(filter:behavior:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/setFilter(filter:behavior:)","navigatorTitle":[{"kind":"identifier","text":"setFilterWithFilter:behavior:"}],"type":"topic","abstract":[{"type":"text","text":"Apply a filter to the map. Only show the "},{"type":"codeVoice","code":"MPLocations"},{"text":" captured by the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter","isActive":true},{"text":".","type":"text"}],"required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/mapPadding":{"kind":"symbol","title":"mapPadding","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/mapPadding","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mapPadding","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"role":"symbol","type":"topic","abstract":[{"text":"Sets padding on the map.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/mappadding","navigatorTitle":[{"kind":"identifier","text":"mapPadding"}],"required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/showUserPosition":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"showUserPosition"}],"role":"symbol","abstract":[{"type":"text","text":"Enable\/disable showing the users position with a blue dot (customizable) (requires your application to implement a "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","isActive":true},{"type":"text","text":")."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/showUserPosition","type":"topic","url":"\/documentation\/mapsindoors\/mpmapcontrol\/showuserposition","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"showUserPosition","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"showUserPosition"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter":{"navigatorTitle":[{"text":"MPFilter","kind":"identifier"}],"title":"MPFilter","url":"\/documentation\/mapsindoors\/mpfilter","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFilter"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Filter object used when making a request to e.g. "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","isActive":true},{"type":"text","text":"."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionProvider":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProvider"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","navigatorTitle":[{"text":"MPPositionProvider","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mppositionprovider","kind":"symbol","title":"MPPositionProvider","abstract":[{"type":"text","text":"Protocol specifying how an indoor positioning provider should be implemented if the users location is to be exposed to "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true},{"type":"text","text":"."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/positionProvider":{"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/positionProvider","url":"\/documentation\/mapsindoors\/mpmapcontrol\/positionprovider","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"positionProvider"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPPositionProvider","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPPositionProvider"},{"kind":"text","text":"?"}],"title":"positionProvider","kind":"symbol","required":true,"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"positionProvider"}],"deprecated":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/goTo(entity:)":{"kind":"symbol","role":"symbol","title":"goTo(entity:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"goTo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPEntity","text":"MPEntity"},{"text":")","kind":"text"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/goto(entity:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/goTo(entity:)","navigatorTitle":[{"text":"goToEntity:","kind":"identifier"}],"abstract":[{"text":"Move the camera to the entity.","type":"text"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/select(building:behavior:)":{"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/select(building:behavior:)","title":"select(building:behavior:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"select"},{"text":"(","kind":"text"},{"text":"building","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPBuilding","text":"MPBuilding"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"behavior"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSelectionBehavior","text":"MPSelectionBehavior"},{"text":")","kind":"text"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/select(building:behavior:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"selectWithBuilding:behavior:"}],"abstract":[{"type":"text","text":"Select a Building."}],"kind":"symbol","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsRenderer":{"navigatorTitle":[{"text":"MPDirectionsRenderer","kind":"identifier"}],"role":"symbol","title":"MPDirectionsRenderer","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDirectionsRenderer","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer","type":"topic","abstract":[{"type":"text","text":"This allows for an easy way to display a route on the MapsIndoors map. Each leg of the route can be shown individually and can be navigated by manipulating the selected leg index. Various customization options are available to adjust the polyline styling and camera behavior."}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/clearFilter()":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"clearFilter"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/clearFilter()","url":"\/documentation\/mapsindoors\/mpmapcontrol\/clearfilter()","type":"topic","required":true,"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearFilter","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Clear any previously applied filter."}],"title":"clearFilter()"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/select(floorIndex:)":{"required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/select(floorIndex:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"select","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"floorIndex"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"selectWithFloorIndex:"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/select(floorindex:)","kind":"symbol","title":"select(floorIndex:)","abstract":[{"type":"text","text":"Select a floor index."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/disableLiveData(domain:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"disableLiveData","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"domain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"kind":"symbol","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/disableLiveData(domain:)","abstract":[{"text":"Convenience: Disable LiveData for a given domain (includes default live data badged icons).","type":"text"}],"title":"disableLiveData(domain:)","navigatorTitle":[{"text":"disableLiveDataWithDomain:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontrol\/disablelivedata(domain:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/enableLiveData(domain:listener:)":{"title":"enableLiveData(domain:listener:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableLiveData"},{"text":"(","kind":"text"},{"text":"domain","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"listener","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate","text":"MPLiveUpdate","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/enableLiveData(domain:listener:)","navigatorTitle":[{"text":"enableLiveDataWithDomain:listener:","kind":"identifier"}],"abstract":[{"type":"text","text":"Convenience: Enable LiveData for a given domain (includes default live data badged icons)."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontrol\/enablelivedata(domain:listener:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","abstract":[{"text":"This is the control object for the visual representation of the MapsIndoors SDK.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"title":"MPMapControl","role":"symbol","navigatorTitle":[{"text":"MPMapControl","kind":"identifier"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/currentBuilding":{"required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/currentBuilding","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"currentBuilding","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPBuilding","text":"MPBuilding"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"currentBuilding","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/currentbuilding","kind":"symbol","title":"currentBuilding","abstract":[{"type":"text","text":"Get the currently selected Building."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/setFilter(locations:behavior:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setFilter","kind":"identifier"},{"kind":"text","text":"("},{"text":"locations","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","text":"MPLocation"},{"text":"], ","kind":"text"},{"text":"behavior","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilterBehavior","kind":"typeIdentifier","text":"MPFilterBehavior"},{"text":")","kind":"text"}],"kind":"symbol","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/setFilter(locations:behavior:)","abstract":[{"type":"text","text":"Apply a filter to the map. Only show the "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","isActive":true},{"type":"text","text":"s included in the list."}],"title":"setFilter(locations:behavior:)","navigatorTitle":[{"kind":"identifier","text":"setFilterWithLocations:behavior:"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontrol\/setfilter(locations:behavior:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/select(location:behavior:)":{"navigatorTitle":[{"kind":"identifier","text":"selectWithLocation:behavior:"}],"required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/select(location:behavior:)","type":"topic","abstract":[{"type":"text","text":"Select a Location."}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/select(location:behavior:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"select"},{"kind":"text","text":"("},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","text":"MPLocation"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"behavior"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSelectionBehavior","text":"MPSelectionBehavior"},{"kind":"text","text":")"}],"title":"select(location:behavior:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/setMapLabelFont(font:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:)-8rq64":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/setMapLabelFont(font:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:)-8rq64","abstract":[{"text":"Set a custom label font, text size, color and halo.","type":"text"}],"required":true,"defaultImplementations":1,"url":"\/documentation\/mapsindoors\/mpmapcontrol\/setmaplabelfont(font:textsize:color:labelhalocolor:labelhalowidth:labelhaloblur:)-8rq64","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setMapLabelFont","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"font"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textSize"},{"kind":"text","text":": "},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"color","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"labelHaloColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"labelHaloWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"text":"labelHaloBlur","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"setMapLabelFont(font:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:)","role":"symbol","navigatorTitle":[{"text":"setMapLabelFontWithFont:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:","kind":"identifier"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/selectedLocation":{"required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/selectedLocation","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"selectedLocation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"selectedLocation","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/selectedlocation","kind":"symbol","title":"selectedLocation","abstract":[{"text":"Get the currently selected Location.","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/customClusterIcon":{"title":"customClusterIcon","role":"symbol","kind":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"customClusterIcon"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPCustomClusterIcon","text":"MPCustomClusterIcon","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Get or set the cluster icon generator (if none is set, the default internal will be used)."}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/customclustericon","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/customClusterIcon","navigatorTitle":[{"text":"customClusterIcon","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPRoute"}],"type":"topic","url":"\/documentation\/mapsindoors\/mproute","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","abstract":[{"text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","isActive":true,"type":"reference"},{"type":"text","text":"."}],"title":"MPRoute","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPRoute","kind":"identifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/newDirectionsRenderer()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"newDirectionsRenderer","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPDirectionsRenderer","text":"MPDirectionsRenderer","kind":"typeIdentifier"}],"required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/newDirectionsRenderer()","navigatorTitle":[{"text":"newDirectionsRenderer","kind":"identifier"}],"abstract":[{"text":"Get a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer"},{"text":" to show a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","isActive":true},{"type":"text","text":" on the map."}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/newdirectionsrenderer()","type":"topic","kind":"symbol","role":"symbol","title":"newDirectionsRenderer()"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/floorSelector":{"required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/floorSelector","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"floorSelector","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPCustomFloorSelector","text":"MPCustomFloorSelector","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"floorSelector"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/floorselector","abstract":[{"text":"Get or set the floor selector (if none is set, a default floor selector will be used).","type":"text"}],"title":"floorSelector","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/currentVenue":{"required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/currentVenue","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"currentVenue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPVenue","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPVenue","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"currentVenue"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/currentvenue","kind":"symbol","title":"currentVenue","abstract":[{"text":"Get the currently selected Venue.","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/delegate":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Listen to events."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/delegate","required":true,"kind":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontrol\/delegate","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPMapControlDelegate","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPMapControlDelegate"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/showInfoWindowOnClickedLocation":{"navigatorTitle":[{"text":"showInfoWindowOnClickedLocation","kind":"identifier"}],"required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showInfoWindowOnClickedLocation"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Hide or show the info window on user-selected locations (default is true)"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpmapcontrol\/showinfowindowonclickedlocation","title":"showInfoWindowOnClickedLocation","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/showInfoWindowOnClickedLocation"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/cameraPosition":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPosition"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPCameraPosition","text":"MPCameraPosition","kind":"typeIdentifier"}],"required":true,"kind":"symbol","url":"\/documentation\/mapsindoors\/mpmapcontrol\/cameraposition","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraPosition"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/cameraPosition","title":"cameraPosition","abstract":[{"type":"text","text":"Get the current camera position state."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation":{"navigatorTitle":[{"kind":"identifier","text":"MPLocation"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPLocation","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mplocation","title":"MPLocation","abstract":[{"type":"text","text":"This holds the data for a single location and a marker to display the data on a map."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/currentFloorIndex":{"abstract":[{"type":"text","text":"Get the current floor index."}],"url":"\/documentation\/mapsindoors\/mpmapcontrol\/currentfloorindex","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/currentFloorIndex","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"currentFloorIndex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","navigatorTitle":[{"text":"currentFloorIndex","kind":"identifier"}],"required":true,"role":"symbol","title":"currentFloorIndex"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/select(venue:behavior:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectWithVenue:behavior:"}],"abstract":[{"text":"Select a Venue.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/select(venue:behavior:)","url":"\/documentation\/mapsindoors\/mpmapcontrol\/select(venue:behavior:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"select","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"venue"},{"text":": ","kind":"text"},{"text":"MPVenue","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPVenue"},{"kind":"text","text":"?, "},{"text":"behavior","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSelectionBehavior","text":"MPSelectionBehavior"},{"kind":"text","text":")"}],"kind":"symbol","title":"select(venue:behavior:)","required":true}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","value":"MPMapControl","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MPMapControl","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MPMapControl"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/cameraPosition","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/currentBuilding","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/currentFloorIndex","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/currentVenue","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/customClusterIcon","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/customInfoWindow","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/delegate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/floorSelector","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/hideFloorSelector","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/mapPadding","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/mapStyle","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/positionProvider","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/selectedLocation","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/showInfoWindowOnClickedLocation","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/showUserPosition"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/clearFilter()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/disableLiveData(domain:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/enableLiveData(domain:listener:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/goTo(entity:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/newDirectionsRenderer()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/refresh()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/select(building:behavior:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/select(floorIndex:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/select(location:behavior:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/select(venue:behavior:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/setFilter(filter:behavior:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/setFilter(locations:behavior:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/setMapLabelFont(font:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:)-8rq64"],"title":"Instance Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPMapControl","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"refresh","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1refresh()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"refresh","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1refresh()\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1hideFloorSelector\/title","op":"replace","value":"hideFloorSelector"},{"op":"replace","value":[{"kind":"identifier","text":"hideFloorSelector"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1hideFloorSelector\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1customInfoWindow\/title","value":"customInfoWindow","op":"replace"},{"value":[{"kind":"identifier","text":"customInfoWindow"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1customInfoWindow\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1mapStyle\/title","value":"mapStyle"},{"value":[{"text":"mapStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1mapStyle\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1setFilter(filter:behavior:)\/title","op":"replace","value":"setFilterWithFilter:behavior:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1setFilter(filter:behavior:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setFilterWithFilter:behavior:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1mapPadding\/title","op":"replace","value":"mapPadding"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1mapPadding\/fragments","value":[{"text":"mapPadding","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1showUserPosition\/title","value":"showUserPosition"},{"value":[{"text":"showUserPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1showUserPosition\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter\/title","value":"MPFilter"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter\/fragments","value":[{"kind":"identifier","text":"MPFilter"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider\/title","value":"MPPositionProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider\/fragments","value":[{"text":"MPPositionProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1positionProvider\/title","value":"positionProvider"},{"op":"replace","value":[{"kind":"identifier","text":"positionProvider"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1positionProvider\/fragments"},{"value":"goToEntity:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1goTo(entity:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1goTo(entity:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"goToEntity:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1select(building:behavior:)\/title","op":"replace","value":"selectWithBuilding:behavior:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1select(building:behavior:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"selectWithBuilding:behavior:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/title","value":"MPDirectionsRenderer","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/fragments","value":[{"text":"MPDirectionsRenderer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1clearFilter()\/title","value":"clearFilter"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1clearFilter()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"clearFilter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1select(floorIndex:)\/title","op":"replace","value":"selectWithFloorIndex:"},{"value":[{"text":"- ","kind":"text"},{"text":"selectWithFloorIndex:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1select(floorIndex:)\/fragments"},{"op":"replace","value":"disableLiveDataWithDomain:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1disableLiveData(domain:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"disableLiveDataWithDomain:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1disableLiveData(domain:)\/fragments"},{"value":"enableLiveDataWithDomain:listener:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1enableLiveData(domain:listener:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1enableLiveData(domain:listener:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"enableLiveDataWithDomain:listener:"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","op":"replace","value":[{"text":"MPMapControl","kind":"identifier"}]},{"value":"currentBuilding","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1currentBuilding\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1currentBuilding\/fragments","value":[{"kind":"identifier","text":"currentBuilding"}]},{"op":"replace","value":"setFilterWithLocations:behavior:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1setFilter(locations:behavior:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setFilterWithLocations:behavior:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1setFilter(locations:behavior:)\/fragments"},{"op":"replace","value":"selectWithLocation:behavior:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1select(location:behavior:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1select(location:behavior:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"selectWithLocation:behavior:","kind":"identifier"}]},{"value":"setMapLabelFontWithFont:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1setMapLabelFont(font:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:)-8rq64\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1setMapLabelFont(font:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:)-8rq64\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setMapLabelFontWithFont:textSize:color:labelHaloColor:labelHaloWidth:labelHaloBlur:"}]},{"op":"replace","value":"selectedLocation","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1selectedLocation\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1selectedLocation\/fragments","value":[{"text":"selectedLocation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1customClusterIcon\/title","op":"replace","value":"customClusterIcon"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1customClusterIcon\/fragments","value":[{"kind":"identifier","text":"customClusterIcon"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/title","value":"MPRoute","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPRoute"}]},{"value":"newDirectionsRenderer","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1newDirectionsRenderer()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"newDirectionsRenderer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1newDirectionsRenderer()\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1floorSelector\/title","op":"replace","value":"floorSelector"},{"op":"replace","value":[{"text":"floorSelector","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1floorSelector\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1currentVenue\/title","op":"replace","value":"currentVenue"},{"value":[{"text":"currentVenue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1currentVenue\/fragments","op":"replace"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1delegate\/title"},{"value":[{"kind":"identifier","text":"delegate"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1delegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1showInfoWindowOnClickedLocation\/title","value":"showInfoWindowOnClickedLocation"},{"value":[{"kind":"identifier","text":"showInfoWindowOnClickedLocation"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1showInfoWindowOnClickedLocation\/fragments","op":"replace"},{"value":"cameraPosition","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1cameraPosition\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1cameraPosition\/fragments","op":"replace","value":[{"text":"cameraPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/title","value":"MPLocation"},{"value":[{"kind":"identifier","text":"MPLocation"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/fragments","op":"replace"},{"value":"currentFloorIndex","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1currentFloorIndex\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1currentFloorIndex\/fragments","value":[{"kind":"identifier","text":"currentFloorIndex"}]},{"value":"selectWithVenue:behavior:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1select(venue:behavior:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1select(venue:behavior:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"selectWithVenue:behavior:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}