{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMessage"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmessage-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmessage-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)JSONModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)NSCopying","doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding","doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/beaconId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/content","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/deliveredDate","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/geometry","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/image","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/imagePath","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/locationId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/maxPushTimes","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/messageId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/notificationCount","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/pushInterval","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/title"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMessage"}],"title":"MPMessage","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPMessage","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPMessage"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessage-swift.class/deliveredDate":{"role":"symbol","title":"deliveredDate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveredDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/deliveredDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deliveredDate"}],"url":"\/documentation\/mapsindoors\/mpmessage-swift.class\/delivereddate"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessage-swift.class/beaconId":{"role":"symbol","title":"beaconId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"beaconId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/beaconId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"beaconId"}],"url":"\/documentation\/mapsindoors\/mpmessage-swift.class\/beaconid"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessage-swift.class/notificationCount":{"role":"symbol","title":"notificationCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationCount"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/notificationCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"notificationCount"}],"url":"\/documentation\/mapsindoors\/mpmessage-swift.class\/notificationcount"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessage-swift.class/geometry":{"role":"symbol","title":"geometry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/geometry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"geometry"}],"url":"\/documentation\/mapsindoors\/mpmessage-swift.class\/geometry"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessage-swift.class/image":{"role":"symbol","title":"image","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Ignore","preciseIdentifier":"c:objc(pl)Ignore"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/image","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"image"}],"url":"\/documentation\/mapsindoors\/mpmessage-swift.class\/image"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessage-swift.class/pushInterval":{"role":"symbol","title":"pushInterval","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushInterval"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/pushInterval","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pushInterval"}],"url":"\/documentation\/mapsindoors\/mpmessage-swift.class\/pushinterval"},"doc://MapsIndoors/objc(cs)JSONModel":{"type":"unresolvable","title":"JSONModel","identifier":"doc:\/\/MapsIndoors\/objc(cs)JSONModel"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessage-swift.class":{"role":"symbol","title":"MPMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMessage"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMessage"}],"url":"\/documentation\/mapsindoors\/mpmessage-swift.class"},"doc://MapsIndoors/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCopying"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessage-swift.class/locationId":{"role":"symbol","title":"locationId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/locationId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"locationId"}],"url":"\/documentation\/mapsindoors\/mpmessage-swift.class\/locationid"},"doc://MapsIndoors/objc(pl)AbstractJSONModelProtocol":{"type":"unresolvable","title":"JSONModel.AbstractJSONModelProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessage-swift.class/content":{"role":"symbol","title":"content","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/content","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"content"}],"url":"\/documentation\/mapsindoors\/mpmessage-swift.class\/content"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessage-swift.class/messageId":{"role":"symbol","title":"messageId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/messageId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageId"}],"url":"\/documentation\/mapsindoors\/mpmessage-swift.class\/messageid"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessage-swift.class/maxPushTimes":{"role":"symbol","title":"maxPushTimes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxPushTimes"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/maxPushTimes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxPushTimes"}],"url":"\/documentation\/mapsindoors\/mpmessage-swift.class\/maxpushtimes"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessage-swift.class/title":{"role":"symbol","title":"title","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/title","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"title"}],"url":"\/documentation\/mapsindoors\/mpmessage-swift.class\/title"},"doc://MapsIndoors/documentation/MapsIndoors/MPMessage-swift.class/imagePath":{"role":"symbol","title":"imagePath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/imagePath","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imagePath"}],"url":"\/documentation\/mapsindoors\/mpmessage-swift.class\/imagepath"},"doc://MapsIndoors/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPMessage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPMessage"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPMessage"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/beaconId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/content","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/deliveredDate","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/geometry","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/image","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/imagePath","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/locationId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/maxPushTimes","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/messageId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/notificationCount","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/pushInterval","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMessage-swift.class\/title"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)JSONModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMessage"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSONModel","preciseIdentifier":"c:objc(cs)JSONModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1deliveredDate\/title","value":"deliveredDate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1deliveredDate\/fragments","value":[{"kind":"identifier","text":"deliveredDate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1beaconId\/title","value":"beaconId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1beaconId\/fragments","value":[{"kind":"identifier","text":"beaconId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1notificationCount\/title","value":"notificationCount"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1notificationCount\/fragments","value":[{"kind":"identifier","text":"notificationCount"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1geometry\/title","value":"geometry"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1geometry\/fragments","value":[{"kind":"identifier","text":"geometry"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1image\/title","value":"image"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1image\/fragments","value":[{"kind":"identifier","text":"image"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1pushInterval\/title","value":"pushInterval"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1pushInterval\/fragments","value":[{"kind":"identifier","text":"pushInterval"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class\/title","value":"MPMessage"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class\/fragments","value":[{"kind":"identifier","text":"MPMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1locationId\/title","value":"locationId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1locationId\/fragments","value":[{"kind":"identifier","text":"locationId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1content\/title","value":"content"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1content\/fragments","value":[{"kind":"identifier","text":"content"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1messageId\/title","value":"messageId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1messageId\/fragments","value":[{"kind":"identifier","text":"messageId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1maxPushTimes\/title","value":"maxPushTimes"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1maxPushTimes\/fragments","value":[{"kind":"identifier","text":"maxPushTimes"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1title\/title","value":"title"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1title\/fragments","value":[{"kind":"identifier","text":"title"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1imagePath\/title","value":"imagePath"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMessage-swift.class~1imagePath\/fragments","value":[{"kind":"identifier","text":"imagePath"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}