{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPMenuInfo","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"variants":[{"paths":["\/documentation\/mapsindoors\/mpmenuinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmenuinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMenuInfo","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMenuInfo\/categoryKey","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMenuInfo\/iconUrl","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMenuInfo\/menuImageUrl"],"title":"Instance Properties"}],"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPMenuInfo","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPMenuInfo","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"MPMenuInfo","kind":"identifier"}],"symbolKind":"protocol","title":"MPMenuInfo","role":"symbol","roleHeading":"Protocol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMenuInfo/iconUrl":{"kind":"symbol","required":true,"abstract":[{"text":"An optional image URL that can be used as an icon.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iconUrl","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/mapsindoors\/mpmenuinfo\/iconurl","title":"iconUrl","role":"symbol","navigatorTitle":[{"text":"iconUrl","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMenuInfo\/iconUrl","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter":{"navigatorTitle":[{"text":"MPFilter","kind":"identifier"}],"title":"MPFilter","url":"\/documentation\/mapsindoors\/mpfilter","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFilter"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Filter object used when making a request to e.g. "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","isActive":true},{"type":"text","text":"."}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/locationsWith(query:filter:)":{"role":"symbol","navigatorTitle":[{"text":"locationsWithQuery:filter:completionHandler:","kind":"identifier"}],"title":"locationsWith(query:filter:)","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/locationswith(query:filter:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locationsWith","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"query"},{"text":": ","kind":"text"},{"text":"MPQuery","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPQuery","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"filter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilter"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation","text":"MPLocation"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","required":true,"abstract":[{"type":"text","text":"Search for MPLocations using MPQuery and\/or MPFilter."}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMenuInfo":{"kind":"symbol","role":"symbol","title":"MPMenuInfo","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPMenuInfo","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpmenuinfo","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMenuInfo","navigatorTitle":[{"kind":"identifier","text":"MPMenuInfo"}],"abstract":[],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMenuInfo/menuImageUrl":{"kind":"symbol","role":"symbol","title":"menuImageUrl","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"menuImageUrl","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/mapsindoors\/mpmenuinfo\/menuimageurl","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMenuInfo\/menuImageUrl","navigatorTitle":[{"text":"menuImageUrl","kind":"identifier"}],"abstract":[{"type":"text","text":"An optional image URL."}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMenuInfo/categoryKey":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"categoryKey","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMenuInfo\/categoryKey","type":"topic","abstract":[{"type":"text","text":"A language independent identifier for this specific category, can be used with e.g. "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter","isActive":true},{"type":"text","text":" in "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)"},{"text":" to find locations in this category.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpmenuinfo\/categorykey","kind":"symbol","role":"symbol","title":"categoryKey","required":true,"navigatorTitle":[{"text":"categoryKey","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"MPMenuInfo","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MPMenuInfo","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MPMenuInfo"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMenuInfo\/categoryKey","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMenuInfo\/iconUrl","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMenuInfo\/menuImageUrl"]}],"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPMenuInfo"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"iconUrl","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMenuInfo~1iconUrl\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMenuInfo~1iconUrl\/fragments","value":[{"kind":"identifier","text":"iconUrl"}]},{"op":"replace","value":"MPFilter","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter\/title"},{"value":[{"text":"MPFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/title","op":"replace","value":"locationsWithQuery:filter:completionHandler:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"locationsWithQuery:filter:completionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMenuInfo\/title","op":"replace","value":"MPMenuInfo"},{"op":"replace","value":[{"text":"MPMenuInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMenuInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMenuInfo~1menuImageUrl\/title","value":"menuImageUrl"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMenuInfo~1menuImageUrl\/fragments","value":[{"text":"menuImageUrl","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"categoryKey","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMenuInfo~1categoryKey\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMenuInfo~1categoryKey\/fragments","op":"replace","value":[{"kind":"identifier","text":"categoryKey"}]}]}]}