{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMIAPI"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpmiapi"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpmiapi"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMIAPI","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMIAPI\/baseUrl()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMIAPI"}],"title":"MPMIAPI","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPMIAPI","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPMIAPI"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(cs)NSObject"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/documentation/MapsIndoors/MPMIAPI":{"role":"symbol","title":"MPMIAPI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMIAPI"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMIAPI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMIAPI"}],"url":"\/documentation\/mapsindoors\/mpmiapi"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPMIAPI/baseUrl()":{"role":"symbol","title":"baseUrl()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseUrl"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMIAPI\/baseUrl()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"baseUrl"}],"url":"\/documentation\/mapsindoors\/mpmiapi\/baseurl()"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPMIAPI"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPMIAPI"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPMIAPI"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMIAPI\/baseUrl()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMIAPI"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMIAPI\/title","value":"MPMIAPI"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMIAPI\/fragments","value":[{"kind":"identifier","text":"MPMIAPI"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMIAPI~1baseUrl()\/title","value":"baseUrl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMIAPI~1baseUrl()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"baseUrl"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}