{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(MPMultiPolygonGeometry) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPMultiPolygonGeometry","kind":"identifier"}]}]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/area","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/coordinates"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsCoordinate(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsCoordinate(_:ignorePolygonHoles:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsLineSegmentFromCoordinate(_:toCoordinate:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsPoint(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/encode(to:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/init(dictionary:)"],"title":"Instance Methods"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometry"],"title":"Inherits From"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryP","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol","doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"type":"conformsTo"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPMultiPolygonGeometry","kind":"identifier"}],"title":"MPMultiPolygonGeometry","modules":[{"name":"MapsIndoors"}],"symbolKind":"class","externalID":"c:@M@MapsIndoors@objc(cs)MPMultiPolygonGeometry","navigatorTitle":[{"kind":"identifier","text":"MPMultiPolygonGeometry"}]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpmultipolygongeometry"]},{"paths":["\/documentation\/mapsindoors\/mpmultipolygongeometry"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMultiPolygonGeometry/containsCoordinate(_:ignorePolygonHoles:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsCoordinate(_:ignorePolygonHoles:)","type":"topic","abstract":[{"type":"text","text":"Check if the given coordinate is contained within the polygon."}],"url":"\/documentation\/mapsindoors\/mpmultipolygongeometry\/containscoordinate(_:ignorepolygonholes:)","title":"containsCoordinate(_:ignorePolygonHoles:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"containsCoordinate","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"ignorePolygonHoles","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"containsCoordinate:ignorePolygonHoles:"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMultiPolygonGeometry/coordinates":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/coordinates","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"coordinates","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPolygonGeometry","text":"MPPolygonGeometry","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"coordinates","navigatorTitle":[{"kind":"identifier","text":"coordinates"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpmultipolygongeometry\/coordinates","abstract":[],"kind":"symbol","role":"symbol"},"doc://com.mapspeople.mapsindoors/SE":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMultiPolygonGeometry/containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"containsCoordinate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"text":"ignorePolygonHoles","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"containmentMetadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MPGeometryContainmentMetadata","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometryContainmentMetadata"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/mapsindoors\/mpmultipolygongeometry\/containscoordinate(_:ignorepolygonholes:containmentmetadata:)","role":"symbol","abstract":[{"type":"text","text":"Check if the given coordinate is contained within the polygon, and optionally return the coordinate closest to the polygon."},{"type":"text","text":" "},{"text":"If the polygon contains the coordinate, ‘coordinate’ is returned as nearestPoint.","type":"text"},{"type":"text","text":" "},{"text":"If coordinate is not contained, the nearest point is calculated.","type":"text"}],"title":"containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)","navigatorTitle":[{"text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryQueryProtocol":{"navigatorTitle":[{"text":"MPGeometryQueryProtocol","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol","kind":"symbol","role":"symbol","title":"MPGeometryQueryProtocol","type":"topic","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPGeometryQueryProtocol","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/SQ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMultiPolygonGeometry":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry","navigatorTitle":[{"text":"MPMultiPolygonGeometry","kind":"identifier"}],"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMultiPolygonGeometry"}],"url":"\/documentation\/mapsindoors\/mpmultipolygongeometry","type":"topic","title":"MPMultiPolygonGeometry","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMultiPolygonGeometry/area":{"url":"\/documentation\/mapsindoors\/mpmultipolygongeometry\/area","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The area of the polygon computed as the area of the outer path with the area of all holes subtracted."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"area"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"title":"area","type":"topic","navigatorTitle":[{"text":"area","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/area"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometryP":{"title":"MPGeometryP","navigatorTitle":[{"text":"MPGeometryP","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPGeometryP","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryP","url":"\/documentation\/mapsindoors\/mpgeometryp","kind":"symbol","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPGeometry":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPGeometry","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometry","url":"\/documentation\/mapsindoors\/mpgeometry","kind":"symbol","title":"MPGeometry","type":"topic","abstract":[],"navigatorTitle":[{"text":"MPGeometry","kind":"identifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMultiPolygonGeometry/containsLineSegmentFromCoordinate(_:toCoordinate:)":{"role":"symbol","abstract":[{"text":"Check if the given line segment is fully contained within the polygon.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsLineSegmentFromCoordinate(_:toCoordinate:)","navigatorTitle":[{"kind":"identifier","text":"containsLineSegmentFromCoordinate:toCoordinate:"}],"url":"\/documentation\/mapsindoors\/mpmultipolygongeometry\/containslinesegmentfromcoordinate(_:tocoordinate:)","title":"containsLineSegmentFromCoordinate(_:toCoordinate:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"containsLineSegmentFromCoordinate","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toCoordinate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMultiPolygonGeometry/containsCoordinate(_:)":{"role":"symbol","abstract":[{"type":"text","text":"Check if the given coordinate is contained within the polygon."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsCoordinate(_:)","navigatorTitle":[{"kind":"identifier","text":"containsCoordinate:"}],"url":"\/documentation\/mapsindoors\/mpmultipolygongeometry\/containscoordinate(_:)","title":"containsCoordinate(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"containsCoordinate"},{"kind":"text","text":"("},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","type":"topic"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/Se":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/SH":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMultiPolygonGeometry/containsPoint(_:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsPoint(_:)","navigatorTitle":[{"kind":"identifier","text":"containsPoint:"}],"role":"symbol","abstract":[{"text":"Check if the given point is contained within the polygon.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"containsPoint","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","kind":"typeIdentifier","text":"MPPoint"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"containsPoint(_:)","type":"topic","kind":"symbol","url":"\/documentation\/mapsindoors\/mpmultipolygongeometry\/containspoint(_:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMultiPolygonGeometry/encode(to:)":{"title":"encode(to:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"text":"Encoder","preciseIdentifier":"s:s7EncoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/encode(to:)","kind":"symbol","url":"\/documentation\/mapsindoors\/mpmultipolygongeometry\/encode(to:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMultiPolygonGeometry/init(dictionary:)":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/init(dictionary:)","url":"\/documentation\/mapsindoors\/mpmultipolygongeometry\/init(dictionary:)","title":"init(dictionary:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"`init`","kind":"identifier"},{"kind":"text","text":"("},{"text":"dictionary","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPMultiPolygonGeometry","kind":"typeIdentifier","text":"MPMultiPolygonGeometry"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDictionary:error:"}],"role":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"MPMultiPolygonGeometry"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"MPMultiPolygonGeometry"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MPMultiPolygonGeometry"}]},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/area","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/coordinates"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsCoordinate(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsCoordinate(_:ignorePolygonHoles:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsLineSegmentFromCoordinate(_:toCoordinate:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/containsPoint(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMultiPolygonGeometry\/init(dictionary:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometry"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPMultiPolygonGeometry","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeometry","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPGeometry","text":"MPGeometry","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1containsCoordinate(_:ignorePolygonHoles:)\/title","value":"containsCoordinate:ignorePolygonHoles:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsCoordinate:ignorePolygonHoles:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1containsCoordinate(_:ignorePolygonHoles:)\/fragments"},{"op":"replace","value":"coordinates","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1coordinates\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1coordinates\/fragments","op":"replace","value":[{"text":"coordinates","kind":"identifier"}]},{"op":"replace","value":"containsCoordinate:ignorePolygonHoles:containmentMetadata:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"containsCoordinate:ignorePolygonHoles:containmentMetadata:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1containsCoordinate(_:ignorePolygonHoles:containmentMetadata:)\/fragments"},{"op":"replace","value":"MPGeometryQueryProtocol","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol\/fragments","op":"replace","value":[{"text":"MPGeometryQueryProtocol","kind":"identifier"}]},{"value":"MPMultiPolygonGeometry","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry\/title"},{"value":[{"kind":"identifier","text":"MPMultiPolygonGeometry"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1area\/title","op":"replace","value":"area"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1area\/fragments","value":[{"text":"area","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryP\/title","op":"replace","value":"MPGeometryP"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometryP\/fragments","value":[{"text":"MPGeometryP","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometry\/title","op":"replace","value":"MPGeometry"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPGeometry\/fragments","value":[{"text":"MPGeometry","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1containsLineSegmentFromCoordinate(_:toCoordinate:)\/title","value":"containsLineSegmentFromCoordinate:toCoordinate:"},{"value":[{"text":"- ","kind":"text"},{"text":"containsLineSegmentFromCoordinate:toCoordinate:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1containsLineSegmentFromCoordinate(_:toCoordinate:)\/fragments","op":"replace"},{"value":"containsCoordinate:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1containsCoordinate(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsCoordinate:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1containsCoordinate(_:)\/fragments","op":"replace"},{"op":"replace","value":"containsPoint:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1containsPoint(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsPoint:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1containsPoint(_:)\/fragments"},{"value":"initWithDictionary:error:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1init(dictionary:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMultiPolygonGeometry~1init(dictionary:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDictionary:error:"}]}]}]}