{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"metadata":{"roleHeading":"Class","role":"symbol","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"MPOccupancyLiveUpdate","kind":"identifier"}],"title":"MPOccupancyLiveUpdate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPOccupancyLiveUpdate"}],"symbolKind":"class","externalID":"c:@M@MapsIndoors@objc(cs)MPOccupancyLiveUpdate"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPOccupancyLiveUpdate","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Model for live occupancy information for a given Location."}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPOccupancyLiveUpdate\/capacity","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPOccupancyLiveUpdate\/numberOfPeople"]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpoccupancyliveupdate"]},{"paths":["\/documentation\/mapsindoors\/mpoccupancyliveupdate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate"]},{"kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"title":"Conforms To","type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPOccupancyLiveUpdate"},"references":{"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/SE":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPOccupancyLiveUpdate/numberOfPeople":{"title":"numberOfPeople","url":"\/documentation\/mapsindoors\/mpoccupancyliveupdate\/numberofpeople","type":"topic","abstract":[{"text":"The number of people measured for a given Location.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"numberOfPeople","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"kind":"symbol","navigatorTitle":[{"text":"numberOfPeople","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPOccupancyLiveUpdate\/numberOfPeople"},"doc://com.mapspeople.mapsindoors/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","title":"Swift.Equatable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPOccupancyLiveUpdate/capacity":{"title":"capacity","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPOccupancyLiveUpdate\/capacity","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"capacity","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"The current capacity in terms of maximum number of people for a given Location."}],"navigatorTitle":[{"text":"capacity","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpoccupancyliveupdate\/capacity","kind":"symbol"},"doc://com.mapspeople.mapsindoors/Se":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se","title":"Swift.Decodable"},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapspeople.mapsindoors/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable"},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation/getLiveUpdate(forDomainType:)":{"url":"\/documentation\/mapsindoors\/mplocation\/getliveupdate(fordomaintype:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","type":"topic","title":"getLiveUpdate(forDomainType:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getLiveUpdate","kind":"identifier"},{"kind":"text","text":"("},{"text":"forDomainType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"text":"MPLiveUpdate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"getLiveUpdateForDomainType:"}],"abstract":[{"type":"text","text":"Get a live update based on a known domain type."}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPOccupancyLiveUpdate/initWithLiveUpdate:":{"url":"\/documentation\/mapsindoors\/mpoccupancyliveupdate\/initwithliveupdate:","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPOccupancyLiveUpdate\/initWithLiveUpdate:","type":"topic","title":"initWithLiveUpdate:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithLiveUpdate:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithLiveUpdate:","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPOccupancyLiveUpdate":{"url":"\/documentation\/mapsindoors\/mpoccupancyliveupdate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPOccupancyLiveUpdate","type":"topic","title":"MPOccupancyLiveUpdate","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPOccupancyLiveUpdate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPOccupancyLiveUpdate"}],"abstract":[{"text":"Model for live occupancy information for a given Location.","type":"text"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLiveUpdate":{"url":"\/documentation\/mapsindoors\/mpliveupdate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate","type":"topic","title":"MPLiveUpdate","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPLiveUpdate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPLiveUpdate"}],"abstract":[{"text":"Model for a Live Update. Used in ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation\/getLiveUpdate(forDomainType:)","type":"reference","isActive":true}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"MPOccupancyLiveUpdate","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPOccupancyLiveUpdate"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MPOccupancyLiveUpdate","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPOccupancyLiveUpdate\/capacity","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPOccupancyLiveUpdate\/numberOfPeople"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPOccupancyLiveUpdate\/initWithLiveUpdate:"],"title":"Instance Methods"}]},{"value":[{"kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate"],"type":"inheritsFrom","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"MPOccupancyLiveUpdate","kind":"identifier"},{"kind":"text","text":" : "},{"text":"MPLiveUpdate","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPLiveUpdate","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLiveUpdate"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPOccupancyLiveUpdate~1numberOfPeople\/title","value":"numberOfPeople"},{"value":[{"text":"numberOfPeople","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPOccupancyLiveUpdate~1numberOfPeople\/fragments"},{"value":"capacity","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPOccupancyLiveUpdate~1capacity\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPOccupancyLiveUpdate~1capacity\/fragments","value":[{"text":"capacity","kind":"identifier"}]},{"value":"getLiveUpdateForDomainType:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"getLiveUpdateForDomainType:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation~1getLiveUpdate(forDomainType:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPOccupancyLiveUpdate\/title","value":"MPOccupancyLiveUpdate","op":"replace"},{"value":[{"text":"MPOccupancyLiveUpdate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPOccupancyLiveUpdate\/fragments","op":"replace"},{"op":"replace","value":"MPLiveUpdate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MPLiveUpdate"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLiveUpdate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}