{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPersistentCacheGMSTileLayer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppersistentcachegmstilelayer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppersistentcachegmstilelayer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)GMSTileLayer"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/init(venue:andFloor:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/floor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/subdomains","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/urlTemplate","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/venueId"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/parseUrl()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPersistentCacheGMSTileLayer"}],"title":"MPPersistentCacheGMSTileLayer","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPPersistentCacheGMSTileLayer","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPPersistentCacheGMSTileLayer"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPPersistentCacheGMSTileLayer":{"role":"symbol","title":"MPPersistentCacheGMSTileLayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPersistentCacheGMSTileLayer"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPersistentCacheGMSTileLayer"}],"url":"\/documentation\/mapsindoors\/mppersistentcachegmstilelayer"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPPersistentCacheGMSTileLayer/floor":{"role":"symbol","title":"floor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPFloor","preciseIdentifier":"c:objc(cs)MPFloor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Floor property"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/floor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floor"}],"url":"\/documentation\/mapsindoors\/mppersistentcachegmstilelayer\/floor"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/objc(cs)GMSTileLayer":{"type":"unresolvable","title":"GMSTileLayer","identifier":"doc:\/\/MapsIndoors\/objc(cs)GMSTileLayer"},"doc://MapsIndoors/documentation/MapsIndoors/MPPersistentCacheGMSTileLayer/venueId":{"role":"symbol","title":"venueId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"venueId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Venue id"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/venueId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"venueId"}],"url":"\/documentation\/mapsindoors\/mppersistentcachegmstilelayer\/venueid"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPPersistentCacheGMSTileLayer/urlTemplate":{"role":"symbol","title":"urlTemplate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlTemplate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The url template string to use when fetching tiles. Must have format “prefix{param_1}infix{param_N}suffix”, e.g.: “http:\/\/tiles.url.com\/{floor}\/{x}\/{y}\/{zoom}.png”"},{"type":"text","text":" "},{"type":"text","text":"By default the implementation of this tilelayer will look for {venueId}\/{style}\/{buildingId}\/{floor}\/{z}\/{x}\/{y}, where x, y and z is mandatory."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/urlTemplate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"urlTemplate"}],"url":"\/documentation\/mapsindoors\/mppersistentcachegmstilelayer\/urltemplate"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/documentation/MapsIndoors/MPPersistentCacheGMSTileLayer/init(venue:andFloor:)":{"role":"symbol","title":"init(venue:andFloor:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"venue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPVenue","preciseIdentifier":"c:objc(cs)MPVenue"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andFloor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPFloor","preciseIdentifier":"c:objc(cs)MPFloor"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Instantiate using a venue and a floor object."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/init(venue:andFloor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithVenue:andFloor:"}],"url":"\/documentation\/mapsindoors\/mppersistentcachegmstilelayer\/init(venue:andfloor:)"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MPPersistentCacheGMSTileLayer/parseUrl()":{"role":"symbol","title":"parseUrl()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseUrl"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Parse the url template. Normally, this is done automatically"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/parseUrl()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parseUrl"}],"url":"\/documentation\/mapsindoors\/mppersistentcachegmstilelayer\/parseurl()"},"doc://MapsIndoors/documentation/MapsIndoors/MPPersistentCacheGMSTileLayer/subdomains":{"role":"symbol","title":"subdomains","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subdomains"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Array of strings identifying subdomains. If this property is set, and the url template contains the parameter {subdomain}, the tilelayer will do round-robin over the subdomains specified."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/subdomains","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subdomains"}],"url":"\/documentation\/mapsindoors\/mppersistentcachegmstilelayer\/subdomains"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPPersistentCacheGMSTileLayer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPPersistentCacheGMSTileLayer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPPersistentCacheGMSTileLayer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/floor","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/subdomains","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/urlTemplate","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/venueId"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/init(venue:andFloor:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPersistentCacheGMSTileLayer\/parseUrl()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPersistentCacheGMSTileLayer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"GMSTileLayer","preciseIdentifier":"c:objc(cs)GMSTileLayer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer\/title","value":"MPPersistentCacheGMSTileLayer"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer\/fragments","value":[{"kind":"identifier","text":"MPPersistentCacheGMSTileLayer"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer~1floor\/title","value":"floor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer~1floor\/fragments","value":[{"kind":"identifier","text":"floor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer~1venueId\/title","value":"venueId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer~1venueId\/fragments","value":[{"kind":"identifier","text":"venueId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer~1urlTemplate\/title","value":"urlTemplate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer~1urlTemplate\/fragments","value":[{"kind":"identifier","text":"urlTemplate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer~1init(venue:andFloor:)\/title","value":"initWithVenue:andFloor:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer~1init(venue:andFloor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVenue:andFloor:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer~1parseUrl()\/title","value":"parseUrl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer~1parseUrl()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parseUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer~1subdomains\/title","value":"subdomains"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPersistentCacheGMSTileLayer~1subdomains\/fragments","value":[{"kind":"identifier","text":"subdomains"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}