{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPolygonGeometry"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppolygongeometry"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppolygongeometry"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometry"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)NSCopying","doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding","doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/holes","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/path"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/gmsPathForPath()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/gmsPathsForHoles()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPolygonGeometry"}],"title":"MPPolygonGeometry","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPPolygonGeometry","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPPolygonGeometry"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPPolygonGeometry/gmsPathsForHoles()":{"role":"symbol","title":"gmsPathsForHoles()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gmsPathsForHoles"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"GMSPath","preciseIdentifier":"c:objc(cs)GMSPath"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Return an array of GMSPaths for the hole in the polygon."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/gmsPathsForHoles()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gmsPathsForHoles"}],"url":"\/documentation\/mapsindoors\/mppolygongeometry\/gmspathsforholes()"},"doc://MapsIndoors/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPGeometry":{"role":"symbol","title":"MPGeometry","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeometry"}],"abstract":[{"type":"text","text":"Basic geometry class holding one or more coordinate sets"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPGeometry"}],"url":"\/documentation\/mapsindoors\/mpgeometry"},"doc://MapsIndoors/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCopying"},"doc://MapsIndoors/documentation/MapsIndoors/MPPolygonGeometry/gmsPathForPath()":{"role":"symbol","title":"gmsPathForPath()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gmsPathForPath"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GMSPath","preciseIdentifier":"c:objc(cs)GMSPath"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get a GMSPath representing the path of the polygon."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/gmsPathForPath()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gmsPathForPath"}],"url":"\/documentation\/mapsindoors\/mppolygongeometry\/gmspathforpath()"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPPolygonGeometry/holes":{"role":"symbol","title":"holes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"holes"},{"kind":"text","text":": [[["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]]]?"}],"abstract":[{"type":"text","text":"Optional array of polygon holes."},{"type":"text","text":" "},{"type":"text","text":"A polygon hole is an array of [longitude, latitude] pairs."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/holes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"holes"}],"url":"\/documentation\/mapsindoors\/mppolygongeometry\/holes"},"doc://MapsIndoors/documentation/MapsIndoors/MPPolygonGeometry":{"role":"symbol","title":"MPPolygonGeometry","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPolygonGeometry"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPolygonGeometry"}],"url":"\/documentation\/mapsindoors\/mppolygongeometry"},"doc://MapsIndoors/documentation/MapsIndoors/MPGeometryQueryProtocol":{"role":"symbol","title":"MPGeometryQueryProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPGeometryQueryProtocol"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometryQueryProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPGeometryQueryProtocol"}],"url":"\/documentation\/mapsindoors\/mpgeometryqueryprotocol"},"doc://MapsIndoors/documentation/MapsIndoors/MPPolygonGeometry/path":{"role":"symbol","title":"path","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"path"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]]?"}],"abstract":[{"type":"text","text":"The polygon boundary.  Consists of pairs of [longitude, latitude]."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/path","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"path"}],"url":"\/documentation\/mapsindoors\/mppolygongeometry\/path"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/objc(pl)AbstractJSONModelProtocol":{"type":"unresolvable","title":"JSONModel.AbstractJSONModelProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPPolygonGeometry"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPPolygonGeometry"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPPolygonGeometry"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/holes","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/path"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/gmsPathForPath()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPolygonGeometry\/gmsPathsForHoles()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPolygonGeometry"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPGeometry","preciseIdentifier":"c:objc(cs)MPGeometry","text":"MPGeometry"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1gmsPathsForHoles()\/title","value":"gmsPathsForHoles"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1gmsPathsForHoles()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gmsPathsForHoles"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometry\/title","value":"MPGeometry"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometry\/fragments","value":[{"kind":"identifier","text":"MPGeometry"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1gmsPathForPath()\/title","value":"gmsPathForPath"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1gmsPathForPath()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gmsPathForPath"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1holes\/title","value":"holes"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1holes\/fragments","value":[{"kind":"identifier","text":"holes"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry\/title","value":"MPPolygonGeometry"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry\/fragments","value":[{"kind":"identifier","text":"MPPolygonGeometry"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol\/title","value":"MPGeometryQueryProtocol"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPGeometryQueryProtocol\/fragments","value":[{"kind":"identifier","text":"MPGeometryQueryProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1path\/title","value":"path"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPolygonGeometry~1path\/fragments","value":[{"kind":"identifier","text":"path"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}