{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPPositionProvider"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Protocol specifying how an indoor positioning provider should be implemented if the users location is to be exposed to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"},{"type":"text","text":"."}],"seeAlsoSections":[{"title":"Show user position on the map","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult"],"generated":true}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"variants":[{"paths":["\/documentation\/mapsindoors\/mppositionprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppositionprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider\/delegate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider\/latestPosition"]}],"metadata":{"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPPositionProvider","roleHeading":"Protocol","navigatorTitle":[{"text":"MPPositionProvider","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProvider"}],"symbolKind":"protocol","title":"MPPositionProvider"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl/delegate":{"role":"symbol","abstract":[{"text":"Listen to events.","type":"text"}],"kind":"symbol","required":true,"url":"\/documentation\/mapsindoors\/mpmapcontrol\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/delegate","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPMapControlDelegate","text":"MPMapControlDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"delegate"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"abstract":[{"type":"text","text":"This is the control object for the visual representation of the MapsIndoors SDK."}],"url":"\/documentation\/mapsindoors\/mpmapcontrol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPMapControl"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"type":"topic","kind":"symbol","title":"MPMapControl","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionResult":{"role":"symbol","abstract":[{"text":"Instances of this class holds a Position result returned by a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","isActive":true},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mppositionresult","navigatorTitle":[{"text":"MPPositionResult","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPPositionResult"}],"title":"MPPositionResult"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPMapControlDelegate","kind":"identifier"}],"abstract":[{"text":"Delegate protocol specification to react to the events that ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true},{"text":" emits.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpmapcontroldelegate","title":"MPMapControlDelegate","type":"topic","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPMapControlDelegate"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionProvider/delegate":{"role":"symbol","abstract":[{"text":"The receiver of user positions. ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"},{"type":"text","text":" will hook into this delegate to be able to show the current"},{"type":"text","text":" "},{"type":"text","text":"user position on the currently shown map."},{"type":"text","text":" "},{"type":"text","text":"If your app needs to be notified about each new user position, you should create a class conforming to"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate"},{"type":"text","text":" and set that as the "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl\/delegate","isActive":true,"type":"reference"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"User position updates will then be available to you via the"},{"type":"text","text":" "},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/onPositionUpdate(position:)","type":"reference"},{"type":"text","text":" function that you implement in your class."}],"kind":"symbol","required":true,"url":"\/documentation\/mapsindoors\/mppositionprovider\/delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider\/delegate","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"text":"MPPositionProviderDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPPositionProviderDelegate"},{"kind":"text","text":"?"}],"title":"delegate"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionProvider/latestPosition":{"role":"symbol","abstract":[{"type":"text","text":"Latest position result if any."}],"kind":"symbol","required":true,"url":"\/documentation\/mapsindoors\/mppositionprovider\/latestposition","navigatorTitle":[{"text":"latestPosition","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider\/latestPosition","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"latestPosition"},{"kind":"text","text":": "},{"text":"MPPositionResult","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPositionResult","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"latestPosition"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","alt":null,"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPPositionProvider":{"url":"\/documentation\/mapsindoors\/mppositionprovider","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionProvider"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPPositionProvider"}],"title":"MPPositionProvider","abstract":[{"type":"text","text":"Protocol specifying how an indoor positioning provider should be implemented if the users location is to be exposed to "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true},{"type":"text","text":"."}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControlDelegate/onPositionUpdate(position:)":{"url":"\/documentation\/mapsindoors\/mpmapcontroldelegate\/onpositionupdate(position:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControlDelegate\/onPositionUpdate(position:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPositionUpdate"},{"text":"(","kind":"text"},{"text":"position","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPositionResult","text":"MPPositionResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","required":true,"title":"onPositionUpdate(position:)","abstract":[{"type":"text","text":"Called when "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","isActive":true,"type":"reference"},{"type":"text","text":" receives a new user position from the active "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This is the method you should implement if your app needs to be notified about each new user position."}],"navigatorTitle":[{"text":"onPositionUpdate:","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MPPositionProvider","op":"replace"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MPPositionProvider","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MPPositionProvider"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider\/delegate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionProvider\/latestPosition"]}]},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPPositionResult"],"generated":true,"title":"Show user position on the map"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"MPPositionProvider","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1delegate\/title","value":"delegate"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"text":"MPMapControl","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult\/title","value":"MPPositionResult"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionResult\/fragments","value":[{"text":"MPPositionResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/title","value":"MPMapControlDelegate"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate\/fragments","op":"replace","value":[{"text":"MPMapControlDelegate","kind":"identifier"}]},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider~1delegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider~1latestPosition\/title","op":"replace","value":"latestPosition"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider~1latestPosition\/fragments","value":[{"kind":"identifier","text":"latestPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider\/title","value":"MPPositionProvider"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPPositionProvider\/fragments","value":[{"text":"MPPositionProvider","kind":"identifier"}],"op":"replace"},{"value":"onPositionUpdate:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1onPositionUpdate(position:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onPositionUpdate:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControlDelegate~1onPositionUpdate(position:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}