{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionResult"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mppositionresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mppositionresult"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)JSONModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)NSCopying","doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding","doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Position result model"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionResult"}],"title":"MPPositionResult","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPPositionResult","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPPositionResult"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/init(wirelessPositionData:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/geometry","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/headingAvailable","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/properties","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/provider","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/getAge()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/getFloor()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/getHeadingDegrees()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/getProbability()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/getRoundtrip()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/setHeadingDegrees(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/setProbability(_:)"]}],"references":{"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult/setProbability(_:)":{"role":"symbol","title":"setProbability(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setProbability"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/setProbability(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setProbability:"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/setprobability(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult/getAge()":{"deprecated":true,"role":"symbol","title":"getAge()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAge"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the age of the this position result; the time in seconds since the position was first determined."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/getAge()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAge"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/getage()"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult/properties":{"role":"symbol","title":"properties","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"properties"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMutableDictionary","preciseIdentifier":"c:objc(cs)NSMutableDictionary"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Properties dictionary"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/properties","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"properties"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/properties"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult/getProbability()":{"role":"symbol","title":"getProbability()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getProbability"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Get the probability of the position. This is a radius in meters. Can be used to generate an approximation circle."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/getProbability()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getProbability"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/getprobability()"},"doc://MapsIndoors/objc(cs)JSONModel":{"type":"unresolvable","title":"JSONModel","identifier":"doc:\/\/MapsIndoors\/objc(cs)JSONModel"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult/init(wirelessPositionData:)":{"role":"symbol","title":"init(wirelessPositionData:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"wirelessPositionData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/init(wirelessPositionData:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithWirelessPositionData:"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/init(wirelesspositiondata:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult/headingAvailable":{"role":"symbol","title":"headingAvailable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headingAvailable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"The availability of the heading, returns NO if heading is not available, default is YES"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/headingAvailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"headingAvailable"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/headingavailable"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCopying"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult/getRoundtrip()":{"deprecated":true,"role":"symbol","title":"getRoundtrip()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRoundtrip"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Get the roundtrip property"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/getRoundtrip()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getRoundtrip"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/getroundtrip()"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult":{"role":"symbol","title":"MPPositionResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionResult"}],"abstract":[{"type":"text","text":"Position result model"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPPositionResult"}],"url":"\/documentation\/mapsindoors\/mppositionresult"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult/provider":{"role":"symbol","title":"provider","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Position provider that delivered this position"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/provider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"provider"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/provider"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult/type":{"deprecated":true,"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Type property"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/type"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult/setHeadingDegrees(_:)":{"role":"symbol","title":"setHeadingDegrees(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setHeadingDegrees"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Set the heading of the position result in degrees from north"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/setHeadingDegrees(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setHeadingDegrees:"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/setheadingdegrees(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult/getFloor()":{"role":"symbol","title":"getFloor()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFloor"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the floor index property"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/getFloor()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getFloor"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/getfloor()"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult/getHeadingDegrees()":{"role":"symbol","title":"getHeadingDegrees()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getHeadingDegrees"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Get the heading in degrees from north"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/getHeadingDegrees()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getHeadingDegrees"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/getheadingdegrees()"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPPositionResult/geometry":{"role":"symbol","title":"geometry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The geographic point geometry of the position"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/geometry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"geometry"}],"url":"\/documentation\/mapsindoors\/mppositionresult\/geometry"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/objc(pl)AbstractJSONModelProtocol":{"type":"unresolvable","title":"JSONModel.AbstractJSONModelProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol"},"doc://MapsIndoors/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPPositionResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPPositionResult"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPPositionResult"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/geometry","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/headingAvailable","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/properties","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/provider","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/getAge()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/getFloor()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/getHeadingDegrees()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/getProbability()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/getRoundtrip()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/init(wirelessPositionData:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/setHeadingDegrees(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPPositionResult\/setProbability(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPPositionResult"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSONModel","preciseIdentifier":"c:objc(cs)JSONModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1setProbability(_:)\/title","value":"setProbability:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1setProbability(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setProbability:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1getAge()\/title","value":"getAge"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1getAge()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAge"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1properties\/title","value":"properties"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1properties\/fragments","value":[{"kind":"identifier","text":"properties"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1getProbability()\/title","value":"getProbability"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1getProbability()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getProbability"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1init(wirelessPositionData:)\/title","value":"initWithWirelessPositionData:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1init(wirelessPositionData:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithWirelessPositionData:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1headingAvailable\/title","value":"headingAvailable"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1headingAvailable\/fragments","value":[{"kind":"identifier","text":"headingAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1getRoundtrip()\/title","value":"getRoundtrip"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1getRoundtrip()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getRoundtrip"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult\/title","value":"MPPositionResult"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult\/fragments","value":[{"kind":"identifier","text":"MPPositionResult"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1provider\/title","value":"provider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1provider\/fragments","value":[{"kind":"identifier","text":"provider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1setHeadingDegrees(_:)\/title","value":"setHeadingDegrees:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1setHeadingDegrees(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setHeadingDegrees:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1getFloor()\/title","value":"getFloor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1getFloor()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getFloor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1getHeadingDegrees()\/title","value":"getHeadingDegrees"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1getHeadingDegrees()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getHeadingDegrees"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1geometry\/title","value":"geometry"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPPositionResult~1geometry\/fragments","value":[{"kind":"identifier","text":"geometry"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}