{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/init()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/init(from:)"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/near","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/query","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/queryProperties"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/encode(to:)"],"title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery"},"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"title":"Conforms To","type":"conformsTo"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPQuery"}],"roleHeading":"Class","role":"symbol","externalID":"c:@M@MapsIndoors@objc(cs)MPQuery","title":"MPQuery","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPQuery"}],"symbolKind":"class"},"abstract":[{"text":"Query object used when making a request to ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","isActive":true,"type":"reference"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPQuery"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"seeAlsoSections":[{"generated":true,"title":"Searching for Locations","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpquery"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpquery"]}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation":{"url":"\/documentation\/mapsindoors\/mplocation","abstract":[{"type":"text","text":"This holds the data for a single location and a marker to display the data on a map."}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPLocation","kind":"identifier"}],"title":"MPLocation","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MPLocation","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPQuery/query":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"query","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","role":"symbol","type":"topic","title":"query","url":"\/documentation\/mapsindoors\/mpquery\/query","abstract":[{"text":"Single line search string.","type":"text"}],"navigatorTitle":[{"text":"query","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/query"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPQuery/queryProperties":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"queryProperties","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"kind":"symbol","role":"symbol","type":"topic","title":"queryProperties","abstract":[{"text":"List of properties that ","type":"text"},{"type":"codeVoice","code":"MPLocationService"},{"text":" will take into account when finding and sorting matching locations. By default, ","type":"text"},{"code":"MPLocationService","type":"codeVoice"},{"type":"text","text":" will search in the name, externalId and aliases properties. Possible other properties depend on the location content. E.g. if an "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","isActive":true},{"type":"text","text":" has a field called "},{"type":"codeVoice","code":"booking-id"},{"type":"text","text":", the string “booking-id” (case-sensitive) may be added. Query properties added that do not exist in any Locations will be ignored."}],"url":"\/documentation\/mapsindoors\/mpquery\/queryproperties","navigatorTitle":[{"text":"queryProperties","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/queryProperties"},"doc://com.mapspeople.mapsindoors/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPQuery/near":{"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/near","type":"topic","url":"\/documentation\/mapsindoors\/mpquery\/near","title":"near","navigatorTitle":[{"kind":"identifier","text":"near"}],"kind":"symbol","abstract":[{"text":"Geographical point that serve as additional horizontal and vertical proximity context for a search. If supplied, locations that are closer to the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/near"},{"type":"text","text":" point will be ranked higher. The proximity calculation is based on direct lines and does not reflect real world travel distances."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"near","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPPoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPQuery/init(from:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/init(from:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpquery\/init(from:)","title":"init(from:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPQuery/init()":{"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic","title":"init()","url":"\/documentation\/mapsindoors\/mpquery\/init()","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/init()"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPQuery/encode(to:)":{"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/encode(to:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s7EncoderP","text":"Encoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/mapsindoors\/mpquery\/encode(to:)","kind":"symbol","title":"encode(to:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/locationsWith(query:filter:)":{"required":true,"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/locationswith(query:filter:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)","abstract":[{"type":"text","text":"Search for MPLocations using MPQuery and\/or MPFilter."}],"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"locationsWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"query","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPQuery","text":"MPQuery","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"filter"},{"kind":"text","text":": "},{"text":"MPFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPFilter"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ["},{"text":"MPLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocation"},{"kind":"text","text":"]"}],"kind":"symbol","title":"locationsWith(query:filter:)","navigatorTitle":[{"kind":"identifier","text":"locationsWithQuery:filter:completionHandler:"}]},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","type":"image","alt":null},"doc://com.mapspeople.mapsindoors/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapspeople.mapsindoors/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","title":"Swift.Equatable"},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFilter":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPFilter","kind":"identifier"}],"navigatorTitle":[{"text":"MPFilter","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpfilter","kind":"symbol","abstract":[{"text":"Filter object used when making a request to e.g. ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter","role":"symbol","type":"topic","title":"MPFilter"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPQuery":{"abstract":[{"type":"text","text":"Query object used when making a request to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/locationsWith(query:filter:)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPQuery","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPQuery"}],"url":"\/documentation\/mapsindoors\/mpquery","kind":"symbol","title":"MPQuery"},"doc://com.mapspeople.mapsindoors/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPQuery"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MPQuery","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPQuery"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/near","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/query","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/queryProperties"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPQuery\/init()"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"value":[{"generated":true,"title":"Searching for Locations","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFilter"]}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"MPQuery","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"MPLocation","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/fragments","value":[{"text":"MPLocation","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"query","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery~1query\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery~1query\/fragments","value":[{"text":"query","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery~1queryProperties\/title","value":"queryProperties","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery~1queryProperties\/fragments","value":[{"text":"queryProperties","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery~1near\/title","value":"near"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery~1near\/fragments","value":[{"kind":"identifier","text":"near"}]},{"op":"replace","value":"init","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery~1init()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery~1init()\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/title","value":"locationsWithQuery:filter:completionHandler:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1locationsWith(query:filter:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"locationsWithQuery:filter:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter\/title","value":"MPFilter"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFilter\/fragments","value":[{"text":"MPFilter","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MPQuery","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPQuery\/fragments","value":[{"kind":"identifier","text":"MPQuery"}]}]}]}