{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MPRouteLegType","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"MPRouteLegType","role":"symbol","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPRouteLegType","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@E@MPRouteLegType","navigatorTitle":[{"kind":"identifier","text":"MPRouteLegType"}],"roleHeading":"Enumeration","modules":[{"name":"MapsIndoors"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType\/External","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType\/MapsIndoors"]},{"title":"Initializers","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType\/Equatable-Implementations","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType\/RawRepresentable-Implementations"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mproutelegtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mproutelegtype"]}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH","doc:\/\/com.mapspeople.mapsindoors\/SY"],"type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLegType/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType\/RawRepresentable-Implementations","abstract":[],"url":"\/documentation\/mapsindoors\/mproutelegtype\/rawrepresentable-implementations","kind":"article","type":"topic","role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLegType/External":{"url":"\/documentation\/mapsindoors\/mproutelegtype\/external","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType\/External","title":"MPRouteLegType.External","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"External","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPRouteLegTypeExternal"}],"kind":"symbol","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLegType/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType\/MapsIndoors","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapsIndoors","kind":"identifier"}],"title":"MPRouteLegType.MapsIndoors","navigatorTitle":[{"text":"MPRouteLegTypeMapsIndoors","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mproutelegtype\/mapsindoors","abstract":[],"kind":"symbol","role":"symbol"},"doc://com.mapspeople.mapsindoors/SY":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SY","title":"Swift.RawRepresentable"},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"type":"image","identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLegType/Equatable-Implementations":{"url":"\/documentation\/mapsindoors\/mproutelegtype\/equatable-implementations","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType\/Equatable-Implementations","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","kind":"article","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLegType":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType","abstract":[],"url":"\/documentation\/mapsindoors\/mproutelegtype","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRouteLegType"}],"role":"symbol","title":"MPRouteLegType","navigatorTitle":[{"text":"MPRouteLegType","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/SE":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE","title":"Swift.Encodable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/Se":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se","title":"Swift.Decodable"},"doc://com.mapspeople.mapsindoors/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable"},"doc://com.mapspeople.mapsindoors/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","title":"Swift.Equatable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLegType/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType\/init(rawValue:)","title":"init(rawValue:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mproutelegtype\/init(rawvalue:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MPRouteLegType"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"kind":"identifier","text":"MPRouteLegType"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPRouteLegType"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType\/External","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLegType\/MapsIndoors"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteLegType"},{"kind":"text","text":": "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLegType~1External\/title","value":"MPRouteLegTypeExternal"},{"value":[{"kind":"identifier","text":"MPRouteLegTypeExternal"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLegType~1External\/fragments","op":"replace"},{"op":"replace","value":"MPRouteLegTypeMapsIndoors","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLegType~1MapsIndoors\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLegType~1MapsIndoors\/fragments","value":[{"kind":"identifier","text":"MPRouteLegTypeMapsIndoors"}]},{"value":"MPRouteLegType","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLegType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MPRouteLegType"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLegType\/fragments"}]}]}