{"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteBounds","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MapsIndoors"}],"roleHeading":"Protocol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPRouteBounds"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPRouteBounds","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPRouteBounds","kind":"identifier"}],"symbolKind":"protocol","title":"MPRouteBounds"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteBounds\/northeast","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteBounds\/southwest"]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRouteBounds"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mapsindoors\/mproutebounds"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mproutebounds"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteBounds/southwest":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"southwest","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPRouteCoordinate","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRouteCoordinate"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteBounds\/southwest","abstract":[{"type":"text","text":"South west corner coordinate."}],"navigatorTitle":[{"text":"southwest","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mproutebounds\/southwest","role":"symbol","required":true,"title":"southwest"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteBounds":{"url":"\/documentation\/mapsindoors\/mproutebounds","navigatorTitle":[{"text":"MPRouteBounds","kind":"identifier"}],"kind":"symbol","title":"MPRouteBounds","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPRouteBounds","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteBounds"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteBounds/northeast":{"abstract":[{"text":"North east corner coordinate.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"northeast","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteBounds\/northeast","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"northeast"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRouteCoordinate","text":"MPRouteCoordinate"},{"text":"?","kind":"text"}],"url":"\/documentation\/mapsindoors\/mproutebounds\/northeast","title":"northeast"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","value":"MPRouteBounds","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MPRouteBounds","kind":"identifier"}]},{"value":[{"text":"MPRouteBounds","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteBounds\/northeast","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteBounds\/southwest"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteBounds"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteBounds~1southwest\/title","value":"southwest"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteBounds~1southwest\/fragments","value":[{"kind":"identifier","text":"southwest"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteBounds\/title","value":"MPRouteBounds"},{"value":[{"kind":"identifier","text":"MPRouteBounds"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteBounds\/fragments"},{"value":"northeast","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteBounds~1northeast\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteBounds~1northeast\/fragments","value":[{"text":"northeast","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}