{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mproutecoordinate"]},{"paths":["\/documentation\/mapsindoors\/mproutecoordinate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate\/floor_name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate\/label","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate\/lat","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate\/lng","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate\/zLevel"],"title":"Instance Properties"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRouteCoordinate"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteCoordinate"}],"title":"MPRouteCoordinate","roleHeading":"Protocol","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"MPRouteCoordinate","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPRouteCoordinate"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteCoordinate/floor_name":{"url":"\/documentation\/mapsindoors\/mproutecoordinate\/floor_name","abstract":[{"text":"Floor name for this coordinate.","type":"text"}],"type":"topic","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate\/floor_name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floor_name"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"floor_name","kind":"symbol","navigatorTitle":[{"text":"floor_name","kind":"identifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteCoordinate/zLevel":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate\/zLevel","url":"\/documentation\/mapsindoors\/mproutecoordinate\/zlevel","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zLevel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"}],"abstract":[{"text":"Floor level index.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"zLevel","kind":"identifier"}],"title":"zLevel","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteCoordinate/lng":{"role":"symbol","abstract":[{"text":"Longitude angle.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate\/lng","required":true,"navigatorTitle":[{"text":"lng","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mproutecoordinate\/lng","title":"lng","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"lng","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"}],"kind":"symbol","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteCoordinate":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mproutecoordinate","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPRouteCoordinate","kind":"identifier"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"MPRouteCoordinate","kind":"identifier"}],"title":"MPRouteCoordinate","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteCoordinate/label":{"abstract":[{"type":"text","text":"Label for displaying contextual information about this coordinate."}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate\/label","title":"label","role":"symbol","navigatorTitle":[{"text":"label","kind":"identifier"}],"required":true,"url":"\/documentation\/mapsindoors\/mproutecoordinate\/label","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"label","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteCoordinate/lat":{"url":"\/documentation\/mapsindoors\/mproutecoordinate\/lat","abstract":[{"text":"Latitude angle.","type":"text"}],"type":"topic","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate\/lat","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"}],"title":"lat","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"lat"}],"role":"symbol"},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"type":"image","identifier":"MapsPeopleWhite.png"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"value":"MPRouteCoordinate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPRouteCoordinate"}],"op":"replace"},{"value":[{"text":"MPRouteCoordinate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate\/floor_name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate\/label","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate\/lat","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate\/lng","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteCoordinate\/zLevel"],"title":"Instance Properties"}],"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteCoordinate"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteCoordinate~1floor_name\/title","op":"replace","value":"floor_name"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteCoordinate~1floor_name\/fragments","value":[{"kind":"identifier","text":"floor_name"}]},{"op":"replace","value":"zLevel","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteCoordinate~1zLevel\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteCoordinate~1zLevel\/fragments","op":"replace","value":[{"text":"zLevel","kind":"identifier"}]},{"value":"lng","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteCoordinate~1lng\/title","op":"replace"},{"value":[{"kind":"identifier","text":"lng"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteCoordinate~1lng\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteCoordinate\/title","value":"MPRouteCoordinate"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteCoordinate\/fragments","op":"replace","value":[{"text":"MPRouteCoordinate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteCoordinate~1label\/title","value":"label"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteCoordinate~1label\/fragments","value":[{"text":"label","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteCoordinate~1lat\/title","value":"lat"},{"value":[{"text":"lat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteCoordinate~1lat\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}