{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoute"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mproute-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mproute-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)JSONModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)NSCopying","doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding","doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the "},{"type":"codeVoice","code":"MPDirectionsService"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoute"}],"title":"MPRoute","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPRoute","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPRoute"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/bounds","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/copyrights","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/distance","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/duration","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/legs","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/overview_polyline","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/restrictions","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/summary","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/warnings"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/findNearestRouteSegmentPath(from:floor:)"]}],"references":{"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCopying"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoute-swift.class/bounds":{"role":"symbol","title":"bounds","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bounds"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MPRouteBounds","preciseIdentifier":"c:objc(cs)MPRouteBounds"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The route bounds."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/bounds","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bounds"}],"url":"\/documentation\/mapsindoors\/mproute-swift.class\/bounds"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoute-swift.class/copyrights":{"role":"symbol","title":"copyrights","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"copyrights"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/copyrights","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyrights"}],"url":"\/documentation\/mapsindoors\/mproute-swift.class\/copyrights"},"doc://MapsIndoors/objc(pl)AbstractJSONModelProtocol":{"type":"unresolvable","title":"JSONModel.AbstractJSONModelProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoute-swift.class/distance":{"role":"symbol","title":"distance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distance"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The full distance in meters."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/distance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"distance"}],"url":"\/documentation\/mapsindoors\/mproute-swift.class\/distance"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoute-swift.class/summary":{"role":"symbol","title":"summary","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"summary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Textual summary of the route. May be empty\/nil."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/summary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"summary"}],"url":"\/documentation\/mapsindoors\/mproute-swift.class\/summary"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoute-swift.class/legs":{"role":"symbol","title":"legs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"legs"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"MPRouteLegProtocol","preciseIdentifier":"c:objc(pl)MPRouteLeg"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The route legs: the different route components. Typically a route from 1st floor to 2nd floor will consist of two route legs."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/legs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"legs"}],"url":"\/documentation\/mapsindoors\/mproute-swift.class\/legs"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoute-swift.class":{"role":"symbol","title":"MPRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoute"}],"abstract":[{"type":"text","text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the "},{"type":"codeVoice","code":"MPDirectionsService"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRoute"}],"url":"\/documentation\/mapsindoors\/mproute-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoute-swift.class/overview_polyline":{"role":"symbol","title":"overview_polyline","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"overview_polyline"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MPEncodedPolyline","preciseIdentifier":"c:objc(cs)MPEncodedPolyline"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/overview_polyline","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"overview_polyline"}],"url":"\/documentation\/mapsindoors\/mproute-swift.class\/overview_polyline"},"doc://MapsIndoors/objc(cs)JSONModel":{"type":"unresolvable","title":"JSONModel","identifier":"doc:\/\/MapsIndoors\/objc(cs)JSONModel"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoute-swift.class/duration":{"role":"symbol","title":"duration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The full duration in seconds based on travel times for each leg\/step."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/duration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"duration"}],"url":"\/documentation\/mapsindoors\/mproute-swift.class\/duration"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoute-swift.class/findNearestRouteSegmentPath(from:floor:)":{"role":"symbol","title":"findNearestRouteSegmentPath(from:floor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"findNearestRouteSegmentPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"floor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPRouteSegmentPath","preciseIdentifier":"c:@S@MPRouteSegmentPath"}],"abstract":[{"type":"text","text":"Find route segment path (route leg and route step) nearest to a point and floor index."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/findNearestRouteSegmentPath(from:floor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"findNearestRouteSegmentPathFromPoint:floor:"}],"url":"\/documentation\/mapsindoors\/mproute-swift.class\/findnearestroutesegmentpath(from:floor:)"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoute-swift.class/restrictions":{"role":"symbol","title":"restrictions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"restrictions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The restrictions that apply for the route. May be empty\/nil"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/restrictions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"restrictions"}],"url":"\/documentation\/mapsindoors\/mproute-swift.class\/restrictions"},"doc://MapsIndoors/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoute-swift.class/warnings":{"role":"symbol","title":"warnings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"warnings"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Textual warning for the route. May be empty\/nil."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/warnings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"warnings"}],"url":"\/documentation\/mapsindoors\/mproute-swift.class\/warnings"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPRoute"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPRoute"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPRoute"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/bounds","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/copyrights","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/distance","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/duration","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/legs","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/overview_polyline","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/restrictions","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/summary","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/warnings"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoute-swift.class\/findNearestRouteSegmentPath(from:floor:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)JSONModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoute"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSONModel","preciseIdentifier":"c:objc(cs)JSONModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1bounds\/title","value":"bounds"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1bounds\/fragments","value":[{"kind":"identifier","text":"bounds"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1copyrights\/title","value":"copyrights"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1copyrights\/fragments","value":[{"kind":"identifier","text":"copyrights"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1distance\/title","value":"distance"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1distance\/fragments","value":[{"kind":"identifier","text":"distance"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1summary\/title","value":"summary"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1summary\/fragments","value":[{"kind":"identifier","text":"summary"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1legs\/title","value":"legs"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1legs\/fragments","value":[{"kind":"identifier","text":"legs"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class\/title","value":"MPRoute"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class\/fragments","value":[{"kind":"identifier","text":"MPRoute"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1overview_polyline\/title","value":"overview_polyline"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1overview_polyline\/fragments","value":[{"kind":"identifier","text":"overview_polyline"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1duration\/title","value":"duration"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1duration\/fragments","value":[{"kind":"identifier","text":"duration"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1findNearestRouteSegmentPath(from:floor:)\/title","value":"findNearestRouteSegmentPathFromPoint:floor:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1findNearestRouteSegmentPath(from:floor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"findNearestRouteSegmentPathFromPoint:floor:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1restrictions\/title","value":"restrictions"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1restrictions\/fragments","value":[{"kind":"identifier","text":"restrictions"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1warnings\/title","value":"warnings"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoute-swift.class~1warnings\/fragments","value":[{"kind":"identifier","text":"warnings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}