{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoutingProviderDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mproutingproviderdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mproutingproviderdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProviderDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Directions service delegate"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoutingProviderDelegate"}],"title":"MPRoutingProviderDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)MPRoutingProviderDelegate","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPRoutingProviderDelegate"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProviderDelegate\/onRouteResultReady(_:)"]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProviderDelegate/onRouteResultReady(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onRouteResultReady:"}],"role":"symbol","title":"onRouteResultReady(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRouteResultReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPRoute","preciseIdentifier":"c:objc(cs)MPRoute"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProviderDelegate\/onRouteResultReady(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mproutingproviderdelegate\/onrouteresultready(_:)"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProviderDelegate":{"role":"symbol","title":"MPRoutingProviderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoutingProviderDelegate"}],"abstract":[{"type":"text","text":"Directions service delegate"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProviderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRoutingProviderDelegate"}],"url":"\/documentation\/mapsindoors\/mproutingproviderdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPRoutingProviderDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPRoutingProviderDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPRoutingProviderDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProviderDelegate\/onRouteResultReady(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoutingProviderDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProviderDelegate~1onRouteResultReady(_:)\/title","value":"onRouteResultReady:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProviderDelegate~1onRouteResultReady(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRouteResultReady:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProviderDelegate\/title","value":"MPRoutingProviderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProviderDelegate\/fragments","value":[{"kind":"identifier","text":"MPRoutingProviderDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}