{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mproute"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mproute"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MPRoute"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPRoute","symbolKind":"protocol","title":"MPRoute","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRoute"}],"modules":[{"name":"MapsIndoors"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService"},{"text":".","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/bounds","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/copyrights","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/distance","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/duration","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/legs","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/overview_polyline","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/restrictions","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/summary","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/warnings"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/findNearestRouteSegmentPathFromPoint(_:floorIndex:)"],"title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRoute"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer"],"title":"Directions","generated":true}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute/legs":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"legs"}],"type":"topic","url":"\/documentation\/mapsindoors\/mproute\/legs","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/legs","abstract":[{"text":"The route legs: the different route components. Typically a route from 1st floor to 2nd floor will consist of two route legs.","type":"text"}],"title":"legs","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"legs","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MPRouteLeg","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRouteLeg"},{"text":"]","kind":"text"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute/distance":{"kind":"symbol","navigatorTitle":[{"text":"distance","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mproute\/distance","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/distance","title":"distance","abstract":[{"type":"text","text":"The full distance in meters."}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"distance","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute/copyrights":{"kind":"symbol","navigatorTitle":[{"text":"copyrights","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mproute\/copyrights","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/copyrights","abstract":[],"title":"copyrights","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"copyrights","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute/summary":{"kind":"symbol","navigatorTitle":[{"text":"summary","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mproute\/summary","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/summary","title":"summary","abstract":[{"text":"Textual summary of the route.","type":"text"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"summary"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute/restrictions":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"restrictions"}],"type":"topic","url":"\/documentation\/mapsindoors\/mproute\/restrictions","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/restrictions","abstract":[{"type":"text","text":"The restrictions that apply for the route. May be empty."}],"title":"restrictions","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"restrictions"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute/bounds":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"bounds"}],"type":"topic","url":"\/documentation\/mapsindoors\/mproute\/bounds","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/bounds","title":"bounds","abstract":[{"text":"The route bounds.","type":"text"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bounds"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRouteBounds","kind":"typeIdentifier","text":"MPRouteBounds"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute/findNearestRouteSegmentPathFromPoint(_:floorIndex:)":{"kind":"symbol","navigatorTitle":[{"text":"findNearestRouteSegmentPathFromPoint:floorIndex:","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mproute\/findnearestroutesegmentpathfrompoint(_:floorindex:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/findNearestRouteSegmentPathFromPoint(_:floorIndex:)","abstract":[{"text":"Find route segment path (route leg and route step) nearest to a point and floor index.","type":"text"}],"title":"findNearestRouteSegmentPathFromPoint(_:floorIndex:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"findNearestRouteSegmentPathFromPoint","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","text":"MPPoint","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"floorIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPRouteSegmentPath","text":"MPRouteSegmentPath","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery":{"kind":"symbol","navigatorTitle":[{"text":"MPDirectionsQuery","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdirectionsquery","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery","title":"MPDirectionsQuery","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDirectionsQuery","kind":"identifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsService":{"kind":"symbol","navigatorTitle":[{"text":"MPDirectionsService","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdirectionsservice","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","abstract":[],"title":"MPDirectionsService","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPDirectionsService","kind":"identifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLeg":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPRouteLeg"}],"type":"topic","url":"\/documentation\/mapsindoors\/mprouteleg","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg","title":"MPRouteLeg","abstract":[{"type":"text","text":"Route leg model. A route model will consist of one ore more route legs. Typically a route from 1st floor to 2nd floor will consist of two route legs. Thus, a route leg defines a continuous route part within the same floor and\/or building and\/or vehicle."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPRouteLeg","kind":"identifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute/duration":{"kind":"symbol","navigatorTitle":[{"text":"duration","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mproute\/duration","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/duration","abstract":[{"type":"text","text":"The full duration in seconds based on travel times for each leg\/step."}],"title":"duration","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsRenderer":{"navigatorTitle":[{"text":"MPDirectionsRenderer","kind":"identifier"}],"role":"symbol","title":"MPDirectionsRenderer","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDirectionsRenderer","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer","type":"topic","abstract":[{"type":"text","text":"This allows for an easy way to display a route on the MapsIndoors map. Each leg of the route can be shown individually and can be navigated by manipulating the selected leg index. Various customization options are available to adjust the polyline styling and camera behavior."}],"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute/warnings":{"kind":"symbol","navigatorTitle":[{"text":"warnings","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mproute\/warnings","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/warnings","title":"warnings","abstract":[{"type":"text","text":"Textual warning for the route."}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"warnings","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPRoute"}],"type":"topic","url":"\/documentation\/mapsindoors\/mproute","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","abstract":[{"text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","isActive":true,"type":"reference"},{"type":"text","text":"."}],"title":"MPRoute","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPRoute","kind":"identifier"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute/overview_polyline":{"kind":"symbol","navigatorTitle":[{"text":"overview_polyline","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mproute\/overview_polyline","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/overview_polyline","title":"overview_polyline","abstract":[],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"overview_polyline","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPEncodedPolyline","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPEncodedPolyline"},{"kind":"text","text":"?"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MPRoute"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MPRoute","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPRoute"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/bounds","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/copyrights","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/distance","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/duration","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/legs","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/overview_polyline","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/restrictions","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/summary","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/warnings"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/findNearestRouteSegmentPathFromPoint(_:floorIndex:)"]}],"op":"replace"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","value":[{"generated":true,"title":"Directions","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer"]}],"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRoute"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"legs","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1legs\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1legs\/fragments","op":"replace","value":[{"kind":"identifier","text":"legs"}]},{"value":"distance","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1distance\/title"},{"value":[{"text":"distance","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1distance\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1copyrights\/title","op":"replace","value":"copyrights"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1copyrights\/fragments","value":[{"text":"copyrights","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"summary","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1summary\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1summary\/fragments","value":[{"text":"summary","kind":"identifier"}]},{"value":"restrictions","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1restrictions\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1restrictions\/fragments","value":[{"kind":"identifier","text":"restrictions"}],"op":"replace"},{"op":"replace","value":"bounds","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1bounds\/title"},{"op":"replace","value":[{"text":"bounds","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1bounds\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1findNearestRouteSegmentPathFromPoint(_:floorIndex:)\/title","value":"findNearestRouteSegmentPathFromPoint:floorIndex:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1findNearestRouteSegmentPathFromPoint(_:floorIndex:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"findNearestRouteSegmentPathFromPoint:floorIndex:"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/title","op":"replace","value":"MPDirectionsQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/fragments","value":[{"kind":"identifier","text":"MPDirectionsQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/title","value":"MPDirectionsService"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/fragments","value":[{"text":"MPDirectionsService","kind":"identifier"}]},{"value":"MPRouteLeg","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg\/fragments","value":[{"text":"MPRouteLeg","kind":"identifier"}]},{"value":"duration","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1duration\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1duration\/fragments","op":"replace","value":[{"text":"duration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/title","op":"replace","value":"MPDirectionsRenderer"},{"op":"replace","value":[{"text":"MPDirectionsRenderer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1warnings\/title","value":"warnings","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1warnings\/fragments","value":[{"kind":"identifier","text":"warnings"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/title","value":"MPRoute"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/fragments","op":"replace","value":[{"text":"MPRoute","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1overview_polyline\/title","value":"overview_polyline"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1overview_polyline\/fragments","value":[{"text":"overview_polyline","kind":"identifier"}]}]}]}