{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","seeAlsoSections":[{"title":"Directions","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"MPRouteLeg"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPRouteLeg","modules":[{"name":"MapsIndoors"}],"title":"MPRouteLeg","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPRouteLeg","kind":"identifier"}]},"sections":[],"abstract":[{"text":"Route leg model. A route model will consist of one ore more route legs. Typically a route from 1st floor to 2nd floor will consist of two route legs. Thus, a route leg defines a continuous route part within the same floor and\/or building and\/or vehicle.","type":"text"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/distance","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/duration","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/end_address","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/end_location","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/routeLegType","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/start_address","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/start_location","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/steps"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRouteLeg"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mprouteleg"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mprouteleg"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsQuery":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery","kind":"symbol","url":"\/documentation\/mapsindoors\/mpdirectionsquery","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsQuery"}],"navigatorTitle":[{"text":"MPDirectionsQuery","kind":"identifier"}],"type":"topic","title":"MPDirectionsQuery"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLeg/routeLegType":{"navigatorTitle":[{"kind":"identifier","text":"routeLegType"}],"kind":"symbol","type":"topic","abstract":[{"text":"The type of leg, determined by the source service, External (Google or Mapbox) or MapsIndoors.","type":"text"}],"url":"\/documentation\/mapsindoors\/mprouteleg\/routelegtype","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/routeLegType","required":true,"title":"routeLegType","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"routeLegType"},{"kind":"text","text":": "},{"text":"MPRouteLegType","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPRouteLegType"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLeg/steps":{"navigatorTitle":[{"kind":"identifier","text":"steps"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/steps","url":"\/documentation\/mapsindoors\/mprouteleg\/steps","abstract":[{"type":"text","text":"Collection of steps for the route leg."}],"required":true,"title":"steps","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"steps","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MPRouteStep","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRouteStep"},{"kind":"text","text":"]"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLeg":{"url":"\/documentation\/mapsindoors\/mprouteleg","navigatorTitle":[{"kind":"identifier","text":"MPRouteLeg"}],"type":"topic","abstract":[{"text":"Route leg model. A route model will consist of one ore more route legs. Typically a route from 1st floor to 2nd floor will consist of two route legs. Thus, a route leg defines a continuous route part within the same floor and\/or building and\/or vehicle.","type":"text"}],"role":"symbol","title":"MPRouteLeg","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRouteLeg"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute":{"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","title":"MPRoute","type":"topic","url":"\/documentation\/mapsindoors\/mproute","abstract":[{"type":"text","text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRoute"}],"navigatorTitle":[{"text":"MPRoute","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLeg/end_location":{"navigatorTitle":[{"text":"end_location","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The route leg end position."}],"url":"\/documentation\/mapsindoors\/mprouteleg\/end_location","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/end_location","required":true,"title":"end_location","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"end_location","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRouteCoordinate","text":"MPRouteCoordinate"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLeg/duration":{"navigatorTitle":[{"text":"duration","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/duration","url":"\/documentation\/mapsindoors\/mprouteleg\/duration","abstract":[{"type":"text","text":"The route leg duration in seconds."}],"required":true,"title":"duration","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLeg/distance":{"navigatorTitle":[{"text":"distance","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The route leg distance in meters."}],"url":"\/documentation\/mapsindoors\/mprouteleg\/distance","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/distance","required":true,"title":"distance","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"distance","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsRenderer":{"url":"\/documentation\/mapsindoors\/mpdirectionsrenderer","role":"symbol","title":"MPDirectionsRenderer","kind":"symbol","abstract":[{"type":"text","text":"This allows for an easy way to display a route on the MapsIndoors map. Each leg of the route can be shown individually and can be navigated by manipulating the selected leg index. Various customization options are available to adjust the polyline styling and camera behavior."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPDirectionsRenderer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPDirectionsRenderer"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsService":{"abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","title":"MPDirectionsService","url":"\/documentation\/mapsindoors\/mpdirectionsservice","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsService"}],"type":"topic","navigatorTitle":[{"text":"MPDirectionsService","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLeg/start_address":{"navigatorTitle":[{"text":"start_address","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/start_address","url":"\/documentation\/mapsindoors\/mprouteleg\/start_address","abstract":[{"type":"text","text":"The route leg start address. If the position is outdoors, the address may be a postal address. If the position is indoors, the address may be a textual description of the indoor location, like “Lower Ground Floor, Building X”."}],"required":true,"title":"start_address","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"start_address","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLeg/start_location":{"navigatorTitle":[{"text":"start_location","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The route leg start position."}],"url":"\/documentation\/mapsindoors\/mprouteleg\/start_location","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/start_location","required":true,"title":"start_location","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start_location","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRouteCoordinate","text":"MPRouteCoordinate"}]},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLeg/end_address":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/end_address","title":"end_address","required":true,"role":"symbol","url":"\/documentation\/mapsindoors\/mprouteleg\/end_address","abstract":[{"text":"The route leg end address. If the position is outdoors, the address may be a postal address. If the position is indoors, the address may be a textual description of the indoor location, like “Lower Ground Floor, Building X”.","type":"text"}],"navigatorTitle":[{"text":"end_address","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"end_address","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","value":"MPRouteLeg","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPRouteLeg"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MPRouteLeg"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/distance","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/duration","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/end_address","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/end_location","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/routeLegType","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/start_address","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/start_location","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg\/steps"]}]},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsQuery","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsRenderer"],"generated":true,"title":"Directions"}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRouteLeg"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"MPDirectionsQuery","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsQuery\/fragments","value":[{"text":"MPDirectionsQuery","kind":"identifier"}]},{"op":"replace","value":"routeLegType","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg~1routeLegType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg~1routeLegType\/fragments","value":[{"kind":"identifier","text":"routeLegType"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg~1steps\/title","value":"steps","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg~1steps\/fragments","value":[{"text":"steps","kind":"identifier"}]},{"value":"MPRouteLeg","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg\/fragments","value":[{"kind":"identifier","text":"MPRouteLeg"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/title","op":"replace","value":"MPRoute"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/fragments","op":"replace","value":[{"text":"MPRoute","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg~1end_location\/title","op":"replace","value":"end_location"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg~1end_location\/fragments","value":[{"kind":"identifier","text":"end_location"}]},{"op":"replace","value":"duration","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg~1duration\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg~1duration\/fragments","value":[{"text":"duration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg~1distance\/title","op":"replace","value":"distance"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg~1distance\/fragments","value":[{"kind":"identifier","text":"distance"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/title","value":"MPDirectionsRenderer","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsRenderer\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPDirectionsRenderer"}]},{"value":"MPDirectionsService","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/title"},{"op":"replace","value":[{"text":"MPDirectionsService","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg~1start_address\/title","value":"start_address"},{"op":"replace","value":[{"text":"start_address","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg~1start_address\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg~1start_location\/title","value":"start_location","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg~1start_location\/fragments","value":[{"text":"start_location","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg~1end_address\/title","value":"end_address","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg~1end_address\/fragments","value":[{"kind":"identifier","text":"end_address"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}