{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath\/init()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath\/init(from:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath\/init(legIndex:stepIndex:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath\/legIndex","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath\/stepIndex"]}],"variants":[{"paths":["\/documentation\/mapsindoors\/mproutesegmentpath"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mproutesegmentpath"]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteSegmentPath"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"metadata":{"roleHeading":"Class","title":"MPRouteSegmentPath","navigatorTitle":[{"text":"MPRouteSegmentPath","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(cs)MPRouteSegmentPath","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRouteSegmentPath"}],"symbolKind":"class","modules":[{"name":"MapsIndoors"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath"},"references":{"doc://com.mapspeople.mapsindoors/SE":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE","title":"Swift.Encodable","type":"unresolvable"},"MapsPeopleWhite.png":{"alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"type":"image","identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/SH":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/objc(cs)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/Se":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteSegmentPath/init(from:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath\/init(from:)","title":"init(from:)","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/mapsindoors\/mproutesegmentpath\/init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Decoder","preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteSegmentPath/init(legIndex:stepIndex:)":{"abstract":[],"kind":"symbol","title":"init(legIndex:stepIndex:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath\/init(legIndex:stepIndex:)","navigatorTitle":[{"text":"initWithLegIndex:stepIndex:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mproutesegmentpath\/init(legindex:stepindex:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"legIndex"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"stepIndex"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteSegmentPath/init()":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath\/init()","type":"topic","title":"init()","abstract":[],"url":"\/documentation\/mapsindoors\/mproutesegmentpath\/init()","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}]},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteSegmentPath":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath","type":"topic","title":"MPRouteSegmentPath","abstract":[],"url":"\/documentation\/mapsindoors\/mproutesegmentpath","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPRouteSegmentPath"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPRouteSegmentPath","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/SQ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteSegmentPath/legIndex":{"title":"legIndex","abstract":[{"text":"Leg index.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath\/legIndex","navigatorTitle":[{"text":"legIndex","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mproutesegmentpath\/legindex","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"legIndex"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteSegmentPath/stepIndex":{"abstract":[{"type":"text","text":"Step index."}],"kind":"symbol","title":"stepIndex","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath\/stepIndex","navigatorTitle":[{"text":"stepIndex","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mproutesegmentpath\/stepindex","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"stepIndex","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"MPRouteSegmentPath","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MPRouteSegmentPath","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MPRouteSegmentPath"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath\/legIndex","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath\/stepIndex"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath\/init()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteSegmentPath\/init(legIndex:stepIndex:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteSegmentPath"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"initWithLegIndex:stepIndex:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteSegmentPath~1init(legIndex:stepIndex:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithLegIndex:stepIndex:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteSegmentPath~1init(legIndex:stepIndex:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteSegmentPath~1init()\/title","value":"init","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteSegmentPath~1init()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteSegmentPath\/title","value":"MPRouteSegmentPath"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteSegmentPath\/fragments","value":[{"kind":"identifier","text":"MPRouteSegmentPath"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteSegmentPath~1legIndex\/title","value":"legIndex","op":"replace"},{"value":[{"kind":"identifier","text":"legIndex"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteSegmentPath~1legIndex\/fragments"},{"op":"replace","value":"stepIndex","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteSegmentPath~1stepIndex\/title"},{"value":[{"kind":"identifier","text":"stepIndex"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteSegmentPath~1stepIndex\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}