{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"abstract":[{"type":"text","text":"Route step model. A step is segment on a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg"},{"text":" (","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg","type":"reference"},{"text":" is a segment on a ","type":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","isActive":true,"type":"reference"},{"type":"text","text":"). The step contains start and end locations, distance and duration information, as well as navigational instructions."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPRouteStep","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep"},"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/distance","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/duration","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/end_location","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/highway","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/html_instructions","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/maneuver","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/polyline","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/routeContext","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/start_location","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/transit_details","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/travel_mode"],"title":"Instance Properties"}],"sections":[],"kind":"symbol","metadata":{"symbolKind":"protocol","role":"symbol","navigatorTitle":[{"text":"MPRouteStep","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPRouteStep","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRouteStep"}],"roleHeading":"Protocol","modules":[{"name":"MapsIndoors"}],"title":"MPRouteStep"},"variants":[{"paths":["\/documentation\/mapsindoors\/mproutestep"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mproutestep"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep/end_location":{"navigatorTitle":[{"kind":"identifier","text":"end_location"}],"role":"symbol","abstract":[{"type":"text","text":"End location coordinate and floor index."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"end_location","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRouteCoordinate","text":"MPRouteCoordinate","kind":"typeIdentifier"}],"title":"end_location","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/end_location","url":"\/documentation\/mapsindoors\/mproutestep\/end_location","type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteLeg":{"title":"MPRouteLeg","navigatorTitle":[{"kind":"identifier","text":"MPRouteLeg"}],"abstract":[{"type":"text","text":"Route leg model. A route model will consist of one ore more route legs. Typically a route from 1st floor to 2nd floor will consist of two route legs. Thus, a route leg defines a continuous route part within the same floor and\/or building and\/or vehicle."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPRouteLeg","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mprouteleg","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep/start_location":{"navigatorTitle":[{"kind":"identifier","text":"start_location"}],"role":"symbol","abstract":[{"type":"text","text":"Start location coordinate and floor index."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start_location"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPRouteCoordinate","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPRouteCoordinate"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/start_location","url":"\/documentation\/mapsindoors\/mproutestep\/start_location","title":"start_location","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep/html_instructions":{"navigatorTitle":[{"kind":"identifier","text":"html_instructions"}],"role":"symbol","abstract":[{"type":"text","text":"Textual instructions for the step. May not be specified."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"html_instructions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"html_instructions","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/html_instructions","url":"\/documentation\/mapsindoors\/mproutestep\/html_instructions","type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep/duration":{"navigatorTitle":[{"kind":"identifier","text":"duration"}],"role":"symbol","abstract":[{"type":"text","text":"Duration of the step in seconds, with specified travel mode "},{"type":"codeVoice","code":"step.travel_mode"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/duration","url":"\/documentation\/mapsindoors\/mproutestep\/duration","title":"duration","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsService":{"url":"\/documentation\/mapsindoors\/mpdirectionsservice","abstract":[],"kind":"symbol","title":"MPDirectionsService","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","navigatorTitle":[{"kind":"identifier","text":"MPDirectionsService"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDirectionsService"}],"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep/polyline":{"navigatorTitle":[{"text":"polyline","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Encoded polyline for the step. Only long polylines may be encoded."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"polyline","kind":"identifier"},{"kind":"text","text":": "},{"text":"MPEncodedPolyline","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPEncodedPolyline"}],"title":"polyline","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/polyline","url":"\/documentation\/mapsindoors\/mproutestep\/polyline","type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep/travel_mode":{"navigatorTitle":[{"text":"travel_mode","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Travel mode key. Can be ","type":"text"},{"type":"codeVoice","code":"walking"},{"type":"text","text":", "},{"type":"codeVoice","code":"bicycling"},{"text":", ","type":"text"},{"type":"codeVoice","code":"driving"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"transit"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"travel_mode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/travel_mode","url":"\/documentation\/mapsindoors\/mproutestep\/travel_mode","title":"travel_mode","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep/maneuver":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Maneuver value for the step. Possible values are:"}],"required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/maneuver","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"maneuver","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/mapsindoors\/mproutestep\/maneuver","title":"maneuver","navigatorTitle":[{"text":"maneuver","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep/distance":{"navigatorTitle":[{"text":"distance","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Distance of the step in meters."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"distance","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"}],"title":"distance","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/distance","url":"\/documentation\/mapsindoors\/mproutestep\/distance","type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep/highway":{"navigatorTitle":[{"text":"highway","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Way type for this step (part of the route). E.g. footway, steps, elevator, residential etc."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"highway","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPHighway","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPHighway"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/highway","url":"\/documentation\/mapsindoors\/mproutestep\/highway","title":"highway","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep/routeContext":{"navigatorTitle":[{"kind":"identifier","text":"routeContext"}],"role":"symbol","abstract":[{"type":"text","text":"Context of the step. May be "},{"code":"InsideBuilding","type":"codeVoice"},{"text":", ","type":"text"},{"code":"OutsideOnVenue","type":"codeVoice"},{"type":"text","text":" or a custom context e.g. "},{"type":"codeVoice","code":"Security"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"routeContext"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"routeContext","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/routeContext","url":"\/documentation\/mapsindoors\/mproutestep\/routecontext","type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep/transit_details":{"navigatorTitle":[{"text":"transit_details","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Transit details. May apply for "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/travel_mode","isActive":true},{"text":" ","type":"text"},{"type":"codeVoice","code":"transit"},{"text":".","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"transit_details"},{"text":": ","kind":"text"},{"text":"MPTransitDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitDetails"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/transit_details","url":"\/documentation\/mapsindoors\/mproutestep\/transit_details","title":"transit_details","required":true},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRouteStep":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Route step model. A step is segment on a "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg","type":"reference","isActive":true},{"type":"text","text":" ("},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteLeg"},{"text":" is a segment on a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute"},{"type":"text","text":"). The step contains start and end locations, distance and duration information, as well as navigational instructions."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPRouteStep","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mproutestep","title":"MPRouteStep","navigatorTitle":[{"text":"MPRouteStep","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the "},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRoute"}],"url":"\/documentation\/mapsindoors\/mproute","title":"MPRoute","navigatorTitle":[{"kind":"identifier","text":"MPRoute"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MPRouteStep","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"text":"MPRouteStep","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MPRouteStep"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/distance","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/duration","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/end_location","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/highway","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/html_instructions","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/maneuver","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/polyline","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/routeContext","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/start_location","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/transit_details","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRouteStep\/travel_mode"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRouteStep"}]}]}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1end_location\/title","value":"end_location","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1end_location\/fragments","value":[{"text":"end_location","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg\/title","value":"MPRouteLeg"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteLeg\/fragments","op":"replace","value":[{"text":"MPRouteLeg","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1start_location\/title","value":"start_location","op":"replace"},{"value":[{"text":"start_location","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1start_location\/fragments","op":"replace"},{"value":"html_instructions","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1html_instructions\/title"},{"value":[{"text":"html_instructions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1html_instructions\/fragments","op":"replace"},{"value":"duration","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1duration\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1duration\/fragments","value":[{"text":"duration","kind":"identifier"}]},{"op":"replace","value":"MPDirectionsService","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/fragments","value":[{"kind":"identifier","text":"MPDirectionsService"}],"op":"replace"},{"value":"polyline","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1polyline\/title"},{"op":"replace","value":[{"text":"polyline","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1polyline\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1travel_mode\/title","value":"travel_mode","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1travel_mode\/fragments","op":"replace","value":[{"text":"travel_mode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1maneuver\/title","op":"replace","value":"maneuver"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1maneuver\/fragments","op":"replace","value":[{"kind":"identifier","text":"maneuver"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1distance\/title","value":"distance","op":"replace"},{"value":[{"kind":"identifier","text":"distance"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1distance\/fragments"},{"value":"highway","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1highway\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1highway\/fragments","value":[{"text":"highway","kind":"identifier"}],"op":"replace"},{"value":"routeContext","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1routeContext\/title"},{"op":"replace","value":[{"kind":"identifier","text":"routeContext"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1routeContext\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1transit_details\/title","value":"transit_details","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep~1transit_details\/fragments","op":"replace","value":[{"kind":"identifier","text":"transit_details"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep\/title","op":"replace","value":"MPRouteStep"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRouteStep\/fragments","value":[{"text":"MPRouteStep","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/title","op":"replace","value":"MPRoute"},{"value":[{"text":"MPRoute","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}