{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteStep"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mproutestep-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mproutestep-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)JSONModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)NSCopying","doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding","doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Route step model. A step is segment on a "},{"type":"codeVoice","code":"MPRouteLeg"},{"type":"text","text":" ("},{"type":"codeVoice","code":"MPRouteLeg"},{"type":"text","text":" is a segment on a "},{"type":"codeVoice","code":"MPRoute"},{"type":"text","text":"). The step contains start and end locations, distance and duration information, as well as navigational instructions."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteStep"}],"title":"MPRouteStep","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPRouteStep","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPRouteStep"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/distance","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/duration","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/end_location","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/geometry","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/highway","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/html_instructions","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/maneuver","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/polyline","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/routeContext","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/start_location","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/steps","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/transit_details","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/travel_mode"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/getActionPoint()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/getEndPoint()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/getStartFloorName()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/getStartPoint()"]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/travel_mode":{"role":"symbol","title":"travel_mode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"travel_mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Travel mode key. Can be walking, bicycling, driving and transit."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/travel_mode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"travel_mode"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/travel_mode"},"doc://MapsIndoors/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCopying"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/getActionPoint()":{"role":"symbol","title":"getActionPoint()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getActionPoint"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/getActionPoint()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getActionPoint"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/getactionpoint()"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/maneuver":{"role":"symbol","title":"maneuver","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maneuver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Maneuver value for the step. Possible values are:"},{"type":"text","text":" "},{"type":"text","text":"straight,"},{"type":"text","text":" "},{"type":"text","text":"turn-left,"},{"type":"text","text":" "},{"type":"text","text":"turn-right,"},{"type":"text","text":" "},{"type":"text","text":"turn-sharp-left,"},{"type":"text","text":" "},{"type":"text","text":"turn-sharp-right,"},{"type":"text","text":" "},{"type":"text","text":"turn-slight-left,"},{"type":"text","text":" "},{"type":"text","text":"turn-slight-right,"},{"type":"text","text":" "},{"type":"text","text":"uturn-left,"},{"type":"text","text":" "},{"type":"text","text":"uturn-right"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/maneuver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maneuver"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/maneuver"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/routeContext":{"role":"symbol","title":"routeContext","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routeContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Context of the step. May be "},{"type":"codeVoice","code":"InsideBuilding"},{"type":"text","text":", "},{"type":"codeVoice","code":"OutsideOnVenue"},{"type":"text","text":" or a custom context e.g. "},{"type":"codeVoice","code":"Security"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/routeContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"routeContext"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/routecontext"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/end_location":{"role":"symbol","title":"end_location","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"end_location"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MPRouteCoordinate","preciseIdentifier":"c:objc(cs)MPRouteCoordinate"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"End location coordinate and floor index"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/end_location","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"end_location"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/end_location"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/polyline":{"role":"symbol","title":"polyline","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polyline"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MPEncodedPolyline","preciseIdentifier":"c:objc(cs)MPEncodedPolyline"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Encoded polyline for the step. Can de decoded with "},{"type":"codeVoice","code":"[GMSPath pathFromEncodedPath:]"},{"type":"text","text":". Only long polylines may be encoded."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/polyline","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"polyline"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/polyline"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/getEndPoint()":{"role":"symbol","title":"getEndPoint()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getEndPoint"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/getEndPoint()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getEndPoint"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/getendpoint()"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/getStartPoint()":{"role":"symbol","title":"getStartPoint()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getStartPoint"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/getStartPoint()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getStartPoint"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/getstartpoint()"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/start_location":{"role":"symbol","title":"start_location","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"start_location"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MPRouteCoordinate","preciseIdentifier":"c:objc(cs)MPRouteCoordinate"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Start location coordinate and floor index"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/start_location","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"start_location"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/start_location"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/steps":{"role":"symbol","title":"steps","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"steps"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"MPRouteStepProtocol","preciseIdentifier":"c:objc(pl)MPRouteStep"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Substeps for the step. May be empty\/nil."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/steps","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"steps"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/steps"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/distance":{"role":"symbol","title":"distance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distance"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Distance of the step in meters."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/distance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"distance"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/distance"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/objc(cs)JSONModel":{"type":"unresolvable","title":"JSONModel","identifier":"doc:\/\/MapsIndoors\/objc(cs)JSONModel"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/duration":{"role":"symbol","title":"duration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Duration of the step in seconds, with specified travel mode "},{"type":"codeVoice","code":"step.travel_mode"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/duration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"duration"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/duration"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/objc(pl)AbstractJSONModelProtocol":{"type":"unresolvable","title":"JSONModel.AbstractJSONModelProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol"},"doc://MapsIndoors/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/transit_details":{"role":"symbol","title":"transit_details","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transit_details"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MPTransitDetails","preciseIdentifier":"c:objc(cs)MPTransitDetails"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Transit details. May apply for travel mode "},{"type":"codeVoice","code":"transit"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/transit_details","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"transit_details"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/transit_details"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class":{"role":"symbol","title":"MPRouteStep","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteStep"}],"abstract":[{"type":"text","text":"Route step model. A step is segment on a "},{"type":"codeVoice","code":"MPRouteLeg"},{"type":"text","text":" ("},{"type":"codeVoice","code":"MPRouteLeg"},{"type":"text","text":" is a segment on a "},{"type":"codeVoice","code":"MPRoute"},{"type":"text","text":"). The step contains start and end locations, distance and duration information, as well as navigational instructions."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteStep"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/getStartFloorName()":{"role":"symbol","title":"getStartFloorName()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getStartFloorName"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/getStartFloorName()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getStartFloorName"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/getstartfloorname()"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/geometry":{"role":"symbol","title":"geometry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"MPRouteCoordinateProtocol","preciseIdentifier":"c:objc(pl)MPRouteCoordinate"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Polyline geometry for the step."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/geometry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"geometry"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/geometry"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/highway":{"role":"symbol","title":"highway","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highway"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPHighwayType","preciseIdentifier":"c:MPDefines.h@T@MPHighwayType"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Way type for this step (part of the route). E.g. footway, steps, elevator, residential etc."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/highway","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"highway"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/highway"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteStep-swift.class/html_instructions":{"role":"symbol","title":"html_instructions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"html_instructions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Textual instructions for the step. May not be specified."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/html_instructions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"html_instructions"}],"url":"\/documentation\/mapsindoors\/mproutestep-swift.class\/html_instructions"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPRouteStep"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPRouteStep"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPRouteStep"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/distance","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/duration","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/end_location","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/geometry","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/highway","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/html_instructions","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/maneuver","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/polyline","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/routeContext","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/start_location","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/steps","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/transit_details","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/travel_mode"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/getActionPoint()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/getEndPoint()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/getStartFloorName()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteStep-swift.class\/getStartPoint()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteStep"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSONModel","preciseIdentifier":"c:objc(cs)JSONModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1travel_mode\/title","value":"travel_mode"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1travel_mode\/fragments","value":[{"kind":"identifier","text":"travel_mode"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1getActionPoint()\/title","value":"getActionPoint"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1getActionPoint()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getActionPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1maneuver\/title","value":"maneuver"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1maneuver\/fragments","value":[{"kind":"identifier","text":"maneuver"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1routeContext\/title","value":"routeContext"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1routeContext\/fragments","value":[{"kind":"identifier","text":"routeContext"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1end_location\/title","value":"end_location"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1end_location\/fragments","value":[{"kind":"identifier","text":"end_location"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1polyline\/title","value":"polyline"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1polyline\/fragments","value":[{"kind":"identifier","text":"polyline"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1getEndPoint()\/title","value":"getEndPoint"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1getEndPoint()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getEndPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1getStartPoint()\/title","value":"getStartPoint"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1getStartPoint()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getStartPoint"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1start_location\/title","value":"start_location"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1start_location\/fragments","value":[{"kind":"identifier","text":"start_location"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1steps\/title","value":"steps"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1steps\/fragments","value":[{"kind":"identifier","text":"steps"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1distance\/title","value":"distance"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1distance\/fragments","value":[{"kind":"identifier","text":"distance"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1duration\/title","value":"duration"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1duration\/fragments","value":[{"kind":"identifier","text":"duration"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1transit_details\/title","value":"transit_details"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1transit_details\/fragments","value":[{"kind":"identifier","text":"transit_details"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class\/title","value":"MPRouteStep"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class\/fragments","value":[{"kind":"identifier","text":"MPRouteStep"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1getStartFloorName()\/title","value":"getStartFloorName"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1getStartFloorName()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getStartFloorName"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1geometry\/title","value":"geometry"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1geometry\/fragments","value":[{"kind":"identifier","text":"geometry"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1highway\/title","value":"highway"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1highway\/fragments","value":[{"kind":"identifier","text":"highway"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1html_instructions\/title","value":"html_instructions"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteStep-swift.class~1html_instructions\/fragments","value":[{"kind":"identifier","text":"html_instructions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}