{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoutingProvider"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mproutingprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mproutingprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/init(area:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/init(mapsIndoorsSolutionId:googleApiKey:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/delegate","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/googleApiKey","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/language","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/solutionId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/vehicle","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/venue"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getGoogleRouting(from:to:by:avoid:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getGoogleRouting(from:to:by:avoid:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getGoogleRouting(from:to:by:avoid:depart:arrive:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getGoogleRouting(from:to:by:avoid:depart:arrive:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getRoutingFrom(_:to:by:avoid:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getRoutingFrom(_:to:by:avoid:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getRoutingFrom(_:to:by:avoid:depart:arrive:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getRoutingFrom(_:to:by:avoid:depart:arrive:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getRoutingFrom(_:to:by:avoid:depart:arrive:userRoles:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getRoutingFrom(_:to:by:avoid:depart:arrive:userRoles:completionHandler:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoutingProvider"}],"title":"MPRoutingProvider","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPRoutingProvider","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPRoutingProvider"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/getRoutingFrom(_:to:by:avoid:)":{"role":"symbol","title":"getRoutingFrom(_:to:by:avoid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRoutingFrom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getRoutingFrom(_:to:by:avoid:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getRoutingFrom:to:by:avoid:"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/getroutingfrom(_:to:by:avoid:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/getRoutingFrom(_:to:by:avoid:depart:arrive:userRoles:completionHandler:)":{"role":"symbol","title":"getRoutingFrom(_:to:by:avoid:depart:arrive:userRoles:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRoutingFrom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"depart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"arrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userRoles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPUserRole","preciseIdentifier":"c:objc(cs)MPUserRole"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpRouteHandlerBlockType","preciseIdentifier":"c:MPRoutingProvider.h@T@mpRouteHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getRoutingFrom(_:to:by:avoid:depart:arrive:userRoles:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getRoutingFrom:to:by:avoid:depart:arrive:userRoles:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/getroutingfrom(_:to:by:avoid:depart:arrive:userroles:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/getRoutingFrom(_:to:by:avoid:completionHandler:)":{"role":"symbol","title":"getRoutingFrom(_:to:by:avoid:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRoutingFrom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpRouteHandlerBlockType","preciseIdentifier":"c:MPRoutingProvider.h@T@mpRouteHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getRoutingFrom(_:to:by:avoid:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getRoutingFrom:to:by:avoid:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/getroutingfrom(_:to:by:avoid:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider":{"role":"symbol","title":"MPRoutingProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoutingProvider"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRoutingProvider"}],"url":"\/documentation\/mapsindoors\/mproutingprovider"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/googleApiKey":{"role":"symbol","title":"googleApiKey","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"googleApiKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/googleApiKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"googleApiKey"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/googleapikey"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/vehicle":{"role":"symbol","title":"vehicle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vehicle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/vehicle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"vehicle"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/vehicle"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/getRoutingFrom(_:to:by:avoid:depart:arrive:)":{"role":"symbol","title":"getRoutingFrom(_:to:by:avoid:depart:arrive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRoutingFrom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"depart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"arrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getRoutingFrom(_:to:by:avoid:depart:arrive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getRoutingFrom:to:by:avoid:depart:arrive:"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/getroutingfrom(_:to:by:avoid:depart:arrive:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/venue":{"role":"symbol","title":"venue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"venue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/venue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"venue"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/venue"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/getGoogleRouting(from:to:by:avoid:completionHandler:)":{"role":"symbol","title":"getGoogleRouting(from:to:by:avoid:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getGoogleRouting"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpRouteHandlerBlockType","preciseIdentifier":"c:MPRoutingProvider.h@T@mpRouteHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getGoogleRouting(from:to:by:avoid:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getGoogleRoutingFrom:to:by:avoid:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/getgooglerouting(from:to:by:avoid:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/getGoogleRouting(from:to:by:avoid:)":{"role":"symbol","title":"getGoogleRouting(from:to:by:avoid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getGoogleRouting"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getGoogleRouting(from:to:by:avoid:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getGoogleRoutingFrom:to:by:avoid:"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/getgooglerouting(from:to:by:avoid:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/getGoogleRouting(from:to:by:avoid:depart:arrive:)":{"role":"symbol","title":"getGoogleRouting(from:to:by:avoid:depart:arrive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getGoogleRouting"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"depart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"arrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getGoogleRouting(from:to:by:avoid:depart:arrive:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getGoogleRoutingFrom:to:by:avoid:depart:arrive:"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/getgooglerouting(from:to:by:avoid:depart:arrive:)"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/solutionId":{"role":"symbol","title":"solutionId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"solutionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/solutionId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"solutionId"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/solutionid"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/init(mapsIndoorsSolutionId:googleApiKey:)":{"role":"symbol","title":"init(mapsIndoorsSolutionId:googleApiKey:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"mapsIndoorsSolutionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"googleApiKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/init(mapsIndoorsSolutionId:googleApiKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMapsIndoorsSolutionId:googleApiKey:"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/init(mapsindoorssolutionid:googleapikey:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/getGoogleRouting(from:to:by:avoid:depart:arrive:completionHandler:)":{"role":"symbol","title":"getGoogleRouting(from:to:by:avoid:depart:arrive:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getGoogleRouting"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"depart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"arrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpRouteHandlerBlockType","preciseIdentifier":"c:MPRoutingProvider.h@T@mpRouteHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getGoogleRouting(from:to:by:avoid:depart:arrive:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getGoogleRoutingFrom:to:by:avoid:depart:arrive:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/getgooglerouting(from:to:by:avoid:depart:arrive:completionhandler:)"},"doc://MapsIndoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(cs)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/getRoutingFrom(_:to:by:avoid:depart:arrive:completionHandler:)":{"role":"symbol","title":"getRoutingFrom(_:to:by:avoid:depart:arrive:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRoutingFrom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"depart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"arrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpRouteHandlerBlockType","preciseIdentifier":"c:MPRoutingProvider.h@T@mpRouteHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getRoutingFrom(_:to:by:avoid:depart:arrive:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getRoutingFrom:to:by:avoid:depart:arrive:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/getroutingfrom(_:to:by:avoid:depart:arrive:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/getRoutingFrom(_:to:by:avoid:depart:arrive:userRoles:)":{"role":"symbol","title":"getRoutingFrom(_:to:by:avoid:depart:arrive:userRoles:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRoutingFrom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"depart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"arrive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userRoles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPUserRole","preciseIdentifier":"c:objc(cs)MPUserRole"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getRoutingFrom(_:to:by:avoid:depart:arrive:userRoles:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getRoutingFrom:to:by:avoid:depart:arrive:userRoles:"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/getroutingfrom(_:to:by:avoid:depart:arrive:userroles:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/init(area:)":{"role":"symbol","title":"init(area:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"area"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/init(area:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithArea:"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/init(area:)"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/language":{"role":"symbol","title":"language","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/language","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"language"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/language"},"doc://MapsIndoors/documentation/MapsIndoors/MPRoutingProvider/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPRoutingProviderDelegate","preciseIdentifier":"c:objc(pl)MPRoutingProviderDelegate"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/mapsindoors\/mproutingprovider\/delegate"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPRoutingProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPRoutingProvider"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPRoutingProvider"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/delegate","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/googleApiKey","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/language","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/solutionId","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/vehicle","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/venue"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getGoogleRouting(from:to:by:avoid:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getGoogleRouting(from:to:by:avoid:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getGoogleRouting(from:to:by:avoid:depart:arrive:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getGoogleRouting(from:to:by:avoid:depart:arrive:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getRoutingFrom(_:to:by:avoid:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getRoutingFrom(_:to:by:avoid:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getRoutingFrom(_:to:by:avoid:depart:arrive:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getRoutingFrom(_:to:by:avoid:depart:arrive:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getRoutingFrom(_:to:by:avoid:depart:arrive:userRoles:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/getRoutingFrom(_:to:by:avoid:depart:arrive:userRoles:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/init(area:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRoutingProvider\/init(mapsIndoorsSolutionId:googleApiKey:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoutingProvider"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getRoutingFrom(_:to:by:avoid:)\/title","value":"getRoutingFrom:to:by:avoid:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getRoutingFrom(_:to:by:avoid:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getRoutingFrom:to:by:avoid:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getRoutingFrom(_:to:by:avoid:depart:arrive:userRoles:completionHandler:)\/title","value":"getRoutingFrom:to:by:avoid:depart:arrive:userRoles:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getRoutingFrom(_:to:by:avoid:depart:arrive:userRoles:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getRoutingFrom:to:by:avoid:depart:arrive:userRoles:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getRoutingFrom(_:to:by:avoid:completionHandler:)\/title","value":"getRoutingFrom:to:by:avoid:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getRoutingFrom(_:to:by:avoid:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getRoutingFrom:to:by:avoid:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider\/title","value":"MPRoutingProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider\/fragments","value":[{"kind":"identifier","text":"MPRoutingProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1googleApiKey\/title","value":"googleApiKey"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1googleApiKey\/fragments","value":[{"kind":"identifier","text":"googleApiKey"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1vehicle\/title","value":"vehicle"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1vehicle\/fragments","value":[{"kind":"identifier","text":"vehicle"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getRoutingFrom(_:to:by:avoid:depart:arrive:)\/title","value":"getRoutingFrom:to:by:avoid:depart:arrive:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getRoutingFrom(_:to:by:avoid:depart:arrive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getRoutingFrom:to:by:avoid:depart:arrive:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1venue\/title","value":"venue"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1venue\/fragments","value":[{"kind":"identifier","text":"venue"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getGoogleRouting(from:to:by:avoid:completionHandler:)\/title","value":"getGoogleRoutingFrom:to:by:avoid:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getGoogleRouting(from:to:by:avoid:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getGoogleRoutingFrom:to:by:avoid:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getGoogleRouting(from:to:by:avoid:)\/title","value":"getGoogleRoutingFrom:to:by:avoid:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getGoogleRouting(from:to:by:avoid:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getGoogleRoutingFrom:to:by:avoid:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getGoogleRouting(from:to:by:avoid:depart:arrive:)\/title","value":"getGoogleRoutingFrom:to:by:avoid:depart:arrive:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getGoogleRouting(from:to:by:avoid:depart:arrive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getGoogleRoutingFrom:to:by:avoid:depart:arrive:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1solutionId\/title","value":"solutionId"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1solutionId\/fragments","value":[{"kind":"identifier","text":"solutionId"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1init(mapsIndoorsSolutionId:googleApiKey:)\/title","value":"initWithMapsIndoorsSolutionId:googleApiKey:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1init(mapsIndoorsSolutionId:googleApiKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMapsIndoorsSolutionId:googleApiKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getGoogleRouting(from:to:by:avoid:depart:arrive:completionHandler:)\/title","value":"getGoogleRoutingFrom:to:by:avoid:depart:arrive:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getGoogleRouting(from:to:by:avoid:depart:arrive:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getGoogleRoutingFrom:to:by:avoid:depart:arrive:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getRoutingFrom(_:to:by:avoid:depart:arrive:completionHandler:)\/title","value":"getRoutingFrom:to:by:avoid:depart:arrive:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getRoutingFrom(_:to:by:avoid:depart:arrive:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getRoutingFrom:to:by:avoid:depart:arrive:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getRoutingFrom(_:to:by:avoid:depart:arrive:userRoles:)\/title","value":"getRoutingFrom:to:by:avoid:depart:arrive:userRoles:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1getRoutingFrom(_:to:by:avoid:depart:arrive:userRoles:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getRoutingFrom:to:by:avoid:depart:arrive:userRoles:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1init(area:)\/title","value":"initWithArea:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1init(area:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithArea:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1language\/title","value":"language"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1language\/fragments","value":[{"kind":"identifier","text":"language"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRoutingProvider~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}