{"abstract":[{"type":"text","text":"Selection behavior class that determines how a location selection should be displayed on the map."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPSelectionBehavior","kind":"identifier"}],"symbolKind":"class","title":"MPSelectionBehavior","navigatorTitle":[{"kind":"identifier","text":"MPSelectionBehavior"}],"roleHeading":"Class","modules":[{"name":"MapsIndoors"}],"role":"symbol","externalID":"c:@M@MapsIndoors@objc(cs)MPSelectionBehavior"},"sections":[],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/init(from:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/allowFloorChange","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/animationDuration","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/moveCamera","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/showInfoWindow","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/zoomToFit"]},{"title":"Type Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/default"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSelectionBehavior"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Get the default behavior from "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/default","type":"reference","isActive":true},{"type":"text","text":". The default behavior is that the camera moves to display the selected location and the infowindow is shown."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpselectionbehavior"]},{"paths":["\/documentation\/mapsindoors\/mpselectionbehavior"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"kind":"relationships"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior","doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"abstract":[{"type":"text","text":"This is the control object for the visual representation of the MapsIndoors SDK."}],"url":"\/documentation\/mapsindoors\/mpmapcontrol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPMapControl"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"type":"topic","kind":"symbol","title":"MPMapControl","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapBehavior":{"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpmapbehavior","navigatorTitle":[{"text":"MPMapBehavior","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPMapBehavior","kind":"identifier"}],"title":"MPMapBehavior"},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.mapspeople.mapsindoors/SQ":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapspeople.mapsindoors/Se":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://com.mapspeople.mapsindoors/SE":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSelectionBehavior":{"title":"MPSelectionBehavior","navigatorTitle":[{"kind":"identifier","text":"MPSelectionBehavior"}],"abstract":[{"text":"Selection behavior class that determines how a location selection should be displayed on the map.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPSelectionBehavior","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior","url":"\/documentation\/mapsindoors\/mpselectionbehavior","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSelectionBehavior/moveCamera":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"moveCamera","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"moveCamera"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/moveCamera","abstract":[{"type":"text","text":"Whether "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"},{"type":"text","text":" should move the camera and fit the map view to show the selected location. The default value is "},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"url":"\/documentation\/mapsindoors\/mpselectionbehavior\/movecamera","title":"moveCamera"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSelectionBehavior/zoomToFit":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zoomToFit","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/mapsindoors\/mpselectionbehavior\/zoomtofit","kind":"symbol","title":"zoomToFit","abstract":[],"navigatorTitle":[{"text":"zoomToFit","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/zoomToFit","type":"topic","role":"symbol"},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapspeople.mapsindoors/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSelectionBehavior/init(from:)":{"title":"init(from:)","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/init(from:)","url":"\/documentation\/mapsindoors\/mpselectionbehavior\/init(from:)","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSelectionBehavior/showInfoWindow":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showInfoWindow","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/mapsindoors\/mpselectionbehavior\/showinfowindow","kind":"symbol","title":"showInfoWindow","abstract":[{"type":"text","text":"Whether "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"},{"type":"text","text":" should show the info window if a filter only contains one Location. The default behavior is no infowindow shown "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"showInfoWindow"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/showInfoWindow","type":"topic","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSelectionBehavior/init":{"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpselectionbehavior\/init","title":"init","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/init","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSelectionBehavior/allowFloorChange":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowFloorChange"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/mapsindoors\/mpselectionbehavior\/allowfloorchange","kind":"symbol","title":"allowFloorChange","abstract":[],"navigatorTitle":[{"text":"allowFloorChange","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/allowFloorChange","type":"topic","role":"symbol"},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSelectionBehavior/animationDuration":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animationDuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpselectionbehavior\/animationduration","title":"animationDuration","abstract":[],"navigatorTitle":[{"text":"animationDuration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/animationDuration","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSelectionBehavior/default":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"`default`","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSelectionBehavior","kind":"typeIdentifier","text":"MPSelectionBehavior"}],"url":"\/documentation\/mapsindoors\/mpselectionbehavior\/default","kind":"symbol","title":"default","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/default","type":"topic","role":"symbol"},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","alt":null,"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSelectionBehavior/default_":{"fragments":[{"text":"default_","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpselectionbehavior\/default_","kind":"symbol","title":"default_","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/default_","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"MPSelectionBehavior","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MPSelectionBehavior","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MPSelectionBehavior","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/allowFloorChange","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/animationDuration","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/moveCamera","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/showInfoWindow","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/zoomToFit"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/init"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSelectionBehavior\/default_"],"title":"Type Properties"}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapBehavior"]}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPSelectionBehavior","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl","op":"replace"},{"value":[{"text":"MPMapControl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapBehavior\/title","op":"replace","value":"MPMapBehavior"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapBehavior\/fragments","op":"replace","value":[{"text":"MPMapBehavior","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSelectionBehavior\/title","value":"MPSelectionBehavior","op":"replace"},{"value":[{"kind":"identifier","text":"MPSelectionBehavior"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSelectionBehavior\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSelectionBehavior~1moveCamera\/title","value":"moveCamera","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSelectionBehavior~1moveCamera\/fragments","value":[{"text":"moveCamera","kind":"identifier"}]},{"value":"zoomToFit","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSelectionBehavior~1zoomToFit\/title"},{"value":[{"text":"zoomToFit","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSelectionBehavior~1zoomToFit\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSelectionBehavior~1showInfoWindow\/title","value":"showInfoWindow","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSelectionBehavior~1showInfoWindow\/fragments","value":[{"text":"showInfoWindow","kind":"identifier"}]},{"value":"allowFloorChange","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSelectionBehavior~1allowFloorChange\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSelectionBehavior~1allowFloorChange\/fragments","value":[{"kind":"identifier","text":"allowFloorChange"}]},{"value":"animationDuration","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSelectionBehavior~1animationDuration\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSelectionBehavior~1animationDuration\/fragments","op":"replace","value":[{"kind":"identifier","text":"animationDuration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}