{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig","interfaceLanguage":"swift"},"abstract":[{"text":"MPSolutionConfig is the way to access the Solution settings made in the MapsIndoors CMS.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"externalID":"c:@M@MapsIndoors@objc(cs)MPSolutionConfig","roleHeading":"Class","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPSolutionConfig","kind":"identifier"}],"navigatorTitle":[{"text":"MPSolutionConfig","kind":"identifier"}],"role":"symbol","modules":[{"name":"MapsIndoors"}],"title":"MPSolutionConfig"},"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/init(from:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/buildingDisplayRuleData","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/collisionHandling","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/enableClustering","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/mainDisplayRuleData","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/settings3D"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/encode(to:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/init(dictionary:)"],"title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPSolutionConfig"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"inlineContent":[{"type":"text","text":"MPSolutionConfig governs solution level settings such as:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Marker clustering","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Marker collision handling"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Main Display Rule"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"MPSettings3D"}],"type":"paragraph"}]}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpsolutionconfig"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpsolutionconfig"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject","doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","doc:\/\/com.mapspeople.mapsindoors\/Se","doc:\/\/com.mapspeople.mapsindoors\/SE","doc:\/\/com.mapspeople.mapsindoors\/SQ","doc:\/\/com.mapspeople.mapsindoors\/SH"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig"],"generated":true,"title":"MapsIndoors configuration data"}],"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolutionConfig/settings3D":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/settings3D","abstract":[],"url":"\/documentation\/mapsindoors\/mpsolutionconfig\/settings3d","navigatorTitle":[{"kind":"identifier","text":"settings3D"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"settings3D","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSettings3D","text":"MPSettings3D"}],"title":"settings3D"},"doc://com.mapspeople.mapsindoors/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SQ"},"doc://com.mapspeople.mapsindoors/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(pl)NSObject"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolutionConfig/init(from:)":{"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpsolutionconfig\/init(from:)","title":"init(from:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/init(from:)","role":"symbol","kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolutionConfig/mainDisplayRuleData":{"kind":"symbol","title":"mainDisplayRuleData","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mainDisplayRuleData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPDisplayRuleData","kind":"typeIdentifier","preciseIdentifier":"s:11MapsIndoors17MPDisplayRuleDataV"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/mainDisplayRuleData","abstract":[],"type":"topic","url":"\/documentation\/mapsindoors\/mpsolutionconfig\/maindisplayruledata"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolutionConfig/collisionHandling":{"url":"\/documentation\/mapsindoors\/mpsolutionconfig\/collisionhandling","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"collisionHandling","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@E@MPCollisionHandling","text":"MPCollisionHandling","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"collisionHandling","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/collisionHandling","abstract":[],"type":"topic","title":"collisionHandling"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolutionConfig/init(dictionary:)":{"kind":"symbol","title":"init(dictionary:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`init`","kind":"identifier"},{"text":"(","kind":"text"},{"text":"dictionary","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]!) ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"MPSolutionConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSolutionConfig"}],"navigatorTitle":[{"text":"initWithDictionary:error:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/init(dictionary:)","abstract":[],"type":"topic","url":"\/documentation\/mapsindoors\/mpsolutionconfig\/init(dictionary:)"},"doc://com.mapspeople.mapsindoors/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SH","title":"Swift.Hashable"},"doc://com.mapspeople.mapsindoors/SE":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/SE","title":"Swift.Encodable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolutionConfig/encode(to:)":{"url":"\/documentation\/mapsindoors\/mpsolutionconfig\/encode(to:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7EncoderP","text":"Encoder"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/encode(to:)","abstract":[],"type":"topic","title":"encode(to:)"},"doc://com.mapspeople.mapsindoors/s7CVarArgP":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolutionConfig/buildingDisplayRuleData":{"url":"\/documentation\/mapsindoors\/mpsolutionconfig\/buildingdisplayruledata","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildingDisplayRuleData"},{"kind":"text","text":": "},{"text":"MPDisplayRuleData","kind":"typeIdentifier","preciseIdentifier":"s:11MapsIndoors17MPDisplayRuleDataV"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/buildingDisplayRuleData","abstract":[],"type":"topic","title":"buildingDisplayRuleData"},"doc://com.mapspeople.mapsindoors/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject","title":"NSObject"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolutionConfig":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig","abstract":[{"type":"text","text":"MPSolutionConfig is the way to access the Solution settings made in the MapsIndoors CMS."}],"url":"\/documentation\/mapsindoors\/mpsolutionconfig","navigatorTitle":[{"kind":"identifier","text":"MPSolutionConfig"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPSolutionConfig"}],"title":"MPSolutionConfig"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAppConfig":{"title":"MPAppConfig","abstract":[{"text":"Provides the contextual information needed for setting up a map with specific MapsPeople site data.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpappconfig","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPAppConfig","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MPAppConfig","kind":"identifier"}],"role":"symbol","type":"topic"},"MapsPeopleWhite.png":{"type":"image","alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolutionConfig/enableClustering":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/enableClustering","navigatorTitle":[{"kind":"identifier","text":"enableClustering"}],"url":"\/documentation\/mapsindoors\/mpsolutionconfig\/enableclustering","title":"enableClustering","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableClustering","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"type":"topic"},"doc://com.mapspeople.mapsindoors/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolution":{"abstract":[{"type":"text","text":"The solution model holds data about the buildings and floors in a solution, plus additional meta-data."}],"type":"topic","url":"\/documentation\/mapsindoors\/mpsolution","title":"MPSolution","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPSolution"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPSolution","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution"},"doc://com.mapspeople.mapsindoors/Se":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/Se","title":"Swift.Decodable"},"doc://com.mapspeople.mapsindoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mapspeople.mapsindoors\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MPSolutionConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"MPSolutionConfig"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MPSolutionConfig","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/collisionHandling","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/enableClustering","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/settings3D"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig\/init(dictionary:)"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig"],"generated":true,"title":"MapsIndoors configuration data"}]},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPSolutionConfig"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig~1settings3D\/title","value":"settings3D"},{"value":[{"kind":"identifier","text":"settings3D"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig~1settings3D\/fragments","op":"replace"},{"value":"collisionHandling","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig~1collisionHandling\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig~1collisionHandling\/fragments","op":"replace","value":[{"kind":"identifier","text":"collisionHandling"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig~1init(dictionary:)\/title","value":"initWithDictionary:error:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig~1init(dictionary:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDictionary:error:"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig\/title","op":"replace","value":"MPSolutionConfig"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig\/fragments","value":[{"kind":"identifier","text":"MPSolutionConfig"}],"op":"replace"},{"op":"replace","value":"MPAppConfig","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig\/title"},{"value":[{"text":"MPAppConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig~1enableClustering\/title","op":"replace","value":"enableClustering"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig~1enableClustering\/fragments","op":"replace","value":[{"kind":"identifier","text":"enableClustering"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution\/title","value":"MPSolution"},{"value":[{"text":"MPSolution","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}