{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSolutionProviderDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpsolutionproviderdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpsolutionproviderdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProviderDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Solution provider delegate."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSolutionProviderDelegate"}],"title":"MPSolutionProviderDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)MPSolutionProviderDelegate","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPSolutionProviderDelegate"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProviderDelegate\/onSolutionsReady(_:)"]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPSolutionProviderDelegate":{"role":"symbol","title":"MPSolutionProviderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSolutionProviderDelegate"}],"abstract":[{"type":"text","text":"Solution provider delegate."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProviderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPSolutionProviderDelegate"}],"url":"\/documentation\/mapsindoors\/mpsolutionproviderdelegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPSolutionProviderDelegate/onSolutionsReady(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onSolutionsReady:"}],"role":"symbol","title":"onSolutionsReady(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSolutionsReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPSolution","preciseIdentifier":"c:objc(cs)MPSolution"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProviderDelegate\/onSolutionsReady(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpsolutionproviderdelegate\/onsolutionsready(_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPSolutionProviderDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPSolutionProviderDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPSolutionProviderDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSolutionProviderDelegate\/onSolutionsReady(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSolutionProviderDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProviderDelegate\/title","value":"MPSolutionProviderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProviderDelegate\/fragments","value":[{"kind":"identifier","text":"MPSolutionProviderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProviderDelegate~1onSolutionsReady(_:)\/title","value":"onSolutionsReady:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSolutionProviderDelegate~1onSolutionsReady(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSolutionsReady:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}