{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPSolution","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpsolution"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpsolution"]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/availableLanguages","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/config","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/dataSetId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/defaultLanguage","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/mapClientUrl","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/modules","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/positionProviderConfigs","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/types"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/getMapClientUrlFor(venueId:locationId:)"]}],"metadata":{"title":"MPSolution","roleHeading":"Protocol","navigatorTitle":[{"text":"MPSolution","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPSolution","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPSolution"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"protocol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution"},"abstract":[{"text":"The solution model holds data about the buildings and floors in a solution, plus additional meta-data.","type":"text"}],"seeAlsoSections":[{"title":"MapsIndoors configuration data","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolution/defaultLanguage":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mpsolution\/defaultlanguage","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/defaultLanguage","type":"topic","title":"defaultLanguage","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultLanguage"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultLanguage"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolution/positionProviderConfigs":{"abstract":[{"type":"text","text":"Optionally contains configuration data for the positioning systems used with the solution."}],"kind":"symbol","title":"positionProviderConfigs","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/positionProviderConfigs","navigatorTitle":[{"text":"positionProviderConfigs","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpsolution\/positionproviderconfigs","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"positionProviderConfigs"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]]?"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolution":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPSolution","kind":"identifier"}],"navigatorTitle":[{"text":"MPSolution","kind":"identifier"}],"abstract":[{"type":"text","text":"The solution model holds data about the buildings and floors in a solution, plus additional meta-data."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution","role":"symbol","type":"topic","kind":"symbol","title":"MPSolution","url":"\/documentation\/mapsindoors\/mpsolution"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolution/modules":{"abstract":[],"kind":"symbol","title":"modules","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/modules","navigatorTitle":[{"kind":"identifier","text":"modules"}],"url":"\/documentation\/mapsindoors\/mpsolution\/modules","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolution/types":{"url":"\/documentation\/mapsindoors\/mpsolution\/types","abstract":[],"type":"topic","kind":"symbol","required":true,"title":"types","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/types","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"types"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"types"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPType","text":"MPType","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolution/getMapClientUrlFor(venueId:locationId:)":{"title":"getMapClientUrlFor(venueId:locationId:)","kind":"symbol","abstract":[{"type":"text","text":"Get a link for a location in a specific venue, for use with the web-client."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/getMapClientUrlFor(venueId:locationId:)","navigatorTitle":[{"text":"getMapClientUrlForVenueId:locationId:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpsolution\/getmapclienturlfor(venueid:locationid:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getMapClientUrlFor","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"venueId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"locationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolutionConfig":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig","url":"\/documentation\/mapsindoors\/mpsolutionconfig","navigatorTitle":[{"kind":"identifier","text":"MPSolutionConfig"}],"abstract":[{"type":"text","text":"MPSolutionConfig is the way to access the Solution settings made in the MapsIndoors CMS."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPSolutionConfig","kind":"identifier"}],"title":"MPSolutionConfig"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null,"type":"image","identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolution/availableLanguages":{"abstract":[],"kind":"symbol","title":"availableLanguages","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/availableLanguages","navigatorTitle":[{"text":"availableLanguages","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpsolution\/availablelanguages","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"availableLanguages","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolution/name":{"abstract":[],"title":"name","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/name","navigatorTitle":[{"text":"name","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpsolution\/name","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolution/mapClientUrl":{"title":"mapClientUrl","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/mapClientUrl","navigatorTitle":[{"kind":"identifier","text":"mapClientUrl"}],"url":"\/documentation\/mapsindoors\/mpsolution\/mapclienturl","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mapClientUrl"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAppConfig":{"role":"symbol","abstract":[{"text":"Provides the contextual information needed for setting up a map with specific MapsPeople site data.","type":"text"}],"kind":"symbol","title":"MPAppConfig","type":"topic","url":"\/documentation\/mapsindoors\/mpappconfig","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPAppConfig","kind":"identifier"}],"navigatorTitle":[{"text":"MPAppConfig","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolution/dataSetId":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/dataSetId","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataSetId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/mapsindoors\/mpsolution\/datasetid","navigatorTitle":[{"text":"dataSetId","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"dataSetId","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSolution/config":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/config","title":"config","required":true,"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"config"}],"url":"\/documentation\/mapsindoors\/mpsolution\/config","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"config","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPSolutionConfig","text":"MPSolutionConfig","kind":"typeIdentifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"value":"MPSolution","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","value":[{"kind":"identifier","text":"MPSolution"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPSolution"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/availableLanguages","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/config","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/dataSetId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/defaultLanguage","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/mapClientUrl","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/modules","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/positionProviderConfigs","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/types"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolution\/getMapClientUrlFor(venueId:locationId:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"MapsIndoors configuration data","generated":true,"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSolutionConfig","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAppConfig"]}]},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPSolution"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"defaultLanguage","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1defaultLanguage\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1defaultLanguage\/fragments","value":[{"text":"defaultLanguage","kind":"identifier"}]},{"op":"replace","value":"positionProviderConfigs","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1positionProviderConfigs\/title"},{"op":"replace","value":[{"kind":"identifier","text":"positionProviderConfigs"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1positionProviderConfigs\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution\/title","value":"MPSolution","op":"replace"},{"value":[{"text":"MPSolution","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution\/fragments","op":"replace"},{"value":"modules","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1modules\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1modules\/fragments","value":[{"kind":"identifier","text":"modules"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1types\/title","value":"types","op":"replace"},{"value":[{"kind":"identifier","text":"types"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1types\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1getMapClientUrlFor(venueId:locationId:)\/title","value":"getMapClientUrlForVenueId:locationId:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1getMapClientUrlFor(venueId:locationId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getMapClientUrlForVenueId:locationId:","kind":"identifier"}],"op":"replace"},{"value":"MPSolutionConfig","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolutionConfig\/fragments","value":[{"kind":"identifier","text":"MPSolutionConfig"}],"op":"replace"},{"value":"availableLanguages","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1availableLanguages\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1availableLanguages\/fragments","value":[{"kind":"identifier","text":"availableLanguages"}],"op":"replace"},{"value":"name","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1name\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1name\/fragments","value":[{"kind":"identifier","text":"name"}]},{"value":"mapClientUrl","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1mapClientUrl\/title"},{"value":[{"text":"mapClientUrl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1mapClientUrl\/fragments"},{"value":"MPAppConfig","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig\/title"},{"value":[{"text":"MPAppConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAppConfig\/fragments","op":"replace"},{"value":"dataSetId","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1dataSetId\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"dataSetId"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1dataSetId\/fragments"},{"op":"replace","value":"config","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1config\/title"},{"op":"replace","value":[{"text":"config","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSolution~1config\/fragments"}]}]}