{"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/delegate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/state"]},{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/connect(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/disconnect()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/subscribe(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/unsubscribe(_:)"],"title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient"},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPSubscriptionClient","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"role":"symbol","roleHeading":"Protocol","symbolKind":"protocol","title":"MPSubscriptionClient","navigatorTitle":[{"text":"MPSubscriptionClient","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPSubscriptionClient"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSubscriptionClient"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"variants":[{"paths":["\/documentation\/mapsindoors\/mpsubscriptionclient"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpsubscriptionclient"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClient/unsubscribe(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsubscribe"},{"text":"(","kind":"text"},{"text":"MPSubscriptionTopic","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionTopic"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"unsubscribe:"}],"url":"\/documentation\/mapsindoors\/mpsubscriptionclient\/unsubscribe(_:)","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/unsubscribe(_:)","required":true,"abstract":[],"title":"unsubscribe(_:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClient/connect(_:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/connect(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"connect","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"connect(_:)","navigatorTitle":[{"text":"connect:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpsubscriptionclient\/connect(_:)","type":"topic","abstract":[],"required":true,"kind":"symbol","role":"symbol"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClient/state":{"type":"topic","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpsubscriptionclient\/state","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@E@MPSubscriptionState","text":"MPSubscriptionState","kind":"typeIdentifier"}],"title":"state","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/state","navigatorTitle":[{"text":"state","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClient/disconnect()":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/disconnect()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"disconnect","kind":"identifier"},{"text":"()","kind":"text"}],"title":"disconnect()","navigatorTitle":[{"text":"disconnect","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpsubscriptionclient\/disconnect()","type":"topic","abstract":[],"required":true,"kind":"symbol","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClient":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPSubscriptionClient","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MPSubscriptionClient","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpsubscriptionclient","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient","abstract":[],"title":"MPSubscriptionClient"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClient/delegate":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionClientDelegate","text":"MPSubscriptionClientDelegate","kind":"typeIdentifier"}],"title":"delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpsubscriptionclient\/delegate","abstract":[],"required":true,"kind":"symbol","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClient/subscribe(_:)":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/subscribe(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"subscribe"},{"text":"(","kind":"text"},{"text":"MPSubscriptionTopic","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionTopic","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"subscribe(_:)","navigatorTitle":[{"kind":"identifier","text":"subscribe:"}],"url":"\/documentation\/mapsindoors\/mpsubscriptionclient\/subscribe(_:)","type":"topic","abstract":[],"required":true,"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"MPSubscriptionClient","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"op":"replace","value":[{"text":"MPSubscriptionClient","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MPSubscriptionClient","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/delegate","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/state"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/connect(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/disconnect()","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/subscribe(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClient\/unsubscribe(_:)"]}]},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"MPSubscriptionClient","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient~1unsubscribe(_:)\/title","value":"unsubscribe:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient~1unsubscribe(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"unsubscribe:","kind":"identifier"}]},{"value":"connect:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient~1connect(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"connect:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient~1connect(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient~1state\/title","value":"state","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient~1state\/fragments","op":"replace","value":[{"kind":"identifier","text":"state"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient~1disconnect()\/title","value":"disconnect","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"disconnect","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient~1disconnect()\/fragments"},{"value":"MPSubscriptionClient","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient\/fragments","value":[{"kind":"identifier","text":"MPSubscriptionClient"}]},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient~1delegate\/title"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient~1delegate\/fragments","op":"replace"},{"value":"subscribe:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient~1subscribe(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"subscribe:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClient~1subscribe(_:)\/fragments"}]}]}