{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpsubscriptionclientdelegate"]},{"paths":["\/documentation\/mapsindoors\/mpsubscriptionclientdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/didReceiveMessage(_:onTopic:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/didSubscribe(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/didUnsubscribe(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/didUpdateState(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/onError(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/onSubscriptionError(_:topic:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/onUnsubscriptionError(_:topic:)"],"title":"Instance Methods"}],"metadata":{"roleHeading":"Protocol","title":"MPSubscriptionClientDelegate","navigatorTitle":[{"text":"MPSubscriptionClientDelegate","kind":"identifier"}],"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPSubscriptionClientDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPSubscriptionClientDelegate","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"protocol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPSubscriptionClientDelegate","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClientDelegate/onUnsubscriptionError(_:topic:)":{"url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/onunsubscriptionerror(_:topic:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onUnsubscriptionError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topic"},{"kind":"text","text":": "},{"text":"MPSubscriptionTopic","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionTopic"},{"text":")","kind":"text"}],"kind":"symbol","title":"onUnsubscriptionError(_:topic:)","required":true,"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/onUnsubscriptionError(_:topic:)","navigatorTitle":[{"text":"onUnsubscriptionError:topic:","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClientDelegate":{"kind":"symbol","navigatorTitle":[{"text":"MPSubscriptionClientDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate","url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPSubscriptionClientDelegate","kind":"identifier"}],"title":"MPSubscriptionClientDelegate","type":"topic","role":"symbol","abstract":[]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClientDelegate/onError(_:)":{"required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"type":"topic","title":"onError(_:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/onError(_:)","kind":"symbol","url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/onerror(_:)","navigatorTitle":[{"text":"onError:","kind":"identifier"}],"abstract":[]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClientDelegate/onSubscriptionError(_:topic:)":{"type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onSubscriptionError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topic"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionTopic","text":"MPSubscriptionTopic","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"onSubscriptionError:topic:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/onsubscriptionerror(_:topic:)","abstract":[],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/onSubscriptionError(_:topic:)","kind":"symbol","title":"onSubscriptionError(_:topic:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClientDelegate/didUnsubscribe(_:)":{"abstract":[],"kind":"symbol","title":"didUnsubscribe(_:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/didUnsubscribe(_:)","navigatorTitle":[{"kind":"identifier","text":"didUnsubscribe:"}],"url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/didunsubscribe(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didUnsubscribe","kind":"identifier"},{"kind":"text","text":"("},{"text":"MPSubscriptionTopic","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionTopic"},{"kind":"text","text":")"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClientDelegate/didUpdateState(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateState"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPSubscriptionState","text":"MPSubscriptionState"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"didUpdateState:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/didUpdateState(_:)","required":true,"type":"topic","role":"symbol","kind":"symbol","title":"didUpdateState(_:)","url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/didupdatestate(_:)"},"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","alt":null,"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClientDelegate/didReceiveMessage(_:onTopic:)":{"navigatorTitle":[{"text":"didReceiveMessage:onTopic:","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/didReceiveMessage(_:onTopic:)","type":"topic","url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/didreceivemessage(_:ontopic:)","abstract":[],"role":"symbol","required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didReceiveMessage","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onTopic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"didReceiveMessage(_:onTopic:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClientDelegate/didSubscribe(_:)":{"abstract":[],"kind":"symbol","title":"didSubscribe(_:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/didSubscribe(_:)","navigatorTitle":[{"kind":"identifier","text":"didSubscribe:"}],"url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/didsubscribe(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSubscribe"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"MPSubscriptionTopic","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionTopic"},{"kind":"text","text":")"}],"type":"topic","required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MPSubscriptionClientDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"MPSubscriptionClientDelegate","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MPSubscriptionClientDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/didReceiveMessage(_:onTopic:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/didSubscribe(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/didUnsubscribe(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/didUpdateState(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/onError(_:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/onSubscriptionError(_:topic:)","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/onUnsubscriptionError(_:topic:)"]}]},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSubscriptionClientDelegate"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"onUnsubscriptionError:topic:","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1onUnsubscriptionError(_:topic:)\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1onUnsubscriptionError(_:topic:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onUnsubscriptionError:topic:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate\/title","value":"MPSubscriptionClientDelegate","op":"replace"},{"value":[{"text":"MPSubscriptionClientDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1onError(_:)\/title","value":"onError:"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1onError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onError:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1onSubscriptionError(_:topic:)\/title","value":"onSubscriptionError:topic:"},{"value":[{"text":"- ","kind":"text"},{"text":"onSubscriptionError:topic:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1onSubscriptionError(_:topic:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1didUnsubscribe(_:)\/title","value":"didUnsubscribe:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1didUnsubscribe(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"didUnsubscribe:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1didUpdateState(_:)\/title","value":"didUpdateState:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdateState:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1didUpdateState(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1didReceiveMessage(_:onTopic:)\/title","value":"didReceiveMessage:onTopic:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1didReceiveMessage(_:onTopic:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didReceiveMessage:onTopic:","kind":"identifier"}]},{"op":"replace","value":"didSubscribe:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1didSubscribe(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1didSubscribe(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didSubscribe:"}]}]}]}