{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSubscriptionState"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpsubscriptionstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpsubscriptionstate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH","doc:\/\/MapsIndoors\/SY","doc:\/\/MapsIndoors\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState\/closed","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState\/connected","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState\/connecting","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState\/disconnecting"]},{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState\/Equatable-Implementations","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSubscriptionState"}],"title":"MPSubscriptionState","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@MPSubscriptionState","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionState"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/MapsIndoors\/SY"},"doc://MapsIndoors/documentation/MapsIndoors/MPSubscriptionState/connecting":{"role":"symbol","title":"MPSubscriptionState.connecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState\/connecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionStateConnecting"}],"url":"\/documentation\/mapsindoors\/mpsubscriptionstate\/connecting"},"doc://MapsIndoors/documentation/MapsIndoors/MPSubscriptionState/connected":{"role":"symbol","title":"MPSubscriptionState.connected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState\/connected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionStateConnected"}],"url":"\/documentation\/mapsindoors\/mpsubscriptionstate\/connected"},"doc://MapsIndoors/documentation/MapsIndoors/MPSubscriptionState":{"role":"symbol","title":"MPSubscriptionState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSubscriptionState"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionState"}],"url":"\/documentation\/mapsindoors\/mpsubscriptionstate"},"doc://MapsIndoors/documentation/MapsIndoors/MPSubscriptionState/closed":{"role":"symbol","title":"MPSubscriptionState.closed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closed"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState\/closed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionStateClosed"}],"url":"\/documentation\/mapsindoors\/mpsubscriptionstate\/closed"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/MapsIndoors\/s8SendableP"},"doc://MapsIndoors/documentation/MapsIndoors/MPSubscriptionState/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mpsubscriptionstate\/rawrepresentable-implementations"},"doc://MapsIndoors/documentation/MapsIndoors/MPSubscriptionState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mpsubscriptionstate\/init(rawvalue:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPSubscriptionState/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/mapsindoors\/mpsubscriptionstate\/equatable-implementations"},"doc://MapsIndoors/documentation/MapsIndoors/MPSubscriptionState/disconnecting":{"role":"symbol","title":"MPSubscriptionState.disconnecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnecting"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState\/disconnecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionStateDisconnecting"}],"url":"\/documentation\/mapsindoors\/mpsubscriptionstate\/disconnecting"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"MPSubscriptionState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPSubscriptionState"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPSubscriptionState"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState\/closed","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState\/connected","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState\/connecting","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPSubscriptionState\/disconnecting"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSubscriptionState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionState~1connecting\/title","value":"MPSubscriptionStateConnecting"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionState~1connecting\/fragments","value":[{"kind":"identifier","text":"MPSubscriptionStateConnecting"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionState~1connected\/title","value":"MPSubscriptionStateConnected"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionState~1connected\/fragments","value":[{"kind":"identifier","text":"MPSubscriptionStateConnected"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionState\/title","value":"MPSubscriptionState"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionState\/fragments","value":[{"kind":"identifier","text":"MPSubscriptionState"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionState~1closed\/title","value":"MPSubscriptionStateClosed"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionState~1closed\/fragments","value":[{"kind":"identifier","text":"MPSubscriptionStateClosed"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionState~1disconnecting\/title","value":"MPSubscriptionStateDisconnecting"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPSubscriptionState~1disconnecting\/fragments","value":[{"kind":"identifier","text":"MPSubscriptionStateDisconnecting"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}