{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPTransitTime","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Transit time information."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitTime"},"variants":[{"paths":["\/documentation\/mapsindoors\/mptransittime"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mptransittime"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitTime\/text","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitTime\/time_zone","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitTime\/value"]}],"metadata":{"title":"MPTransitTime","symbolKind":"protocol","externalID":"c:@M@MapsIndoors@objc(pl)MPTransitTime","roleHeading":"Protocol","role":"symbol","modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPTransitTime","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPTransitTime"}]},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitTime/text":{"navigatorTitle":[{"text":"text","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mptransittime\/text","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"text","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The time specified as a string. The time is displayed in the time zone of the transit stop."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitTime\/text","type":"topic","title":"text","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitTime":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPTransitTime","kind":"identifier"}],"navigatorTitle":[{"text":"MPTransitTime","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mptransittime","abstract":[{"type":"text","text":"Transit time information."}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitTime","kind":"symbol","title":"MPTransitTime"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitTime/value":{"navigatorTitle":[{"text":"value","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mptransittime\/value","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"value"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The time specified as Unix time, or seconds since midnight, January 1, 1970 UTC."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitTime\/value","type":"topic","title":"value","role":"symbol"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitTime/time_zone":{"navigatorTitle":[{"text":"time_zone","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mptransittime\/time_zone","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"time_zone","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Time zone of this stop\/station. The value is the name of the time zone as defined in the IANA Time Zone Database, e.g. "},{"type":"codeVoice","code":"\"America\/New_York\""},{"type":"text","text":"."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitTime\/time_zone","type":"topic","title":"time_zone","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"MPTransitTime","op":"replace"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPTransitTime"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MPTransitTime"}]},{"value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitTime\/text","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitTime\/time_zone","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitTime\/value"],"title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"MPTransitTime","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitTime~1text\/title","value":"text","op":"replace"},{"value":[{"text":"text","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitTime~1text\/fragments"},{"value":"MPTransitTime","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitTime\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitTime\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPTransitTime"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitTime~1value\/title","op":"replace","value":"value"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitTime~1value\/fragments","value":[{"text":"value","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitTime~1time_zone\/title","op":"replace","value":"time_zone"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitTime~1time_zone\/fragments","value":[{"kind":"identifier","text":"time_zone"}],"op":"replace"}]}]}