{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitAgency","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPTransitAgency","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitAgency\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitAgency\/phone","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitAgency\/url"]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Transit agency information."}],"metadata":{"navigatorTitle":[{"text":"MPTransitAgency","kind":"identifier"}],"roleHeading":"Protocol","role":"symbol","title":"MPTransitAgency","symbolKind":"protocol","modules":[{"name":"MapsIndoors"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPTransitAgency","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPTransitAgency"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mptransitagency"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mptransitagency"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitAgency/url":{"url":"\/documentation\/mapsindoors\/mptransitagency\/url","required":true,"abstract":[{"type":"text","text":"Url contains the URL for the transit agency."}],"title":"url","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitAgency\/url","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"url","kind":"identifier"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitAgency/name":{"url":"\/documentation\/mapsindoors\/mptransitagency\/name","required":true,"abstract":[{"text":"Name contains the name of the transit agency.","type":"text"}],"title":"name","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitAgency\/name","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"name","kind":"identifier"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitAgency/phone":{"url":"\/documentation\/mapsindoors\/mptransitagency\/phone","required":true,"abstract":[{"text":"Phone contains the phone number of the transit agency.","type":"text"}],"title":"phone","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitAgency\/phone","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"phone"}],"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitAgency":{"url":"\/documentation\/mapsindoors\/mptransitagency","abstract":[{"type":"text","text":"Transit agency information."}],"title":"MPTransitAgency","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitAgency","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPTransitAgency","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPTransitAgency"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"MPTransitAgency","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"text":"MPTransitAgency","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MPTransitAgency"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitAgency\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitAgency\/phone","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitAgency\/url"]}]},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPTransitAgency"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"url","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitAgency~1url\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitAgency~1url\/fragments","value":[{"kind":"identifier","text":"url"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitAgency~1name\/title","value":"name","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitAgency~1name\/fragments","value":[{"text":"name","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitAgency~1phone\/title","value":"phone","op":"replace"},{"value":[{"text":"phone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitAgency~1phone\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitAgency\/title","value":"MPTransitAgency"},{"op":"replace","value":[{"text":"MPTransitAgency","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitAgency\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}