{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mptransitline"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mptransitline"]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/agencies","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/color","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/icon","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/short_name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/text_color","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/url","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/vehicle"]}],"metadata":{"title":"MPTransitLine","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"MPTransitLine"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPTransitLine","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPTransitLine","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"protocol"},"abstract":[{"text":"Transit line information.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPTransitLine"}]}]}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitAgency":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitAgency","type":"topic","url":"\/documentation\/mapsindoors\/mptransitagency","abstract":[{"type":"text","text":"Transit agency information."}],"navigatorTitle":[{"text":"MPTransitAgency","kind":"identifier"}],"title":"MPTransitAgency","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPTransitAgency"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitLine/short_name":{"required":true,"abstract":[{"text":"The short name of this transit line. This will normally be a line number, such as “M7” or “355”.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/short_name","type":"topic","url":"\/documentation\/mapsindoors\/mptransitline\/short_name","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"short_name","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"short_name","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"short_name"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitLine/agencies":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"agencies"},{"text":": [","kind":"text"},{"text":"MPTransitAgency","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitAgency"},{"text":"]","kind":"text"}],"url":"\/documentation\/mapsindoors\/mptransitline\/agencies","title":"agencies","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/agencies","navigatorTitle":[{"kind":"identifier","text":"agencies"}],"type":"topic","abstract":[{"type":"text","text":"An array of "},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitAgency","type":"reference"},{"type":"text","text":" objects that each provide information about the operator of the line."}],"required":true,"kind":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitLine/url":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mptransitline\/url","title":"url","navigatorTitle":[{"kind":"identifier","text":"url"}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/url","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"URL for this transit line as provided by the transit agency."}],"required":true,"role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitLine/name":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mptransitline\/name","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/name","type":"topic","title":"name","abstract":[{"type":"text","text":"Name contains the full name of this transit line. eg. “7 Avenue Express”."}],"role":"symbol","navigatorTitle":[{"text":"name","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitLine":{"abstract":[{"type":"text","text":"Transit line information."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine","type":"topic","url":"\/documentation\/mapsindoors\/mptransitline","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPTransitLine"}],"kind":"symbol","title":"MPTransitLine","role":"symbol","navigatorTitle":[{"text":"MPTransitLine","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitLine/text_color":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"text_color","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"text_color","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/text_color","abstract":[{"text":"Color of text commonly used for signage of this line. The color will be specified as a hex string.","type":"text"}],"required":true,"type":"topic","role":"symbol","kind":"symbol","title":"text_color","url":"\/documentation\/mapsindoors\/mptransitline\/text_color"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitLine/color":{"title":"color","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"color","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"type":"text","text":"The color commonly used in signage for this transit line. The color will be specified as a hex string such as: #FF0033."}],"url":"\/documentation\/mapsindoors\/mptransitline\/color","navigatorTitle":[{"text":"color","kind":"identifier"}],"kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/color","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitLine/icon":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"icon","kind":"identifier"}],"type":"topic","required":true,"url":"\/documentation\/mapsindoors\/mptransitline\/icon","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/icon","abstract":[{"text":"URL for the icon associated with this line.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"icon","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"icon"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitLine/vehicle":{"kind":"symbol","url":"\/documentation\/mapsindoors\/mptransitline\/vehicle","required":true,"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/vehicle","title":"vehicle","abstract":[{"type":"text","text":"Type of vehicle used on this line. This may include the following properties:"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"vehicle"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"vehicle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPTransitVehicle","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitVehicle"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MPTransitLine","op":"replace"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MPTransitLine","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MPTransitLine","kind":"identifier"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/agencies","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/color","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/icon","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/short_name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/text_color","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/url","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitLine\/vehicle"],"title":"Instance Properties"}],"op":"replace"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPTransitLine"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MPTransitAgency","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitAgency\/title"},{"value":[{"kind":"identifier","text":"MPTransitAgency"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitAgency\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1short_name\/title","value":"short_name","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1short_name\/fragments","value":[{"kind":"identifier","text":"short_name"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1agencies\/title","value":"agencies","op":"replace"},{"value":[{"text":"agencies","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1agencies\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1url\/title","value":"url","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1url\/fragments","value":[{"text":"url","kind":"identifier"}]},{"op":"replace","value":"name","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1name\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1name\/fragments","value":[{"kind":"identifier","text":"name"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine\/title","value":"MPTransitLine"},{"value":[{"text":"MPTransitLine","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine\/fragments","op":"replace"},{"op":"replace","value":"text_color","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1text_color\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1text_color\/fragments","value":[{"kind":"identifier","text":"text_color"}]},{"op":"replace","value":"color","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1color\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1color\/fragments","value":[{"text":"color","kind":"identifier"}],"op":"replace"},{"value":"icon","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1icon\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1icon\/fragments","value":[{"kind":"identifier","text":"icon"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1vehicle\/title","value":"vehicle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitLine~1vehicle\/fragments","value":[{"kind":"identifier","text":"vehicle"}]}]}]}