{"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/arrival_stop","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/arrival_time","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/departure_stop","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/departure_time","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/headsign","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/headway","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/line","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/num_stops"],"title":"Instance Properties"}],"abstract":[{"text":"Transit details information.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPTransitDetails","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MPTransitDetails","roleHeading":"Protocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPTransitDetails"}],"symbolKind":"protocol","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPTransitDetails"}],"title":"MPTransitDetails"},"variants":[{"paths":["\/documentation\/mapsindoors\/mptransitdetails"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mptransitdetails"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitDetails/arrival_time":{"required":true,"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mptransitdetails\/arrival_time","abstract":[{"text":"Contains the arrival times for this leg of the journey.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/arrival_time","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"arrival_time","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPTransitTime","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitTime"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"arrival_time","kind":"identifier"}],"title":"arrival_time"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitDetails/headsign":{"navigatorTitle":[{"kind":"identifier","text":"headsign"}],"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"headsign"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","abstract":[{"text":"Headsign specifies the direction in which to travel on this line, as it is marked on the vehicle or at the departure stop. This will often be the terminus station.","type":"text"}],"url":"\/documentation\/mapsindoors\/mptransitdetails\/headsign","title":"headsign","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/headsign"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitDetails/headway":{"navigatorTitle":[{"kind":"identifier","text":"headway"}],"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"headway"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"abstract":[{"text":"Specifies the expected number of seconds between departures from the same stop at this time. For example, with a headway value of 600, you would expect a ten minute wait if you should miss your bus.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mptransitdetails\/headway","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/headway","title":"headway"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitDetails/departure_stop":{"navigatorTitle":[{"kind":"identifier","text":"departure_stop"}],"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"departure_stop"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitStop","text":"MPTransitStop","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","abstract":[{"text":"Departure stop contains information about the departure stop\/station for this part of the trip.","type":"text"}],"url":"\/documentation\/mapsindoors\/mptransitdetails\/departure_stop","title":"departure_stop","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/departure_stop"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitDetails/arrival_stop":{"navigatorTitle":[{"kind":"identifier","text":"arrival_stop"}],"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"arrival_stop"},{"kind":"text","text":": "},{"text":"MPTransitStop","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitStop"},{"text":"?","kind":"text"}],"abstract":[{"text":"Arrival stop contains information about the arrival stop\/station for this part of the trip.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mptransitdetails\/arrival_stop","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/arrival_stop","title":"arrival_stop"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitDetails/line":{"navigatorTitle":[{"kind":"identifier","text":"line"}],"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"line"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitLine","text":"MPTransitLine","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","abstract":[{"text":"Line contains information about the transit line used in this step.","type":"text"}],"url":"\/documentation\/mapsindoors\/mptransitdetails\/line","title":"line","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/line"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitDetails/num_stops":{"navigatorTitle":[{"text":"num_stops","kind":"identifier"}],"required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"num_stops","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"text":"Number of stops. Contains the number of stops in this step, counting the arrival stop, but not the departure stop. For example, if your directions involve leaving from Stop A, passing through stops B and C, and arriving at stop D, ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/num_stops","isActive":true},{"type":"text","text":" will return 3."}],"kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mptransitdetails\/num_stops","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/num_stops","title":"num_stops"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitDetails/departure_time":{"navigatorTitle":[{"kind":"identifier","text":"departure_time"}],"required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"departure_time"},{"kind":"text","text":": "},{"text":"MPTransitTime","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPTransitTime"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Contains the departure times for this leg of the journey."}],"url":"\/documentation\/mapsindoors\/mptransitdetails\/departure_time","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/departure_time","title":"departure_time"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTransitDetails":{"role":"symbol","type":"topic","url":"\/documentation\/mapsindoors\/mptransitdetails","kind":"symbol","abstract":[{"text":"Transit details information.","type":"text"}],"title":"MPTransitDetails","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPTransitDetails","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails","navigatorTitle":[{"kind":"identifier","text":"MPTransitDetails"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MPTransitDetails","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"text":"MPTransitDetails","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MPTransitDetails"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/arrival_stop","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/arrival_time","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/departure_stop","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/departure_time","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/headsign","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/headway","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/line","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTransitDetails\/num_stops"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPTransitDetails","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1arrival_time\/title","value":"arrival_time","op":"replace"},{"value":[{"text":"arrival_time","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1arrival_time\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1headsign\/title","op":"replace","value":"headsign"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1headsign\/fragments","value":[{"text":"headsign","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1headway\/title","value":"headway","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1headway\/fragments","value":[{"text":"headway","kind":"identifier"}]},{"value":"departure_stop","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1departure_stop\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1departure_stop\/fragments","value":[{"text":"departure_stop","kind":"identifier"}]},{"op":"replace","value":"arrival_stop","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1arrival_stop\/title"},{"value":[{"kind":"identifier","text":"arrival_stop"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1arrival_stop\/fragments","op":"replace"},{"value":"line","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1line\/title","op":"replace"},{"value":[{"text":"line","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1line\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1num_stops\/title","value":"num_stops"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1num_stops\/fragments","value":[{"kind":"identifier","text":"num_stops"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1departure_time\/title","value":"departure_time","op":"replace"},{"value":[{"text":"departure_time","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails~1departure_time\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails\/title","value":"MPTransitDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTransitDetails\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPTransitDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}