{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"metadata":{"navigatorTitle":[{"text":"MPType","kind":"identifier"}],"title":"MPType","symbolKind":"protocol","modules":[{"name":"MapsIndoors"}],"roleHeading":"Protocol","externalID":"c:@M@MapsIndoors@objc(pl)MPType","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPType","kind":"identifier"}],"role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPType","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mptype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mptype"]}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPType\/displayRule","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPType\/fields","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPType\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPType\/restrictions","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPType\/translatedName"],"title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPType","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPType/restrictions":{"required":true,"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"restrictions"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPType\/restrictions","kind":"symbol","title":"restrictions","navigatorTitle":[{"text":"restrictions","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mptype\/restrictions","abstract":[{"text":"Get restrictions for Type. Locations of this Type is restricted to this set of app user roles.","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPType/translatedName":{"title":"translatedName","kind":"symbol","abstract":[{"text":"Location Type translated name. May be nil if not defined in the CMS.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPType\/translatedName","navigatorTitle":[{"kind":"identifier","text":"translatedName"}],"url":"\/documentation\/mapsindoors\/mptype\/translatedname","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"translatedName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPType/name":{"abstract":[{"text":"Location Type name.","type":"text"}],"kind":"symbol","title":"name","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPType\/name","navigatorTitle":[{"text":"name","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mptype\/name","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPType/fields":{"title":"fields","kind":"symbol","abstract":[{"type":"text","text":"Dictionary of custom fields."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPType\/fields","navigatorTitle":[{"text":"fields","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mptype\/fields","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fields"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationField","kind":"typeIdentifier","text":"MPLocationField"},{"text":"]?","kind":"text"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPType/displayRule":{"abstract":[{"text":"Get the Display Rule assigned to this Location Type.","type":"text"}],"kind":"symbol","title":"displayRule","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPType\/displayRule","navigatorTitle":[{"text":"displayRule","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mptype\/displayrule","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"displayRule","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPDisplayRule","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule"},{"text":"?","kind":"text"}],"type":"topic","required":true},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null,"identifier":"MapsPeopleWhite.png","type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPType":{"url":"\/documentation\/mapsindoors\/mptype","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPType","title":"MPType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPType"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPType"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MPType","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"kind":"identifier","text":"MPType"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MPType","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPType\/displayRule","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPType\/fields","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPType\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPType\/restrictions","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPType\/translatedName"],"title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPType","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"restrictions","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPType~1restrictions\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPType~1restrictions\/fragments","value":[{"text":"restrictions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPType~1translatedName\/title","value":"translatedName","op":"replace"},{"op":"replace","value":[{"text":"translatedName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPType~1translatedName\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPType~1name\/title","value":"name"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPType~1name\/fragments","value":[{"text":"name","kind":"identifier"}],"op":"replace"},{"value":"fields","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPType~1fields\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPType~1fields\/fragments","value":[{"kind":"identifier","text":"fields"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPType~1displayRule\/title","value":"displayRule"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPType~1displayRule\/fragments","value":[{"kind":"identifier","text":"displayRule"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPType\/title","value":"MPType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPType\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}