{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mptype-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mptype-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)JSONModel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSCoding","doc:\/\/MapsIndoors\/objc(pl)NSCopying","doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding","doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol","doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Location Type model."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPType"}],"title":"MPType","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPType","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPType"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/displayRule","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/fields","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/icon","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/name","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/restrictions","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/translatedName"]}],"references":{"doc://MapsIndoors/objc(pl)AbstractJSONModelProtocol":{"type":"unresolvable","title":"JSONModel.AbstractJSONModelProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)AbstractJSONModelProtocol"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/documentation/MapsIndoors/MPType-swift.class/displayRule":{"role":"symbol","title":"displayRule","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayRule"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MPLocationDisplayRule","preciseIdentifier":"c:objc(cs)MPLocationDisplayRule"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Get the Display Rule assigned to this Location Type."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/displayRule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"displayRule"}],"url":"\/documentation\/mapsindoors\/mptype-swift.class\/displayrule"},"doc://MapsIndoors/documentation/MapsIndoors/MPType-swift.class/translatedName":{"role":"symbol","title":"translatedName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"translatedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Location Type translated name. May be nil if not defined in the CMS."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/translatedName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"translatedName"}],"url":"\/documentation\/mapsindoors\/mptype-swift.class\/translatedname"},"doc://MapsIndoors/objc(cs)JSONModel":{"type":"unresolvable","title":"JSONModel","identifier":"doc:\/\/MapsIndoors\/objc(cs)JSONModel"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPType-swift.class/icon":{"deprecated":true,"role":"symbol","title":"icon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Location Type icon."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/icon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"icon"}],"url":"\/documentation\/mapsindoors\/mptype-swift.class\/icon"},"doc://MapsIndoors/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCoding"},"doc://MapsIndoors/documentation/MapsIndoors/MPType-swift.class/restrictions":{"role":"symbol","title":"restrictions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"restrictions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Get restrictions for Type. Locations of this Type is restricted to this set of app user roles."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/restrictions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"restrictions"}],"url":"\/documentation\/mapsindoors\/mptype-swift.class\/restrictions"},"doc://MapsIndoors/documentation/MapsIndoors/MPType-swift.class":{"role":"symbol","title":"MPType","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPType"}],"abstract":[{"type":"text","text":"Location Type model."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPType"}],"url":"\/documentation\/mapsindoors\/mptype-swift.class"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSCopying"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPType-swift.class/fields":{"role":"symbol","title":"fields","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"MPLocationField","preciseIdentifier":"c:objc(cs)MPLocationField"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Dictionary of custom fields"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/fields","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fields"}],"url":"\/documentation\/mapsindoors\/mptype-swift.class\/fields"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPType-swift.class/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Location Type name."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/mapsindoors\/mptype-swift.class\/name"},"doc://MapsIndoors/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSSecureCoding"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/displayRule","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/fields","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/icon","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/name","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/restrictions","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPType-swift.class\/translatedName"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPType"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"JSONModel","preciseIdentifier":"c:objc(cs)JSONModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPType-swift.class~1displayRule\/title","value":"displayRule"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPType-swift.class~1displayRule\/fragments","value":[{"kind":"identifier","text":"displayRule"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPType-swift.class~1translatedName\/title","value":"translatedName"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPType-swift.class~1translatedName\/fragments","value":[{"kind":"identifier","text":"translatedName"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPType-swift.class~1icon\/title","value":"icon"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPType-swift.class~1icon\/fragments","value":[{"kind":"identifier","text":"icon"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPType-swift.class~1restrictions\/title","value":"restrictions"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPType-swift.class~1restrictions\/fragments","value":[{"kind":"identifier","text":"restrictions"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPType-swift.class\/title","value":"MPType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPType-swift.class\/fragments","value":[{"kind":"identifier","text":"MPType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPType-swift.class~1fields\/title","value":"fields"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPType-swift.class~1fields\/fragments","value":[{"kind":"identifier","text":"fields"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPType-swift.class~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPType-swift.class~1name\/fragments","value":[{"kind":"identifier","text":"name"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}