{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPURITemplate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpuritemplate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpuritemplate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Generates an url based on an URI template. Template string must have format “prefix{param_1}infix{param_N}suffix”, e.g.: “http:\/\/tiles.url.com\/{floor}\/{x}\/{y}\/{zoom}.png”"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPURITemplate"}],"title":"MPURITemplate","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPURITemplate","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPURITemplate"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/init(templateString:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/resultURI","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/templateURI"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/addIntParam(_:value:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/addParam(_:value:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/resetParams()"]}],"references":{"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPURITemplate/addIntParam(_:value:)":{"role":"symbol","title":"addIntParam(_:value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addIntParam"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Find the parameter placeholder {name} with given name and replace with given int value"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/addIntParam(_:value:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addIntParam:value:"}],"url":"\/documentation\/mapsindoors\/mpuritemplate\/addintparam(_:value:)"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(cs)NSObject"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPURITemplate":{"role":"symbol","title":"MPURITemplate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPURITemplate"}],"abstract":[{"type":"text","text":"Generates an url based on an URI template. Template string must have format “prefix{param_1}infix{param_N}suffix”, e.g.: “http:\/\/tiles.url.com\/{floor}\/{x}\/{y}\/{zoom}.png”"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPURITemplate"}],"url":"\/documentation\/mapsindoors\/mpuritemplate"},"doc://MapsIndoors/documentation/MapsIndoors/MPURITemplate/resetParams()":{"role":"symbol","title":"resetParams()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetParams"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Reset the url parameters."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/resetParams()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resetParams"}],"url":"\/documentation\/mapsindoors\/mpuritemplate\/resetparams()"},"doc://MapsIndoors/documentation/MapsIndoors/MPURITemplate/templateURI":{"role":"symbol","title":"templateURI","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Template string property. Must have format “prefix{param_1}infix{param_N}suffix”, e.g.: “http:\/\/tiles.url.com\/{floor}\/{x}\/{y}\/{zoom}.png”"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/templateURI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"templateURI"}],"url":"\/documentation\/mapsindoors\/mpuritemplate\/templateuri"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPURITemplate/init(templateString:)":{"role":"symbol","title":"init(templateString:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"templateString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialization with template string. Must have format “prefix{param_1}infix{param_N}suffix”, e.g.: “http:\/\/tiles.url.com\/{floor}\/{x}\/{y}\/{zoom}.png”"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/init(templateString:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithTemplateString:"}],"url":"\/documentation\/mapsindoors\/mpuritemplate\/init(templatestring:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPURITemplate/addParam(_:value:)":{"role":"symbol","title":"addParam(_:value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addParam"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Find the parameter placeholder {name} with given name and replace with given string value"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/addParam(_:value:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addParam:value:"}],"url":"\/documentation\/mapsindoors\/mpuritemplate\/addparam(_:value:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPURITemplate/resultURI":{"role":"symbol","title":"resultURI","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the resulting url string"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/resultURI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resultURI"}],"url":"\/documentation\/mapsindoors\/mpuritemplate\/resulturi"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPURITemplate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPURITemplate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPURITemplate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/resultURI","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/templateURI"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/addIntParam(_:value:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/addParam(_:value:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/init(templateString:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPURITemplate\/resetParams()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPURITemplate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate~1addIntParam(_:value:)\/title","value":"addIntParam:value:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate~1addIntParam(_:value:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addIntParam:value:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate\/title","value":"MPURITemplate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate\/fragments","value":[{"kind":"identifier","text":"MPURITemplate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate~1resetParams()\/title","value":"resetParams"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate~1resetParams()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetParams"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate~1templateURI\/title","value":"templateURI"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate~1templateURI\/fragments","value":[{"kind":"identifier","text":"templateURI"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate~1init(templateString:)\/title","value":"initWithTemplateString:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate~1init(templateString:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTemplateString:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate~1addParam(_:value:)\/title","value":"addParam:value:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate~1addParam(_:value:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addParam:value:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate~1resultURI\/title","value":"resultURI"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPURITemplate~1resultURI\/fragments","value":[{"kind":"identifier","text":"resultURI"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}