{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenueProviderDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpvenueproviderdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpvenueproviderdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Venue provider delegate."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenueProviderDelegate"}],"title":"MPVenueProviderDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)MPVenueProviderDelegate","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPVenueProviderDelegate"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate\/onBuilding(withinBoundsReady:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate\/onBuildingDetailsReady(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate\/onBuildingsReady(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate\/onVenueDetailsReady(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate\/onVenuesReady(_:)"]}],"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProviderDelegate/onBuildingDetailsReady(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onBuildingDetailsReady:"}],"role":"symbol","title":"onBuildingDetailsReady(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBuildingDetailsReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPBuilding","preciseIdentifier":"c:objc(cs)MPBuilding"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Building data ready event method."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate\/onBuildingDetailsReady(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpvenueproviderdelegate\/onbuildingdetailsready(_:)"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProviderDelegate/onVenuesReady(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onVenuesReady:"}],"role":"symbol","title":"onVenuesReady(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onVenuesReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPVenueCollection","preciseIdentifier":"c:objc(cs)MPVenueCollection"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate\/onVenuesReady(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpvenueproviderdelegate\/onvenuesready(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProviderDelegate":{"role":"symbol","title":"MPVenueProviderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenueProviderDelegate"}],"abstract":[{"type":"text","text":"Venue provider delegate."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenueProviderDelegate"}],"url":"\/documentation\/mapsindoors\/mpvenueproviderdelegate"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProviderDelegate/onVenueDetailsReady(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onVenueDetailsReady:"}],"role":"symbol","title":"onVenueDetailsReady(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onVenueDetailsReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPVenue","preciseIdentifier":"c:objc(cs)MPVenue"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Venue data ready event method."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate\/onVenueDetailsReady(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpvenueproviderdelegate\/onvenuedetailsready(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPMapControl":{"role":"symbol","title":"MPMapControl","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"abstract":[{"type":"text","text":"Convenience class for setting up a Google map with MapsIndoors venues, buildings, locations and other map content."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"url":"\/documentation\/mapsindoors\/mpmapcontrol"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProviderDelegate/onBuildingsReady(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onBuildingsReady:"}],"role":"symbol","title":"onBuildingsReady(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBuildingsReady"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"MPBuilding","preciseIdentifier":"c:objc(cs)MPBuilding"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Building data ready event method."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate\/onBuildingsReady(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpvenueproviderdelegate\/onbuildingsready(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProviderDelegate/onBuilding(withinBoundsReady:)":{"navigatorTitle":[{"kind":"identifier","text":"onBuildingWithinBoundsReady:"}],"role":"symbol","title":"onBuilding(withinBoundsReady:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBuilding"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withinBoundsReady"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPBuilding","preciseIdentifier":"c:objc(cs)MPBuilding"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Building data ready event method."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate\/onBuilding(withinBoundsReady:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mpvenueproviderdelegate\/onbuilding(withinboundsready:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MPVenueProviderDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPVenueProviderDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPVenueProviderDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate\/onBuilding(withinBoundsReady:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate\/onBuildingDetailsReady(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate\/onBuildingsReady(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate\/onVenueDetailsReady(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProviderDelegate\/onVenuesReady(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPMapControl"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenueProviderDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProviderDelegate~1onBuildingDetailsReady(_:)\/title","value":"onBuildingDetailsReady:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProviderDelegate~1onBuildingDetailsReady(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBuildingDetailsReady:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProviderDelegate~1onVenuesReady(_:)\/title","value":"onVenuesReady:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProviderDelegate~1onVenuesReady(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onVenuesReady:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProviderDelegate\/title","value":"MPVenueProviderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProviderDelegate\/fragments","value":[{"kind":"identifier","text":"MPVenueProviderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProviderDelegate~1onVenueDetailsReady(_:)\/title","value":"onVenueDetailsReady:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProviderDelegate~1onVenueDetailsReady(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onVenueDetailsReady:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/title","value":"MPMapControl"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"kind":"identifier","text":"MPMapControl"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProviderDelegate~1onBuildingsReady(_:)\/title","value":"onBuildingsReady:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProviderDelegate~1onBuildingsReady(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBuildingsReady:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProviderDelegate~1onBuilding(withinBoundsReady:)\/title","value":"onBuildingWithinBoundsReady:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProviderDelegate~1onBuilding(withinBoundsReady:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBuildingWithinBoundsReady:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}