{"variants":[{"paths":["\/documentation\/mapsindoors\/mpvenue"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpvenue"]}],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Protocol","modules":[{"name":"MapsIndoors"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPVenue","title":"MPVenue","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPVenue","kind":"identifier"}],"navigatorTitle":[{"text":"MPVenue","kind":"identifier"}],"symbolKind":"protocol"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"]]},"abstract":[{"type":"text","text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data."}],"seeAlsoSections":[{"title":"MapsIndoors entities","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation"],"generated":true}],"topicSections":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/administrativeId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/anchor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/boundingBox","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/buildings","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/defaultFloor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/defaultStyle","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/entryPoints","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/externalId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/geometry","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/graphId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/hasGraph","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/properties","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/solutionId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/styles","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/tilesUrl","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/venueId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/venueInfo"],"title":"Instance Properties"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity"],"kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPVenue","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPEntity","text":"MPEntity","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/defaultFloor":{"type":"topic","abstract":[{"text":"Venue default floor.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultFloor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"title":"defaultFloor","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/defaultFloor","url":"\/documentation\/mapsindoors\/mpvenue\/defaultfloor","kind":"symbol","required":true,"navigatorTitle":[{"text":"defaultFloor","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/buildings":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/buildings","abstract":[{"type":"text","text":"Container array for buildings in this venue. Note that this array are not populated initially. "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl","type":"reference","isActive":true},{"text":" will populate this for the active venue.","type":"text"}],"kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"buildings"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildings","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPBuilding","text":"MPBuilding"},{"kind":"text","text":"]?"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpvenue\/buildings","title":"buildings"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/properties":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/properties","abstract":[{"type":"text","text":"Dictionary of custom properties."}],"kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"properties"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"properties","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationField","kind":"typeIdentifier","text":"MPLocationField"},{"text":"]?","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpvenue\/properties","title":"properties"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocation":{"url":"\/documentation\/mapsindoors\/mplocation","abstract":[{"type":"text","text":"This holds the data for a single location and a marker to display the data on a map."}],"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPLocation","kind":"identifier"}],"title":"MPLocation","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MPLocation","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding":{"abstract":[{"text":"Holds relevant data for a single building, and the buildings floor levels.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","title":"MPBuilding","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPBuilding"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpbuilding","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPBuilding"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/graphId":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/graphId","abstract":[{"text":"Route network\/graph identifier for the given venue.","type":"text"}],"kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"graphId"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"graphId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpvenue\/graphid","title":"graphId"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/venueId":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/venueId","abstract":[{"text":"Venue id.","type":"text"}],"kind":"symbol","required":true,"navigatorTitle":[{"text":"venueId","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"venueId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpvenue\/venueid","title":"venueId"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/anchor":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/anchor","abstract":[{"type":"text","text":"Venue anchor point."}],"kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"anchor"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"anchor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","text":"MPPoint","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpvenue\/anchor","title":"anchor"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/venueInfo":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/venueInfo","abstract":[{"text":"The VenueInfo from backend. Contains the name, aliases and properties for the venue.","type":"text"}],"kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"venueInfo"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"venueInfo"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPEntityInfo","kind":"typeIdentifier","text":"MPEntityInfo"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpvenue\/venueinfo","title":"venueInfo"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/externalId":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/externalId","abstract":[{"text":"External id.","type":"text"}],"kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"externalId"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"externalId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpvenue\/externalid","title":"externalId"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFloor":{"type":"topic","navigatorTitle":[{"text":"MPFloor","kind":"identifier"}],"abstract":[{"text":"Floor data model. Holds the floor geometry, display name, z-index and id of the building it belongs to.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor","kind":"symbol","url":"\/documentation\/mapsindoors\/mpfloor","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPFloor","kind":"identifier"}],"title":"MPFloor"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/entryPoints":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"entryPoints","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPoint","text":"MPPoint"},{"text":"]?","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/entryPoints","abstract":[{"type":"text","text":"Array of entry points in this venue."}],"navigatorTitle":[{"text":"entryPoints","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpvenue\/entrypoints","role":"symbol","required":true,"title":"entryPoints"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/administrativeId":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"administrativeId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Get venue administrative id."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/administrativeId","navigatorTitle":[{"text":"administrativeId","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpvenue\/administrativeid","role":"symbol","required":true,"title":"administrativeId"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/styles":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"styles"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPMapStyle","text":"MPMapStyle"},{"text":"]?","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/styles","abstract":[{"type":"text","text":"Array of possible map styles."}],"navigatorTitle":[{"text":"styles","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpvenue\/styles","role":"symbol","required":true,"title":"styles"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPMapControl":{"title":"MPMapControl","url":"\/documentation\/mapsindoors\/mpmapcontrol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPMapControl"}],"type":"topic","abstract":[{"text":"This is the control object for the visual representation of the MapsIndoors SDK.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPMapControl"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPMapControl"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/defaultStyle":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPMapStyle","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPMapStyle"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Get a default style. If none is set, it will be the first string value in the list of map styles."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/defaultStyle","navigatorTitle":[{"text":"defaultStyle","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpvenue\/defaultstyle","role":"symbol","required":true,"title":"defaultStyle"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/geometry":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"geometry"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPPolygonGeometry","text":"MPPolygonGeometry"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/geometry","abstract":[{"type":"text","text":"The polygon geometry describing the Venue outline."}],"navigatorTitle":[{"text":"geometry","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpvenue\/geometry","role":"symbol","required":true,"title":"geometry"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/name":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Venue name."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/name","navigatorTitle":[{"text":"name","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpvenue\/name","role":"symbol","required":true,"title":"name"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/solutionId":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"solutionId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/solutionId","abstract":[{"type":"text","text":"Solution id."}],"navigatorTitle":[{"text":"solutionId","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpvenue\/solutionid","role":"symbol","required":true,"title":"solutionId"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/hasGraph":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hasGraph"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Does the venue have an active route graph?"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/hasGraph","navigatorTitle":[{"text":"hasGraph","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpvenue\/hasgraph","role":"symbol","required":true,"title":"hasGraph"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","alt":null,"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/tilesUrl":{"abstract":[{"type":"text","text":"The general url template to be used when creating floor layers for this venue. If used by this framework, the url string must have format "},{"code":"\"prefix{param_1}infix{param_N}suffix\"","type":"codeVoice"},{"type":"text","text":", e.g. "},{"code":"\"http:\/\/tiles.url.com\/{floor}\/{x}\/{y}\/{zoom}.png\"","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/mapsindoors\/mpvenue\/tilesurl","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tilesUrl"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/tilesUrl","type":"topic","kind":"symbol","navigatorTitle":[{"text":"tilesUrl","kind":"identifier"}],"title":"tilesUrl"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue/boundingBox":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"boundingBox"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPGeoBounds","text":"MPGeoBounds"}],"abstract":[{"type":"text","text":"Get the geographic bounding box for the venue."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/boundingBox","navigatorTitle":[{"text":"boundingBox","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpvenue\/boundingbox","role":"symbol","required":true,"title":"boundingBox"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPEntity":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPEntity"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity","abstract":[{"text":"MPEntity is a general protocol implemented by ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation","isActive":true},{"type":"text","text":", "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","isActive":true,"type":"reference"},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue","isActive":true},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/mapsindoors\/mpentity","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPEntity","kind":"identifier"}],"title":"MPEntity"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPVenue":{"title":"MPVenue","url":"\/documentation\/mapsindoors\/mpvenue","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPVenue","kind":"identifier"}],"abstract":[{"text":"The venue model holds data about the buildings and floors in a venue, plus additional meta-data.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"MPVenue","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"MPVenue","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"value":[{"text":"MPVenue","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MPVenue","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/administrativeId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/anchor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/boundingBox","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/buildings","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/defaultFloor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/defaultStyle","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/entryPoints","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/externalId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/geometry","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/graphId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/hasGraph","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/name","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/properties","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/solutionId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/styles","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/tilesUrl","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/venueId","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPVenue\/venueInfo"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"path":"\/seeAlsoSections","value":[{"title":"MapsIndoors entities","identifiers":["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocation"],"generated":true}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPVenue","kind":"identifier"},{"text":" <","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPEntity","text":"MPEntity"},{"text":">","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1defaultFloor\/title","value":"defaultFloor"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1defaultFloor\/fragments","value":[{"text":"defaultFloor","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1buildings\/title","op":"replace","value":"buildings"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1buildings\/fragments","value":[{"kind":"identifier","text":"buildings"}],"op":"replace"},{"value":"properties","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1properties\/title"},{"op":"replace","value":[{"text":"properties","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1properties\/fragments"},{"value":"MPLocation","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/title"},{"value":[{"text":"MPLocation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocation\/fragments","op":"replace"},{"value":"MPBuilding","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/title"},{"value":[{"kind":"identifier","text":"MPBuilding"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/fragments","op":"replace"},{"value":"graphId","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1graphId\/title"},{"value":[{"text":"graphId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1graphId\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1venueId\/title","value":"venueId","op":"replace"},{"value":[{"kind":"identifier","text":"venueId"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1venueId\/fragments"},{"value":"anchor","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1anchor\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1anchor\/fragments","value":[{"text":"anchor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1venueInfo\/title","value":"venueInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1venueInfo\/fragments","value":[{"text":"venueInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1externalId\/title","value":"externalId"},{"op":"replace","value":[{"text":"externalId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1externalId\/fragments"},{"value":"MPFloor","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor\/fragments","value":[{"text":"MPFloor","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1entryPoints\/title","value":"entryPoints","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1entryPoints\/fragments","op":"replace","value":[{"kind":"identifier","text":"entryPoints"}]},{"op":"replace","value":"administrativeId","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1administrativeId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"administrativeId"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1administrativeId\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1styles\/title","value":"styles","op":"replace"},{"value":[{"text":"styles","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1styles\/fragments"},{"value":"MPMapControl","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPMapControl\/fragments","value":[{"text":"MPMapControl","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1defaultStyle\/title","value":"defaultStyle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1defaultStyle\/fragments","value":[{"kind":"identifier","text":"defaultStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1geometry\/title","value":"geometry"},{"op":"replace","value":[{"kind":"identifier","text":"geometry"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1geometry\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1name\/title","value":"name"},{"value":[{"text":"name","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1name\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1solutionId\/title","value":"solutionId"},{"value":[{"text":"solutionId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1solutionId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1hasGraph\/title","value":"hasGraph"},{"op":"replace","value":[{"text":"hasGraph","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1hasGraph\/fragments"},{"op":"replace","value":"tilesUrl","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1tilesUrl\/title"},{"value":[{"text":"tilesUrl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1tilesUrl\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1boundingBox\/title","value":"boundingBox","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue~1boundingBox\/fragments","value":[{"text":"boundingBox","kind":"identifier"}]},{"value":"MPEntity","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntity\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEntity\/fragments","value":[{"text":"MPEntity","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/title","op":"replace","value":"MPVenue"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPVenue\/fragments","value":[{"text":"MPVenue","kind":"identifier"}]}]}]}