{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpVenueListHandlerBlockType"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueCollection","preciseIdentifier":"c:objc(cs)MPVenueCollection","text":"MPVenueCollection"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"venueCollection","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Venue collection. Can be nil."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error object. Can be nil."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpvenuelisthandlerblocktype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpvenuelisthandlerblocktype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpVenueListHandlerBlockType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Handler block for fetching venues."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpVenueListHandlerBlockType"}],"title":"mpVenueListHandlerBlockType","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias","externalID":"c:MPVenueProvider.h@T@mpVenueListHandlerBlockType","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"mpVenueListHandlerBlockType"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueCollection":{"role":"symbol","title":"MPVenueCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenueCollection"}],"abstract":[{"type":"text","text":"Venue collection model, just holds an array."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenueCollection"}],"url":"\/documentation\/mapsindoors\/mpvenuecollection"},"doc://MapsIndoors/documentation/MapsIndoors/mpVenueListHandlerBlockType":{"role":"symbol","title":"mpVenueListHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpVenueListHandlerBlockType"}],"abstract":[{"type":"text","text":"Handler block for fetching venues."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpVenueListHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpVenueListHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mpvenuelisthandlerblocktype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"mpVenueListHandlerBlockType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mpVenueListHandlerBlockType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"mpVenueListHandlerBlockType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(MPVenueCollection *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)MPVenueCollection#*$objc(cs)NSError)"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpVenueListHandlerBlockType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueCollection\/title","value":"MPVenueCollection"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueCollection\/fragments","value":[{"kind":"identifier","text":"MPVenueCollection"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpVenueListHandlerBlockType\/title","value":"mpVenueListHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpVenueListHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpVenueListHandlerBlockType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}