{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenueProvider"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpvenueprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpvenueprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MapsIndoors\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MapsIndoors\/objc(pl)Ignore","doc:\/\/MapsIndoors\/objc(pl)Optional","doc:\/\/MapsIndoors\/objc(pl)NSObject","doc:\/\/MapsIndoors\/s7CVarArgP","doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP","doc:\/\/MapsIndoors\/s23CustomStringConvertibleP","doc:\/\/MapsIndoors\/SQ","doc:\/\/MapsIndoors\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Venue provider interface, that defines a delegate and a method for venue queries."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenueProvider"}],"title":"MPVenueProvider","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MPVenueProvider","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPVenueProvider"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingWithId(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingWithId(_:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingWithinBounds(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingWithinBounds(_:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildings()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingsWithCompletion(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getDataFrom(_:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getVenueWithId(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getVenueWithId(_:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getVenues()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getVenuesWithCompletion(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getDataFrom(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/isOfflineDataAvailable(forSolutionId:language:)"]}],"references":{"doc://MapsIndoors/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MapsIndoors\/s7CVarArgP"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/getDataFrom(_:completionHandler:)":{"role":"symbol","title":"getDataFrom(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDataFrom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpGeocodeHandlerBlockType","preciseIdentifier":"c:MPVenueProvider.h@T@mpGeocodeHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get all possible data related to the provided geographical point. Callback arguments will be nullable venue, building and floor objects."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getDataFrom(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDataFromPoint:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/getdatafrom(_:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/getBuildings()":{"role":"symbol","title":"getBuildings()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBuildings"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Get buildings from this provider"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildings()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getBuildings"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/getbuildings()"},"doc://MapsIndoors/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MapsIndoors\/s28CustomDebugStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/getVenuesWithCompletion(_:)":{"role":"symbol","title":"getVenuesWithCompletion(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVenuesWithCompletion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpVenueListHandlerBlockType","preciseIdentifier":"c:MPVenueProvider.h@T@mpVenueListHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get all venues from this provider"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getVenuesWithCompletion(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getVenuesWithCompletion:"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/getvenueswithcompletion(_:)"},"doc://MapsIndoors/objc(pl)Ignore":{"type":"unresolvable","title":"JSONModel.Ignore","identifier":"doc:\/\/MapsIndoors\/objc(pl)Ignore"},"doc://MapsIndoors/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MapsIndoors\/objc(pl)NSObject"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/getBuildingsWithCompletion(_:)":{"role":"symbol","title":"getBuildingsWithCompletion(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBuildingsWithCompletion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mpBuildingListHandlerBlockType","preciseIdentifier":"c:MPVenueProvider.h@T@mpBuildingListHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get buildings from this provider"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingsWithCompletion(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getBuildingsWithCompletion:"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/getbuildingswithcompletion(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/getBuildingWithId(_:completionHandler:)":{"role":"symbol","title":"getBuildingWithId(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBuildingWithId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpBuildingDetailsHandlerBlockType","preciseIdentifier":"c:MPVenueProvider.h@T@mpBuildingDetailsHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get single building detail object"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingWithId(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getBuildingWithId:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/getbuildingwithid(_:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/getVenueWithId(_:)":{"role":"symbol","title":"getVenueWithId(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVenueWithId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get a single venue object"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getVenueWithId(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getVenueWithId:"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/getvenuewithid(_:)"},"doc://MapsIndoors/objc(pl)Optional":{"type":"unresolvable","title":"JSONModel.Optional","identifier":"doc:\/\/MapsIndoors\/objc(pl)Optional"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MapsIndoors\/SQ"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/getVenueWithId(_:completionHandler:)":{"role":"symbol","title":"getVenueWithId(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVenueWithId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpVenueDetailsHandlerBlockType","preciseIdentifier":"c:MPVenueProvider.h@T@mpVenueDetailsHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get single venue details object"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getVenueWithId(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getVenueWithId:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/getvenuewithid(_:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/getBuildingWithinBounds(_:)":{"role":"symbol","title":"getBuildingWithinBounds(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBuildingWithinBounds"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPMapExtend","preciseIdentifier":"c:objc(cs)MPMapExtend"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get a single building within given bounds"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingWithinBounds(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getBuildingWithinBounds:"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/getbuildingwithinbounds(_:)"},"doc://MapsIndoors/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MapsIndoors\/objc(cs)NSObject"},"doc://MapsIndoors/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MapsIndoors\/s23CustomStringConvertibleP"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/getDataFrom(_:)":{"role":"symbol","title":"getDataFrom(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDataFrom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPPoint","preciseIdentifier":"c:objc(cs)MPPoint"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Synchronously get all possible data related to the provided geographical point."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getDataFrom(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDataFromPoint:"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/getdatafrom(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/isOfflineDataAvailable(forSolutionId:language:)":{"role":"symbol","title":"isOfflineDataAvailable(forSolutionId:language:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOfflineDataAvailable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSolutionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determine if cached or preloaded data is available for the given solutionId."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/isOfflineDataAvailable(forSolutionId:language:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isOfflineDataAvailableForSolutionId:language:"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/isofflinedataavailable(forsolutionid:language:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/getBuildingWithinBounds(_:completionHandler:)":{"role":"symbol","title":"getBuildingWithinBounds(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBuildingWithinBounds"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPMapExtend","preciseIdentifier":"c:objc(cs)MPMapExtend"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpBuildingDetailsHandlerBlockType","preciseIdentifier":"c:MPVenueProvider.h@T@mpBuildingDetailsHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get a single building within given bounds"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingWithinBounds(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getBuildingWithinBounds:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/getbuildingwithinbounds(_:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/getVenues()":{"role":"symbol","title":"getVenues()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVenues"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Get venues from this provider"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getVenues()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getVenues"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/getvenues()"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPVenueProviderDelegate","preciseIdentifier":"c:objc(pl)MPVenueProviderDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Venue provider delegate."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/delegate"},"doc://MapsIndoors/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MapsIndoors\/SH"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider/getBuildingWithId(_:)":{"role":"symbol","title":"getBuildingWithId(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getBuildingWithId"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get a single building detail object"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingWithId(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getBuildingWithId:"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider\/getbuildingwithid(_:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPVenueProvider":{"role":"symbol","title":"MPVenueProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenueProvider"}],"abstract":[{"type":"text","text":"Venue provider interface, that defines a delegate and a method for venue queries."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPVenueProvider"}],"url":"\/documentation\/mapsindoors\/mpvenueprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MPVenueProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPVenueProvider"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MPVenueProvider"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingWithId(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingWithId(_:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingWithinBounds(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingWithinBounds(_:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildings()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getBuildingsWithCompletion(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getDataFrom(_:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getVenueWithId(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getVenueWithId(_:completionHandler:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getVenues()","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getVenuesWithCompletion(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/getDataFrom(_:)","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPVenueProvider\/isOfflineDataAvailable(forSolutionId:language:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPVenueProvider"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getDataFrom(_:completionHandler:)\/title","value":"getDataFromPoint:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getDataFrom(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDataFromPoint:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getBuildings()\/title","value":"getBuildings"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getBuildings()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBuildings"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getVenuesWithCompletion(_:)\/title","value":"getVenuesWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getVenuesWithCompletion(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVenuesWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getBuildingsWithCompletion(_:)\/title","value":"getBuildingsWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getBuildingsWithCompletion(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBuildingsWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getBuildingWithId(_:completionHandler:)\/title","value":"getBuildingWithId:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getBuildingWithId(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBuildingWithId:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getVenueWithId(_:)\/title","value":"getVenueWithId:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getVenueWithId(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVenueWithId:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getVenueWithId(_:completionHandler:)\/title","value":"getVenueWithId:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getVenueWithId(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVenueWithId:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getBuildingWithinBounds(_:)\/title","value":"getBuildingWithinBounds:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getBuildingWithinBounds(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBuildingWithinBounds:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getDataFrom(_:)\/title","value":"getDataFromPoint:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getDataFrom(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getDataFromPoint:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1isOfflineDataAvailable(forSolutionId:language:)\/title","value":"isOfflineDataAvailableForSolutionId:language:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1isOfflineDataAvailable(forSolutionId:language:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isOfflineDataAvailableForSolutionId:language:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getBuildingWithinBounds(_:completionHandler:)\/title","value":"getBuildingWithinBounds:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getBuildingWithinBounds(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBuildingWithinBounds:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getVenues()\/title","value":"getVenues"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getVenues()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVenues"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getBuildingWithId(_:)\/title","value":"getBuildingWithId:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider~1getBuildingWithId(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getBuildingWithId:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider\/title","value":"MPVenueProvider"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPVenueProvider\/fragments","value":[{"kind":"identifier","text":"MPVenueProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}