{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"START_ACTION"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteActionType","preciseIdentifier":"c:@E@MPRouteActionType","text":"MPRouteActionType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/start_action"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/start_action"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/START_ACTION","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"START_ACTION"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPRouteActionType","preciseIdentifier":"c:@E@MPRouteActionType"}],"title":"START_ACTION","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@E@MPRouteActionType@START_ACTION","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"START_ACTION"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteActionType":{"role":"symbol","title":"MPRouteActionType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteActionType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteActionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteActionType"}],"url":"\/documentation\/mapsindoors\/mprouteactiontype"},"doc://MapsIndoors/documentation/MapsIndoors/START_ACTION":{"role":"symbol","title":"START_ACTION","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"START_ACTION"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPRouteActionType","preciseIdentifier":"c:@E@MPRouteActionType"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/START_ACTION","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"START_ACTION"}],"url":"\/documentation\/mapsindoors\/start_action"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"START_ACTION"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"START_ACTION"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"START_ACTION"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteActionType\/title","value":"MPRouteActionType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteActionType\/fragments","value":[{"kind":"identifier","text":"MPRouteActionType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1START_ACTION\/title","value":"START_ACTION"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1START_ACTION\/fragments","value":[{"kind":"identifier","text":"START_ACTION"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}