{"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"floor"}],"navigatorTitle":[{"kind":"identifier","text":"MPLocationBaseTypeFloor"}],"modules":[{"name":"MapsIndoors"}],"symbolKind":"case","externalID":"c:@M@MapsIndoors@E@MPLocationBaseType@MPLocationBaseTypeFloor","roleHeading":"Case","role":"symbol","title":"MPLocationBaseType.floor"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationbasetype\/floor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mplocationbasetype\/floor"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"floor","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/floor"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationBaseType":{"navigatorTitle":[{"text":"MPLocationBaseType","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/mapsindoors\/mplocationbasetype","abstract":[],"title":"MPLocationBaseType","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationBaseType"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationBaseType/floor":{"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"floor"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/floor","navigatorTitle":[{"text":"MPLocationBaseTypeFloor","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mplocationbasetype\/floor","kind":"symbol","title":"MPLocationBaseType.floor","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MPLocationBaseTypeFloor","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"MPLocationBaseTypeFloor","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MPLocationBaseTypeFloor"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"MPLocationBaseType","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType\/title"},{"value":[{"text":"MPLocationBaseType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType~1floor\/title","value":"MPLocationBaseTypeFloor","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType~1floor\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPLocationBaseTypeFloor"}]}]}]}