{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mplocationbasetype\/pointofinterest"]},{"paths":["\/documentation\/mapsindoors\/mplocationbasetype\/pointofinterest"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"MPLocationBaseTypePointOfInterest"}],"modules":[{"name":"MapsIndoors"}],"roleHeading":"Case","title":"MPLocationBaseType.pointOfInterest","externalID":"c:@M@MapsIndoors@E@MPLocationBaseType@MPLocationBaseTypePointOfInterest","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"pointOfInterest","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pointOfInterest","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/pointOfInterest"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType"]]},"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationBaseType/pointOfInterest":{"navigatorTitle":[{"kind":"identifier","text":"MPLocationBaseTypePointOfInterest"}],"url":"\/documentation\/mapsindoors\/mplocationbasetype\/pointofinterest","abstract":[],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType\/pointOfInterest","title":"MPLocationBaseType.pointOfInterest","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pointOfInterest"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationBaseType":{"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationBaseType","kind":"symbol","title":"MPLocationBaseType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationBaseType"}],"navigatorTitle":[{"kind":"identifier","text":"MPLocationBaseType"}],"abstract":[],"url":"\/documentation\/mapsindoors\/mplocationbasetype"},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"identifier":"MapsPeopleWhite.png","type":"image"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MPLocationBaseTypePointOfInterest"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"MPLocationBaseTypePointOfInterest","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"MPLocationBaseTypePointOfInterest"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"MPLocationBaseTypePointOfInterest","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType~1pointOfInterest\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType~1pointOfInterest\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPLocationBaseTypePointOfInterest"}]},{"value":"MPLocationBaseType","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationBaseType\/fragments","op":"replace","value":[{"text":"MPLocationBaseType","kind":"identifier"}]}]}]}