{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTravelMode"]]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPTravelModeDriving"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"driving"}],"externalID":"c:@M@MapsIndoors@E@MPTravelMode@MPTravelModeDriving","modules":[{"name":"MapsIndoors"}],"roleHeading":"Case","symbolKind":"case","title":"MPTravelMode.driving"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mptravelmode\/driving"]},{"paths":["\/documentation\/mapsindoors\/mptravelmode\/driving"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"driving"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTravelMode\/driving","interfaceLanguage":"swift"},"references":{"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTravelMode":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPTravelMode"}],"type":"topic","abstract":[],"title":"MPTravelMode","role":"symbol","url":"\/documentation\/mapsindoors\/mptravelmode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MPTravelMode","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTravelMode"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPTravelMode/driving":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPTravelMode\/driving","abstract":[],"title":"MPTravelMode.driving","kind":"symbol","navigatorTitle":[{"text":"MPTravelModeDriving","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mptravelmode\/driving","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"driving","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MPTravelModeDriving"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPTravelModeDriving"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MPTravelModeDriving","kind":"identifier"}],"platforms":["iOS"]}]}},{"value":"MPTravelMode","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTravelMode\/title"},{"value":[{"kind":"identifier","text":"MPTravelMode"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTravelMode\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTravelMode~1driving\/title","value":"MPTravelModeDriving","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPTravelMode~1driving\/fragments","value":[{"kind":"identifier","text":"MPTravelModeDriving"}],"op":"replace"}]}]}