{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"directionsRouteNotFound","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError"]]},"variants":[{"paths":["\/documentation\/mapsindoors\/mperror\/directionsroutenotfound"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mperror\/directionsroutenotfound"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"roleHeading":"Case","modules":[{"name":"MapsIndoors"}],"title":"MPError.directionsRouteNotFound","navigatorTitle":[{"text":"MPErrorDirectionsRouteNotFound","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@E@MPError@MPErrorDirectionsRouteNotFound","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"directionsRouteNotFound","kind":"identifier"}],"role":"symbol","symbolKind":"case"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/directionsRouteNotFound"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError":{"url":"\/documentation\/mapsindoors\/mperror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPError","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MPError","kind":"identifier"}],"abstract":[{"text":"MapsIndoors error codes","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError","title":"MPError","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError/directionsRouteNotFound":{"kind":"symbol","role":"symbol","title":"MPError.directionsRouteNotFound","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"directionsRouteNotFound"}],"url":"\/documentation\/mapsindoors\/mperror\/directionsroutenotfound","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/directionsRouteNotFound","navigatorTitle":[{"kind":"identifier","text":"MPErrorDirectionsRouteNotFound"}],"abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MPErrorDirectionsRouteNotFound","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"MPErrorDirectionsRouteNotFound","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"MPErrorDirectionsRouteNotFound","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MPError","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError\/fragments","value":[{"text":"MPError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1directionsRouteNotFound\/title","op":"replace","value":"MPErrorDirectionsRouteNotFound"},{"value":[{"text":"MPErrorDirectionsRouteNotFound","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1directionsRouteNotFound\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}