{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mperror\/directionsmatrixnotfound"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mperror\/directionsmatrixnotfound"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/directionsMatrixNotFound"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError"]]},"metadata":{"modules":[{"name":"MapsIndoors"}],"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@MapsIndoors@E@MPError@MPErrorDirectionsMatrixNotFound","role":"symbol","title":"MPError.directionsMatrixNotFound","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"directionsMatrixNotFound"}],"navigatorTitle":[{"kind":"identifier","text":"MPErrorDirectionsMatrixNotFound"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"directionsMatrixNotFound","kind":"identifier"}]}]}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError/directionsMatrixNotFound":{"role":"symbol","url":"\/documentation\/mapsindoors\/mperror\/directionsmatrixnotfound","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPErrorDirectionsMatrixNotFound"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/directionsMatrixNotFound","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"directionsMatrixNotFound","kind":"identifier"}],"title":"MPError.directionsMatrixNotFound"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError":{"role":"symbol","url":"\/documentation\/mapsindoors\/mperror","type":"topic","navigatorTitle":[{"text":"MPError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors error codes"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPError"}],"title":"MPError"},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","alt":null,"type":"image"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"MPErrorDirectionsMatrixNotFound","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MPErrorDirectionsMatrixNotFound","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"MPErrorDirectionsMatrixNotFound","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1directionsMatrixNotFound\/title","value":"MPErrorDirectionsMatrixNotFound"},{"value":[{"text":"MPErrorDirectionsMatrixNotFound","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1directionsMatrixNotFound\/fragments","op":"replace"},{"op":"replace","value":"MPError","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError\/fragments","value":[{"text":"MPError","kind":"identifier"}]}]}]}