{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"liveDataSubscriptionFailedInactive","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/liveDataSubscriptionFailedInactive","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"liveDataSubscriptionFailedInactive","kind":"identifier"}],"title":"MPError.liveDataSubscriptionFailedInactive","externalID":"c:@M@MapsIndoors@E@MPError@MPErrorLiveDataSubscriptionFailedInactive","role":"symbol","roleHeading":"Case","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPErrorLiveDataSubscriptionFailedInactive"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mperror\/livedatasubscriptionfailedinactive"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mperror\/livedatasubscriptionfailedinactive"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError":{"role":"symbol","url":"\/documentation\/mapsindoors\/mperror","type":"topic","navigatorTitle":[{"text":"MPError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors error codes"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPError"}],"title":"MPError"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"MapsPeopleWhite.png":{"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null,"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError/liveDataSubscriptionFailedInactive":{"role":"symbol","url":"\/documentation\/mapsindoors\/mperror\/livedatasubscriptionfailedinactive","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPErrorLiveDataSubscriptionFailedInactive"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/liveDataSubscriptionFailedInactive","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"liveDataSubscriptionFailedInactive"}],"title":"MPError.liveDataSubscriptionFailedInactive"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"MPErrorLiveDataSubscriptionFailedInactive","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPErrorLiveDataSubscriptionFailedInactive"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"MPErrorLiveDataSubscriptionFailedInactive"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError\/title","value":"MPError"},{"value":[{"kind":"identifier","text":"MPError"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError\/fragments","op":"replace"},{"op":"replace","value":"MPErrorLiveDataSubscriptionFailedInactive","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1liveDataSubscriptionFailedInactive\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1liveDataSubscriptionFailedInactive\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPErrorLiveDataSubscriptionFailedInactive"}]}]}]}