{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/unknownError","interfaceLanguage":"swift"},"metadata":{"title":"MPError.unknownError","modules":[{"name":"MapsIndoors"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"externalID":"c:@M@MapsIndoors@E@MPError@MPErrorUnknownError","symbolKind":"case","navigatorTitle":[{"text":"MPErrorUnknownError","kind":"identifier"}],"roleHeading":"Case","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mperror\/unknownerror"]},{"paths":["\/documentation\/mapsindoors\/mperror\/unknownerror"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError/unknownError":{"type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError\/unknownError","kind":"symbol","title":"MPError.unknownError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPErrorUnknownError"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mperror\/unknownerror","abstract":[]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPError":{"url":"\/documentation\/mapsindoors\/mperror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPError","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MPError","kind":"identifier"}],"abstract":[{"text":"MapsIndoors error codes","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPError","title":"MPError","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MPErrorUnknownError","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MPErrorUnknownError","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"MPErrorUnknownError","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MPErrorUnknownError","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1unknownError\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError~1unknownError\/fragments","value":[{"text":"MPErrorUnknownError","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError\/title","value":"MPError"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPError\/fragments","value":[{"kind":"identifier","text":"MPError"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}