{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate"]]},"variants":[{"paths":["\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/didsubscribe(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/didsubscribe(_:)"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSubscribe"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"topic","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionTopic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionTopic","text":"MPSubscriptionTopic"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","externalID":"c:@M@MapsIndoors@objc(pl)MPSubscriptionClientDelegate(im)didSubscribe:","required":true,"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"didSubscribe:"}],"modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didSubscribe"},{"kind":"text","text":"("},{"text":"MPSubscriptionTopic","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionTopic"},{"kind":"text","text":")"}],"symbolKind":"method","title":"didSubscribe(_:)"},"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/didSubscribe(_:)","interfaceLanguage":"swift"},"references":{"MapsPeopleWhite.png":{"alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image","identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClientDelegate/didSubscribe(_:)":{"title":"didSubscribe(_:)","url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/didsubscribe(_:)","abstract":[],"required":true,"role":"symbol","navigatorTitle":[{"text":"didSubscribe:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didSubscribe","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionTopic","text":"MPSubscriptionTopic"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/didSubscribe(_:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionTopic":{"url":"\/documentation\/mapsindoors\/mpsubscriptiontopic","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPSubscriptionTopic","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionTopic","navigatorTitle":[{"text":"MPSubscriptionTopic","kind":"identifier"}],"role":"symbol","abstract":[],"title":"MPSubscriptionTopic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClientDelegate":{"url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPSubscriptionClientDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate","navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionClientDelegate"}],"role":"symbol","abstract":[],"title":"MPSubscriptionClientDelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"didSubscribe:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"didSubscribe:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"didSubscribe:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPSubscriptionTopic","kind":"typeIdentifier","text":"id<MPSubscriptionTopic>"},{"kind":"text","text":" *) "},{"text":"topic","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1didSubscribe(_:)\/title","value":"didSubscribe:"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1didSubscribe(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"didSubscribe:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionTopic\/title","value":"MPSubscriptionTopic"},{"value":[{"kind":"identifier","text":"MPSubscriptionTopic"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionTopic\/fragments","op":"replace"},{"op":"replace","value":"MPSubscriptionClientDelegate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate\/title"},{"value":[{"kind":"identifier","text":"MPSubscriptionClientDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}