{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/didUpdateState(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate"]]},"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didUpdateState"},{"text":"(","kind":"text"},{"text":"MPSubscriptionState","preciseIdentifier":"c:@M@MapsIndoors@E@MPSubscriptionState","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPSubscriptionClientDelegate(im)didUpdateState:","navigatorTitle":[{"text":"didUpdateState:","kind":"identifier"}],"symbolKind":"method","role":"symbol","required":true,"modules":[{"name":"MapsIndoors"}],"title":"didUpdateState(_:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didUpdateState","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionState","text":"MPSubscriptionState","preciseIdentifier":"c:@M@MapsIndoors@E@MPSubscriptionState"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/didupdatestate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/didupdatestate(_:)"]}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClientDelegate/didUpdateState(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateState"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPSubscriptionState","text":"MPSubscriptionState"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"didUpdateState:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/didUpdateState(_:)","required":true,"type":"topic","role":"symbol","kind":"symbol","title":"didUpdateState(_:)","url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/didupdatestate(_:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClientDelegate":{"kind":"symbol","navigatorTitle":[{"text":"MPSubscriptionClientDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate","url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPSubscriptionClientDelegate","kind":"identifier"}],"title":"MPSubscriptionClientDelegate","type":"topic","role":"symbol","abstract":[]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionState":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionState","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPSubscriptionState"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpsubscriptionstate","navigatorTitle":[{"text":"MPSubscriptionState","kind":"identifier"}],"title":"MPSubscriptionState","abstract":[],"role":"symbol","kind":"symbol"},"MapsPeopleWhite.png":{"type":"image","identifier":"MapsPeopleWhite.png","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"didUpdateState:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdateState:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didUpdateState:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionState","text":"MPSubscriptionState","preciseIdentifier":"c:@M@MapsIndoors@E@MPSubscriptionState"},{"text":") ","kind":"text"},{"text":"state","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1didUpdateState(_:)\/title","op":"replace","value":"didUpdateState:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUpdateState:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1didUpdateState(_:)\/fragments"},{"op":"replace","value":"MPSubscriptionClientDelegate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate\/title"},{"value":[{"text":"MPSubscriptionClientDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionState\/title","value":"MPSubscriptionState"},{"value":[{"text":"MPSubscriptionState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionState\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}