{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSubscriptionError"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topic"},{"kind":"text","text":": "},{"text":"MPSubscriptionTopic","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionTopic","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionTopic"},{"text":")","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/onSubscriptionError(_:topic:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/onsubscriptionerror(_:topic:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/onsubscriptionerror(_:topic:)"]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate"]]},"metadata":{"required":true,"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onSubscriptionError:topic:"}],"modules":[{"name":"MapsIndoors"}],"title":"onSubscriptionError(_:topic:)","externalID":"c:@M@MapsIndoors@objc(pl)MPSubscriptionClientDelegate(im)onSubscriptionError:topic:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onSubscriptionError","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topic"},{"kind":"text","text":": "},{"text":"MPSubscriptionTopic","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionTopic"},{"text":")","kind":"text"}],"role":"symbol"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionTopic":{"url":"\/documentation\/mapsindoors\/mpsubscriptiontopic","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPSubscriptionTopic","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionTopic","navigatorTitle":[{"text":"MPSubscriptionTopic","kind":"identifier"}],"role":"symbol","abstract":[],"title":"MPSubscriptionTopic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClientDelegate/onSubscriptionError(_:topic:)":{"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/onSubscriptionError(_:topic:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onSubscriptionError"},{"text":"(","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"topic","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MPSubscriptionTopic","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionTopic"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onSubscriptionError:topic:"}],"title":"onSubscriptionError(_:topic:)","required":true,"url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/onsubscriptionerror(_:topic:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClientDelegate":{"url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPSubscriptionClientDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate","navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionClientDelegate"}],"role":"symbol","abstract":[],"title":"MPSubscriptionClientDelegate"},"MapsPeopleWhite.png":{"alt":null,"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onSubscriptionError:topic:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onSubscriptionError:topic:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onSubscriptionError:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":" "},{"kind":"identifier","text":"topic:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPSubscriptionTopic","text":"id<MPSubscriptionTopic>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"topic"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"MPSubscriptionTopic","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionTopic\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionTopic\/fragments","value":[{"text":"MPSubscriptionTopic","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1onSubscriptionError(_:topic:)\/title","value":"onSubscriptionError:topic:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onSubscriptionError:topic:"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1onSubscriptionError(_:topic:)\/fragments"},{"op":"replace","value":"MPSubscriptionClientDelegate","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate\/fragments","value":[{"text":"MPSubscriptionClientDelegate","kind":"identifier"}]}]}]}