{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate"]]},"variants":[{"paths":["\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/onunsubscriptionerror(_:topic:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/onunsubscriptionerror(_:topic:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/onUnsubscriptionError(_:topic:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"required":true,"externalID":"c:@M@MapsIndoors@objc(pl)MPSubscriptionClientDelegate(im)onUnsubscriptionError:topic:","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onUnsubscriptionError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":", "},{"text":"topic","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPSubscriptionTopic","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionTopic"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onUnsubscriptionError:topic:","kind":"identifier"}],"role":"symbol","modules":[{"name":"MapsIndoors"}],"title":"onUnsubscriptionError(_:topic:)"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onUnsubscriptionError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topic"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionTopic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionTopic","text":"MPSubscriptionTopic"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClientDelegate/onUnsubscriptionError(_:topic:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"onUnsubscriptionError:topic:","kind":"identifier"}],"abstract":[],"required":true,"url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate\/onunsubscriptionerror(_:topic:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onUnsubscriptionError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topic"},{"text":": ","kind":"text"},{"text":"MPSubscriptionTopic","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPSubscriptionTopic"},{"kind":"text","text":")"}],"title":"onUnsubscriptionError(_:topic:)","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate\/onUnsubscriptionError(_:topic:)"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionClientDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPSubscriptionClientDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionClientDelegate"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpsubscriptionclientdelegate","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionClientDelegate","abstract":[],"title":"MPSubscriptionClientDelegate","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPSubscriptionTopic":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSubscriptionTopic"}],"navigatorTitle":[{"kind":"identifier","text":"MPSubscriptionTopic"}],"role":"symbol","url":"\/documentation\/mapsindoors\/mpsubscriptiontopic","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPSubscriptionTopic","abstract":[],"title":"MPSubscriptionTopic","type":"topic"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","alt":null,"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"onUnsubscriptionError:topic:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onUnsubscriptionError:topic:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"onUnsubscriptionError:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":" "},{"text":"topic:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPSubscriptionTopic","kind":"typeIdentifier","text":"id<MPSubscriptionTopic>"},{"kind":"text","text":" *) "},{"text":"topic","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1onUnsubscriptionError(_:topic:)\/title","value":"onUnsubscriptionError:topic:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onUnsubscriptionError:topic:"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate~1onUnsubscriptionError(_:topic:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate\/title","value":"MPSubscriptionClientDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionClientDelegate\/fragments","value":[{"kind":"identifier","text":"MPSubscriptionClientDelegate"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionTopic\/title","op":"replace","value":"MPSubscriptionTopic"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPSubscriptionTopic\/fragments","value":[{"text":"MPSubscriptionTopic","kind":"identifier"}]}]}]}