{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationsUsing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPQuery","preciseIdentifier":"c:objc(cs)MPQuery","text":"MPQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFilter","preciseIdentifier":"c:objc(cs)MPFilter","text":"MPFilter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":" "},{"kind":"internalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpLocationsHandlerBlockType","preciseIdentifier":"c:MPLocationService.h@T@mpLocationsHandlerBlockType","text":"mpLocationsHandlerBlockType"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationservice\/getlocationsusing(_:filter:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationservice\/getlocationsusing(_:filter:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationService\/getLocationsUsing(_:filter:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get locations with given filter, query and callback handler block."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationsUsing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPQuery","preciseIdentifier":"c:objc(cs)MPQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPFilter","preciseIdentifier":"c:objc(cs)MPFilter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpLocationsHandlerBlockType","preciseIdentifier":"c:MPLocationService.h@T@mpLocationsHandlerBlockType"},{"kind":"text","text":"?)"}],"title":"getLocationsUsing(_:filter:completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPLocationService(im)getLocationsUsingQuery:filter:completionHandler:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"getLocationsUsingQuery:filter:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationService"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/mpLocationsHandlerBlockType":{"role":"symbol","title":"mpLocationsHandlerBlockType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mpLocationsHandlerBlockType"}],"abstract":[{"type":"text","text":"Handler block for a locations query"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/mpLocationsHandlerBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mpLocationsHandlerBlockType"}],"url":"\/documentation\/mapsindoors\/mplocationshandlerblocktype"},"doc://MapsIndoors/documentation/MapsIndoors/MPFilter":{"role":"symbol","title":"MPFilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFilter"}],"abstract":[{"type":"text","text":"Filter object used when making a request to "},{"type":"codeVoice","code":"MPLocationService"},{"type":"text","text":". The filters will be applied in the following order:"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPFilter"}],"url":"\/documentation\/mapsindoors\/mpfilter"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationService/getLocationsUsing(_:filter:completionHandler:)":{"role":"symbol","title":"getLocationsUsing(_:filter:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLocationsUsing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MPQuery","preciseIdentifier":"c:objc(cs)MPQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPFilter","preciseIdentifier":"c:objc(cs)MPFilter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"mpLocationsHandlerBlockType","preciseIdentifier":"c:MPLocationService.h@T@mpLocationsHandlerBlockType"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Get locations with given filter, query and callback handler block."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationService\/getLocationsUsing(_:filter:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getLocationsUsingQuery:filter:completionHandler:"}],"url":"\/documentation\/mapsindoors\/mplocationservice\/getlocationsusing(_:filter:completionhandler:)"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationService":{"role":"symbol","title":"MPLocationService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationService"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"LocationService"},{"type":"text","text":" acts as service for search and filtering in the full, aggregated collection of Locations. The service requests from all registered Location sources, both internal MapsIndoors and external. Get the shared instance through "},{"type":"codeVoice","code":"MPLocationService.sharedInstance"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationService"}],"url":"\/documentation\/mapsindoors\/mplocationservice"},"doc://MapsIndoors/documentation/MapsIndoors/MPQuery":{"role":"symbol","title":"MPQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPQuery"}],"abstract":[{"type":"text","text":"Query object used when making a request to "},{"type":"codeVoice","code":"MPLocationService"},{"type":"text","text":"."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPQuery"}],"url":"\/documentation\/mapsindoors\/mpquery"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getLocationsUsingQuery:filter:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationsUsingQuery:filter:completionHandler:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getLocationsUsingQuery:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPQuery","preciseIdentifier":"c:objc(cs)MPQuery","text":"MPQuery"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"query"},{"kind":"text","text":" "},{"kind":"identifier","text":"filter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFilter","preciseIdentifier":"c:objc(cs)MPFilter","text":"MPFilter"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"filter"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<MPLocation *> *, NSError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"handler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpLocationsHandlerBlockType\/title","value":"mpLocationsHandlerBlockType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1mpLocationsHandlerBlockType\/fragments","value":[{"kind":"identifier","text":"mpLocationsHandlerBlockType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFilter\/title","value":"MPFilter"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFilter\/fragments","value":[{"kind":"identifier","text":"MPFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationService~1getLocationsUsing(_:filter:completionHandler:)\/title","value":"getLocationsUsingQuery:filter:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationService~1getLocationsUsing(_:filter:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLocationsUsingQuery:filter:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationService\/title","value":"MPLocationService"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationService\/fragments","value":[{"kind":"identifier","text":"MPLocationService"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPQuery\/title","value":"MPQuery"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPQuery\/fragments","value":[{"kind":"identifier","text":"MPQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}