{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andType"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationproperty\/init(value:andtype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationproperty\/init(value:andtype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationProperty\/init(value:andType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initialization that takes a type identifier and a value"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(value:andType:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)MPLocationProperty(im)initWithValue:andType:","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"initWithValue:andType:"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationProperty"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationProperty":{"role":"symbol","title":"MPLocationProperty","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationProperty"}],"abstract":[{"type":"text","text":"Creates a location property, holding a type identifier and a value"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationProperty","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationProperty"}],"url":"\/documentation\/mapsindoors\/mplocationproperty"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationProperty/init(value:andType:)":{"role":"symbol","title":"init(value:andType:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"andType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initialization that takes a type identifier and a value"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationProperty\/init(value:andType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithValue:andType:"}],"url":"\/documentation\/mapsindoors\/mplocationproperty\/init(value:andtype:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithValue:andType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:andType:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithValue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"value"},{"kind":"text","text":" "},{"kind":"identifier","text":"andType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationProperty\/title","value":"MPLocationProperty"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationProperty\/fragments","value":[{"kind":"identifier","text":"MPLocationProperty"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationProperty~1init(value:andType:)\/title","value":"initWithValue:andType:"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationProperty~1init(value:andType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:andType:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}