{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"elements"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixElements-swift.class","preciseIdentifier":"c:objc(cs)MPDistanceMatrixElements","text":"MPDistanceMatrixElements"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdistancematrixrows-swift.class\/elements"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdistancematrixrows-swift.class\/elements"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixRows-swift.class\/elements","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"elements"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPDistanceMatrixElements","preciseIdentifier":"c:objc(cs)MPDistanceMatrixElements"},{"kind":"text","text":"]?"}],"title":"elements","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPDistanceMatrixRows(py)elements","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"elements"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixRows-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixRows-swift.class":{"role":"symbol","title":"MPDistanceMatrixRows","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDistanceMatrixRows"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixRows-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDistanceMatrixRows"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixrows-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixElements-swift.class":{"role":"symbol","title":"MPDistanceMatrixElements","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDistanceMatrixElements"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixElements-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDistanceMatrixElements"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixelements-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPDistanceMatrixRows-swift.class/elements":{"role":"symbol","title":"elements","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"elements"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MPDistanceMatrixElements","preciseIdentifier":"c:objc(cs)MPDistanceMatrixElements"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDistanceMatrixRows-swift.class\/elements","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"elements"}],"url":"\/documentation\/mapsindoors\/mpdistancematrixrows-swift.class\/elements"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"elements"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"elements"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<MPDistanceMatrixElements *><MPDistanceMatrixElements>","preciseIdentifier":"c:Q$objc(cs)NSArrayobjc(pl)MPDistanceMatrixElements"},{"kind":"text","text":" *"},{"kind":"identifier","text":"elements"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixRows-swift.class\/title","value":"MPDistanceMatrixRows"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixRows-swift.class\/fragments","value":[{"kind":"identifier","text":"MPDistanceMatrixRows"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixElements-swift.class\/title","value":"MPDistanceMatrixElements"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixElements-swift.class\/fragments","value":[{"kind":"identifier","text":"MPDistanceMatrixElements"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixRows-swift.class~1elements\/title","value":"elements"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDistanceMatrixRows-swift.class~1elements\/fragments","value":[{"kind":"identifier","text":"elements"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}