{"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/apply(userRoles:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"apply(userRoles:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apply"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userRoles"},{"kind":"text","text":": ["},{"text":"MPUserRole","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPUserRole","kind":"typeIdentifier"},{"text":"]) ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"applyWithUserRoles:completionHandler:","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"required":true,"externalID":"c:@M@MapsIndoors@objc(pl)MapsIndoorsShared(im)applyWithUserRoles:completionHandler:"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"apply","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userRoles"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPUserRole","text":"MPUserRole","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPUserRole"},{"text":"]) ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Set and apply a list of "},{"type":"codeVoice","code":"MPUserRole"},{"text":"s asynchronously","type":"text"}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/mapsindoors\/mapsindoorsshared\/apply(userroles:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mapsindoorsshared\/apply(userroles:)"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPUserRole":{"title":"MPUserRole","kind":"symbol","abstract":[],"url":"\/documentation\/mapsindoors\/mpuserrole","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPUserRole"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPUserRole","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MPUserRole","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/apply(userRoles:)":{"abstract":[{"text":"Set and apply a list of ","type":"text"},{"type":"codeVoice","code":"MPUserRole"},{"text":"s asynchronously","type":"text"}],"kind":"symbol","title":"apply(userRoles:)","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/apply(userRoles:)","navigatorTitle":[{"text":"applyWithUserRoles:completionHandler:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/apply(userroles:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"apply","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userRoles","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPUserRole","text":"MPUserRole","kind":"typeIdentifier"},{"text":"]) ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapsIndoorsShared","kind":"identifier"}],"navigatorTitle":[{"text":"MapsIndoorsShared","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared","abstract":[{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared","isActive":true},{"type":"text","text":" describes the main entry point to the SDK which is accessed via "},{"type":"codeVoice","code":"MPMapsIndoors\/shared"},{"text":".","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","title":"MapsIndoorsShared","url":"\/documentation\/mapsindoors\/mapsindoorsshared"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"applyWithUserRoles:completionHandler:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"applyWithUserRoles:completionHandler:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"applyWithUserRoles:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<MPUserRole *>"},{"text":" *) ","kind":"text"},{"text":"userRoles","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"MPUserRole","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPUserRole\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPUserRole\/fragments","op":"replace","value":[{"text":"MPUserRole","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1apply(userRoles:)\/title","value":"applyWithUserRoles:completionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1apply(userRoles:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applyWithUserRoles:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared\/title","value":"MapsIndoorsShared"},{"value":[{"kind":"identifier","text":"MapsIndoorsShared"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared\/fragments"}]}]}