{"abstract":[{"type":"text","text":"For creating instances of ``MPLocationUpdate`"},{"type":"text","text":" "},{"text":"This approach of creating instances is subject to change","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/createLocationUpdateFactory()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mapsindoorsshared\/createlocationupdatefactory()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mapsindoorsshared\/createlocationupdatefactory()"]}],"sections":[],"metadata":{"role":"symbol","modules":[{"name":"MapsIndoors"}],"title":"createLocationUpdateFactory()","symbolKind":"method","externalID":"c:@M@MapsIndoors@objc(pl)MapsIndoorsShared(cm)createLocationUpdateFactory","navigatorTitle":[{"text":"createLocationUpdateFactory","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createLocationUpdateFactory","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MPLocationUpdateFactory","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationUpdateFactory"}],"required":true,"roleHeading":"Type Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createLocationUpdateFactory"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"MPLocationUpdateFactory","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdateFactory","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationUpdateFactory"}]}]}],"references":{"MapsPeopleWhite.png":{"alt":null,"type":"image","identifier":"MapsPeopleWhite.png","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/createLocationUpdateFactory()":{"title":"createLocationUpdateFactory()","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/createLocationUpdateFactory()","type":"topic","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/createlocationupdatefactory()","abstract":[{"text":"For creating instances of ``MPLocationUpdate`","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This approach of creating instances is subject to change"}],"navigatorTitle":[{"text":"createLocationUpdateFactory","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createLocationUpdateFactory","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationUpdateFactory","kind":"typeIdentifier","text":"MPLocationUpdateFactory"}],"kind":"symbol","required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationUpdateFactory":{"url":"\/documentation\/mapsindoors\/mplocationupdatefactory","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationUpdateFactory"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationUpdateFactory"}],"kind":"symbol","abstract":[{"type":"text","text":"Protocol  to create instance of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdateFactory","title":"MPLocationUpdateFactory","role":"symbol"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationUpdate":{"abstract":[],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationUpdate","type":"topic","url":"\/documentation\/mapsindoors\/mplocationupdate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationUpdate"}],"kind":"symbol","title":"MPLocationUpdate","role":"symbol","navigatorTitle":[{"text":"MPLocationUpdate","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapsIndoorsShared","kind":"identifier"}],"navigatorTitle":[{"text":"MapsIndoorsShared","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared","abstract":[{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared","isActive":true},{"type":"text","text":" describes the main entry point to the SDK which is accessed via "},{"type":"codeVoice","code":"MPMapsIndoors\/shared"},{"text":".","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","title":"MapsIndoorsShared","url":"\/documentation\/mapsindoors\/mapsindoorsshared"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","value":"createLocationUpdateFactory","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createLocationUpdateFactory"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"id<MPLocationUpdateFactory>","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPLocationUpdateFactory","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"createLocationUpdateFactory","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"createLocationUpdateFactory","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1createLocationUpdateFactory()\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1createLocationUpdateFactory()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createLocationUpdateFactory"}]},{"op":"replace","value":"MPLocationUpdateFactory","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdateFactory\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdateFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPLocationUpdateFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdate\/title","value":"MPLocationUpdate"},{"op":"replace","value":[{"text":"MPLocationUpdate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationUpdate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared\/title","value":"MapsIndoorsShared"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared\/fragments","value":[{"text":"MapsIndoorsShared","kind":"identifier"}],"op":"replace"}]}]}