{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"displayRuleFor","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"displayRuleType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@E@MPDisplayRuleType","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType","text":"MPDisplayRuleType"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule","kind":"typeIdentifier","text":"MPDisplayRule"},{"kind":"text","text":"?"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mapsindoorsshared\/displayrulefor(displayruletype:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mapsindoorsshared\/displayrulefor(displayruletype:)"]}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/displayRuleFor(displayRuleType:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared"]]},"sections":[],"metadata":{"modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"displayRuleForDisplayRuleType:","kind":"identifier"}],"roleHeading":"Instance Method","required":true,"externalID":"c:@M@MapsIndoors@objc(pl)MapsIndoorsShared(im)displayRuleForDisplayRuleType:","title":"displayRuleFor(displayRuleType:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayRuleFor"},{"kind":"text","text":"("},{"text":"displayRuleType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPDisplayRuleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPDisplayRuleType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule","text":"MPDisplayRule","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"symbolKind":"method"},"abstract":[{"type":"text","text":"Get display rules used for various general styling (e.g. building outline)."}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared":{"url":"\/documentation\/mapsindoors\/mapsindoorsshared","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MapsIndoorsShared","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsIndoorsShared"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared","abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared"},{"type":"text","text":" describes the main entry point to the SDK which is accessed via "},{"type":"codeVoice","code":"MPMapsIndoors\/shared"},{"text":".","type":"text"}],"title":"MapsIndoorsShared"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRule":{"kind":"symbol","abstract":[{"text":"This class represents a Display Rule, a MapsIndoors concept which describes a number of styling values for MapsIndoors objects.","type":"text"},{"type":"text","text":" "},{"text":"The values contained within dictates how the MapsIndoors SDK renders a given object on the map (POI, area, selection, model, etc.).","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MPDisplayRule","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdisplayrule","navigatorTitle":[{"text":"MPDisplayRule","kind":"identifier"}],"title":"MPDisplayRule"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/displayRuleFor(displayRuleType:)":{"abstract":[{"type":"text","text":"Get display rules used for various general styling (e.g. building outline)."}],"type":"topic","title":"displayRuleFor(displayRuleType:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"displayRuleFor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"displayRuleType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@E@MPDisplayRuleType","kind":"typeIdentifier","text":"MPDisplayRuleType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"MPDisplayRule","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/displayRuleFor(displayRuleType:)","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/displayrulefor(displayruletype:)","required":true,"role":"symbol","navigatorTitle":[{"text":"displayRuleForDisplayRuleType:","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDisplayRuleType":{"role":"symbol","abstract":[{"text":"The MapsIndoors SDK contains a number of display rules used to style non-location content (blue dot, buildings or locations when they are selected).","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDisplayRuleType","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpdisplayruletype","type":"topic","title":"MPDisplayRuleType","navigatorTitle":[{"kind":"identifier","text":"MPDisplayRuleType"}],"kind":"symbol"},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"alt":null,"identifier":"MapsPeopleWhite.png","type":"image"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"displayRuleForDisplayRuleType:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"displayRuleForDisplayRuleType:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPDisplayRule","text":"MPDisplayRule","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRule","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"displayRuleForDisplayRuleType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@E@MPDisplayRuleType","kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDisplayRuleType","text":"MPDisplayRuleType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"displayRuleType"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"MapsIndoorsShared","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared\/title"},{"value":[{"kind":"identifier","text":"MapsIndoorsShared"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared\/fragments","op":"replace"},{"value":"MPDisplayRule","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRule\/fragments","value":[{"kind":"identifier","text":"MPDisplayRule"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1displayRuleFor(displayRuleType:)\/title","value":"displayRuleForDisplayRuleType:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1displayRuleFor(displayRuleType:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"displayRuleForDisplayRuleType:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType\/title","value":"MPDisplayRuleType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDisplayRuleType\/fragments","value":[{"kind":"identifier","text":"MPDisplayRuleType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}