{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchAuthDetails","kind":"identifier"},{"kind":"text","text":"() "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPAuthDetails","text":"MPAuthDetails","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Fetch authentication details using MapsIndoors API key.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/fetchAuthDetails()"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mapsindoorsshared\/fetchauthdetails()"]},{"paths":["\/documentation\/mapsindoors\/mapsindoorsshared\/fetchauthdetails()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchAuthDetails","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPAuthDetails","text":"MPAuthDetails"},{"text":"?","kind":"text"}],"externalID":"c:@M@MapsIndoors@objc(pl)MapsIndoorsShared(im)fetchAuthDetailsWithCompletionHandler:","roleHeading":"Instance Method","modules":[{"name":"MapsIndoors"}],"role":"symbol","navigatorTitle":[{"text":"fetchAuthDetailsWithCompletionHandler:","kind":"identifier"}],"title":"fetchAuthDetails()","required":true,"symbolKind":"method"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/fetchAuthDetails()":{"title":"fetchAuthDetails()","type":"topic","abstract":[{"type":"text","text":"Fetch authentication details using MapsIndoors API key."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/fetchAuthDetails()","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fetchAuthDetails","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"MPAuthDetails","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPAuthDetails"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"fetchAuthDetailsWithCompletionHandler:","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mapsindoorsshared\/fetchauthdetails()"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"kind":"symbol","abstract":[{"type":"text","text":"MapsIndoors enables you to show indoor maps in your apps."},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","type":"topic","url":"\/documentation\/mapsindoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPAuthDetails":{"abstract":[{"type":"text","text":"The OAuth2 details to be used for performing an OAuth2 login flow in an app using MapsIndoors."}],"type":"topic","title":"MPAuthDetails","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MPAuthDetails","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPAuthDetails","url":"\/documentation\/mapsindoors\/mpauthdetails","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPAuthDetails"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared":{"url":"\/documentation\/mapsindoors\/mapsindoorsshared","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MapsIndoorsShared","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapsIndoorsShared"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared","abstract":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared"},{"type":"text","text":" describes the main entry point to the SDK which is accessed via "},{"type":"codeVoice","code":"MPMapsIndoors\/shared"},{"text":".","type":"text"}],"title":"MapsIndoorsShared"},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null,"identifier":"MapsPeopleWhite.png","type":"image"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"fetchAuthDetailsWithCompletionHandler:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchAuthDetailsWithCompletionHandler:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"fetchAuthDetailsWithCompletionHandler:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(id<MPAuthDetails>, NSError *)","preciseIdentifier":"c:BFv(#*Qo@M@MapsIndoors@objc(pl)MPAuthDetails#*$objc(cs)NSError)"},{"text":") ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"fetchAuthDetailsWithCompletionHandler:","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1fetchAuthDetails()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"fetchAuthDetailsWithCompletionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1fetchAuthDetails()\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails\/title","op":"replace","value":"MPAuthDetails"},{"op":"replace","value":[{"text":"MPAuthDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPAuthDetails\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared\/title","value":"MapsIndoorsShared"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared\/fragments","value":[{"text":"MapsIndoorsShared","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}