{"kind":"symbol","identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/imageProvider","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared"]]},"abstract":[{"text":"The image provider that MapsIndoors should use when image resources are needed.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"imageProvider"}],"roleHeading":"Instance Property","externalID":"c:@M@MapsIndoors@objc(pl)MapsIndoorsShared(py)imageProvider","title":"imageProvider","modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPImageProviderProtocol","kind":"typeIdentifier","text":"MPImageProviderProtocol"}],"required":true},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPImageProviderProtocol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPImageProviderProtocol","text":"MPImageProviderProtocol","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mapsindoorsshared\/imageprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mapsindoorsshared\/imageprovider"]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/imageProvider":{"role":"symbol","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/imageprovider","navigatorTitle":[{"text":"imageProvider","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/imageProvider","title":"imageProvider","type":"topic","abstract":[{"type":"text","text":"The image provider that MapsIndoors should use when image resources are needed."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageProvider"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPImageProviderProtocol","text":"MPImageProviderProtocol","kind":"typeIdentifier"}],"kind":"symbol","required":true},"MapsPeopleWhite.png":{"variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}],"identifier":"MapsPeopleWhite.png","type":"image","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapsIndoorsShared","kind":"identifier"}],"navigatorTitle":[{"text":"MapsIndoorsShared","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared","abstract":[{"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared","isActive":true},{"type":"text","text":" describes the main entry point to the SDK which is accessed via "},{"type":"codeVoice","code":"MPMapsIndoors\/shared"},{"text":".","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","title":"MapsIndoorsShared","url":"\/documentation\/mapsindoors\/mapsindoorsshared"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPImageProviderProtocol":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPImageProviderProtocol"}],"navigatorTitle":[{"text":"MPImageProviderProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPImageProviderProtocol","url":"\/documentation\/mapsindoors\/mpimageproviderprotocol","abstract":[{"text":"Protocol to conform to when implementing an image provider for MapsIndoors.","type":"text"}],"type":"topic","title":"MPImageProviderProtocol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"imageProvider","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"imageProvider"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPImageProviderProtocol","kind":"typeIdentifier","text":"id<MPImageProviderProtocol>"},{"text":" * ","kind":"text"},{"text":"imageProvider","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"imageProvider","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1imageProvider\/title"},{"value":[{"text":"imageProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1imageProvider\/fragments"},{"value":"MapsIndoorsShared","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared\/title","op":"replace"},{"op":"replace","value":[{"text":"MapsIndoorsShared","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPImageProviderProtocol\/title","value":"MPImageProviderProtocol","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MPImageProviderProtocol"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPImageProviderProtocol\/fragments"}]}]}