{"metadata":{"externalID":"c:@M@MapsIndoors@objc(pl)MapsIndoorsShared(py)userRoles","required":true,"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"userRoles","kind":"identifier"}],"modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userRoles","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPUserRole","kind":"typeIdentifier","text":"MPUserRole"},{"text":"]","kind":"text"}],"symbolKind":"property","title":"userRoles"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mapsindoorsshared\/userroles"]},{"paths":["\/documentation\/mapsindoors\/mapsindoorsshared\/userroles"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"userRoles","kind":"identifier"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPUserRole","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPUserRole","text":"MPUserRole"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"Get or set the current list of applied user roles. If you want to apply user roles and wait for the SDK to load, use ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/apply(userRoles:)"},{"type":"text","text":" asynchronously."}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/userRoles"},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"url":"\/documentation\/mapsindoors","type":"topic","title":"MapsIndoors","kind":"symbol","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","role":"collection"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPUserRole":{"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPUserRole","role":"symbol","url":"\/documentation\/mapsindoors\/mpuserrole","navigatorTitle":[{"text":"MPUserRole","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPUserRole","kind":"identifier"}],"type":"topic","title":"MPUserRole","abstract":[]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/userRoles":{"required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/userRoles","kind":"symbol","role":"symbol","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/userroles","navigatorTitle":[{"text":"userRoles","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userRoles","kind":"identifier"},{"kind":"text","text":": ["},{"text":"MPUserRole","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPUserRole"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Get or set the current list of applied user roles. If you want to apply user roles and wait for the SDK to load, use "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/apply(userRoles:)","isActive":true,"type":"reference"},{"text":" asynchronously.","type":"text"}],"type":"topic","title":"userRoles"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared/apply(userRoles:)":{"required":true,"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared\/apply(userRoles:)","role":"symbol","url":"\/documentation\/mapsindoors\/mapsindoorsshared\/apply(userroles:)","navigatorTitle":[{"text":"applyWithUserRoles:completionHandler:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apply"},{"text":"(","kind":"text"},{"text":"userRoles","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"MPUserRole","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(cs)MPUserRole"},{"text":"]) ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"type":"topic","title":"apply(userRoles:)","abstract":[{"type":"text","text":"Set and apply a list of "},{"code":"MPUserRole","type":"codeVoice"},{"text":"s asynchronously","type":"text"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MapsIndoorsShared":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared","type":"topic","url":"\/documentation\/mapsindoors\/mapsindoorsshared","kind":"symbol","navigatorTitle":[{"text":"MapsIndoorsShared","kind":"identifier"}],"abstract":[{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MapsIndoorsShared","isActive":true,"type":"reference"},{"type":"text","text":" describes the main entry point to the SDK which is accessed via "},{"type":"codeVoice","code":"MPMapsIndoors\/shared"},{"type":"text","text":"."}],"title":"MapsIndoorsShared","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapsIndoorsShared","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"userRoles","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"userRoles","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"NSArray<MPUserRole *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"userRoles","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"MPUserRole","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPUserRole\/title"},{"op":"replace","value":[{"text":"MPUserRole","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPUserRole\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1userRoles\/title","value":"userRoles"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1userRoles\/fragments","value":[{"kind":"identifier","text":"userRoles"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1apply(userRoles:)\/title","op":"replace","value":"applyWithUserRoles:completionHandler:"},{"value":[{"text":"- ","kind":"text"},{"text":"applyWithUserRoles:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared~1apply(userRoles:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared\/title","value":"MapsIndoorsShared"},{"op":"replace","value":[{"text":"MapsIndoorsShared","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MapsIndoorsShared\/fragments"}]}]}