{"abstract":[{"type":"text","text":"Caching strategy for the data set."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcache\/cachingstrategy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapsindoors\/mpdatasetcache\/cachingstrategy"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache\/cachingStrategy"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache"]]},"metadata":{"role":"symbol","modules":[{"name":"MapsIndoors"}],"title":"cachingStrategy","required":true,"externalID":"c:@M@MapsIndoors@objc(pl)MPDataSetCache(py)cachingStrategy","navigatorTitle":[{"text":"cachingStrategy","kind":"identifier"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cachingStrategy"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingStrategy","text":"MPDataSetCachingStrategy"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cachingStrategy","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPDataSetCachingStrategy","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy","preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingStrategy"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCache":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache","abstract":[{"text":"Data set cache class.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCache"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPDataSetCache","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapsindoors\/mpdatasetcache","title":"MPDataSetCache"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCache/cachingStrategy":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cachingStrategy","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingStrategy","text":"MPDataSetCachingStrategy"}],"kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCache\/cachingStrategy","type":"topic","abstract":[{"type":"text","text":"Caching strategy for the data set."}],"url":"\/documentation\/mapsindoors\/mpdatasetcache\/cachingstrategy","required":true,"role":"symbol","navigatorTitle":[{"text":"cachingStrategy","kind":"identifier"}],"title":"cachingStrategy"},"MapsPeopleWhite.png":{"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","type":"image","alt":null},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDataSetCachingStrategy":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy","url":"\/documentation\/mapsindoors\/mpdatasetcachingstrategy","kind":"symbol","type":"topic","title":"MPDataSetCachingStrategy","abstract":[{"type":"text","text":"Data set caching strategy."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPDataSetCachingStrategy"}],"navigatorTitle":[{"kind":"identifier","text":"MPDataSetCachingStrategy"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"cachingStrategy","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cachingStrategy"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDataSetCachingStrategy","preciseIdentifier":"c:@M@MapsIndoors@E@MPDataSetCachingStrategy","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDataSetCachingStrategy","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cachingStrategy"}]}],"kind":"declarations"}},{"op":"replace","value":"MPDataSetCache","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache\/fragments","value":[{"kind":"identifier","text":"MPDataSetCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache~1cachingStrategy\/title","value":"cachingStrategy"},{"value":[{"kind":"identifier","text":"cachingStrategy"}],"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCache~1cachingStrategy\/fragments"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy\/title","value":"MPDataSetCachingStrategy","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MPDataSetCachingStrategy"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDataSetCachingStrategy\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}