{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpdatasetcache\/name"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpdatasetcache\/name"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCache\/name","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Dataset name."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"name","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPDataSetCache(py)name","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"name"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCache"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCache/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Dataset name."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCache\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/mapsindoors\/mpdatasetcache\/name"},"doc://MapsIndoors/documentation/MapsIndoors/MPDataSetCache":{"role":"symbol","title":"MPDataSetCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDataSetCache"}],"abstract":[{"type":"text","text":"Data set cache class."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPDataSetCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPDataSetCache"}],"url":"\/documentation\/mapsindoors\/mpdatasetcache"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"name"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"name"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCache~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCache~1name\/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCache\/title","value":"MPDataSetCache"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPDataSetCache\/fragments","value":[{"kind":"identifier","text":"MPDataSetCache"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}