{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hybrid"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplayertype\/hybrid()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplayertype\/hybrid()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLayerType\/hybrid()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Hybrid is a satellite map layer with roads and tracks on top of it."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hybrid"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"hybrid()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MPLayerType(cm)HYBRID","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"HYBRID"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLayerType"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLayerType":{"role":"symbol","title":"MPLayerType","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLayerType"}],"abstract":[{"type":"text","text":"Provides a static way to access the possible layer types for general purpose MapsPeople services"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLayerType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLayerType"}],"url":"\/documentation\/mapsindoors\/mplayertype"},"doc://MapsIndoors/documentation/MapsIndoors/MPLayerType/hybrid()":{"role":"symbol","title":"hybrid()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hybrid"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Hybrid is a satellite map layer with roads and tracks on top of it."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLayerType\/hybrid()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HYBRID"}],"url":"\/documentation\/mapsindoors\/mplayertype\/hybrid()"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"HYBRID"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"HYBRID"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"HYBRID"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLayerType\/title","value":"MPLayerType"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLayerType\/fragments","value":[{"kind":"identifier","text":"MPLayerType"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLayerType~1hybrid()\/title","value":"HYBRID"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLayerType~1hybrid()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"HYBRID"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}