{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"start_address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mprouteleg-swift.class\/start_address"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mprouteleg-swift.class\/start_address"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/start_address","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The route leg start address. If the position is outdoors, the address may be a postal address. If the position is indoors, the address may be a textual description of the indoor location, like “Lower Ground Floor, Building X”."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"start_address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"start_address","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPRouteLeg(py)start_address","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"start_address"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLeg-swift.class/start_address":{"role":"symbol","title":"start_address","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"start_address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The route leg start address. If the position is outdoors, the address may be a postal address. If the position is indoors, the address may be a textual description of the indoor location, like “Lower Ground Floor, Building X”."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class\/start_address","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"start_address"}],"url":"\/documentation\/mapsindoors\/mprouteleg-swift.class\/start_address"},"doc://MapsIndoors/documentation/MapsIndoors/MPRouteLeg-swift.class":{"role":"symbol","title":"MPRouteLeg","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRouteLeg"}],"abstract":[{"type":"text","text":"Route leg model. A route model will consist of one ore more route legs. Typically a route from 1st floor to 2nd floor will consist of two route legs. Thus, a route leg defines a continueus route part within the same floor and\/or building and\/or vehicle."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPRouteLeg-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPRouteLeg"}],"url":"\/documentation\/mapsindoors\/mprouteleg-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"start_address"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"start_address"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString<Optional>","preciseIdentifier":"c:Q$objc(cs)NSStringobjc(pl)Optional"},{"kind":"text","text":" *"},{"kind":"identifier","text":"start_address"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1start_address\/title","value":"start_address"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class~1start_address\/fragments","value":[{"kind":"identifier","text":"start_address"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class\/title","value":"MPRouteLeg"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPRouteLeg-swift.class\/fragments","value":[{"kind":"identifier","text":"MPRouteLeg"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}