{"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mproute\/overview_polyline"]},{"paths":["\/documentation\/mapsindoors\/mproute\/overview_polyline"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"required":true,"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"overview_polyline","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MPEncodedPolyline","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPEncodedPolyline"},{"kind":"text","text":"?"}],"title":"overview_polyline","externalID":"c:@M@MapsIndoors@objc(pl)MPRoute(py)overview_polyline","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"text":"overview_polyline","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"overview_polyline","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEncodedPolyline","text":"MPEncodedPolyline","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPEncodedPolyline"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/overview_polyline","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsService":{"abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","title":"MPDirectionsService","url":"\/documentation\/mapsindoors\/mpdirectionsservice","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPDirectionsService"}],"type":"topic","navigatorTitle":[{"text":"MPDirectionsService","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"kind":"symbol","title":"MapsIndoors","images":[{"identifier":"MapsPeopleWhite.png","type":"icon"}],"type":"topic","role":"collection","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","url":"\/documentation\/mapsindoors"},"MapsPeopleWhite.png":{"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"alt":null,"identifier":"MapsPeopleWhite.png"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute/overview_polyline":{"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"overview_polyline"}],"title":"overview_polyline","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/overview_polyline","url":"\/documentation\/mapsindoors\/mproute\/overview_polyline","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"overview_polyline"},{"text":": ","kind":"text"},{"text":"MPEncodedPolyline","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPEncodedPolyline"},{"text":"?","kind":"text"}],"required":true},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute":{"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","title":"MPRoute","type":"topic","url":"\/documentation\/mapsindoors\/mproute","abstract":[{"type":"text","text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPRoute"}],"navigatorTitle":[{"text":"MPRoute","kind":"identifier"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPEncodedPolyline":{"url":"\/documentation\/mapsindoors\/mpencodedpolyline","title":"MPEncodedPolyline","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPEncodedPolyline"}],"abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPEncodedPolyline","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPEncodedPolyline"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"overview_polyline","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"overview_polyline"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<MPEncodedPolyline>","preciseIdentifier":"c:Qo@M@MapsIndoors@objc(pl)MPEncodedPolyline"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"overview_polyline"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/title","op":"replace","value":"MPDirectionsService"},{"value":[{"text":"MPDirectionsService","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/fragments","op":"replace"},{"value":"overview_polyline","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1overview_polyline\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1overview_polyline\/fragments","value":[{"text":"overview_polyline","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/title","value":"MPRoute","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/fragments","value":[{"kind":"identifier","text":"MPRoute"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEncodedPolyline\/title","value":"MPEncodedPolyline"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPEncodedPolyline\/fragments","value":[{"text":"MPEncodedPolyline","kind":"identifier"}]}]}]}