{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/restrictions"},"metadata":{"title":"restrictions","roleHeading":"Instance Property","navigatorTitle":[{"text":"restrictions","kind":"identifier"}],"externalID":"c:@M@MapsIndoors@objc(pl)MPRoute(py)restrictions","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restrictions","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"required":true,"modules":[{"name":"MapsIndoors"}],"symbolKind":"property"},"abstract":[{"text":"The restrictions that apply for the route. May be empty.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"restrictions"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"] { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mproute\/restrictions"]},{"paths":["\/documentation\/mapsindoors\/mproute\/restrictions"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPDirectionsService":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPDirectionsService","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MPDirectionsService"}],"url":"\/documentation\/mapsindoors\/mpdirectionsservice","kind":"symbol","title":"MPDirectionsService","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute":{"role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute","kind":"symbol","title":"MPRoute","url":"\/documentation\/mapsindoors\/mproute","type":"topic","abstract":[{"text":"The route model contains the route components: The start and end point, the overall route distance, the duration using the given travel mode(s), the actual route components (legs and steps) containing the route geometry and actions (shifts, turns, climbs etc.) performed to get to the destination point. Typically this object is not manually instantiated, but returns as a result from the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPDirectionsService","type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MPRoute"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPRoute"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPRoute/restrictions":{"navigatorTitle":[{"text":"restrictions","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The restrictions that apply for the route. May be empty."}],"title":"restrictions","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"restrictions"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"url":"\/documentation\/mapsindoors\/mproute\/restrictions","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPRoute\/restrictions"},"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"restrictions","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"restrictions"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"restrictions","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"MPDirectionsService","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPDirectionsService\/fragments","value":[{"text":"MPDirectionsService","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/title","value":"MPRoute","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute\/fragments","value":[{"kind":"identifier","text":"MPRoute"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1restrictions\/title","value":"restrictions"},{"op":"replace","value":[{"text":"restrictions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPRoute~1restrictions\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}