{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"floors"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"text":"MPFloor","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPFloor","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"required":true,"navigatorTitle":[{"text":"floors","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"MapsIndoors"}],"role":"symbol","title":"floors","externalID":"c:@M@MapsIndoors@objc(pl)MPBuilding(py)floors"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"floors","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"MPFloor","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPFloor","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor"},{"text":"]? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/floors"},"variants":[{"paths":["\/documentation\/mapsindoors\/mpbuilding\/floors"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpbuilding\/floors"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The Building floors. Since this is a Dictionary the order of floors is not guaranteed."}],"references":{"MapsPeopleWhite.png":{"alt":null,"identifier":"MapsPeopleWhite.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/MapsPeopleWhite.png"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding":{"url":"\/documentation\/mapsindoors\/mpbuilding","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPBuilding","kind":"identifier"}],"abstract":[{"type":"text","text":"Holds relevant data for a single building, and the buildings floor levels."}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MPBuilding","kind":"identifier"}],"title":"MPBuilding","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding/floors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/floors","kind":"symbol","required":true,"url":"\/documentation\/mapsindoors\/mpbuilding\/floors","type":"topic","navigatorTitle":[{"text":"floors","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The Building floors. Since this is a Dictionary the order of floors is not guaranteed."}],"title":"floors","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"floors","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"MPFloor","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPFloor"},{"kind":"text","text":"]?"}]},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPFloor":{"url":"\/documentation\/mapsindoors\/mpfloor","navigatorTitle":[{"text":"MPFloor","kind":"identifier"}],"abstract":[{"type":"text","text":"Floor data model. Holds the floor geometry, display name, z-index and id of the building it belongs to."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPFloor","title":"MPFloor","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloor"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"floors"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"floors","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id<MPFloor>>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"floors","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/title","value":"MPBuilding","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/fragments","value":[{"kind":"identifier","text":"MPBuilding"}]},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1floors\/title","value":"floors","op":"replace"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1floors\/fragments","op":"replace","value":[{"text":"floors","kind":"identifier"}]},{"value":"MPFloor","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor\/title","op":"replace"},{"value":[{"text":"MPFloor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPFloor\/fragments","op":"replace"}]}]}