{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpbuilding\/properties"]},{"paths":["\/documentation\/mapsindoors\/mpbuilding\/properties"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","required":true,"title":"properties","modules":[{"name":"MapsIndoors"}],"symbolKind":"property","externalID":"c:@M@MapsIndoors@objc(pl)MPBuilding(py)properties","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"properties"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"MPLocationField","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationField"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"properties","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"properties"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationField","text":"MPLocationField","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationField"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/properties"},"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding"]]},"abstract":[{"text":"Dictionary of custom properties of the Building.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPLocationField":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"MPLocationField","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mplocationfield","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MPLocationField","kind":"identifier"}],"title":"MPLocationField","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPLocationField"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding/properties":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"properties","kind":"identifier"}],"type":"topic","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/properties","abstract":[{"text":"Dictionary of custom properties of the Building.","type":"text"}],"url":"\/documentation\/mapsindoors\/mpbuilding\/properties","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"properties","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"text":"MPLocationField","kind":"typeIdentifier","preciseIdentifier":"c:@M@MapsIndoors@objc(pl)MPLocationField"},{"kind":"text","text":"]"}],"title":"properties"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","abstract":[{"text":"MapsIndoors enables you to show indoor maps in your apps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app."}],"url":"\/documentation\/mapsindoors","kind":"symbol","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"role":"collection","title":"MapsIndoors","type":"topic"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding":{"kind":"symbol","abstract":[{"type":"text","text":"Holds relevant data for a single building, and the buildings floor levels."}],"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding","navigatorTitle":[{"text":"MPBuilding","kind":"identifier"}],"type":"topic","title":"MPBuilding","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPBuilding","kind":"identifier"}],"url":"\/documentation\/mapsindoors\/mpbuilding","role":"symbol"},"MapsPeopleWhite.png":{"type":"image","variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"identifier":"MapsPeopleWhite.png","alt":null}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"properties","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"properties","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id<MPLocationField>>"},{"kind":"text","text":" * "},{"text":"properties","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MPLocationField","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationField\/title"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPLocationField\/fragments","value":[{"text":"MPLocationField","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1properties\/title","value":"properties"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1properties\/fragments","op":"replace","value":[{"text":"properties","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/title","value":"MPBuilding"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/fragments","op":"replace","value":[{"kind":"identifier","text":"MPBuilding"}]}]}]}