{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"venueId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"required":true,"roleHeading":"Instance Property","modules":[{"name":"MapsIndoors"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"venueId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"venueId"}],"role":"symbol","symbolKind":"property","title":"venueId","externalID":"c:@M@MapsIndoors@objc(pl)MPBuilding(py)venueId"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/venueId"},"abstract":[{"type":"text","text":"The id of the Venue the Building is part of."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapsindoors\/mpbuilding\/venueid"]},{"paths":["\/documentation\/mapsindoors\/mpbuilding\/venueid"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors","doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors":{"type":"topic","role":"collection","images":[{"type":"icon","identifier":"MapsPeopleWhite.png"}],"kind":"symbol","url":"\/documentation\/mapsindoors","abstract":[{"text":"MapsIndoors iOS SDK v4 can use either Google Maps or Mapbox Maps to show and interact with your indoors maps in an iOS app.","type":"text"}],"title":"MapsIndoors","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding":{"url":"\/documentation\/mapsindoors\/mpbuilding","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MPBuilding","kind":"identifier"}],"abstract":[{"type":"text","text":"Holds relevant data for a single building, and the buildings floor levels."}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MPBuilding","kind":"identifier"}],"title":"MPBuilding","identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding"},"MapsPeopleWhite.png":{"identifier":"MapsPeopleWhite.png","alt":null,"variants":[{"url":"\/images\/MapsPeopleWhite.png","traits":["1x","light"]}],"type":"image"},"doc://com.mapspeople.mapsindoors/documentation/MapsIndoors/MPBuilding/venueId":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"venueId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/mapsindoors\/mpbuilding\/venueid","abstract":[{"type":"text","text":"The id of the Venue the Building is part of."}],"title":"venueId","role":"symbol","navigatorTitle":[{"text":"venueId","kind":"identifier"}],"type":"topic","required":true,"identifier":"doc:\/\/com.mapspeople.mapsindoors\/documentation\/MapsIndoors\/MPBuilding\/venueId"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"venueId"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"venueId"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"venueId"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/title","value":"MPBuilding","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding\/fragments","value":[{"kind":"identifier","text":"MPBuilding"}]},{"value":"venueId","op":"replace","path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1venueId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"venueId"}],"path":"\/references\/doc:~1~1com.mapspeople.mapsindoors~1documentation~1MapsIndoors~1MPBuilding~1venueId\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}