{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"latLng"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationcoordinate3d\/latlng"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationcoordinate3d\/latlng"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D\/latLng","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"latLng"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"title":"latLng","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@S@MPLocationCoordinate3D@FI@latLng","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"latLng"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationCoordinate3D/latLng":{"role":"symbol","title":"latLng","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"latLng"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D\/latLng","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"latLng"}],"url":"\/documentation\/mapsindoors\/mplocationcoordinate3d\/latlng"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationCoordinate3D":{"role":"symbol","title":"MPLocationCoordinate3D","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationCoordinate3D"}],"abstract":[{"type":"text","text":"A structure that contains a coordinate in 3D space: latitude\/longitude and floor."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationCoordinate3D","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationCoordinate3D"}],"url":"\/documentation\/mapsindoors\/mplocationcoordinate3d"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"latLng"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"latLng"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":" "},{"kind":"identifier","text":"latLng"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationCoordinate3D~1latLng\/title","value":"latLng"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationCoordinate3D~1latLng\/fragments","value":[{"kind":"identifier","text":"latLng"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationCoordinate3D\/title","value":"MPLocationCoordinate3D"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationCoordinate3D\/fragments","value":[{"kind":"identifier","text":"MPLocationCoordinate3D"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}