{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplivedatamanagerstate\/closed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplivedatamanagerstate\/closed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/closed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The Closed state is the initial state before any subscriptions has been made in the Live Data Manager. It is also the state for when the Live Data Manager lost the connection or intentionally disconnected the Live Update remote services."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closed"}],"title":"MPLiveDataManagerState.closed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MPLiveDataManagerState@MPLiveDataManagerStateClosed","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerStateClosed"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerState":{"role":"symbol","title":"MPLiveDataManagerState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManagerState"}],"abstract":[{"type":"text","text":"Enumeration of MPLiveDataManager states."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerState"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerstate"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerState/closed":{"role":"symbol","title":"MPLiveDataManagerState.closed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closed"}],"abstract":[{"type":"text","text":"The Closed state is the initial state before any subscriptions has been made in the Live Data Manager. It is also the state for when the Live Data Manager lost the connection or intentionally disconnected the Live Update remote services."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/closed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerStateClosed"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerstate\/closed"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MPLiveDataManagerStateClosed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerStateClosed"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MPLiveDataManagerStateClosed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState\/title","value":"MPLiveDataManagerState"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerState"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState~1closed\/title","value":"MPLiveDataManagerStateClosed"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState~1closed\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerStateClosed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}