{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplivedatamanagerstate\/connecting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplivedatamanagerstate\/connecting"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/connecting","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The Connecting state reflects the process of creating a valid connection with the Live Update remote services."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"title":"MPLiveDataManagerState.connecting","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MPLiveDataManagerState@MPLiveDataManagerStateConnecting","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerStateConnecting"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerState":{"role":"symbol","title":"MPLiveDataManagerState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLiveDataManagerState"}],"abstract":[{"type":"text","text":"Enumeration of MPLiveDataManager states."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerState"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerstate"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/MPLiveDataManagerState/connecting":{"role":"symbol","title":"MPLiveDataManagerState.connecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"abstract":[{"type":"text","text":"The Connecting state reflects the process of creating a valid connection with the Live Update remote services."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLiveDataManagerState\/connecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLiveDataManagerStateConnecting"}],"url":"\/documentation\/mapsindoors\/mplivedatamanagerstate\/connecting"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MPLiveDataManagerStateConnecting"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerStateConnecting"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MPLiveDataManagerStateConnecting"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState\/title","value":"MPLiveDataManagerState"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerState"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState~1connecting\/title","value":"MPLiveDataManagerStateConnecting"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLiveDataManagerState~1connecting\/fragments","value":[{"kind":"identifier","text":"MPLiveDataManagerStateConnecting"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}