{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationsReady"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mplocationservicedelegate\/locationsready()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mplocationservicedelegate\/locationsready()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationServiceDelegate\/locationsReady()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This method on the delegate is invoked when the Locations in the current"},{"type":"text","text":" "},{"type":"text","text":"Solution are all loaded and ready to be worked with, e.g. search in them."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"locationsReady"}],"role":"symbol","title":"locationsReady()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationsReady"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:objc(pl)MPLocationServiceDelegate(im)locationsReady","required":true,"modules":[{"name":"MapsIndoors"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationServiceDelegate"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPLocationServiceDelegate/locationsReady()":{"navigatorTitle":[{"kind":"identifier","text":"locationsReady"}],"role":"symbol","title":"locationsReady()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationsReady"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This method on the delegate is invoked when the Locations in the current"},{"type":"text","text":" "},{"type":"text","text":"Solution are all loaded and ready to be worked with, e.g. search in them."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationServiceDelegate\/locationsReady()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mapsindoors\/mplocationservicedelegate\/locationsready()"},"doc://MapsIndoors/documentation/MapsIndoors/MPLocationServiceDelegate":{"role":"symbol","title":"MPLocationServiceDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPLocationServiceDelegate"}],"abstract":[{"type":"text","text":"This delegate informs about the status of loading the Locations of the current"},{"type":"text","text":" "},{"type":"text","text":"Solution."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPLocationServiceDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPLocationServiceDelegate"}],"url":"\/documentation\/mapsindoors\/mplocationservicedelegate"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"locationsReady"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationsReady"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"locationsReady"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationServiceDelegate~1locationsReady()\/title","value":"locationsReady"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationServiceDelegate~1locationsReady()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationsReady"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationServiceDelegate\/title","value":"MPLocationServiceDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPLocationServiceDelegate\/fragments","value":[{"kind":"identifier","text":"MPLocationServiceDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}