{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"aliases"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpfloor-swift.class\/aliases"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpfloor-swift.class\/aliases"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class\/aliases","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Floor aliases"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"aliases"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"title":"aliases","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPFloor(py)aliases","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"aliases"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPFloor-swift.class":{"role":"symbol","title":"MPFloor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloor"}],"abstract":[{"type":"text","text":"Floor data model. Holds the floor geometry, display name, z-index and id of the building it belongs to."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPFloor"}],"url":"\/documentation\/mapsindoors\/mpfloor-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloor-swift.class/aliases":{"role":"symbol","title":"aliases","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"aliases"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Floor aliases"}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class\/aliases","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"aliases"}],"url":"\/documentation\/mapsindoors\/mpfloor-swift.class\/aliases"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"aliases"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"aliases"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<NSString *><Optional>","preciseIdentifier":"c:Q$objc(cs)NSArrayobjc(pl)Optional"},{"kind":"text","text":" * "},{"kind":"identifier","text":"aliases"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class\/title","value":"MPFloor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class\/fragments","value":[{"kind":"identifier","text":"MPFloor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class~1aliases\/title","value":"aliases"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class~1aliases\/fragments","value":[{"kind":"identifier","text":"aliases"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}