{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpfloor-swift.class\/style"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpfloor-swift.class\/style"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class\/style","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Floor layer style, if any."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"style","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MPFloor(py)style","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"style"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPFloor-swift.class/style":{"role":"symbol","title":"style","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Floor layer style, if any."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class\/style","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"style"}],"url":"\/documentation\/mapsindoors\/mpfloor-swift.class\/style"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloor-swift.class":{"role":"symbol","title":"MPFloor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloor"}],"abstract":[{"type":"text","text":"Floor data model. Holds the floor geometry, display name, z-index and id of the building it belongs to."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPFloor"}],"url":"\/documentation\/mapsindoors\/mpfloor-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"style"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"style"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString<Optional>","preciseIdentifier":"c:Q$objc(cs)NSStringobjc(pl)Optional"},{"kind":"text","text":" *"},{"kind":"identifier","text":"style"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class~1style\/title","value":"style"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class~1style\/fragments","value":[{"kind":"identifier","text":"style"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class\/title","value":"MPFloor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class\/fragments","value":[{"kind":"identifier","text":"MPFloor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}