{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileLayer"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"GMSTileLayer","preciseIdentifier":"c:objc(cs)GMSTileLayer"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/mpfloor-swift.class\/tilelayer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/mpfloor-swift.class\/tilelayer"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class\/tileLayer","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"tileLayer"}],"role":"symbol","title":"tileLayer","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileLayer"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"GMSTileLayer","preciseIdentifier":"c:objc(cs)GMSTileLayer"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"symbolKind":"property","externalID":"c:objc(cs)MPFloor(py)tileLayer","modules":[{"name":"MapsIndoors"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors/MPFloor-swift.class":{"role":"symbol","title":"MPFloor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPFloor"}],"abstract":[{"type":"text","text":"Floor data model. Holds the floor geometry, display name, z-index and id of the building it belongs to."}],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MPFloor"}],"url":"\/documentation\/mapsindoors\/mpfloor-swift.class"},"doc://MapsIndoors/documentation/MapsIndoors/MPFloor-swift.class/tileLayer":{"deprecated":true,"role":"symbol","title":"tileLayer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileLayer"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"GMSTileLayer","preciseIdentifier":"c:objc(cs)GMSTileLayer"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"Optional","preciseIdentifier":"c:objc(pl)Optional"},{"kind":"text","text":")?"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/MPFloor-swift.class\/tileLayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tileLayer"}],"url":"\/documentation\/mapsindoors\/mpfloor-swift.class\/tilelayer"},"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"tileLayer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"tileLayer"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"GMSTileLayer<Optional>","preciseIdentifier":"c:Q$objc(cs)GMSTileLayerobjc(pl)Optional"},{"kind":"text","text":" *"},{"kind":"identifier","text":"tileLayer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class\/title","value":"MPFloor"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class\/fragments","value":[{"kind":"identifier","text":"MPFloor"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class~1tileLayer\/title","value":"tileLayer"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1MPFloor-swift.class~1tileLayer\/fragments","value":[{"kind":"identifier","text":"tileLayer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}