{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"truck"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mapsindoors\/customfonticon\/truck"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapsindoors\/customfonticon\/truck"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/truck","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"truck"}],"title":"CustomFontIcon.truck","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@CustomFontIcon@truck","modules":[{"name":"MapsIndoors"}],"navigatorTitle":[{"kind":"identifier","text":"truck"}]},"hierarchy":{"paths":[["doc:\/\/MapsIndoors\/documentation\/MapsIndoors","doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon"]]},"references":{"doc://MapsIndoors/documentation/MapsIndoors":{"role":"collection","title":"MapsIndoors","abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors","kind":"symbol","type":"topic","url":"\/documentation\/mapsindoors"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon":{"role":"symbol","title":"CustomFontIcon","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomFontIcon"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomFontIcon"}],"url":"\/documentation\/mapsindoors\/customfonticon"},"doc://MapsIndoors/documentation/MapsIndoors/CustomFontIcon/truck":{"role":"symbol","title":"CustomFontIcon.truck","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"truck"}],"abstract":[],"identifier":"doc:\/\/MapsIndoors\/documentation\/MapsIndoors\/CustomFontIcon\/truck","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"truck"}],"url":"\/documentation\/mapsindoors\/customfonticon\/truck"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"truck"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"truck"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"truck"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon\/title","value":"CustomFontIcon"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon\/fragments","value":[{"kind":"identifier","text":"CustomFontIcon"}]},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1truck\/title","value":"truck"},{"op":"replace","path":"\/references\/doc:~1~1MapsIndoors~1documentation~1MapsIndoors~1CustomFontIcon~1truck\/fragments","value":[{"kind":"identifier","text":"truck"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}